* lesson 39
** a bull
a black bull on green grass
The cows and bull are crossint the street. They're looking for grass.
** a ram
A sheep and a ram five fur.
What gives fur? A sheep and a ram give fur.
Sheep and rams give fur.
** a chicken
The chicken is walking by the house. It's looking for food.
Chickens lay eggs.
What lays eggs? Chickens lay eggs.

** a sheep
In the country graze cows and sheep, but there are no leopards or wolves.
A sheep is a herbivorous animal. It eats grass.
** a cow
The cows and bull are crossing the street. They're looking for grass.
Cows give milk.
A cow is a spotted and herbivorous animal. It eats grass.
A cow also is a herbivorous animal.
a spotted cow
In the country graze cows and sheep, but there are no leopards or wolves.
** a rooster
What sings at dawn? A rooster sings at dawn.
** a rabbit
a grey rabbit on yellow sand
The grey rabbit is hiding behind a tree.
In the winter a rabbit is white. It's invisible in the snow. It doesn't hide.
What hunts rabbits? Hungry wolves hunt rabbits.
The hungry wolf is looking around. He's looking for a rabbit.
** a wolf
A wolf is a carnivorous animal. It eats meat.
The wolf is hunting a deer.
What hunts rabbits? Hungry wolves hunt rabbits.
** a deer
a spotted deer
If a deer is thirsty, it goes to the river.
A deer is a spotted and herbivorous animal.
The hungry wolf is hunting a deer.
The deer is grazing in the forest.
The hungry tiger is hunting a deer.
The spotted leopard chases a yellow deer. It's hunting.
What is spotted and herbivorous? A deer is spotted and herbivorous.
** a lion
If lions sleep, they're not hungry.
The full lion is lying under a tree.
The small, full lion is jumping on the tree. He's playing.
The lion is lying under a tree and eating meat.

** a tiger
a striped tiger
The hungry tiger is hunting a deer.
What is striped and carnivorous? A tiger is striped and carnivorous.

** a leopard
a spotted leopard
The spotted leopard chases a yellow. It's hunting.
A leopard is spotted. It's invisible among the trees.
If a leopard is hungry, it hunts.
A leopard is a carnivorous animal.
In the country graze cows and sheep, but there are no leopards or wolves.

** to graze

to hunt
to give milk
to lay eggs
to give fur
to hide

hungry
full
carnivorous
herbivorous
spotted
striped

a striped tiger
a grey rabbit on yellow sand
a blakc bull on green grass
The spotted leopard chases a yellow deer. It's hunging.
a spotted leopard
a spotted cow

The sheep is standing by the house and eating grass.
The wolf is hunting a deer.
The deer is grazing in the forest.
A wolf is a carnivorous animal. It eats meat.
The lion is lying under a tree and eating meat.
A leopard also is a carnivorous animal.

A cow also is a hervivorous animal.
Cows give milk.
Sheep and rams give fur.
A sheep is a hervivorous animal. It eats grass.
Chickens lay eggs.
The hungry tiger is hunting a deer.

The cows and bull are crossing the street. They're looking for grass.
The rabbit is hiding behind a tree.
The chicken is walking by the house. It's looking for food.
The small, full lion is jumping on the tree. He's playing.
The full lion is sleeping under a tree.
The hungry wolf is looking around. He's looking for a rabbit.

A leopard is spotted. It's invisible among the trees.
If a deer is thirsty, it goes to the river.
If a leopard is hungry, it hunts.
In the country graze cows and sheep, but there are no leopards or  wolves.
In the winter a rabbit is white. It's invisible in the snow. It doesn't hide.
If lions sleep, they're not hungry.

What lays eggs? Chickens lay eggs.
What sings at dawn? A rooster sings at dawn.
What hunts rabbits? Hungry wolves hunt rabbits.
What is spotted and herbivorous? A deer is spotted and herbivorous.
What gives fur? A sheep and a ram give fur.
What is striped and carnivorous? A tiger is striped and carnivorous.

* lesson 40
laundry detergent
detergent
a bucket
a cloth

a washing machine
a mop
an iron
an ironing board
a vacuum cleaner
a dishwasher
a rug
a brush
a soap
order
disorder

to vacuum

to wipe off
to clean
to clean up
to wash 
to iron 
to 

The table is in order.
The table is in disorder.
The room is in order.
The room is in disorder.

A wet cloth is lying on the bucket.
A dry cloth is lying on the floor.
The vacuum cleaner is standing on the rug.
The soap is lying on the shelf under the mirror in the bathroom.
The girl is holding a bucket with water and a cloth. She wants to wash the floor
in the room.
The laundry detergent is standing on the washing machine.

The man is turning on the washing machine.
Grandma washes dishes with her hands. She doesn't have a dishwasher.
The woman washes her clothing with her hands. She doesn't have a washing machine.
The woman is washing the big, dirty window. No one is helping her.
The man is washing his things in the washing machine.
The boy is washing the floor with a mop and a cloth. He's helping his mom.

The kitchen is in order.
The room is in disorder.
The woman isn't washing clothes. She's cleaning up the kitchen.
The man is cleaning up the table.
The boy isn't washing the floor. He's cleaning up the shelf.
The girl is cleaning up the room.

The room is in order - the books are standing on the shelf and the clothes are
lying in the cabinet.
The kitchen is in disorder - dirty dishes are on the table, and the tablecloth
is lying on the floor.
The room is in disorder - books, clothes and toys are lying on the floor.
The bathroom is in disorder - the laundry detergent, soap and towel are lying on
the floor.
The bathroom is in order - the laundry detergent and soap are lying on the
shelf, and the towel is hanging.
The kitchen is in order - clean dishes are standing in the cabinet.

In order to wash the stove, you need detergent.
In order to clean shoes, you need a shoe brush.
In order to wash clothes, you need laundry detergent and a washing machine.
In order to iron pants, you need an iron and an ironing board.
In order to vacuum the rug, you need a vacuum cleaner.
In order to wash the floor, you need a mop and bucket.

The mother is washing the window, and her daughter is washing the floor.
The father is ironing a shirt and talking on the phone.
The boy is vacuuming the rug and smiling.
The woman is ironing a beautiful dress and thinking about a party.
The mother is washing glasses, and her daughter is drying them.
The woman is washing dirty dishes and listening to happy music.

Is the grandmother washing dishes with her hands? Yes, she doesn't have a
dishwasher.
With what is the man cleaning his shoes? He's cleaning them with a shoe brush.
What are the children doing? The children are helping their mom clean up in the
room.
With what is the girl drying the plate? She's drying the plate with a clean
white towel.
With what is the woman washing the floor? She's washing the floor with a mop and
a wet rag.
Is the woman washing clothes with her hands? No, she is washing them in the
washing machine.

