* lesson 33
** Words
*** drapes
drapes	英[dreɪps]
美[dreɪps]
v.	将(衣服、织物等)悬挂，披; 遮盖; 盖住; 装饰; 使(身体部位)放松地搭在…上;
n.	(厚长的) 帘子，帷帘，帷幕;
[词典]	drape 的第三人称单数和复数;
[例句]He pulled the drapes shut, locked the door behind him.
他把帘子拉严，转身把门锁好。
[其他]	原型： drape

 a ceiling
 a fireplace
***  blinds

blinds	英[blaɪndz]
美[blaɪndz]
n.	窗帘; (尤指) 卷帘; 用以蒙蔽人的言行; 借口; 托词; 幌子;
v.	使变瞎; 使失明; 使眼花; 使目眩; 使思维混沌; 使失去判断力;
[词典]	blind 的第三人称单数和复数;
[例句]Mother was lying on her bed, with the blinds drawn.
母亲正躺在床上，百叶窗已经拉了下来。
[其他]	原型： blind
*** curtains 
curtains	英[ˈkɜːtnz]
美[ˈkɜːrtnz]
n.	窗帘; 帘; 幔; (遮隔房间的) 帷幔; 床帷; (舞台上的) 幕，幕布，帷幕;
[词典]	curtain 的复数;
[例句]Her bedroom curtains were drawn.
她卧室的窗帘拉上了。
[其他]	原型： curtain

 a floor
 a balcony

 to look for
 to hang
 to fit
 to stand
 to find
 to lie

 bed sheets
 a chandelier
 a floor lamp
 a pillow
 a blanket
 a rug

 the other
 none
 outside
 this
 all
 inside

 In the room to the right of the bed stands a beautiful floor lamp.

 This rug doesn't hang on the wall. It lies on the ground.

 On the window in the living room hang beautiful, green drapes.

 To the right of the bed stands a lamp, not a television.

 On the fireplace stands a clock, not a computer.

 On the ceiling hangs a beautiful, valuable, big chandelier.

 A big, white, soft pillow is lying on the floor.

 A girl is standing on the balcony. She is looking at the tall buildings.

 In front of the bed on the floor lies a soft rug.

 A soft blanket is lying on the bed.

 A boy is lying on the wooden floor and looking at the beautiful chandelier on
 the ceiling.

 A woman is bringing clean bed sheets to the room.

 On all of the windows hang blinds.

 All of the blinds on the windows are closed.

 On this window hang blinds, but on the other - curtains.

 In this room there's a balcony, but in the other room there's not.

 In all of the expensive hotel rooms  there is a beautiful fireplace.

 This key doesn't fit this door. It is the other key.

 The bag is ourside the closet.

 Inside the house it's warm, but outside it's cold.

 Inside the fireplace it's dirty, but outside it's clean.

 A father and son are sitting at a table outside. They don't see the people who
 are sitting inside.

 The clothes are inside the closet.

 A mother and daughter are sitting at a table inside the cafe. They don't see the people who
 are sitting outside.

 In the room it's hot. No one is sleeping under a blanket.

 In the winter no one opens the balcony.

 None of the brides wears a blue dress.

 All brides wear a white dress to the wedding.

 None of the students in the school wears a red jacket.

 All the students in the school wear blue jackets.

 The student is looking for a book on the shelf.

 The boy and the girl are looking for their younger brother in the room.

 The girl finds a beautiful flower in the grass.

 The woman before the door is looking for the key in her bag.

 The woman finds the key on the floor.

 The boy finds a gift under the pillow.

 The mother is looking for her son outside, but he's inside the house.

 The boy is looking for the towel, but it's hanging in the bathroom.

 The woman is looking for the blanket, but she doesn't find it.

 The man is looking for the pillow, but he doesn't find it.

 The woman finds a key on the floor, but it doesn't fit.

 The student is looking for the book in the bag, but it's lying on the table.

 The woman works in the hotel, so she brings clean bed sheets to the room.

 The cat isn't in the room, so the boy is looking for it in the cabinet.

 In the room it's cold, so the boy is lying under a thick blanket.

 The boy doesn't find money, so he doesn't buy ice cream.

 The book isn't on the table, so the man is looking for it in the cabinet.

 On the ceiling hangs a beautiful chandelier, so the girl is looking at the
 ceiling.

* lesson 34
** words
*** soup
soup	英[suːp]
美[suːp]
n.	汤; 羹;
v.	使振作; 打扮; 竖起;
[例句]She has a knack of landing herself right in the soup.
她老是让自己的处境很尴尬。
[其他]	第三人称单数：soups 复数：soups 现在分词：souping 过去式：souped 过去分
词：souped
***  salad
salad	英[ˈsæləd]
美[ˈsæləd]
n.	(生吃的) 蔬菜色拉，蔬菜沙拉; (拌有肉、鱼、奶酪等的) 混合色拉，混合沙拉; (或生或熟，多拌有蛋黄酱，与面食、豆类等一起食用的) 蔬菜色拉;
[例句]The Grand Hotel did not seem to have changed since her salad days.
从她年少时候到现在，格兰德酒店似乎一直就没有变过。
[其他]	复数：salads
***  cabbage
cabbage	英[ˈkæbɪdʒ]
美[ˈkæbɪdʒ]
n.	甘蓝; 卷心菜; 洋白菜;
[例句]They ate a mash of 2 potatoes, 2 carrots& cabbage
他们吃了由两个土豆、两根胡萝卜和洋白菜做的糊。
[其他]	复数：cabbages
*** mushrooms
mushroom	英[ˈmʌʃrʊm]
美[ˈmʌʃrʊm]
n.	蘑菇; 蕈; 伞菌;
v.	快速生长; 迅速增长; 采蘑菇;
[例句]There are many types of wild mushrooms.
野生蘑菇有很多种。
[其他]	第三人称单数：mushrooms 复数：mushrooms 现在分词：mushrooming 过去式：mushroomed 过去分词：mushroomed
***  mashed potatoes
土豆泥
*** onion
onion	英[ˈʌnjən]
美[ˈʌnjən]
n.	洋葱; 葱头;
[例句]Will you chop an onion up for me?
你能帮我把一个洋葱切碎吗？
[其他]	复数：onions
***  to cook
烹调
*** to boil
沸腾（煮开）
***  to fry
煎
The chef is frying chicken because the man and the woman want fried chicken.
In order to fry chicken, you need a roasting pan.
The woman is frying potatoes because she is making lunch for the family.
What is the chef doing? He's frying a whole chicken.

*** to bring food
The man is asking the waiter to bring appetizers.
All tourists bring with them a compass when they go into the woods.
The waiter brings the change and receipt on a tray.
***  to try 
Mom is preparing tasty food, and dad is trying it.
Mom is baking a pie with onion and egg, and dad is making vegetable soup.
The girl is trying on a white, thin, small-sized blouse without embroidery.
The girl is trying on a red high heels
The man is trying on a blue shirt. It's his size.

***  to bake
烧烤
Does the boy know how to bake pies? No, he doesn't know how to bake pies. He's
still very small.
Does grandma know how to bake tasty pies with cabbage? Yes, grandma knows how to
bake tasty pies.
Does the man know how to bake pies? No, he doesn't know how to bake pies.
The chef bakes tasty pies.
In order to bake pie with egg, you need to fry eggs.

***  fried

fried	英[fraɪd]
美[fraɪd]
v.	油炸; 油煎; 油炒; (被阳光) 灼伤，晒伤;
[词典]	fry 的过去分词和过去式;
[例句]I fried up the beef
我把牛肉煎了一下。
[其他]	原型： fry

The chef is frying chicken because the man and the woman want fried chicken.
For mashed potatoes, you need boiled potatoes, not fried.
The father wants fried potatoes for lunch, but his son wants fresh vegetable
salad.

***  tasty
tasty	英[ˈteɪsti]
美[ˈteɪsti]
adj.	美味的; 可口的; 好吃的; 风骚的，有味道的，性感的(男子用以形容性感女子);
n.	可口的东西; 引人入胜的东西;
[例句]Try this tasty dish for supper with a crispy salad
晚饭就着鲜脆的色拉尝尝这道佳肴。
[其他]	比较级：tastier 最高级：tastiest 复数：tasties

The chef in the café makes tasty soup, so many people go to the café.
The chef bakes tasty pies.
In order to prepare tasty vegetabls soup, you need fresh vegetables.
Does grandma know how to bake tasty pies with cabbage? Yes, grandma knows how to
bake tasty pies.

***  boiled

boiled	英[bɔɪld]
美[bɔɪld]
v.	(使) 沸腾; 煮沸; 烧开; (把壶、锅等) 里面的水烧开; 用沸水煮(或烫洗); 被煮(或烫洗);
[词典]	boil 的过去分词和过去式;
[例句]The milk has boiled over.
牛奶煮沸了，都溢出来了。
[其他]	原型： boil

The chef is boiling cabbage in the pot.
Dad is making mashed potatoes from boiled potatoes.
For mashed potatoes, you need boiled potatoes, not fried.
***  hot
hot	英[hɒt]
美[hɑːt]
adj.	温度高的; 热的; 觉得闷(或燥、湿)热; 使人感到热的;
v.	（变，加） 热; 把……加温; （使） 激动起来;
[例句]When the oil is hot, add the sliced onion
油热了后，放入切好的洋葱。
[其他]	比较级：hotter 最高级：hottest 第三人称单数：hots 现在分词：hotting 过去
式：hotted 过去分词：hotted

In the south it's hot.
People swim in the sea in the south, because in the south the sea is warm.
The children love hot pies with potatoes and milk.

***  cold
cold	英[kəʊld]
美[koʊld]
adj.	寒冷的; 冷的; 未热过的; 已凉的; 冷却的; 冷漠的; 不友好的;
n.	冷; 寒冷; (尤指) 低气温; 感冒; 伤风; 着凉;
adv.	突然; 完全; 毫无准备地;
[例句]Rinse the vegetables under cold running water
用凉的自来水清洗这些蔬菜。
[其他]	比较级：colder 最高级：coldest 复数：colds

The boy doesn't drink warm milk. He wants cold juice.
The cat is drinking cold milk.
In the north it's cold.
Polar bears swim in the sea in the north, because in the north the sea is cold.

*** fresh
fresh	英[freʃ]
美[freʃ]
adj.	新鲜的; 新产的; 刚摘的; 新近的; 新近出现的; 新近体验的; 新的; 不同的;
adv.	刚刚，才，最新地;
[例句]He asked Strathclyde police, which carried out the original investigation, to make fresh inquiries
他要求原来负责案子的斯特拉斯克莱德警方展开新一轮的调查。
[其他]	比较级：fresher 最高级：freshest

fresh vegetables
fresh onion
In order to prepare tasty vegetable soup, you need fresh vegetables.
For salad you need fresh vegetables.
The father wants fried potatoes for lunch, but his son wants fresh vegetable salad.

***  pie with potato 
土豆派
The children love hot pies with potatoes and milk.

 pie with onion and egg
Mom is baking a pie with onion and egg, and dad is making vegetable soup.

 pie with meat
The man is ordering a pie with meat in the café. 
The children love pies with meat, so their mom is baking pies with meat.

 pie
 pie with cabbage
 pie with mushrooms
*** appetizers
appetizers
英[ˈæpɪtaɪzəz]
美[ˈæpəˌtaɪzərz]
n.	(餐前的) 开胃品，开胃饮料;
[词典]	appetizer 的复数;
[例句]As I was looking at the appetizers, I spotted one of my favorite dishes – crab cakes!
当我正在看有没有什么好菜，发现了一个我的最爱&蟹饼！
[其他]	原型： appetizer

The man is asking the waiter to bring appetizers.
At the bar they sell drinks and appetizers.

***  a café
café	
网络	咖啡馆; 咖啡屋; 小餐馆; 咖啡室; 咖啡厅;
[例句]我们在最不起眼的酒吧和咖啡馆找到了最可口、最具创意的肉菜饭和餐前小吃。
We found the tastiest and most imaginative paella and tapas in the most
unprepossessing bars and caf é s.
The man is ordering a pie with meat in the café.
The chef in the café makes tasty soup, so many people go to the café.
***  a bar
bar	英[bɑː(r)]
美[bɑːr]
n.	酒吧; (出售饮料等的) 柜台; (专售某类饮食的) 小吃店，小馆子;
v.	(用铁条或木条) 封，堵; 阻挡; 拦住; 禁止，阻止(某人做某事);
prep.	除…外;
[例句]I'll see you in the bar later
一会儿酒吧见。
[其他]	第三人称单数：bars 复数：bars 现在分词：barring 过去式：barred 过去分词：
barred
***  strong drinks
The men come to the bar to drink strong drinks.
The child doesn't drink strong drinks, his mom gives him water with lemon.
The man and the woman are sitting at the dark bar and drinking strong drinks.

 drinks
 milk

 fresh cabbage
 mushroom soup
 fresh onion
 vegetable salad
 fried onion
 boiled cabbage

 The mother is feeding her son mashed potatoes.
 The woman is eating vegetable salad for breakfast.
 The children don't love onion.
 The cat is drinking cold milk.
 The children love hot pies with potatoes and milk.
 The boy doesn't drink warm milk. He wants cold juice.

 Dad is making mashed potatoes from boiled potatoes.
 The chef is boiling cabbage in the pot.
 The man is ordering a pie with meat in the café.
 Mom is preparing tasty food, and dad is trying it.
 The mother is making vegetable soup for her children.
 The chef bakes tasty pies.

 The chef in the café makes tasty soup, so many people go to the café.
 The children love pies with meat, so their mom is baking pies with meat.
 The father wants fried potatoes for lunch, but his son wants fresh vegetable salad.
 The woman is frying potatoes because she's making lunch for the family.
 Mom is baking a pie with onion and egg, and dad is making vegetable soup.
 The chef is frying chicken because the man and the woman want fried chicken.

 The man and the woman are sitting in the dark bar and drinking strong drinks.
 The child doesn't drink strong drinks. His mom gives him water with lemon.
 Men come to the bar to drink strong drinks.
 The women are drinking wine at the bar.
 The man is asking the waiter to bring appetizers.
 At the bar they sell drinks and appetizers.

 For salad you need fresh vegetables.
 In order to prepare tasty vegetable soup, you need fresh vegetables.
 In order to fry chicken, you need a roasting pan.
 For mashed potatoes, you need boiled potatoes, not fried.
 For mushroom soup you need mushrooms, not meet.
 In order to bake pie with egg, you need to fry eggs.

 Does grandma know how to bake tasty pies with cabbage? Yes, grandma knows how to
 bake tasty pies.
 Does the man know how to bake pies? No, he doesn't know how to bake 
 pies.
 Does the girl know how to prepare vegetable salad? Yes, she prepares vegetable
 salad well.
 Does the boy know how to fry potatoes? No, he doesn't know how to fry potatoes.
 He's still very small.
 Does mom know how to make tasty soup? Yes, mom knows how to make tasty soups.
 Does the chef know how to cook? Yes, he prepares very tasty food.



* lesson 35
** words
*** a coat
coat	英[kəʊt]
美[koʊt]
n.	外套; 外衣; 大衣; (套装的) 上装; 动物皮毛;
v.	给…涂上一层; (用…) 覆盖;
[例句]He turned off the television, put on his coat and walked out.
他关掉电视，穿上外套，出门了。
[其他]	第三人称单数：coats 复数：coats 现在分词：coating 过去式：coated 过去分
词：coated
a light coat
a large-sized coat
a small-sized coat
a coat my size

In order to sew a coat, you need fabric.
The salesperson is showing the woman a coat.
The woman is giving the salesperson a tight coat - it's not her size.

*** a sweater
sweater	英[ˈswetə(r)]
美[ˈswetər]
n.	毛衣，线衣(英国英语指套头无扣的; 美国英语可指开襟有扣的);
[例句]She wore a thick tartan skirt and a red cashmere sweater.
她穿了一条厚厚的格子呢裙和一件红色羊绒衫。
[其他]	复数：sweaters

The grandmother is knitting a warm, grey sweater for her grandson.

*** a blouse
blouse	英[blaʊz]
美[blaʊs]
n.	(女式) 短上衣，衬衫;
[例句]That morning I had put on a pair of black slacks and a long-sleeved black blouse.
那天早上，我穿了一条宽松的黑裤子和一件长袖黑衬衫。
[其他]	复数：blouses

Do all men like women in white blouses with embroidery?
Yes, all men like such women.
The girl is trying on a white, thin, small-sized blouse with embroidery.

*** tights
tights	英[taɪts]
美[taɪts]
n.	(女用) 连裤袜，紧身裤; (尤指舞蹈演员穿的) 紧身衣裤;
[例句]He was horrified at the thought of his son prancing about on a stage in tights.
一想到儿子身穿紧身衣在舞台上神气活现地走来走去，他就感到震惊。
The woman takes off light, grey tights.
In the west women wear tight pants.
The girl is wearing a short, tight, small-sized skirt.
The woman is giving the salesperson a tight coat - it's not her size.

*** socks
sock	英[sɒk]
美[sɑːk]
n.	短袜; (尤指用拳头) 猛击，重击;
v.	猛击; 狠打;
[例句]Come on, lads. Sock it to 'em.
来吧，伙计们，让他们开开眼。
[其他]	第三人称单数：socks 复数：socks 现在分词：socking 过去式：socked
The man puts on warm, white socks.
Do all  grandmothers like to sew warm socks for their grandchildren?
Yes, they like it.
The boy wants to knit socks, but he doesn't know how.


*** a tank top
anktop	
网络	背心; 坦克背心; 小可爱背心; 吊带;

vest 是“背心、汗衫来、内衣”的意思。 
tank top 是“紧身短背心”的意思。

一. “tank top”,就是中文里所讲的背心,也就是那种无袖的上衣。

二. “tank top“即无袖的上衣，还没有源到吊带衫那么露的。

三.句子 brown knee-length skirt, orange tank top, ponytail（棕色膝盖长度的裙子,
橙色无袖的上衣, 扎着马尾辫）。

The boy in the white tank top is sitting on the bench.
There is no embroidery on the tank top.
*** vest
vest	英[vest]
美[vest]
n.	(衬衣等里面贴身穿的) 背心，汗衫; 坎肩; (外面穿的) 背心;
v.	给予; 授予某人某种权力; (指财产等) 归属;
[例句]All authority was vested in the woman, who discharged every kind of public duty
女性被赋予了所有权力，履行所有公共职责。
[其他]	第三人称单数：vests 复数：vests 现在分词：vesting 过去式：vested

*** a warm sweater
sweater	英[ˈswetə(r)]
美[ˈswetər]
n.	毛衣，线衣(英国英语指套头无扣的; 美国英语可指开襟有扣的);
[例句]She wore a thick tartan skirt and a red cashmere sweater.
她穿了一条厚厚的格子呢裙和一件红色羊绒衫。
[其他]	复数：sweaters


*** a long skirt
skirt	英[skɜːt]
美[skɜːrt]
n.	女裙; (连衣裙、外衣等的) 下摆; (车辆或机器基座的) 挡板，裙板;
v.	环绕…的四周; 位于…的边缘; 沿…的边缘走; 绕开，回避(话题);
[例句]We raced across a large field that skirted the slope of a hill.
我们从山坡下的一大片田地里飞奔而过。
[其他]	第三人称单数：skirts 复数：skirts 现在分词：skirting 过去式：skirted

a short skirt
a light coat
loose pants 
tight pants

The girl is wearing a short, tight, small-sized skirt.

*** to embroider 
embroider	英[ɪmˈbrɔɪdə(r)]
美[ɪmˈbrɔɪdər]
v.	刺绣; 加以渲染(或润色); 添枝加叶;
[例句]The collar was embroidered with very small red strawberries
衣领上绣着非常小的红色草莓。
[其他]	第三人称单数：embroiders 现在分词：embroidering 过去式：embroidered 过去
分词：embroidered

In order to embroider, you need a needle and thread.
The woman is embroidering a red flower on white fabric.
The girl gets a needle with red thread. She wants to embroider.
*** to cut 
cut	英[kʌt]
美[kʌt]
v.	切; 割; 割破; 划破; (用刀等从某物上) 切下，割下; (用刀等将某物) 切成，割成;
n.	伤口; 划口; (锋利物留下的) 开口，破口; (数量、尺寸、供应等的) 削减，减少，缩减;
[例句]Mrs. Haines stood nearby, holding scissors to cut a ribbon
海恩斯夫人站在旁边，手持剪刀准备剪彩。
[其他]	第三人称单数：cuts 现在分词：cutting 过去式：cut 过去分词：cut

The girl is holding a scissors in her right hand, and fabric in her left. She
wants to cut.
In order to cut thread, you need scissors.
The boy is cutting a piece of paper in half.
*** to put on 
穿上


*** to take off
脱下，不及物时飞机起飞

*** to sew
sew	英[səʊ]
美[soʊ]
v.	缝; 做针线活; 缝制; 缝补; 缝上;
[例句]The hand was preserved in ice by neighbours and sewn back on in hospital
手被邻居用冰块保存起来了，在医院又被缝合好了。
[其他]	第三人称单数：sews 现在分词：sewing 过去式：sewed 过去分词：sewn

*** to knit
knit	英[nɪt]
美[nɪt]
v.	编织; 针织; 机织; 织平针; (使) 紧密结合，严密，紧凑;
n.	编织的衣服; 针织衫;
[例句]I had endless hours to knit and sew
我整天无休止地编织缝纫。
[其他]	第三人称单数：knits 复数：knits 现在分词：knitting 过去式：knitted 过去
分词：knitted

*** thread
thread	英[θred]
美[θred]
n.	(棉、毛、丝等的) 线; 线索; 脉络; 思绪; 思路; 贯穿的主线; 线状物; 细细的一条;
v.	穿(针); 纫(针); 穿过; (使) 穿过; 通过; 穿行; 穿成串; 串在一起;
[例句]This time I'll do it properly with a needle and thread.
这次，我要用针线将它缝好。
[其他]	第三人称单数：threads 复数：threads 现在分词：threading 过去式：threaded

*** fabric
fabric	英[ˈfæbrɪk]
美[ˈfæbrɪk]
n.	织物; 布料; (社会、机构等的) 结构; (建筑物的)结构(如墙、地面、屋顶) ;
[例句]Whatever your colour scheme, there's a fabric to match.
无论什么样的色彩图案，都有与之相配的织物。
[其他]	复数：fabrics

embroidery

*** scissors
scissors	英[ˈsɪzəz]
美[ˈsɪzərz]
n.	剪刀;
v.	剪断; 删除;
[词典]	scissor 的第三人称单数;
[例句]He told me to get some scissors
他让我去拿把剪刀。
[其他]	原型： scissor  复数：scissors

*** a needle
needle	英[ˈniːdl]
美[ˈniːdl]
n.	针; 缝衣针; 编织针; 注射针; 针头;
v.	刺激; 故意招惹; (尤指) 不断地数落;
[例句]She took the needle off the record and turned the lights out.
她把唱针从唱片上移开，把灯也关了。
[其他]	复数：needles

a needle and thread

size 
a big size
a small size
a large-sized coat
a coat my size.
a small-sized coat

*** heel
heel	英[hiːl]
美[hiːl]
n.	足跟; 脚后跟; (袜子等的) 后跟; (鞋、靴子等的) 后跟;
v.	给(鞋等)修理后跟; 倾侧; 倾斜;
[例句]He kicked it shut with the heel of his boot.
他用靴子的后跟将它踢上。
[其他]	第三人称单数：heels 复数：heels 现在分词：heeling 过去式：heeled

** text 
women's shoes with a mid heel
women's shoes with a low heel
women's shoes with a high heel
women's shoes without a heel
women's shoes

In order to embroider, you need a needle and thread.
In order to cut thread, you need scissors.
The girl gets a needle with red thread. She wants to embroider.
The woman is holding a needle with black thread in her right hand, and fabric in
her left. She wants to sew.
In order to sew a coat, you need fabric.
The girl is holding scissors in her right hand, and fabric in her left. She
wants to cut.

The woman is embroidering a red flower on white fabric.
The man doesn't know how to sew. His wife sews pants and a jacket for him.
The grandmother is knitting a grey, warm sweater for her grandson.
The woman knows how to sew. She sews pants and a jacket for her husband.
The boy doesn't know how to sew. He sews a red shirt with green thread.
The granddaughter also knows how to knit. She knits a hat for her bear.

The womman in the long dress with the embroidery is entering the restaurant.
The man puts on warm, white socks.
The boy in the white tank top is sitting on the bench.
The woman takes off light, grey tights.
There is no embroidery on the tank top.
The salesperson is showing the woman a coat.

The man is trying on the blue shirt. It's his size.
The girl is wearing a short, tight, small-sized skirt.
The woman is trying on a red, large-sized dress with  beautiful embroidery.
The woman is giving the salesperson a tight coat - it's not her size.
The girl is trying on a white, thin[fn:1], small-sized blouse without embroidery.
The boy is wearing a loose, large-sized shirt.

Men like women in high heels.
The woman is trying on[fn:2] red high heels.
The man is wearing shoes without a heel.
The girl has shoes with a low heel.
The woman is trying on fall boots with a mid heel.
The woman is trying on winter boots with a low heel.

The woman wants to sew a beautiful dress, but doesn't know how.
The girl wants to walk in high heels, but she doesn't know how.
The woman knows how to knit, but doesn't want to.
The man doesn't know how to knit and doesn't want to.
The boy wants to knit socks, but he doesn't know how.
The boy doesn't know how  to embroider, but really wants to.

Do all girls like to sew? Yes, but not all know how.
Do all men like women in white blouses with embroidery? Yes, all men like such
women.
Does the whole family like the clothing that grandma knits? Yes, the whole
family likes this clothing.
Do all women like a dress with embroidery? No, there are women who don't
like this dress.
Do all men like women in high heels? Yes, all men like such women.
Do all grandmothers like to sew warm socks for their grnadchildren? Yes, they
like it.

* lesson 36
a receipt
change
a market
a supermarket
a counter
a cash register

a purchase
produce
chocolate
cake
souvenirs
perfume

to weigh
to help
to wrap
to pick out 
to carry
to give

dark
light
cheap
expensive
rich
poor

whole 
half 
a whole apple
a whole pie
half of a pie
helf of an apple

a bright room
a dark bar
At the market produce is inexpensive, at the supermarket it's expensive.
The woman is buying produce at the market.
a big, bright supermarket.
The man is buying produce at the supermarket.

The girl is picking out chocolate.
The tall man is helping the woman carry her purchase.
The tourists are picking out souvenirs.
The grandmother is helping her granddaughter wrap a gift for her mother.
The woman is picking out perfume.
The salesperson is helping the customer pick out cake.

The woman is carrying her purchase to the car.
The customers are standing in line for the cash register.
an expensive purchase
The salesperson is carrying produce to the counter.
a cheap purchase
The girl is carrying chocolate to the cash register.

The salesperson is weighing apples.
The customer takes the change and receipt from the salesperson.
The salesperson is wrapping a souvenir.
The woman is wrapping a gift for her husband.
The waiter brings the change and receipt on a tray.
The salesperson gives the customer the receipt and change.

A rich woman buys an expensive dress with embroidery, but a poor woman - a cheep
dress with a discount.
A rich man reserves an expensive room in a hotel, but a poor man - a cheap room.
In the small dark room live poor people.
A rich man gives his wife expensive perfume, but a poor man - cheap perfume.
A rich man drives a new, expensive car, but a poor man - an old, cheap car.
In the big bright house live rich people.

The mother gives her son half a glass of juice.
The boy is cutting a piece of paper in half.
What is the salesperson doing? He's weighing half a chicken.
What is the chef doing? He's frying a whole chicken.
What is the boy doing? He's putting half a cake on a plate.
What is the waiter doing? He's carrying a whole cake on a tray.

* lesson 37
** words
*** north
 north	英[nɔːθ]
 美[nɔːrθ]
 n.	北; 北方; 北部; 北部地区; (美国南北战争时与南方作战的) 北部各州;
 adj.	北方的; 向北的; 北部的; 北风的; 北方吹来的;
 adv.	向北; 朝北;
 [例句]In the north the ground becomes very cold as the winter snow and ice covers the ground
 冬天冰雪覆盖大地，北方的地面变得非常寒冷。
 In the north it's cold.
 In the north half the year it is day, and half it is night.
 Polar bears swim in the sea in the north, becaseu in the north the sea is cold.

*** south
 south	英[saʊθ]
 美[saʊθ]
 n.	南; 南方; 南部; 美国南方各州; 美国南方;
 adj.	南方的; 向南的; 南部的; 南风的; 南方吹来的;
 adv.	向南; 朝南;
 [例句]The town lies ten miles to the south of here
 那个小镇位于这里以南 10 英里处。
 In the south it's hot.
 In the south the grass grows all year.
 In the south it rains half the year.
 People swim in the sea in the south, because in the south the sea is warm.

*** east
 east	英[iːst]
 美[iːst]
 n.	东; 东方; 东部; 东边; 亚洲国家，东方国家(尤指中国、日本和印度);
 adj.	东方的; 向东的; 东部的; 东风的; 东方吹来的;
 adv.	向东; 朝东;
 [例句]The principal range runs east to west.
 主体山脉呈东西走向。
 In the east women wear long, dark dresses.
 The ship is going from the east to the west.
 The river flows from the west to the east.
 Where is the ship going? The ship is going from the west to east.


*** west
 west	英[west]
 美[west]
 n.	西; 西方; 西方(与东方国家相对照的欧洲和北美); 美国西部;
 adj.	西方的; 向西的; 西部的; 西风的; 西方吹来的;
 adv.	向西; 朝西;
 [例句]I pushed on towards Flagstaff, a hundred miles to the west
 我继续西行，向 100 英里外的弗拉格斯塔夫进发。

 In the west women wear tight pants.

*** a compass
 compass	英[ˈkʌmpəs]
 美[ˈkʌmpəs]
 n.	罗盘; 罗经; 指南针; 罗盘仪; 圆规; 两脚规; 范围; 范畴; 界限;
 [例句]We had to rely on a compass and a lot of luck to get here.
 我们不得不依靠指南针和不错的运气找到这儿来。
 [其他]	复数：compasses

 The tourist is finding the path in the mountains by his compass.
 All tourists bring with them a compass when they go into the woods.
 The tourist is holding a compass in his right hand, a map in his left.
 The compass needle points north.
 Where does the compass needle point? 
 The compass needle points north.

*** a needle
 needle	英[ˈniːdl]
 美[ˈniːdl]
 n.	针; 缝衣针; 编织针; 注射针; 针头;
 v.	刺激; 故意招惹; (尤指) 不断地数落;
 [例句]She took the needle off the record and turned the lights out.
 她把唱针从唱片上移开，把灯也关了。
 [其他]	复数：needles
*** day
 day	英[deɪ]
 美[deɪ]
 n.	一天; 一日; 白昼; 白天; 工作日; 一天的活动时间;
 [例句]The weather did not help; hot by day, cold at night
 天气也不肯帮忙：白天很热，晚上很冷。
 [其他]	复数：days

 In the north half the year it is day, and half it is night.
 On work days children and parents get up early.

*** night
 night	英[naɪt]
 美[naɪt]
 n.	夜; 夜晚; 晚上，夜晚(夜里就寝前的一段时间); (举行盛事的) 夜晚; …之夜;
 [例句]He didn't sleep a wink all night
 他一夜没合眼。
 [其他]	复数：nights

 At night the moon and the stars are in the sky.
 In the north half the year it is day, and half it is night.
*** the sun
 sun	英[sʌn]
 美[sʌn]
 n.	太阳; 日; 太阳的光和热; 阳光; 日光; 恒星;
 v.	晒太阳;
 [例句]The sun was now high in the southern sky
 太阳正高挂在南边的天空上。
 [其他]	第三人称单数：suns 复数：suns 现在分词：sunning 过去式：sunned 过去分词：
 sunned
 The sun is a star.

*** the moon
 moon	英[muːn]
 美[muːn]
 n.	月球; 月亮; 月相; 卫星;
 v.	以屁股示人(在公共场所进行的恶作剧或侮辱);
 [例句]There will be no moon.
 月亮不会出来了。
 [其他]	第三人称单数：moons 复数：moons 现在分词：mooning 过去式：mooned 过去分
 词：mooned
 At night the moon and the stars are in the sky.

*** sunset
 sunset	英[ˈsʌnset]
 美[ˈsʌnset]
 n.	日落; 傍晚; 晚霞; (法律的) 自动废止期，效力消减期;
 adj.	霞红色的; 浅橘红色的; 衰落的; 最后期的; 定期废止的;
 v.	(使) 定期届满废止;
 [例句]The dance ends at sunset.
 舞会在日落时分结束。
 [其他]	复数：sunsets
 A man and woman are looking at the beautiful sunset.
 At sunset there are red clouds in the sky.


*** sunrise
 sunrise	英[ˈsʌnraɪz]
 美[ˈsʌnraɪz]
 n.	日出; 朝霞;
 [例句]There was a spectacular sunrise yesterday.
 昨天的朝霞很绚烂。
 [其他]	复数：sunrises
 A man and woman are meeting the sunrise on the beach, because it's very
 beautiful.
 Birds get up at sunrise and sing songs.

*** far
 far	英[fɑː(r)]
 美[fɑːr]
 adv.	远; (问到或谈及距离时说)有多远，远(至) ; 久;
 adj.	较远的; (某方向的) 最远的，远端的; 远的; 远方的; 遥远的;
 [例句]I know a nice little Italian restaurant not far from here
 我知道有家不错的意大利小餐馆离这儿不远。
 [其他]	比较级：farther 最高级：farthest
 The tree is far.
 The ship is far from the coast.
 The children don't swim to the ship, because the ship is very far from the
 coast.

*** near
 near	英[nɪə(r)]
 美[nɪr]
 adj.	距离近; 不远; 不久以后; 随后; 接近;
 adv.	距离不远; 在附近; 不久以后; 几乎; 差不多;
 prep.	在…附近; 靠近; 接近; 临近; (用于数词前) 大约，上下;
 [例句]Don't come near me
 别靠近我。
 [其他]	比较级：nearer 最高级：nearest 第三人称单数：nears 现在分词：nearing 过
 去式：neared
 The bench is near.
 In this hotel there are many tourists, because it's near the sea.
 The rock is near the coast.

*** fast
 fast	英[fɑːst]
 美[fæst]
 adj.	快的; 迅速的; 敏捷的; 迅速发生的; 立即发生的; 动作迅速的; 头脑灵活的;
 adv.	快; 快速; 迅速; 不久; 立即; 牢固地; 完全地;
 v.	节食; 禁食; 斋戒;
 [例句]Brindley was known as a very, very fast driver
 众所周知，布林德利是个喜欢飞车的人。
 [其他]	比较级：faster 最高级：fastest 第三人称单数：fasts 现在分词：fasting 过
 去式：fasted 过去分词：fasted

*** slowly
 slowly	英[ˈsləʊli]
 美[ˈsloʊli]
 adv.	慢速地; 缓慢地; 迟缓地;
 [例句]He slowly sat on the seat with a sigh.
 他叹了一口气，慢慢地坐到位子上。
 [其他]	比较级：more slowly 最高级：most slowly
 The big river flows slowly.
 How do yellow leaves fall from the trees? Yellow leaves fall from trees slowly.
 How does the moon wax? The moon waxes slowly.
*** early
 early	英[ˈɜːli]
 美[ˈɜːrli]
 adj.	早期的; 初期的; 早先的; 早到的; 提前的; 提早的;
 adv.	在早期; 在初期; 在开始阶段; 提早; 提前; 先前; 早些时候; …之前;
 [例句]I knew I had to get up early
 我知道我得早起。
 [其他]	比较级：earlier 最高级：earliest
 No one likes to get up early.
 On work days children and parents get up early.

*** late
 late	英[leɪt]
 美[leɪt]
 adj.	接近末期; 在晚年; 迟到; 迟发生; 迟做; 近日暮的; 近深夜的;
 adv.	迟; 晚; 接近末期; 在晚年; 临近日暮; 接近午夜;
 [例句]It was late in the afternoon
 那是下午近黄昏的时候。
 [其他]	比较级：later 最高级：latest
 On weekends everyone gets up late.

 On weekends everyone gets up late.(adv.)

*** to fall
 fall	英[fɔːl]
 美[fɔːl]
 v.	落下; 下落; 掉落; 跌落; 突然倒下; 跌倒; 倒塌; 下垂; 低垂;
 n.	落下; 下落; 跌落; 掉落; (雪、岩石等的) 降落; 发生; 秋天（AmE=autumn）;
 [例句]Totally exhausted, he tore his clothes off and fell into bed
 他疲惫至极，扯下衣服，一头倒在床上。
 [其他]	第三人称单数：falls 现在分词：falling 过去式：fell 过去分词：fallen
 The girl falls and gets up.
 The glass falls on the floor.
 Yellow leaves fall from the trees.
 In the fall how do yellow leaves fall from trees? Yellow leaves fall from trees
 slowly.
 The girl falls on the sand.
 The stars sometimes fall on the earth.
 The moon doesn't fall on the earth.

*** to rise
 rise	英[raɪz]
 美[raɪz]
 n.	(数量或水平的) 增加，提高; 加薪; 工资增长; (重要性、优势、权力等的) 增强;
 v.	上升; 攀升; 提高; 达到较高水平(或位置); 起床; 起立; 站起来; 升起;
 [例句]He watched the smoke rise from his cigarette
 他注视着烟雾从香烟上升起。
 [其他]	第三人称单数：rises 现在分词：rising 过去式：rose 过去分词：risen

*** to flow

 flow	英[fləʊ]
 美[floʊ]
 n.	流; 流动; 持续生产; 不断供应; 滔滔不绝;
 v.	流; 流动; 涌流; 流畅;
 [例句]A stream flowed gently down into the valley
 一条小溪潺潺流进山谷。
 [其他]	第三人称单数：flows 现在分词：flowing 过去式：flowed 过去分词：flowed

 The small river flows fast.
 The big river flows slowly.
 Water flows.
 The river flows from the west to the east.

*** to float

 loat	英[fləʊt]
 美[floʊt]
 v.	浮动; 漂流; 飘动; 飘移; 浮; 漂浮; 使浮动; 使漂流;
 n.	彩车; 鱼漂; 浮子; (学游泳用的) 浮板;
 [例句]Empty things float.
 空的物体会在水中浮起。
 [其他]	第三人称单数：floats 复数：floats 现在分词：floating 过去式：floated 过
 去分词：floated

*** to swim

 swim	英[swɪm]
 美[swɪm]
 v.	游水; 游泳; 游泳(作为娱乐); 游; 游动;
 n.	游泳;
 [例句]She swam the 400 metres medley ten seconds slower than she did in 1980.
 她 400 米混合泳的成绩比其 1980 年慢了 10 秒。
 [其他]	第三人称单数：swims 现在分词：swimming 过去式：swam 过去分词：swum

 The children don't swim to the ship, because the ship is very far from the
 coast.
 People swim in the sea in the south, because in the south the sea is warm.
 Polar bears swim in the sea in the north, because in the north the sea is cold.

*** to grow

 grow	英[ɡrəʊ]
 美[ɡroʊ]
 v.	扩大; 增加; 增强; 长大; 长高; 发育; 成长; (使) 生长;
 [例句]We stop growing at maturity.
 我们成年之后不再长个儿。
 [其他]	第三人称单数：grows 现在分词：growing 过去式：grew 过去分词：grown

 How do mushrooms in the forest grow after rain? Mushrooms in the forest grow
 fast after rain.
 In the south the grass grows all year.
 On the riverbank grows a tall tree.

*** the sky 

 sky	英[skaɪ]
 美[skaɪ]
 n.	天; 天空;
 v.	把(球)击向高空;
 [例句]The sun is already high in the sky.
 已经日上三竿。
 [其他]	第三人称单数：skies 复数：skies 现在分词：skying 过去式：skied 过去分词：
 skied

 There are red clouds in the sky.
 At night the moon and the stars are in the sky.
 A woman is standing on the beach and looking at the blue sky and the white clouds.
 At sunset there are red clouds in the sky.
 After rain there is a rainbow in the sky.

*** stars

 star	英[stɑː(r)]
 美[stɑːr]
 n.	恒星; 星; 星状物; 星形饰物; 星号; (尤指旅馆或餐馆的) 星级;
 v.	主演; 担任主角; 使主演; 由…担任主角; (在文字等旁) 标星号;
 [例句]The night was dark, the stars hidden behind cloud.
 夜很黑，星星都躲在云的后面。
 [其他]	第三人称单数：stars 复数：stars 现在分词：starring 过去式：starred 过去
 分词：starred

 Stars sometimes fall on the earth.
 At night the moon and the stars are in the sky.

*** a rainbow

 rainbow	英[ˈreɪnbəʊ]
 美[ˈreɪnboʊ]
 n.	虹; 彩虹;
 [例句]Oh look, a rainbow!
 看哪，彩虹！
 [其他]	

 After rain there is a rainbow in the sky.

*** a cloud

 cloud	英[klaʊd]
 美[klaʊd]
 n.	云; 云朵; 云状物(如尘雾、烟雾、一群飞行的昆虫); 阴影; 忧郁; 焦虑; 令人忧虑的事;
 v.	使难以理解; 使记不清楚; 使模糊; 显得阴沉(或恐惧、愤怒等); 看起来忧愁(或害怕、愤怒等); (尤指用无关的话题来)混淆，搅混(问题) ;
 [例句]The sky was almost entirely obscured by cloud.
 天空几乎完全被云所遮蔽。
 [其他]	第三人称单数：clouds 复数：clouds 现在分词：clouding 过去式：clouded 过
 去分词：clouded

 At sunset there are red clouds in the sky.
 The woman is standing on the beach and looking at the blue sky and the white
 clouds.

*** a river

 river	英[ˈrɪvə(r)]
 美[ˈrɪvər]
 n.	河; 江; (液体) 涌流;
 [例句]The Chicago River flooded the city's underground tunnel system
 芝加哥河的河水淹没了城市的地下隧道系统。
 [其他]	复数：rivers

 The small river flows fast.
 The big river flows slowly.
 The river flows from the west to the east.
 If a deer is thirsty, it goes to the river.

*** a coast

 coast	英[kəʊst]
 美[koʊst]
 n.	海岸; 海滨;
 v.	(尤指不用动力向山坡下) 滑行，惯性滑行; (不用多少动力) 快速平稳地移动; 不费力地取得成功;
 [例句]Camp sites are usually situated along the coast, close to beaches.
 野营地一般都位于海滨，靠近沙滩。
 [其他]	第三人称单数：coasts 复数：coasts 现在分词：coasting 过去式：coasted 过
 去分词：coasted

 The rock is near the coast.
 The ship is very far from the coast.
 The children don't swim to the ship, because the ship is very far from the
 coast.


 In the north it's cold.
 In the south it's hot.
 In the north there is snow all year.
 In the west women wear tight pants.
 In the south the grass grows all year.
 In the east women wear long, dark dresses.

 The sun is a star.
 At sunset there are red clouds in the sky.
 A man and woman are looking at the beautiful sunset.
 Clouds are covering the sun.
 After rain there is a rainbow in the sky.
 At night the moon and the stars are in the sky.

 The tree is far.
 The rock is near the coast.
 The bench is near.
 In this hotel there are many tourists, because it's near the sea.
 The children don't swim to the ship, because the ship is very far from the
 coast.
 The ship is far from the coast.

 a beach
 A boy is playing in the sand on the beach.
 A woman is standing on the beach and looking at the blue sky and the white clouds.
 On the riverbank grows a tall tree.
 The girl is walking along the beach.
 A man and woman are meeting the sunrise on the beach, because it's very beautiful.

 The woman gets up and goes to take a shower.
 The boy gets up and goes to wash up. 
 On work days children and parents get up early.
 On weekends everyone gets up late.
 No one likes to get up early.
 Birds get up at sunrise and sing songs.

 The moon doesn't fall on the earth.
 The girl falls and gets up.
 Stars sometimes fall on the earth.
 In the fall yellow leaves fall from trees.
 The glass falls on the floor.
 The girl falls on the sand.

 Water flows.
 The big river flows slowly.
 People swim in the sea in the south, because in the south the sea is warm.
 The small river flows fast.
 Polar bears swim in the sea in the north, because in the north the sea is cold.
 The river flows from the west to the east.

 The compass needle points north.
 The tourist is holding a compass needle in his right hand, and a map in his left.
 In the south it rains half the year.
 In the north half the year it is day, and half it is night.
 The tourist is finding the path in the mountains by his compass.
 All tourists bring with them a compass when they go into the woods.

 How do mushrooms in the forest grow after rain? Mushrooms in the forest grow
 fast after rain.
 Where does the compass needle point? The compass needle points north.
 How do yellow leaves fall from trees? Yellow leaves fall from trees slowly.
 How does the moon wax? The moon waxes slowly.
 Where is the ship going? The ship is going from the west to the east.
 Where is the boy looking? He's looking at the stars.

** programmer

*** 提问如何、地点、等 
 How do yellow leaves fall from trees?
 Yellow leaves fall from trees slowly.

 How does the moon wax?
 The moon waxes slowly.

 Where is the ship going? 
 The ship is going from the east to the west.

 Where is the boy looking?
 He's looking at the stars.

 How do mushrooms in the forest grow after rain?
 Mushrooms in the forest grow fast after rain.

*** 时间

**** 星期、日 用 on
On work days children and parents get up early.
On weekends everyone gets up late.
Can you come at 10 a.m. on Monday, April, 24th?

**** at night
At night the moon and the stars are in the sky.
He telephoned again at night.
在某个时间点：at sunrise at sunset
At sunrise there are red cluds in the sky.
Birds get up at sunrise and sing songs.
A man and woman are meeting the sunrise on the beach, because it's very
beautiful.
At mid night

**** in 在某个时段

***** in the morning

***** in the afternoon

***** in the evening
Then I arrived home at six o'clock yesterday evening.

*** on the beach 
A woman is standing on the beach and looking at the blue sky and the white
clouds.

*** in the sand
A boy is playing in the sand on the beach.

*** on the riverbank
On the riverbank grows a tall tree.

*** look at 
He's looking at the stars.
What is the boy looking?

*** 在。。。里，在。。。季节 in 
in the north in the south 
in the sea
in the forest
How do mushrooms in the forest grow after rain?
Mushrooms in the forest grow fast after rain.
The tourist is finding the path in the mountains by his compass.
In the winter a rabbit is white. It's inviable in the snow. It doesn't hide.
In the fall yellow leaves fall from trees.

*** 代词 it。。。如天气等
In the south it's hot.
In the north it's cold.
In the north half the year it is day, and half it is night.
In the south it rains half the year.


* lesson 38
** words
*** a violin
 The musicians are playing old-fashioned music on violins.
 The man is playing music on violin,  and the girl is listening to the music.
 These musicians are playing modern music on a violin and a guitar.
 The young man is playing the violin, and the young woman is listening to the
 music.
 The girl loves music. She plays the violin.
 Are the musicians playing violins or drums? The musicians are playing violins.
*** a guitar
 The musicians are playing modern music on a violin and a guitar.
*** dance
 The girl loves dancing. she loves to dance.
 What do the friends love to do? They love to dance.
*** music
 The musicians are playing modern music on a violin and a guitar.
 These musicians are playing old-fashioned music on violins.
 The young man is playing the violin, and the young woman is listening to the
 music.
 She loves music. She plays the violin.
 During a carnival music plays.
 The woman is washing dirty dishes and listening to the music.
*** film
 These children are friends. They're watching an interesting film about
 old-fashioned clothes on TV.
 Are the friends watching a film or leaving the city? The friends are watching a
 film.
*** a drum
 The boys play the drums.
 The musician also plays the drums.
 Are the musicians playing the violins or drums? The musicians are playing the
 violins.
*** a bouquet
 The bride with the bouquet of white flowers is dancing on the grass.
 At a wedding the bride throws her bouquet of flowers to her friends.
 The bride throws her bouquet, and her friends catch it.
 The bride holds the bouquet of white flowers.
 Does the bride catch or throw the bouquet? The bride throws her
 bouquet.
 Is the woman holding a bouquet of flowers or a wig? The woman is holding a
 bouquet of flowers.
*** candy
 The boy gives the girl candy.
 The boy is happy because his mom gave him candy.
 When are children happy? Children are happy when they're given candy and toys.
 The girl is crying because she has no candy.
*** a mask
 The woman collects masks.
 When do actors wear masks? They wear masks during a spectacle.
*** a carnival costume
 The friends are putting on carnival costumes.
 The man in the carnival costume gives the woman in the old-fashioned dress and
 wig a bouquet of flowers.
*** a wig
 The actors are dressed in old-fashioned dresses and wigs.
 The actor puts on a wig.
 During a carnival people put on old-fashioned dresses and wigs.
 The woman is wearing a wig.
 When do men put on wigs? They put on wigs at a carnival.
*** a carnival
 When do men put on wigs? They put on wigs at a carnival.
 During a carnival people put on old-fashioned dresses and wigs.
 During a carnival music plays.
 In the city is there a carnival or traffic? In the city there is a carnival.
*** to throw
 At a wedding the bride throws her bouquet to her friends.
 The girl throws the ball, and the boy catches the ball.
 The bride throws her bouquet, and her friends catch it.
 Does the bride catch or throws her bouquet? The bride throws her bouquet.
*** to collect
 The man collects phones.
 The woman collects masks.
 The young man collects old-fashioned watches.
 The man collects paintings.
 What does the man collect? He collects paintings.
*** to leave the city
 The family leave the city to relax in nature.
 The friends leave the city to fry meat and drink beer.
*** to celebrate
 The girl invites her classmates to her birthday party.
 The friends are celebrating a holiday.
*** to catch
 The girl throws the ball, and the boy catches the ball.
 Does the bride catch or throw the bouquet? The bride throws the bouquet.
 The bride throws her bouquet, and her friends catch it.
*** to love to do something
 What do the friends love to do? They love to dance.
 The girl loves dancing. She loves to dance.
 The boy loves photography. He loves to photograph his friends.
*** modern
 Is this a modern or an old-fashioned building. This is a modern building.
 The man is in a modern suit, and the woman is in an old-fashioned dress.
 These musicians are playing modern music on a violin and a guitar.

 an old-fashioned cabinet
 a modern clock
 old-fashioned
 a modern cabinet
 an old-fashioned clock

 These girls are peers.
*** a peer 
 These girls are peers. They study in the same grade at the university.
*** a classmate
 These boys are classmates. They study in the same class at school.
 The girl invites her classmates to her birthday party.
 a girlfriend
 These boys are classmates.
 a friend

 These boys are classmates. They study in the same class at school.
 The girl invites her classmates to her birthday party.
 In the store the friends are picking out clothing.
 These children are friends. They're watching an interesting film about
 old-fashioned clothes on TV.
 The friends are celebrating  a holiday.
 These girls are peers. They study in the same grade at the university.

 The friends are putting on carnival costumes.
 The musicians are playing old-fashioned music on violins.
 During a carnival music plays.
 The musician also plays the drums.
 These musicians are playing modern music on a violin and a guitar.
 The boys play the drums.

 The actors are dressed in old-fashioned dresses and wigs.
 The woman with the bouquet of white flowers is dancing on the grass.
 The actor puts on a wig.
 A man and woman are dancing in old-fashioned costumes.
 During a carnival people put on old-fashioned dresses and wigs.
 The woman is wearing a wig.

 The boy gives the girl candy.
 The boy is happy because his mom gave him candy.
 The young man is playing the violin, and the young woman is listening to the
 music.
 The friends leave the city to fry meat and drink beer.
 The girl is crying because she has no candy.
 The family leaves the city to relax in nature.

 At a wedding the bride throws her bouquet to her friends.
 The man in the carnival costume gives the woman in the old-fashioned dress and wig
 a bouquet of flowers.
 The girl throws the ball, and the boy catches the ball.
 The man is in a modern suit, and the woman is in an old-fashioned dress.
 The bride holds a bouquet of white flowers.
 The bride throws her bouquet, and her friends catch it.

 The boy loves photography. He loves to photograph his friends.
 The young man collects old-fashioned watches.
 The girl loves music. She plays the violin.
 The girl loves dancing. She loves to dance.
 The man collects phones.
 The woman collects masks.

 In the city is there a carnival or traffic? In the city there is a carnival.
 Is this a modern or an old-fashioned building. This is a modern building.
 Does the bride catch or throw the bouquet? The bride throws the bouquet.
 Is the woman holding a bouquet of flowers or a wig? The woman is holding a
 bouquet of flowers.
 Are the musicians playing violins or drums? The musicians are playing violins.
 Are the friends watching a film or leaving the city? The friends are watching a
 film.

 When do men put on wigs? They put on wigs at a carnival.
 What do the friends love to do? They love to dance.
 When are children happy? Children are happy when they're given candy and toys.
 When do actors wear masks? They wear masks during a spectacle.
 Where are the friends going? They're leaving the city.
 What does the man collect? He collects paintings.
*** 着衣的表达
**** wear
 When do actors wear masks? They wear masks during a spectacle.
 The woman is wearing a wig.
**** be dressed in 被动式 
 The actors are dressed in old-fashioned dresses and wigs.
**** is in 
 The man is in a modern suit, and the woman is in an old-fashioned dress.
**** put on
 The actor puts on a wig.
 The friends are putting on carnival costumes.
 When do men put on wigs? They put on wigs at a carnival.

*** 衣服
**** dress 裙子
 During a carnival people put on old-fashioned dresses and wigs.
**** suit 西装
 The man is in a modern suit, and the woman is in an old-fashioned dress.
**** costume 服装
 a carnival costumes 
 The man in the carnival costume gives the woman in the old-fashioned dress and
 wig a bouquet of flowers.

**** clothes 衣服
 In order to wash clothes, you need laundry detergent and a washing machine.
 The woman is washing clothes in the washing machine.
 The bathroom is in disorder - the laundry detergent, soap and clothes are lying
 on the floor.
 Is the woman washing clothes with her hands? No, she is washing them in the
 washing machine.
 Is the woman washing clothes? No, she's cleaning up the kitchen.


**** clothing 衣物
 In the store the friends are picking out clothing.
 The woman washes her clothing with her hands. She doesn't have a washing
 machine.

**** skirt

**** shirt

**** coat

**** pants

**** blouse

**** gown

**** 

* lesson 39
** words
*** a bull
 a black bull on green grass
 The cows and bull are crossing the street. They're looking for grass.
*** a ram
 A sheep and a ram give fur.
 What gives fur? A sheep and a ram give fur.
 Sheep and rams give fur.
*** a chicken
 The chicken is walking by the house. It's looking for food.
 Chickens lay eggs.
 What lays eggs? Chickens lay eggs.

*** a sheep
 In the country graze cows and sheep, but there are no leopards or wolves.
 A sheep is a herbivorous animal. It eats grass.
*** a cow
 The cows and bull are crossing the street. They're looking for grass.
 Cows give milk.
 A cow is a spotted and herbivorous animal. It eats grass.
 A cow also is a herbivorous animal.
 a spotted cow
 In the country graze cows and sheep, but there are no leopards or wolves.
*** a rooster
 What sings at dawn? A rooster sings at dawn.
*** a rabbit
 a grey rabbit on yellow sand
 The grey rabbit is hiding behind a tree.
 In the winter a rabbit is white. It's invisible in the snow. It doesn't hide.
 What hunts rabbits? Hungry wolves hunt rabbits.
 The hungry wolf is looking around. He's looking for a rabbit.
*** a wolf
 A wolf is a carnivorous animal. It eats meat.
 The wolf is hunting a deer.
 What hunts rabbits? Hungry wolves hunt rabbits.
*** a deer
 a spotted deer
 If a deer is thirsty, it goes to the river.
 A deer is a spotted and herbivorous animal.
 The hungry wolf is hunting a deer.
 The deer is grazing in the forest.
 The hungry tiger is hunting a deer.
 The spotted leopard chases a yellow deer. It's hunting.
 What is spotted and herbivorous? A deer is spotted and herbivorous.
*** a lion
 If lions sleep, they're not hungry.
 The full lion is lying under a tree.
 The small, full lion is jumping on the tree. He's playing.
 The lion is lying under a tree and eating meat.

*** a tiger
 a striped tiger
 The hungry tiger is hunting a deer.
 What is striped and carnivorous? A tiger is striped and carnivorous.

*** a leopard
 a spotted leopard
 The spotted leopard chases a yellow deer. It's hunting.
 A leopard is spotted. It's invisible among the trees.
 If a leopard is hungry, it hunts.
 A leopard is a carnivorous animal.
 In the country graze cows and sheep, but there are no leopards or wolves.

*** to graze

 The spotted deer is grazing in the forest.
 In the country graze cows and sheep, but there are no leopards or wolves.

** text

to hunt
to give milk
to lay eggs
to give fur
to hide

hungry
full
carnivorous
herbivorous
spotted
striped

a striped tiger
a grey rabbit on yellow sand
a black bull on green grass
The spotted leopard chases a yellow deer. It's hunting.
a spotted leopard
a spotted cow

The sheep is standing by the house and eating grass.
The wolf is hunting a deer.
The deer is grazing in the forest.
A wolf is a carnivorous animal. It eats meat.
The lion is lying under a tree and eating meat.
A leopard also is a carnivorous animal.

A cow also is a herbivorous animal.
Cows give milk.
Sheep and rams give fur.
A sheep is a herbivorous animal. It eats grass.
Chickens lay eggs.
The hungry tiger is hunting a deer.

The cows and bull are crossing the street. They're looking for grass.
The rabbit is hiding behind a tree.
The chicken is walking by the house. It's looking for food.
The small, full lion is jumping on the tree. He's playing.
The full lion is sleeping under a tree.
The hungry wolf is looking around. He's looking for a rabbit.

A leopard is spotted. It's invisible among the trees.
If a deer is thirsty, it goes to the river.
If a leopard is hungry, it hunts.
In the country graze cows and sheep, but there are no leopards or  wolves.
In the winter a rabbit is white. It's invisible in the snow. It doesn't hide.
If lions sleep, they're not hungry.

What lays eggs? Chickens lay eggs.
What sings at dawn? A rooster sings at dawn.
What hunts rabbits? Hungry wolves hunt rabbits.
What is spotted and herbivorous? A deer is spotted and herbivorous.
What gives fur? A sheep and a ram give fur.
What is striped and carnivorous? A tiger is striped and carnivorous.

* lesson 40
** words
*** laundry detergent
 The laundry detergent is standing on the washing machine.
 In order to wash clothes, you need laundry detergent and a washing machine.
 The bathroom is in disorder - the laundry detergent, soap and clothes are lying
 on the floor.
 The bathroom is in order - the laundry detergent and soap are lying on the
 shelf, and the towel is hanging.

*** detergent
 In order to wash the stove, you need detergent.

*** a bucket
 In order to wash the floor, you need a mop and a bucket.
 The girl is holding  a bucket with water and  cloth. She wants to wash the
 floor.
 A wet cloth is lying on the bucket.

 a cloth

 a washing machine
 a mop
 an iron
 an ironing board
 a vacuum cleaner
 a dishwasher
 a rug
 a brush
 a soap
 order
 disorder

*** to vacuum

 The boy is vacuuming the rug and smiling.
 In order to vacuum the rug, you need a vacuum cleaner.


 to wipe off
 to clean
*** to clean up
 The boy isn't washing the floor. He's cleaning up the shelf.
 The man is cleaning up the table.
 What are the children doing? The children are helping their mom clean up the
 room.

*** to iron 

 The father is ironing a shirt and talking on the phone.
 The woman is ironing a beautiful dress and thinking about a party.
 In order to iron pants, you need an iron and an ironing board.

** text

The table is in order.
The table is in disorder.
The room is in order.
The room is in disorder.

A wet cloth is lying on the bucket.
A dry cloth is lying on the floor.
The vacuum cleaner is standing on the rug.
The soap is lying on the shelf under the mirror in the bathroom.
The girl is holding a bucket with water and a cloth. She wants to wash the floor
in the room.
The laundry detergent is standing on the washing machine.

The man is turning on the washing machine.
Grandma washes dishes with her hands. She doesn't have a dishwasher.
The woman washes her clothing with her hands. She doesn't have a washing machine.
The woman is washing the big, dirty window. No one is helping her.
The man is washing his things in the washing machine.
The boy is washing the floor with a mop and a cloth. He's helping his mom.

The kitchen is in order.
The room is in disorder.
The woman isn't washing clothes. She's cleaning up the kitchen.
The man is cleaning up the table.
The boy isn't washing the floor. He's cleaning up the shelf.
The girl is cleaning up the room.

The room is in order - the books are standing on the shelf and the clothes are
lying in the cabinet.
The kitchen is in disorder - dirty dishes are on the table, and the tablecloth
is lying on the floor.
The room is in disorder - books, clothes and toys are lying on the floor.
The bathroom is in disorder - the laundry detergent, soap and towel are lying on
the floor.
The bathroom is in order - the laundry detergent and soap are lying on the
shelf, and the towel is hanging.
The kitchen is in order - clean dishes are standing in the cabinet.

In order to wash the stove, you need detergent.
In order to clean shoes, you need a shoe brush.
In order to wash clothes, you need laundry detergent and a washing machine.
In order to iron pants, you need an iron and an ironing board.
In order to vacuum the rug, you need a vacuum cleaner.
In order to wash the floor, you need a mop and bucket.

The mother is washing the window, and her daughter is washing the floor.
The father is ironing a shirt and talking on the phone.
The boy is vacuuming the rug and smiling.
The woman is ironing a beautiful dress and thinking about a party.
The mother is washing glasses, and her daughter is drying them.
The woman is washing dirty dishes and listening to happy music.

Is the grandmother washing dishes with her hands? Yes, she doesn't have a
dishwasher.
With what is the man cleaning his shoes? He's cleaning them with a shoe brush.
What are the children doing? The children are helping their mom clean up in the
room.
With what is the girl drying the plate? She's drying the plate with a clean
white towel.
With what is the woman washing the floor? She's washing the floor with a mop and
a wet rag.
Is the woman washing clothes with her hands? No, she is washing them in the
washing machine.

* Footnotes

[fn:2]试穿(衣服等);试戴;试用: May I try on the hat? 

[fn:1]thin	英[θɪn]
美[θɪn]
adj.	薄的; 细的; 瘦的; 稀少的; 稀疏的;
adv.	薄薄地;
v.	(掺水等) 使稀薄，使变淡; 变稀疏; 变稀少; (使) 变稀薄，变少;
[例句]A thin cable carries the signal to a computer
一根细电缆将信号传送给一台计算机。
[其他]	比较级：thinner 最高级：thinnest 第三人称单数：thins 现在分词：thinning 过去式：thinned 过去分词：thinned 
