* lesson 38
** a violin
The musicians are playing old-fashioned music on violins.
The man is playing music on violin,  and the girl is listening to the music.
These musicians are playing modern music on a violin and a guitar.
The young man is playing the violin, and the young woman is listening to the
music.
The girl loves music. She plays the violin.
Are the musicians playing violins or drums? The musicians are playing violins.
** a guitar
The musicians are playing modern music on a violin and a guitar.
** dance
The girl loves dancing. she loves to dance.
What do the friends love to do? They love to dance.
** music
The musicians are playing modern music on a violin and a guitar.
These musicians are playing old-fashioned music on violins.
The young man is playing the violin, and the young woman is listening to the
music.
She loves music. She plays the violin.
During a carnival music plays.
The woman is washing dirty dishes and listening to the music.
** film
These children are friends. They're watching an interesting film about
old-fashioned clothes on TV.
Are the friends watching a film or leaving the city? The friends are watching a
film.
** a drum
The boys play the drums.
The musician also plays the drums.
Are the musicians playing the violins or drums? The musicians are playing the
violins.
** a bouquet
The bride with the bouquet of white flowers is dancing on the grass.
At a wedding the bride throws her bouquet of flowers to her friends.
The bride throws her bouquet, and her friends catch it.
The bride holds the bouquet of white flowers.
Does the bride catch or throw the bouquet? The bride throws her
bouquet.
Is the woman holding a bouquet of flowers or a wig? The woman is holding a
bouquet of flowers.
** candy
The boy gives the girl candy.
The boy is happy because his mom gave him candy.
When are children happy? Children are happy when they're given candy and toys.
The girl is crying because she has no candy.
** a mask
The woman collects masks.
When do actors wear masks? They wear masks during a spectacle.
** a carnival costume
The friends are putting on carnival costumes.
The man in the carnival costume gives the woman in the old-fashioned dress and
wig a bouquet of flowers.
** a wig
The actors are dressed in old-fashioned dresses and wigs.
The actor puts on a wig.
During a carnival people put on old-fashioned dresses and wigs.
The woman is wearing a wig.
When do men put on wigs? They put on wigs at a carnival.
** a carnival
When do men put on wigs? They put on wigs at a carnival.
During a carnival people put on old-fashioned dresses and wigs.
During a carnival music plays.
In the city is there a carnival or traffic? In the city there is a carnival.
** to throw
At a wedding the bride throws her bouquet to her friends.
The girl throws the ball, and the boy catches the ball.
The bride throws her bouquet, and her friends catch it.
Does the bride catch or throws her bouquet? The bride throws her bouquet.
** to collect
The man collects phones.
The woman collects masks.
The young man collects old-fashioned watches.
The man collects paintings.
What does the man collect? He collects paintings.
** to leave the city
The family leave the city to relax in nature.
The friends leave the city to fry meat and drink beer.
** to celebrate
The girl invites her classmates to her birthday party.
The friends are celebrating a holiday.
** to catch
The girl throws the ball, and the boy catches the ball.
Does the bride catch or throw the bouquet? The bride throws the bouquet.
The bride throws her bouquet, and her friends catch it.
** to love to do something
What do the friends love to do? They love to dance.
The girl loves dancing. She loves to dance.
The boy loves photography. He loves to photograph his friends.
** modern
Is this a modern or an old-fashioned building. This is a modern building.
The man is in a modern suit, and the woman is in an old-fashioned dress.
These musicians are playing modern music on a violin and a guitar.

an old-fashioned cabinet
a modern clock
old-fashioned
a modern cabinet
an old-fashioned clock

These girls are peers.
** a peer 
These girls are peers. They study in the same grade at the university.
** a classmate
These boys are classmates. They study in the same class at school.
The girl invites her classmates to her birthday party.
a girlfriend
These boys are classmates.
a friend

These boys are classmates. They study in the same class at school.
The girl invites her classmates to her birthday party.
In the store the friends are picking out clothing.
These children are friends. They're watching an interesting film about
old-fashioned clothes on TV.
The friends are celebrating  a holiday.
These girls are peers. They study in the same grade at the university.

The friends are putting on carnival costumes.
The musicians are playing old-fashioned music on violins.
During a carnival music plays.
The musician also plays the drums.
These musicians are playing modern music on a violin and a guitar.
The boys play the drums.

The actors are dressed in old-fashioned dresses and wigs.
The woman with the bouquet of white flowers is dancing on the grass.
The actor puts on a wig.
A man and woman are dancing in old-fashioned costumes.
During a carnival people put on old-fashioned dresses and wigs.
The woman is wearing a wig.

The boy gives the girl candy.
The boy is happy because his mom gave him candy.
The young man is playing the violin, and the young woman is listening to the
music.
The friends leave the city to fry meat and drink beer.
The girl is crying because she has no candy.
The family leaves the city to relax in nature.

At a wedding the bride throws her bouquet to her friends.
The man in the carnival costume gives the woman in the old-fashioned dress and wig
a bouquet of flowers.
The girl throws the ball, and the boy catches the ball.
The man is in a modern suit, and the woman is in an old-fashioned dress.
The bride holds a bouquet of white flowers.
The bride throws her bouquet, and her friends catch it.

The boy loves photography. He loves to photograph his friends.
The young man collects old-fashioned watches.
The girl loves music. She plays the violin.
The girl loves dancing. She loves to dance.
The man collects phones.
The woman collects masks.

In the city is there a carnival or traffic? In the city there is a carnival.
Is this a modern or an old-fashioned building. This is a modern building.
Does the bride catch or throw the bouquet? The bride throws the bouquet.
Is the woman holding a bouquet of flowers or a wig? The woman is holding a
bouquet of flowers.
Are the musicians playing violins or drums? The musicians are playing violins.
Are the friends watching a film or leaving the city? The friends are watching a
film.

When do men put on wigs? They put on wigs at a carnival.
What do the friends love to do? They love to dance.
When are children happy? Children are happy when they're given candy and toys.
When do actors wear masks? They wear masks during a spectacle.
Where are the friends going? They're leaving the city.
What does the man collect? He collects paintings.
** 着衣的表达
*** wear
When do actors wear masks? They wear masks during a spectacle.
The woman is wearing a wig.
*** be dressed in 被动式 
The actors are dressed in old-fashioned dresses and wigs.
*** is in 
The man is in a modern suit, and the woman is in an old-fashioned dress.
*** put on
The actor puts on a wig.
The friends are putting on carnival costumes.
When do men put on wigs? They put on wigs at a carnival.

** 衣服
*** dress 裙子
During a carnival people put on old-fashioned dresses and wigs.
*** suit 西装
The man is in a modern suit, and the woman is in an old-fashioned dress.
*** costume 服装
a varnival costumes 
The man in the carnival costume gives the woman in the old-fashioned dress and
wig a bouquet of flowers.

*** clothes 衣服
In order to wash clothes, you need laundry detergent and a washing machine.
The woman is washing clothes in the washing machine.
The bathroom is in disorder - the laundry detergent, soap and clothes are lying
on the floor.
Is the woman washing clothes with her hands? No, she is washing them in the
washing machine.
Is the woman washing clothes? No, she's cleaning up the kitchen.


*** clothing 衣物
In the store the friends are picking out clothing.
The woman washes her clothing with her hands. She doesn't have a washing
machine.

*** skirt

*** shirt

*** coat

*** pants

*** blouse

*** goan

*** 

* lesson 39
** a bull
a black bull on green grass
The cows and bull are crossing the street. They're looking for grass.
** a ram
A sheep and a ram give fur.
What gives fur? A sheep and a ram give fur.
Sheep and rams give fur.
** a chicken
The chicken is walking by the house. It's looking for food.
Chickens lay eggs.
What lays eggs? Chickens lay eggs.

** a sheep
In the country graze cows and sheep, but there are no leopards or wolves.
A sheep is a herbivorous animal. It eats grass.
** a cow
The cows and bull are crossing the street. They're looking for grass.
Cows give milk.
A cow is a spotted and herbivorous animal. It eats grass.
A cow also is a herbivorous animal.
a spotted cow
In the country graze cows and sheep, but there are no leopards or wolves.
** a rooster
What sings at dawn? A rooster sings at dawn.
** a rabbit
a grey rabbit on yellow sand
The grey rabbit is hiding behind a tree.
In the winter a rabbit is white. It's invisible in the snow. It doesn't hide.
What hunts rabbits? Hungry wolves hunt rabbits.
The hungry wolf is looking around. He's looking for a rabbit.
** a wolf
A wolf is a carnivorous animal. It eats meat.
The wolf is hunting a deer.
What hunts rabbits? Hungry wolves hunt rabbits.
** a deer
a spotted deer
If a deer is thirsty, it goes to the river.
A deer is a spotted and herbivorous animal.
The hungry wolf is hunting a deer.
The deer is grazing in the forest.
The hungry tiger is hunting a deer.
The spotted leopard chases a yellow deer. It's hunting.
What is spotted and herbivorous? A deer is spotted and herbivorous.
** a lion
If lions sleep, they're not hungry.
The full lion is lying under a tree.
The small, full lion is jumping on the tree. He's playing.
The lion is lying under a tree and eating meat.

** a tiger
a striped tiger
The hungry tiger is hunting a deer.
What is striped and carnivorous? A tiger is striped and carnivorous.

** a leopard
a spotted leopard
The spotted leopard chases a yellow deer. It's hunting.
A leopard is spotted. It's invisible among the trees.
If a leopard is hungry, it hunts.
A leopard is a carnivorous animal.
In the country graze cows and sheep, but there are no leopards or wolves.

** to graze

The spotted deer is grazing in the forest.
In the country graze cows and sheep, but there are no leopards or wolves.

** text

to hunt
to give milk
to lay eggs
to give fur
to hide

hungry
full
carnivorous
herbivorous
spotted
striped

a striped tiger
a grey rabbit on yellow sand
a black bull on green grass
The spotted leopard chases a yellow deer. It's hunting.
a spotted leopard
a spotted cow

The sheep is standing by the house and eating grass.
The wolf is hunting a deer.
The deer is grazing in the forest.
A wolf is a carnivorous animal. It eats meat.
The lion is lying under a tree and eating meat.
A leopard also is a carnivorous animal.

A cow also is a herbivorous animal.
Cows give milk.
Sheep and rams give fur.
A sheep is a herbivorous animal. It eats grass.
Chickens lay eggs.
The hungry tiger is hunting a deer.

The cows and bull are crossing the street. They're looking for grass.
The rabbit is hiding behind a tree.
The chicken is walking by the house. It's looking for food.
The small, full lion is jumping on the tree. He's playing.
The full lion is sleeping under a tree.
The hungry wolf is looking around. He's looking for a rabbit.

A leopard is spotted. It's invisible among the trees.
If a deer is thirsty, it goes to the river.
If a leopard is hungry, it hunts.
In the country graze cows and sheep, but there are no leopards or  wolves.
In the winter a rabbit is white. It's invisible in the snow. It doesn't hide.
If lions sleep, they're not hungry.

What lays eggs? Chickens lay eggs.
What sings at dawn? A rooster sings at dawn.
What hunts rabbits? Hungry wolves hunt rabbits.
What is spotted and herbivorous? A deer is spotted and herbivorous.
What gives fur? A sheep and a ram give fur.
What is striped and carnivorous? A tiger is striped and carnivorous.

* lesson 40
** laundry detergent
The laundry detergent is standing on the washing machine.
In order to wash clothes, you need laundry detergent and a washing machine.
The bathroom is in disorder - the laundry detergent, soap and clothes are lying
on the floor.
The bathroom is in order - the laundry detergent and soap are lying on the
shelf, and the towel is hanging.

** detergent
In order to wash the stove, you need detergent.

** a bucket
In order to wash the floor, you need a mop and a bucket.
The girl is holding  a bucket with water and  cloth. She wants to wash the
floor.
A wet cloth is lying on the bucket.

a cloth

a washing machine
a mop
an iron
an ironing board
a vacuum cleaner
a dishwasher
a rug
a brush
a soap
order
disorder

** to vacuum

The boy is vacuuming the rug and smiling.
In order to vacuum the rug, you need a vacuum cleaner.


to wipe off
to clean
** to clean up
The boy isn't washing the floor. He's cleaning up the shelf.
The man is cleaning up the table.
What are the children doing? The children are helping their mom clean up the
room.

** to iron 

The father is ironing a shirt and talking on the phone.
The woman is ironing a beautiful dress and thinking about a party.
In order to iron pants, you need an iron and an ironing board.

** text

The table is in order.
The table is in disorder.
The room is in order.
The room is in disorder.

A wet cloth is lying on the bucket.
A dry cloth is lying on the floor.
The vacuum cleaner is standing on the rug.
The soap is lying on the shelf under the mirror in the bathroom.
The girl is holding a bucket with water and a cloth. She wants to wash the floor
in the room.
The laundry detergent is standing on the washing machine.

The man is turning on the washing machine.
Grandma washes dishes with her hands. She doesn't have a dishwasher.
The woman washes her clothing with her hands. She doesn't have a washing machine.
The woman is washing the big, dirty window. No one is helping her.
The man is washing his things in the washing machine.
The boy is washing the floor with a mop and a cloth. He's helping his mom.

The kitchen is in order.
The room is in disorder.
The woman isn't washing clothes. She's cleaning up the kitchen.
The man is cleaning up the table.
The boy isn't washing the floor. He's cleaning up the shelf.
The girl is cleaning up the room.

The room is in order - the books are standing on the shelf and the clothes are
lying in the cabinet.
The kitchen is in disorder - dirty dishes are on the table, and the tablecloth
is lying on the floor.
The room is in disorder - books, clothes and toys are lying on the floor.
The bathroom is in disorder - the laundry detergent, soap and towel are lying on
the floor.
The bathroom is in order - the laundry detergent and soap are lying on the
shelf, and the towel is hanging.
The kitchen is in order - clean dishes are standing in the cabinet.

In order to wash the stove, you need detergent.
In order to clean shoes, you need a shoe brush.
In order to wash clothes, you need laundry detergent and a washing machine.
In order to iron pants, you need an iron and an ironing board.
In order to vacuum the rug, you need a vacuum cleaner.
In order to wash the floor, you need a mop and bucket.

The mother is washing the window, and her daughter is washing the floor.
The father is ironing a shirt and talking on the phone.
The boy is vacuuming the rug and smiling.
The woman is ironing a beautiful dress and thinking about a party.
The mother is washing glasses, and her daughter is drying them.
The woman is washing dirty dishes and listening to happy music.

Is the grandmother washing dishes with her hands? Yes, she doesn't have a
dishwasher.
With what is the man cleaning his shoes? He's cleaning them with a shoe brush.
What are the children doing? The children are helping their mom clean up in the
room.
With what is the girl drying the plate? She's drying the plate with a clean
white towel.
With what is the woman washing the floor? She's washing the floor with a mop and
a wet rag.
Is the woman washing clothes with her hands? No, she is washing them in the
washing machine.






