* chapter 1
WE were in the prep.-room when the Head came in, fllowed by a new boy in
ordinary day clothes, and a beadle carrying a big desk. The sleepers aroused
themselves, and we all stood up, putting on a startled look, as if we had been
buried in our work.

  The Head motioned to us to sit down.
   "Monsieur Roger," said he in a quiet toneto the prep. master, 'I've brought you a new boy. He's going into the second.
  If his counduct and progress aare satisfactory, he will be put up with the
  boys of his own age.' The new boy had kept in the background, in the corner
  behind the door, almost out of sight. He was a country lad of about fifteen,
  and taller than any of us. His hair as clipped straight across the forehead,
  like a village choir-boy's. He seemed a decent fellow enough, but horribly
  nervous. Although he was not broad across the shoulders, his green cloth
  jacket, with its black buttons, looked as if it pinched him under the arms.
  Protruding well beyound the cuffs, he displayed a pair of raw, bony wrists,
  obviously not unaccustomed to exposure. His legs, encased in blue stockings,
  issued from a pair of drab-colured breeches, very tightly braced. He had on a
  pair of thick clumsy shoes, not particularly well cleaned and plentifully
  fortified with nails. The master began to hear the boys their work. The
  newcomer listened with all his ears, drinking it in as attentively as if he
  had been in church, not daring to cross his legs or to lean his elbows on the
  desk, and when two o'clock came and the bell rang for dismissal, the master
  had to call him back to earth and tell hom to line up with the rest of us.
