* DONE 人理想的生活状态：
  CLOSED: [2016-08-23 二 09:13]
  :LOGBOOK:
  - State "DONE"       from "STARTED"    [2016-08-23 二 09:13]
  CLOCK: [2016-08-23 二 08:34]--[2016-08-23 二 09:13] =>  0:39
  :END:
工作愉快，生活品味--生活幸福，工作愉快
外在需求随时达成
内在高度满意满足

* 如何实现

** 工作：
终身学习，具有世界眼光及必备知识、技能
实现当前工作环境中无压、自信、掌控一切。

** 用最好的高效工具（到达同一目标：一个步行的人无法和一个开车的竞争）

*** 如：搞计算机一定要用：
硬件：Mac book pro Mac pro
手机：iphone(or sumsung)
手表：iwatch(or Gear S2)
ipad
耳机：蓝牙4.0以上

*** 汽车：要么不买。安全，省心。
B级车以上。你的生命比世界上任何一款车都贵。家庭离不了你。

*** 家居：环保

*** 饮食：无害、安全

*** 衣着：少次、品味。不着过期衣服。

*** 做精英就要过异于常人的生活，要比常人付出更多。

*** 软件：

**** 良好的生活及工作习惯

**** 精确管理自己的时间

**** 科学整理自己的知识构架并时时回顾、实践、提升、应用、推广。
 （修之于身，其德乃真；修之于家，其德乃馀；修之于乡，其德乃长；修之于国，其德乃丰；修之于天下，其德乃普）
   全面：工作、管理、家庭、生活、时事、工具、语言等。
   例：

**** 编辑器：纯文本的-spacemacs
 (即有vim的高效、智能、又有emacs的可扩充、定制。无可披敌，所向披)

**** GTD Getting Things Doing

**** Emacs Org

**** English learning

** work:
 ERP
 Project: Redmaine
E-learning: Moodle(mooc)
big data:docker
file manger: github
dictionary:Youdao
edit and print:Latex
program language:C;Ruby;lisp;html 5
database: Reails?
application:only apple

hero: emacs linux latex ruby Facebook google apple

** 需要别人认同吗？no!

*** 在国人眼里：
 正言若反。
 知者不博，博者不知；
 知者不言，言者不知；
 信言不美，美言不信。
 善者不辩，辩者不善。

 上士闻道，勤而行之。
 中士闻道，若存若亡。
 下士闻道，大笑之。
 不笑不足以为道。

 常循准则：
 千里之行，始于足下。
 慎终如始。
 欲先民，必以身后之。
 欲上民，必以言下之。
 善用人者，为之下。

 既以为人已愈有，
 既以与人已愈多。

 行不言之教，
 为而不恃，功成而弗居。
 多言数穷，不如守中。
 为而为争。

 上善若水：
 水善利万物而不争，处众人之所恶，故几于道。

 物的态度：
 金玉满堂，莫之能守；宝贵而骄，自遗其咎。
 功遂身退，天之道也。

 去甚、去奢、去泰

 知人者智，自知者明。
 胜人者有力，自胜者强。
 知足者富。
 强行者有志，不失其所者久。
 死而不亡者寿。

 质真若渝；大器晚成。
 知足不辱，知止不殆。

 祸莫大于不知足；咎莫大于欲得。

 生而不有，为而不恃，长而不宰。是谓玄德。

 祸兮福之所倚，
 福兮祸之所伏。

 困难于其易
 为大于其细。
 天下难事，必作于易。
 天下大事，必作于细。
 轻诺必寡信，多易必多难。

 为之于未有，治之于未乱。

 天之道，损有余而补不足。
 人之道，损不足以奉有余。

 有时间多读易经：中国人的至圣哲学

** 我的改变：
始于工具的改变：Mac pro 2015年9月3号
学习Mac系统，高效、协同、共享。
开始学习管理：精细管理
查找工具：找到Redmine
布署实践，扩展到云、大数据、移动互联
知道了：docker
排版：latex
文件管理：github
纯文本编辑工具emacs,实践两个多月后深入学习
后又发现更好的：spacemacs 并学习vim高效、智能的编辑
知道了GTD Getting Things Doing
一个月后实践并逐步完善。

每天该干什么？干了什么？用时多少？都有详细的历程及记录。
为了更好地掌握最新知识，开始学习英语，从2015年10月开始，已历时半年以上。相当于学
前水平，小学一年级不到。
还不会说，一个一年级的学生可以与人无障碍交流，自己还达不到。
按自己学习中文的历程来学习英语，不求快，不功利，乐在其中。
随学随用，阅读英语原版手册，纯英文软件的使用，用英语记简单的笔记。
可以大大提高程序开发语言的学习实践效率。

** 今后打算：在适当时机：
first:learn Lisp
Second: Learn Ruby
https://www.douban.com/note/64005602/#42921542
Third: database
Four: Big data
Five: Swift
apple app
At the sametime collect knowlege and sort and pushed.

*** work: three years fished ERP Moodle

ISO 9001
education notes
Product quality evaluation
fine management

* 五精四细
概念的提出及其内涵

由笔者提出的"精细管理工程"，是指企业按照"五精四细"的思路与方法，对企业的管理进行
精细化改造的工程。"五精四细"是精细管理工程的核心内容，其内涵是：


** 五精

*** 1、 精华：
 企业需要有效运用、创造、输出全球范围内的文化精华（含企业精神）、技术精
   华、智慧精华等来指导、促进企业的发展。


** 四细

1、细分市场和客户，全面准确把握市场变化和客户需求，企业发展战略和产品定位准。
2、细分企业组织机构中的职能和岗位，企业管理体系健全，责权利明确、到位。
3、细化分解每一个战略、决策、目标、任务、计划、指令，使之落实到人。
4、细化企业管理制度的编制、实施、控制、检查、激励等程序、环节，做到制度到位。
指在工作中,将各种任务分解明确,责任到人,严格要求,全面落实,既要从宏观上统筹,又要在
微观上研究与落实.这个名词最初是由山西省灵时县教育局长田应松在2005年教育工作会议
上提出,并被各行业广泛流传.

*** 管理学概念?


将某项工作或者某个流程细化，使其具有可知性和可控性。通过细化，能够让员工真正了解
这项工作或流程的每个环节或每个可能影响最终结果的因素，从而认识其规律；有了可知性
才能有可控性，在可知性的基础之上，管理者和员工能够把握好每一个环节，规避不利因素，
发挥有利因素使工作结果向想要的方向发展。?

对地方政府投融资平台的管理启示

精细管理所倡导的资源利用效率最大化、管理规范化和责任制度是值得投融资平台认真研究
和借鉴的。

第一，投融资平台要加强对存量资产的管理。目前，投融资平台的存量资产包括政府划入资
产、自建资产和购入资产。这些资产中有许多经营性资产或者可阶段经营资产，比如公司名
下房地产和整理完毕尚未出让的土地，可以通过租售方式增加平台的现金收入。

第二，投融资平台管理需要跟进一步制度化。许多中小平台尚未建立起基本的管理制度框架，
人浮于事。已制定的制度在执行过程中存在流程不合理、实施困难。为了提升集团的管理效
率，提高员工执行力，平台规范化势在必行。

第三，平台管理必须明确权责。责任制度是精细管理的核心，通过对平台内部流程执行责任
的明晰化，建立企业员工的责任感是平台精细管理的关键。通过建立岗位说明书，明确员工
责任。

以上来源于 百度百科

* 下学期工作安排与分工：

平台布署与技术支撑：张青
教学管理任务下达及管理：李倩
所有设备进入ERP管理
所有教学活动档案标准化、电子化、公开、共享、协同。
每门课选取世界或国内现有内容建立在线课程。
教师建立作业库并答疑、定成绩。平时成绩及每个学生成绩始终在线，供家长、教师、学习
浏览。
建立计算机科学知识库系统，大家共同搜集并书写。
学生管理：陈振超
全部学生进入ERP系统，实现自动考勤，统计。
班主任是班级经理，学生顾员，体验ERP职业岗位。

* 七个对我最重要的职业建议（译文）
七个对我最好的职业建议（精简版）
作者：Nicholas C. Zakas
译者：阮一峰
原文网址：https://www.nczonline.net/blog/2013/10/15/the-best-career-advice-ive-received/

** MEETING 一、不要别人点什么，就做什么
   CLOSED: [2016-08-23 二 08:32]
 我的第一份工作，只干了8个月，那家公司就倒闭了。我问经理，接下来我该怎么办，他说：
"小伙子，千万不要当一个被人点菜的厨师，别人点什么，你就烧什么。不要接受那样一份
工作，别人下命令你该干什么，以及怎么干。你要去一个地方，那里的人肯定你对产品的想
法，相信你的能力，放手让你去做。"
 我从此明白，单单实现一个产品是不够的，你还必须参与决定怎么实现。好的工程师并不
 仅仅服从命令，而且还给出反馈，帮助产品的拥有者改进它。


** 二、推销自己
我进入雅虎公司以后，经理有一天跟我谈话，他觉得我还做得不够。
"你工作得很好，代码看上去不错，很少出Bug。但是，问题是别人都没看到这一点。为了
让其他人相信你，你必须首先让别人知道你做了什么。你需要推销自己，引起别人的注意。
"

我这才意识到，即使做出了很好的工作，别人都不知道，也没用。做一个角落里静静编码
的工程师，并不可取。你的主管会支持你，但是他没法替你宣传。公司的其他人需要明白
你的价值，最好的办法就是告诉别人你做了什么。一封简单的Email："嗨，我完成了XXX，
欢迎将你的想法告诉我"，就很管用。

** 三、学会带领团队
工作几年后，已经没人怀疑我的技术能力了，大家知道我能写出高质量的可靠代码。有一
次，我问主管，怎么才能得到提升，他说：

"当你的技术能力过关以后，就要考验你与他人相处的能力了。"
于是，我看到了，自己缺乏的是领导能力，如何带领一个团队，有效地与其他人协同工作，
取到更大的成果。


** 四、生活才是最重要的
 有一段时间，我在雅虎公司很有挫折感，对公司的一些做法不认同，经常会对别人发火。
 我问一个同事，他怎么能对这种事情保持平静，他回答：

 "你要想通，这一切并不重要。有人提交了烂代码，网站下线了，又怎么样？工作并不是你
的整个生活。它们不是真正的问题，只是工作上的问题。真正重要的事情都发生在工作以外。
我回到家，家里人正在等我，这才重要啊。"
从此，我就把工作和生活分开了，只把它当作"工作问题"看待。这样一来，我对工作就总
 能心平气和，与人交流也更顺利了。


** 五、自己找到道路
我被提升为主管以后，不知道该怎么做。我请教了上级，他回答：
"以前都是我们告诉你做什么，从现在开始，你必须自己回答这个问题了，我期待你来告诉
我，什么事情需要做。"

很多工程师都没有完成这个转变，如果能够做到，可能就说明你成熟了，学会了取舍。你
不可能把时间花在所有事情上面，必须找到一个重点。


** 六、把自己当成主人
我每天要开很多会，有些会议我根本无话可说。我对一个朋友说，我不知道自己为什么要
参加这个会，也没有什么可以贡献，他说：

"不要再去开这样的会了。你参加一个会，那是因为你参与了某件事。如果不确定自己为什
么要在场，就停下来问。如果这件事不需要你，就离开。不要从头到尾都静静地参加一个
会，要把自己当成负责人，大家会相信你的。"
从那时起，我从没有一声不发地参加会议。我确保只参加那些需要我参加的会议。

** 七、找到水平更高的人
最后，让我从自己的经历出发，给我的读者一个建议。
"找到那些比你水平更高、更聪明的人，尽量和他们在一起，吃饭或者喝咖啡，向他们讨教，
了解他们拥有的知识。你的职业，甚至你的生活，都会因此变得更好。"

http://wenku.baidu.com/link?url=CmXvHhwlRW4w5VMA3J8OOq7BsjmV4aBLounpOvi6-c60h5RhJADEkMuQYk3sgYnXiUnLFFkt9ld52AtMQffYmY1J_tuU-qco4L0h4899GYq
http://wenku.baidu.com/view/71a5078dec3a87c24028c4b4.html?re=view
* 乔布斯的管理课

http://www.ruanyifeng.com/blog/2014/10/real-leadership-lessons-of-steve-jobs.html

** 一、保持专注
1997年，乔布斯重新执掌濒临破产的苹果公司。那时，苹果公司有庞大的产品线，单单
Macintosh电脑就有十几个版本。乔布斯决定砍掉大部分产品。

products
他在白板上画了一个2x2的网格。"这才是我们要的，"在两栏的底部，他写下"普通消费者"
（Consumer）和"专业用户"（Pro），在两行的前端他写下"桌面设备"（Desktop）和"便携
设备"（Portable）。他告诉团队，我们的工作就是要生产四个伟大的产品，表格的每一格
代表一个产品，其余的产品应该全部取消。

还有一次，乔布斯问大家："我们下一步最应该做的10件事是什么？"，大家七嘴八舌，列
出了10件事。乔布斯划掉了后面7件，说我们只做最前面的3件。


** 二、保持简单
乔布斯参观施乐公司的Palo Alto实验室，见到了刚刚发明的鼠标。他一下子被吸引住了。
Palo Alto
回来以后，他告诉设计人员，立刻仿造一个。但是，施乐公司的鼠标有三个键，乔布斯要
求苹果的鼠标只能有一个键。

Apple II mouse
设计iPod操作界面时，乔布斯坚持最多只需三次点击，用户就能完成所有操作。
乔布斯经常问别人，你觉得有没有什么东西过于复杂了？他以此作为参考，决定下一步要
开发的产品。


** 三、追求完美
乔布斯从小养成追求完美的性格。有一次，他与父亲在后院搭篱笆。父亲要求篱笆的背面
也要精心施工。乔布斯说："谁会去看篱笆的背面？"父亲回答："你会看到。"

Macintosh Case
开发Macintosh电脑时，他不顾整个团队的反对，要求机箱内部的电路板和电线也要整齐美
观。设计定案后，他把设计人员的签名镌刻在机箱上，"真正的工匠都对自己的作品签名"。


** 四、重视设计
乔布斯重返苹果后的第一件产品，是彩色的桌面电脑iMac。它的顶部有一个把手，并不是
那么有用，有谁会提着桌面电脑走来走去呢？

iMac
生产部门希望去掉这个把手，这样可以降低成本。但是，乔布斯坚持要加上。因为，他觉
得普通消费者仍然对电脑有敬畏感，认为那是高深莫测的产品。他希望，苹果的产品能够
给人一种友好的、平易近人的、易于操作的感觉。这个把手可以传递这样的信号，仿佛在
那里说，快来使用我吧。

* 一个合格的程序员应该读过哪些书
http://blog.pfan.cn/art/53720.html

* FaceBook

** Done is better than prefect.
* 管理的精髓
http://wenku.baidu.com/view/c974011c227916888486d7b6.html
* Hack 的详细定义主要有三点：马上上手、快速搞定和持续迭代。
http://kb.cnblogs.com/page/545228/
#+BEGIN_LaTeX
\newpage
#+END_LaTeX

* <2016-09-13 二 09:00>

1. 时间管理及知识管理，从干部做起
2. 严格考勤，统计通报。从干部、党员做起。
3. 落实ERP、在线学习系统。
4. 身教大于言传
5. 16级管理、全部进入readme，学习wiki
6. 胸牌制作及配带
7. 晚自习，丰富内容：讲座、技能练习、音乐、形体
8. 教师考勤逐步实行ERP
