* Lesson 83 Holiday
Hello, Sam. Come in.
Hi, Sam.
We're having lunch.
Do you want to have lunch with us?
No, thank you. Tom.
I've already had lunch.
I had a lunch at half past twelver.
Have a cup of coffee then.
I've just had a cup, thank you.
I had one after my lunch.
Let's go into the living room, Carol.
We can have our coffee there.
Excuse the mess, Sam.
This room's very untidy.
We're packing our suitcases.
We're going to leave tomorrow.
Tom and I are going to have a holiday.
Aren't you lucky!
When are you going to have a holiday, Sam?
I don't know.
I've already had my holiday this year.
Where did you go?
I stayed at home!
** 现在进行时
We're having lunch.
We're packing our suitcases.
** 打算（将来时）
We're going to leave tomorrow.
Tom and I are going to have a holiday.
When are you going to have a holiday, Sam?
** 正在完成时 have +过去分词
I've already had lunch.
I've just had a cup, thank you.
I've already had my holiday this year.
** 一般过去时
I had a lunch at half past twelve.
I had one after my lunch.
Where did you go?
I stayed at home.
** 一般现在时
Do you want to have lunch with us?
Have a cup of coffee then.
Let's go into the living room, Carol.
We can have our coffee there.
This broom's very untidy.
I don't know.

** test

Hello, Sam. Come in.
Hi, Sam. 
We're having lunch.
Do you want to have lunch wiht us?
No, thank you. Tom.
I've already had lunch.
I had a lunch at half past twelve.
Have a cup of coffee then.
I've juse had a cup, thank you.
I had one after my lunch.
Let's go into the living room, Carol.
We can have our coffee there.
Exeuse the mess, Sam.
This room's very untidy.
We're packing our suitcases.
We're going to leave tomorrow.
Tom and I are going to have a holiday.
Aren't you lucky!
When are you going to have a holiday, Sam?
I don't know.
I've already had my holiday this year.
Where did you go?
I stayed at home!

* Lesson 85

Hello, Ken.

Hi, George.

Have you just been to the cinema?

Yes, I have.

What's on?

'Pairs in the spring.'

Oh, I've already seen it.

I saw it on television last year.

It's an old film, but it's very good.

Pairs is a beautiful city.

I've never been there.

Have you ever been there, Ken? 

Yes, I have. I was there in spring. 

Pairs in the spring, eh?

It was spring,

but the weather was awful.

It rained all the time.

Just like London! 

** 现在完成时
Have you just been to the cinema?
Oh, I've already seen it.
I've never been there.
Have you ever been there, Ken?

** 一般过去时
I saw it on television last year.
I was there in April.
It was spring, but the weather was awful.
It rained all the time.

** 一般现在时
What's on?
It's an old film, but it's very good.
Pairs is a beautiful city.
Just like London.

* lesson 87
/Is/ my car ready yet?

I don't know, sir.

What's the number of your car?

It is LIZ 312G.
When did you bring it to us?
I brought here three days ago.
Oh,yes. I remember now.
Have your mechanics finished yet?
No, they're still working on it.
Let's go into the garage and have a look at it.
Isn't that your car?
Well, it was my car.
Didn't you have a crash? 
That's right.
I drove it into a lamp-post.
Can your mechanics repair it?
Well, they're trying to repair it, sir.
But to tell you the truth, 
you need a new car.

** 现在完成时（特殊）
Is my car ready yet?
Have your mechanics finished yet?
Didn't you have a crash?

** 一般过去时
I brought here three days ago.
It was my car.
I drove it into a lamp-post.
** 现在进行时
No, they're still working on it.
Well, they're trying to repair it, sir.
** Can
Can your mechanics repair it?
* Lesson 89 For Sale
Good afternoon.
I believe that this house is for sale.
That's right.
May I have a look at it, please?
Yes, of course.
Come in.
How long have you lived here?
I've live here for twenty years.
Twenty years!
That's a long time.
Yes, I've been here since 1976.
Then why do you want to sell it?
Because I've just retired.
I want to buy a small house in the country.
How much does this house cost?
$68500.
That's a lot of money.
It's worth every penny of it.
Well, I like the house,
but I can't decide yet.
My wife must see it first.
Women always have the last word.
* Lesson 91 Poor Ian
Has Ian sold his house yet?
Yes, he has.
Has he moved to his new house yet? 
No,not yet.
He's still here.
He's going to move tomorrow.
When? Tomorrow morning.
No. Tomorrow afternoon.
I'll miss him.
He has always been a good neighbour.
He's a very nice person.
We'll all miss him.
When will the new people move into this house?
I think that they'll move in the day after tomorrow.
Will you see Ian today, Jenny?
Yes, I will.
Please give him my regards.
Poor Ian!
He didn't want to leave this house.
No, he didn't want to leave,
but his wife did.

** Lesson 93
Nigel is our new next-door neighbour.
He's a pilot.
He was in the R.A.F.
He will fly to New York next month.
The month after next he'll fly to Tokyo.
At the moment, he's in Madrid.
He flew to Spain a week ago.
He'll return to London the week after next.
He's only forty-one years old,
and he has already been to nearly every country in the world.
Nigel is a very lucky man.
But his wife isn't very lucky.
She usually stays at home!
