* lesson 75 Uncomfortable shoes
Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those a month ago,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last.
But they're not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable.
But women always wear uncomfortable shoes!
像这样的鞋子你们有吗？
什么尺码的？
5 号的。
什么颜色？
黑的。
对不起，我们没有。
但是，我姐姐上个月买到了这样的一双。
好是在这儿买的吗？
不。她是在美国买的。
一个月前我们有这样的鞋。
但是现在没有了。
您能为我找一双吗？
恐怕不行。
这鞋在去年和前年时兴，而今年已不流行了。
现在流行的是这种鞋子。
这种鞋子看上去很不舒适。
的确很不舒适。
可是女人们总是穿不舒适的鞋子！

** write in

Do you have any shoes like these?
What size?
Number five.
What color?
Blank.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those a month ago,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last.
But they are not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable. 
But women always wear uncomfortable shoes!

wrong:
But my sister bought a pair last month.
Did she buy them here?
Do you get a pair for me, please?
I'm afraird I can't.
But they are not in fashion now.
But they look very uncomfortable.
But women always wear uncomfortable shoes.
crrect:
But my sister bought this pair last month.
Did she buy them here?
Can you get a pair for me, please?
I'm afraird that I can't.
But they're not in fashion this year.
They look very uncomfortable.
But women always wear uncomfortables shoes!

** second test
Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those a month ago.
But we don't have any now.
Can you get a pari for me, please?
I'm afraired that I can't.
They were in fashion last year and the year before last.
But they're not in fashion this year.
These shoes are in fishion now.
They look very uncomfortables.
They are very uncomfortables.
But women always wear uncomfortables shoes!

** Third review

Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those a month agon,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last,
but they're not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable.
But women always 

#+BEGIN_SRC LISP
(global-set-key (kbd "<f2>") 'open-init-file)
#+END_SRC 

* lesson 77 toothache
Good morning. Mr. Croft.
Good morning, nurse.
I want to see the dentist, please.
Do you have an appointment?
No, I don't.
Is it urgent?
Yes, it is.
It's very urgent.
I fell awful.
I have a terrible toothache.
Can you come at 10 a.m on Monday, April 24th?
I must see the dentist now, nurse.
The dentist is very busy at the moment.
Can you come at 2 p.m?
That's very late
.
Can the dentist see me now?
I'm afraid that he can't. Mr. Croft.
Can't you wait till this afternoon?
I can wait, but my toothache can't.

** write in 
Good morning, Mr. Croft.
Good morning, nurse.
I want to see the dentist, please.
Do you have an appointment?
No, I don't.
Is it urgent?
Yes, it is.
It is very urgent.
I fell awful.
I have a terrible toothache.
Can you come at 10 a.m. on Monday, April 24th?
I must see the dentist now, nurse.
The dentist is very busy at the moment.
Can you come at 2 p.m.?
That's very late.
Can the dentist see me now?
I'm afraid that he can't. Mr. Croft.
Can't you wait till this afternoon?
I can wait, but my toothache can't.

** Second write in.
Good morning. Mr. Croft.
Good morning, nurse.
I want to see the dentist, please.
Do you have an appointment?
No. I don't.
Is it urgent?
Yes, it is.
It's very urgent.
I feel awful.
I have a terrible toothache.
Can you come at 10 a.m. on Monday, April, 24th?
I must see the dentist now, nurse.
The dentist is very busy at the moment.
Can you come at 2 p.m.?
That's very late.
Can the dentist see me now?
I'm afraid that he can't. Mr. Croft.
Can't you wait till this afternoon?
I can wait, but my toothache can't.
** third write in
Good morning, Mr. Croft.
Good morning, nurse.
I want to see the dentist, please.
Do you have an appointment?
No, I don't.
Is it urgent?
Yes, it is.
It's very urgent.
I feel awful.
I have a terrible toothache.
Can you come at 10 a.m. on Monday, April, 24th?
I must see the dentist now, nurse.
The dentist is very busy now at the moment.
Can you come at 2 p.m.?
That's very late.
Can the dentist see me now?
I'm afraid that he can't, Mr. Croft.
Can't you wait till this afternoon?
I can wait, but my toothache can't!
** appointment
英[əˈpɔɪntmənt]
美[əˈpɔɪntmənt]
n.	约会; 预约; 约定; 任命; 委任; 职务; 职位;
[例句]His appointment to the Cabinet would please the right-wing.
他被任命为内阁成员会让右翼党派很高兴。
[其他]	复数：appointments
** urgent	英[ˈɜːdʒənt]
美[ˈɜːrdʒənt]
adj.	紧急的; 紧迫的; 迫切的; 催促的; 急切的;
[例句]There is an urgent need for food and water
现在亟需食物和水。
** awful	英[ˈɔːfl]
美[ˈɔːfl]
adj.	很坏的; 极讨厌的; 非常的; 很多的; 过多的; 骇人听闻的; 可怕的;
adv.	非常; 极其;
[例句]We met and I thought he was awful
我们见了面，我觉得他很讨人厌。

* lesson 79 Carol's shopping list
What are you doing, Carol?
I'm making a shopping list, Tom.
What do we need?
We need a lot of thing this week.
I must go to the grocer's.
We haven't got much tea or coffee, 
and we haven't got any sugar or jam.
What about vegetables?
I must go to the green-grocer's.
We haven't got many tomatoes, 
but we've got a lot of potatoes.
I must go to the butcher's, too.
We need some meat.
We haven't got any meat at all.
Have you got any beer and wine?
No, we haven't. 
And I'm not going to get any!
I hope that you've got some money.
I haven't got much.
Well, I haven't got much either!

** test

What are you doing, Carol?
I'm making a shopping list, Tom.
What do we need?
We need a lot of thing this week.
I must go to the grocer's.
We haven't got much tea or coffee,
and we haven't got any sugar or jam.
What about vegetables?
I must go to the green-grocer's.
We haven't got many tomatoes,
but we've got a lot of potatoes.
I must go to the butcher's, too.
We need some meat.
We haven't got any meat at all.
Have we got any beer and wine?
No, we haven't.
And I'm not going to get any!
I hope that you've got some money.
I haven't got much.
Well, I haven't got much either!

** many 肯定或可数
We haven't got many tomatoes.
** much 否定或不可数
We haven't got much tea or coffee.
How much does this house cost?
I haven't got much.
Well, I haven't got much either.

** any 否定问句或不可数

and we haven't got any sugar or jam.
We haven't got any meat at all.
Have we got any beer and wine?
No, we haven't. And I'm not going to got any!

** a lot of 不可数的（钱、东西、马铃蓍） 
but we've got a lot of potatoes.
We need a lot of thing this week.
That's a lot of money.

** must 必须
I must go to the grocer's.
I must go to the green-grocer's.
I must go to the butcher's, too.
My wife must see it first.

** need
What do we need?
We need a lot of thing this week.
We need some meat.
You need a new car.
** Be going to 
Well, I'm not going to get any!
Well, you're going to have roast beef and potatoes again tonight.
We're going to leave tomorrow.
We're going to have a holiday.
Tom and I are going to have a holiday.
When are you going to have a holiday?

** get
get	英[ɡet]
美[ɡet]
v.	收到; 接到; 获得; 得到; (卖某物) 挣得;
[例句]The boys were getting bored
男孩子们开始感到厌烦。
[其他]	第三人称单数：gets 现在分词：getting 过去式：got 过去分词：got

have got 现在完成时
** 酒
*** whisky


 whisky	英[ˈwɪski]
 美[ˈwɪski]
 n.	威士忌; 一杯威士忌;
 [例句]He took a mouthful of neat whisky, and coughed.
 他喝了一口纯威士忌，咳嗽了起来。
 [其他]	复数：whiskies
 威士忌（Whisky、Whiskey），是一种由大麦等谷物酿制，在橡木桶中陈酿多年后，调配成 43 度左右的烈性蒸馏酒。英国人称之为“生命之水”。按照产地可以分为：苏格兰威士忌、爱尔兰威士忌、美国威士忌和加拿大威士忌四大类。威士忌的酿制工艺过程分为六个步骤：发芽、糖化、发酵、蒸馏、陈年、混配。
*** wine
 wine	英[waɪn]
 美[waɪn]
 n.	葡萄酒; (用植物或除葡萄以外的水果酿制的) 酒，果酒; 紫红色; 深红色;
 v.	喝酒; 请…喝酒;
 [例句]This is a nice wine.
 这种葡萄酒味道不错。
 [其他]	第三人称单数：wines 现在分词：wining 过去式：wined 过去分词：wined

*** beer 


 beer	英[bɪə(r)]
 美[bɪr]
 n.	啤酒; 一杯(或一瓶、一罐)啤酒;
 [例句]He sat in the kitchen drinking beer
 他坐在厨房里喝啤酒。
 [其他]	复数：beers
** 商店
*** grocer's
 杂货店; 食品杂货店;

*** greengrocer's 

 蔬菜水果店;

*** butcher's
 butcher's	英[ˈbʊtʃəz]
 美[ˈbʊtʃərz]
	 肉店; 屠夫

*** store
 store	英[stɔː(r)]
 美[stɔːr]
 n.	(大型) 百货商店; 商店; 店铺; 贮存物; 备用物;
 v.	贮存; 贮藏; 保存; (在计算机里) 存储; 记忆;
 [例句]Bombs were planted in stores in Manchester and Blackpool.
 炸弹被安放在曼彻斯特和布莱克浦的几家商店里。
 [其他]	第三人称单数：stores 复数：stores 现在分词：storing 过去式：stored 过去
 分词：stored

*** stove 火炉

*** market
 market	英[ˈmɑːkɪt]
 美[ˈmɑːrkɪt]
 n.	集市; 市场; 商场; 交易; 买卖; 交易量; 商品的销售地; 行销地区; 消费群体;
 v.	推销; 促销;
 [例句]He sold boots on a market stall.
 他在集市上摆摊卖靴子。
 [其他]	第三人称单数：markets 复数：markets 现在分词：marketing 过去式：marketed 过去分词：marketed

*** supermarket
 英[ˈsuːpəmɑːkɪt]
 美[ˈsuːpərmɑːrkɪt]
 n.	超级市场; 超市;
 [例句]Most of us do our food shopping in the supermarket
 我们大多数人去超市购买食品。
 [其他]	复数：supermarkets


* Lesson 81 Roast beef and potatoes
Hi, Carol! Where's Tom?
He's upstairs.
He's having a bath.
Tom! Yes?
Sam's here.
I'm nearly ready.
Hello, Sam.
Have a cigarette.
No, thanks, Tom.
Have a glass of whisky then.
OK. Thanks.
Is dinner ready, Carol?
It's nearly ready.
We can have dinner at seven o'clock.
Sam and I had lunch together today.
We went to a restaurant.
What did you have?
We had roast beef and potatoes.
Oh!
What's the matter, Carol?
Well, you're going to have roast beef and potatoes again tonight.
** first 
err:
Hi, Carol.
No,thanks. Tom.
OK, thanks.
Correct:
Hi, Carol!
No, thanks, Tom.
OK. Thanks.
** ask where
Where's Tom?
** ask what
What did you have?
** have eat meal ett.
Have a cigarette.
Have a glass whisky then.
We can have dinner at seven o'clock.
Sam and I had lunch together today.
We had roast beef and potatoes.
Well, you're going to have roast beef and potatoes again tonight.
** ready
I'm nearly ready.
It's nearly ready.
** 标点
No,thanks, Tom.
OK. Thanks.
Oh!
* Lesson 83 Holiday
Hello, Sam. Come in.
Hi, Sam.
We're having lunch.
Do you want to have lunch with us?
No, thank you. Tom.
I've already had lunch.
I had a lunch at half past twelve.
Have a cup of coffee then.
I've just had a cup, thank you.
I had one after my lunch.
Let's go into the living room, Carol.
We can have our coffee there.
Excuse the mess, Sam.
This room's very untidy.
We're packing our suitcases.
We're going to leave tomorrow.
Tom and I are going to have a holiday.
Aren't you lucky!
When are you going to have a holiday, Sam?
I don't know.
I've already had my holiday this year.
Where did you go?
I stayed at home!
** 现在进行时
We're having lunch.
We're packing our suitcases.
** 打算（将来时）
We're going to leave tomorrow.
Tom and I are going to have a holiday.
When are you going to have a holiday, Sam?
** 正在完成时 have +过去分词
I've already had lunch.
I've just had a cup, thank you.
I've already had my holiday this year.
** 一般过去时
I had a lunch at half past twelve.
I had one after my lunch.
Where did you go?
I stayed at home.
** 一般现在时
Do you want to have lunch with us?
Have a cup of coffee then.
Let's go into the living room, Carol.
We can have our coffee there.
This broom's very untidy.
I don't know.

** test

Hello, Sam. Come in.
Hi, Sam. 
We're having lunch.
Do you want to have lunch with us?
No, thank you. Tom.
I've already had lunch.
I had a lunch at half past twelve.
Have a cup of coffee then.
I've just had a cup, thank you.
I had one after my lunch.
Let's go into the living room, Carol.
We can have our coffee there.
Excuse the mess, Sam.
This room's very untidy.
We're packing our suitcases.
We're going to leave tomorrow.
Tom and I are going to have a holiday.
Aren't you lucky!
When are you going to have a holiday, Sam?
I don't know.
I've already had my holiday this year.
Where did you go?
I stayed at home!

* Lesson 85 Pairs in the spring 

Hello, Ken.

Hi, George.

Have you just been to the cinema?

Yes, I have.

What's on?

'Pairs in the spring.'

Oh, I've already seen it.

I saw it on television last year.

It's an old film, but it's very good.

Pairs is a beautiful city.

I've never been there.

Have you ever been there, Ken? 

Yes, I have. I was there in spring. 

Pairs in the spring, eh?

It was spring,

but the weather was awful.

It rained all the time.

Just like London! 

** 现在完成时
Have you just been to the cinema?
Oh, I've already seen it.
I've never been there.
Have you ever been there, Ken?

** 一般过去时
I saw it on television last year.
I was there in April.
It was spring, but the weather was awful.
It rained all the time.

** 一般现在时
What's on?
It's an old film, but it's very good.
Pairs is a beautiful city.
Just like London.

** Test
Hello, Ken.
Hi, George.
Have you just been to the cinema?
Yes, I have.
What's on?
"Pairs in the spring."
Oh, I've already seen it.
I saw it on television last year.
It's an old film, but it's very good.
Pairs is a beautiful city.
I've never been there.
Have you ever been there, Ken?
Yes, I have. 
I was there in April.
Pairs in the spring, eh?
It was sprint, 
but the weather was awful.
It rained all the time.
Just like London!

err: George George

* lesson 87 crash
/Is/ my car ready yet?

I don't know, sir.

What's the number of your car?

It is LIZ 312G.
When did you bring it to us?
I brought here three days ago.
Oh,yes. I remember now.
Have your mechanics finished yet?
No, they're still working on it.
Let's go into the garage and have a look at it.
Isn't that your car?
Well, it was my car.
Didn't you have a crash? 
That's right.
I drove it into a lamp-post.
Can your mechanics repair it?
Well, they're trying to repair it, sir.
But to tell you the truth, 
you need a new car.

** 现在完成时（特殊）
Is my car ready yet?
Have your mechanics finished yet?
Didn't you have a crash?

** 一般过去时
I brought here three days ago.
It was my car.
I drove it into a lamp-post.
** 现在进行时
No, they're still working on it.
Well, they're trying to repair it, sir.
** Can
Can your mechanics repair it?
** test
Is my car ready yet?
I don't know, sir.
What's the number of your car?
It is LFZ 312G.
When did you bring it to us?
I bought here three days ago.
Oh, yes. I remember now.
Have your mechanics finished yet?
No, They're still working on it.
Let's go into the garage and have a look at it.
Isn't that your car?
Well, it was my car.
Didn't you have a crash?
That's right.
I drove it into a lamp-post.
Can your mechanics repair it?
Well, they're trying to repair it, sir.
But tell you the truth,
you need a new car.

err:
Is my car ready yet?
wrong:Is my car already yet.

I don't know, sir.
wrong: I don't know.

Well, they're trying to repair it, sir.
wrong: Well, they're trying to repair it, sir.
服务人员说话客气。加 sir.

Didn't you have a crash.
wrong:
Have you have a crash.

* Lesson 89 For Sale
Good afternoon.
I believe that this house is for sale.
That's right.
May I have a look at it, please?
Yes, of course.
Come in.
How long have you lived here?
I've live here for twenty years.
Twenty years!
That's a long time.
Yes, I've been here since 1976.
Then why do you want to sell it?
Because I've just retired.
I want to buy a small house in the country.
How much does this house cost?
$68500.
That's a lot of money.
It's worth every penny of it.
Well, I like the house,
but I can't decide yet.
My wife must see it first.
Women always have the last word.
** Test
Good afternoon.
I believe that this house is for sale.
That's right.
May I have a look at it, please?
Yes, of course.
Come in.
How long have you lived here?
I've live here for twenty years.
That's a long time.
Yes, I've been here since 1976.
Then why do you want to sell it?
Because I've just retired.
I want to buy a small house in the country.
How much does this house cost?
$68500.
That's a lot of money.
It's worth every penny of it.
Well, I like the house, 
but I can't decide yet.
My wife must see it first.
Women always have the last word.

err:
I think /that/ this house is for sale.
/Yes/, of course.
/but/ it's worth every penny of it.

** Test
Good afternoon.
I believe that this house is for sale.
That's right.
May I have a look at it, please?
Yes, of course.
Come in.
How long have you lived here?
I've lived here for twenty years.
Twenty years!
That's a long time.
Yes, I've been here since 1976.
Then why do you want to sell it?
Because I've just retired.
I want to buy a small house in the country.
How much does this house cost?
$68500.
That's a lot of money.
It's worth every penny of it.
Well, I like the house, 
but I can't decide yet.
My wife must see it first.
Women always have the last word.

* Lesson 91 Poor Ian
Has Ian sold his house yet?
Yes, he has.
Has he moved to his new house yet? 
No,not yet.
He's still here.
He's going to move tomorrow.
When? Tomorrow morning.
No. Tomorrow afternoon.
I'll miss him.
He has always been a good neighbour.
He's a very nice person.
We'll all miss him.
When will the new people move into this house?
I think that they'll move in the day after tomorrow.
Will you see Ian today, Jenny?
Yes, I will.
Please give him my regards.
Poor Ian!
He didn't want to leave this house.
No, he didn't want to leave,
but his wife did.

** Lesson 93
Nigel is our new next-door neighbour.
He's a pilot.
He was in the R.A.F.
He will fly to New York next month.
The month after next he'll fly to Tokyo.
At the moment, he's in Madrid.
He flew to Spain a week ago.
He'll return to London the week after next.
He's only forty-one years old,
and he has already been to nearly every country in the world.
Nigel is a very lucky man.
But his wife isn't very lucky.
She usually stays at home!


|------+-----+-------+---------|
| name | age | saray | address |
|------+-----+-------+---------|
| 夏   |  55 | 10000 | 泰安    |
|------+-----+-------+---------|
|      |     |       |         |
|------+-----+-------+---------|
|      |     |       |         |
|------+-----+-------+---------|

** test
Has Ian sold his house yet?
Yes, he has.
He sold it last week.
Has he moved to his new house yet?
No, not yet.
He's still here.
He's going to move tomorrow.
When? Tomorrow morning.
No. Tomorrow afternoon.
I'll miss him. 
He has always been a good neighbour.
He's a very nice person.
We'll miss him.
When will the new people move into this house?
I think that they'll move in the day after tomorrow.
Will you see Ian, today?
Yes, I will.
Please give him my regards.
Poor Ian!
He didn't want to leave this house.
No,he didn't want to leave, 
but his wife did.

err:
Will you see Ian today, Jenny?
wrong
Will you see Ian, today?

No, he didn't want to leave,
wrong

no, he didn't want to
