* 笠翁对韵

《笠翁对韵》是从前人们学习写作近体诗、词，用来熟悉对仗、用韵、组织词语的启蒙读物。
作者李渔[fn:1]，号笠翁，因此叫《笠翁对韵》。全书分为卷一和卷二。按韵分编，包罗天
文、地理、花木、鸟兽、人物、器物等的虚实应对。从单字到双字对，三字对、五字对、七
字对到十一字对，声韵协调，琅琅上口，从中得到语音、词汇、修辞的训练。从单字到多字
的层层属对，读起来，如唱歌般。较之其他全用三言、四言句式更见韵味。

** 上卷

*** 一东

天对地，雨对风。大陆对长空。山花对海树，赤日对苍穹。雷隐隐，雾蒙蒙。日下对天中。风
高秋月白，雨霁晚霞红。牛女二星河左右，参商两曜斗西东。十月塞边，飒飒寒霜惊戎旅；
三冬江上，漫漫朔雪冷渔翁。

河对汉，绿对红。雨伯对雷公。烟楼对雪洞，月殿对天宫。云叆叇，日曈曚。腊屐对渔篷。
过天星似箭，吐魄月如弓。驿旅客逢梅子雨，池亭人挹藉花风。茅店村前，皓月附林鸡唱韵；
板桥路上，青霜锁道马行踪。

山对海，华对嵩。四岳对三公。宫花对禁柳，塞雁对江龙。清暑殿，广寒宫。拾翠对题红。
庄周梦化蝶，吕望兆飞熊。北牗当风停夏扇，南帘曝日省冬烘。鹤舞楼头。玉笛弄殘仙子月；
凤翔台上，紫簘吹断美人风。

*** 二冬 

晨对午，夏对冬。下饷对高舂[fn:2]。青春对白昼，古柏对苍松。垂钓客，荷锄翁。仙鹤对
神龙。凤冠珠闪烁，螭带[fn:3]玉玲珑。三元及第才千顷，一品当朝禄万钟。花萼楼间，仙李盘根
调国脉；沉香亭畔，娇杨擅宠起边风。

清对淡，薄对浓。暮鼓对晨钟。山茶对石菊，烟锁对云封。金菡萏，玉芙蓉。绿绮对表锋。
早汤先宿酒，晚食继朝饔。唐库金钱能化蝶，延津宝剑会成龙。巫峡浪传，云雨荒唐神女庙；
岱宗遥望，儿孙罗列丈人峰。

繁对简，叠对重。意懒对心慵[fn:4]。仙翁对释伴，道范对儒宗。花灼灼，草茸茸。浪蝶对狂蜂。
数竿君子竹，五树大夫松。高皇灭项凭三杰，虞帝承尧[fn:5]殛四凶。内苑佳人，满地风光悉不尽；
边关过客，连天烟草憾无穷。

* Footnotes

[fn:5] 殛是一个汉字，读音为 jí，形声字。从歹（è），亟声。从“歹”，表示杀死。《孔
传》：“殛窜放流皆诛也。异其文，述作之体。”


[fn:4] 心慵
[拼音]	[xīn yōng]
[释义]	心意懒散。唐 白居易《白云期》诗：“年长识命分，心慵少营为。”


[fn:3] 螭带:螭(chī吃) ,古代传说中一种无角的龙。螭带, 带钩上雕有螭纹的玉带。三元
句:封建科举考试,乡试第一称解(ji?借)元,会试第一称会元,殿试第一 称


[fn:2] 读音:[chōng]
部首:臼五笔:DWVF
释义:把东西放在石臼或乳钵里捣去皮壳或捣碎。

[fn:1] 李渔
李渔（1611-1680），初名仙侣，后改名渔，字谪凡，号笠翁。汉族，浙江金华兰溪夏李村
人。明末清初文学家、戏剧家、戏剧理论家、美学家。被后世誉为“中国戏剧理论始祖”、
“世界喜剧大师”、“东方莎士比亚”，是休闲文化的倡导者、文化产业的先行者，被列入世界
文化名人之一。一生著述丰富，著有《笠翁十种曲》（含《风筝误》）、《无声戏》（又名
《连城璧》）、《十二楼》、《闲情偶寄》、《笠翁一家言》等五百多万字。还批阅《三国
志》，改定《金瓶梅》，倡编《芥了园画谱》等，是中国文化史上不可多得的一位艺术天才。
