** DONE <2016-07-22 Fri 06:11>
   CLOSED: [2016-07-22 Fri 06:25]
   :LOGBOOK:
   - State "DONE"       from "STARTED"    [2016-07-22 Fri 06:25]
   CLOCK: [2016-07-22 Fri 06:12]--[2016-07-22 Fri 06:25] =>  0:13
   :END:
*** 习近平在宁夏召开扶贫座谈会 22省书记参加(图)http://news.ifeng.com/a/20160721/49493461_0.shtml
*** DONE 习近平提出新任务：培养具有国际视野的企业家http://news.ifeng.com/a/20160717/49369032_0.shtml
    CLOSED: [2016-07-22 Fri 21:31]
    :LOGBOOK:
    - State "DONE"       from "STARTED"    [2016-07-22 Fri 21:31]
    :END:
 万古基业，必出自雄才伟略。在纵论国际国内大势、描绘改革发展蓝图时，习近平曾反复强
 调领导干部要有战略思维和战略眼光。特别是当前中国经济发展已经进入新常态，向形态更
 高级、分工更复杂、结构更合理阶段演化，更需要一大批有国际视野的企业家。
*** DONE 据说，这件事习近平牵挂了20多年http://news.ifeng.com/a/20160721/49482422_0.shtml
    CLOSED: [2016-07-22 Fri 21:31]
    :LOGBOOK:
    - State "DONE"       from "STARTED"    [2016-07-22 Fri 21:31]
    :END:
 “没有轰轰烈烈的大建设，闽宁扶贫协作都是从一件件小事做起，久久为功。”马国林说。
** DONE 习近平主持深改组会议 通过6个文件http://news.ifeng.com/a/20160722/49536294_0.shtml
   CLOSED: [2016-07-22 Fri 21:31]
    :LOGBOOK:
    - State "DONE"       from "STARTED"    [2016-07-22 Fri 21:31]
    CLOCK: [2016-07-22 Fri 21:19]--[2016-07-22 Fri 21:31] =>  0:12
    :END:
会议审议通过了《贫困地区水电矿产资源开发资产收益扶贫改革试点方案》、《关于加强文
化领域行业组织建设的指导意见》、《关于认罪认罚从宽制度改革试点方案》、《关于建立
法官、检察官惩戒制度的意见(试行)》、《关于省以下环保机构监测监察执法垂直管理制度
改革试点工作的指导意见》、《关于各地区各部门开展改革督察情况的报告》。

会议指出，开展贫困地区水电矿产资源开发资产收益扶贫改革试点，是扶贫开发工作的重大
制度创新。要以增加贫困人口资产性收益为目标，创新贫困地区水电矿产资源开发占用农村
集体土地补偿方式，围绕界定入股资产范围、明确入股受益主体、合理设置股权、完善收益
分配、加强股权管理和风险防控等重点任务，探索建立集体股权参与项目分红的资产收益扶
贫长效机制，走出一条资源开发和脱贫攻坚有机结合的新路子。

会议强调，加强文化领域行业组织建设，要坚持中国特色社会主义文化发展道路，始终把社
会效益放在首位，坚持积极引导发展和严格依法管理并重，通过明确职能定位、做好培育发
展、完善内部治理、强化规范管理等，健全党委统一领导、政府有效监管、分级负责、协调
配合的行业组织管理体制机制，引导行业组织在服务文化企事业单位、服务广大文化工作者、
服务行业发展、丰富群众文化生活等方面，更好发挥自身功能和独特优势，激发全社会文化
创造活力。

会议指出，完善刑事诉讼中认罪认罚从宽制度，涉及侦查、审查起诉、审判等各个诉讼环节，
要明确法律依据、适用条件，明确撤案和不起诉程序，规范审前和庭审程序，完善法律援助
制度。选择部分地区依法有序稳步推进试点工作。

会议强调，建立法官、检察官惩戒制度，对落实法官、检察官办案责任制，促进法官、检察
官依法行使职权，维护社会公平正义具有重要意义。要坚持党管干部原则，尊重司法规律，
体现司法职业特点，坚持实事求是、客观公正、坚持责任和过错相结合，坚持惩戒和教育相
结合，规范法官、检察官惩戒的范围、组织机构、工作程序、权利保障等，发挥惩戒委员会
在审查认定方面的作用。

会议指出，开展省以下环保机构监测监察执法垂直管理制度改革试点，目的是建立健全条块
结合、各司其职、权责明确、保障有力、权威高效的地方环保管理体制，确保环境监测监察
执法的独立性、权威性、有效性。要强化地方党委和政府及其相关部门的环境保护责任，注
意协调处理好环保部门统一监督管理和属地主体责任、相关部门分工负责的关系，规范和加
强地方环保机构和队伍建设，建立健全高效协调的运行机制。

会议强调，开展改革督察工作，要明确工作重点、盯住关键环节。督任务，就是要督促地方
和部门按照党中央要求谋划改革任务，既看方向准不准，又看任务实不实，是不是能够结合
实际，真正解决问题。督进度，就是要根据改革的阶段性目标和时间表、路线图，既督促改
革方案及时出台、抓紧落实，又督察相关改革任务配套跟进，抓好进度统筹，加强政策衔接。
督成效，就是要把改革举措放到实践中去检验，让基层来评判，让群众来打分，看改革是否
促进了经济社会发展，是否促进社会公平正义，是否给人民群众带来获得感。察认识，就是
要看思想工作有没有做深入，广大党员、干部特别是领导干部有没有从党和国家工作大局出
发认识和理解改革、关心和支持改革，是不是自觉站在改革全局高度正确看待局部利益关系
调整，形成推进改革的思想自觉和行动自觉。察责任，就是要看改革主体责任是不是划分清
楚，有没有理解到位、落实到位，是不是做到了各司其职、各负其责又相互协作。察作风，
就是要对照“三严三实”要求，督察各级干部特别是领导干部是不是坚持实事求是、求真务
实，是不是以改革促进派、实干家的标准要求自己，以严和实的作风谋划改革、落实改革。

会议指出，当前和今后一个时期，要按照把改革主体框架搭建起来这一阶段性目标，排出督
察优先顺序，聚焦重点难点。要抓问题要害，做到眼睛向下、脚步向下，既要发现实施中的
共性问题，也要关注群众反映强烈的热点难点问题，找出症结，提出对策。要抓整改落实，
督促真抓真改，对改革抓得实、有效果的要表扬，对执行不力、落实不到位的要问责追责。
要抓统筹联动，完善督察职能，发挥社会和群众监督作用，做到上下贯通、内外结合。

** DONE 习近平再提“头等大事” 干货全在这儿http://news.ifeng.com/a/20160416/48479065_0.shtml
   CLOSED: [2016-07-23 Sat 04:12]
   :LOGBOOK:
   - State "DONE"       from "STARTED"    [2016-07-23 Sat 04:12]
   CLOCK: [2016-07-23 Sat 03:52]--[2016-07-23 Sat 04:12] =>  0:20
   :END:
*** 继往开来，掌舵扬帆：习近平治国理政思想的四大逻辑http://news.ifeng.com/a/20160108/46991127_0.shtml
*** 习近平谈“为官不为”3种情况：要不等不拖尽快扭转http://news.ifeng.com/a/20160510/48741140_0.shtml
*** 习近平为领导干部传授“三字诀内功”http://news.ifeng.com/a/20160511/48750971_0.shtml
“深”字诀

领导干部工作水平和质量提高的源泉是不断地学习和实践。习近平强调，要“坚持学习、学
习、再学习，坚持实践、实践、再实践”。

一句话中将学习和实践强调三遍，可见他对此之重视；复述三遍，亦有层层递进之意。

“深”学才能弄清。习近平在山东考察时说，不要事情还没弄明白就盲目推进。身为领导干
部要弄明白哪些事情？习近平指出，该中央统一部署的不要抢跑，该尽早推进的不要拖宕，
该试点的不要仓促推开，该深入研究后再推进的不要急于求成，该得到法律授权的不要超前
推进。

弄明白这些事情，学习大政方针、法律法规、系列讲话就一定要“深”。习近平强调，学习
重在学懂弄通，不能心浮气躁、浅尝辄止、不求甚解。

在改革进入攻坚期和深水区的历史关口，一个个新问题、新课题不断摆在我们面前，从前的
办法常常不够用，甚至不管用了。这就要求各级领导干部更加深入地学习中央的战略布局和
新的发展理念，不断领悟，努力当好“行家里手、内行领导”。

“深”学才能修身。习近平还强调，各种文史知识，中国优秀传统文化，领导干部也要学习，
以学益智，以学修身，以学增才。

古人说，“腹有诗书气自华”。深入学习是提升精神境界、形成人格力量非常重要的途径。
习近平指出，学史可以看成败、鉴得失、知兴替；学诗可以情飞扬、志高昂、人灵秀；学伦
理可以知廉耻、懂荣辱、辨是非。

学用相长，学用皆“深”。实践离不开深入的调查研究。焦裕禄有一句名言：“吃别人嚼过
的馍没味道。”只有自己把情况摸清吃透，对“张家长、李家短”都做到心中有数，才能把
工作做到家、做到位。

习近平在正定工作时就经常骑着自行车下乡。从滹沱河北岸到滹沱河以南的公社去，每次骑
到滹沱河沙滩就得扛着自行车走。习近平说，虽然辛苦一点，但确实摸清了情况，同基层干
部和老百姓拉近了距离、增进了感情。

习近平说过，当县委书记一定要跑遍所有的村，当市委书记一定要跑遍所有的乡镇，当省委
书记一定要跑遍所有的县市区。这正是要求领导干部打好深入调研的基本功，搞好规划，做
到因势利导，避免眉毛胡子一把抓。

学习和实践都要遵循“深”的要求，这二者也并不是孤立的。学在于用，用也是学。“客里
空”和蛮干盲干都是不可取的。习近平指出，要在“干中学、学中干，学以致用、用以促学、
学用相长”。

“实”字诀

“只有干在实处，才能走在前列。”习近平始终认为，不抓落实，再美好的蓝图也是空中楼
阁。他要求抓住群众最关心的问题，扎扎实实办实事。

有这样一段往事：1983年初，尚在寒冬腊月，习近平和时任正定县长的程宝怀专程到石家庄
市寻访一位研发医用化妆品的科研工作者。因不知道对方具体住址，他们就挨家挨户询问，
到了晚上十点多还没找着，习近平扯起嗓门沿着大街小巷高喊对方的名字，终于找到了人。
他们一直谈到凌晨，对方当场答应，很快携带科研项目落户正定，一年就为正定带来30多万
元的利润。

这只是习近平为政经历中的一件小事，却深刻反映出习近平实干为民的为政准则。实干，既
是实现蓝图的唯一途径，也是民心衡量的具体标尺。真正把工作干在实处，需要有爱心、有
决心、有本心。

“实”，就是“一枝一叶总关情”。习近平曾引用过郑板桥的一首诗：“衙斋卧听萧萧竹，
疑是民间疾苦声。些小吾曹州县吏，一枝一叶总关情。”道出了一个共产党员应有的情怀：
“格外关注、格外关爱、格外关心”困难群众，时刻把他们的安危冷暖放在心上。

常怀这样的爱民之心，才能做到“民之所好好之，民之所恶恶之”。才能够自觉从人民利益
出发，既不沉浸在“文山会海”中使虚劲、务虚功，又不搞华而不实、劳民伤财的“形象工
程”。

“实”，就是“一切从实际出发”。要实干，就要坚持实事求是。谋划的事业和工作都要符
合实际情况。不能好高骛远、脱离实际。更不能为了一己私利而说假话、做假账、报假政绩。

在正定时，习近平就曾与时任县委副书记的吕玉兰顶着压力，如实向上级反映征购粮食负担
过重的问题，争取到粮食年征购量减免2800万斤，使正定得以减轻负担，卸下包袱，轻装前
进。

到福建宁德后，习近平坚持一切从实际出发，因地制宜解决了许多实际问题。针对“大黄鱼
之乡”的独特优势，他集中资源组织科研攻关，解决大黄鱼不能人工养殖的问题，大大增加
了农民收入。

“实”，就是“敢教日月换新天”。真正实干的干部应该是群众的“主心骨”，要在关键时
刻能够豁得出来，顶得上去。绝不满足于做四平八稳的“太平官”。

习近平要求把学习弘扬焦裕禄精神作为一条红线贯穿始终。焦裕禄身上就体现着这种“敢教
日月换新天”的坚定意志。“拼上老命大干一场，决心改变兰考面貌。”“活着没有治好沙
丘，死了也要看着把沙丘治好。”这种意志与决心，生动体现了焦裕禄的实干精神与责任担
当。

“阔”字诀

“修其心治其身，而后可以为政于天下。”对领导干部而言，个人的修养水平至关重要。习
近平在十八届中央纪委第三次全会上指出，共产党人特别是领导干部都应该心胸开阔。在数
次讲话中，习近平分别诠释了领导干部心胸开阔的三重境界，对领导干部个人修养的提高寄
望甚深。

“要有胸怀，能容人容事”。民主集中制是党的根本组织原则，也是党的优良传统和工作惯
例。然而，民主不够，集中不够的问题却仍在一些领导班子中存在、滋长。民主不够者，把
“班长”当成“家长”，个人说了算；而集中不够者则互不买账、互不服气，造成内耗。无
论是民主不够还是集中不够，都严重影响了工作的效率和质量。

习近平在中央党校县委书记研修班学员座谈会上，妙用三组词语，揭示了民主集中制的核心
内涵：总揽不包揽、分工不分家、放手不撒手。如何达到这三点要求？习近平强调说，要有
胸怀，能容人容事，注意听取班子成员的意见。

领导干部能容人容事才便于把各方面的智慧集中起来，才能够让“谔言”上陈。“千人之诺
诺，不如一士之谔谔。”在班子工作中，有人及时“咬咬”耳朵、扯扯袖子，是防止工作失
误，发现隐患风险的重要保证，是我党多年以来的宝贵经验。

习近平指出，批评和自我批评是一剂良药，是对同志、对自己的真正爱护。他形象地说，不
能把我们防身治病的武器给丢掉了。

“功成不必在我”。习近平强调，对定下来的工作部署，要一抓到底、善始善终。要有“功
成不必在我”的境界，像接力赛一样，一棒一棒接着干下去。

习近平如此强调，更是如此垂范。2002年，针对福建长汀水土流失严重问题，时任福建省长
的习近平率先提出建设生态省的战略构想，使福建成为全国第一批生态建设试点省。经过10
多年持之以恒的努力，长汀百万亩荒山重披绿衣，福建也成为全国唯一的水、空气、生态环
境全优的省份。

2004年，习近平在浙江推广武义县在村支部、村委会之外设立“村务监督委员会”的经验，
建立了村级权力的制衡机制，实现了看得见摸得着的村务监督。基层民主不再是抽象的概念。
2010年，全国人大常委会修改了村民委员会组织法，明确规定“村应当建立村务监督委员会
或者其他形式的村务监督机构”。

许多工作都不可能一蹴而就，需要的是久久为功、利在长远的恒心和耐力，需要领导干部心
中有责，像习近平强调的那样，“不贪一时之功，不图一时之名”，“一张蓝图绘到底”，
“一茬接着一茬干”。

“常怀忧患之思，常念人民之托”。古语云：“从善如登，从恶如崩。”说的是为善不易，
但内心防线一旦被攻破，就会一泻千里。

习近平曾这样提醒领导干部：“各种诱惑、算计都冲着你来，各种讨好、捧杀都对着你去，
往往会成为‘围猎’的对象。”在这样的环境下工作，就必须要有政治上的“定海神针”。

习近平要求党的干部，不论在什么地方、在哪个岗位上工作，都要经得起风浪考验，不能在
政治方向上走岔了、走偏了。他将世界观、人生观、价值观比喻为“总开关”，告诫领导干
部要志存高远，始终心系党、心系人民、心系国家，自觉坚持党性原则。

习近平常说，为“官”一任，就要造福一方，要“常怀忧患之思，常念人民之托”。只有志
存高远才能对个人的名誉、地位、利益想得透、看得淡；“打掉内心的小算盘”才能保持
“见善如不及，见不善如探汤”的作风和人格，与合格共产党员的标准真正契合。
** DONE 习近平告诫干部该敬畏什么
   CLOSED: [2016-08-16 二 10:22]
   :LOGBOOK:
   - State "DONE"       from "STARTED"    [2016-08-16 二 10:22]
   :END:
http://news.ifeng.com/a/20160816/49784445_0.shtml
*** 一、敬畏人民

“水能载舟，亦能覆舟”。人心向背关系党的生死存亡，敬畏之心须臾不可忘却。越是成就
辉煌，越需要保持对人民的谦逊敬畏之心。邓小平同志曾指出，共产党员“一怕党，二怕群
众，三怕民主党派，总是好一些。”这里的“怕”，就是敬畏之心。敬畏人民，就是作为掌
权者的领导干部要对人民群众赋予的权力心生敬畏，既要严谨持重、毫不懈怠地运用权力去
为人民谋利益，又要老老实实、诚诚恳恳地去接受人民群众对权力运行的监督。习近平强调，
各级党员干部要在“对待人民赋予权力上始终保持敬畏之心”。
**** 敬畏人民，就要坚持人民立场，敬畏人民的历史主体地位。
 人民是历史的创造者，是真正的英雄。毛泽东同志说：“人民，只有人民，才是历史的创
 造者。”人民是认识活动的主体、实践活动的主体，也是评价实践成果的价值主体。坚持
 人民立场，敬畏人民的历史主体地位，体现了马克思主义政党的本色，是马克思主义政党
 区别于其他政党的显著标志。中国共产党95年的发展历程，就是党领导人民艰苦创业的历
 史，就是人民群众历史主体地位得到充分尊重的历史。一切为了人民，一切依靠人民是我
 们党不断夺取胜利的根本保证，是党从小到大、从弱变强、从革命党到执政党转变的决定
 性因素。习近平指出：“人民立场是中国共产党的根本政治立场，是马克思主义政党区别
 于其他政党的显著标志。党与人民风雨同舟、生死与共，始终保持血肉联系，是党战胜一
 切困难和风险的根本保证，正所谓‘得众则得国，失众则失国’。”
**** 敬畏人民，就要牢记手中的权力是人民赋予的，坚持权为民所用。

领导干部的权力是从哪里来的？有些人可能会认为:“是上级给的”，“是政府给的”，
“是党给的”。这些回答没有弄清楚权力的真正来源。现代民主政治的基本原则是“人民主
权”，即人民应当掌握国家最高权力，人民是一切政治权力的来源和基础。习近平指出：
“马克思主义权力观，概括起来是两句话:权为民所赋，权为民所用。”我国宪法第一条明
文规定:“中华人民共和国的一切权力属于人民。”“人民主权”意即国家的一切权力属于
人民，意味着人民是国家的主人，各级领导干部都是人民的公仆，是受人民委托，为人民办
事的，他们的权力是人民赋予的。人民和干部的这种关系是由社会主义国家性质所决定，是
不容颠倒的。
党章明确指出:“党的干部是党的事业的骨干，是人民的公仆。”既然人民群众是权力的所
有者、委托者，作为权力受托者的党员干部，在行使权力时就理应忠实于人民，接受人民的
监督。党员干部的权力不是自封的，也不是无限的，而是人民赋予的，必须在授权范围内活
动，对人民群众负责，为人民掌好权、用好权。
**** 敬畏人民，就要坚持心中有民、人民至上的执政理念，全心全意为人民服务。
民心是最大的政治，得民心者，得天下。中国共产党从成立之日起，就把全心全意为人民谋利益作为自
己的根本宗旨和行为准则。立党为公，执政为民，清正廉洁，诚心诚意为人民谋利益，这是
我们党受到人民群众拥护、领导人民夺取革命和建设事业胜利的奥秘所在。党的十八大报告
指出：“为人民服务是党的根本宗旨，以人为本、执政为民是检验党一切执政活动的最高标
准。”习近平指出：“全党同志要把人民放在心中最高位置，坚持全心全意为人民服务的根
本宗旨，实现好、维护好、发展好最广大人民根本利益，把人民拥护不拥护、赞成不赞成、
高兴不高兴、答应不答应作为衡量一切工作得失的根本标准，使我们党始终拥有不竭的力量
源泉。”

 图为：2013年6月28日，中共中央总书记、国家主席、中央军委主席习近平在全国组织工作
 会议上发表重要讲话。
*** 二、敬畏组织
**** “组织”是党的生命线。
 马克思曾说：“只有在集体中，个人才能获得全面发展其才能的手
 段，也就是说，只有在集体中才可能有个人自由。”中国共产党是按照民主集中制原则建立
 起来的科学严密的为民组织，具有巨大的组织优势。作为党组织中的“关键少数”——领导干
 部执掌着人民赋予党的执政权和国家立法权、行政权、司法权等公权力，作用非常关键，必
 须对党组织有敬畏之心。一旦目无组织、目无法纪，个人凌驾于组织和法纪之上，必定会行
 为失范、放纵妄为，给党和人民事业造成严重伤害。因此，领导干部必须敬畏组织，敬畏组
 织的纪律、规章，敬畏组织的监督、教育；要心怀感恩，感念组织的培养、教育和信任，把
 敬畏之心转化成为兢兢业业、忠于职守、义无反顾的工作情怀，把敬畏之心当作履行职责、
 为官从政的基本底线。
**** 敬畏组织，就要摆正个人与组织的关系，始终牢记自己是组织的普通一员。
 组织的培养是干部成长的外在因素和客观条件。习近平指出：“好干部不会自然而然产生。
 成长为一个好干部，一靠自身努力，二靠组织培养”。有个别领导干部，摆不正个人与组
 织的关系，被提拔了，不是认为自己能耐大，就是觉得自己“上面有人”。实际上，对领
 导干部来说，进步离不开组织的培养，没有了组织，纵有天大本事也毫无用武之地；背离
 了组织，再多的荣耀也会化为乌有。
**** 敬畏组织，就要强化组织观念，坚持个人服从组织。
强化组织观念，是共产党人的必修课程，也是每一名党员的基本政治品质。个人服从组织，
被党章列为民主集中制基本原则之一，位居“四个服从”之首。革命先辈视死如归，正是把
服从组织奉为信仰，把卫护组织视若生命。对党员来说，服从组织既是天职，也是纪律。目
前，党内无组织无纪律的问题还比较多。一些党员干部，拿功劳当资本，自恃能力强贡献大，
端架子开条件，精于算计；一些领导干部，拿资历要待遇，组织没提拔有意见，岗位不满意
有牢骚，待遇不合意有怨言，甚至闹情绪撂挑子，搞软对抗；还有的领导干部，把分管领域
当私人领地，针插不进水泼不进，搞起独立王国，进行非组织活动。凡此种种，严重损害了
党的威信，侵蚀了党和人民的整体利益。对党员干部来说，必须把个人服从组织、下级服从
上级摆在更高位置，这是组织原则；重大事项必须向组织请示报告，这是党性要求；组织交
办的任务、作出的决定，贯彻落实不打折扣，这是组织纪律。习近平指出：“必须遵循组织
程序，重大问题该请示的请示，该汇报的汇报，不允许超越权限办事；必须服从组织决定，
决不允许搞非组织活动，不得违背组织决定。”
*** 三、敬畏法纪
**** 没有规矩不成方圆，党纪国法是每个党员干部的戒尺。
 马克思曾指出：“我们现在必须完全保持党的纪律，否则一切都会陷入淤泥中。”法律面
 前人人平等，纪律面前没有特权，党纪国法的红线不能逾越。遵纪守法是领导干部从政的
 底线，也是安身立命的最基本要求、最基本职责和最基本素养。近来，中央和地方查处了
 一批违法违纪领导干部，原因虽然很多；但对法纪缺乏最起码的敬畏是一个非常重要的原
 因。因此，领导干部必须尊重法纪的神圣，心存敬畏、手握戒尺，带头遵纪守法，从程序
 和制度上规范权力、约束权力，在任何情况下坚持做到不越界、不越轨，拒腐蚀，永不沾。
 习近平指出：“领导干部要把对法治的尊崇、对法律的敬畏转化成思维方式和行为方式，
 做到在法治之下、而不是法治之外、更不是法治之上想问题、作决策、办事情。党纪国法
 不能成为‘橡皮泥’、‘稻草人’，违纪违法都要受到追究。”
**** 领导干部必须敬畏法律。
法律，是限制公权力的利器。领导干部要牢记法律红线不可逾越、法律底线不可触碰，带头
遵守法律、执行法律，带头营造办事依法、遇事找法、解决问题用法、化解矛盾靠法的法治
环境。谋划工作要运用法治思维，处理问题要运用法治方式，说话做事要先考虑一下是不是
合法。习近平指出：“各级领导干部尤其要弄明白法律规定我们怎么用权，什么事能干、什
么事不能干，心中高悬法律的明镜，手中紧握法律的戒尺，知晓为官做事的尺度。”习近平
强调：“领导干部要做尊法的模范，带头尊崇法治、敬畏法律；做学法的模范，带头了解法
律、掌握法律；做守法的模范，带头遵纪守法、捍卫法治；做用法的模范，带头厉行法治、
依法办事。”
**** 领导干部必须敬畏党规党纪。
纲纪不彰，党将不党，国将不国。党的各项纪律规矩是“带电的高压线”，要牢固树立法治
意识、制度意识、纪律意识，懂法纪、明规矩，知敬畏、存戒惧，形成尊崇制度、遵守制度、
捍卫制度的良好氛围。中共中央印发的《中国共产党廉洁自律准则》和《中国共产党纪律处
分条例》，为共产党人立起了道德的高线和纪律的底线。共产党人必须遵守党纪党规，《条
例》以负面清单的方式，列举了共产党员不能做、不能违反的情形。党员干部，要做尊崇党
纪党规的模范，强化党的意识、纪律意识、规矩意识，自觉用党章和党规党纪约束自己的言
行，守住法规底线，依法行使权力。习近平指出：“要以上率下，从中央政治局常委会、中
央政治局、中央委员会做起，从各地区各部门党委（党组）做起，从高级干部做起，对党绝
对忠诚，模范遵守党章，严格按党的制度和规矩办事，夙兴夜寐为党和人民工作，任何时候
都不搞特权，都不破坏党的制度和规矩。”

 “凡善怕者，必身有所正，言有所规，行有所止，偶有逾矩，亦不出大格。”习近平指出：
 “领导干部工作上要大胆，用权上则要谨慎，常怀敬畏之心、戒惧之意，自觉接受纪律和
 法律的约束。”只有心存敬畏、手握戒尺，才能更好地行使权力，确保权力为人民服务，
 无愧于党和人民的重托。

** DONE 习近平：问责不能有怜悯之心 要较真
   CLOSED: [2016-08-16 二 10:22]
   :LOGBOOK:
   - State "DONE"       from "STARTED"    [2016-08-16 二 10:22]
   :END:
** DONE 习近平选人用人新理念
   CLOSED: [2016-08-18 四 17:40]
   :LOGBOOK:
   - State "DONE"       from "STARTED"    [2016-08-18 四 17:40]
   CLOCK: [2016-08-18 四 17:37]--[2016-08-18 四 17:40] =>  0:03
   :END:
“为政之要，莫先于用人。”选人用人问题是党和人民事业成败的关键问题。党的十八大以
来，以习近平同志为总书记的党中央面对新形势新任务，为实现“两个一百年”奋斗目标和
中华民族的伟大复兴，提出了一系列选人用人的新理念。习近平在庆祝中国共产党成立95周
年大会上指出：“伟大的斗争，宏伟的事业，需要高素质干部。我们要坚持德才兼备、以德
为先，坚持五湖四海、任人唯贤，坚持事业为上、公道正派，坚决防止和纠正选人用人上的
不正之风，把党和人民需要的好干部精心培养起来、及时发现出来、合理使用起来。” 请
随“学习中国”小编一起学习。
*** 一、坚持德才兼备以德为先
 “惟贤惟德，能服于人。”坚持德才兼备、以德为先，是我们党选人用人的根本标准，目的
 是要把政治上靠得住、工作上有本事、作风上过得硬、人民群众信得过的干部选拔到各级领
 导岗位上来。德，主要体现在理想信念、党性修养、道德品质、思想作风等方面；才，就是
 干事业的才能。坚持德才兼备、以德为先，凝练而科学地概括了党的干部应当具备的基本条
 件，既要求德与才缺一不可，又突出德的主导作用，强调选人用人要坚持以德为前提、以德
 为基础、以德为先决条件。
 三国时期，刘邵在《人物志》中曾提出“德才兼备，聪明平淡”的识人选人原则。在长期的
 革命、建设和改革实践中，我们党始终强调选人用人要坚持德才兼备，并把德放在首要位置。
 早在1938年，毛泽东同志在党的六届六中全会上就指出：“中国共产党是一个在几万万人的
 大民族中领导伟大革命斗争的党，没有多数德才兼备的干部，是不能完成其历史任务的。”
 周恩来同志也曾强调：“挑选干部的标准，政治标准与工作能力，两者缺一不可，而政治上
 可以信任是先决问题。”陈云同志也具体阐述过德才兼备标准，强调“德才并重，以德为
 主。”习近平指出：“好干部的标准，大的方面说，就是德才兼备。同时，好干部的标准又
 是具体的、历史的。不同历史时期，对干部德才的具体要求有所不同。革命战争年代，对党
 忠诚、英勇善战、不怕牺牲的干部就是好干部。社会主义革命和建设时期，懂政治、懂业务、
 又红又专的干部就是好干部。改革开放初期，拥护党的十一届三中全会确定的路线方针政策，
 有知识、懂专业、锐意改革的干部就是好干部。现在，我们提出政治上靠得住、工作上有本
 事、作风上过得硬、人民群众信得过等具体要求，突出了好干部标准的时代内涵。概括起来
 说，好干部要做到信念坚定、为民服务、勤政务实、敢于担当、清正廉洁。”习近平总书记
 用辩证统一的思维将“德”与“才”两者的关系有效揭示出来，使“德才兼备，以德为先”
 的用人原则更加具体并与时俱进。
 贯彻德才兼备、以德为先用人标准，要正确把握德与才的辩证关系。“才者，德之资也；德
 者，才之帅也。”德是才的统帅，决定着才的作用的方向；才是德的支撑，影响着德的作用
 的发挥。与才相比，德始终是第一位的。坚持德才兼备、以德为先的用人标准，就是选人用
 人要以德为前提、以德为先决，同样是能力强的干部，谁在德方面表现更加突出，就先提拔
 重用谁。对于在德方面存在严重问题的干部，本事再大也不能提拔重用。俗话说“就怕流氓
 有文化”，对已在领导岗位上且品德有问题的干部，应坚决拿下。当然，强调以德为先，也
 决不能忽视才。“功以才成,业由才广。”一个干部有德无才，政治上虽然可以信赖，但难
 以托付重任，也会让人民失望。在选拔任用干部工作中，必须把德才兼备、以德为先的用人
 标准作为一个整体来认识、来把握、来贯彻，既要把好政治关、又要把好才能关，真正把那
 些品德好、同时又有真才实学、能力突出的干部选拔上来。
 贯彻德才兼备、以德为先的用人标准，要把握好干部的德。朱熹云：“涵养、致知、力行三
 者，便是以涵养为首，致知次之，力行又次之。”“以德为先”，是用人标准的本质和核心，
 是选人用人的根本所在。“德”必须驭“才”，“才”必须从“德”，绝不能舍本逐末。现
 在一些干部出问题，多数不是出在“才”上，而是出在“德”上。人民群众对一些干部的意
 见，也主要集中在“德”上。要建立健全“德才兼备，以德为先”的考察监督机制，注重从
 履行岗位职责、完成急难险重任务、关键时刻表现、对待个人名利等方面考察干部的“德”，
 使选拔出来的干部组织放心、群众满意，不让老实人吃亏，不让投机钻营者得利。
*** 二、坚持五湖四海任人唯贤
“山不厌高，海不厌深；周公吐哺，天下归心。”坚持五湖四海、任人唯贤是我们党选人用
人的一条重要原则，是党的先进性的本质要求。在选人用人上，是坚持五湖四海、任人唯贤，
还是任人唯亲，拉山头，搞小圈子、小团体，是区分马克思主义政党与非马克思主义政党的
重要标准。中国共产党除了人民利益，没有自己的特殊利益。党的性质和宗旨，决定了我们
党在选人用人上能够做到五湖四海、任人唯贤，用崇高的事业感召人才、培养人才、造就人
才，为一切忠于人民、扎根人民、奉献人民的人提供施展才华的宽广舞台。
“古者圣王，甚尊尚贤而任使能，不党父兄，不偏贵富，不嬖颜色。”我国古代就有内举不
避亲，外举不避仇“任人唯贤”的历史典故。不论亲疏贵贱，不论资排辈，有能则举之。95
年来，我们党领导革命、建设和改革谱写了一个又一个光辉篇章，一条重要经验就是党在选
人用人上坚持“五湖四海”的原则，选贤任能，唯才是举，把各方面优秀人才都聚集到党的
事业中来。在党的历史上，虽然曾经有过王明、张国焘搞宗派主义而导致革命严重受损的教
训，但总体上，党内没有形成过强烈的派系斗争。毛泽东同志曾经指出，我们都是来自五湖
四海，为了一个共同的革命目标，走到一起来了。他强调：“共产党的干部政策，应是以能
否坚决地执行党的路线，服从党的纪律，和群众有密切的联系，有独立的工作能力，积极肯
干，不谋私利为标准，这就是‘任人唯贤’的路线。”邓小平同志曾语重心长地说：“小圈
子那个东西害死人呐！很多失误就从这里出来，错误就从这里犯起。”无数事实表明，坚持
“五湖四海”，就会群英荟萃，人才辈出，事业兴旺；搞小圈子，“一朝天子一朝臣”，必
然正气不彰，人心不齐，事业不振。
“我劝天公重抖擞，不拘一格降人才。”不拒众流，方为江海。在选人用人时，必须具备宽
阔胸怀，坚持五湖四海、任人唯贤，广开进贤之路。境界决定眼界，胸怀决定视野。要从党
和人民事业出发，扩大识人视野，拓宽选人渠道，广开进贤之路，不拘一格选人用人。境界
源自公心。“任天下之大，立心不可不公”。有了公心，就能坚持原则、敢于负责、不为个
人得失所困，不为人情关系所缚，不为歪风邪气所扰，对干部一视同仁；就能宽厚待人，着
眼于人的长处，取大功，略小过，不以个人好恶衡量人，不以完美标准苛求人，不以才华过
己妒忌人；就能抛弃个人恩怨，容忍和团结各方，启用那些与自己意见不同甚至曾经反对过
自己的人。坚持五湖四海，要敢于打破地域、身份、学历等方面的束缚，破除地方和部门保
护主义，在更大的范围内发现和选拔干部；要敢于破除论资排辈、平衡照顾的思维定势，坚
持以实绩论英雄、凭德才用干部，唯才是举、任人唯贤。中央机关公开遴选公务员自2011年
试行以来，今年已是第6年。中央机关公开选调公务员也在2014年首次开展的基础上，继续
试点。公开遴选和公开选调公务员，彰显了中央在干部工作上坚持“五湖四海、任人唯贤”
的决心。公开遴选与选调为优秀基层干部铺设了“高速路”、提供了“直通车”，在全党树
立重视基层一线、倾斜基层一线的干部工作导向，优化了中央机关公务员队伍来源，为建设
高素质中央机关公务员队伍开辟了良好渠道。习近平指出：“党和人民事业要不断发展，就
要把各方面人才更好使用起来，聚天下英才而用之。我们要以识才的慧眼、爱才的诚意、用
才的胆识、容才的雅量、聚才的良方，广开进贤之路，把党内和党外、国内和国外等各方面
优秀人才吸引过来、凝聚起来，努力形成人人渴望成才、人人努力成才、人人皆可成才、人
人尽展其才的良好局面。”
*** 三、坚持事业为上公道正派
“天行健，君子以自强不息；地势坤，君子以厚德载物。”坚持事业为上、公道正派是党对
组织工作的根本要求，是坚持正确用人导向的源头保证。所谓事业为上，就是要从党的事业
出发选拔干部，选用那些真正有事业心、能干事创业的干部，像习近平所说的，“坚持党的
原则第一、党的事业第一、人民利益第一，敢于旗帜鲜明，敢于较真碰硬，对工作任劳任怨、
尽心竭力、善始善终、善作善成。”所谓公道正派，就是选人用人要讲党性、讲原则，不讲
关系，不循私情。毛泽东同志说过：“在干部政策上要坚持正派的公道的作风，反对不正派
的不公道的作风，借此巩固党的统一团结。”组织部门改进作风，最核心的是坚持公道正派。
实践告诉我们，一个地方、一个单位，组织人事部门公道正派用人，投机钻营者就无机可乘，
搞歪门邪道的人就难有市场，否则，各种用人上的不正之风就会泛起和蔓延。
坚持事业为上、公道正派，要严格、准确、全面地把握中央提出的选人用人标准，坚决防止
选人用人的片面化。组织工作是为党和人民的事业选人，必须始终坚持“德才兼备、以德为
先”，坚持“五湖四海、任人唯贤”，坚持“信念坚定、为民服务、勤政务实、敢于担当、
清正廉洁”的好干部标准，做到全面准确把握，努力为党的事业负责。
坚持事业为上、公道正派，要严格程序，坚决反对选人用人上的形式主义。要切实防止程序
上都符合《干部任用条例》要求，而选出来的干部实际结果让群众不满意。要做到既走好程
序又要达到效果。一是要严肃工作纪律。组织部门一定要讲纪律、执公正，不要把选人搞成
作秀、造势。二是要立规矩、守规矩，没有规矩不成方圆。三是要吃透情况，真正了解干部。
古人讲，“世上最难之事莫过于知人”，要知人善任，全面了解干部情况。四是要正确集中，
防止假民主，要把干部选拔任用工作的规定程序落实到位。
坚持事业为上、公道正派，要着力选拔实绩突出的干部。古人说，“位必使当其德，禄必使
当其功，官必使当其能”。对广大干部来说，只有立足于“干”，才能称职尽责；对选人用
人来说，只有着眼于“干”，才能选出党的事业需要的干部。习近平指出：“要树立正确用
人导向，使那些对群众感情真挚、深得群众拥护的干部，那些说话办事有灼见、有效率的干
部，那些对上对下都实实在在、不玩虚招的干部，那些清正廉洁、公众形象好的干部，得到
褒奖和重用；使那些享乐思想严重、热衷于形式主义、严重脱离群众的干部，受到警醒和惩
戒，用为民务实清廉的良好形象凝聚党心民心。”
“尚贤者，政之本也。” 治国之要，首在用人。习近平指出：“用一贤人则群贤毕至，见
贤思齐就蔚然成风。选什么人就是风向标，就有什么样的干部作风，乃至就有什么样的党
风。”我们要坚持正确的选人用人原则，真正把优秀人才聚集到党和人民的事业中来。
*** http://news.ifeng.com/a/20160815/49778100_0.shtml

 党的问责工作是由党组织按照职责权限，追究在党的建设和党的事业中失职失责党组织和
 党的领导干部的主体责任、监督责任和领导责任。问责要真正发挥作用，就必须使真劲、
 动真格。习近平在十八届中央纪委六次全会上指出：“有权就有责，权责要对等。问责不
 能感情用事，不能有怜悯之心，要‘较真’、‘叫板’，发挥震慑效应。”他还强调：
 “党的十八大以来，我们在问责方面查了一些典型，体现了有权必有责、有责要担当、失
 职必追究，推动了‘两个责任’落实。”请随“学习中国”小编一起学习。


*** 一、有权必有责

**** 权力意味着责任，没有离开责任的权力，权责对等是普遍规则。
 从权责对等的原则来说，享
 有什么样的权力，就应承担相应的责任。如果权力大、责任小，容易导致权力的滥用；如果
 权力小、责任大，容易导致责任无法落实，工作虎头蛇尾、有头无尾。习近平指出：“有权
 就有责，权责要对等。无论是党委还是纪委或其他相关职能部门，都要对承担的党风廉政建
 设责任进行签字背书，做到守土有责。出了问题，就要追究责任。决不允许出现底下问题成
 串、为官麻木不仁的现象！不能事不关己、高高挂起，更不能明哲保身。自己做了好人，但
 把党和人民事业放到什么位置上了?如果一个地方腐败问题严重，有关责任人装糊涂、当好
 人，那就不是党和人民需要的好人！你在消极腐败现象面前当好人，在党和人民面前就当不
 成好人，二者不可兼得。”
 当前，少数地方和部门之所以产生党的领导弱化、党的建设缺失、全面从严治党不力、党的
 观念淡漠、组织涣散、纪律松弛等问题，归其根本在于一些党的领导干部没有正确认识权力
 与责任的关系，把两者分离开来，甚至只想要权力、不愿担责任。一些党组织党内政治生活
 失去原则性和战斗性，好人主义盛行，搞一团和气、不愿得罪人，基本不开展批评，即便批
 评也是抽象空洞的，包装了再包装，致使批评失去了锋芒，成为无的放矢。对共产党人来说，
 没有离开责任的权力，党和人民赋予权力时，更是压上了责任。针对党的一些领导干部不能
 正确认识权力与责任的关系，责任担当缺失问题，《中国共产党问责条例》明确规定：“党
 组织领导班子在职责范围内负有全面领导责任，主要负责人和直接主管的班子成员承担主要
 领导责任，参与决策和工作的其他成员承担重要领导责任。”这是对权责对等规则的充分肯
 定和对权责关系的明确规定。

 图为：2015年1月13日，中共中央总书记、国家主席、中央军委主席习近平在中国共产党第
 十八届中央纪律检查委员会第五次全体会议上发表重要讲话。

*** 二、有责要担当

**** 有责任就要有担当。
 对领导干部来说，权力越大，责任越重；责任越重，越要勇于担当。习
 近平明确指出，“忠诚干净担当是党对领导干部提出的政治要求”。习近平强调：“干部就
 要有担当，有多大担当才能干多大事业，尽多大责任才会有多大成就。不能只想当官不想干
 事，只想揽权不想担责，只想出彩不想出力。”

**** 担当，是党员干部职责所系、使命所在。
党95年的历史证明，担当精神是共产党人的魂，是
 党员的脊梁。革命战争年代，担当就是为民族独立和解放抛头颅洒热血，前赴后继，在所不
 辞；今天，担当是要把人民对美好生活的向往作为奋斗目标，对党和人民负责、为党和人民
 担责。习近平指出：“是否具有担当精神，是否能够忠诚履责、尽心尽责、勇于担责，是检
 验每一个领导干部身上是否真正体现了共产党人先进性和纯洁性的重要方面。”要进一步增
 强责任意识、使命意识、忧患意识，深刻认识到“无功就是过、庸碌就是错”，以担当为荣，
 以避事为耻。领导干部要以对党和人民事业高度负责精神，为党分忧、为人辛劳，勇于做事，
 敢于担责。要在大是大非面前敢于亮剑，在矛盾问题面前迎难而上，在危机困难关头挺身而
 出，面对歪风邪气敢于斗争。对党的事业、对人民群众有利的事，看准了就要大胆去做，奋
 勇向前。实践证明，哪个地区、部门有一个敢于担当、勇于负责的党组织，党的领导、党的
 建设、管党治党就会坚强有力，就能联系本地区本部门实际，真正把党的路线方针政策落到
 实处。习近平指出：“看一个领导干部，很重要的是看有没有责任感，有没有担当精神。好
 干部要在敢于担当中历练提高，努力创造无愧于时代的业绩。”

**** 担当与否最终要体现于行动，完成历史使命、践行党的宗旨必须有担当精神。
各级党组织要
 牢固树立政治意识、大局意识、核心意识、看齐意识，自觉向以习近平同志为总书记的党中
 央看齐，用担当的行动诠释对党和人民的忠诚。各级党委尤其是主要负责人要联系实际、从
 自身做起，以身作则、以上率下，手电筒对着自己照，不能只对着下级说事。要以眼里不揉
 沙子的认真劲儿，敢于较真碰硬，对腐败问题严重、不作为乱作为、群众反映强烈的，要严
 肃问责，一级抓一级，增强责任意识，激发担当精神，担当起该担当的责任。

 图为：2014年1月14日，中共中央总书记、国家主席、中央军委主席习近平在中国共产党第
 十八届中央纪律检查委员会第三次全体会议上发表重要讲话。

*** 三、失责必追究

**** 动员千遍，不如问责一次。
 要发挥问责利器作用，让失责必问、问责必严成为常态。对于党
 组织和党的领导干部违反党章和其他党内法规，不履行或者不正确履行职责的，应当予以严
 厉问责。只有依法依规强力问责，才能消除制度“破窗效应”，形成守土有责、守土尽责的
 良好氛围。习近平在十八届中央纪委六次全会上指出：“前年，我们对湖南衡阳发生的以贿
 赂手段破坏选举案件严肃问责，给予党纪政纪处分467人，移送司法机关处理69人。去年，
 我们又对南充拉票贿选案进行彻底调查，对全部477名涉案人员严肃处理。这两起案件性质
 极为恶劣，是对我们党和社会主义民主制度的挑战。坚决查处这些案件，实施严厉问责，体
 现了失职必究、执纪必严的鲜明态度。”

**** 实行全面问责。
 问责涉及到诸多方面的问题，要一网打尽，有多少就处理多少。《中国共产
 党问责条例》列出了予以问责的五种情况，涉及党的领导弱化、党的建设缺失、全面从严治
 党不力，党的观念淡漠、组织涣散、纪律松弛、不担当、不负责等突出问题，对党组织和党
 的领导干部的行为具有明确的指引作用。问责条例在列举问责情形时加上了“其他应当问责
 的失职失责情形”的条款，将一些新出现或新发现的应该被问责的情形，通过这个兜底条款
 来予以适用，保证了问责的全天候、全覆盖、无空档。习近平指出：“任何地方、部门、单
 位，发生了党的领导作用不发挥、贯彻党的路线方针政策走样、管党治党不严不实、选人用
 人失察、发生严重‘四风’和腐败现象、巡视整改不力等问题，就要抓住典型严肃追责。既
 追究主体责任、监督责任，又上查一级追究领导责任、党组织责任。”

**** 实行终身问责。
对失职失责性质恶劣、后果严重的，不论其责任人是否调离转岗、提拔或者
 退休，都要严肃问责，该打的板子都要打下去，决不搞下不为例、网开一面，这样才能保证
 失责必问真正落到实处。

**** 完善责任追究制度。
问责既要对事、也要对人，要问到具体人头上。习近平指出：“当前的
 一个问题是，抓安全事故等行政问责多、抓管党治党不力问责少，问责规定零散、内容不聚
 焦。要整合问责制度，健全问责机制，坚持有责必问、问责必严，把监督检查、目标考核、
 责任追究有机结合起来，实现问责内容、对象、事项、主体、程序、方式的制度化、程序
 化。”各级党组织和纪检机关要严格落实主体责任、监督责任，党的工作部门要各司其职、
 各负其责，各级领导干部要切实担负起领导责任，按照管理权限，实行分级负责。问责既要
 追究主体责任、监督责任，又要追究领导责任，是哪一级的责任就追究到哪一级，推动责任
 层层得到落实。习近平强调：“中央纪委要抓紧完善并严格执行责任追究办法，对每一个具
 体问题都要分清党委负什么责任、有关部门负什么责任、纪委负什么责任，健全责任分解、
 检查监督、倒查追究的完整链条，有错必究，有责必问。”
 问责是全面从严治党的应有之义和重要保证。习近平指出：“不明确责任，不落实责任，不
 追究责任，从严治党是做不到的。”要坚持利剑高悬、铁面问责，做到有责必履、失责必问、
 渎责必究，既要“较真”，又要“叫板”，真正使管党治党从宽松软走向严紧硬，推动全面
 从严治党取得新成效。
** 习近平文化建设的“六个一”<2016-09-22 Thu 08:06>
http://news.ifeng.com/a/20160921/50001766_0.shtml

** 王蒙解读习近平的文化思想
http://news.ifeng.com/a/20160921/50001772_0.shtml
