* take me hand
Take me hand
In my dreams
我的梦里
I feel your light
有你的光芒
I feel love is born again
爱再次绽放
Fireflies
萤火虫
In the moonlight
在月光里
Rising stars
如闪烁的繁星
Remember
还记得吗
The day
在那一天
I fell in love with you
我迷恋上了你
Darling won't you break
亲爱的，请不要伤害
My heart
我的心
Take my hand now
抓紧我的手
Stay close to me
靠近我的心
be my lover
成为我爱人
Won't you let me go
不要放开我的手
close your eyes now
闭上你的眼睛
And you will see
你将会看到
There's a rainbow
有道彩虹
For you and me
连接你我的心
As I wake up
当我醒来
I see your face
看到你的脸
I feel love is born again
爱再次绽放
Cherry blossom
樱桃盛开
Flying birds
飞翔的鸟儿
In the sky
在蓝天翱翔
Can't you see
你看见了吗
The sun
阳光
That is shining on the fields
在原野闪烁
Is it shining in
像闪烁在
Your heart
你的心
And I dream of you
你出现在我梦中
Every night
每个夜晚
Cause's there only you
因为只有你
In my mind
在我脑海里
Will you be
你愿成为
A stranger or a friend in my life
我生命中的陌生人或朋友
* 《dream it possible》

I will run, I will climb, I will soar，我奔跑，我攀爬，我会飞翔，
I’m undefeated，永不言败，
Jumping out of my skin, pull the chord，欣喜若狂，拉动琴弦，
Yeah Ibelieve it，哦，我相信。
The past, is everything we were don’t make us who we are，
往昔，逝去的光阴不会决定现在，
So I’ll dream, until I make it real, and all I see
is stars，
所以我们梦想，直到变成真，看到满天星光，
Its not until you fall thatyou fly，
不怕跌倒，所以飞翔，
When your dreams come alive you’re unstoppable，
当你的梦想成真，你是不可阻挡，
Take a shot, chase the sun, find the beautiful，
挥着翅膀，追逐太阳，寻找美丽，
We will glow in the dark turning dust to gold，
在黑暗中闪耀点石成金，
And we’ll dream it possible，
我们会梦想成真，
I will chase, Iwill reach, I will fly，
我追逐，我奔驰，我要飞翔，
Until I’m breaking, until I’m
breaking，
直到坠落，直到崩溃，
Out of my cage, like a bird in the night，
走出我的囚笼，像在黑夜里的莺，
I know I’m changing, I know I’m changing，
我知道我在变化，在蜕变，
In, into something big, better than before，
变成无比强大，从未有过，
Andif it takes, takes a thousand lives，
如果需要牺牲，需要无数的生命，
Then It’sworth fighting for，
那值得去奋斗，
Its not until you fall that you fly，
不怕跌倒，所以飞翔，
When your dreams come alive you’re unstoppable，
当你的梦想成真，你是不可阻挡，
Take a shot, chase the sun, find the beautiful，
挥着翅膀，追逐太阳，寻找美丽，
We will glow in the dark turning dust to gold，
在黑暗中闪耀点石成金，
Andwe’ll dream it possible，
我们会梦想成真，
From the bottom to the top，
从山谷到巅峰，
We’re sparking wild fire’s，
我们正在迸发野火，
Never quit and never stop，
永不放弃，永不停止，
The rest of our lives，
点燃未来，
From the bottom to the top，
从山谷到巅峰，
We’re sparking wild fire’s，
我们正在迸发野火，
Never quit and never stop，
永不放弃，永不停止，
Its not until you fall that you fly，
不怕跌倒，所以飞翔，
When your dreams come alive you’re unstoppable，
当你的梦想成真，你是不可阻挡，
Take a shot, chase the sun, find the beautiful，
挥着翅膀，追逐太阳，寻找美，
We will glow in the dark turning dust to gold，
在黑暗中闪耀点石成金，
And we’ll dream it possible possible，
我们会梦想成真。  
* Yesterday once more 
When I was yong， 当我年轻时，

I’d listen to the radio， 常听收音机， 
Waiting for my favorite songs。 等待心爱的歌曲。 
When they played I’d sing along， 听到播放时便随声歌唱。 
It made me smile。 这使我欢畅。 

Those were such happy times， 那时多么幸福的时刻！ 
And not so long ago。 就在不久以前。 
How I wondered where they’d gone。 我想知道他们曾去何处， 
But they’re back again， 但我所有深爱的歌曲 
Just like a long lost friend。 他们现在又回来， 
All the songs I love so well。 正如老友失散又重聚。 

Every sha-la-la-la 每一句 sha-la-la-la 
Enery wo-wo still shines， 每一句 wo-wo 仍闪烁， 
Every shinga-linga-ling， 每一句 shinga-linga-ling， 
That they’restarting to sing so fine。他们又开始唱得如此动听。 

When they get to the part 当他们唱到一个地方 
Where he，s breaking her heart， 令她伤心断肠， 
It can really make me cry， 这真能叫我哭出来， 
Just like before， 正如从前一样， 
It’s yesterday once more。 仿佛昔日又重来 

Looking back on how it was 回头看 
In years gone by， 岁月如何消逝 
And the good time that I had 这些过去的好时光 
Makes today seem rather sad。 使今天显得令人哀伤。 
So much has changed。 变化多大啊！ 

It was songs of love 我向他们唱 
That I would sing to them， 爱的歌曲。 
And I’d memorize each word， 我会记住每一句歌词。 
Those old melodies 那些古老的曲调， 
Still sound so good to me， 在我听来还是那么好， 
As they melt the years away。 好像他们把岁月融消。 

Every sha-la-la-la 每一句 sha-la-la-la 
Enery wo-wo still shines， 每一句 wo-wo 仍闪烁， 
Every shinga-linga-ling， 每一句 shinga-linga-ling， 
That they’restarting to sing so fine。他们又开始唱得如此动听。 

All my best memories 我所有美好的记忆 
Come back clearly to me。 清晰的重现。 
Some can even make me cry， 有一些仍能使我哭出来， 
Just like before， 正如从前一样， 
It’s yesterday once more。 仿佛昔日又重来。 

Every sha-la-la-la 每一句 sha-la-la-la 
Enery wo-wo still shines， 每一句 wo-wo 仍闪烁， 
Every shinga-linga-ling， 每一句 shinga-linga-ling， 
That they’restarting to sing so fine。他们又开始唱得如此动听。
