* 文件学习
** DONE 国家十三五规划
   CLOSED: [2017-10-14 Sat 11:50]
   :LOGBOOK:
   - State "DONE"       from "STARTED"    [2017-10-14 Sat 11:50]
   CLOCK: [2017-10-14 Sat 10:39]--[2017-10-14 Sat 11:50] =>  1:11
   :END:
*** 第六篇 拓展网络经济空间 
      牢牢把握信息技术变革趋势，实施网络强国战略，加快建设数字中国，推动信息技术与经
    济社会发展深度融合，加快推动信息经济发展壮大。


**** 第二十五章 构建泛在高效的信息网络 

       加快构建高速、移动、安全、泛在的新一代信息基础设施，推进信息网络技术广泛运用，
     形成万物互联、人机交互、天地一体的网络空间。

***** 第一节 完善新一代高速光纤网络 

        构建现代化通信骨干网络，提升高速传送、灵活调度和智能适配能力。推进宽带接入光纤
      化进程，城镇地区实现光网覆盖，提供1000兆比特每秒以上接入服务能力，大中城市家庭用
      户带宽实现100兆比特以上灵活选择；98%的行政村实现光纤通达，有条件地区提供100兆比
      特每秒以上接入服务能力，半数以上农村家庭用户带宽实现50兆比特以上灵活选择。建立畅
      通的国际通信设施，优化国际通信网络布局，完善跨境陆海缆基础设施。建设中国－阿拉伯
      国家等网上丝绸之路，加快建设中国－东盟信息港。

***** 第二节 构建先进泛在的无线宽带网 

        深入普及高速无线宽带。加快第四代移动通信（4G）网络建设，实现乡镇及人口密集的行
      政村全面深度覆盖，在城镇热点公共区域推广免费高速无线局域网（WLAN）接入。加快边远
      山区、牧区及岛礁等网络覆盖。优化国家频谱资源配置，加强无线电频谱管理，维护安全有
      序的电波秩序。合理规划利用卫星频率和轨道资源。加快空间互联网部署，实现空间与地面
      设施互联互通。

***** 第三节 加快信息网络新技术开发应用 

        积极推进第五代移动通信（5G）和超宽带关键技术研究，启动5G商用。超前布局下一代互
      联网，全面向互联网协议第6版（IPv6）演进升级。布局未来网络架构、技术体系和安全保
      障体系。重点突破大数据和云计算关键技术、自主可控操作系统、高端工业和大型管理软件、
      新兴领域人工智能技术。

***** 第四节 推进宽带网络提速降费 

        开放民间资本进入基础电信领域竞争性业务，形成基础设施共建共享、业务服务相互竞争
      的市场格局。深入推进“三网融合”。强化普遍服务责任，完善普遍服务机制。开展网络提
      速降费行动，简化电信资费结构，提高电信业务性价比。完善优化互联网架构及接入技术、
      计费标准。加强网络资费行为监管。

**** 第二十六章 发展现代互联网产业体系 

       实施“互联网+”行动计划，促进互联网深度广泛应用，带动生产模式和组织方式变革，
     形成网络化、智能化、服务化、协同化的产业发展新形态。

***** 第一节 夯实互联网应用基础 

        积极推进云计算和物联网发展。鼓励互联网骨干企业开放平台资源，加强行业云服务平台
      建设，支持行业信息系统向云平台迁移。推进物联网感知设施规划布局，发展物联网开环应
      用。推进信息物理系统关键技术研发和应用。建立“互联网+”标准体系，加快互联网及其
      融合应用的基础共性标准和关键技术标准研制推广，增强国际标准制定中的话语权。

***** 第二节 加快多领域互联网融合发展 

        组织实施“互联网+”重大工程，加快推进基于互联网的商业模式、服务模式、管理模式
      及供应链、物流链等各类创新，培育“互联网+”生态体系，形成网络化协同分工新格局。
      引导大型互联网企业向小微企业和创业团队开放创新资源，鼓励建立基于互联网的开放式创
      新联盟。促进“互联网+”新业态创新，鼓励搭建资源开放共享平台，探索建立国家信息经
      济试点示范区，积极发展分享经济。推动互联网医疗、互联网教育、线上线下结合等新兴业
      态快速发展。放宽融合性产品和服务的市场准入限制。 

**** 第二十七章 实施国家大数据战略

     把大数据作为基础性战略资源，全面实施促进大数据发展行动，加快推动数据资源共享开放
     和开发应用，助力产业转型升级和社会治理创新。

***** 第一节 加快政府数据开放共享

      全面推进重点领域大数据高效采集、有效整合，深化政府数据和社会数据关联分析、融合利
      用，提高宏观调控、市场监管、社会治理和公共服务精准性和有效性。依托政府数据统
      一共享交换平台，加快推进跨部门数据资源共享共用。加快建设国家政府数据统一开放
      平台，推动政府信息系统和公共数据互联开放共享。制定政府数据共享开放目录，依法
      推进数据资源向社会开放。统筹布局建设国家大数据平台、数据中心等基础设施。研究
      制定数据开放、保护等法律法规，制定政府信息资源管理办法。

***** 第二节 促进大数据产业健康发展

      深化大数据在各行业的创新应用，探索与传统产业协同发展新业态新模式，加快完善大数据
      产业链。加快海量数据采集、存储、清洗、分析发掘、可视化、安全与隐私保护等领域关键
      技术攻关。促进大数据软硬件产品发展。完善大数据产业公共服务支撑体系和生态体系，加
      强标准体系和质量技术基础建设。

**** 第二十八章 强化信息安全保障

     统筹网络安全和信息化发展，完善国家网络安全保障体系，强化重要信息系统和数据资源保
     护，提高网络治理能力，保障国家信息安全。
***** 第一节 加强数据资源安全保护
      建立大数据安全管理制度，实行数据资源分类分级管理，保障安全高效可信应用。实施
      大数据安全保障工程，加强数据资源在采集、存储、应用和开放等环节的安全保护，加
      强各类公共数据资源在公开共享等环节的安全评估与保护，建立互联网企业数据资源资
      产化和利用授信机制。加强个人数据保护，严厉打击非法泄露和出卖个人数据行为。
***** 第二节 科学实施网络空间治理
      完善网络空间治理，营造安全文明的网络环境。建立网络空间治理基础保障体系，完善
      网络安全法律法规，完善网络信息有效登记和网络实名认证。建立网络安全审查制度和
      标准体系，加强精细化网络空间管理，清理违法和不良信息，依法惩治网络违法犯罪行
      为。健全网络与信息突发安全事件应急机制。推动建立多边、民主、透明的国际互联网
      治理体系，积极参与国际网络空间安全规则制定、打击网络犯罪、网络安全技术和标准
      等领域的国际合作。
***** 第三节 全面保障重要信息系统安全

      建立关键信息基础设施保护制度，完善涉及国家安全重要信息系统的设计、建设和运行监督
      机制。集中力量突破信息管理、信息保护、安全审查和基础支撑关键技术，提高自主保障能
      力。加强关键信息基础设施核心技术装备威胁感知和持续防御能力建设。完善重要信息系统
      等级保护制度。健全重点行业、重点地区、重要信息系统条块融合的联动安全保障机制。积
      极发展信息安全产业。
*** 信息化重大工程
**** （一）宽带中国
     建设高速大容量光通信传输系统，实施宽带乡村和中西部地区中小城市基础网络完善工程，
     扩容互联网国际出入口带宽，部署第四代移动通信（4G）及后续演进技术，在有需求的区域
     全面深度覆盖。
**** (二)物联网应用推广

     建设物联网应用基础设施和服务平台，推进物联网重大应用示范工程建设，广泛开展物联网
     技术集成应用和模式创新，丰富物联网应用服务。

**** （三)云计算创新发展

     支持公有云服务平台建设，布局云计算和大数据中心，提升云计算解决方案提供能力。推动
     制造、金融、民生、物流、医疗等重点行业云应用服务，不断完善云计算生态体系。

**** （四）“互联网+”行动

     推动“互联网+”创业创新、协同制造、智慧能源、普惠金融、益民服务、高效物流、电子
     商务、便捷交通、绿色生态、人工智能以及电子税务、便民司法、教育培训、科普、地理信
     息、信用、文化旅游等行动，不断拓展融合领域。

**** （五）大数据应用

     建设统一的开放平台，逐步实现公共数据集开放，鼓励企业和公众发掘利用。推动政府治理、
     公共服务、产业发展，技术研发等领域大数据创新应用。推进贵州等大数据综合试验区建设。

**** （六）国家政务信息化

     加快国家统一电子政务网络建设应用，完善审批监管、信息信息、公共资源交易、价格举报
     信息等平台。加快国家基础信息资源库建设应用。

**** （七）电子商务

     支持电子商务基础设施建设，促进重点领域电子商务创新和融合应用，推动杭州等跨境电子
     商务综合试验区建设，打造电子商务国际大通道。

**** （八）网络安全保障

     实施国家信息安全专项，提高关键信息基础设施、重要信息系统和涉密信息系统安全保障能
     力及产业化支撑水平。实施国家网络空间安全重大科技项目，突破核心芯片、基础软件、关
     键元器件及重点整机系统等关键技术，构建国家网络空间安全和保密技术保障体系。

** [[http://www.gov.cn/zhengce/content/2015-05/19/content_9784.htm][中国制造2025]]

   （五）健全多层次人才培养体系。
   　　加强制造业人才发展统筹规划和分类指导，组织实施制造业人才培养计划，加大专业技
   术人才、经营管理人才和技能人才的培养力度，完善从研发、转化、生产到管理的人才培养
   体系。以提高现代经营管理水平和企业竞争力为核心，实施企业经营管理人才素质提升工程
   和国家中小企业银河培训工程，培养造就一批优秀企业家和高水平经营管理人才。*以高层次、
   急需紧缺专业技术人才和创新型人才为重点，实施专业技术人才知识更新工程和先进制造卓
   越工程师培养计划，在高等学校建设一批工程创新训练中心，打造高素质专业技术人才队伍。
   强化职业教育和技能培训，引导一批普通本科高等学校向应用技术类高等学校转型，建立一
   批实训基地，开展现代学徒制试点示范，形成一支门类齐全、技艺精湛的技术技能人才队伍。*
   鼓励企业与学校合作，培养制造业急需的科研人员、技术技能人才与复合型人才，深化相关
   领域工程博士、硕士专业学位研究生招生和培养模式改革，积极推进产学研结合。加强产业
   人才需求预测，完善各类人才信息库，构建产业人才水平评价制度和信息发布平台。建立人
   才激励机制，加大对优秀人才的表彰和奖励力度。建立完善制造业人才服务机构，健全人才
   流动和使用的体制机制。采取多种形式选拔各类优秀人才重点是专业技术人才到国外学习培
   训，探索建立国际培训基地。加大制造业引智力度，引进领军人才和紧缺人才。

** [[http://www.miit.gov.cn/n1146290/n1146392/c5168620/content.html][国家信息化发展战略纲要]]

** [[http://www.gov.cn/zhengce/content/2015-07/04/content_10002.htm][国务院关于积极推进“互联网+”行动的指导意见]]

** [[http://www.gov.cn/zhengce/content/2016-05/20/content_5075099.htm][国务院关于深化制造业与互联网融合发展的指导意见]]

** 信息产业发展指南


   “十二五”以来，我国信息产业发展势头良好，产业体系不断完善，产业链掌控能力显著提
   高，正日益成为我国创新发展的先导力量、驱动经济持续增长的新引擎、引领产业转型和融
   合创新的新动力、提升政府治理和公共服务能力的新手段。当前，以信息技术与制造业融合
   创新为主要特征的新一轮科技革命和产业变革正在孕育兴起，必须紧紧抓住这一机遇，加快
   发展具有国际竞争力、安全可控的现代信息产业体系，为建设制造强国和网络强国打下坚实
   基础。为科学引导“十三五”时期信息产业持续健康发展，根据“十三五”规划纲要、《中
   国制造2025》、《国家信息化发展战略纲要》、《国务院关于积极推进“互联网+”行动的
   指导意见》（国发〔2015〕40号）、《国务院关于深化制造业与互联网融合发展的指导意见》
   （国发〔2016〕28号）等的部署，经国务院同意，特制定本指南，实施期限为2016-2020年。


*** 一、发展回顾及面临形势
    ****（一）“十二五”发展回顾。
    “十二五”时期我国信息产业发展取得显著成效，比较优势和竞争能力发生深刻变化。一是
    产业规模平稳较快增长。2015年信息产业收入规模达到17.1万亿元。彩电、手机、微型计算
    机、网络通信设备等主要电子信息产品的产量居全球第一，电话用户和互联网用户规模居世
    界首位。二是结构优化升级取得实质进展。2015年，软件和信息技术服务业占信息产业收入
    比重由2010年的16%提高到25%，移动数据及互联网业务收入占电信业收入比重提升至27.6%。
    电子信息产品竞争力明显提升，对外贸易顺差稳步扩大。三是技术创新能力大幅提升。国内
    信息技术专利申请总量已超过304.8万件，其中发明专利申请总量和授权量分别超过193.7万
    件和7.48万件。具有自主知识产权的时分同步码分多址长期演进技术（TD-LTE Advanced）
    成为第四代移动通信（4G）国际主流标准之一，并实现大规模商用。集成电路设计水平达到
    16/14纳米，制造业实现28纳米小批量生产。多条高世代平板显示生产线建成投产。安全可
    靠软硬件实现重要突破，一批骨干企业创新能力和竞争力大幅提升。四是信息基础设施加速
    升级。宽带接入实现从非对称数字用户线路（ADSL）向光纤入户（FTTH）的跨越，移动通信
    实现从3G向4G的升级。新增七个国家级骨干直联点建成开通，网间互通质量和效率大幅提升。
    中国铁塔公司成立，电信基础设施共建共享迈向新高度。五是信息产业支撑引领作用全面凸
    显。信息产业快速发展带动两化融合水平稳步提升，互联网对经济社会促进作用逐步显现。
    2015年网络零售交易额达3.88万亿元，一批互联网龙头企业建立开放平台，成为带动大众创
    业、万众创新的新渠道、新推力。智慧城市、智慧交通、远程医疗、互联网金融等新业态不
    断涌现，加速经济社会运行模式深度变革。

    但与此同时，我国信息产业核心基础能力依然薄弱，核心芯片和基础软件对外依存度高，要
    素成本增长较快，关键领域原始创新和协同创新能力急需提升，引领产业发展方向、把握产
    业发展主导权的能力不强；产品供给效率与质量不高，与发达国家相比，呈现出“应用强、
    技术弱、市场厚、利润薄”的倒三角式产业结构；信息技术融合应用深度不够，新产品、新
    业态、新模式发展面临体制机制障碍；网络与信息安全形势依然严峻，安全保障能力亟待提
    升。

**** （二）“十三五”发展形势。
     新一轮技术创新引领产业新变革。全球信息产业技术创新进入新一轮加速期，云计算、大数
     据、物联网、移动互联网、人工智能、虚拟现实等新一代信息技术快速演进，单点技术和单
     一产品的创新正加速向多技术融合互动的系统化、集成化创新转变，创新周期大幅缩短，硬
     件、软件、服务等核心技术体系加速重构，新业态、新模式快速涌现，我国信息产业实现跨
     越发展的战略机遇窗口正在打开。同时，信息技术与制造、材料、能源、生物等技术的交叉
     渗透日益深化，我国已形成的局部技术优势将面临新的挑战。


     全球信息产业竞争加剧分工格局调整。发达国家依然占据信息产业价值制高点，在大力构建
     信息经济新优势的同时，积极以信息技术为手段推动再工业化进程，争取未来全球高端产业
     发展主导权。跨国企业加快重组步伐，以期在工业互联网、人工智能、智能制造等领域形成
     新布局。一些信息产业新兴国家（地区）加快谋篇，积极参与全球产业再分工，承接资本及
     技术转移。我国已成为全球最大的信息产品消费市场和制造基地，在互联网、通信服务、设
     备与终端产品等领域形成了一批龙头企业，在全球产业分工体系中呈跃升态势，具备了跨越
     发展的条件。同时，也面临发达国家“高端回流”和发展中国家“中低端分流”的双向挤压，
     以及国内要素禀赋深刻变化、新旧增长动力转换的严峻挑战，转型升级任务更加紧迫艰巨。

     国家重大战略实施对信息产业发展提出新要求。从世界范围看，信息产业日益成为重塑经济
     发展模式的主导力量，创新融合、智能绿色、开放共享成为全球经济发展新特征。在我国，
     信息产业也日益成为实施创新驱动战略、推进供给侧结构性改革的关键力量。创新驱动、制
     造强国、网络强国、“互联网+”、军民融合等一系列国家重大战略的实施和居民消费升级，
     要求加快完善信息基础设施、强化信息核心技术能力、提升信息消费体验、加强信息安全保
     障、优化网络空间治理、繁荣信息产业生态，发挥更强有力的引领和支撑作用。

*** 二、总体要求
**** （一）指导思想。
     全面贯彻党的十八大、十八届二中、三中、四中、五中、六中全会精神和习近平总书记系列
     重要讲话精神，认真落实党中央、国务院决策部署，按照“五位一体”总体布局和“四个全
     面”战略布局，牢固树立创新、协调、绿色、开放、共享的发展理念，推进供给侧结构性改
     革，以支撑制造强国和网络强国等重大战略实施为使命，以加快建立具有全球竞争优势、安
     全可控的信息产业生态体系为主线，坚持追赶补齐与换道超车并举、技术突破与强化应用并
     重、对外合作与体系创新结合、全面发展与重点推进统筹，着力强化科技创新能力、产业基
     础能力和安全保障能力，突破关键瓶颈，优化产业结构，提升产品质量，完善基础设施，深
     化普遍服务，促进深度融合应用，拓展网络经济空间，加快重点项目建设和关键环节发展，
     带动全面提升信息产业发展质量效益和核心竞争力，推动经济社会持续健康发展，支撑全面
     建成小康社会奋斗目标如期实现。

**** （二）基本原则。
     ——创新引领。坚持把创新作为引领发展的第一动力。着力提升核心基础软硬件创新能力，强
     化关键共性技术研发供给，推动产业链协同创新。强化企业创新主体地位和主导作用，培育
     一批具有国际竞争力的创新型领军企业。

     ——融合发展。坚持软件与硬件、技术与产品、产业链上下游等融合协同发展，完善产业生态
     体系。促进军民用信息技术和产品深度融合，推动信息产业与其他行业跨界融合、集成创新，
     加快传统行业改造提升，大力发展新业态、新模式。推动数据开放，加强共建共享，提高资
     源利用效率。

     ——市场主导。充分发挥市场在资源配置中的决定性作用，更好发挥政府作用，强化企业主体
     地位和市场应用牵引，深入推进简政放权、放管结合、优化服务，加快转变政府职能，为信
     息产业创新发展和提质增效营造更加良好的市场环境。

     ——开放合作。坚持走出去与引进来相结合。进一步提升双向开放合作水平，优化信息网络国
     际布局，提升产业国际化布局和运营能力，积极推动建立国际互联网发展新秩序，加强国际
     间信息产业技术、标准、人才及产能合作。

     ——安全可控。统筹发展和安全，以安全保发展、以发展促安全。强化法治建设、标准制定、
     技术支撑和市场监管，壮大信息安全产业，推进行业自律和社会监督，健全关键信息基础设
     施安全保障体系。

     ——绿色低碳。坚持绿色发展、循环发展和低碳发展。推进信息技术在生产各环节的应用，加
     速传统产业绿色化转型。加快提升电子信息产品和设备能效，不断降低信息基础设施能耗水
     平。提高电子信息产品回收再利用水平。

**** （三）发展目标。

     到2020年，具有国际竞争力、安全可控的信息产业生态体系基本建立，在全球价值链中的地
     位进一步提升。突破一批制约产业发展的关键核心技术和标志性产品，我国主导的国际标准
     领域不断扩大；产业发展的协调性和协同性明显增强，产业布局进一步优化，形成一批具有
     全球品牌竞争优势的企业；电子产品能效不断提高，生产过程能源资源消耗进一步降低；信
     息产业安全保障体系不断健全，关键信息基础设施安全保障能力满足需求，安全产业链条更
     加完善；光网全面覆盖城乡，第五代移动通信（5G）启动商用服务，高速、移动、安全、泛
     在的新一代信息基础设施基本建成。


     2020年信息产业发展主要指标

     注：1.[ ]内数值为年均增速；
     2.信息产业企业进入世界500强企业数量指标，指中国大陆进入《财富》500强的企业数量。

*** 三、主要任务


**** （一）增强体系化创新能力。

     构建先进的核心技术与产品体系。围绕产业链体系化部署创新链，针对创新链统筹配置资源
     链，着力在云计算与大数据、新一代信息网络、智能硬件等三大领域，提升体系化创新能力。
     瞄准重大战略需求和未来产业发展制高点，支持专业机构研究发布重点领域技术创新指南，
     提出瓶颈短板清单及优先级，引导市场主体创新突破。加强产学研用研发力量协调，统筹利
     用国家科技计划（专项、基金等），支持关键核心技术研发和重大技术试验验证，强化关键
     共性技术研发供给。加快信息产业军民融合深度发展，在技术研发、产业布局中充分考虑军
     用需求和国防布局，着力加强军民联合攻关，在优先满足军工需要的同时带动民口技术进步
     和产业发展。加强前沿领域重大布局，重点在未来网络、量子计算、平流层通信、卫星通信、
     可见光通信、车联网、地海空天一体化网络、人工智能、类脑计算等关键领域，集中优势资
     源开展原始创新和集成创新，增强新供给创造能力，抢占产业技术发展主动权和制高点。

     建设高水平创新载体和服务平台。充分利用已有创新资源，探索政产学研用联合的新机制新
     模式，在集成电路、基础软件、大数据、云计算、物联网、工业互联网等战略性核心领域布
     局建设若干创新中心，开展关键共性技术研发和产业化示范。强化企业技术创新主体地位和
     主导作用，支持优势企业建设一批高水平技术中心和创新实验室，支持企业联合高校、科研
     机构等建设重点领域产学研用联盟，积极参与和组建开源社区，支持企业牵头承担国家重大
     科技研发和产业化项目。整合优化信息科技资源，积极发挥行业协会/联盟、标准化组织、
     中介组织和智库在战略与政策研究、统计分析、公共服务等方面的作用，建设和提升一批技
     术创新、成果转化、标准规范、计量测试、认证检测、市场推广等公共服务平台。

     强化标准体系建设与知识产权运用。进一步优化国家标准、行业标准、军用标准体系结构，
     支持发展团体标准，加快构建产业化导向、军民通用的新一代信息技术标准体系，研究制定
     智能硬件、传感器、智慧家庭、虚拟现实、云计算、大数据、太阳能光伏、锂离子电池等领
     域综合标准化技术体系。加快基础标准、通用标准、安全标准、测试方法以及重点产品标准
     制修订工作，不断提升技术、能耗、环保、质量、安全等方面规范要求。积极参与国际标准
     化战略规划、政策和规则的制定，以国际标准提案为核心，推动我国更多信息通信领域标准
     成为国际标准；加快转化我国产业发展急需的国际先进标准，推动国际国内标准接轨。建立
     专利导航产业发展工作机制，加强信息产业关键核心技术知识产权储备和战略布局，推动技
     术创新成果的知识产权转移转化；鼓励市场主体组建产业知识产权联盟，建立知识产权联合
     创造、协同运用、共同保护和风险分担的机制；研究制定重点领域知识产权运营策略，健全
     运营服务体系，促进知识产权的收储、许可和转让；支持引导行业组织、产业联盟加强知识
     产权分析评议，防控知识产权风险。

**** （二）构建协同优化的产业结构。
     打造协同发展产业链。依托优势骨干企业，建设和完善信息网络、云计算、大数据、物联网、
     工业互联网、智能终端、电子制造关键装备等一批重要产业链，以“硬件+软件+内容+服务”为
     架构建设形成若干具有国际竞争力的产业生态。支持有条件的企业通过兼并重组、股权投资
     等方式开展产业链上下游垂直整合和跨领域价值链横向拓展，提升价值创造能力和核心竞争
     力。以产业集群为中心，实施商标品牌发展战略，提升产业链整体质量水平，加强团体标准、
     知识产权和公共服务平台建设，强化商标品牌宣传与营销，打造一批具有国际影响力的产业
     集群区域品牌。

     提升产业基础能力。围绕基础软硬件、关键制造工艺、关键电子基础材料和工艺装备等，制
     定重点领域瓶颈清单，组织实施重点领域“一揽子”突破计划。依托制造业质量提升专项行
     动，针对信息产业重点产品，组织攻克一批长期困扰产品质量提升的关键共性质量技术。加
     强可靠性和可测性设计、试验验证，积累准确有效的工艺参数数据，推广采用先进质量管理
     方法、先进成型和加工方法、在线计量检测装置等，提高电子信息装备、材料和工艺技术的
     可靠性、一致性、稳定性和有效性。制定和提升一批急需的国家计量基标准，加强信息产业
     相关国家计量测试中心建设，构建信息产业计量测试服务体系。推动基础软硬件、基础材料
     和工艺装备企业与下游企业对接，组织开展首台（套）、首批次示范应用，加快安全可靠基
     础软硬件产品的市场化应用和推广。

     增强企业创新活力。在信息产业重点领域设立市场化运作的投资基金，支持企业开展兼并重
     组和引技引智，提高企业利用全球资源和开拓国际市场的能力和水平，形成以大企业集团为
     核心、集中度高、分工细化、协作高效的产业组织形态。进一步完善和落实支持中小企业发
     展的财税、金融政策，推动小微企业创业创新基地建设，大力扶持初创期创业创新型企业发
     展。引导中小企业专注细分市场，激发中小企业创新活力，发展一批专精特“隐形冠军”企
     业。充分发挥各类平台作用，支持信息产业中小企业创新发展，引导大中小企业建立更紧密
     协作关系。支持企业将具有核心竞争力的专利技术向标准转化，提高企业综合竞争力。引导
     企业树立质量为先、信誉至上的经营理念，切实增强质量和品牌意识，培育和弘扬精益求精
     的工匠精神。全面提升行业企业信息技术运用能力，加快个性化制造、网络化协同制造、智
     能制造等生产方式变革，创新发展新模式，推动企业向价值链高端转型。

     优化产业空间布局。贯彻落实国家区域发展总体战略和主体功能区规划，引导地方发挥比较
     优势，形成集成电路、基础软件、平板显示、智能终端、信息技术服务、云计算、大数据等
     重点领域生产力差异化发展格局。重点推动长江经济带、珠三角、京津冀等创新资源密集地
     区率先突破，建设具有全球竞争力的信息产业创新高地。支持中西部地区立足自身优势承接
     信息产业转移，重点支持若干基础和条件较好的中心城市提高研发能力和产业层次，在特色
     领域形成差异化竞争优势。合理引导人才、技术、资金、政策等要素资源集聚，建设一批信
     息产业领域国家新型工业化产业示范基地，不断提高软件名城建设水平。扎实推进数据中心
     布局优化，促进数据中心合理利用。

     推动产业绿色发展。支持促进企业升级生产技术及工艺，鼓励企业开发绿色产品，推行电子
     信息产品绿色设计，降低电子信息产品生产和使用能耗，引导绿色生产，促进绿色消费。持
     续提高电子信息产品中有毒有害物质的限量要求，严格检测环节，确保限用物质含量符合国
     家标准。研发支撑数据中心能源使用效率（PUE）量值等效可溯源的计量测试技术、方法和
     装置。鼓励企业研发应用节能型服务器设备，采用高压直流、自然风冷等新型节能技术发展
     绿色云计算数据中心。加快现有数据中心、基站等信息网络设施的节能改造，鼓励老旧高耗
     能设备淘汰退网和绿色节能新技术应用。推动废弃电器电子产品处理与资源化利用技术研发，
     制定废弃电器电子产品及重点拆解产物资源综合利用相关标准，搭建和推广基于互联网的回
     收服务信息平台，推动生产者履行废弃电器电子产品回收处理相关责任，鼓励专业化回收处
     理企业发展，促进再制造产业规模化发展。推动统一绿色产品标准、认证、标识体系的建立
     实施。

**** （三）促进信息技术深度融合应用。

     推动信息技术与制造业融合创新。推动制造业、“互联网+”和“双创”紧密结合，加快新
     一代信息技术更大范围、更深程度融合渗透和创新应用，推动制造业智能化、绿色化、服务
     化发展。建立完善智能制造和两化融合管理标准体系，全面推进两化融合管理体系贯标。推
     进“数控一代”示范工程，加快突破传感器、可编程逻辑控制器（PLC）、工业控制系统等
     智能制造核心信息设备，提升安全可靠水平。开展智能制造试点示范。推进信息物理系统
     （CPS）关键技术研发及产业化，构建综合验证平台，开展行业应用测试和试点示范。以工
     业云、工业大数据、工业电子商务和系统解决方案等为重点，开展制造业与互联网融合发展
     试点示范，培育一批面向重点工业行业智能制造的系统解决方案领军企业。实施工业云及工
     业大数据创新应用试点，建设一批高质量的工业云服务和工业大数据平台，推广个性化定制、
     网络协同制造、远程运维服务等智能制造新模式。建设大型制造企业“双创”平台和为中小
     企业服务的第三方“双创”服务平台，营造大中小企业协同共进的“双创”新生态。依托强
     基工程，面向智能制造关键环节应用需求，重点扶持发展一批应用效果好、技术创新强、市
     场认可度高的工业软件，推动先进适用工业软件在重点行业应用普及。积极推动用信息技术
     改造提升制造业，着力提高产品和服务附加值。

     积极推进“互联网+”行动。依托互联网平台，大力发展众创、众包、众扶、众筹，促进互
     联网和经济社会融合发展。建立“互联网+”标准体系，加快互联网及其融合应用的基础共
     性标准和关键技术标准研制推广。整合政府部门、电信企业、互联网企业、行业机构等各类
     资源，集成资源申请、能力开放、技术支撑、创业孵化、测试认证、实验环境、业务咨询等
     创业创新服务，提升信息通信企业对“双创”服务平台的支撑能力。推进“互联网+”安全
     生产，提升安全生产重点领域企业的全过程、全链条在线监测和预警预控能力，强化跨部门、
     跨区域信息共享与业务协同。开展新型网络经济培育行动，支持互联网企业、信息技术服务
     企业、制造企业联合打造服务产业转型的平台经济模式，加快人工智能、云计算、大数据等
     在经济活动中的发展应用，强化对智慧交通、智慧能源、智慧环保、高效物流、益民服务、
     普惠金融、智慧医疗、现代农业等的支撑，发展基于电网的通信设施和新型业务。培育信息
     消费新业态，拓展网络经济新空间。

     加快发展信息技术服务。围绕政务、金融、能源、交通、环保、安全生产、电子商务、数字
     内容等关键领域，提升信息技术服务企业的咨询设计、软件开发、集成实施、运行维护和测
     试验证能力。支持信息技术企业突破业务建模、远程智能检查、大规模资源调度管理、自动
     化运维、数据治理等关键技术，发展互联网运维服务、网络众包服务、微服务、智能服务等
     新模式、新业态，加强对区块链、人工智能、虚拟现实、增强现实等新兴技术在行业系统解
     决方案中的应用推广，加快向高端价值服务提供商转型。选择信息技术服务业集聚发展的城
     市或区域，开展面向制造业的信息技术服务应用示范。总结行业先进实践经验，制定完善信
     息技术服务相关规范。加快综合集成和智能运维平台研发和产业化进程，提升信息技术服务
     保障能力。实施信息技术服务标准化工作五年行动计划，完善和推广信息技术服务标准
     （ITSS），鼓励企业加快服务标准化和产品化。

**** （四）建设新一代信息基础设施。

     加快高速光纤宽带网建设。引导建成一批光网城市，基本完成老旧小区宽带接入铜缆替换，
     鼓励企业通过引入新技术、更新老旧光缆等，进一步提升光纤宽带网络高速传送、灵活调度
     和智能适配能力，消除宽带网络接入“最后一公里”瓶颈。进一步优化互联网骨干网络架构，
     推动网间互通扩容和质量提升。开展新型交换中心试点，完善全方位、多层次、立体化的网
     络互联体系。推动地面数字电视覆盖网和超高清交互式电视网络设施建设。实施电信普遍服
     务补偿机制，推动相关企业加快对农村地区宽带网络覆盖和能力提升，基本实现行政村光网
     全覆盖，并逐步向有条件的自然村延伸。

     推动宽带无线接入网络升级演进。继续推动长期演进（LTE）网络建设，实现深度和广度覆
     盖，提升网络质量。加速低速率和低频谱利用率网络退网和频率重耕，发展认知无线电技术，
     拓宽4G网络发展空间，实现频分双工长期演进LTE FDD和TD-LTE融合发展。加强无线局域网
     （WLAN）新技术研究，鼓励在城镇热点公共区域推广WLAN接入，提升WLAN与移动通信网络的
     协同融合能力。推动5G网络研发和应用。加快边远山区、牧区及岛礁等的网络覆盖。

     提升应急通信保障能力。着力提升应急通信保障网络能力、可用性和覆盖范围。完善国家应
     急通信保障、装备储备体系。支持应急体系相关单位加强应急指挥手段建设，推动与应急通
     信指挥系统信息共享。加强国家应急通信设施建设和通信保障队伍建设。完善天空地一体的
     应急通信保障网络，推广突发事件预警信息系统应用。加强应急通信技术支撑能力建设。

     增强卫星通信网络及应用服务能力。统筹规划卫星通信发展，加快卫星通信标准制定和更新，
     推进关键部件、卫星整机、通信终端和系统、地面信息基础设施协调建设和军民融合发展，
     推进天地一体化信息网络建设。构建宽带卫星电子政务网、防灾和应急卫星通信网，建设多
     种卫星端站，补充地面网络难以布设地区的通信需求。推动卫星通信发展，逐步拓展建立区
     域化、商业化的卫星通信服务体系，持续完善北斗导航技术，加快推动基于北斗的高精度时
     频设备研发及应用，实现产业安全可控。创新北斗导航应用模式，发展位置服务，开展应用
     示范。

     加强下一代互联网应用和未来网络技术创新。推动下一代互联网改造升级和大规模商用，实
     现互联网协议第4版（IPv4）向第6版（IPv6）的平滑过渡和业务互通。加强未来网络顶层设
     计，加强未来网络长期演进的战略布局和技术储备，开展网络体系架构、安全性和标准研究，
     重点突破软件定义网络（SDN）/网络功能虚拟化（NFV）、网络操作系统、内容分发等关键
     技术，推动关键技术试验验证，组织开展规模应用试验。


**** （五）提升信息通信和无线电行业管理水平。

     创新互联网行业管理。坚持政策引导和依法管理并举、鼓励支持和规范发展并行，促进互联
     网持续健康发展。创新监管体系，积极运用大数据等先进技术加强对市场主体监管，形成覆
     盖资源、接入、网络、业务各层面的互联网行业全周期管理体系。完善互联网基础资源管理
     体系，严格落实网站、域名、IP地址和电话实名制。加快推广使用IPv6地址，推动开放IPv6
     国际连接。建立和完善多部门联动管理机制，建立新业务备案和发展指引制度，加强互联网
     与实体经济融合新型业务联合管理。坚持放管结合，推进以信用体系为代表的全流程监管支
     撑体系建设，强化事中事后监管。建立互联网市场主体信用评价体系，依托国家企业信息公
     示系统建立企业信息归集共享机制，健全守信联合激励和失信联合惩戒制度，推进市场分级
     预警，营造公平诚信的市场环境。加强服务质量监管，保护用户权益和个人信息。积极引导
     社会力量参与互联网行业管理，完善行业规范与自律公约，引导行业协会和第三方机构开展
     行业自律、社会监督、评估认证等活动，推进形成政府主导，多方参与的共同治理格局。

     完善电信行业管理。着力夯实电信业基础性支撑地位，建设高品质信息基础设施，提升行业
     服务能力和质量。加快开展电信普遍服务试点工作。深入推进网络提速降费，推动简化电信
     资费结构，提高电信业务性价比，规范企业经营、服务和收费行为。进一步放开竞争性领域
     市场准入，抓好自贸区电信领域开放试点，推动对港澳等地区开放合作。

     优化无线电频率和卫星轨道资源管理。优化国家频谱资源配置，加强无线电频谱管理，维护
     安全有序的电波秩序。科学规划和合理配置无线电频率资源，统筹重点业务部门以及战略性
     新兴产业发展的中长期用频需求，促进宽带中国、信息消费、“中国制造2025”和“互联网
     +”行动涉及的无线电业务发展。加强对无线电频率和卫星轨道资源使用的基础性、前瞻性、
     战略性重大问题及相关技术研究，加强卫星频率和轨道资源的可用性论证，做好卫星网络资
     料的国际申报、协调及登记工作。开展无线电频谱使用评估，促进频谱资源有效开发利用。
     深化台站管理，加强事中事后监管。加大无线电管理基础和技术设施建设投入，加强无线电
     监管能力建设，实现广域、泛在的城区无线电监测网络覆盖，增强电波秩序维护能力。

**** （六）强化信息产业安全保障能力。

     完善网络与信息安全管理制度。加紧制定实施关键信息基础设施保护、数据安全、工业互联
     网安全等领域的部门规章和规范性文件。健全网络与信息安全标准体系，推动出台5G、物联
     网、云计算、大数据、智能制造等新兴领域安全标准。加强安全可靠电子签名应用推广，推
     动电子签名法律效力认定。建立健全身份服务提供商管理制度。明确关键信息基础设施安全
     保护责任，完善涉及国家安全重要信息系统的设计、建设和运行监督机制，进一步加强对互
     联网企业所有或运营的重要网络基础设施和业务系统的网络安全监管。健全跨行业、跨部门
     的应急协调机制，切实提升网络与信息安全事件的预警通报、监测发现和快速处置能力。加
     强政府和企业之间的安全威胁信息共享。加快推动实施网络安全审查制度。

     加强大数据场景下的网络数据保护。探索建立大数据时代的网络数据保护体系，推动对网络
     数据的分级分类监管，强化网络数据全生命周期保护，制定网络数据保护管理政策。督促企
     业不断完善用户信息泄露社会公告制度，建立健全大数据安全信用体系。加快推动数据加密、
     防泄露、信息保密等专用技术的研发与应用，推动建立安全可信的大数据技术体系。

     推动信息安全技术和产业发展。着力突破关键基础软硬件和信息安全核心技术，增强漏洞挖
     掘修补、攻击监测溯源等能力，强化“互联网+”、5G、SDN等新技术、新业态的安全风险应
     对。实施国家信息安全专项，开展关键信息基础设施运行安全保护和要害信息系统网络安全
     试点示范。推动信息安全产品和服务的研发和产业化应用。充分发挥政府引导作用，加快培
     育骨干企业，发展特色优势企业，打造结构完整、层次清晰、竞争有力的产业格局。

     提升工业信息安全保障能力。建立健全工业信息安全政策和标准体系，针对重点行业制定安
     全管理政策以及管理指南、测评能力要求等安全标准。建立工业信息安全管理体系，完善工
     业信息安全检查评测和信息共享机制，推动开展安全检查、漏洞发布、信息通报等工作，营
     造安全的工业互联网环境。建设工业信息安全仿真、测试和验证平台，开展测试评估、安全
     验证等技术研发，推动安全新技术、新产品试点应用，提升工业信息安全技术保障能力。


**** （七）增强国际化发展能力。

     提升产业国际化发展水平。推动引资与引技、引智相结合，鼓励和支持信息产业企业与境外
     优势企业在研发创新、新产品开发、标准制定、品牌建设等高端环节开展合资合作，提高引
     进来层次。支持企业在境外设立研发中心，充分利用各种国际创新资源。结合国家重大战略
     实施，以信息基础设施建设、终端产品产能合作、重大工程总集成总承包等为牵引，带动产
     业链上下游企业、先进技术标准、信息网络设备、配套服务等体系化、集群化走出去。支持
     有条件的企业建设境外信息产业合作园区。提供企业走出去国别目录、项目对接等服务，引
     导金融机构开展金融服务，降低企业走出去风险。深入推动中文域名推广和使用。主动参与
     国际互联网标准制定，提高参与制定国际规则的能力及影响力。

     优化信息网络国际布局。依托“一带一路”战略，构建高效跨境信息通道，推动与周边国家
     信息通信设施互联互通，创新国际通信设施建设和运营模式，重点打通经中亚到西亚、经南
     亚到印度洋、经俄罗斯到欧洲等陆上通道，推进重点方向国际海缆建设。完善我国国际通信
     出入口布局，以亚非欧拉为主要方向提升我国国际互联网能力，加快推进海外网络服务提供
     点（PoP）和互联网数据中心（IDC）建设。推进电信企业设立海外分支机构，加强国际通信
     的质量监测和服务提升，为“走出去”中资企业及海外用户提供更完善、更优质信息服务，
     实现我国信息业务的海外运营和落地。

*** 四、发展重点


**** （一）集成电路。

     以重点整机和重大应用需求为导向，增强芯片与整机和应用系统的协同。着力提升集成电路
     设计水平，不断丰富知识产权（IP）核和设计工具，突破中央处理器（CPU）、现场可编程
     门阵列（FPGA）、数字信号处理（DSP）、存储芯片（DRAM/NAND）等核心通用芯片，提升芯
     片应用适配能力。加快推动先进逻辑工艺、存储器等生产线建设，持续增强特色工艺制造能
     力。掌握高密度封装及三维（3D）微组装技术，探索新型材料产业化应用，提升封装测试产
     业发展能力。加紧布局超越“摩尔定律”相关领域，推动特色工艺生产线建设和第三代化合
     物半导体产品开发，加速新材料、新结构、新工艺创新。以生产线建设带动关键装备和材料
     配套发展，基本建成技术先进、安全可靠的集成电路产业体系。实施“芯火”创新行动，充
     分发挥集成电路对“双创”的支撑作用。


**** （二）基础电子。

     大力发展满足高端装备、应用电子、物联网、新能源汽车、新一代信息技术需求的核心基础
     元器件，提升国内外市场竞争力。拓展新型显示器件规模应用领域，实现液晶显示器超高分
     辨率产品规模化生产、有源矩阵有机发光二极管（AMOLED）产品量产；突破柔性制备和封装
     等核心技术，完成量产技术储备，开发10英寸以上柔性显示器件。突破微机电系统（MEMS）
     微结构加工、高密度封装等关键共性技术，加快传感器产品开发和产业化。提升发光二极管
     （LED）器件性能，推动高端场控电力电子器件推广应用，开发下一代电力电子器件，支持
     典型领域推广应用。加强电子级多晶硅、高效太阳能电池及组件封装工艺创新和技术储备，
     提升光伏发电系统集成水平及储能设备配套水平。积极发展电子纸、锂离子电池、光伏等行
     业关键电子材料，重点突破高端配套应用市场。提升电子专用设备配套供给能力，重点发展
     12英寸集成电路成套生产线设备、新型薄膜太阳能电池生产设备、锂离子电池关键材料生产
     设备、新型元器件生产设备和表面贴装设备。研发半导体和集成电路、通信与网络、物联网、
     新型电子元器件、高性能通用电子等测试设备。


**** （三）基础软件和工业软件。
     建立安全可靠的基础软件产品体系，支持开源、开放的开发模式，重点推进云操作系统、云
     中间件、新型数据库管理系统、移动端和云端办公套件等基础软件产品的研发和应用。强化
     技术产品和终端应用协同互动，提升基础软件成熟度，加快集成适配优化。推动工业软件和
     工业控制系统核心技术和产品的研发及应用，重点突破军工、能源、化工等安全关键行业工
     业应用软件核心关键技术，构建先进产品体系，形成评测标准与规范；突破高档数控系统、
     现场总线、通信协议、高精度高速控制和伺服驱动等工业控制系统关键技术，推动中高端数
     控系统、伺服系统和控制系统研发。构建国家工业软件安全测试平台。加快工业大数据软件
     与平台布局，促进重要工业领域系统解决方案定制化深度应用，打造工业云应用服务体系。


**** （四）关键应用软件和行业解决方案。

     着力发展基于云计算、大数据、移动互联网、物联网等新型计算框架和应用场景的软件平台
     和应用系统。针对政府应用、公共服务、行业发展等重点需求，集中突破一批重点应用软件
     和行业解决方案，深化普及应用。支持软件和信息技术服务企业面向公共服务领域积极开展
     应用解决方案研发和信息技术服务，推动软件企业与传统行业企业深入合作，加快支撑传统
     行业转型升级的软件及解决方案发展和应用，培育一批综合性解决方案提供商。

**** （五）智能硬件和应用电子。

     突破人工智能、低功耗轻量级系统、智能感知、新型人机交互等关键核心技术，重点发展面
     向下一代移动互联网和信息消费的智能可穿戴、智慧家庭、智能车载终端、智慧医疗健康、
     智能机器人、智能无人系统等产品，面向特定需求的定制化终端产品，以及面向特殊行业和
     特殊网络应用的专用移动智能终端产品。发展高水平“互联网+”人工智能平台，提升消费
     级和工业级智能硬件产品及服务供给能力。加快智能感知技术创新，重点推动毫米波与太赫
     兹、蜂窝窄带物联网（NB-IOT）、智能语音等技术在公共安全、物联网等重点领域开展示范
     应用。支持虚拟现实产品研发及产业化，探索开展在设计制造、健康医疗、文体娱乐等领域
     的应用示范。丰富智慧家庭产品供给，重点加大智能电视、智能音响、智能服务机器人等新
     型消费类电子产品供给力度，推动完善智慧家庭产业链，引导产业向“产品+服务”转型升
     级。开展智慧健康养老服务应用，支持健康监测和管理、家庭养老看护等可穿戴设备发展。
     推广智慧交通创新与应用示范，推动基于宽带移动互联网的智能汽车与智慧交通示范区建设。
     积极推进工业电子、医疗电子、汽车电子、能源电子、金融电子等产品研发应用。


     ****（六）计算机与通信设备。

     引导产业链上下游合作，突破高端服务器和存储设备核心处理器、内存芯片和输入/输出
     （I/O）芯片等核心器件，构建完善高端服务器、存储设备等核心信息设备产业体系。研究
     神经元计算、量子计算等新型计算技术应用。支持发展低功耗低成本绿色计算产品，强化芯
     片、软件、系统与应用服务适配，开展绿色计算应用示范，丰富应用服务模式，推动绿色计
     算生态良性发展。创新绿色计算产业合作机制，搭建绿色计算产品创新公共服务平台，开发
     和完善绿色计算接口标准、应用规范与产品检测认证体系。加快高性能安全工业控制计算机
     以及可信计算、数据安全、网络安全等信息安全产品的研发与产业化。支持安全可靠工业控
     制计算机在电网、水利、能源、石化等国民经济重要领域的应用。开发高速光传输设备及大
     容量组网调度光传输设备，发展智能光网络和高速率、大容量、长距离光传输、光纤接入
     （FTTx）等技术和设备。积极推进5G、IPv6、SDN和NFV等下一代网络设备研发制造。

**** （七）大数据。

     突破大数据关键技术和产品，培育壮大大数据服务业态，完善大数据产业体系。深化大数据
     应用创新，发展面向工业领域的大数据服务和成套解决方案。鼓励工业企业整合各环节数据
     资源，基于大数据应用开展个性化定制、众包设计、智能监测、全产业链追溯、在线监控诊
     断及维护、工控系统安全监控、智能制造等新业务。引导企业加快商业和服务模式创新，构
     建基于大数据的民生服务新体系，在公共安全、自然灾害防治、环境保护等城市管理领域，
     拓展和丰富服务范围、形式和内容。开展大数据产业集聚发展和应用示范区创建工作。在重
     点行业开展应用试点，推进政府、金融、能源等重要行业大数据系统安全可靠软硬件应用。
     培育数据采集、数据分析、数据安全、数据交易等新型数据服务产业和企业。在依法合规、
     安全可控前提下加快大数据交易产业发展，开展第三方数据交易平台建设试点示范。组织制
     定数据交易流通的一般规则和信息披露制度，逐步完善数据交易流通中的个人信息保护、数
     据安全、知识产权保护等制度，建立数据交易流通的行业自律和监督机制。

**** （八）云计算。

     积极发展基础设施即服务（IaaS）、平台即服务（PaaS）、软件即服务（SaaS）等云服务，
     提升公有云服务能力，扩展专有云应用范畴，围绕工业、金融、电信、就业、社保、交通、
     教育、环保、安监等重点领域应用需求，支持建设全国或区域混合云服务平台。大力发展云
     服务应用软件，促进各类信息系统向云计算服务平台迁移。积极发展基于云计算的个人信息
     存储、在线工具、学习娱乐等服务。鼓励大企业开放平台资源，加强行业云服务平台建设。
     建立为中小企业提供办公、生产、财务、营销、人力资源等基本管理服务的云计算平台。大
     力发展面向云计算的信息系统规划咨询、方案设计、系统集成和测试评估等服务。支持第三
     方机构开展云计算服务质量、可信度和网络安全等评估评测。优化云计算基础设施布局，建
     设完善云计算综合标准体系。完善云计算环境下网络信息安全管理体系，加强技术管理系统
     建设，强化新技术新业务评估，防范网络信息安全风险。

**** （九）物联网。

     实施物联网重大应用示范工程，发展物联网开环应用，加快物联网技术与产业发展、民生服
     务、生活消费、城市管理以及能源、环保、安监等领域的深度融合，形成一批综合集成解决
     方案。应用物联网技术推动大田耕种精准化、园艺种植智能化、畜禽养殖高效化，促进形成
     现代农业经营方式和组织形态。以车联网、智慧医疗、智能家居、智能可穿戴设备等为重点，
     通过与移动互联网融合加快消费领域物联网应用创新。推进物联网感知设施规划布局，深化
     物联网在智慧城市基础设施管理方面的应用。建立城市级物联网接入管理与数据汇聚平台，
     推动感知设备统一接入、集中管理和数据共享利用。大力发展工业互联网，成立工业互联网
     产业联盟，加快制定工业互联网标准体系，推动产业协同创新。组织开展工业互联网试点示
     范，建设公共服务平台和管理平台，强化基础设施建设，全面打造低时延、高可靠、广覆盖
     的工业互联网。



*** 五、政策措施


**** （一）深化体制机制改革。

     落实行政审批制度改革要求，积极推动电信法、网络安全法等立法。实现跨部门、跨平台的
     网上并联审批，取消不必要的审批目录和不合理收费，完善负面清单，积极应用大数据、云
     计算等新技术创新行业服务和管理方式。加快完善招投标和政府采购机制。加强事中事后监
     管，完善监测和惩戒机制。积极推动电信领域混合所有制改革，鼓励民间资本通过多种形式
     参与信息通信业投融资，激发非公有制经济和小微企业的活力与创造力。深化国有电信企业
     改革，增强企业活力。加大基础电信领域竞争性业务的开放力度,通过市场竞争促进企业提
     升服务质量。推动制定用户权益和个人信息保护相关法规，以及网络数据和用户信息保护分
     级分类标准及具体规则。健全产业安全审查机制和法规体系，加强业务开放情况下的网络与
     信息安全风险控制。加快发展信息产业技术市场，健全知识产权创造、运用、管理、保护机
     制，严打假冒伪劣。

**** （二）完善财税扶持政策。

     创新财政支持方式，优化财政资金投入，充分利用国家新兴产业创业投资引导基金、先进制
     造产业投资基金、中小企业发展基金、国家集成电路产业投资基金等政策性基金引导社会资
     金，支持重大产业化项目发展。加强资源协调，充分利用现有资金渠道支持重大生产力布局、
     关键产品产业化和重点产品示范项目。完善和落实支持创新的政府采购政策，推动信息产业
     创新产品和服务的研发应用。鼓励地方积极探索利用政府抵用券等方式支持信息企业引进创
     新技术、购置或租赁设备、培养人才等。继续落实软件和集成电路税收支持政策，以及研发
     费用加计扣除和固定资产加速折旧等政策，推动设备更新和新技术应用。推动符合条件的重
     大信息技术装备列入《首台（套）重大技术装备推广应用指导目录》，通过有关保险补偿试
     点支持推广应用。

**** （三）加大金融支持力度。

     建立完善多层次资本市场，支持符合条件的信息产业创新创业企业充分利用创业板拓宽融资
     渠道，推动在全国中小企业股份转让系统挂牌的符合条件的信息产业中小企业向创业板转板。
     丰富信息产业直接融资工具，积极推动项目收益票据、项目收益债、可转债等的应用。加大
     产融信息对接力度，建立完善跨部门工作协调机制，搭建服务平台。鼓励商业银行创新信贷
     产品和金融服务，推动知识产权质押融资、股权质押融资、供应链融资、信用保险保单质押
     贷款等金融产品创新，在风险可控和商业可持续前提下，加大对信息产业发展的金融支持力
     度。鼓励开发性、政策性金融机构在业务范围内，为符合条件的信息产业相关项目提供信贷
     支持。按照国家统一部署，引导和支持符合条件的金融机构在试点地区面向电子信息领域创
     新企业探索开展投贷联动试点，引导银行业金融机构对“中国制造2025”、“互联网+”行
     动等涉及的信息产业重点领域实施差别化信贷政策。支持符合条件的信息产业企业建立资金
     管理平台。鼓励信息产业骨干企业通过并购票据、并购基金、并购债等开展海外并购。

**** （四）大力培养产业人才。

     鼓励高校加强信息产业新兴领域学科专业建设，面向产业发展需求制定人才培养目标和质量
     标准，鼓励校企合作，建立人才实训基地。培养产业急需的各类科研人员、技术人才和复合
     型人才，联合开展在职人员培训。继续做好国家软件与集成电路人才国际培训基地工作，充
     分发挥基地作用，缩短人才培养周期。鼓励企业依托行业协会加强人才协作，推动信息产业
     与传统制造业人才交流。设立融合型就业人才综合信息平台。实施企业经营管理人才素质提
     升工程和专业技术人才知识更新工程，以急需紧缺人才为重点，着力加强信息技术领域专业
     技术人才和经营管理人才培养。做好职业培训和职业资格认证工作。加强人才需求调查和预
     测，建立健全信息产业高层次人才信息库。建设计算机技术与软件专业技术资格（水平）考
     试和通信专业技术水平考试合格人员数据库，为企业选人用人提供服务。促进人才双向交流，
     鼓励专业技术人才到国外学习培训交流，重点实施软件和集成电路人才出国培训专项；继续
     实施软件和集成电路产业外国专家引进计划，引进一批具有国际影响力的学术技术带头人和
     关键技术项目负责人。完善适应信息产业发展要求的人才引进和激励政策，创新引进渠道，
     积极引进新型显示、智能硬件、云计算、大数据等领域高端人才。

**** （五）切实加强组织实施。

     在国家制造强国建设领导小组的领导下，工业和信息化部、发展改革委联合牵头，各成员单
     位分工协作、加强配合，共同推动指南落实。加强上下联动，引导各地区结合实际合理布局、
     有序推进重大应用示范和产业化项目，减少低水平重复建设和投资，促进差异化发展。充分
     发挥国家制造强国建设战略咨询委员会和相关行业协会/联盟等的作用，加强对信息产业新
     技术、新产品、新业态、新模式、新趋势的跟踪研究。建立指南任务落实情况督促检查和第
     三方评价机制，扎实开展动态监测和中期评估工作。做好“十三五”时期信息产业各行业领
     域相关规划、政策、专项和工程与本指南的衔接。


** DONE [[https://wenku.baidu.com/view/82acb4f8be23482fb5da4c13.html][德国工业4.0与中国制造2025的区别]]
   CLOSED: [2017-11-01 三 06:59]
   :LOGBOOK:
   - State "DONE"       from "STARTED"    [2017-11-01 三 06:59]
   CLOCK: [2017-11-01 三 06:44]--[2017-11-01 三 06:59] =>  0:15
   :END:

   德国工业4.0在全球产生重大影响，标志着全球加快全面进入以智能制造为核心的智能经济
   时代。德国工业4.0与美国比较流行的第三次工业革命提法和一些学者说的第五次工业革命
   等，都是以信息技术革命性突破为基础，反映了工业经济数字化、信息化、智能化、网络
   化的发展趋势。本文着重分析德国工业4.0战略的主要特点，比较中国制造2025，得出一些
   重要启示。

*** 德国工业4.0主要特点

    德国工业4.0可以概括为：一个核心，两个重点，三大集成，四个特征和六项措施。一个核心：互联网+制造业，将信息物理融合系统(CPS)
    广泛深入地应用于制造业，构建智能工厂、实现智能制造。两个重点：领先的供应商策略，
    成为“智能生产”设备的主要供应者;主导的市场策略，设计并实施一套全面的知识和技术
    转化方案，引领市场发展。三大集成：企业内部灵活且可重新组合的纵向集成，企业之间
    价值链的横向集成，全社会价值链的端到端工程数字化集成。四个特征：生产可调节，可
    自我调节以应对不同形势;产品可识别，可以在任何时候把产品分辨出来;需求可变通，可
    以根据临时的需求变化而改变设计、构造、计划、生产和运作，并且仍有获利空间;四是过
    程可监测，可以实时针对商业模式全过程进行监测。六项措施：实现技术标准化和开放标
    准的参考体系;建立复杂模型管理系统;建立一套综合的工业宽带基础设施;建立安全保障机
    制和规章制度;创新工作组织和设计方式;加强培训和持续职业教育。

    把德国工业4.0放在全球范围和历史背景中比较发现，可以看出德国工业4.0有以下5个
    重要特点。

**** 基础性

     与德国整体发展战略相关，发挥优势，应对全局性挑战。德国是一个很重视发展
     战略规划的国家，特别是进入21世纪以来，一直在努力建立部门间高技术战略协调机制，
     制定德国的创新发展国家战略。2006年。德国政府制定了“高科技战略”，2010年7月，发
     布了《德国2020高技术战略》报告，2011年11月，德国政府特别提出把德国工业4.0作为
     《德国2020高技术战略》的重心，具有非同一般的意义，充分说明德国制造业在德国整体
     发展战略中的基础性作用。工业4.0有助于促进工业-科研联盟瞄准中长期科学和技术发展
     目标，制定具体的创新战略和实施路线图，确保德国制造业的领先和优势地位，是保持德
     国可持续发展的基础性战略。

**** 策略性

     与国际社会竞争相关，在国际相近的战略思维中，寻求不同的策略。加快先进制造业的发展
     不仅仅德国高度重视，其他国家也同样高度重视。事实上，早在2006年，美国国家科学基
     金会(NSF)就把CPS系统确定为关键研究领域。2011年3月，欧盟公布了“欧洲2020战略”，
     提出800亿欧元预算，使其成为世界上最大的研发经费计划。日本也提出了类似的“工业智
     能化”战略，重点发展人工智能、服务机器人等产业。德国很清楚自身近些年在竞争中的
     不利态势，面临很大的压力。面对竞争形势，德国采取了包容、开放、有策略的战略，在
     竞争中合作，在合作中竞争。德国为工业4.0配套制定了领先的供应商策略和主导的市场策
     略，重点考虑将产品与恰当的服务相衔接，着力开发新的商业模式。这是很值得借鉴的。

**** 创新性

     与工业发展历史相关，把累积、继承、创新有机结合起来，形成高水平的创新。
     一方面，充分考虑了从工业化早期阶段吸取经验，继承和发扬现有工业的核心价值。在德
     国，一般意义的信息和通信技术(ICT)至今仍然支持90%的工业制造过程。因此，工业4.0很
     重视借助传统工业和研究领域的传统优势。另一方面，德国工业4.0将制造领域的所有因素
     和资源通过CBS系统构成全新的社会服务和实时保障平台，体现了深度的创新性。德国“工
     业4.0”就是一种“再工业化”战略。但是与美日的“再工业化”不同，德国的“工业
     4.0”核心在于利用互联网、物联网以及模块化技术，实现工业生产方式的变革，从根本上
     改变传统工业中由于地理位置导致的生产、研发脱节现象，使工业生产技术的研发和升级
     不再依赖物理上的互相接触，使德国在既保持自己科技研发技术优势的同时，也可以继续
     享受全球化生产的优势。德国通过新理念、新战略、新技术，把信息化推向质的变化阶段，
     推动以智能制造、互联网、新能源、新材料、现代生物为特征的新的工业革命。这一点是
     很高明的。

**** 前瞻性

     与未来趋势相关，正确研判当前的形势和未来的趋势，体现事
     物发展规律。工业4.0是一个长期的发展战略;智能经济、智能世界是一个中长期的发展目
     标。在现实与中长期目标之间，德国一方面特别注重充分发挥自身优势，对智能工厂进行
     多层次、多视角的透视和描述，既体现可操作性，又体现前瞻性，为正确选择战略重点、
     采取超常规的相应举措，提供理论和实践基础。另一方面，德国把实现技术标准化放在最
     为优先的地位，抢先制定行业标准，企图继续占领全球制造业的制高点，除了在经济上获
     得现实利益外，更重要的是为长远确立德国制造优势创造条件。

**** 市场性

     与市场发展需求相关，适应市场、构建市场、引领市场，占据市场制高点。德国
     把智能工厂作为智能化世界的一部分，以“工业智能化”带动“社会智能化”，为“社会
     智能化”提供新一代网络基础设施、先进通信技术、智能控制系统设计、“大数据”分析
     方法等各类软硬件，将成熟的“工业解决方案”转化为“社会服务解决方案”，在不同的
     地区、不同的领域推广应用，构建新的市场空间。德国在构建市场的过程中，特别把CBS技
     术和产品确立为主导市场，根据不同消费者的需求设计系列化的智能产品，建设智能社会，
     建立全新的商业机会和模式，必将产生难以估量的市场价值。

*** 中国制造2025与德国工业4.0的比较

    2015年，中国在分析国内外市场的基础上，遵循产业升级与转型的客观规
    律，编制中长期十年规划，颁布了中国制造2025，明确了十个重点行业，包含战略性新兴
    产业、先进制造业、其他关系到国计民生的传统行业，以及相应的供应链和销售网。其主
    线是两化深度融合，主攻方向是推进智能制造，主要形式是互联网+。“中国制造2025”与
    德国“工业4.0”都是在新一轮科技革命和产业变革背景下针对制造业发展提出的一个重要
    战略举措。比较两个战略可以看出各有特点，除了技术基础和产业基础不同之外，还存在
    战略思想等方面的明显差异。德国工业4.0为德国工业发展描绘了细致的发展蓝图，反映了
    德意志民族特有的认真与严谨，在战略思想、基础研究、技术教育、政策机构和措施方面
    有很多值得我们学习和参考。

**** 1战略思想的差异

     比较德国工业4.0与中国制造2025， 一个重要的区别在于，德国工业4.0战略是一个革
     命性的基础性的科技战略。其立足点并不是单纯提升某几个工业制造技术，而是从制
     造方式最基础层面上进行变革，从而实现整个 工业发展的质的飞跃。因此，德国工业
     4.0战略的核心内容并不拘泥于工业产值数据这个层面上“量的变化”，而更加关注工
     业生产方式的“质的变化”。相对于德国工业4.0，《中国制造2025》，则强调的是在
     现有的工业制造水平和技术上，通过“互联网+”这种工具的应用，实现结构的变化和
     产量的增加。这种区别就好比《中国制造2025》是在工业现阶段水平和思维模式上寻
     求阶段内的改进和发展，德国则是寻求从工业3.0阶段跨越到工业4.0阶段，实现“质
     的变化”。这种战略思想上的差别应该说是客观条件的反映，符合现实基础，但也说
     明中国制造2025缺少战略上的理论深度和技术高度，也缺少市场上的感召力和影响力。



**** 2战略基础的差异

     战略基础包括基础研究、技术教育、人才培养等，是战略
     实施成功的基本条件。仔细研究《德国工业4.0》，我们不难发现这个战略最
     重要的因素是基础科学研究，很多细节方面的任务目标，都以“高、精、尖”的理论知识作
     为依凭。致力于改善德国科学基础研究的条件，提高科研创新能力。相比之下，中国基础
     学科的研究比较薄弱，科研创新能力不强，很难有重大突破。其根本原因，除历史基础条
     件因素之外，也有政策的因素。在政策支持上，中国横向研究比纵向研究无论在数目上，
     还是支持力度上都要大很多，导致中国应用型的研究领域较强，理论基础研究较薄弱。中
     国还在制定国际化行业标准方面缺乏经验和条件。因此，我们有必要下大力加强基础研究。
     同时，我们还有必要采取开放式的合作方针，积极成为网络化先进理论和先进标准体系的
     重要接入者，积极开展国际合作，与包括德国在内的发达国家一起分享理论、技术与市场。
     3战略措施的差异 在配套政策方面，德国为了有效实施工业4.0，比较重视对技术、政策和
     环境等进行评估调整。比如，德国系统评估新技术对相关法律可能造成的颠覆性影响，以
     及创新周期缩短可能导致相关规则架构频繁更新等，及时对现行不利于发展的各项规章制
     度进行了修改。德国比较重视构建支持工业4.0的法律环境，及时对与企业责任、数据保护、
     贸易限制、密码系统等相关法规进行调整，培养全国国民的竞争意识，比较重视反思和自
     我调适。这一点很值得我们借鉴。

**** 在协同机构方面，德国成立了政府统一协调机构，

     建立了第四次工业革命平台。德国信息技术通讯新媒体协会、德国机械制造联合会以及德
     国电子工业联合会三个专业协会共同建立了秘书处，负责为优先主体研发路线图。我国除
     了在中央政府层面成立由国务院领导同志担任组长的领导机构和战略咨询委员会之外，还
     应该大力发挥行业协会的作用，加强行业协同机制建设。

*** 德国工业4.0比较中国制造2025对中国的启示

**** 1积极迎接智能经济新时代 工业4.0将使人类-技术
     (human-technology)和人类-环境(human-environment)的相互作用发生全新转变。借助CPS
     系统，特别是互联网+，可以巨大地提升人的智能。智能是把人的智慧和知识转化为一种行
     动能力。基于人类智慧、电脑网络和物理世界有机融合的经济具有更高的效率，这种效率
     是传统工业无法达到的，因而智能一旦出现将以新的结构和形态取代传统工业，形成“智
     能经济”。在智能经济时代，智能环保、智能建筑、智能交通、智能医疗等，构成智能经
     济的不同领域;智能家庭、智能企业、智能城市、智能地区、智能国家、智能世界，构成智
     能社会的不同层面。在智能经济时代，全球经济一体化的整体性更加突出，市场主体相互
     之间内在联系更加紧密，社会经济系统对外更加开放。以智能工厂为特征的智能经济也很
     可能是工业经济发展的最高阶段。可以预料：世界的不平衡性将更加突出，竞争的形式将
     会改变，全球治理方式将有重大变化。对此，我们要有一定的准备，在发展战略、科技创
     新、人文道德上占据制高点，形成良好态势。

**** 2积极探索中国特色工业化道路

     我国还是一个发展中的国家，仍处于工业化进程中，落后与先进并存、传统与现代共生，需要积
     极探讨中国特色工业化道路：提升传统产业与培育新兴产业相结合;传统手工艺与先进制造
     业相结合;第一次工业化与第二次工业化相结合;信息化与工业化相结合。我国相当一个时
     期可能还需要同时推动“工业2.0”、“工业3.0”和“工业4.0”，既要实传统产业的转型
     升级，还要实现在高端领域的跨越式发展，建立既符合中国实际情况、又体现世界发展潮
     流的中国工业体系，为全面实现小康社会，实现现代化提供坚实和广宽的基础。既要考虑
     提高劳动生产率，又要考虑解决就业问题。

**** 3正确认识发达国家再工业化中的中国制造业

     在当前国际形势下，中国制造业面临三方面挑战：一方面来自高端挑战。发达国家通
     过“再工业化”，将“再工业化”与新的工业革命相结合，必定使发达国家在科技、信息、
     资本等方面长期积累的优势进一步强化，成为科技革新与产业革命红利的主要受益者，使
     不利于发展中国家的“中心-外围”世界分工体系进一步固化，进一步拉大与我国的距离。
     另一方面来自低端挤压，印度、越南、印尼等发展中国家可能以更低的劳动力成本承接劳
     动密集型产业的转移，抢占制造业的中低端，我国制造业在中低端广大市场的优势面临失
     去的危险。再一方面来自内部的困境。从整体来看，我国自主创新能力不强，核心技术对
     外依存度较高;制造业仍处于产业中低端水平，缺乏世界一流大型企业与知名品牌，在全球
     产业链中的高附加值环节份额相对较小;产业结构不尽合理，技术密集型产业和生产型服务
     业比重偏低，产业集聚和集群发展水平不高，产品质量问题比较突出;资源利用效率偏低，
     环保问题严重;管理水平不高，管理效率低，导致管理成本高，严重影响产品竞争力。

     中国制造业也迎来了三大机遇。首先是新的契机。新一轮科技革命和产业变革与我国加快
     转变经济发展方式形成历史性交汇，国际产业分工格局进入重塑阶段，新理念、新技术、
     新方式启动期有很多空白点，在某种程度上为全球提供了新的起跑线，也为中国赶超发展
     提供了契机。其次是新的供需。发达国家“再工业化”与正在兴起的新一轮工业革命有机
     结合，向我们展现了不同于传统流水线、集中化机器大生产的全新生产方式、生产要素、
     组织模式，必将创造新的市场和供需，这些都是我国可以大展身手之处。再次，发达国家
     “去工业化”和“再工业化”为我们提供了经验教训。发达国家过度“去工业化”及发展
     高风险、高杠杆的金融业务，导致实体经济与虚拟经济脱节，我国充分汲取其教训，借鉴
     其“再工业化”发展战略中具有前瞻性、符合发展大势的政策措施，根据不同类型行业的
     特点，有重点、有差别地推进结构优化升级，通过突破研发、设计、营销网络、品牌和供
     应链管理等制约产业结构升级的关键环节，完全有可能加快改造提升制造业。化挑战
     为机遇，可能要考虑“争两头，保中间”的战略规划格局，建立中国特色的现代产业体系。
     一头是集中优秀力量，大力增强集成创新能力，培育原始创新能力，加快拥有一批核心关
     键技术，在一些重要的高端领域，争取一席之地。这一点，我们过去做到了，今后也应该
     做到，从而在国际核心俱乐部有一定的话语权。一头是继续争取在低端有一定份额，努力
     创造更多的就业机会。我们应该在长期底端基础上有所升级，全部升到高端是不现实的，
     升到中端应该是我们的主要选项。克服“中国制造”所面临的困境，成为国内外市场优良
     (中端)产品和服务的重要提供者。

**** 4高度重视互联网+企业组织变革

     “互联网+”是科技与经济的有机结合，在实施“互联网+”战略中，互联网+企业组织变革具有特别重要的
     意义，企业作为市场的重要主体和经济的细胞，除了利用互联网加强与市场的互联和联系、
     推动网络化协同制造和服务之外，还要下大功夫增强内生动力，焕发内部活力。如何利用
     信息技术改善重构生产要素，深化企业组织变革，创新生产方式，提升资产质量和服务功
     能，适应市场需求和变化，是一个影响中国制造2025战略全局性的问题。解答这个问题首
     先需要正确理解技术与组织的关系。技术结构与企业组织结构的关系是相互促进和相互构
     建的过程，特别是互联网技术将企业的消费者、供应商、合作者和企业员工等各种关系全
     部组织在电脑网络里，使信息的获取、处理、传递和应用变得高速便捷，必然要求企业的
     生产方式、管理模式和组织机构做相应的调整和变革。在这种情况下，只有深化企业组织
     变革，将互联网技术和企业生产方式紧密联合起来，形成有效的信息沟通反馈机制，才能
     实现技术与组织的良性互动，才能使互联网技术的发展为企业所需要，企业才能成为推动
     企业技术进步的主要力量。

**** 5加强中国制造2025基础工作
     我国对基础研究、基础培训、基础设施等方面的重要性有一定的认识和措施，但缺乏深度、缺乏核心、缺乏灵魂。一项
     大的战略，特别是涉及到一个国家中长期发展的大战略，必须要有自己的系统、深厚的理
     论基础，必须要有自己的核心关键的创新技术，必须要有创新理念、勇于担当、能够解决
     问题的人才。

     虽然我们可以通过向西方发达国家学习的方式缩小技术差距，但是如果
     理论研究无法赶上去，那么将永远落后于别人，进而失去真正的竞争力。在基础研究和基
     础培训两方面，德国都有很多宝贵经验，值得我们学习。

     如何加强基础研究、基础培训呢?可以考虑从基础设施建设着手。基础设施建设也是中国制
     造2025重要一部分内容。中国制造2025必须要有配套的基础设施和能够获得的相应材料。
     比较深入地研究分析中国制造基础设施工程，可以发现问题、解决问题，体现以问题为导
     向的创新研究思路，既有针对性地加强理论研究，又为中国制造提供基础条件。从目前情
     况看，很有必要梳理出中国制造重要基础设施名目，比如，宽带互联网基础设施、高效大
     容量数据基础设施、IT基础设施、统一的安全保障构架和独特的标识符等。在比较参考国
     际相应的先进基础设施基础之上，很有必要逐项制定中国制造基础设施项目的理论研究方
     案和工程建设方案，为中国制造2025夯实基础。

     不可否认，新的工业革命浪潮正在兴 起，智能世界的前景正在展现，激烈竞争的号角已经吹响。我们急不得，也慢不得。关键
     是要深入研判，长线布局，措施得当。“中国制造”需要从要素驱动转变为创新驱动;从低
     成本竞争优势转变为质量效益竞争优势;从资源消耗大、污染物排放多的粗放制造转变为绿
     色制造;从生产型制造转变为服务型制造。中国制造发展战略核心要义应该是：以加快新一
     代信息技术与制造业融合为主线，以提质增效为中心，以满足经济社会发展和国防建设对
     重大技术装备需求为目标，以开放合作为手段，强化工业基础能力，提高综合集成水平，
     完善多层次人才体系，培育有中国特色的制造文化，促进产业转型升级，实现制造业由大
     变强的历史跨越。中国完全有可能成为新的工业革命的重要受益者，也为新的工业革命做
     出重要贡献。



** 国务院关于进一步扩大和升级信息消费持续释放内需潜力的指导意见

   作者：来源：中国政府网2017-08-24 17:59




    
   国务院部署扩大和升级信息消费 力争2020年启动5G商用
    
   　　国务院关于进一步扩大和升级信息消费持续释放内需潜力的指导意见
   　　国发〔2017〕40号
   　　各省、自治区、直辖市人民政府，国务院各部委、各直属机构：
   　　近年来，随着互联网技术与经济社会深度融合，我国信息消费快速发展，正从以线上为主加快向线上线下融合的新形态转变，网络提速降费深入推进，消费主体不断增加、边界逐渐拓展、模式深刻调整，带动其他领域消费快速增长，已成为当前创新最活跃、增长最迅猛、辐射最广泛的经济领域之一，对拉动内需、促进就业和引领产业升级发挥着重要作用。但与此同时，我国信息消费有效供给仍然创新不足，内需潜力仍未充分释放，消费环境亟待优化。为进一步扩大和升级信息消费、持续释放发展活力和内需潜力，现提出以下意见。
   　　一、总体要求
   　　（一）指导思想。
   　　全面贯彻党的十八大和十八届三中、四中、五中、六中全会精神，深入贯彻习近平总书记系列重要讲话精神和治国理政新理念新思想新战略，认真落实党中央、国务院决策部署，统筹推进“五位一体”总体布局和协调推进“四个全面”战略布局，坚持稳中求进工作总基调，牢固树立和贯彻落实创新、协调、绿色、开放、共享的发展理念，以推进供给侧结构性改革为主线，优化信息消费环境，进一步加大网络提速降费力度，加速激发市场活力，积极拓展信息消费新产品、新业态、新模式，扩大信息消费覆盖面，加强和改进监管，完善网络安全保障体系，打造信息消费升级版，不断释放人民群众日益增长的消费需求，促进经济社会持续健康发展。
   　　（二）基本原则。
   　　坚持创新驱动。推动信息消费与大众创业万众创新、“互联网+”深度融合，鼓励核心技术研发和服务模式创新，促进新一代信息技术向消费领域广泛渗透，创造更多适应消费升级的有效供给，带动多层次、个性化的信息消费发展。
   　　坚持需求拉动。以满足人民群众期待和经济社会发展需要为出发点和落脚点，加快拓展和升级信息消费，推动信息产品供给结构与需求结构有效匹配、消费升级与有效投资良性互动，用安全、便捷、丰富的信息消费助力经济升级和民生改善。
   　　坚持协同联动。以企业为主体，促进信息消费产业链协同发展，加强网络、平台、支付、物流等支撑能力建设，构建完善的信息消费生态体系。统筹促发展与保安全，持续优化信用安全、市场环境和权益保护，营造“能消费、敢消费、愿消费”的环境，形成政府、企业、消费者多方协同的良好发展格局。
   　　（三）发展目标。
   　　到2020年，信息消费规模预计达到6万亿元，年均增长11%以上；信息技术在消费领域的带动作用显著增强，信息产品边界深度拓展，信息服务能力明显提升，拉动相关领域产出达到15万亿元，信息消费惠及广大人民群众。信息基础设施达到世界领先水平，“宽带中国”战略目标全面实现，建成高速、移动、安全、泛在的新一代信息基础设施，网络提速降费取得明显成效。基于网络平台的新型消费快速成长，线上线下协同互动的消费新生态发展壮大。公共数据资源开放共享体系基本建立，面向企业和公民的一体化公共服务体系基本建成。网络空间法律法规体系日趋完善，高效便捷、安全可信、公平有序的信息消费环境基本形成。
   　　（四）重点领域。
   　　生活类信息消费。创新发展满足人民群众生活需求的各类便民惠民服务新业态，重点发展面向社区生活的线上线下融合服务、面向文化娱乐的数字创意内容和服务、面向便捷出行的交通旅游服务。
   　　公共服务类信息消费。推广高效、均等的在线公共服务，重点发展面向居家护理的智慧健康服务、面向便捷就医的在线医疗服务、面向学习培训的在线教育服务、面向利企便民的“互联网+政务服务”。
   　　行业类信息消费。培育支撑行业信息化的新兴信息技术服务，重点发展面向垂直领域的电子商务平台服务，面向信息消费全过程的网络支付、现代物流、供应链管理等支撑服务，面向信息技术应用的综合系统集成服务。
   　　新型信息产品消费。升级智能化、高端化、融合化信息产品，重点发展面向消费升级的中高端移动通信终端、可穿戴设备、数字家庭产品等新型信息产品，以及虚拟现实、增强现实、智能网联汽车、智能服务机器人等前沿信息产品。
   　　二、提高信息消费供给水平
   　　（五）推广数字家庭产品。鼓励企业发展面向定制化应用场景的智能家居“产品+服务”模式，推广智能电视、智能音响、智能安防等新型数字家庭产品，积极推广通用的产品技术标准及应用规范。加强“互联网+”人工智能核心技术及平台开发，推动虚拟现实、增强现实产品研发及产业化，支持可穿戴设备、消费级无人机、智能服务机器人等产品创新和产业化升级。依托消费品工业“三品”专项行动，促进信息产品相关企业争创“中国质量奖”。
   　　（六）拓展电子产品应用。支持利用物联网、大数据、云计算、人工智能等技术推动各类应用电子产品智能化升级，在交通、能源、市政、环保等领域开展新型应用示范。推动智能网联汽车与智能交通示范区建设，发展辅助驾驶系统等车联网相关设备。推进农业物联网区域试验工程，推动信息技术与农业生产经营、市场流通、资源环境保护等相融合。
   　　（七）提升信息技术服务能力。支持大型企业建立基于互联网的“双创”平台，为全社会提供专业化信息服务。发挥好中小企业公共服务平台作用，引导小微企业创业创新示范基地平台化、生态化发展。鼓励信息技术服务企业积极发展位置服务、社交网络等新型支撑服务及智能应用。支持地方联合云计算、大数据骨干企业为当地信息技术服务企业提供咨询、研发、培训等技术支持，推动提升“互联网+”环境下的综合集成服务能力。鼓励利用开源代码开发个性化软件，开展基于区块链、人工智能等新技术的试点应用。
   　　（八）丰富数字创意内容和服务。实施数字内容创新发展工程，加快文化资源的数字化转换及开发利用。构建新型、优质的数字文化服务体系，推动传统媒体与新兴媒体深度融合、创新发展。支持原创网络作品创作，加强知识产权保护，推动优秀作品网络传播。扶持一批重点文艺网站，拓展数字影音、动漫游戏、网络文学等数字文化内容，丰富高清、互动等视频节目，培育形成一批拥有较强实力的数字创新企业。发展交互式网络电视（IPTV）、手机电视、有线电视网宽带服务等融合性业务。支持用市场化方式发展知识分享平台，打造集智创新、灵活就业的服务新业态。
   　　（九）壮大在线教育和健康医疗。建设课程教学与应用服务有机结合的优质在线开放课程和资源库。鼓励学校、企业和其他社会力量面向继续教育开发在线教育资源。推动在线开放教育资源平台建设和移动教育应用软件研发，支持大型开放式网络课程、在线辅导等线上线下融合的学习新模式，培育社会化的在线教育服务市场。加强家庭诊疗、健康监护、分析诊断等智能设备研发，进一步推广网上预约、网络支付、结果查询等在线就医服务，推动在线健康咨询、居家健康服务、个性化健康管理等应用。
   　　（十）扩大电子商务服务领域。鼓励电商、物流、商贸、邮政等社会资源合作构建农村购物网络平台。支持重点行业骨干企业建立在线采购、销售、服务平台，推动建设一批第三方工业电商服务平台。培育基于社交电子商务、移动电子商务及新技术驱动的新一代电子商务平台，建立完善新型平台生态体系。积极稳妥推进跨境电子商务发展。
   　　三、扩大信息消费覆盖面
   　　（十一）推动信息基础设施提速升级。加大信息基础设施建设投入力度，进一步拓展光纤宽带和第四代移动通信（4G）网络覆盖的深度和广度，促进网间互联互通。积极参与“一带一路”沿线重要国家、节点城市网络建设。加快第五代移动通信（5G）标准研究、技术试验和产业推进，力争2020年启动商用。加快推进物联网基础设施部署。统筹发展工业互联网，开展工业互联网产业推进试点示范。推进实施云计算工程，引导各类企业积极拓展应用云服务。积极研究推动数据中心和内容分发网络优化布局。
   　　（十二）推动信息消费全过程成本下降。重点在通信、物流、信贷、支付、售后服务等关键环节全面提升效率、降低成本。深入挖掘网络降费潜力，加快实现网络资费合理下降，充分释放提速降费的改革红利，支持信息消费发展。建立标准化、信息化的现代物流服务体系，推进物流业信息消费降本增效。鼓励金融机构开发更多适合信息消费的金融产品和服务，推广小额、快捷、便民的小微支付方式，降低信息消费金融服务成本。
   　　（十三）提高农村地区信息接入能力。深化电信普遍服务试点，助力网络扶贫攻坚、农村信息化等工作，组织实施“百兆乡村”等示范工程，引导社会资本加大投入力度，重点支持中西部省份、贫困地区、革命老区、民族地区等农村及偏远地区宽带建设，到2020年实现98%的行政村通光纤。全面实施信息进村入户工程，开展整省推进示范，力争到2020年村级信息服务站覆盖率达到80%。
   　　（十四）加快信息终端普及和升级。支持企业推广面向低收入人群的经济适用的智能手机、数字电视等信息终端设备，开发面向老年人的健康管理类智能可穿戴设备。推介适合农村及偏远地区的移动应用软件和移动智能终端。构建面向新型农业经营主体的生产和学习交流平台。推动民族语言软件研发，减少少数民族使用移动智能终端和获取信息服务的障碍。鼓励各地采用多种方式促进信息终端普及。
   　　（十五）提升消费者信息技能。实施消费者信息技能提升工程，选择部分地区开展100个以上信息技能培训项目，通过多种方式开展宣传引导活动，面向各类消费主体特别是信息知识相对薄弱的农牧民、老年人等群体，普及信息应用、网络支付、风险甄别等相关知识。组织开展信息类职业技能大赛，鼓励企业、行业协会等社会力量开展信息技能培训。
   　　（十六）增强信息消费体验。组织开展“信息消费城市行”活动。鼓励地方和行业开展信息消费体验周、优秀案例展示等各种体验活动，扩大信息消费影响力。鼓励企业利用互联网平台深化用户在产品设计、应用场景定制、内容提供等方面的协同参与，提高消费者满意度。支持企业加快线上线下体验中心建设，积极运用虚拟现实、增强现实、交互娱乐等技术丰富消费体验，培养消费者信息消费习惯。
   　　四、优化信息消费发展环境
   　　（十七）加强和改进监管。坚持包容审慎监管，加强分类指导，深入推进“放管服”改革，继续推进信息消费领域“证照分离”试点，进一步简化优化业务办理流程，推行清单管理制度，放宽新业态新模式市场准入。强化事中事后监管，积极应用大数据、云计算等新技术创新行业服务和管理方式，在信息消费领域推行“双随机、一公开”监管，完善守信联合激励和失信联合惩戒制度。严厉打击电信网络诈骗、制售假冒伪劣商品等违法违规行为，整顿和规范信息消费环境。深化电信体制改革，鼓励民间资本通过多种形式参与信息通信业投融资。做好自由贸易试验区电信领域开放试点，加大基础电信领域竞争性业务开放力度，适时在全国其他地区复制推广。
   　　（十八）加快信用体系建设。健全用户身份及网站认证服务等信任机制，提升网络支付安全水平。结合全面实施统一社会信用代码制度，构建面向信息消费的企业信用体系，加强信息消费全流程信用管理。规范平台企业市场行为，加大对信息消费领域不正当竞争行为的惩戒力度，推动建立健全企业“黑名单”制度，将相关行政许可、行政处罚等信息纳入全国信用信息共享平台和国家企业信用信息公示系统，并依法依规在“信用中国”网站公示，营造公平诚信的信息消费市场环境。
   　　（十九）加强个人信息和知识产权保护。贯彻落实网络安全法相关规定，加快建立健全个人信息保护法律法规体系和管理制度。严格落实企业加强个人信息保护的责任，全面规范个人信息采集、存储、使用等行为，防范个人信息泄露和滥用，加大对窃取、贩卖个人信息等行为的处罚力度。健全知识产权侵权查处机制，提升网络领域知识产权执法维权水平，加强网络文化知识产权保护。
   　　（二十）提高信息消费安全性。加强网络信息安全相关技术攻关，为构建安全可靠的信息消费环境提供支撑保障。落实网络安全等级保护制度，深入推进互联网管理和网络信息安全保障体系建设，加强移动应用程序和应用商店网络安全管理，规范移动互联网信息传播。完善网络安全标准体系，建设标准验证平台，支持第三方专业机构开展安全评估和认证工作。做好网络购物等领域消费者权益保护工作，依法受理和处理消费者投诉举报，切实降低信息消费风险。
   　　（二十一）加大财税支持力度。深入推进信息消费试点示范城市建设。鼓励各地依法依规采用政府购买服务、政府和社会资本合作（PPP）等方式，加大对信息消费领域技术研发、内容创作、平台建设、技术改造等方面的财政支持，支持新型信息消费示范项目建设。落实企业研发费用加计扣除等税收优惠政策，促进社会资本对信息消费领域的投入。经认定为高新技术企业的互联网企业，依法享受相应的所得税优惠政策。
   　　（二十二）加强统计监测和评价。完善信息消费统计监测制度，进一步明确统计范围，将智能产品、互联网业务、数字内容等纳入信息消费统计。加强中央、地方、行业、重点企业间的协调联动，强化信息消费数据采集、处理、发布和共享。建立健全信息消费评价机制，研究建立并定期发布信息消费发展指数，加强督查检查，指导和推动信息消费持续健康发展。
   　　各地区、各部门要进一步统一思想，充分认识新形势下扩大和升级信息消费对释放内需潜力、促进经济升级、支持民生改善的重要作用，按照本意见要求，根据职责分工，加强组织实施，抓紧制定出台配套政策措施，强化协调联动，形成工作合力。各地方要因地制宜制定具体实施方案，明确任务、落实责任，扎实做好相关工作，确保各项任务措施落实到位。
   　　附件：重点任务分工方案
   　　国务院 　 　　　　　
   　　2017年8月13日　　　　　
   　　（此件公开发布）
   　　附件
   　　重点任务分工方案
   　　（有关任务目标截至2020年）
   　　
