* 活动路线
* 1.接待、集合：地点:办公楼二楼会议室
参加调研人员：致公党主委：人大农经委主任梁望东及（副主委、卢秘书长等5人左右）
邀请统战部党派科长姜华、分管部长薛部长（周一待定）
学院参加领导：
张永华书记
张清民副书记，王文林副院长
** 2.桌牌：办公室，茶杯、水、水果准备
* 3.参观路线：先整体-文化建设，后mac实验室-指纹机-三楼一体机实训室-物联网
*
4.在系小会议室 ppt介绍
**
** 5.在系小会议室讨论发言
6.5：10晚餐

稿件主要内容：
落实国家的五大发展理念：创新、协调、绿色、开放、共享，“坚持创新发展、协调发展、绿色发展、开放发展、共享发展。”
我们提出了愉快高效、协同共享的工作理念，践行“精细培养，个性发展”的育人理念。

在教育管理中育人，体现了教师的爱心，让每个学生成长成材；
应用现代管理，教育教学管理精准、到位；
承认和关注每个学生的进步与成长足迹，对家长来说，一个学生即是一个家庭的百分之百；
承认每个学生的个性，让学生自由成长，发展其强项、特长，使其成为技能与特长显明的有用人才。
为达到此目标，重点建设了大数据、云中心，搭建了系列管理平台，用企业最先进的管理理
念来育人及管理，学生既学知识、练技能，同时体会参与到先进管理体系中。
*** 1.学生考勤、请假、与班主任交互使用“钉钉”网上通用平台
目前中小企业人员考勤多数用的是“钉钉”系统，我们使用此系统用于学生考勤等管理，让
学生提前体验企业中对员工的管理，更好地适应未来的工作方式。
*** 2.重点工作、项目管理布署了项目管理平台
在名校建设过程中，引入了项目管理平台，工作推进有力有序，在教学中试用一学期，成效
显著。教师和学生学会用现代管理理念来工作，管理整个过程。共完成1848个文件整理，15
级300多名学生上线，参与教学与实践。
*** 3.为了学生个性学习，碎片化学习，在16年下半年布署了在线课程系统，部分教师先行先试
，取得了良好的效果，本学期所有教师课程皆建立了在线课程，推行混合式教学，充分利用
现代科技，改进教育教学，学生体验最先进的教育平台，为终身学习养成良好的习惯。
*** 4.用企业管理的思想来管理教学和学生
今年开始，搭建完成ERP管理平台，为精细化管理、精准成本核算打好基础。
现代企业管理都在ERP来管理企业，推行ERP的管理理念，让学生及教师体验先进的管理方式，
适应岗位及绩效管理，为服务于中小企业提理念、积体会。提前进入职场情境。
