* 时态
** 现在完成时
*** have(has)+过去分词
Have you just been(is,was,be were ) to the cinema?
I've never been there.
Have you even been there?
I've already seen(see,saw)it.
He's only forty-one years old, 
but he has already been to nearly every country in the world.
** 一般过去时 
过去式
I saw(see)it on television last year.
I was there in April.
It was spring, but the weather was awful.
It rained all the time.
** 一般现在时
*** 事实
Pairs is a beautiful city.
It's an old film, but it's very good.
Just like London.

In order to wash the floor, you need a mop and a bucket.
In order to clean shoes, you need a shoe brush.
In order to vacuum the rug, you need a vacuum cleaner.
In order to clean the stove, you need detergent.
In order to wash clothes, you need laundry detergent and a washing machine.

The bathroom is in disorder - the laundry detergent, soap and clothes are lying on
the floor.

** 现在进行时
正在进行的动作
The man is cleaning up the table.
The woman is washing the floor with a mop and a wet rag.
The father is ironing a shirt and talking on the phone.
The woman is washing dirty dishes and listening to happy music.
The woman is ironing a beautiful dress and thinking about a party.
The mother is washing the window, and her daughter is washing the floor.

With what is the man cleaning his shoes? He's cleaning them with a shoe brush.
With what is the girl drying the plate? She's drying the plate with a clean
white towel.
What are the children doing? The children are helping their mom clean up in the
room.
** 一般将来时
will +原型
He will fly to New York next month.
The month after next he'll fly to Tokyo.
He'll return to London the week after next.
** 表职业
*** 现在时，现在的职业
He's a pilot.
*** 过去时，过去的职业
He was in the R.A.F.

