* lesson 28
** Text
a forest
a desert
a view of the sea
a palm 
a cactus
a view of the mountains

a squirrel
a swan
a seagull
a camel
a turtle
a parrot

animals
vegetables
good weather
bad weather
fruits
plants

Cacti grow in the desert.
This cactus grows in the window.
There is no water in the desert, only sand.
Trees do not grow in the desert.
Many trees grow in the forest.
This is a view of the mountains covered with snow.

The man is travelling across the desert on a camel.
The squirrel is eating on the park bench.
There is a camel near the palm.
There is a beautiful green forest around the small lake.
A woman is feeding the squirrel from her hand.
A palm grows on the beach.

A turtle lives in the sea.
A squirrel lives in a tree in the forest.
A seagull flies above the sea.
This parrot lives in a house.
A parrot also lives in the forest.
A swan lives in the lake.

A cucumber and a tomato are vegetables.
An apple, an orange, and a banana are all fruits.
A potato is a vegetable, not a fruit.
A pear is a fruit, not a vegetable.
Fruits grow on trees.
Vegetables and fruits are good food.

A dog is an animal.
A squirrel is an animal that lives in the forest.
A camel is an animal that lives in the desert.
Some animals live in a house.
Many animals live in the sea.
A cat is also an animal.

There are many plants in the sea.
There are very few plants in the desert.
A cactus is a plant.
Flowers are plants.
Trees are plants.
A palm is a plant.

People do not like to walk in bad weather.
This is a view of the sea in good weather.
Both people and animals like good weather.
Sunny weather is good weather.
This is a view of the city in bad weather.
Rainy weather is bad weather.
* lesson 29
** text
*** one
 Who is waiting at the door? The dog.
 Who is sitting on the pink stool? The young artist.
 Who is carrying the flowers? The bride.
 Who is crying in bed? The child.
 Who is singing and playing the guitar? The musician.
 Who is drinking from the puddle? The horse.
*** two
 Where is the child sitting? He is sitting on his father's shoulders.
 Where does the turtle live? It lives in the sea.
 Where are the shirts? They are in the closet.
 Where are the dishes? They are in the tray.
 Where are the actors performing? They are performing in the park.
 Where is the man sitting? He is sitting in a large blue chair.
*** three
 How many windows are there in this room? There is one window in the room.
 How many dogs are playing in the park? There are two dogs playing in the park.
 How many people are in this photograph? There are three people in the
 photograph.
 How many palms are growing on the beach? There are two palms growing on the
 beach.
 How many legs does a giraffe have? A giraffe has four legs.
 How many chairs are around the table? There are five chairs around the table.
*** Four
 What colour is the grass at the stadium? It is green.
 What colour is the car on the mountain road? It is white.
 What colour is the train? It is blue.
 What colour are the flowers around the fountain? They are red and yellow.
 What colour are the legs of this bird? They are pink.
 What colour is the girl's dress? It is violet.
*** Five 
 What is the man holding in his hand? He is holding a pair of glasses.
 What are the guests bringing? They are bringing presents.
 What is the boy eating? He is eating bread.
 What is the doctor putting on? She is putting on white gloves.
 What are they selling in the shop? They are selling clothes there.
 What are the travellers looking at? They are looking at the mountaiins covered
 with snow.
*** Six
 What is the boy doing? He is giving the woman a banana.
 What is the sportsman doing? He is jumping at the stadium.
 What is the girl doing? She is drawing.
 What are the tourists doing? They are taking photographs.
 What is the doctor doing? He is treating the patient.
 What are the young people doing? They are dancing.
*** Seven
 Who is the grandfather hugging? He is hugging his granddaughter.
 Which bird has a long neck? A swan has a long neck.
 Who is the mother kissing? She is kissing her little son.
 Which animal has a very long neck? A giraffe has a very long neck.
 When are the trees covered with snow? In the winter.
 When are the leaves on the trees yellow? In the autumn.
*** Eight
 Is there a clock in the room? Yes, there is a clock here.
 Is there a television in the kitchen? No, there is no television here.
 Are there any spectators at the theatre? Yes, there are some spectators here.
 Are there fruits on the table? No, there are no fruits here.
 Is there food in the refrigerator? Yes, there is a lot of food here.
 Is there a bench near the house? Yes, there is a bench here.
*** Nine
 Is the child on the floor or on the sofa? The child is on the floor.
 Is the child laughing or crying? He is laughing.
 Is this an artist or a musician? This is an artist.
 Is the person working or relaxing? He is relaxing.
 Is this a street in the city or a road in the countryside？This is a road in the
 countryside.
 Are people swimming in the sea or in the river? They are swimming in the sea.
*** Ten
 This is a aquare in a big city. There are groups of tourists on the square.
 There are many beautiful buildings around the square.
 This is a train car. A policeman in a grey cap and blue shirt is sitting in the
 train car. He is sleeping.
 This man is an artist. There are many paintings around him. On the paintings are
 views of the cities.
 This is the city beach. The beach is near a bridge. Young people are playing
 on the beach.
 These are swans on the ice. They are white and grey. Swans are very beautiful
 birds.
 The young woman is sitting on the beach. There is good sunny weather oat the sea.The
 woman is paying with sand.

** Words
*** stool 
stool | BrE stuːl, AmE stul | noun
 ① (seat) 凳子 dèngzi
  ▸ high stool 高脚凳
  ▸ to fall between two stools (mainly British) figurative 两头落空
 ② (faeces) 粪便 fènbiàn
*** artist
artist | BrE ˈɑːtɪst, AmE ˈɑrdəst | noun
 ① (general) 艺术家 yìshùjiā ; (painter) 画家 huàjiā
 ② informal (skilled person) 能手 néngshǒu
*** carry
carry | BrE ˈkari, AmE ˈkɛri |
 A. transitive verb
 ① (support and take) 抱 bào ‹child›; 拿 ná ‹suitcase, umbrella›; 搬 bān ‹box, chair›; «more than two people» 抬 tái
  ▸ she carried the baby in her arms 她把孩子抱在怀里
  ▸ they carried the injured man away on a stretcher 他们用担架把伤员抬走了
  ▸ will you carry the tray out, please 请你把托盘端出去好吗 → coal 2
 ② (take in vehicle) 运送 yùnsòng
  ▸ the minibus carries 12 people 这辆中巴可载 12 人
 ③ (transport on air or water) 带走 dàizǒu
  ▸ his hat was carried away by a gust of wind 他的帽子被一阵风吹走了
  ▸ the tide carried the boat back towards the shore 潮水把船冲回岸边
 ④ (act as conduit for) «pipe» 输送 shūsòng ‹water, oil, gas›; «line, wire» 传导 chuándǎo ‹sound, signal, electricity›
  ▸ the veins carry blood back to the heart 静脉将血液输送回心脏
 ⑤ (take to place, position) 推进 tuījìn
  ▸ to carry sth too far 把某事做得太过分
  ▸ she carries modesty to extremes 她谦虚得过了头
  ▸ her abilities carried her to the top of her profession 她的才能使她在本行业出类拔萃
  ▸ the war was carried into enemy territory 战事推进到了敌方境内
 ⑥ (have with one) 带有 dàiyǒu
  ▸ I don't usually carry much cash with me 我通常不多带现金
  ▸ he will carry the memory with him for the rest of his life 他将一生铭记这一切
  ▸ to carry sth in one's head or mind 牢记某事物
 ⑦ (publish) «newspaper, magazine, poster» 刊登 kāndēng ‹news, information›; (broadcast) «programme» 播出 bōchū ‹news, information›
 ⑧ (be marked by) «object» 附有 fùyǒu ‹label, symbol›
  ▸ the notepaper carries the company logo 信纸上印有公司的标识
 ⑨ (have as quality, feature) 具有 jùyǒu ‹conviction, authority›; (have as a result) «job, venture, plan, crime» 带来 dàilái ‹risk, boredom, excitement, penalty›
  ▸ the offence carries a maximum fine of £50 这种违法行为最高可处 50 英镑罚款
  ▸ the new post carries increased responsibility 这一新职位的责任更大
  ▸ the video recorder carries a 12-month guarantee 这部录像机保修 12 个月
  ▸ to carry weight 有影响力
 ⑩ (be pregnant with) 怀 huái
  ▸ she is carrying twins 她怀了双胞胎
  ▸ the elephant carries its young for 22 months 大象孕期有 22 个月
 ⑪ Medicine (be infected with) 携带 xiédài ‹germ, virus›; 传染 chuánrǎn ‹disease, condition›
 ⑫ Business (stock, sell) «shop, trader» 出售 chūshòu ‹goods, brand›
 ⑬ (support weight of) «pillars» 支撑 zhīchēng ‹weight›; «road, bridge, table» 承载 chéngzài ‹load›
 ⑭ (take responsibility for) 承担 chéngdān
  ▸ he is carrying the entire department 他主持着整个部门的工作
  ▸ we can't afford to carry passengers 我们养不起闲人
  ▸ to carry a (heavy) burden or load 肩负重担
 ⑮ (win) 在…中获胜 zài… zhōng huòshèng ‹battle, argument, match›; 攻占 gōngzhàn ‹fortress, town›; 打败 dǎbài ‹enemy, opponent›
  ▸ to carry the day 获胜
  ▸ to carry all or everything before one 大获全胜
 ⑯ (approve) 使…获得通过 shǐ… huòdé tōngguò ‹amendment, bill, proposal›
  ▸ the motion was carried by 25 votes to 13 这一动议以 25 票对 13 票获得通过
 ⑰ (gain in election) «candidate, party» 在…获得多数票 zài… huòdé duōshùpiào ‹state, district›
 ⑱ (persuade) «person, speech» 打动 dǎdòng ‹audience, voters›
  ▸ he carried the congregation with him 他打动了教堂会众
 ⑲ Mathematics 使…进位 shǐ… jìnwèi ‹number›
 B. intransitive verb
 ① (be audible) «sound, voice» 传到远处 chuándào yuǎnchù
  ▸ the noise of the explosion carried several miles 爆炸声传到了几英里外
 ② (go) «missile» 射出一定距离 shèchū yīdìng jùlí
  ▸ the ball carried over the boundary 球出界了
 C. to carry oneself reflexive verb (move, behave) 保持姿态 bǎochí zītài
  ▸ she carried herself like a model 她举手投足像个模特
  ▸ he carried himself with dignity 他举止庄重 tā jǔzhǐ zhuāngzhòng
 D. noun informal (in sb's arms) 抱 bào ; (on sb's back) 背 bēi ; (transporting in a vehicle) 送 sòng
  ▸ to give sb a carry 送某人一程 PHRASAL VERBS carry away: transitive verb [carry sb away] 使失去自制力 shǐ shīqù zìzhìlì
  ▸ he was carried away by the splendour of the palace 他被壮观的宫殿完全吸引住了
  ▸ sorry I'm late: I was trying out my new computer and I got carried away 对不起，我来晚了；我在试用新电脑，结果忘了时间 carry back: transitive verb [carry sb back] 使回想起过去 shǐ huíxiǎng qǐ guòqù
  ▸ to carry sb back to sth; 使某人回想起某事物
  ▸ the smell of the sea air carried her back to childhood holidays 大海的气息使她回想起儿时度假的情景 carry forward transitive verb [carry sth forward, carry forward sth]
 ① (transfer to new page or account) 结转 jiézhuǎn ‹balance, figure, total›
 ② (keep to use or deal with later) «person, company» 冲转 chōngzhuàn ‹sum, loss›carry off: transitive verb
 ① [carry sb/sth off, carry off sb/sth] (take by force) 强行带走 qiángxíng dàizǒu
  ▸ she was carried off by the terrorists 她被恐怖分子抓走了
  ▸ the burglars carried off the family silver 窃贼们盗走了家里的银器
 ② [carry off sth] (win) 赢得 yíngdé ‹prize, honour›
 ③ [carry sth off, carry off sth] (succeed with) 成功处理 chénggōng chǔlǐ
  ▸ to carry it off 轻松应付过去
  ▸ she carried the speech off brilliantly 她十分出色地完成了演讲
  ▸ he was unable to carry off the deception 他的诡计没能得逞
 ④ [carry sb off, carry off sb] (kill) «disease» 导致…死亡 dǎozhì… sǐwáng
  ▸ she was carried off by cancer 她被癌症夺去了生命 carry on
 A. intransitive verb
 ① (continue, resume activity) 继续 jìxù
  ▸ if it carries on raining, we'll have to cancel the match 如果雨下个不停的话，我们将不得不取消比赛
  ▸ I'll carry on with this work after lunch 午饭后我会继续做这个工作
 ② (mainly British) (continue in same direction) 继续行进 jìxù xíngjìn
  ▸ to carry on down or along the road (in car) 沿路一直开下去 (on foot) 沿路一直走下去
 ③ informal (behave) 有某种举止 yǒu mǒu zhǒng jǔzhǐ
  ▸ that's no way to carry on 绝不可以有那样的行为
 ④ informal (make fuss) 不断抱怨 bùduàn bàoyuàn
  ▸ to carry on about sb/sth; 不停抱怨某人/某事物
 ⑤ informal dated (have love affair) 有暧昧关系 yǒu àimèi guānxì
  ▸ to carry on with sb; 与某人关系暧昧
 B. [carry on sth] transitive verb
 ① (conduct) 经营 jīngyíng ‹business›; 从事 cóngshì ‹work, trade›; 进行 jìnxíng ‹negotiations, conversation, research›
  ▸ they carried on a correspondence for several years 他们保持了好几年通信联系
 ② (continue) 继续保持 jìxù bǎochí ‹tradition›; 继续经营 jìxù jīngyíng ‹family business›; 继续进行 jìxù jìnxíng ‹conversation, activity›carry out transitive verb [carry out sth, carry sth out]
 ① (go through with) 实行 shíxíng ‹plan, policy, reform›; 执行 zhíxíng ‹order, instruction, mission›; 履行 lǚxíng ‹duty, promise›
  ▸ do you think she will carry out her threat? 你认为她会把威胁付诸行动吗？
 ② (conduct) 进行 jìnxíng ‹research, repair›; 实施 shíshī ‹attack›carry over
 A. transitive verb [carry over sth, carry sth over]
 ① (transfer) 使继续下去 shǐ jìxù xiaqu
  ▸ she carried her business problems over into her private life 她把工作上的问题带到了自己的私人生活中
  ▸ this custom has been carried over from the 19th century 这一习俗从 19 世纪保持至今
 ② (postpone) 推迟 tuīchí ‹event›
  ▸ this debate has been carried over from the last meeting 这一争议是上次会议遗留下来的
 ③ Finance = carry forwardB. intransitive verb 继续存在 jìxù cúnzài
  ▸ these attitudes have carried over from childhood 童年时期形成的这些观念一直保持至今 carry through: transitive verb
 ① [carry through sth, carry sth through] (accomplish) 顺利完成 shùnlì wánchéng
  ▸ to carry through the reforms 把改革进行到底
 ② [to carry sb through] (help to survive) «courage, sense of humour» 帮助…渡过难关 bāngzhù… dùguo nánguān
  ▸ his determination carried him through the ordeal 他靠坚定的信心熬过了这场磨难
*** flower
flower | BrE ˈflaʊə, AmE ˈflaʊ(ə)r |
 A. noun
 ① (bloom) 花 huā
  ▸ to be in/come into flower; 开花 kāihuā
  ▸ to be in full flower literal 盛开 figurative 盛行 shèngxíng
  ▸ to arrange flowers 插花 chāhuā
  ▸ a bunch or bouquet of flowers 一束花
  ▸ ‘no flowers by request’ “不收花圈”
 ② (plant) 开花植物 kāihuā zhíwù
  ▸ wild flowers 野花
  ▸ to plant/sow/grow flowers 种花
 B. intransitive verb
 ① literal «plant, tree» 开花 kāihuā
 ② figurative (develop) «movement» 繁荣 fánróng ; «friendship, talent, young person» 发展成熟 fāzhǎn chéngshú
  ▸ she has flowered into a great writer 她已经成长为一位伟大的作家
*** bride
flower | BrE ˈflaʊə, AmE ˈflaʊ(ə)r |
 A. noun
 ① (bloom) 花 huā
  ▸ to be in/come into flower; 开花 kāihuā
  ▸ to be in full flower literal 盛开 figurative 盛行 shèngxíng
  ▸ to arrange flowers 插花 chāhuā
  ▸ a bunch or bouquet of flowers 一束花
  ▸ ‘no flowers by request’ “不收花圈”
 ② (plant) 开花植物 kāihuā zhíwù
  ▸ wild flowers 野花
  ▸ to plant/sow/grow flowers 种花
 B. intransitive verb
 ① literal «plant, tree» 开花 kāihuā
 ② figurative (develop) «movement» 繁荣 fánróng ; «friendship, talent, young person» 发展成熟 fāzhǎn chéngshú
  ▸ she has flowered into a great writer 她已经成长为一位伟大的作家
*** cry
cry | BrE krʌɪ, AmE kraɪ | 
 A. intransitive verb 
 ① (weep) 哭 kū ; (shed tears) 流泪 liúlèi 
  ▸ to cry about or over sth; 为某事物而哭泣 
  ▸ to cry for sth/sb; (because of) 因为某事物/某人而哭泣 (calling for) 哭着要某物/某人 
  ▸ to cry with pain/hunger 疼/饿得直哭 
  ▸ to cry with laughter 笑出眼泪 
  ▸ to cry for joy 喜极而泣 
  ▸ to cry over spilt milk figurative 为无法挽回的事忧伤 
 ② (call out) = cry out A
 ③ Zoology «bird» 鸣 míng ; «animal» 嗥叫 háojiào 
 B. transitive verb 
 ① (weep) 流出 liúchū 
  ▸ to cry tears of joy 喜极而泣 
  ▸ to cry oneself to sleep 哭到睡着 kū dào shuìzháo 
 ② (shout) 大声表示 dàshēng biǎoshì ‹approval, dismay›; 大声发出 dàshēng fāchū ‹warning›; «vendor» 叫卖 jiàomài ‹wares›
  ▸ ‘look out!’he cried “小心！”他喊道 
 C. noun 
 ① (call) 叫喊 jiàohǎn ; (of vendor) 叫卖声 jiàomài shēng ; (in protest) 呐喊 nàhǎn 
  ▸ to utter a cry 发出一声叫喊 
  ▸ a cry for help 呼救声 
  ▸ to be a cry for help/attention figurative 迫切需要帮助/注意 
  ▸ to be a far cry from sth 与某事物大相径庭 
 ② Zoology 叫声 jiàoshēng ; (huntsman) 吠声 fèi shēng 
  ▸ to be in full cry literal 吠叫着紧追不舍 figurative 大声疾呼 dà shēng jí hū 
  ▸ to be in full cry against sb «crowd» 激情呐喊反对某人 
 ③ (demand) 呼声 hūshēng ; (slogan) 口号 kǒuhào 
  ▸ a cry for/against sth; 支持/反对某事物的呼声 
 ④ (weeping) 哭 kū ; (fit of weeping) 一阵哭泣 yīzhèn kūqì 
  ▸ to have a good cry 大哭一场 
  ▸ to have a cry over sth; 因某事物而哭泣 PHRASAL VERBS cry down transitive verb [cry sth down, cry down sth] dated 贬低 biǎndī ‹efforts, success›cry off intransitive verb British informal 打退堂鼓 dǎ tuìtánggǔ 
  ▸ to cry off from doing sth; 变卦不做某事 cry out 
 A. intransitive verb (call out) 呼喊 hūhǎn ; (yell) 叫喊 jiàohǎn 
  ▸ to cry out to sb; 朝某人叫喊 
  ▸ to cry out for sth/sb; literal 呼喊着要求得到某物/某人 figurative 迫切需要某物/某人 pòqiè xūyào mǒu wù/mǒu rén 
  ▸ to cry out for help 大声呼救 
  ▸ for crying out loud! informal 我的天哪！ 
  ▸ to cry out in pain/ecstasy 痛得/狂喜得大叫 
 B. transitive verb 
  ▸ to cry one's eyes/heart out 痛哭流涕 tòngkū liú tì 
*** child
child | BrE tʃʌɪld, AmE tʃaɪld | noun plural children
 ① (non-adult) 儿童 értóng, 小孩 xiǎohái
  ▸ when I was a child 我小时候
  ▸ a child of six 6 岁的小孩
  ▸ a child star/prodigy 童星/神童
  ▸ to be child's play 是轻而易举的事
  ▸ spare the rod and spoil the child proverb 孩子不打不成器
  ▸ the child is father to the man proverb 三岁看到老
  ▸ to be with child archaic 怀孕
 ② 子女 zǐnǚ [可指儿子或女儿]
  ▸ her mother's child 有其母必有其女
 ③ (immature person) 孩子气的人 háiziqì de rén
  ▸ don't be such a child! 别孩子气啦！
 ④ (inexperienced person) 幼稚的人 yòuzhì de rén
 ⑤ figurative (product) 产物 chǎnwù
  ▸ a child of the 60s/of nature 60 年代的人/大自然之子
 ⑥ children (descendants) 后代 hòudài
*** guitar
guitar | BrE ɡɪˈtɑː, AmE ɡəˈtɑr | noun 吉他 jíta
  ▸ to play the guitar 弹吉他
  ▸ a guitar player 吉他弹奏者
*** musician
musician | BrE mjuːˈzɪʃ(ə)n, AmE mjuˈzɪʃən | noun 音乐家 yīnyuèjiā
*** puddle
puddle | BrE ˈpʌd(ə)l, AmE ˈpədl | noun 水洼 shuǐwā
*** shoulder
shoulder | BrE ˈʃəʊldə, AmE ˈʃoʊldər |
 A. noun
 ① countable Anatomy 肩 jiān
  ▸ to have round/broad/
narrow shoulders 长着溜肩/宽肩/窄肩
  ▸ to carry sb on one's shoulders 背某人
  ▸ to carry sb shoulder high 把某人举到肩上
  ▸ to look (back) over one's shoulder 回过头去看
  ▸ to stand shoulder to shoulder (with sb) （和某人）肩并肩站立
  ▸ to work shoulder to shoulder figurative 齐心协力
  ▸ a shoulder to cry on figurative 倾诉对象
  ▸ to fall on sb's shoulders figurative «responsibility» 落到某人肩上
  ▸ to put one's shoulder to the wheel figurative 全力以赴
  ▸ straight from the shoulder figurative 直截了当地
 ② usually plural countable (part of garment) 肩部 jiānbù
  ▸ padded shoulders 有衬垫的肩部
 ③ uncountable Cooking 肩肘肉 jiānzhǒu ròu
  ▸ a shoulder of lamb 羊前腿连肩肉
 ④ countable (of mountain, hill) 山肩 shānjiān
 ⑤ countable (of road) 路肩 lùjiān
 B. transitive verb
 ① (take on one's shoulder) 扛起 kángqǐ
 ② figurative (take on) 承担 chéngdān ‹blame, responsibility›
 ③ (push with shoulder) 用肩推搡 yòng jiān tuīsǎng
  ▸ to shoulder sb aside/out of the way 肩部一顶把某人挤到一边儿去/挤开
*** turtle
turtle | BrE ˈtəːt(ə)l, AmE ˈtərdl | noun
 ① countable Zoology (marine) 海龟 hǎiguī ; (freshwater) 淡水龟 dànshuǐguī
  ▸ a fresh-water/mud turtle 淡水龟/泥龟
  ▸ a snapping turtle 鳄龟
  ▸ to turn turtle «boat» 倾覆
 ② uncountable Cooking 海龟肉 hǎiguī ròu
*** shirt
shirt | BrE ʃəːt, AmE ʃərt | noun 衬衫 chènshān
  ▸ to wear a shirt 穿衬衫
  ▸ to put on/take off one's shirt 穿上/
脱下衬衫
  ▸ to button up one's shirt 扣上衬衫的扣子
  ▸ a football/rugby/tennis/sports shirt 足球衫/橄榄球衫/网球衫/运动衫
  ▸ to lose one's shirt figurative informal 血本无归
  ▸ to put one's shirt on sth figurative informal 把全部家当押在某事物上
  ▸ keep your shirt on! figurative informal 保持镇静！
  ▸ to sell the shirt off sb's back figurative informal 为了筹钱卖光某人的全部家
  当
*** closet
closet | BrE ˈklɒzɪt, AmE ˈklɑzət |
 A. noun
 ① (mainly US) (cupboard) 壁橱 bìchú ; (for clothes) 衣橱 yīchú
 ② (room) 储藏室 chǔcángshì
 ③ dated (lavatory) 盥洗室 guànxǐshì
 ④
  ▸ figurative the closet 隐秘 yǐnmì
  ▸ to come out of the closet 公开自己的同性恋身份
  ▸ to bring sth/sb out of the closet 公开讨论某事物/某人 gōngkāi tǎolùn mǒu shìwù/mǒu rén
 B. adjective attributive 隐秘的 yǐnmì de
  ▸ a closet fascist/homosexual 潜伏的法西斯分子/不公开的同性恋
 C. transitive verb
  ▸ figurative to be closeted with sb 与某人关门密谈 yǔ mǒu rén guānmén mìtán
  ▸ to be closeted in the boardroom/with one's advisers 在董事会会议室/和顾问们密谈 zài dǒngshìhuì huìyìshì/hé gùwènmen mìtán
  ▸ a closeted world 封闭的世界 fēngbì de shìjiè
*** dish
dish | BrE dɪʃ, AmE dɪʃ |
 A. noun
 ① (plate) 盘子 pánzi
 ② (food) 一盘 yī pán
 ③ (recipe) 一道菜 yī dào cài
  ▸ a hot/side dish 热菜/小菜
 ④ (receptacle) 碟状物 diézhuàngwù
  ▸ a soap dish 肥皂碟
 ⑤ Television 抛物面天线 pāowùmiàn tiānxiàn
 ⑥ informal (good-looking person) 漂亮的人 piàoliang de rén ; (sexy person) 性感的人 xìnggǎn de rén
 B. dishes plural noun 待洗餐具 dài xǐ cānjù
  ▸ to do or wash the dishes 洗碗
 C. transitive verb (mainly British) informal dated 毁掉 huǐdiào ‹chances›
  ▸ to dish the dirt about or on sb/sth 说某人/某事的闲话 PHRASAL VERBS dish out transitive verb [dish out sth, dish sth out]
 ① (serve) 把…分到盘里 bǎ… fēndào pán li ‹food, helping›
 ② (distribute) 分发 fēnfā ‹money, leaflets›; 布置 bùzhì ‹homework›
 ③ (dole out) 提出 tíchū ‹advice›; 给予 jǐyǔ ‹punishment, insults›
  ▸ to dish it out informal 数落人 dish up transitive verb [dish up sth, dish sth up]
 ① (serve) 端上 duānshang
  ▸ to dish up (the) dinner/the food 端上晚饭/饭菜
 ② (come up with) 提出 tíchū ‹argument, idea›; 找出 zhǎochū ‹excuse›
*** tray
tray | BrE treɪ, AmE treɪ | noun
 ① (for food etc.) 托盘 tuōpán
 ② (salver) [放名片、杯子或作为装饰物的] 浅盘 qiǎnpán
 ③ (for baking) 烤盘 kǎopán ; (for roasting) 烤肉盘 kǎoròupán ; (cooling rack) 网眼搁架 wǎngyǎn gējià
 ④ (for papers, letters) 文件盘 wénjiànpán
 ⑤ (for collecting drips) 接油盘 jiēyóupán
*** perform
perform | BrE pəˈfɔːm, AmE pərˈfɔrm |
 A. transitive verb
 ① (carry out) 做 zuò
  ▸ to perform an operation 施行手术
  ▸ to perform an important role 发挥重要作用
  ▸ a saint who performed numerous miracles 创造出无数奇迹的圣人
 ② (for entertainment) 表演 biǎoyǎn
  ▸ the violinist performed a solo 小提琴手演奏了一首独奏曲
  ▸ she performed the part of the queen 她扮演了女王的角色
  ▸ to perform tricks 耍把戏
 ③ (enact) 主持 zhǔchí ‹ceremony, ritual›
 B. intransitive verb
 ① (in play, film, concert etc.) 表演 biǎoyǎn
  ▸ to perform live; 现场演出
  ▸ to perform on the violin 演奏小提琴
  ▸ she performed brilliantly as Viola 她把维奥拉演得惟妙惟肖
 ② (conduct oneself) 表现 biǎoxiàn
  ▸ the students performed better in their exams than last year 学生们考得比去年好
 ③ (work, function) 运行 yùnxíng
  ▸ how is the machine performing? 机器的性能如何？
 ④ Business, Finance 业绩良好 yèjì liánghǎo
  ▸ the economy has been performing rather sluggishly 经济一直都很萧条
*** palm
palm
英 [pɑːm]   美 [pɑːm]  
n.
手掌;手心;棕榈树
v.
把…藏在手中(尤指玩戏法)
第三人称单数： palms 复数： palms 现在分词： palming 过去式： palmed 过去分词： palmed
*** grow
grow | BrE ɡrəʊ, AmE ɡroʊ |
 A. intransitive verb past tense grew past participle grown
 ① (increase in size naturally) 生长 shēngzhǎng
  ▸ her hair had grown very long 她的头发长得很长了
  ▸ to grow X inches/centimetres 长 X 英寸/厘米
  ▸ to grow (to) more than 20 feet long or to a length of more than 20 feet 长到 20 多英尺长
  ▸ to let one's hair/nails grow 蓄发/留指甲
  ▸ to grow from sth; 从…生长起来 ‹seed, bulb, acorn›
 ② (increase in measurable way) «business, money, profits» 增长 zēngzhǎng ; «membership, family» 增多 zēngduō
  ▸ the queue is growing 队列越排越长了
 ③ figurative (increase, develop) «pressure, ability, confidence» 增强 zēngqiáng ; «friendship, love» 加深 jiāshēn ; «anger, fear, crisis» 加剧 jiājù
  ▸ she continues to grow as an artist 身为艺术家，她在不断成长
  ▸ as I listened, my anger grew 我越听越生气
  ▸ to grow in strength/authority/importance/confidence; 在力量/权力/重要性/自信心方面得以增强
  ▸ she has grown in beauty/popularity 她比以前更美丽/更受欢迎了
 ④ (become) 渐渐变成 jiànjiàn biànchéng
  ▸ to grow old 渐渐变老
  ▸ to grow dark/light 慢慢暗下来/亮起来
  ▸ the weather is growing hot 天越来越热
  ▸ to grow impatient 越来越不耐烦
  ▸ to grow used to sth/doing sth 逐渐适应某事/做某事
  ▸ to grow like sb 变得像某人
 ⑤ (reach stage) 开始 kāishǐ
  ▸ to grow to like sb 开始喜欢某人 kāishǐ xǐhuan mǒu rén
  ▸ to grow to expect sth of sb 开始对某人的某事习以为常
 B. transitive verb past tense grew past participle grown
 ① (allow to grow) 使…生长 shǐ… shēngzhǎng ‹part of body, cells›
  ▸ to grow one's hair/a beard 蓄发/蓄须
  ▸ to grow one's nails long 留长指甲
  ▸ the lizard grew a new tail 蜥蜴长出了一条新尾巴
 ② (cause to grow) 种植 zhòngzhí ‹fruit, vegetables, crop›
  ▸ to grow flowers from cuttings/seed 用插条/种子培育这些花
 ③ Business 拓展 tuòzhǎn ‹business, market›; 提高 tígāo ‹sales, production›PHRASAL VERBS grow apart intransitive verb 变得疏远 biàndé shūyuǎn
  ▸ to grow apart from sb; 疏远某人 grow away intransitive verb 变得疏远 biàndé shūyuǎn
  ▸ to grow away from sb; 逐渐疏远某人
  ▸ they had grown away from each other 他们之间逐渐疏远了 grow from transitive verb [grow from sth]
 ① (arise out of) 源于 yuányú ‹activity, condition, earlier stage or form›
  ▸ her scepticism grew from her early experiences 她怀疑的态度源于年少时的经历
 ② (change from) «person» 由…成长而来 yóu… chéngzhǎng ér lái ; «place, business» 由…演变而来 yóu… yǎnbiàn ér lái
  ▸ the city grew from a small village 这座城市是由一座小村庄发展起来的
 ③ (increase from) «number, amount, deficit» 增长 zēngzhǎng ; «population, crime» 增多 zēngduō ; Business «sales, profits» 上涨 shàngzhǎng
  ▸ to grow from sth to sth; 从…发展到某程度 ‹figure, level›
  ▸ the school grew from 400 to 900 pupils 在校学生人数从 400 名上升到 900 名 grow in intransitive verb «nail» 向内生长 xiàng nèi shēngzhǎng grow into transitive verb [grow into sth]
 ① (become) 进入 jìnrù ‹adult›
  ▸ grow into sth larger/older 长得更大/更老
  ▸ grow into sb/sth different 变成不同的人/东西
 ② (fit into) 长得适合于穿着 zhǎng de shìhé yú chuānzhuó ‹garment, shoes›
  ▸ the coat's too big for him now, but he'll grow into it 这件外套他现在穿太大，但他长高后可以穿
 ③ figurative (become accustomed to) 适应 shìyìng ‹role, job›; 养成 yǎngchéng ‹habit›
 ④ (become embedded) «bone, nail» 长进…里 zhǎngjìn… li ‹skin, flesh›grow on transitive verb [grow on sb]
 ① (become ingrained in) «habit, characteristic» 深深影响 shēnshēn yǐngxiǎng ‹person›
 ② (become more appealing to) 越来越受…的喜爱 yuèláiyuè shòu… de xǐ'ài ‹person›
  ▸ the music was starting to grow on me 我越来越喜欢听这种音乐了 grow out
 A. intransitive verb «perm, colour, curls» 长长后被剪掉 zhǎngcháng hòu bèi jiǎndiào
 B. transitive verb [grow sth out, grow out sth] 等…长长后剪掉 děng… zhǎngcháng hòu jiǎndiào ‹perm, colour, curls›grow out of transitive verb [grow out of sth]
 ① (no longer fit into) 长得穿不下 zhǎng de chuānbuxia ‹garment, shoes›
 ② (become too mature for) 随成熟而放弃 suí chéngshú ér fàngqì ‹practice, activity, liking›
  ▸ most children grow out of tantrums by the time they're three 多数孩子到三岁就不会乱发脾气了
  ▸ to grow out of the habit of doing sth 随成熟而放弃做某事的习惯
 ③ (develop from) 源于 yuányú ‹experience, activity, earlier stage or form›grow together intransitive verb
 ① (become more intimate) 变得更亲近 biàn de gèng qīnjìn
 ② (join) «branches, bones, plants» 长到一起 zhǎngdào yīqǐ
  ▸ a tangle of bushes which had grown together 一团纠缠蓬乱的灌木 grow up intransitive verb
 ① (become adult) 长大 zhǎngdà
  ▸ to grow up into sth; 长大成人
  ▸ he grew up into a handsome young man 他长成了英俊的小伙子
  ▸ to grow up to do sth; 长大做某事
  ▸ he grew up to play in the World Cup 他长大后参加了世界杯
 ② (spend childhood) 度过童年 dùguò tóngnián
  ▸ to grow up in London/believing that … 儿时在伦敦度过/儿时就相信…
 ③ (act more sensibly) 变得成熟 biàn de chéngshú
  ▸ oh, grow up! 哎，成熟点好不好！
 ④ (develop) «city, business, movement» 逐渐发展 zhújiàn fāzhǎn ; «idea, friendship, custom, feeling» 形成 xíngchéng
*** giraffe
giraffe | BrE dʒɪˈrɑːf,dʒɪˈraf, AmE dʒəˈræf | noun 长颈鹿 chángjǐnglù
*** chair
chair | BrE tʃɛː, AmE tʃɛr |
 A. noun
 ① (seat) (with no arms and unupholstered) 椅子 yǐzi ; (with arms and upholstered) 单人沙发 dānrén shāfā
  ▸ to sit on/in a chair 坐在椅子上/单人沙发里
  ▸ a dentist's chair 牙医诊疗椅
  ▸ to have or take a chair 坐下
 ② (chairperson) 主席 zhǔxí
  ▸ to take or be in the chair 担任主席
 ③ University 教授职位 jiàoshòu zhíwèi
  ▸ to hold the chair 担任教授
 ④
  ▸ US informal (electric chair) the chair 电椅 diànyǐ
  ▸ to go to the chair 坐上电椅被处死 zuòshang diànyǐ bèi chǔsǐ
  ▸ to be sent to the chair 被送上电椅处死 bèi sòngshang diànyǐ chǔsǐ
 B. transitive verb
 ① (preside over) 主持 zhǔchí ‹meeting›
 ② British (carry) 把…以坐姿高高抬起 bǎ… yǐ zuòzhī gāogāo táiqǐ ‹winner, captain›
* lesson 30
** text
These young people are also travelling across the desert. They like to travell on
 fourwheelers.
  It is a summer's day in the countryside. There is a horse standing under the
  tree. It is relaxing.
 This elderly man is wearing glasses. He is hugging a large white dog around the
 neck and laughing.
 This is a view of the desert. A group of people are travelling on camels.   Three camels are lying in the sand, and two are standing.
 It is a sunny day. The sportsmen are relaxing at a table in the cafe. One of
 them is drinking water from a bottle.
 This is a small, beautiful monkey. It is eating lunch. In front of it are two
 plates of food.

 The girl with glasses is drawing. There is a fish and beautiful sea plants in
 the picture. Two girls are looking at her work.
 This is a restaurant. The young man is paying the waiter in cash. There is a cup
 of coffee on the table in front of him.
 A knife and a fork are lying on a napkin, the napkin is lying on a white tablecloth,
 and the tablecloth is lying on a table.
 The elderly man is sitting on a stool under the tree. His white cap is lying on
 the grass.
 The young man is taking a photo of the girl with long black hair. There is a
 small, white dog sitting on the girl's lap.
 Two girls are sitting on a bench in the park. They are wearing white pants. One of them is
 holding an umbrella.

 The woman who is sitting to the left of the boy is a teacher.
 Rome is a city that tourists like very much.
 The customer who is standing in front of the mirror wants to buy a skirt.
 A seagull is a bird that lives at the sea.
 A turtle is an animal that moves very slowly.
 A cactus is a plant that is able to live in the desert.

 When a person is ill, he goes to the doctor.
 When there is good weather outside, the window in the house is open.
 When there is a traffic jam, the policemen have a lot of work.
 Many customers come to the big shop when there is a sale.
 When it is raining, people open their umbrellas.
 When the parents work, the child plays with his grandmother.

 The woman is drinking water, because she does not want to drink wine.
 The man is turning off the television, because he does not want to watch it any
 longer.
 The waiter is taking away the chicken, because the woman does not like it.
 The man is drinking wine, because he likes it.
 The boy is turning off the computer, because he does not want to play any
 longer.
 The tourists are travelling on the ship, because they do not like to fly on
 airplanes.

 The spectators are going to the theatre in order to watch the performance.
 The boy is turning on the computer in order to play.
 The customers are going to the shop at the time of a sale in order to buy cheap
 goods.
 The man is turning on the television in order to watch an interesting programme.
 The woman is not drinking wine in order to drive the car well.
 The actors are going to the theatre in order to perform on stage.

 The boy is turning on the computer, although his parents would rather him not.
 The woman wants to buy a new dress, even though she has many dresses.
 The girl is not happy, even though today is her birthday.
 The woman does not like the chicken, although it tastes good.
 The woman is drinking water, although she likes wine.
 The girl likes to walk in the forest, though it is raining.

 This is the bus stop. A man is sitting on the bench and reading the newspaper.
 He is waiting for the bus.
 The woman is standing by the sea. She is neither bathing nor tanning. She is
 looking at the sea and waiting for a ship.
 The weather is rainy. The boy is looking out of the window. He is bored, and 
 wants to walk and play outside.
 Today is the little boy's birthday. He is holding a present in his hands. He
 likes this holiday very much.
 Two women in the park are looking at the big grey bird. One woman is holding an
 orange. She wants to feed the bird.
 There is a beautiful, tan saleswoman behind the counter in the small shop. There
 is only one customer in the shop, and he is looking at the wine and fruits.

 Two cheerful girls are walking in the autumn park. They like to play with the
 beautiful yellow leaves.
 The man wants to give flowers to the woman in the beautiful dress. He is holding
 them behind his back, and she is looking at him and laughing.
 This is a large brown bear. It is getting out the water, and the lake and the
 mountains are behind him.
 This is a young woman in blue. She has long hair and beautiful blue eyes. She is
 holding a white cup.
 The bride and groom are celebrating their wedding on the beach at the sea. The
 groom is holding the bride in his arms. she is wearing a long white dress and
 has flowers in her hand.
 This is a large, beautiful, red and white house. Next to the house is a table
 and four chairs. There are small trees growing across from the house.

 Why are the swans not talking on the telephone? They are not talking on the
 telephone because they do not have a telephone.
 Why are people sleeping on the grass. They are sleeping here because they do
 not have a home.
 Why are there many tourists taking photos of the square. They are taking photos
 of it because it is beautiful.
 Why are the girls sleeping during the lesson? They are sleeping because the
 lesson is boring.
 Why are these girls not working and instead spending time at the beach? They are
 spending time at the beach because they are on holiday.
 Why does the giraffe like to eat leaves from tall trees? It likes to do so
 because it has a long neck.
*** first
*** 
 These young people are also travelling across the desert. They like to travel on
 fourwheelers.
 This is a view of the desert. A group of people are travelling on camels. Three
 camels are lying in the sand, and two are standing.
 It is a summer's day in the countryside. There is a horse standing under the
 tree. It is relaxing.
 This elderly man is wearing glasses. He is hugging a large white dog around the
 the neck.
 It is a sunny day. The sportsmen are relaxing at a table in the cafe. One of
 them is drinking water from a bottle.
 This is a small, beautiful monkey. It is eating lunch. In front of it are two
 plates of food.

 The girl with glasses is drawing. There is a fish and beautiful sea plants in
 the picture. Two girls are looking at her work.
 This is a restaurant. The young man is paying the waiter in cash. There is a cup
 of coffee on the table in front of him.
 A knife and a fork are lying on a napkin. The napkin is lying on a white
 tablecloth, and the tablecloth is lying on a table.
 The elderly man is sitting on a stool under the tree. His white cap is lying on the
 the grass.
 The young man is taking a photo of the girl with long black hair. There is a
 small white dog sitting on the girl's lap.
 Two girls are sitting on a bench in the park. They are wearing wh
 white pants. One of them is holding an umbrella.

 The woman who is sitting to the left of the boy is a teacher.
 Rome is a city that tourists like very much.
 A turtle is an animal that moves very slowly.
 A seagull is a bird that lives at the sea.
 A cactus is a plant that is able to live in the desert.
 The customer who is standing in front of the mirror wants to buy a skirt.

 When a person is ill, he goes to the doctor.
 When the parents work, the child plays with his grandmother.
 When there is a traffic jam, the policemen have a lot of work.
 When it is raining, people open their umbrellas.
 When there is good weather outside, the window in the house is open.
 Many customers come to the big shop when there is a sale.

 The woman is drinking water, because she does not want to drink wine.
 The man is drinking wine, because he likes it.
 The waiter is taking away the chicken, because the woman does not like it.
 The tourists are travelling on the ship, because they do not like to fly on
 airplanes.
 The boy is turning off the computer, because he does not want to play any
 longer.
 The man is turning off the television, because he does not want to watch it any
 longer.

 The spectators are going to the theatre in order to watch the performance.
 The actors are going to the theatre in order to perform on stage.
 The boy is turning on the computer in order to play.
 The man is turning on the television in order to watch an interesting programme.
 The woman is not drinking wine in order to drive the car well.
 The customers are going to the shop at the time of a sale in order to buy cheap
 goods.

 The boy is turning on the computer, although his parents would rather him not.
 The woman does not like the chicken, although it tastes good.
 The girl is not happy, even though today is her birthday.
 The girl likes to walk in the forest, though it is raining.
 The woman wants to buy a new dress, even though she has many dresses.
 The woman is drinking water, even though she likes wine.

 Why does the giraffe like to eat leaves from tall trees? It likes to do so
 because it has a long neck.
 Why are these girls not working and instead spending time at the beach? They are
  spending time at the beach because they are on holiday.
 Why are the swans not talking on the telephone?
 They are not talking on the telephone because they do not have a telephone.
 Why are people sleeping onthe grass? They are sleeping here because they do not
 have a home.
 Why are there many tourists taking photos of the square? They are taking photos
 of it because it is beautiful.
 Why are the girls sleeping during the lesson?
 They are sleeping because the lesson is boring.

 This is a large, beautiful, red and white house. Next to the house is a table
 and four chairs. There are small trees growing across from the house.
 This is a large brown bear. It is getting out of the water, and the lake and the
 mountains are behind him.
 The bride and groom are celebrating their wedding on the beach at the sea. The
 groom is holding the bride in his arms. She is wearing a long white dress and
 has flowers in her hand.
 Two women in the park are looking at the big grey bird. One woman is holding an
 orange. She wants to feed the bird.
 The man wants to give flowers to the woman in the beautiful dress. He is holding
 them behind his back, and she is looking at him and laughing.
 The cheerful girls are walking in the autumn park. They like to play with the
 beautiful yellow leaves.
 This is a young woman in blue. She has long hair and beautiful blue eyes. She is
 holding a white cup.

 This is the bus stop. A man is sitting on the bench and reading the newspaper.
 He is waiting for the bus.
 The woman is standing by the sea. She is neither bathing nor tanning. She is
 looking at the sea and waiting for a ship.
Second
It is a summer's day in the countryside. There is a horse standing under the
 tree. It is relaxing.
This elderly man is wearing glasses. He is hugging a large white dog around the
 neck and laughing.
The elderly man is sitting on a stool under the tree. His white cap is lying on
 the grass.
The young man is taking a photo of the girl with long black hair. There is a
 small white dog sitting on the girl's lap.
These young people are also travelling across the desert. They like to travel on
 fourwheelers.
The tourists are travelling on the ship, because they do not like to fly on
 airplanes.
This is a small, beautiful monkey. It is eating lunch. In front of it are two
 plates of food.
The bride and groom are celebrating their wedding on the beach at the sea. The
 groom is holding the bride in his arms. She is wearing a long white dress and
 has flowers in her hands.
This is the bus stop. A man is sitting on the bench and reading the newspaper.
 He is waiting for the bus.
There is a beautiful, tan saleswoman behind the counter in the small shop.
 Therre is only one customer in the shop, and he is looking at wine and fruits.
This is a large brown bear. It is getting out of the water, and the lake and the
 mountains are behind him.
Why does the giraff like to eat leaves from tall trees? It likes to do so
 because it has a long neck.
Why are the girls sleeping during the lesson? They are sleeping because the
 lesson is boring.
Why are the swans not talking on the telephone? They are not talking on the
 telephone because they do not have a telephone.
Why are the people sleeping on the grass? They are sleeping here because they do
 not have a home.
* lesson 31
** Words
flight
registration
a currency exchange booth
a waiting area
passport control
customs control

to go through
to exchange currency
to carry
to check baggage
to check
to claim baggage

a gate
a boarding pass
a passenger
a customs afficial
a stewardess
a seat

heavy
a heavy suitcase 
a heavy book
a light bag
a light
a light computer 

This suitcase is big and heavy.
The brother isn't holding his sister. She's heavy.
Is this book heavy? No, it's light. You can carry it in a bag.
Is the bag light? Yes, it's light: children can carry it.
The brother is light, but his sister is heavvy.
The sister is holding her brother. He's light.

The people are claiming their baggage.
The woman is claiming her baggage. She's taking her heavy suitcase.
The boy is claiming his baggage. He's taking his light bag.
The man is checking his baggage.
The girl isn't checking her baggage. She's taking her bag onto the plane.
The woman also is checking her baggage.

The woman also is going through registration with her children. She also is
showing their tickets and passports.
People with boarding passes go to the waiting area.
On the boarding pass is the seat number on the plane.
In the big waiting area people wait for their flights.
The man is going through registration. He's showing his ticket and passport.
At registration people check their baggage and receive their boarding pass.

The man also is exchanging currency.
The man also is going to the currency exchange booth. He wants to exchange currency. 
The stewardess brings the passengers food.
The stewardess shows the passengers their seats on the plane.
The stewardess meets the passengers by the plane.
The woman is exchanging currency.

The customs official is checking their passports.
The man is checking where his money is.
The woman is going through passport control with her child.
The man is going through customs control.
The woman is checking her flight on her ticket.
The customs official is checking his baggage.

Is the man going through passport or customs control? He is going through
customs control.
Are the children sitting on the plane or in the waiting area?
The children are sitting in the waiting area.
Is the man going through passport or customs control?
He is going through passport control.
Is the boy exchanging currency or buying ice cream? 
He is buying ice cream.
Is the woman checking her baggage or claiming it? 
The woman is checking her baggage.
Is the woman checking her baggage or claiming it? 
The woman is claiming her baggage.

What is the man doing? He is going through registration and receiving his
boarding pass.
What is the woman doing? She is going through  passport control  with her child.
What is the customs official doing? He is checking baggage.
What is the stewardess doing? She is bringing the man a glass water.
What are the boy and the girl doing? They are playing in the waiting area.
What are the man and the woman doing? They are waiting for their flight.

* lesson 32
** words
a floor
a room
*** a hotel
hotel	英[həʊˈtel]
美[hoʊˈtel]
n.	旅馆; 旅社; 酒吧; 酒馆; 餐馆;
vi.	使…在饭店下榻进行旅馆式办公;
[例句]We had dinner in the hotel's restaurant.
我们在这家宾馆的餐厅吃了晚饭。
[其他]	第三人称单数：hotels 复数：hotels 现在分词：hotelling 过去式：hotelled
过去分词：hotelled

 a form
 a reception desk
 a receptionist

 to take a shower
 to choose
 to wash up
 to fill out
 to offer
 to make a reservation

 The kitchen before
 the kitchen after
 The painting before
 the painting after
 the oranges before 
 the oranges after

 a key
 a bathtub
 a bathroom
 a door
 a window
 a shower

 a soft chair
 a hard chair
 a single room
 a double room
 the first floor
 the second floor

 The man is saying to the receptionist: I have reserved a room.
 The man is filling out the form. The woman also is filling out the form.
 The receptionist is giving the man and the woman forms.
 Behind the reception desk stands a receptionist.
 The woman also has reserved a room.
 The tourists are entering the hotel.

 The receptionist is offer the woman and her child a double room.
 The man is paying with a credit card and taking the keys.
 The woman is paying with cash and taking the keys.
 The receptionist is offering the man a single room.
 The woman chooses an inexpensive double room with a view of the mountains on the
 first floor.
 The man chooses an expensive room with a view of the sea on the second floor.

 The girl is going down in the elevator.
 The man is opening the door with the key.
 The man is going up in the elevator.
 The woman doesn't need to go up in the elevator.
 The man is waiting for the elevator. He also wants to go down in the elevator.
 The woman is giving her daughter the key.

 The woman is sleeping in the soft bed.
 The girl is lying on the hard floor.
 The receptionist is sleeping on the hard chair.
 a hard couch
 a soft bed
 The man is sitting on the soft chair.

 The woman is going down to the restaurant before dinner.
 The man has reserved a room before his arrival at the hotel.
 The children are washing up before breakfast.
 The tourist is taking a shower after a walk.
 The woman is filling out a form after her arrival at the hotel.
 The man is going up to his room after breakfast.

 The boy also wants to take a shower.
 The man is washing up.
 The woman is washing up.
 The girl is taking a shower.
 The clean child is sitting in the big white bathtub.
 The mother is washing her dirty child in the bathtub.

 In the morning before breakfast people wash up.
 The little boy is sleeping in a soft bed before dinner.
 After a shower the woman puts on a long white robe.
 After the excursion to the mountains the tourists want to take a shower.
 After the rain there are many puddles on the street.
 The tourists are reserving a hotel before buying plane tickets.

 The girl is taking a shower because she's dirty.
 The woman gives the key to her daughter because she has a bag in her arms.
 The woman is going up in the elevator because she has a heavy suitcase.
 The man is lying on the soft couch because he's watching television.
 The boy is smiling because he likes the hotel.
 The family is going to this hotel because they have reserved a room in it.

* lesson 33
** Words
*** drapes
drapes	英[dreɪps]
美[dreɪps]
v.	将(衣服、织物等)悬挂，披; 遮盖; 盖住; 装饰; 使(身体部位)放松地搭在…上;
n.	(厚长的) 帘子，帷帘，帷幕;
[词典]	drape 的第三人称单数和复数;
[例句]He pulled the drapes shut, locked the door behind him.
他把帘子拉严，转身把门锁好。
[其他]	原型： drape

 a ceiling
 a fireplace

On the window in the living room hang beautiful, green drapes.

***  blinds

blinds	英[blaɪndz]
美[blaɪndz]
n.	窗帘; (尤指) 卷帘; 用以蒙蔽人的言行; 借口; 托词; 幌子;
v.	使变瞎; 使失明; 使眼花; 使目眩; 使思维混沌; 使失去判断力;
[词典]	blind 的第三人称单数和复数;
[例句]Mother was lying on her bed, with the blinds drawn.
母亲正躺在床上，百叶窗已经拉了下来。
[其他]	原型： blind
All of the window hang blinds.
On this room hang blinds, but on the other - curtains.
All of the windows hang blinds.
*** curtains 
curtains	英[ˈkɜːtnz]
美[ˈkɜːrtnz]
n.	窗帘; 帘; 幔; (遮隔房间的) 帷幔; 床帷; (舞台上的) 幕，幕布，帷幕;
[词典]	curtain 的复数;
[例句]Her bedroom curtains were drawn.
她卧室的窗帘拉上了。
[其他]	原型： curtain

 a floor
*** a balcony
balcony	英[ˈbælkəni]
美[ˈbælkəni]
n.	阳台; (剧院的) 楼厅，楼座;
[例句]She led us to a room with a balcony overlooking the harbour
她把我们领进了一个带阳台的房间，从那里可以俯瞰海港。
[其他]	复数：balconies
***  to look for
ook for 和 find 的区别为：意思不同、用法不同、侧重点不同
**** 一、意思不同

 1、look for：寻找；寻求；期 2113 待

 2、find：发现；找到；认为；觉得
**** 二、用法不同 5261

 1、look for：接名 4102 词或代词作宾语。也可接以形容词充当补足语的复合宾语。

 例句：

 He turned on the torch to look for his keys

 他打开了手电筒，寻找钥匙。

 2、find：接名词、代词、带疑问词的动词不定式或从句作宾语，也可接双宾语，其间接宾语可以转换为介词 for 的宾语，可用于被动结构。

 例句：

 He tried to find in the list his own name

 他试图在名单上找到自己的名字。
**** 三、1653 侧重点不同

 1、look for：指客观存在的。

 2、find：指抽象的或客观存在的。
      评论 

  喵喵喵 0597  
 2019-05-18
**** 一、侧重点不同

 1、作为“寻找”，find 的意思 2113 更加强调结果，是否找到东西了？不管是偶然找到，或者是无意中发现了具体的东西，都可以用 find 来强调这个找到的结果。

 I've just found a ten-pound note in my pocket.

 我在我的口袋里发现了十磅。

 2、look for  寻找

 look for，则更加强调寻找的过程，不管现在结果是否找到，但是确实有这个寻找的过程存在，可以把它理解成“try to find”（尝试找到东西的过程）

 I'm looking for my bike．

 我正 5261 在找我的自行车。
**** 二、用法不同

 1、find：用作及物动词，主要用于下列句型：

 (1) 后接名词或代词。

 (2) 后接复合结构 (名词的复合结构、形容词的复合结构、现在分词的复合结构、过去分词的复合结构、不定式的复合结构等等) 。

 2、look for 用法比较单一，没有以上这些用法。
****  三、与时间连用的状态不同

 1、find 是终止性动词，一 4102 般不与一段时间连用。

 2、look for 可以与一段时间连用。
**** 扩展资料

 同义词：

 1、search

 英 [sɜːtʃ]   美 [sɜːrtʃ]  

 n.搜索；搜 1653 寻；搜查；查找；检索

 v.搜索；搜寻；搜查；查找；搜身；思索，细想(问题答案等)

 She went into the kitchen in search of (= looking for) a drink.

 她进了厨房，想找点喝的。

 2、seek

 英 [siːk]   美 [siːk]  

 v.寻找；寻求；谋求；争取；(向人)请求

 They sought in vain for somewhere to shelter.

 他们怎么也找不到一个藏身的地方。
***   to hang
hang	英[hæŋ]
美[hæŋ]
v.	悬挂; 吊; 垂下; 垂落; (使) 低垂，下垂;
n.	(衣服、织物等的) 悬挂方式，下垂;
[例句]Notices painted on sheets hang at every entrance
写在纸上的告示悬挂在每个入口。
[其他]	第三人称单数：hangs 现在分词：hanging 过去式：hung 过去分词：hung
***  to fit
fit	英[fɪt]
美[fɪt]
v.	(形状和尺寸) 适合，合身; (大小、式样、数量适合) 可容纳，装进; 试穿(衣服);
adj.	健壮的; 健康的; (质量、素质或技能) 适合的，恰当的，合格的; 可能(或准备)做某事至极端程度;
n.	(癫痫等的) 突发，发作; 昏厥; 痉挛; 一阵(忍不住的咳嗽、笑); (强烈感情) 发作，冲动;
[例句]The sash, kimono, and other garments were made to fit a child
腰带、和服和其他衣服都是儿童款的。
[其他]	比较级：fitter 最高级：fittest 第三人称单数：fits 复数：fits 现在分词：fitting 过去式：fitted 过去分词：fitted

 to stand
 to find
***  to lie
lie	英[laɪ]
美[laɪ]
v.	躺; 平躺; 平卧; 平放; 处于，保留，保持(某种状态);
n.	谎言; 位置;
v.	说谎; 撒谎; 编造谎言;
[例句]There was a child lying on the ground
地上躺着一个小孩。
[其他]	第三人称单数：lies 复数：lies 现在分词：lying 过去式：lay 过去分词：lain

 bed sheets
 a chandelier
 a floor lamp
***  a pillow
pillow	英[ˈpɪləʊ]
美[ˈpɪloʊ]
n.	枕头;
v.	枕着(某物);
[例句]I have a pillow with my name embroidered on it.
我有一个绣着我名字的枕头。
[其他]	第三人称单数：pillows 复数：pillows 现在分词：pillowing 过去式：pillowed 过去分词：pillowed
***  a blanket
blanket	英[ˈblæŋkɪt]
美[ˈblæŋkɪt]
n.	毯子; 毛毯; 厚层; 厚的覆盖层;
adj.	包括所有情形(或人员)的; 总括的; 综合的;
v.	以厚层覆盖;
[例句]The mud disappeared under a blanket of snow
泥巴被积雪盖住了。
[其他]	第三人称单数：blankets 复数：blankets 现在分词：blanketing 过去式：blanketed 过去分词：blanketed
***  a rug
rug	英[rʌɡ]
美[rʌɡ]
n.	小地毯; 垫子; (盖腿的) 厚毯子;
[例句]A Persian rug covered the hardwood floors.
硬木地板上铺着一张波斯地毯。
[其他]	复数：rugs

 the other
 none
 outside
 this
 all
 inside
** text
In the room to the right of the bed stands a beautiful floor lamp.

This rug doesn't hang on the wall. It lies on the ground.

On the window in the living room hang beautiful, green drapes.

To the right of the bed stands a lamp, not a television.

On the fireplace stands a clock, not a computer.

On the ceiling hangs a beautiful, valuable, big chandelier.

A big, white, soft pillow is lying on the floor.

A girl is standing on the balcony. She is looking at the tall buildings.

In front of the bed on the floor lies a soft rug.

A soft blanket is lying on the bed.

A boy is lying on the wooden floor and looking at the beautiful chandelier on
the ceiling.

A woman is bringing clean bed sheets to the room.

On all of the windows hang blinds.

All of the blinds on the windows are closed.

On this window hang blinds, but on the other - curtains.

In this room there's a balcony, but in the other room there's not.

In all of the expensive hotel rooms  there is a beautiful fireplace.

This key doesn't fit this door. It is the other key.

The bag is ourside the closet.

Inside the house it's warm, but outside it's cold.

Inside the fireplace it's dirty, but outside it's clean.

A father and son are sitting at a table outside. They don't see the people who
are sitting inside.

The clothes are inside the closet.

A mother and daughter are sitting at a table inside the cafe. They don't see the people who
are sitting outside.

In the room it's hot. No one is sleeping under a blanket.

In the winter no one opens the balcony.

None of the brides wears a blue dress.

All brides wear a white dress to the wedding.

None of the students in the school wears a red jacket.

All the students in the school wear blue jackets.

The student is looking for a book on the shelf.

The boy and the girl are looking for their younger brother in the room.

The girl finds a beautiful flower in the grass.

The woman before the door is looking for the key in her bag.

The woman finds the key on the floor.

The boy finds a gift under the pillow.

The mother is looking for her son outside, but he's inside the house.

The boy is looking for the towel, but it's hanging in the bathroom.

The woman is looking for the blanket, but she doesn't find it.

The man is looking for the pillow, but he doesn't find it.

The woman finds a key on the floor, but it doesn't fit.

The student is looking for the book in the bag, but it's lying on the table.

The woman works in the hotel, so she brings clean bed sheets to the room.

The cat isn't in the room, so the boy is looking for it in the cabinet.

In the room it's cold, so the boy is lying under a thick blanket.

The boy doesn't find money, so he doesn't buy ice cream.

The book isn't on the table, so the man is looking for it in the cabinet.

On the ceiling hangs a beautiful chandelier, so the girl is looking at the
ceiling.

* lesson 34
** words
*** soup
soup	英[suːp]
美[suːp]
n.	汤; 羹;
v.	使振作; 打扮; 竖起;
[例句]She has a knack of landing herself right in the soup.
她老是让自己的处境很尴尬。
[其他]	第三人称单数：soups 复数：soups 现在分词：souping 过去式：souped 过去分
词：souped
***  salad
salad	英[ˈsæləd]
美[ˈsæləd]
n.	(生吃的) 蔬菜色拉，蔬菜沙拉; (拌有肉、鱼、奶酪等的) 混合色拉，混合沙拉; (或生或熟，多拌有蛋黄酱，与面食、豆类等一起食用的) 蔬菜色拉;
[例句]The Grand Hotel did not seem to have changed since her salad days.
从她年少时候到现在，格兰德酒店似乎一直就没有变过。
[其他]	复数：salads
***  cabbage
cabbage	英[ˈkæbɪdʒ]
美[ˈkæbɪdʒ]
n.	甘蓝; 卷心菜; 洋白菜;
[例句]They ate a mash of 2 potatoes, 2 carrots& cabbage
他们吃了由两个土豆、两根胡萝卜和洋白菜做的糊。
[其他]	复数：cabbages
*** mushrooms
mushroom	英[ˈmʌʃrʊm]
美[ˈmʌʃrʊm]
n.	蘑菇; 蕈; 伞菌;
v.	快速生长; 迅速增长; 采蘑菇;
[例句]There are many types of wild mushrooms.
野生蘑菇有很多种。
[其他]	第三人称单数：mushrooms 复数：mushrooms 现在分词：mushrooming 过去式：mushroomed 过去分词：mushroomed
***  mashed potatoes
土豆泥
*** onion
onion	英[ˈʌnjən]
美[ˈʌnjən]
n.	洋葱; 葱头;
[例句]Will you chop an onion up for me?
你能帮我把一个洋葱切碎吗？
[其他]	复数：onions
***  to cook
烹调
*** to boil
沸腾（煮开）
***  to fry
煎
The chef is frying chicken because the man and the woman want fried chicken.
In order to fry chicken, you need a roasting pan.
The woman is frying potatoes because she is making lunch for the family.
What is the chef doing? He's frying a whole chicken.

*** to bring food
The man is asking the waiter to bring appetizers.
All tourists bring with them a compass when they go into the woods.
The waiter brings the change and receipt on a tray.
***  to try 
Mom is preparing tasty food, and dad is trying it.
Mom is baking a pie with onion and egg, and dad is making vegetable soup.
The girl is trying on a white, thin, small-sized blouse without embroidery.
The girl is trying on a red high heels
The man is trying on a blue shirt. It's his size.

***  to bake
烧烤
Does the boy know how to bake pies? No, he doesn't know how to bake pies. He's
still very small.
Does grandma know how to bake tasty pies with cabbage? Yes, grandma knows how to
bake tasty pies.
Does the man know how to bake pies? No, he doesn't know how to bake pies.
The chef bakes tasty pies.
In order to bake pie with egg, you need to fry eggs.

***  fried

fried	英[fraɪd]
美[fraɪd]
v.	油炸; 油煎; 油炒; (被阳光) 灼伤，晒伤;
[词典]	fry 的过去分词和过去式;
[例句]I fried up the beef
我把牛肉煎了一下。
[其他]	原型： fry

The chef is frying chicken because the man and the woman want fried chicken.
For mashed potatoes, you need boiled potatoes, not fried.
The father wants fried potatoes for lunch, but his son wants fresh vegetable
salad.

***  tasty
tasty	英[ˈteɪsti]
美[ˈteɪsti]
adj.	美味的; 可口的; 好吃的; 风骚的，有味道的，性感的(男子用以形容性感女子);
n.	可口的东西; 引人入胜的东西;
[例句]Try this tasty dish for supper with a crispy salad
晚饭就着鲜脆的色拉尝尝这道佳肴。
[其他]	比较级：tastier 最高级：tastiest 复数：tasties

The chef in the café makes tasty soup, so many people go to the café.
The chef bakes tasty pies.
In order to prepare tasty vegetabls soup, you need fresh vegetables.
Does grandma know how to bake tasty pies with cabbage? Yes, grandma knows how to
bake tasty pies.

***  boiled

boiled	英[bɔɪld]
美[bɔɪld]
v.	(使) 沸腾; 煮沸; 烧开; (把壶、锅等) 里面的水烧开; 用沸水煮(或烫洗); 被煮(或烫洗);
[词典]	boil 的过去分词和过去式;
[例句]The milk has boiled over.
牛奶煮沸了，都溢出来了。
[其他]	原型： boil

The chef is boiling cabbage in the pot.
Dad is making mashed potatoes from boiled potatoes.
For mashed potatoes, you need boiled potatoes, not fried.
***  hot
hot	英[hɒt]
美[hɑːt]
adj.	温度高的; 热的; 觉得闷(或燥、湿)热; 使人感到热的;
v.	（变，加） 热; 把……加温; （使） 激动起来;
[例句]When the oil is hot, add the sliced onion
油热了后，放入切好的洋葱。
[其他]	比较级：hotter 最高级：hottest 第三人称单数：hots 现在分词：hotting 过去
式：hotted 过去分词：hotted

In the south it's hot.
People swim in the sea in the south, because in the south the sea is warm.
The children love hot pies with potatoes and milk.

***  cold
cold	英[kəʊld]
美[koʊld]
adj.	寒冷的; 冷的; 未热过的; 已凉的; 冷却的; 冷漠的; 不友好的;
n.	冷; 寒冷; (尤指) 低气温; 感冒; 伤风; 着凉;
adv.	突然; 完全; 毫无准备地;
[例句]Rinse the vegetables under cold running water
用凉的自来水清洗这些蔬菜。
[其他]	比较级：colder 最高级：coldest 复数：colds

The boy doesn't drink warm milk. He wants cold juice.
The cat is drinking cold milk.
In the north it's cold.
Polar bears swim in the sea in the north, because in the north the sea is cold.

*** fresh
fresh	英[freʃ]
美[freʃ]
adj.	新鲜的; 新产的; 刚摘的; 新近的; 新近出现的; 新近体验的; 新的; 不同的;
adv.	刚刚，才，最新地;
[例句]He asked Strathclyde police, which carried out the original investigation, to make fresh inquiries
他要求原来负责案子的斯特拉斯克莱德警方展开新一轮的调查。
[其他]	比较级：fresher 最高级：freshest

fresh vegetables
fresh onion
In order to prepare tasty vegetable soup, you need fresh vegetables.
For salad you need fresh vegetables.
The father wants fried potatoes for lunch, but his son wants fresh vegetable salad.

***  pie with potato 
土豆派
The children love hot pies with potatoes and milk.

 pie with onion and egg
Mom is baking a pie with onion and egg, and dad is making vegetable soup.

 pie with meat
The man is ordering a pie with meat in the café. 
The children love pies with meat, so their mom is baking pies with meat.

 pie
 pie with cabbage
 pie with mushrooms
*** appetizers
appetizers
英[ˈæpɪtaɪzəz]
美[ˈæpəˌtaɪzərz]
n.	(餐前的) 开胃品，开胃饮料;
[词典]	appetizer 的复数;
[例句]As I was looking at the appetizers, I spotted one of my favorite dishes – crab cakes!
当我正在看有没有什么好菜，发现了一个我的最爱&蟹饼！
[其他]	原型： appetizer

The man is asking the waiter to bring appetizers.
At the bar they sell drinks and appetizers.

***  a café
café	
网络	咖啡馆; 咖啡屋; 小餐馆; 咖啡室; 咖啡厅;
[例句]我们在最不起眼的酒吧和咖啡馆找到了最可口、最具创意的肉菜饭和餐前小吃。
We found the tastiest and most imaginative paella and tapas in the most
unprepossessing bars and caf é s.
The man is ordering a pie with meat in the café.
The chef in the café makes tasty soup, so many people go to the café.
***  a bar
bar	英[bɑː(r)]
美[bɑːr]
n.	酒吧; (出售饮料等的) 柜台; (专售某类饮食的) 小吃店，小馆子;
v.	(用铁条或木条) 封，堵; 阻挡; 拦住; 禁止，阻止(某人做某事);
prep.	除…外;
[例句]I'll see you in the bar later
一会儿酒吧见。
[其他]	第三人称单数：bars 复数：bars 现在分词：barring 过去式：barred 过去分词：
barred
***  strong drinks
The men come to the bar to drink strong drinks.
The child doesn't drink strong drinks, his mom gives him water with lemon.
The man and the woman are sitting at the dark bar and drinking strong drinks.

 drinks
 milk

 fresh cabbage
 mushroom soup
 fresh onion
 vegetable salad
 fried onion
 boiled cabbage

 The mother is feeding her son mashed potatoes.
 The woman is eating vegetable salad for breakfast.
 The children don't love onion.
 The cat is drinking cold milk.
 The children love hot pies with potatoes and milk.
 The boy doesn't drink warm milk. He wants cold juice.

 Dad is making mashed potatoes from boiled potatoes.
 The chef is boiling cabbage in the pot.
 The man is ordering a pie with meat in the café.
 Mom is preparing tasty food, and dad is trying it.
 The mother is making vegetable soup for her children.
 The chef bakes tasty pies.

 The chef in the café makes tasty soup, so many people go to the café.
 The children love pies with meat, so their mom is baking pies with meat.
 The father wants fried potatoes for lunch, but his son wants fresh vegetable salad.
 The woman is frying potatoes because she's making lunch for the family.
 Mom is baking a pie with onion and egg, and dad is making vegetable soup.
 The chef is frying chicken because the man and the woman want fried chicken.

 The man and the woman are sitting in the dark bar and drinking strong drinks.
 The child doesn't drink strong drinks. His mom gives him water with lemon.
 Men come to the bar to drink strong drinks.
 The women are drinking wine at the bar.
 The man is asking the waiter to bring appetizers.
 At the bar they sell drinks and appetizers.

 For salad you need fresh vegetables.
 In order to prepare tasty vegetable soup, you need fresh vegetables.
 In order to fry chicken, you need a roasting pan.
 For mashed potatoes, you need boiled potatoes, not fried.
 For mushroom soup you need mushrooms, not meet.
 In order to bake pie with egg, you need to fry eggs.

 Does grandma know how to bake tasty pies with cabbage? Yes, grandma knows how to
 bake tasty pies.
 Does the man know how to bake pies? No, he doesn't know how to bake 
 pies.
 Does the girl know how to prepare vegetable salad? Yes, she prepares vegetable
 salad well.
 Does the boy know how to fry potatoes? No, he doesn't know how to fry potatoes.
 He's still very small.
 Does mom know how to make tasty soup? Yes, mom knows how to make tasty soups.
 Does the chef know how to cook? Yes, he prepares very tasty food.



* lesson 35
** words
*** a coat
coat	英[kəʊt]
美[koʊt]
n.	外套; 外衣; 大衣; (套装的) 上装; 动物皮毛;
v.	给…涂上一层; (用…) 覆盖;
[例句]He turned off the television, put on his coat and walked out.
他关掉电视，穿上外套，出门了。
[其他]	第三人称单数：coats 复数：coats 现在分词：coating 过去式：coated 过去分
词：coated
a light coat
a large-sized coat
a small-sized coat
a coat my size

In order to sew a coat, you need fabric.
The salesperson is showing the woman a coat.
The woman is giving the salesperson a tight coat - it's not her size.

*** a sweater
sweater	英[ˈswetə(r)]
美[ˈswetər]
n.	毛衣，线衣(英国英语指套头无扣的; 美国英语可指开襟有扣的);
[例句]She wore a thick tartan skirt and a red cashmere sweater.
她穿了一条厚厚的格子呢裙和一件红色羊绒衫。
[其他]	复数：sweaters

The grandmother is knitting a warm, grey sweater for her grandson.

*** a blouse
blouse	英[blaʊz]
美[blaʊs]
n.	(女式) 短上衣，衬衫;
[例句]That morning I had put on a pair of black slacks and a long-sleeved black blouse.
那天早上，我穿了一条宽松的黑裤子和一件长袖黑衬衫。
[其他]	复数：blouses

Do all men like women in white blouses with embroidery?
Yes, all men like such women.
The girl is trying on a white, thin, small-sized blouse with embroidery.

*** tights
tights	英[taɪts]
美[taɪts]
n.	(女用) 连裤袜，紧身裤; (尤指舞蹈演员穿的) 紧身衣裤;
[例句]He was horrified at the thought of his son prancing about on a stage in tights.
一想到儿子身穿紧身衣在舞台上神气活现地走来走去，他就感到震惊。
The woman takes off light, grey tights.
In the west women wear tight pants.
The girl is wearing a short, tight, small-sized skirt.
The woman is giving the salesperson a tight coat - it's not her size.

*** socks
sock	英[sɒk]
美[sɑːk]
n.	短袜; (尤指用拳头) 猛击，重击;
v.	猛击; 狠打;
[例句]Come on, lads. Sock it to 'em.
来吧，伙计们，让他们开开眼。
[其他]	第三人称单数：socks 复数：socks 现在分词：socking 过去式：socked
The man puts on warm, white socks.
Do all  grandmothers like to sew warm socks for their grandchildren?
Yes, they like it.
The boy wants to knit socks, but he doesn't know how.


*** a tank top
anktop	
网络	背心; 坦克背心; 小可爱背心; 吊带;

vest 是“背心、汗衫来、内衣”的意思。 
tank top 是“紧身短背心”的意思。

一. “tank top”,就是中文里所讲的背心,也就是那种无袖的上衣。

二. “tank top“即无袖的上衣，还没有源到吊带衫那么露的。

三.句子 brown knee-length skirt, orange tank top, ponytail（棕色膝盖长度的裙子,
橙色无袖的上衣, 扎着马尾辫）。

The boy in the white tank top is sitting on the bench.
There is no embroidery on the tank top.
*** vest
vest	英[vest]
美[vest]
n.	(衬衣等里面贴身穿的) 背心，汗衫; 坎肩; (外面穿的) 背心;
v.	给予; 授予某人某种权力; (指财产等) 归属;
[例句]All authority was vested in the woman, who discharged every kind of public duty
女性被赋予了所有权力，履行所有公共职责。
[其他]	第三人称单数：vests 复数：vests 现在分词：vesting 过去式：vested

*** a warm sweater
sweater	英[ˈswetə(r)]
美[ˈswetər]
n.	毛衣，线衣(英国英语指套头无扣的; 美国英语可指开襟有扣的);
[例句]She wore a thick tartan skirt and a red cashmere sweater.
她穿了一条厚厚的格子呢裙和一件红色羊绒衫。
[其他]	复数：sweaters


*** a long skirt
skirt	英[skɜːt]
美[skɜːrt]
n.	女裙; (连衣裙、外衣等的) 下摆; (车辆或机器基座的) 挡板，裙板;
v.	环绕…的四周; 位于…的边缘; 沿…的边缘走; 绕开，回避(话题);
[例句]We raced across a large field that skirted the slope of a hill.
我们从山坡下的一大片田地里飞奔而过。
[其他]	第三人称单数：skirts 复数：skirts 现在分词：skirting 过去式：skirted

a short skirt
a light coat
loose pants 
tight pants

The girl is wearing a short, tight, small-sized skirt.

*** to embroider 
embroider	英[ɪmˈbrɔɪdə(r)]
美[ɪmˈbrɔɪdər]
v.	刺绣; 加以渲染(或润色); 添枝加叶;
[例句]The collar was embroidered with very small red strawberries
衣领上绣着非常小的红色草莓。
[其他]	第三人称单数：embroiders 现在分词：embroidering 过去式：embroidered 过去
分词：embroidered

In order to embroider, you need a needle and thread.
The woman is embroidering a red flower on white fabric.
The girl gets a needle with red thread. She wants to embroider.
*** to cut 
cut	英[kʌt]
美[kʌt]
v.	切; 割; 割破; 划破; (用刀等从某物上) 切下，割下; (用刀等将某物) 切成，割成;
n.	伤口; 划口; (锋利物留下的) 开口，破口; (数量、尺寸、供应等的) 削减，减少，缩减;
[例句]Mrs. Haines stood nearby, holding scissors to cut a ribbon
海恩斯夫人站在旁边，手持剪刀准备剪彩。
[其他]	第三人称单数：cuts 现在分词：cutting 过去式：cut 过去分词：cut

The girl is holding a scissors in her right hand, and fabric in her left. She
wants to cut.
In order to cut thread, you need scissors.
The boy is cutting a piece of paper in half.
*** to put on 
穿上


*** to take off
脱下，不及物时飞机起飞

*** to sew
sew	英[səʊ]
美[soʊ]
v.	缝; 做针线活; 缝制; 缝补; 缝上;
[例句]The hand was preserved in ice by neighbours and sewn back on in hospital
手被邻居用冰块保存起来了，在医院又被缝合好了。
[其他]	第三人称单数：sews 现在分词：sewing 过去式：sewed 过去分词：sewn

*** to knit
knit	英[nɪt]
美[nɪt]
v.	编织; 针织; 机织; 织平针; (使) 紧密结合，严密，紧凑;
n.	编织的衣服; 针织衫;
[例句]I had endless hours to knit and sew
我整天无休止地编织缝纫。
[其他]	第三人称单数：knits 复数：knits 现在分词：knitting 过去式：knitted 过去
分词：knitted

*** thread
thread	英[θred]
美[θred]
n.	(棉、毛、丝等的) 线; 线索; 脉络; 思绪; 思路; 贯穿的主线; 线状物; 细细的一条;
v.	穿(针); 纫(针); 穿过; (使) 穿过; 通过; 穿行; 穿成串; 串在一起;
[例句]This time I'll do it properly with a needle and thread.
这次，我要用针线将它缝好。
[其他]	第三人称单数：threads 复数：threads 现在分词：threading 过去式：threaded

*** fabric
fabric	英[ˈfæbrɪk]
美[ˈfæbrɪk]
n.	织物; 布料; (社会、机构等的) 结构; (建筑物的)结构(如墙、地面、屋顶) ;
[例句]Whatever your colour scheme, there's a fabric to match.
无论什么样的色彩图案，都有与之相配的织物。
[其他]	复数：fabrics

embroidery

*** scissors
scissors	英[ˈsɪzəz]
美[ˈsɪzərz]
n.	剪刀;
v.	剪断; 删除;
[词典]	scissor 的第三人称单数;
[例句]He told me to get some scissors
他让我去拿把剪刀。
[其他]	原型： scissor  复数：scissors

*** a needle
needle	英[ˈniːdl]
美[ˈniːdl]
n.	针; 缝衣针; 编织针; 注射针; 针头;
v.	刺激; 故意招惹; (尤指) 不断地数落;
[例句]She took the needle off the record and turned the lights out.
她把唱针从唱片上移开，把灯也关了。
[其他]	复数：needles

a needle and thread

size 
a big size
a small size
a large-sized coat
a coat my size.
a small-sized coat

*** heel
heel	英[hiːl]
美[hiːl]
n.	足跟; 脚后跟; (袜子等的) 后跟; (鞋、靴子等的) 后跟;
v.	给(鞋等)修理后跟; 倾侧; 倾斜;
[例句]He kicked it shut with the heel of his boot.
他用靴子的后跟将它踢上。
[其他]	第三人称单数：heels 复数：heels 现在分词：heeling 过去式：heeled

** text 
women's shoes with a mid heel
women's shoes with a low heel
women's shoes with a high heel
women's shoes without a heel
women's shoes

In order to embroider, you need a needle and thread.
In order to cut thread, you need scissors.
The girl gets a needle with red thread. She wants to embroider.
The woman is holding a needle with black thread in her right hand, and fabric in
her left. She wants to sew.
In order to sew a coat, you need fabric.
The girl is holding scissors in her right hand, and fabric in her left. She
wants to cut.

The woman is embroidering a red flower on white fabric.
The man doesn't know how to sew. His wife sews pants and a jacket for him.
The grandmother is knitting a grey, warm sweater for her grandson.
The woman knows how to sew. She sews pants and a jacket for her husband.
The boy doesn't know how to sew. He sews a red shirt with green thread.
The granddaughter also knows how to knit. She knits a hat for her bear.

The womman in the long dress with the embroidery is entering the restaurant.
The man puts on warm, white socks.
The boy in the white tank top is sitting on the bench.
The woman takes off light, grey tights.
There is no embroidery on the tank top.
The salesperson is showing the woman a coat.

The man is trying on the blue shirt. It's his size.
The girl is wearing a short, tight, small-sized skirt.
The woman is trying on a red, large-sized dress with  beautiful embroidery.
The woman is giving the salesperson a tight coat - it's not her size.
The girl is trying on a white, thin[fn:1], small-sized blouse without embroidery.
The boy is wearing a loose, large-sized shirt.

Men like women in high heels.
The woman is trying on[fn:2] red high heels.
The man is wearing shoes without a heel.
The girl has shoes with a low heel.
The woman is trying on fall boots with a mid heel.
The woman is trying on winter boots with a low heel.

The woman wants to sew a beautiful dress, but doesn't know how.
The girl wants to walk in high heels, but she doesn't know how.
The woman knows how to knit, but doesn't want to.
The man doesn't know how to knit and doesn't want to.
The boy wants to knit socks, but he doesn't know how.
The boy doesn't know how  to embroider, but really wants to.

Do all girls like to sew? Yes, but not all know how.
Do all men like women in white blouses with embroidery? Yes, all men like such
women.
Does the whole family like the clothing that grandma knits? Yes, the whole
family likes this clothing.
Do all women like a dress with embroidery? No, there are women who don't
like this dress.
Do all men like women in high heels? Yes, all men like such women.
Do all grandmothers like to sew warm socks for their grnadchildren? Yes, they
like it.

* lesson 36
a receipt
change
a market
a supermarket
a counter
a cash register

a purchase
produce
chocolate
cake
souvenirs
perfume

to weigh
to help
to wrap
to pick out 
to carry
to give

dark
light
cheap
expensive
rich
poor

whole 
half 
a whole apple
a whole pie
half of a pie
helf of an apple

a bright room
a dark bar
At the market produce is inexpensive, at the supermarket it's expensive.
The woman is buying produce at the market.
a big, bright supermarket.
The man is buying produce at the supermarket.

The girl is picking out chocolate.
The tall man is helping the woman carry her purchase.
The tourists are picking out souvenirs.
The grandmother is helping her granddaughter wrap a gift for her mother.
The woman is picking out perfume.
The salesperson is helping the customer pick out cake.

The woman is carrying her purchase to the car.
The customers are standing in line for the cash register.
an expensive purchase
The salesperson is carrying produce to the counter.
a cheap purchase
The girl is carrying chocolate to the cash register.

The salesperson is weighing apples.
The customer takes the change and receipt from the salesperson.
The salesperson is wrapping a souvenir.
The woman is wrapping a gift for her husband.
The waiter brings the change and receipt on a tray.
The salesperson gives the customer the receipt and change.

A rich woman buys an expensive dress with embroidery, but a poor woman - a cheep
dress with a discount.
A rich man reserves an expensive room in a hotel, but a poor man - a cheap room.
In the small dark room live poor people.
A rich man gives his wife expensive perfume, but a poor man - cheap perfume.
A rich man drives a new, expensive car, but a poor man - an old, cheap car.
In the big bright house live rich people.

The mother gives her son half a glass of juice.
The boy is cutting a piece of paper in half.
What is the salesperson doing? He's weighing half a chicken.
What is the chef doing? He's frying a whole chicken.
What is the boy doing? He's putting half a cake on a plate.
What is the waiter doing? He's carrying a whole cake on a tray.

* lesson 37
** words
*** north
 north	英[nɔːθ]
 美[nɔːrθ]
 n.	北; 北方; 北部; 北部地区; (美国南北战争时与南方作战的) 北部各州;
 adj.	北方的; 向北的; 北部的; 北风的; 北方吹来的;
 adv.	向北; 朝北;
 [例句]In the north the ground becomes very cold as the winter snow and ice covers the ground
 冬天冰雪覆盖大地，北方的地面变得非常寒冷。
 In the north it's cold.
 In the north half the year it is day, and half it is night.
 Polar bears swim in the sea in the north, becaseu in the north the sea is cold.

*** south
 south	英[saʊθ]
 美[saʊθ]
 n.	南; 南方; 南部; 美国南方各州; 美国南方;
 adj.	南方的; 向南的; 南部的; 南风的; 南方吹来的;
 adv.	向南; 朝南;
 [例句]The town lies ten miles to the south of here
 那个小镇位于这里以南 10 英里处。
 In the south it's hot.
 In the south the grass grows all year.
 In the south it rains half the year.
 People swim in the sea in the south, because in the south the sea is warm.

*** east
 east	英[iːst]
 美[iːst]
 n.	东; 东方; 东部; 东边; 亚洲国家，东方国家(尤指中国、日本和印度);
 adj.	东方的; 向东的; 东部的; 东风的; 东方吹来的;
 adv.	向东; 朝东;
 [例句]The principal range runs east to west.
 主体山脉呈东西走向。
 In the east women wear long, dark dresses.
 The ship is going from the east to the west.
 The river flows from the west to the east.
 Where is the ship going? The ship is going from the west to east.


*** west
 west	英[west]
 美[west]
 n.	西; 西方; 西方(与东方国家相对照的欧洲和北美); 美国西部;
 adj.	西方的; 向西的; 西部的; 西风的; 西方吹来的;
 adv.	向西; 朝西;
 [例句]I pushed on towards Flagstaff, a hundred miles to the west
 我继续西行，向 100 英里外的弗拉格斯塔夫进发。

 In the west women wear tight pants.

*** a compass
 compass	英[ˈkʌmpəs]
 美[ˈkʌmpəs]
 n.	罗盘; 罗经; 指南针; 罗盘仪; 圆规; 两脚规; 范围; 范畴; 界限;
 [例句]We had to rely on a compass and a lot of luck to get here.
 我们不得不依靠指南针和不错的运气找到这儿来。
 [其他]	复数：compasses

 The tourist is finding the path in the mountains by his compass.
 All tourists bring with them a compass when they go into the woods.
 The tourist is holding a compass in his right hand, a map in his left.
 The compass needle points north.
 Where does the compass needle point? 
 The compass needle points north.

*** a needle
 needle	英[ˈniːdl]
 美[ˈniːdl]
 n.	针; 缝衣针; 编织针; 注射针; 针头;
 v.	刺激; 故意招惹; (尤指) 不断地数落;
 [例句]She took the needle off the record and turned the lights out.
 她把唱针从唱片上移开，把灯也关了。
 [其他]	复数：needles
*** day
 day	英[deɪ]
 美[deɪ]
 n.	一天; 一日; 白昼; 白天; 工作日; 一天的活动时间;
 [例句]The weather did not help; hot by day, cold at night
 天气也不肯帮忙：白天很热，晚上很冷。
 [其他]	复数：days

 In the north half the year it is day, and half it is night.
 On work days children and parents get up early.

*** night
 night	英[naɪt]
 美[naɪt]
 n.	夜; 夜晚; 晚上，夜晚(夜里就寝前的一段时间); (举行盛事的) 夜晚; …之夜;
 [例句]He didn't sleep a wink all night
 他一夜没合眼。
 [其他]	复数：nights

 At night the moon and the stars are in the sky.
 In the north half the year it is day, and half it is night.
*** the sun
 sun	英[sʌn]
 美[sʌn]
 n.	太阳; 日; 太阳的光和热; 阳光; 日光; 恒星;
 v.	晒太阳;
 [例句]The sun was now high in the southern sky
 太阳正高挂在南边的天空上。
 [其他]	第三人称单数：suns 复数：suns 现在分词：sunning 过去式：sunned 过去分词：
 sunned
 The sun is a star.

*** the moon
 moon	英[muːn]
 美[muːn]
 n.	月球; 月亮; 月相; 卫星;
 v.	以屁股示人(在公共场所进行的恶作剧或侮辱);
 [例句]There will be no moon.
 月亮不会出来了。
 [其他]	第三人称单数：moons 复数：moons 现在分词：mooning 过去式：mooned 过去分
 词：mooned
 At night the moon and the stars are in the sky.

*** sunset
 sunset	英[ˈsʌnset]
 美[ˈsʌnset]
 n.	日落; 傍晚; 晚霞; (法律的) 自动废止期，效力消减期;
 adj.	霞红色的; 浅橘红色的; 衰落的; 最后期的; 定期废止的;
 v.	(使) 定期届满废止;
 [例句]The dance ends at sunset.
 舞会在日落时分结束。
 [其他]	复数：sunsets
 A man and woman are looking at the beautiful sunset.
 At sunset there are red clouds in the sky.


*** sunrise
 sunrise	英[ˈsʌnraɪz]
 美[ˈsʌnraɪz]
 n.	日出; 朝霞;
 [例句]There was a spectacular sunrise yesterday.
 昨天的朝霞很绚烂。
 [其他]	复数：sunrises
 A man and woman are meeting the sunrise on the beach, because it's very
 beautiful.
 Birds get up at sunrise and sing songs.

*** far
 far	英[fɑː(r)]
 美[fɑːr]
 adv.	远; (问到或谈及距离时说)有多远，远(至) ; 久;
 adj.	较远的; (某方向的) 最远的，远端的; 远的; 远方的; 遥远的;
 [例句]I know a nice little Italian restaurant not far from here
 我知道有家不错的意大利小餐馆离这儿不远。
 [其他]	比较级：farther 最高级：farthest
 The tree is far.
 The ship is far from the coast.
 The children don't swim to the ship, because the ship is very far from the
 coast.

*** near
 near	英[nɪə(r)]
 美[nɪr]
 adj.	距离近; 不远; 不久以后; 随后; 接近;
 adv.	距离不远; 在附近; 不久以后; 几乎; 差不多;
 prep.	在…附近; 靠近; 接近; 临近; (用于数词前) 大约，上下;
 [例句]Don't come near me
 别靠近我。
 [其他]	比较级：nearer 最高级：nearest 第三人称单数：nears 现在分词：nearing 过
 去式：neared
 The bench is near.
 In this hotel there are many tourists, because it's near the sea.
 The rock is near the coast.

*** fast
 fast	英[fɑːst]
 美[fæst]
 adj.	快的; 迅速的; 敏捷的; 迅速发生的; 立即发生的; 动作迅速的; 头脑灵活的;
 adv.	快; 快速; 迅速; 不久; 立即; 牢固地; 完全地;
 v.	节食; 禁食; 斋戒;
 [例句]Brindley was known as a very, very fast driver
 众所周知，布林德利是个喜欢飞车的人。
 [其他]	比较级：faster 最高级：fastest 第三人称单数：fasts 现在分词：fasting 过
 去式：fasted 过去分词：fasted

*** slowly
 slowly	英[ˈsləʊli]
 美[ˈsloʊli]
 adv.	慢速地; 缓慢地; 迟缓地;
 [例句]He slowly sat on the seat with a sigh.
 他叹了一口气，慢慢地坐到位子上。
 [其他]	比较级：more slowly 最高级：most slowly
 The big river flows slowly.
 How do yellow leaves fall from the trees? Yellow leaves fall from trees slowly.
 How does the moon wax? The moon waxes slowly.
*** early
 early	英[ˈɜːli]
 美[ˈɜːrli]
 adj.	早期的; 初期的; 早先的; 早到的; 提前的; 提早的;
 adv.	在早期; 在初期; 在开始阶段; 提早; 提前; 先前; 早些时候; …之前;
 [例句]I knew I had to get up early
 我知道我得早起。
 [其他]	比较级：earlier 最高级：earliest
 No one likes to get up early.
 On work days children and parents get up early.

*** late
 late	英[leɪt]
 美[leɪt]
 adj.	接近末期; 在晚年; 迟到; 迟发生; 迟做; 近日暮的; 近深夜的;
 adv.	迟; 晚; 接近末期; 在晚年; 临近日暮; 接近午夜;
 [例句]It was late in the afternoon
 那是下午近黄昏的时候。
 [其他]	比较级：later 最高级：latest
 On weekends everyone gets up late.

 On weekends everyone gets up late.(adv.)

*** to fall
 fall	英[fɔːl]
 美[fɔːl]
 v.	落下; 下落; 掉落; 跌落; 突然倒下; 跌倒; 倒塌; 下垂; 低垂;
 n.	落下; 下落; 跌落; 掉落; (雪、岩石等的) 降落; 发生; 秋天（AmE=autumn）;
 [例句]Totally exhausted, he tore his clothes off and fell into bed
 他疲惫至极，扯下衣服，一头倒在床上。
 [其他]	第三人称单数：falls 现在分词：falling 过去式：fell 过去分词：fallen
 The girl falls and gets up.
 The glass falls on the floor.
 Yellow leaves fall from the trees.
 In the fall how do yellow leaves fall from trees? Yellow leaves fall from trees
 slowly.
 The girl falls on the sand.
 The stars sometimes fall on the earth.
 The moon doesn't fall on the earth.

*** to rise
 rise	英[raɪz]
 美[raɪz]
 n.	(数量或水平的) 增加，提高; 加薪; 工资增长; (重要性、优势、权力等的) 增强;
 v.	上升; 攀升; 提高; 达到较高水平(或位置); 起床; 起立; 站起来; 升起;
 [例句]He watched the smoke rise from his cigarette
 他注视着烟雾从香烟上升起。
 [其他]	第三人称单数：rises 现在分词：rising 过去式：rose 过去分词：risen

*** to flow

 flow	英[fləʊ]
 美[floʊ]
 n.	流; 流动; 持续生产; 不断供应; 滔滔不绝;
 v.	流; 流动; 涌流; 流畅;
 [例句]A stream flowed gently down into the valley
 一条小溪潺潺流进山谷。
 [其他]	第三人称单数：flows 现在分词：flowing 过去式：flowed 过去分词：flowed

 The small river flows fast.
 The big river flows slowly.
 Water flows.
 The river flows from the west to the east.

*** to float

 loat	英[fləʊt]
 美[floʊt]
 v.	浮动; 漂流; 飘动; 飘移; 浮; 漂浮; 使浮动; 使漂流;
 n.	彩车; 鱼漂; 浮子; (学游泳用的) 浮板;
 [例句]Empty things float.
 空的物体会在水中浮起。
 [其他]	第三人称单数：floats 复数：floats 现在分词：floating 过去式：floated 过
 去分词：floated

*** to swim

 swim	英[swɪm]
 美[swɪm]
 v.	游水; 游泳; 游泳(作为娱乐); 游; 游动;
 n.	游泳;
 [例句]She swam the 400 metres medley ten seconds slower than she did in 1980.
 她 400 米混合泳的成绩比其 1980 年慢了 10 秒。
 [其他]	第三人称单数：swims 现在分词：swimming 过去式：swam 过去分词：swum

 The children don't swim to the ship, because the ship is very far from the
 coast.
 People swim in the sea in the south, because in the south the sea is warm.
 Polar bears swim in the sea in the north, because in the north the sea is cold.

*** to grow

 grow	英[ɡrəʊ]
 美[ɡroʊ]
 v.	扩大; 增加; 增强; 长大; 长高; 发育; 成长; (使) 生长;
 [例句]We stop growing at maturity.
 我们成年之后不再长个儿。
 [其他]	第三人称单数：grows 现在分词：growing 过去式：grew 过去分词：grown

 How do mushrooms in the forest grow after rain? Mushrooms in the forest grow
 fast after rain.
 In the south the grass grows all year.
 On the riverbank grows a tall tree.

*** the sky 

 sky	英[skaɪ]
 美[skaɪ]
 n.	天; 天空;
 v.	把(球)击向高空;
 [例句]The sun is already high in the sky.
 已经日上三竿。
 [其他]	第三人称单数：skies 复数：skies 现在分词：skying 过去式：skied 过去分词：
 skied

 There are red clouds in the sky.
 At night the moon and the stars are in the sky.
 A woman is standing on the beach and looking at the blue sky and the white clouds.
 At sunset there are red clouds in the sky.
 After rain there is a rainbow in the sky.

*** stars

 star	英[stɑː(r)]
 美[stɑːr]
 n.	恒星; 星; 星状物; 星形饰物; 星号; (尤指旅馆或餐馆的) 星级;
 v.	主演; 担任主角; 使主演; 由…担任主角; (在文字等旁) 标星号;
 [例句]The night was dark, the stars hidden behind cloud.
 夜很黑，星星都躲在云的后面。
 [其他]	第三人称单数：stars 复数：stars 现在分词：starring 过去式：starred 过去
 分词：starred

 Stars sometimes fall on the earth.
 At night the moon and the stars are in the sky.

*** a rainbow

 rainbow	英[ˈreɪnbəʊ]
 美[ˈreɪnboʊ]
 n.	虹; 彩虹;
 [例句]Oh look, a rainbow!
 看哪，彩虹！
 [其他]	

 After rain there is a rainbow in the sky.

*** a cloud

 cloud	英[klaʊd]
 美[klaʊd]
 n.	云; 云朵; 云状物(如尘雾、烟雾、一群飞行的昆虫); 阴影; 忧郁; 焦虑; 令人忧虑的事;
 v.	使难以理解; 使记不清楚; 使模糊; 显得阴沉(或恐惧、愤怒等); 看起来忧愁(或害怕、愤怒等); (尤指用无关的话题来)混淆，搅混(问题) ;
 [例句]The sky was almost entirely obscured by cloud.
 天空几乎完全被云所遮蔽。
 [其他]	第三人称单数：clouds 复数：clouds 现在分词：clouding 过去式：clouded 过
 去分词：clouded

 At sunset there are red clouds in the sky.
 The woman is standing on the beach and looking at the blue sky and the white
 clouds.

*** a river

 river	英[ˈrɪvə(r)]
 美[ˈrɪvər]
 n.	河; 江; (液体) 涌流;
 [例句]The Chicago River flooded the city's underground tunnel system
 芝加哥河的河水淹没了城市的地下隧道系统。
 [其他]	复数：rivers

 The small river flows fast.
 The big river flows slowly.
 The river flows from the west to the east.
 If a deer is thirsty, it goes to the river.

*** a coast

 coast	英[kəʊst]
 美[koʊst]
 n.	海岸; 海滨;
 v.	(尤指不用动力向山坡下) 滑行，惯性滑行; (不用多少动力) 快速平稳地移动; 不费力地取得成功;
 [例句]Camp sites are usually situated along the coast, close to beaches.
 野营地一般都位于海滨，靠近沙滩。
 [其他]	第三人称单数：coasts 复数：coasts 现在分词：coasting 过去式：coasted 过
 去分词：coasted

 The rock is near the coast.
 The ship is very far from the coast.
 The children don't swim to the ship, because the ship is very far from the
 coast.


 In the north it's cold.
 In the south it's hot.
 In the north there is snow all year.
 In the west women wear tight pants.
 In the south the grass grows all year.
 In the east women wear long, dark dresses.

 The sun is a star.
 At sunset there are red clouds in the sky.
 A man and woman are looking at the beautiful sunset.
 Clouds are covering the sun.
 After rain there is a rainbow in the sky.
 At night the moon and the stars are in the sky.

 The tree is far.
 The rock is near the coast.
 The bench is near.
 In this hotel there are many tourists, because it's near the sea.
 The children don't swim to the ship, because the ship is very far from the
 coast.
 The ship is far from the coast.

 a beach
 A boy is playing in the sand on the beach.
 A woman is standing on the beach and looking at the blue sky and the white clouds.
 On the riverbank grows a tall tree.
 The girl is walking along the beach.
 A man and woman are meeting the sunrise on the beach, because it's very beautiful.

 The woman gets up and goes to take a shower.
 The boy gets up and goes to wash up. 
 On work days children and parents get up early.
 On weekends everyone gets up late.
 No one likes to get up early.
 Birds get up at sunrise and sing songs.

 The moon doesn't fall on the earth.
 The girl falls and gets up.
 Stars sometimes fall on the earth.
 In the fall yellow leaves fall from trees.
 The glass falls on the floor.
 The girl falls on the sand.

 Water flows.
 The big river flows slowly.
 People swim in the sea in the south, because in the south the sea is warm.
 The small river flows fast.
 Polar bears swim in the sea in the north, because in the north the sea is cold.
 The river flows from the west to the east.

 The compass needle points north.
 The tourist is holding a compass needle in his right hand, and a map in his left.
 In the south it rains half the year.
 In the north half the year it is day, and half it is night.
 The tourist is finding the path in the mountains by his compass.
 All tourists bring with them a compass when they go into the woods.

 How do mushrooms in the forest grow after rain? Mushrooms in the forest grow
 fast after rain.
 Where does the compass needle point? The compass needle points north.
 How do yellow leaves fall from trees? Yellow leaves fall from trees slowly.
 How does the moon wax? The moon waxes slowly.
 Where is the ship going? The ship is going from the west to the east.
 Where is the boy looking? He's looking at the stars.

** programmer

*** 提问如何、地点、等 
 How do yellow leaves fall from trees?
 Yellow leaves fall from trees slowly.

 How does the moon wax?
 The moon waxes slowly.

 Where is the ship going? 
 The ship is going from the east to the west.

 Where is the boy looking?
 He's looking at the stars.

 How do mushrooms in the forest grow after rain?
 Mushrooms in the forest grow fast after rain.

*** 时间

**** 星期、日 用 on
On work days children and parents get up early.
On weekends everyone gets up late.
Can you come at 10 a.m. on Monday, April, 24th?

**** at night
At night the moon and the stars are in the sky.
He telephoned again at night.
在某个时间点：at sunrise at sunset
At sunrise there are red cluds in the sky.
Birds get up at sunrise and sing songs.
A man and woman are meeting the sunrise on the beach, because it's very
beautiful.
At mid night

**** in 在某个时段

***** in the morning

***** in the afternoon

***** in the evening
Then I arrived home at six o'clock yesterday evening.

*** on the beach 
A woman is standing on the beach and looking at the blue sky and the white
clouds.

*** in the sand
A boy is playing in the sand on the beach.

*** on the riverbank
On the riverbank grows a tall tree.

*** look at 
He's looking at the stars.
What is the boy looking?

*** 在。。。里，在。。。季节 in 
in the north in the south 
in the sea
in the forest
How do mushrooms in the forest grow after rain?
Mushrooms in the forest grow fast after rain.
The tourist is finding the path in the mountains by his compass.
In the winter a rabbit is white. It's inviable in the snow. It doesn't hide.
In the fall yellow leaves fall from trees.

*** 代词 it。。。如天气等
In the south it's hot.
In the north it's cold.
In the north half the year it is day, and half it is night.
In the south it rains half the year.


* lesson 38
** words
*** a violin
 The musicians are playing old-fashioned music on violins.
 The man is playing music on violin,  and the girl is listening to the music.
 These musicians are playing modern music on a violin and a guitar.
 The young man is playing the violin, and the young woman is listening to the
 music.
 The girl loves music. She plays the violin.
 Are the musicians playing violins or drums? The musicians are playing violins.
*** a guitar
 The musicians are playing modern music on a violin and a guitar.
*** dance
 The girl loves dancing. she loves to dance.
 What do the friends love to do? They love to dance.
*** music
 The musicians are playing modern music on a violin and a guitar.
 These musicians are playing old-fashioned music on violins.
 The young man is playing the violin, and the young woman is listening to the
 music.
 She loves music. She plays the violin.
 During a carnival music plays.
 The woman is washing dirty dishes and listening to the music.
*** film
 These children are friends. They're watching an interesting film about
 old-fashioned clothes on TV.
 Are the friends watching a film or leaving the city? The friends are watching a
 film.
*** a drum
 The boys play the drums.
 The musician also plays the drums.
 Are the musicians playing the violins or drums? The musicians are playing the
 violins.
*** a bouquet
 The bride with the bouquet of white flowers is dancing on the grass.
 At a wedding the bride throws her bouquet of flowers to her friends.
 The bride throws her bouquet, and her friends catch it.
 The bride holds the bouquet of white flowers.
 Does the bride catch or throw the bouquet? The bride throws her
 bouquet.
 Is the woman holding a bouquet of flowers or a wig? The woman is holding a
 bouquet of flowers.
*** candy
 The boy gives the girl candy.
 The boy is happy because his mom gave him candy.
 When are children happy? Children are happy when they're given candy and toys.
 The girl is crying because she has no candy.
*** a mask
 The woman collects masks.
 When do actors wear masks? They wear masks during a spectacle.
*** a carnival costume
 The friends are putting on carnival costumes.
 The man in the carnival costume gives the woman in the old-fashioned dress and
 wig a bouquet of flowers.
*** a wig
 The actors are dressed in old-fashioned dresses and wigs.
 The actor puts on a wig.
 During a carnival people put on old-fashioned dresses and wigs.
 The woman is wearing a wig.
 When do men put on wigs? They put on wigs at a carnival.
*** a carnival
 When do men put on wigs? They put on wigs at a carnival.
 During a carnival people put on old-fashioned dresses and wigs.
 During a carnival music plays.
 In the city is there a carnival or traffic? In the city there is a carnival.
*** to throw
 At a wedding the bride throws her bouquet to her friends.
 The girl throws the ball, and the boy catches the ball.
 The bride throws her bouquet, and her friends catch it.
 Does the bride catch or throws her bouquet? The bride throws her bouquet.
*** to collect
 The man collects phones.
 The woman collects masks.
 The young man collects old-fashioned watches.
 The man collects paintings.
 What does the man collect? He collects paintings.
*** to leave the city
 The family leave the city to relax in nature.
 The friends leave the city to fry meat and drink beer.
*** to celebrate
 The girl invites her classmates to her birthday party.
 The friends are celebrating a holiday.
*** to catch
 The girl throws the ball, and the boy catches the ball.
 Does the bride catch or throw the bouquet? The bride throws the bouquet.
 The bride throws her bouquet, and her friends catch it.
*** to love to do something
 What do the friends love to do? They love to dance.
 The girl loves dancing. She loves to dance.
 The boy loves photography. He loves to photograph his friends.
*** modern
 Is this a modern or an old-fashioned building. This is a modern building.
 The man is in a modern suit, and the woman is in an old-fashioned dress.
 These musicians are playing modern music on a violin and a guitar.

 an old-fashioned cabinet
 a modern clock
 old-fashioned
 a modern cabinet
 an old-fashioned clock

 These girls are peers.
*** a peer 
 These girls are peers. They study in the same grade at the university.
*** a classmate
 These boys are classmates. They study in the same class at school.
 The girl invites her classmates to her birthday party.
 a girlfriend
 These boys are classmates.
 a friend

 These boys are classmates. They study in the same class at school.
 The girl invites her classmates to her birthday party.
 In the store the friends are picking out clothing.
 These children are friends. They're watching an interesting film about
 old-fashioned clothes on TV.
 The friends are celebrating  a holiday.
 These girls are peers. They study in the same grade at the university.

 The friends are putting on carnival costumes.
 The musicians are playing old-fashioned music on violins.
 During a carnival music plays.
 The musician also plays the drums.
 These musicians are playing modern music on a violin and a guitar.
 The boys play the drums.

 The actors are dressed in old-fashioned dresses and wigs.
 The woman with the bouquet of white flowers is dancing on the grass.
 The actor puts on a wig.
 A man and woman are dancing in old-fashioned costumes.
 During a carnival people put on old-fashioned dresses and wigs.
 The woman is wearing a wig.

 The boy gives the girl candy.
 The boy is happy because his mom gave him candy.
 The young man is playing the violin, and the young woman is listening to the
 music.
 The friends leave the city to fry meat and drink beer.
 The girl is crying because she has no candy.
 The family leaves the city to relax in nature.

 At a wedding the bride throws her bouquet to her friends.
 The man in the carnival costume gives the woman in the old-fashioned dress and wig
 a bouquet of flowers.
 The girl throws the ball, and the boy catches the ball.
 The man is in a modern suit, and the woman is in an old-fashioned dress.
 The bride holds a bouquet of white flowers.
 The bride throws her bouquet, and her friends catch it.

 The boy loves photography. He loves to photograph his friends.
 The young man collects old-fashioned watches.
 The girl loves music. She plays the violin.
 The girl loves dancing. She loves to dance.
 The man collects phones.
 The woman collects masks.

 In the city is there a carnival or traffic? In the city there is a carnival.
 Is this a modern or an old-fashioned building. This is a modern building.
 Does the bride catch or throw the bouquet? The bride throws the bouquet.
 Is the woman holding a bouquet of flowers or a wig? The woman is holding a
 bouquet of flowers.
 Are the musicians playing violins or drums? The musicians are playing violins.
 Are the friends watching a film or leaving the city? The friends are watching a
 film.

 When do men put on wigs? They put on wigs at a carnival.
 What do the friends love to do? They love to dance.
 When are children happy? Children are happy when they're given candy and toys.
 When do actors wear masks? They wear masks during a spectacle.
 Where are the friends going? They're leaving the city.
 What does the man collect? He collects paintings.
*** 着衣的表达
**** wear
 When do actors wear masks? They wear masks during a spectacle.
 The woman is wearing a wig.
**** be dressed in 被动式 
 The actors are dressed in old-fashioned dresses and wigs.
**** is in 
 The man is in a modern suit, and the woman is in an old-fashioned dress.
**** put on
 The actor puts on a wig.
 The friends are putting on carnival costumes.
 When do men put on wigs? They put on wigs at a carnival.

*** 衣服
**** dress 裙子
 During a carnival people put on old-fashioned dresses and wigs.
**** suit 西装
 The man is in a modern suit, and the woman is in an old-fashioned dress.
**** costume 服装
 a carnival costumes 
 The man in the carnival costume gives the woman in the old-fashioned dress and
 wig a bouquet of flowers.

**** clothes 衣服
 In order to wash clothes, you need laundry detergent and a washing machine.
 The woman is washing clothes in the washing machine.
 The bathroom is in disorder - the laundry detergent, soap and clothes are lying
 on the floor.
 Is the woman washing clothes with her hands? No, she is washing them in the
 washing machine.
 Is the woman washing clothes? No, she's cleaning up the kitchen.


**** clothing 衣物
 In the store the friends are picking out clothing.
 The woman washes her clothing with her hands. She doesn't have a washing
 machine.

**** skirt

**** shirt

**** coat

**** pants

**** blouse

**** gown

**** 

* lesson 39
** words
*** a bull
 a black bull on green grass
 The cows and bull are crossing the street. They're looking for grass.
*** a ram
 A sheep and a ram give fur.
 What gives fur? A sheep and a ram give fur.
 Sheep and rams give fur.
*** a chicken
 The chicken is walking by the house. It's looking for food.
 Chickens lay eggs.
 What lays eggs? Chickens lay eggs.

*** a sheep
 In the country graze cows and sheep, but there are no leopards or wolves.
 A sheep is a herbivorous animal. It eats grass.
*** a cow
 The cows and bull are crossing the street. They're looking for grass.
 Cows give milk.
 A cow is a spotted and herbivorous animal. It eats grass.
 A cow also is a herbivorous animal.
 a spotted cow
 In the country graze cows and sheep, but there are no leopards or wolves.
*** a rooster
 What sings at dawn? A rooster sings at dawn.
*** a rabbit
 a grey rabbit on yellow sand
 The grey rabbit is hiding behind a tree.
 In the winter a rabbit is white. It's invisible in the snow. It doesn't hide.
 What hunts rabbits? Hungry wolves hunt rabbits.
 The hungry wolf is looking around. He's looking for a rabbit.
*** a wolf
 A wolf is a carnivorous animal. It eats meat.
 The wolf is hunting a deer.
 What hunts rabbits? Hungry wolves hunt rabbits.
*** a deer
 a spotted deer
 If a deer is thirsty, it goes to the river.
 A deer is a spotted and herbivorous animal.
 The hungry wolf is hunting a deer.
 The deer is grazing in the forest.
 The hungry tiger is hunting a deer.
 The spotted leopard chases a yellow deer. It's hunting.
 What is spotted and herbivorous? A deer is spotted and herbivorous.
*** a lion
 If lions sleep, they're not hungry.
 The full lion is lying under a tree.
 The small, full lion is jumping on the tree. He's playing.
 The lion is lying under a tree and eating meat.

*** a tiger
 a striped tiger
 The hungry tiger is hunting a deer.
 What is striped and carnivorous? A tiger is striped and carnivorous.

*** a leopard
 a spotted leopard
 The spotted leopard chases a yellow deer. It's hunting.
 A leopard is spotted. It's invisible among the trees.
 If a leopard is hungry, it hunts.
 A leopard is a carnivorous animal.
 In the country graze cows and sheep, but there are no leopards or wolves.

*** to graze

 The spotted deer is grazing in the forest.
 In the country graze cows and sheep, but there are no leopards or wolves.

** text

to hunt
to give milk
to lay eggs
to give fur
to hide

hungry
full
carnivorous
herbivorous
spotted
striped

a striped tiger
a grey rabbit on yellow sand
a black bull on green grass
The spotted leopard chases a yellow deer. It's hunting.
a spotted leopard
a spotted cow

The sheep is standing by the house and eating grass.
The wolf is hunting a deer.
The deer is grazing in the forest.
A wolf is a carnivorous animal. It eats meat.
The lion is lying under a tree and eating meat.
A leopard also is a carnivorous animal.

A cow also is a herbivorous animal.
Cows give milk.
Sheep and rams give fur.
A sheep is a herbivorous animal. It eats grass.
Chickens lay eggs.
The hungry tiger is hunting a deer.

The cows and bull are crossing the street. They're looking for grass.
The rabbit is hiding behind a tree.
The chicken is walking by the house. It's looking for food.
The small, full lion is jumping on the tree. He's playing.
The full lion is sleeping under a tree.
The hungry wolf is looking around. He's looking for a rabbit.

A leopard is spotted. It's invisible among the trees.
If a deer is thirsty, it goes to the river.
If a leopard is hungry, it hunts.
In the country graze cows and sheep, but there are no leopards or  wolves.
In the winter a rabbit is white. It's invisible in the snow. It doesn't hide.
If lions sleep, they're not hungry.

What lays eggs? Chickens lay eggs.
What sings at dawn? A rooster sings at dawn.
What hunts rabbits? Hungry wolves hunt rabbits.
What is spotted and herbivorous? A deer is spotted and herbivorous.
What gives fur? A sheep and a ram give fur.
What is striped and carnivorous? A tiger is striped and carnivorous.

* lesson 40
** words
*** laundry detergent
 The laundry detergent is standing on the washing machine.
 In order to wash clothes, you need laundry detergent and a washing machine.
 The bathroom is in disorder - the laundry detergent, soap and clothes are lying
 on the floor.
 The bathroom is in order - the laundry detergent and soap are lying on the
 shelf, and the towel is hanging.

*** detergent
 In order to wash the stove, you need detergent.

*** a bucket
 In order to wash the floor, you need a mop and a bucket.
 The girl is holding  a bucket with water and  cloth. She wants to wash the
 floor.
 A wet cloth is lying on the bucket.

 a cloth

 a washing machine
 a mop
 an iron
 an ironing board
 a vacuum cleaner
 a dishwasher
 a rug
 a brush
 a soap
 order
 disorder

*** to vacuum

 The boy is vacuuming the rug and smiling.
 In order to vacuum the rug, you need a vacuum cleaner.


 to wipe off
 to clean
*** to clean up
 The boy isn't washing the floor. He's cleaning up the shelf.
 The man is cleaning up the table.
 What are the children doing? The children are helping their mom clean up the
 room.

*** to iron 

 The father is ironing a shirt and talking on the phone.
 The woman is ironing a beautiful dress and thinking about a party.
 In order to iron pants, you need an iron and an ironing board.

** text

The table is in order.
The table is in disorder.
The room is in order.
The room is in disorder.

A wet cloth is lying on the bucket.
A dry cloth is lying on the floor.
The vacuum cleaner is standing on the rug.
The soap is lying on the shelf under the mirror in the bathroom.
The girl is holding a bucket with water and a cloth. She wants to wash the floor
in the room.
The laundry detergent is standing on the washing machine.

The man is turning on the washing machine.
Grandma washes dishes with her hands. She doesn't have a dishwasher.
The woman washes her clothing with her hands. She doesn't have a washing machine.
The woman is washing the big, dirty window. No one is helping her.
The man is washing his things in the washing machine.
The boy is washing the floor with a mop and a cloth. He's helping his mom.

The kitchen is in order.
The room is in disorder.
The woman isn't washing clothes. She's cleaning up the kitchen.
The man is cleaning up the table.
The boy isn't washing the floor. He's cleaning up the shelf.
The girl is cleaning up the room.

The room is in order - the books are standing on the shelf and the clothes are
lying in the cabinet.
The kitchen is in disorder - dirty dishes are on the table, and the tablecloth
is lying on the floor.
The room is in disorder - books, clothes and toys are lying on the floor.
The bathroom is in disorder - the laundry detergent, soap and towel are lying on
the floor.
The bathroom is in order - the laundry detergent and soap are lying on the
shelf, and the towel is hanging.
The kitchen is in order - clean dishes are standing in the cabinet.

In order to wash the stove, you need detergent.
In order to clean shoes, you need a shoe brush.
In order to wash clothes, you need laundry detergent and a washing machine.
In order to iron pants, you need an iron and an ironing board.
In order to vacuum the rug, you need a vacuum cleaner.
In order to wash the floor, you need a mop and bucket.

The mother is washing the window, and her daughter is washing the floor.
The father is ironing a shirt and talking on the phone.
The boy is vacuuming the rug and smiling.
The woman is ironing a beautiful dress and thinking about a party.
The mother is washing glasses, and her daughter is drying them.
The woman is washing dirty dishes and listening to happy music.

Is the grandmother washing dishes with her hands? Yes, she doesn't have a
dishwasher.
With what is the man cleaning his shoes? He's cleaning them with a shoe brush.
What are the children doing? The children are helping their mom clean up in the
room.
With what is the girl drying the plate? She's drying the plate with a clean
white towel.
With what is the woman washing the floor? She's washing the floor with a mop and
a wet rag.
Is the woman washing clothes with her hands? No, she is washing them in the
washing machine.

* Footnotes

[fn:2]试穿(衣服等);试戴;试用: May I try on the hat? 

[fn:1]thin	英[θɪn]
美[θɪn]
adj.	薄的; 细的; 瘦的; 稀少的; 稀疏的;
adv.	薄薄地;
v.	(掺水等) 使稀薄，使变淡; 变稀疏; 变稀少; (使) 变稀薄，变少;
[例句]A thin cable carries the signal to a computer
一根细电缆将信号传送给一台计算机。
[其他]	比较级：thinner 最高级：thinnest 第三人称单数：thins 现在分词：thinning 过去式：thinned 过去分词：thinned 
