
#+TITLE: 英语学习笔记
#+AUTHOR: 泰山职业技术学院   夏乐斋
#+OPTIONS: H:3
#+OPTIONS: toc:2 (目录中只显示二级标题)
* Don't drop it!
** Text
What are you going to do with that vase, Penny?
I'm going to put it on this table, Sam.
Don't do that.
Give it to me.
What are you going to do with it?
I'm going to put it here.
in front of the window.
Be careful!
Don't drop it!
Don't put there, Sam.
Put it here.
on this shelf.
There we are!
It's a lovely vase.
Those flowers are lovely, too.
** Words
*** vase 
vase	英[vɑːz]
美[veɪs]
n.	花瓶; 装饰瓶;
[例句]You will catch it for breaking that vase.
你打破了那花瓶要挨骂了。
[其他]	复数：vases
*** drop
drop	英[drɒp]
美[drɑːp]
v.	(意外地) 落下，掉下，使落下; (故意) 降下，使降落; 累倒; 累垮;
n.	滴; 水珠; 少量; 微量; 一点点; 下降; 下跌; 减少;
[例句]Temperatures can drop to freezing at night
夜间温度可能会降到零度以下。
[其他]	第三人称单数：drops 现在分词：dropping 过去式：dropped 过去分词：dropped
*** Be careful!
小心
*** shelf 
shelf	英[ʃelf]
美[ʃelf]
n.	(固定在墙上的或橱柜、书架等的) 架子，搁板; (悬崖上或海底) 突出的岩石; 陆架; 陆棚;
[例句]He took a book from the shelf.
他从书架上拿了一本书。
[其他]	复数：shelves
*** lovely

lovely	英[ˈlʌvli]
美[ˈlʌvli]
adj.	美丽的; 优美的; 有吸引力的; 迷人的; 令人愉快的; 极好的; 亲切友好的; 慷慨大方的; 可爱的;
n.	美女; 美人; 佳人;
[例句]You look lovely, Marcia
你看上去真漂亮，马西娅。
[其他]	比较级：lovelier 最高级：loveliest
*** There we are!
好了。需上下文联系理解
** Test
*** First
What are you going to do with that vase, Penny?
I'm going to put it on this table, Sam.
Don't do that.
Give it to me.
What are you going to do with it?
I'm going to put it here.
In front of the window.
Be careful!
Don't drop it!
Don't put there, Sam.
Put it here.
On this shelf.
There we are!
It's a lovely vase.
Those flowers are lovely, too.
*** Second
What are you going to do with that vase, Penny?
I'm going to put it on this table, Sam.
Don't do that.
Give it to me.
What are you going to do with it?
I'm going to put it here.
In front of the window.
Be careful!
Don't drop it!
Don't put there, Sam.
Put it here,
On this shelf!
There we are!
It's a lovely vase.
Those flowers are lovely, too.
*** Third
What are you going to do with that vase, Penny?
I'm going to put it on this table, Sam.
Don't do that.
Give it to me.
What are you going to do with it?
I'm going to put it here,
in front of the window.
Be careful!
Don't drop it!
Don''t put there, Sam.
Put it here, 
on this shelf.
There we are!
It's a lovely vase.
Those flowers are lovely, too.
*** Forth
What are you going to do with that vase, Penny?
I'm going to put it on this table, Sam.
Don't do that.
Give it to me.
What are you going to do with it?
I'm going to put it here,
in front of the window.
Be careful!
Don't drop it.
Don't put it there, Sam.
Put it here,
on this shelf.
There we are!
It's a lovely vase.
Those flowers are lovely, too.
* Penny's bag
** text
Is that bag heavy, Penny?
Not very.
Here!
Put it on this chair.
What's in it?
A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of Chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
Is that tin of tobacco for me?
Well, it's certainly not for me!
** Words
*** cheese
cheese | BrE tʃiːz, AmE tʃiz | noun countable and uncountable 奶酪 nǎilào
  ▸ hard cheese! British informal 真不走运！
  ▸ say cheese 说“茄子”
  ▸ a big cheese informal 要人 PHRASAL VERB cheese off transitive verb [cheese sb off, cheese off sb] informal 使感到厌烦 shǐ gǎndào yànfán
  ▸ to be cheesed off with … 对…感到厌烦
*** bread 
bread | BrE brɛd, AmE brɛd | noun uncountable
 ① Cooking 面包 miànbāo
  ▸ to be on bread and water 吃粗茶淡饭
  ▸ to know which side one's bread is buttered informal 知道自己的利益所在
  ▸ to break bread (with sb) dated （与某人）共餐
  ▸ to cast one's bread upon the waters figurative 真心行善不图报
  ▸ bread and wine Religion 圣餐
 ② informal (money) 钱 qián
 ③ (livelihood) 生计 shēngjì
  ▸ to earn one's (daily) bread 谋生
  ▸ to take the bread out of sb's mouth 砸某人的饭碗
  ▸ to put bread on the table 挣钱糊
*** soap 
soap | BrE səʊp, AmE soʊp |
 A. noun
 ① countable and uncountable (for washing) 肥皂 féizào
 ② countable informal = soap operaB. transitive verb 用肥皂洗 yòng féizào xǐ
*** chocolate 
chocolate | BrE ˈtʃɒk(ə)lət, AmE ˈtʃɑk(ə)lət | noun
 ① uncountable (substance) 巧克力 qiǎokèlì
  ▸ a bar of chocolate 一块巧克力
  ▸ chocolate biscuits/cake/ice cream 巧克力饼干/蛋糕/冰激凌
 ② countable (sweet) 巧克力糖 qiǎokèlì táng
 ③ uncountable (drink) 巧克力饮料 qiǎokèlì yǐnliào
 ④ uncountable (colour) 巧克力色 qiǎokèlìsè
*** milk 
milk | BrE mɪlk, AmE mɪlk |
 A. noun
 ① uncountable (general) 奶 nǎi
  ▸ a glass of milk 一杯牛奶
  ▸ to produce milk 泌乳
  ▸ to be in milk «animal» 在授乳期
  ▸ a land flowing with milk and honey 富饶之地
  ▸ the milk of human kindness 人的善良天性
  ▸ to be like milk and water 平淡无味
  ▸ it's no use or good crying over spilt milk proverb 覆水难收，后悔也无济于事
 ② uncountable Botany 白色汁液 báisè zhīyè
  ▸ the milk of a coconut 椰汁
 ③ uncountable and countable (cosmetic) 乳剂 rǔjì
 B. transitive verb
 ① Farming 挤…的奶 jǐ… de nǎi ‹cow›
 ② (extract) 抽取 chōuqǔ ‹sap, venom›
 ③ figurative (draw on) 消耗 xiāohào ‹resources›
  ▸ to milk the fund 动用资金
 ④ figurative (exploit) 榨取 zhàqǔ ‹money›; 套取 tàoqǔ ‹ideas›
  ▸ to milk sth/sb of sth, to milk sth from or out of sth/sb; 从某事物/某人处榨取某物
  ▸ to milk sth/sb dry 榨干某物/某人
  ▸ to milk the situation 趁机牟利自肥
  ▸ to milk sb's strength/enthusiasm 利用某人的体力/热情
  ▸ to milk the audience for applause 卖力地想博得观众的掌声
*** sugar 
sugar | BrE ˈʃʊɡə, AmE ˈʃʊɡər |
 A. noun
 ① uncountable (unrefined) [植物所含的] 糖 táng
  ▸ to refine sugar 炼糖
 ② uncountable and countable (refined) 食糖 shítáng
  ▸ brown/white sugar 红糖/白糖
  ▸ how many sugars do you take? 你要加多少糖？
  ▸ a sugar spoon 糖勺
 ③ (mainly US) informal (term of endearment) 亲爱的 qīn'ài de
  ▸ bye, sugar! 再见，宝贝儿！
 B. exclamation euphemistic informal 完了 wánle [表示恼怒]
  ▸ sugar! I've forgotten my wallet! 糟了！我忘带钱包了！
 C. transitive verb 在…中加糖 zài… zhōng jiā táng
  ▸ sugared almonds 糖衣杏仁
*** tobacco
tobacco | BrE təˈbakəʊ, AmE təˈbækoʊ | noun uncountable
 ① (product) 烟草 yāncǎo
  ▸ a tin of tobacco 一听烟丝
  ▸ a tobacco tin 烟草罐
 ② (plant) 烟草植株 yāncǎo zhízhū
  ▸ a tobacco leaf/plant 烟叶/烟草植株 
** Test
*** First
Is that bag heavy, Penny?
Not very.
Here!
Put it on this chair.
What's in it?
A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
Is that tin of tobacco for me?
Well, it's certainly not for me!
*** Second
Is that bag heavy, Penny?
Not very.
Here!
Put it on this chair.
What's in it?
A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
Is that tin of tobacco for me?
Well, it's certainly not for me.
*** Third
Is that bag heavy, Penny?
Not very.
Here!
Put is on this chair.
What's in it?
A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
Is that tin of tobacco for me?
Well, it's certainly not for me!
*** Forth
Is that bag heary, Penny?
Not very.
Here!
Put it on this chair.
What's in it?
A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
Is that tin of tobacco for me?
Well, it's certainly not for me!
*** Fifth
Is that bag heavy, Penny?
Not very.
Here!
Put it on this chair.
What's in it?
A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
Is that tin of tobacco for me?
Well, it's certainly not for me!
* Hurry up!
** Text
 Can you make the tea, Sam?
 Yes, of course I can, Penny.
 Is there any water in this kettle?
 Yes, there is.
 Where's the tea?
 It's over there, behind the teapot.
 Can you see it?
 I can see the teapot,
 but I can't see the tea.
 There it is!
 It's in front of you!
 Ah, yes, I can see it now.
 Where are the cups?
 There are some in the cupboard.
 Can you find them?
 Yes. Here they are.
 Hurry up, Sam!
 The kettle's boiling!
** Words
*** tea

tea	英[tiː]
美[tiː]
n.	茶叶; 茶; 茶水; 一杯茶;
[例句]America imports about 190 million pounds of tea a year
美国每年进口大约 1.9 亿磅茶叶。
[其他]	复数：teas
*** kettle
kettle	英[ˈketl]
美[ˈketl]
n.	(烧水用的) 壶，水壶;
[例句]I'll put the kettle on and make us some tea.
我去烧壶水给大家沏茶。
[其他]	复数：kettles
*** teapot
teapot	英[ˈtiːpɒt]
美[ˈtiːpɑːt]
n.	茶壶;
[例句]On Capitol Hill, senators today appear to view the matter as something of a tempest in a teapot.
美国国会的参议员们今天似乎把这个问题小题大做了。
[其他]	复数：teapots
*** cupboard 
cupboard	英[ˈkʌbəd]
美[ˈkʌbərd]
n.	橱柜; 食物柜; 衣柜; 壁橱;
[例句]The kitchen cupboard was stocked with tins of soup and food.
厨房的橱柜里备有汤罐头和食品罐头。
[其他]	复数：cupboards
*** hurry up
hurry up	英[ˈhʌri ʌp]
美[ˈhɜːri ʌp]
[词典]	赶紧; 赶快; 使加快; 使提早;
[例句]Franklin told Howe to hurry up and take his bath; otherwise, they'd miss their train
富兰克林告诉豪赶快去洗澡；否则他们会赶不上火车。
*** boiling
boil	英[bɔɪl]
美[bɔɪl]
v.	(使) 沸腾; 煮沸; 烧开; (把壶、锅等) 里面的水烧开; 用沸水煮(或烫洗); 被煮(或烫洗);
n.	沸腾; 沸点; 疖; 皮下脓肿; 黄水疮;
[例句]I stood in the kitchen, waiting for the water to boil
我站在厨房，等着水烧开。
[其他]	第三人称单数：boils 现在分词：boiling 过去式：boiled 过去分词：boiled

** Test
*** First
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
I can see the teapot,
but I can't see the tea?
There it is!
It's in front of you!
Can you see it?
Ah, yes. I see it now.
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam！
The kettle's boiling!
*** Second
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
I can see the teapot,
but I can't see the pea.
There it is!
It's in front of you!
Can you see it?
Ah, yes, I can see it now.
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam!
The kettle's boiling!
*** Third
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
I can see the teapot,
but I can't see the tea.
There it is!
It's in front of you!
Can you see it?
Ah, yes. I can see it now.
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam!
The kettle's boiling!
*** Forth
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
Can you see it?
I can see the teapot,
but I can't see the tea.
There it is!
It's in front of you!
Ah, yes. I can see it now.
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam!
The kettle's boiling!
*** Fifth
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
Can you see it?
I can see the teapot,
but I can't see the tea.
There it is!
It's in front of you!
Ah, yes. I can see it now!
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam!
The kettle's boiling!
*** Sixth
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
Can you see it?
I can see the teapot,
but I can't see the tea.
There it is!
It's in front of you!
Ah, yes. I can see it now.
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam!
The kettle's boiling!
*** Seventh
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
Can you see it?
I can see the teapot,
but I can't see the tea.
There it is!
It's in front of you!
Ah, yes. I can see it now.
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam!
The kettle's boiling!
* The boss's letter
** Text
Can you come here a minute please, Bob?
Yes, sir?
Where's Pamela?
She's next door.
She's in her office, sir.
Can she type this letter for me?
Ask her please.
Yes, sir.
Can you type this letter for the boss please, Pamela?
Yes, of course I can.
Here you are.
Thank you, Bob.
Bob!
Yes?
What's the matter?
I can't type this letter.
I can't read it!
The boss's handwriting is terrible!
** WORDS
*** handwriting | BrE ˈhandrʌɪtɪŋ, AmE ˈhæn(d)ˌraɪdɪŋ | noun uncountable
 ① (style) 笔迹 bǐjì
 ② (writing by hand) 书写 shūxiě
*** terrible 
terrible | BrE ˈtɛrɪb(ə)l, AmE ˈtɛrəb(ə)l | adjective
 ① (tragic) 可怕的 kěpà de ; (serious) 严重的 yánzhòng de ; (very unpleasant) 非常讨厌的 fēicháng tǎoyàn de
  ▸ a terrible blow 沉重的打击
  ▸ terrible poverty 赤贫
  ▸ a terrible fool/liar 大傻瓜/大骗子
  ▸ a terrible shame 奇耻大辱
 ② (unwell) 有病的 yǒubìng de
  ▸ to feel/look terrible 感觉不适/看上去有病
 ③ (guilty) 负疚的 fùjiù de
  ▸ to feel terrible about sth 对某事感到愧疚
 ④ (poor, awful) 糟糕的 zāogāo de ‹meal, performance, player›
  ▸ you look terrible in that hat 你戴那顶帽子难看死了
  ▸ to be terrible at sth/doing sth; 在某方面/做某事很差劲
 ⑤ (sinister) 骇人的 hàirén de ‹look, scream›
*** type 
type | BrE tʌɪp, AmE taɪp |
 A. noun
 ① countable (variety, kind) 类型 lèixíng
  ▸ a type of sth; 某物的一种
  ▸ all types of jobs, jobs of all types 各种各样的工作
  ▸ I'm not the or that type 我不是那种人
  ▸ this is definitely my type of place informal 这毫无疑问是我中意的那种地方
  ▸ he's not my type informal 他不是我喜欢的类型
 ② countable informal (person) 某种人 mǒu zhǒng rén
  ▸ an army type 军人一类的人
 ③ uncountable and countable Printing (for printing) 活字 huózì ; (on page) 字体 zìtǐ
  ▸ metal type 金属活字
  ▸ bold/italic type 黑体/斜体
  ▸ to be in type 付排
 ④ countable (archetype) 典型 diǎnxíng
  ▸ her characters are types rather than individuals 她塑造的人物是模式化的，缺乏个性
 B. -type combining form …类型的 … lèixíng de
  ▸ a documentary-type film 纪实类影片
 C. transitive verb
 ① (on typewriter, keyboard) 在…上打字 zài… shang dǎzì ‹page›; 键入 jiànrù ‹word›
  ▸ a typed letter 打印的信
  ▸ to type sth into a computer/on to a screen 把某内容输入电脑/打到屏幕上
  ▸ to type over a mistake 打错字
 ② (classify) 给…分型 gěi… fēnxíng ‹tissue›
  ▸ to type blood samples 给血样分类
  ▸ to be typed as sth; 被看作某类型
 D. intransitive verb 打字 dǎzì PHRASAL VERBS type in transitive verb [type sth in, type in sth]
 ① (on computer) 键入 jiànrù ‹word, command›
  ▸ to type in the file name 键入文件名
 ② (on typewriter) 打出 dǎchū ‹word, letter›type out transitive verb [type sth out, type out sth]
 ① (put in typed form) 打出 dǎchū ‹receipt, letter›
  ▸ I'd prefer it if you typed out the list 我希望你把单子打出来
 ② (erase) 打字覆盖 dǎ zì fùgài ‹error, name›
  ▸ if you make a mistake, you can just type it out 打错了就在上面再打字遮住
 type up transitive verb [type sth up, type up sth] 把…打出来 bǎ… dǎ chulai
 ‹note, draft, report, essay›

** Test
*** First
Can you come here a minute please, Bob?
Yes, sir.
Where's Pamela?
She's next door.
She's in the her office, sir.
Can she type this letter for me?
Ask her please.
Yes, sir.
Can you type this letter for the boss please, Pamela?
Yes, of course I can.
Here you are.
Bob?
Yes?
What's the matter?
I can't type this letter.
The boss's handwriting is terrible!
*** Second
Can you come here a minute please, Bob?
Yes, sir?
Where's Pamela?
She's next door.
She's in her office, sir.
Can she type this letter for me?
Ask her please.
Can you type this letter for the boss, Pamela?
Yes, of course I can.
Here you are.
Bob?
Yes?
What's the matter?
I can't type this letter.
I can't read it！
The boss's handwriting is terrible!
*** Third 
Can you come here a minute please, Bob?
Yes, sir?
Where's Pamela?
She's next door.
She's in her office, sir.
Can she type this letter for me?
Ask her please.
Yes, sir.
Can you type this letter for the boss please, Pamela?
Yes, of course I can.
Here you are.
Bob!
Yes?
What's the matter?
I can't type this letter.
I can't read it.
The boss's handwriting is terrible!
*** Forth
Can you come here a minute please, Bob?
Yes, sir.
Where's Pamela?
She's next door.
She's in her office, sir.
Can she type this letter for me.
Ask her please.
Yes, sir.
Can you type this letter for the boss please, Pamela?
Yes, of course I can.
Here you are.
Bob!
Yes?
What's the matter?
I can't type this letter.
I can's read it.
The boss's handwriting is terrible!
* A cup of coffee
** test
Do you like coffee, Ann?
Yes, I do.
Do you want a cup?
Yes, please. Christine.
Do you want any sugar?
Yes, please.
Do you want any milk?
No, thank you.
I don't like milk in my coffee.
I like black coffee.
Do you like biscuits?
Yes, I do.
Do you want one?
Yes, please.
** words
*** coffee
 A. noun
 ① uncountable (drink) 咖啡 kāfēi
 ② countable (cup) 一杯咖啡 yī bēi kāfēi
  ▸ three coffees, please 请来三杯咖啡
  ▸ black/white coffee 清咖/奶咖
 ③ uncountable (beans) 咖啡豆 kāfēidòu ; (ground) 研磨咖啡 yánmó kāfēi ; (powder) 咖啡粉 kāfēi fěn
 ④ uncountable (shrub) 咖啡树 kāfēi shù
 B. adjective (coffee-coloured) 咖啡色的 kāfēisè de ‹cloth, dress›
*** sugar
 A. noun
 ① uncountable (unrefined) [植物所含的] 糖 táng
  ▸ to refine sugar 炼糖
 ② uncountable and countable (refined) 食糖 shítáng
  ▸ brown/white sugar 红糖/白糖
  ▸ how many sugars do you take? 你要加多少糖？
  ▸ a sugar spoon 糖勺
 ③ (mainly US) informal (term of endearment) 亲爱的 qīn'ài de
  ▸ bye, sugar! 再见，宝贝儿！
 B. exclamation euphemistic informal 完了 wánle [表示恼怒]
  ▸ sugar! I've forgotten my wallet! 糟了！我忘带钱包了！
 C. transitive verb 在…中加糖 zài… zhōng jiā táng
  ▸ sugared almonds 糖衣杏仁
*** milk
 A. noun
 ① uncountable (general) 奶 nǎi
  ▸ a glass of milk 一杯牛奶
  ▸ to produce milk 泌乳
  ▸ to be in milk «animal» 在授乳期
  ▸ a land flowing with milk and honey 富饶之地
  ▸ the milk of human kindness 人的善良天性
  ▸ to be like milk and water 平淡无味
  ▸ it's no use or good crying over spilt milk proverb 覆水难收，后悔也无济于事
 ② uncountable Botany 白色汁液 báisè zhīyè
  ▸ the milk of a coconut 椰汁
 ③ uncountable and countable (cosmetic) 乳剂 rǔjì
 B. transitive verb
 ① Farming 挤…的奶 jǐ… de nǎi ‹cow›
 ② (extract) 抽取 chōuqǔ ‹sap, venom›
 ③ figurative (draw on) 消耗 xiāohào ‹resources›
  ▸ to milk the fund 动用资金
 ④ figurative (exploit) 榨取 zhàqǔ ‹money›; 套取 tàoqǔ ‹ideas›
  ▸ to milk sth/sb of sth, to milk sth from or out of sth/sb; 从某事物/某人处榨取某物
  ▸ to milk sth/sb dry 榨干某物/某人
  ▸ to milk the situation 趁机牟利自肥
  ▸ to milk sb's strength/enthusiasm 利用某人的体力/热情
  ▸ to milk the audience for applause 卖力地想博得观众的掌声
*** black coffee
black coffee	英[blæk ˈkɒfi]
美[blæk ˈkɔːfi]
网络	斋啡; 清咖啡; 清咖; 咖啡; 黑咖啡;
[例句]Newman poured more black coffee and lit a cigarette.
纽曼又倒了些黑咖啡，接着点了支烟
*** biscuits
biscuit | BrE ˈbɪskɪt, AmE ˈbɪskɪt |
 A. noun
 ① countable British (thin crisp cake) 饼干 bǐnggān
  ▸ plain/sweet biscuits 淡/甜饼干
  ▸ to take the biscuit British informal (be most surprising) 极为惊人 (be most annoying) 极其讨厌
 ② countable US (soft bread) 小松饼 xiǎo sōngbǐng
 ③ uncountable (colour) 淡褐色 dàn hèsè
 B. adjective 淡褐色的 dàn hèsè de

** test
*** First
Do you like coffee, Ann?
Yes, I do.
Do you want a cup?
Yes, please.
Do you want any sugar?
Yes, please. Christine.
Do you want any milk?
No, thank you.
I don't like milk in my coffee.
I like black coffee.
Do you like biscuits?
Yes, I do.
Do you want one?
Yes, please.
*** Second
Do you like coffee, Ann?
Yes, I do.
Do you want a cup?
Yes, please.
Do you want any sugar?
Yes, please. Christine.
Do you want any milk?
No, thank you.
I don't like milk in my coffee.
I like black coffee.
Do you like biscusts?
Yes, I do.
Do you want one?
Yes, please.
*** Third
Do you like coffee, Ann?
Yes, I do.
Do you want a cup?
Yes, please.
Do you like any sugar?
Yes, please. Christine.
Do you like any milk?
No, thank you.
I don't like milk in my coffee.
I like black coffee.
Do you like biscuits?
Yes, I do.
Do you want one?
Yes, please.

*** Forth
Do you like coffee, Ann?
Yes, I do.
Do you want a cup?
Yes, please.
Do you want any sugar?
Yes, please. Christine.
Do you want any milk?
No, thank you.
I don't like milk in my coffee?
I like black coffee.
Do you like biscuits?
Yes, I do.
Do you want one?
Yes, please.

*** Firth
Can you come here a minute please, Bob?
Yes, sir?
Where's Pamela?
She's next door.
She's in her office, sir.
Can she type this letter for me?
Ask her please.
Can you type this letter for the boss please, Pamela?
Yes, of course I can.
Here you are.
Thank you, Bob.
Bob!
Yes?
What's the matter?
I can't type this letter.
I can't read it!
The boss's handwriting is terrible!

*** Sixth
Can you come here a minute please, Bob?
Yes, sir?
Where's Pamela?
She's next door.
She's in her office, sir.
Can she type this letter for me?
Ask her please.
Yes, sir.
Can you type this letter for the boss please, Pamela?
Yes, of course I can.
Here you are.
Thank you, Bob.
Bob!
Yes?
What's the matter?
I can't type this letter.
I can't read it!
The boss's handwriting is terrible!
* At the Butchers
** Text
Do you want any meat today, Mrs. Bir?
Yes, please.
Do you want beef or lamb?
Beef, please.
This lamb's very good.
I like lamb,
but my husband doesn't.
What about some steak?
This is a nice piece.
Give me that piece, please.
And a pound of mince, too.
Do you want a chicken, Mrs. Bird?
They're are very nice.
No, thank you.
My husband likes steak, 
but he doesn't like chicken.
To tell you the truth, Mrs. Bird,
I don't like chicken either!
** Words
*** meat
meat	英[miːt]
美[miːt]
n.	肉类; (某种) 食用肉; 重要的部分; 有趣的部分;
[例句]Meat and fish are relatively expensive.
肉和鱼相对来说比较贵。
[其他]	复数：meats
*** beef
beef	英[biːf]
美[biːf]
n.	牛肉; 抱怨; 牢骚;
v.	老是抱怨; 大发牢骚;
[例句]Instead of beefing about what Mrs Martin has not done, her critics might take a look at what she is trying to do.
批评者不要老是抱怨马丁太太没有做什么事情，不妨看看她正要做什么事情。
[其他]	第三人称单数：beefs 现在分词：beefing 过去式：beefed
*** lamb

lamb	英[læm]
美[læm]
n.	羔羊; 小羊; 羊羔肉; (慈爱或怜悯地描述或称呼某人) 宝贝，乖乖;
v.	产羊羔;
[例句]She came and put her arms around me. 'You poor lamb. What's wrong?'
她走过来搂着我。“可怜的宝贝，出什么事儿啦？”
[其他]	复数：lambs
*** steak
steak	英[steɪk]
美[steɪk]
n.	牛排; 肉排; 肉块; 碎牛肉(不是最佳部位，常剁碎出售，可以炖或做馅等);
[例句]Waiter, I specifically asked for this steak rare.
服务员，我特别强调了这块牛排要做得嫩些。
[其他]	复数：steaks
*** mince
mince	英[mɪns]
美[mɪns]
v.	用绞肉机绞(食物，尤指肉); 装腔作势地小步快走;
n.	绞碎的肉，肉末(尤指牛肉);
[例句]Brown the mince in a frying pan.
在煎锅里把肉末煎至棕色。
[其他]	第三人称单数：minces 现在分词：mincing 过去式：minced 过去分词：minced
*** truth
truth	英[truːθ]
美[truːθ]
n.	真相; 实情; 事实; 真实情况; 真实; 真实性; 真理;
[例句]Is it possible to separate truth from fiction?
有可能把事实与虚构分开吗？
[其他]	复数：truths
** test
*** First
Do you want any meat today, Mrs. Bird?
Yes, please.
Do you want beef or lamb?
Beef, please.
This lamb's very good.
I like lamb,
but my husband doesn't.
What about some steak?
This is a nice piece.
Give me that piece, please.
And a pound of mince, too.
Do you want a chicken, Mrs. Bird?
They're very nice.
No, thank you.
My husband likes steak,
but he doesn't like chicken.
To tell you the truth, Mrs. Bird.
I don't like chicken either!
*** Second
Do you want any meat today, Mrs. Bird?
Yes, please.
Do you want beef or lamb?
Beef, please.
This lamp's very good.
I like lamb,
but my husband doesn't.
What about some steak?
This is a nice piece.
Give me that peice, please.
And a pound of mince, too.
Do you want a chicken, Mrs. Bird?
They're very nice.
No, thank you.
My husband likes steak,
but he doesn't like chicken.
To tell you the truth, Mrs. Bird.
I don't like chicken either!
*** Third
Do you want any meat today, Mrs. Bird?
Yes, please.
Do you want beef or lamb?
Beef, please.
This lamb's very good.
I like lamb,
but my husband doesn't.
What about some steak?
This is a very nice peice.
Gave me that peice, please.
And a pound of mince, too.
Do you want a chicken, Mrs. Bird?
They're very nice.
No, thank you. 
My husband likes steak,
but he doesn't like chicken.
To tell you the truth, Mrs. Bird.
I don't like chicken either!

* Interesting climate
** Text
Where do you come from?
I come from England.
What's the climate[fn:2] like in your country?
It's mild[fn:3],
but it's not always pleasant[fn:1].
The weather's often cold in the North and windy[fn:4] in the East.
It's often wet[fn:5] in the West and sometimes warm in the south.
Which seasons[fn:6] do you like best?
I like spring and summer.
The days are long and the nights are short.
I don't like autumn and winter.
The days are short and the nights are long.
The sun rises late and set[fn:7] early.
Our climate is not very good.
but it's certainly interesting.
It's our favorite[fn:8] subject[fn:9] of conversation[fn:10].
** Test
*** First
Where do you come from? 
I come from England.
What's the climate like in your country?
It's mild.
but it's not always pleasant.
The weather's often cold in the North and windy in the East.
It's often wet in the West and sometimes warm in the south.
Which seasons do you like best?
I like spring and summer.
The days are long and the nights are short.
I don't like autumn and winter.
The days are short and the nights are long.
The sun rises late and set early.
Our climate is not very good.
but it's certainly interesting.
It's our favorite subject of conversation.
*** Second
Where do you come from?
I come from England.
What's the climate like in your country?
It's mild.
The weather's often cold in the North,
and windy in the East.
It's often wet in the West and sometimes warm in the south.
Which seasons do you like best?
I like spring and summer.
The days are long and the nights are short.
I don't like autumn and winter.
The days are short and the nights are long.
The sun rises late and set early.
Our climate is not very good,
but it's certainly interesting.
It's our favorite subject of conversation.
*** Third
Where do you come from?
I come from England.
What's the cilmate like in your country?
It's mild.
but it's not always pleasant.
The weather's often cold in the North and windy in the East.
It's often wet in the West and sometimes warm in the South.
Which seasons do you like best?
I like spring and summer.
The days are long and the nights are short.
I don't like autumn and winter. 
The days are short and the nights are long.
The sun rises late and set early.
Our climate is not very good.
but it's certainly interesting.
It's our favorite subject of conversation.

* Sawyer's family
** Text
The Sawyer live at 87 King street.
In the morning, Mr. Sawyer goes to work and the children go to school..
Mrs. Sawyer stays at home every day.
She does the housework.
She always eats her lunch at noon.
In the afternoon, she usually sees her friends.
They often drink tea together.
In the evening, the children come home from school.
They arrive home early.
Mr. Sawyer comes home from work.
He arrives home late.
At night, the children always do their homework.
Then they go to bed.
Mr. Sawyer usually reads his newspaper,
but sometimes he and his wife watch television.
** Test
*** First
The Sawyer live at 87 King Street.
In the morning, Mr. Sawyer goes to work and the children go to school.
Mrs. Sawyer stays at home every day.
She does the housework.
She always eats her lunch at noon.
In the afternoon, she usually sees her friends.
They often drink tea together.
In the evening, the children come home from school.
They arrive home early.
Mr. Sawyer comes home from work. 
He arrives home late.
At night, the children always do their homework.
Then they go to bed.
Mr. Sawyer usually reads his newspaper, but sometimes he and his wife watch television.
*** Second
The Sawyer live at 87 King Street.
In the morning, Mr. Sawyer goes to work and the children go to school.
Mrs. Sawyer stays at home every day.
She does the housework.
She always eats her lunch at noon.
In the afternoon, Mrs. Sawyer usually sees her friends.
They often drink tea together.
In the evening, the children come home from school.
They arrive home early.
Mr. Sawyer comes home from work.
He arrives home late.
At night, the children always do their homework.
Then they go to bed.
Mr. Sawyer usually reads his newspaper at night.
But sometimes he and his wife watch television.
*** Third
The Sawyer live at 87 King Street.
In the morning, Mr. Sawyer goes to work and the children go to school.
Mrs. Sawyer stays at home every day.
She does the housework.
She always eats her lunch at noon.
In the afternoon, Mrs. Sawyer usually sees her friends.
They often drink tea together.
In the evening, the children come home from school.
They arrive home early.
Mr. Sawyer comes home from work.
He arrives home late.
At night, the children always do their homework.
Then they go to bed.
Mr. Sawyer usually reads his newspaper at night,
but sometimes he and his wife watch television.
*** Forth
The Sawyer live at 87 King Street.
In the morning, Mr. Sawyer goes to work and the children go to school.
Mrs. Sawyer stays at home every day.
She does the housework.
She always eats her lunch at noon.
In the afternoon, Mrs. Sawyer usually sees her friends.
They often drink tea together.
In the evening, the children come home from school.
They arrive home early.
Mr. Sawyer comes home from work.
He arrives home late.
At night, the children always do their homework.
Then they go to bed.
Mr. Sawyer usually reads his newspaper at night.
But sometimes he and his wife watch television.
* Unusuall days
** text 
#+BEGIN_VERSE 
  
It is eight o'clock.
The children go to school by car every day, but today, they are going to school on foot.
It is ten o'clock. Mrs. Sawyer usually stays at home in the morning, 
but this morning, she is going to the shops.
It is four o'clock.
In the afternoon, Mrs. Sawyer usually drinks tea in the living room.
But this afternoon, she is drinking tea in the garden.
It is six o'clock.
In the evening, the children usually do their homework,
but this evening, they are not doing their homework.
At the moment, they are playing in the garden.
It is nine o'clock.
Mr. Sawyer usually reads his newspaper at night.
But he's not reading his newspaper tonight.
At the moment, he's reading an interesting book.

#+END_VERSE
** words
*** on foot 
on foot	英[ɒn fʊt]
美[ɑːn fʊt]
[词典]	步行; 走路去;
[例句]I go to school usually on foot.
我上学通常是走路去。
*** living room
living room
英[ˈlɪvɪŋ ruːm]
美[ˈlɪvɪŋ ruːm]
n.	客厅; 起居室;
[例句]We were sitting on the couch in the living room watching TV.
我们就坐在客厅的沙发上看电视。
[其他]	复数：living rooms
*** at the moment
at the moment
英[æt ðə ˈməʊmənt]
美[æt ðə ˈmoʊmənt]
[词典]	此刻; 目前; 眼下;
[例句]I remember now. He arrived just at the moment it happened
现在我想起来了，他恰恰在事情发生的时候到了。
*** tonight 
tonight	英[təˈnaɪt]
美[təˈnaɪt]
adv.	在今夜; 在今晚;
n.	今夜; 今晚;
[例句]I'm at home tonight
我今晚在家。
** test 
*** First
 It is eight o'clock.
 The children usually go to school by car every day, 
 but today, they are going to school on foot.
 It is ten o'clock. Mrs. Sawyer usually stays at home in the morning,
 but this morning, she is going to the shops.
 It is four o'clock.
 In the afternoon, Mrs. Sawyer usually drinks tea in the living room, 
 But this afternoon, she is drinking tea in the garden.
 It is six o'clock.
 In the evening, the children usually do their homework,
 but this evening, they are not doing their homework.
 At the moment, they are playing in the garden.
 It is nine o'clock.
 Mr. Sawyer usually reads his newspaper at night.
 But he's not reading his newspaper tonight.
 At the moment, He's reading an interesting book.
*** Second
It is eight o'clock.
The children usually go to school by car every day, 
but today, they are going to school on foot.
It is ten o'clock. Mrs. Sawyer usually stays at home in the morning, 
but this morning, she is going to the shops.
It it four o'clock.
In the afternoon, Mrs. Sawyer usually drinks tea in the living room.
But this afternoon, she is drinking tea in the garden.
It is six o'clock.
In the evening, the children usually do their homework,
but this evening, they are not doing their homework.
At the moment, they are playing in the garden.
It is nine o'clock.
Mr. Sawyer usually reads his newspaper at night,
but he's not reading his newspaper tonight.
At the moment, he's reading an interesting book.
*** Third
It is eight o'clock.
The children go to school by car every day, 
but today, they are going to school on foot.
It is ten o'clock. Mrs. Swayer usually stays at home in the morning,
but this morning, she is going to the shops.
It is four o'clock.
In the afternoon, Mrs. Sawyer usually drinks tea in the living room.
But this afternoo, she is drinking tea in the garden.
It is six o'clock.
In the evening, the children usually do their homework,
but this evening, they are not doing their homework.
At the moment, they are playing in the garden.
It is nine o'clock.
Mr. Sawyer usually reads his newspaper at night.
But he's not reading his newspaper tonight.
At the moment, He's reading an interesting book.
*** Forth
It is eight o'clock.
The children go to school by car every day,
but today, they are going to school on foot.
It is ten o'clock. Mrs. Sawyer usually stays at home in the morning,
but this morning, she is going to the shops.
It is four o'clock.
In the afternoon, Mrs. Sawyer usually drinks tea in the living room.
But this afternoon, she is drinking tea in the garden.
It is six o'clock.
In the evening, the children usually do their homework,
but this evening, they are not doing their homework.
At the moment, they are playing in the darden.
It is nine o'clock.
Mr. Sawyer usually reads his newspaper at night.
But he's not reading his newspaper tonight.
At the moment, he's reading an interesting book.
*** Fifth
It is eight o'clock.
The children go to school by car every doy,
but today, they are going to school on foot.
It is ten o'clock. Mrs. Sawyer usually stays at home in the morning, 
but this morning, she is going to the shops.
It is four o'clock.
In the afternoon, Mrs. Sawyer usually drinks tea in the living room.
But this afternoon, she is drinking tea in the garden.
It is six o'clock.
In the evening, the children usually do their homework,
but this evening, they are not doing their homework.
At the moment, they are playing in the garden.
It is nine o'clock.
Mr. Sawyer usually reads his newspaper at night.
But he's not reading his newspaper tonight.
At the moment, he's reading an interesting book.
* Is that all?
I want some envelopes, please.
Do you want the large size or the small size?
The large size, please.
Do you have any writing paper?
Yes, we do.I don't have any small pads.
I only have large one.
Do you want a pad?
Yes, please.
And I want some glue.
A bottle of glue.
And I want a large box of chalk, too.
I only have small boxes.
Do you want one?
No, thank you.
Is that all?
That's all, thank you.
What else do you want?
I want my change.
** Words
*** envelope 
envelope	英[ˈenvələʊp]
美[ˈenvəloʊp]
n.	信封; 塑料封套; 塑料封皮;
[例句]There's a valuable place for fashion and design that pushes the envelope a bit
在原有尺度上有所突破的时尚和设计受到人们的重视。
[其他]	复数：envelopes
*** pad
pad	英[pæd]
美[pæd]
n.	(吸收液体、保洁或保护用的) 软垫，护垫，垫状物; 便笺本; 拍纸簿; 爪垫; 肉掌;
v.	(用软材料) 填充，覆盖，保护; 蹑手蹑脚地走; 虚报(账目); 做黑账;
[例句]He withdrew the needle and placed a pad of cotton-wool over the spot.
他把针头拔出，在扎针处按了一块药棉。
[其他]	第三人称单数：pads 复数：pads 现在分词：padding 过去式：padded 过去分词：
padded
*** glue
glue	英[ɡluː]
美[ɡluː]
n.	胶; 胶水;
v.	(用胶水) 粘合，粘牢，粘贴;
[例句]Glue the fabric around the window
用胶水把布料粘在窗户周围。
[其他]	第三人称单数：glues 复数：glues 现在分词：glueing 过去式：glued 过去分词：
glued
*** chalk
chalk	英[tʃɔːk]
美[tʃɑːk]
n.	白垩; (白色或彩色的) 粉笔;
v.	用粉笔写(或画);
[例句]Her skin was chalk white and dry-looking.
她的皮肤看上去苍白发干。
[其他]	第三人称单数：chalks 现在分词：chalking 过去式：chalked 过去分词：
chalked
*** change
change
英 [tʃeɪndʒ]   美 [tʃeɪndʒ]  
v.
改变;变化;使不同;(使)变换，改换，变成
n.
改变;变化;变更;变革;(会令人感兴趣或可喜的)变化;替代;更换;替代物;零钱。
第三人称单数： changes 复数： changes 现在分词： changing 过去式： changed 过去
分词： changed
** Test
*** First
I want some envelopes, please.
Do you want the large size or the small size?
The large size, please.
Do you have any writing paper?
Yes, we do.
I only have the large one.
Do you want a pad?
Yes, please.
And I want some glue.
A bottle of glue.
And I want a large box of chalk, too.
I only have small boxes.
Do you want one?
No, thank you.
Is that all?
That's all, thank you.
What else do you want?
I want my change.
*** Second
I want some envelopes, please.
Do you want the large size or the small size?
The large size, please.
Do you have any writing paper?
Yes, we do.
I don't have any small pads.
I only have large one. 
Do you want one?
Yes, please.
And I want some glue.
A bottle of glue.
And I want a large box of chalk, too.
I only have small boxes.
Do you want one?
No, thank you.
Is that all?
That's all, thank you.
What else do you want?
I want my change.
*** Third
I want some envelopes, please.
Do you want the large size or the small size?
The large size, please.
Do you have any writing paper?
Yes, we do.
I don't have any small pads.
I only have large one.
Do you want a pad?
Yes, please.
And I want some glue.
A bottle of glue.
And I want a large box of chalk, too.
I only have small boxes.
Do you want one?
No, thank you.
Is that all?
That's all, thank you.
What else do you want?
I want my change.
*** Forth
I want some envelopes, please.
Do you want the large size or the small size?
The large size, please.
Do you have any writing paper?
Yes, we do.
I don't have any small pads.
I only have large one.
Do you want a pad?
Yes, please.
And I want some glue.
A bottle of glue.
And I want a large box of chalk, too.
I only have small boxes.
Do you want one?
No, thank you.
It that all?
That's all, thank you.
What else do you want?
I want my change.

* Bad cold
** Text
Where's Jimmy?
He's in bed.
What's the matter with him?
He feels ill.
He looks ill.
We must call the doctor.
Yes, we must.
Can you remember the doctor's telephone number?
Yes. It's 09754.
Open your mouth, Jimmy.
Show me your tongue.
Say,"Ah."
What's the matter with him, doctor?
He has a bad cold. Mr. Williams, 
so he must stay in bed for a week.
That's good news for Jimmy.
Good news? Why?
Because he doesn't like school!
** test
*** First
Where's Jimmy?
He's in bed.
What's matter with him?
He feels ill.
He looks ill.
We must call the doctor.
Yes, we must.
Can you remember the doctor's telephone number?
Yes. It's 09754.
Open your mouth, Jimmy.
Show me your tongue.
Say, "Ah."
What's the matter with him, doctor?
He has a bad cold, Mr. Williams,
so he must stay in bed for a week.
That's good news for Jimmy.
Good news? Why?
Because he doesn't like the school!
*** Second
Where's Jimmy?
He's in bed.
What's the matter with him?
He feels ill.
He looks ill.
We must call the doctor.
Yes, we must.
Can you remember the doctor's telephone number?
Yes. It's 09754.
Open your mouth, Jimmy.
Show me your tongue.
Say, "Ah."
What's the matter with him, doctor?
He has a bad cold, Mr. Williams,
so he must stay in bed for a week.
That's good news for Jimmy.
Good news? Why?
Because he doesn't like school!
*** Third
Where's Jimmy?
He's in bed.
What's the matter with him?
He feels ill.
He looks ill.
We must call the doctor.
Yes, we must.
Can you remember the doctor's telephone number?
Yes, it's 09754.
Open your mouth, Jimmy.
Show me your tongue.
Say, "Ah."
What's the matter with him, doctor?
He has a bad cold, Mr. Williams,
so he must stay in bed for a week.
That's good news for Jimmy?
Good news? Why?
Because he doesn't like the school!
*** Forth
Where's Jimmy?
He's in bed.
What's the matter with him?
He feels ill.
He looks ill.
We must call the doctor.
Yes, we must.
Can you remember the doctor's telephone number?
Yes, it's 09754.
Open your mouth Jimmy.
Show me your tongue.
Say, 'Ah.'
What's the matter with him, doctor?
He has a bad cold, Mr. Williams, 
so he must stay in bed for a week.
That's good news for Jimmy.
Good news? Why?
Because he doesn't like school!
 
* Thank you. Doctor
How's Jimmy today?
Better. Thank you, Doctor.
Can I see him please, Mrs. Williams?
Certainly, doctor.
Come up stairs.
You look very well, Jimmy.
You are better now, 
but you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams.
And he mustn't eat rich food.
Does he have a temperature, doctor?
No, he doesn't.
Must he stay in bed?
Yes. He must remain in bed for another two days.
He can get up for about two hours each day, 
but you must keep the room warm.
Where's Mr. Williams this evening?
He's in bed, doctor.
Can you see him please?
He has a bad cold, too!
** words
*** remain

remain	英[rɪˈmeɪn]
美[rɪˈmeɪn]
v.	仍然是; 保持不变; 剩余; 遗留; 继续存在; 仍需去做(或说、处理);
[例句]The three men remained silent
这 3 个人保持着沉默。
[其他]	第三人称单数：remains 现在分词：remaining 过去式：remained 过去分词：
remained
*** stairs 
stairs	英[steəz]
美[stɛrz]
n.	楼梯; 梯级;
[词典]	stair 的复数;
[例句]We walked up a flight of stairs
我们上了一段楼梯。
[其他]	原型： stair
** test
*** First
How's Jimmy today?
Better. Thank you. Doctor.
Can I see him please, Mrs. Williams?
Certainly. Doctor.
Come up stairs.
You look very well, Jimmy.
You are better now, 
but you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams.
And he mustn't eat rich food.
Does he have a temperature, doctor?
No, he doesn't.
Must he stay in bed?
Yes, he must remain in bed for another two days.
He can get up for about two hours each day,
but you must keep the room warm.
Where's Mr. Williams this evening?
He's in bed, doctor.
Can you see him please?
He has a bad cold, too!
*** Second
How's Jimmy today?
Better. Thank you, Doctor.
Can I see him please, Mrs. Williams? 
Certainly, doctor.
Come up stairs.
You look very well, Jimmy.
You are better now, 
but you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams.
And he mustn't eat rich food.
Does he have a temperature，doctor? 
No, he doesn't.
Must he stays in bed?
Yes, he must remain in bed for another two days,
He can get up for about two hours each day,
but you must keep the room warm.

Where's Mr. Williams this evening? 
He's in bed, doctor.
Can you see him please?
He has a bad cold, too!
*** Third 
How's Jimmy today?
Better. Thank you, Doctor.
Can I see him please, Mrs. Williams? 
Certainly, doctor.
Come up stairs.
You look very well, Jimmy.
You are better now, 
but you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams,
and he mustn't eat rich food.
Does he have a temperature, doctor? 
No, he doesn't.
Must he stay in bed?
Yes, he must remain in bed for another two days.
He can get up for about two hours each day, 
but you must keep the room warm.
Where's Mr. Williams this evening?
He's in bed, doctor.
Can you see him please?
He has a bad cold, too!
*** Forth
How's Jimmy today?
Better. Thank you, Doctor.
Can I see him please, Mrs. Williams? 
Certainly, doctor.
Come up stairs.
You look very well, Jimmy.
You are better now.
But you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams.
And he mustn't eat rich food.
Does he have a temperature, doctor? 
No, he doesn't.
Must he stay in bed?
Yes. He must remain stay in bed for another two days.
He can get up for about two hours each day, 
but you must keep the room warm.
Where's Mr. Williams this evening? 
He's in bed, doctor.
Can you see him please?
He has a bad cold, too!
*** Fifth
How's Jimmy?
Better. Thank you, doctor.
Can I see him please, Mrs. Williams?
Certainly, doctor.
Come up stairs.
You look very well, Jimmy.
You are better now,
but you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams.
And he mustn't eat rich food.
Does he have a temperature, doctor?
No, he doesn't.
Must he stay in bed?
Yes. He must remain in bed for another two days.
He can get up for about two hours each day, 
but you must keep the room warm.
Where's Mr. Williams this evening?
He's bed, doctor.
Can you see him please?
He has a bad cold, too!
*** Seventh
How's Jimmy today?
Better. Thank you. Doctor.
Can I see him please, Mrs. Williams?
Certainly, doctor. 
Come up stairs.
You look very well, Jimmy.
You are better now,
but you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams.
And he mustn't eat rich food.
Does he have a temperature, doctor?
No, he doesn't.
Must he stay in bed?
Yes. He must remain stay in bed for another two days.
He can get up for about two hours each day, 
but you must keep the room warm.
Where's Mr. Williams this evening? 
He's in bed, doctor.
Can you see him please?
He has a bad cold, too!

* Not a same baby
What are you going to do this evening, Jill?
I'm going to meet some friends, Dad.
You mustn't come home late.
You must be home at half past ten.
I can't get home so early, Dad!
Can I have the key to the front door please?
No, you can't.
Jill's eighteen years old, Tom.
She's not a baby.
Give her the key.
She always comes home early.
Oh, all right!
Here you are.
But you mustn't come home after a quarter past eleven.
Do you hear?
Yes, Dad.
Thanks, Mum.
That's all right. Goodbye.
Enjoy youselef!
We always enjoy ourselves, Mum.
Bye-bye.
** Words
*** meet

meet	英[miːt]
美[miːt]
v.	相遇; 相逢; 遇见; 开会; 会晤; (与…) 会面; 集合;
n.	体育比赛; 运动会; 猎狐运动;
[例句]I have just met the man I want to spend the rest of my life with
我刚刚遇到了我想与之共度余生的男人。
[其他]	第三人称单数：meets 复数：meets 现在分词：meeting 过去式：met 过去分词：
met
*** home
home	英[həʊm]
美[hoʊm]
n.	家; 住所; (可买卖的) 房子，住宅，寓所; 家乡; 故乡; 定居地;
adj.	家的; 家庭的; 在家里做的; 家用的; 本国的; 国内的;
adv.	到家; 向家; 在家; 到正确的位置;
[例句]Last night they stayed at home and watched TV
昨晚他们呆在了家里看电视。
[其他]	第三人称单数：homes 复数：homes 现在分词：homing 过去式：homed 过去分词：
homed
*** get home
get home	英[ɡet həʊm]
美[ɡet hoʊm]
[词典]	抵家;
[例句]Come along, lad. Time for you to get home.
来吧，小伙子。你该回家了。
*** quarter
quarter	英[ˈkwɔːtə(r)]
美[ˈkwɔːrtər]
n.	四等份之一; (正点之前或之后的) 15 分钟，一刻钟; 三个月时间; 季度; 季;
v.	把…切成(或分成)四部分; 给…提供食宿;
[例句]The group said results for the third quarter are due on October 29.
该集团表示第三季度的结果将于 10 月 29 日公布。
[其他]	第三人称单数：quarters 复数：quarters 现在分词：quartering 过去式：quartered 过去分词：quartered
*** hear
hear	英[hɪə(r)]
美[hɪr]
v.	听见; 听到; 听; 注意听; 倾听; 听说; 得知;
[例句]She heard no further sounds
她再没有听到别的声音了。
[其他]	第三人称单数：hears 现在分词：hearing 过去式：heard 过去分词：heard
*** enjoy
enjoy	英[ɪnˈdʒɔɪ]
美[ɪnˈdʒɔɪ]
v.	享受…的乐趣; 欣赏; 喜爱; 过得快活; 玩得痛快; 得到乐趣; 享有; 享受;
[例句]Ross had always enjoyed the company of women
罗斯总是喜欢有女人陪伴。
[其他]	第三人称单数：enjoys 现在分词：enjoying 过去式：enjoyed 过去分词：
enjoyed
enjoy yourself
英[ɪnˈdʒɔɪ jɔːˈself]
美[ɪnˈdʒɔɪ jɔːrˈself]
[词典]	祝你玩得开心; 祝你玩得痛快; 尽情享受;
[例句]Get out and enjoy yourself, make new friends.
出去走走，好好玩玩，交些新朋友。
** Test
*** First
What are you going to do this evening, Jill?
I'm going to meet some friends, Dad.
You mustn't come home late.
You must be home at half past ten.
I can't get home so early, dad.
Can I have the key to the front door, please.
No, you can't!
Jill's eighteen years old, Tom.
She's not a baby.
Give her the key.
She always comes home early.
Oh, all right.
Here you are.
But you mustn't come home after a quarter past eleven.
Do you hear?
Yes, Dad.
Thanks, Mum.
That's all right. Goodbye.
Enjoy yourself.
We always enjoy ourselves, Mum.
Bye-bye.
*** Second
What are you going to do this evening, Jill?
I'm going to meet some friends, Dad.
You mustn't come home late.
You must be home at half past ten.
I can't get home so early, Dad!
Can I have the key to the front door please?
No, you can't.
Jill's eighteen years old, Tom.
She's not a baby.
Give her the key.
She always comes home early.
Oh! all right.
Here you are.
But you mustn't come home after a quarter past eleven.
Do you hear?
Yes, Dad.
Thinks, Mum.
That's all right. Goodbye.
Enjoy yourself!
We always enjoy ourselves, Mum.
Bye-bye.
语序错了一句。
*** Third
What do you going to do this evening, Jill?
I'm going to meet some friends, Dad.
You mustn't come home late.
You must be home at half past ten.
I can't get home so early, Dad!
Can I have the key to the front door please?
No, you can't.
Jill's eighteen years old, Tom.
She's not a baby.
Give her the key.
Oh! All right.
Here you are.
But you mustn't come home after a quarter past eleven.
Do you here?
Yes, dad.
Thanks, Mum.
That's all right. Boodbye.
Enjoy yourself!
We always enjoy ourselves, Mum. 
Bye-bye.

* Weekend
Hello. Were you at the butcher's?
Yes. I was.
Were you at butcher's, too?
No, I wasn't.
I was at the greengrocer's.
How's Jimmy today?
He's very well, thank you.
Was he absent from school last week?
Yes, he was.
He was absent on Monday, Tuesday, Wednesday and Thursday.
How are you all keeping?
Very well, thank you.
We're going to spend three days in the country.
We're going to stay at my mother's for the weekend.
Friday, Saturday and Sunday in the country!
Aren't you luck!
** Test
*** First
Hello. Were you at the butcher's?
Yes, I was.
Were you at the butcher's, too?
No, I wasn't.
I was at the greengrocer's.
How's Jimmy today?
Very well. Thank you.
Was he absent from school last wee?
Yes, he was.
He was absent on Monday, Tuesday, Wednesday and Thursday.
How are you all keeping?
Very well, thank you.
We're going to spend three days in the country.
We're going to stay at my mother's for the weekend.
Friday, Saturday and Sunday in the country!
Aren't you luck!
*** Second
Hello. Were you at the butcher's?
Yes, I was.
Were you at the butcher's, too?
No, I wasn't.
How's Jimmy today?
He's very well, thank you.
Was he absent from school last week?
Yes, he was.
He was absent on Monday, Tuesday, Wednesday and Thursday.
How are you all keeping?
Very well, thank you.
We're going to spend three days in the country.
We're going to stay at my mother's for the weekend,
Friday, Saturday and Sunday in the country!
Aren't you luck!
*** Third
Hello. Were you at the butcher's? 
Yes, I was.
Were you at butcher's, too?
No, I wasn't.
I was at the greengrocer's.
How's Jimmy today?
He's very well, thank you.
Was he absent from school last week?
Yes, he was.
He was absent on Monday, Tuesday, Wednesday and Thursday.
How are you all keeping? 
Very well, thank you.
We're going to spend three days in the country.
We're going to stay at my mother's for the weekend.
Friday, Saturday and Sunday in the country!
Aren't you luck!

Very good!
*** Forth
Hello. Were you at the butcher's?
Yes, I was.
Were you at butcher's, too?
No, I wasn't.
I was at the greengrocer's.
How's Jimmy today? He's very well, thank you.
Was he absent from school last week? 
Yes, he was.
He was absent on Monday, Tuesday, Wednesday and Thurday.
How are you all keeping?
Very well, thank you.
We're going to spend three days in the country.
We're going to stay at my mother's for the weekend.
Friday, Saturday and Sunday in the country.
Aren't you luck!
** words
*** week
this week next week last week
a week ago, the week before last
*** day of a week
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
What day is it today?
Sunday is a holiday.
Today is Saturday.
I'm so tired. I wish today was Saturday.
Today is Saturday. It's a day off.
Today is Saturday. I get up very early on.

* Car race

There is a car race near our town every year.
In 1995, there was a very big race.
There were hundreds of people there.
My wife and I were at the race.
Out friends Julie and Jack were there, too.
You can see us in the crowd.
We are standing on the left.
There are twenty cars in the race.
There were English cars, French cars, German cars. Italian cars. American cars
and Japanses cars.
It was an exciting finish.
The winner was Billy Stewart.
He was in car number fifteen.
Five other cars were just behind him.
On the way home, my wife said to me.
'Don't drive so quickly! You're not Billy Stewart!'
** Test
*** First
There is a car race near out town every year.
In 1995, there was a very big race.
There were hundreds of people there.
My wife and I were at the race.
Our friends Julie and Jack were there, too.
You can see us in the crowd.
We are standing on the left.
There were twenty cars in the race.
There were English cars, French cars, German cars. Italian cars, American cars
and Japanese cars.
It was an exciting finish.
The winner was Billy Stewart.
He was in car number fifteen.
Five other cars were just behind him.
On the way home, my wife said to me.
'Don't drive so quickly! You're not Billy Stewart!'
*** Second
There is a car race near our town every year.
In 1995, there was a very big race.
There were hundreds of people there.
My wife and I were at the race.
Our friends Julie and Jack were there, too.
You can see us in the crowd.
We are standing on the left.
There were twenty cars in the race.
There were English cars, French cars, German cars. Italian cars, American cars
and Japanese cars.
It was an exciting finish.
The winner was Billy Stewart. 
He was in car number fifteen.
Five other cars were just behind him.
On the way home, my wife said to me.
'Don't drive so quickly! You're not Billy Stewart!'
*** Third
There is a car race near our town every year.
In 1995, there was a very big race.
There were hundreds of people there.
My wife and I were at the race.
Our friends Julie and Jack were there, too.
You can see us in the crowd.
We are standing on the left.
There were twenty cars in the race.
They were English cars, French cars, German cars. Italian cars, American cars and
Japanese cars.
It was an exciting finish.
The winner was Billy Steward.
He was in car number fifteen.
Five other cars were just behind him.
On the way home, my wife said to me.
'Don't drive so quickly! You're not Billy Stewart!'
*** Forth
There is a car race near our town every year.
In 1995, there was a very big race.
There were hundreds of people there.
My wife and I were at the race.
Our friends Julie and Jack were there, too.
You can see us in the crowd.
We are standing on the left.
There were twenty cars in the race.
There were English cars, French cars, German cars. Italian cars, American cars
and Japanese cars.
It was an exciting finish.
The winner is Billy Stewart.
He was in car number fifteen.
Five other cars were just behind him.
On the way home, my wife said to me.
'Don't drive so quickly! You're not Billy Stewart!'
*** Fifth
There is a car race near our town every year.
In 1995, there was a very big race.
There were hundreds of people there.
My wife and I were at the race.
Our friends Julie and Jack were there, too.
You can see us in the crowd.
We are standing on the left.
There were twenty cars in the race.
There were English cars, French cars, German cars. Italian cars, American cars
and Japanese cars.
It was an exciting finish.
The winner was Billy Stewart!
He was in car number fifteen.
Five other cars were just behind him.
On the way home, my wife said to me.
'Don't drive so quickly! You're not Billy Stewart!'

** words
*** race
 race	英[reɪs]
 美[reɪs]
 n.	赛跑; 速度竞赛; 竞争; 角逐; 赛马会; 种族; 人种; 血统;
 v.	(和…) 比赛; 参加比赛; 使比赛; 让…参加速度比赛; (使) 快速移动，快速运转;
 [例句]The women's race was won by the American, Patti Sue Plumer.
 女子赛跑的冠军被美国人帕蒂·休·普卢默夺得。
 [其他]	第三人称单数：races 复数：races 现在分词：racing 过去式：raced 过去分词：
 raced
*** hundred
 hundred	英[ˈhʌndrəd]
 美[ˈhʌndrəd]
 num.	一百; 许多; 大量; 100 到 999 间的数目; 百位数;
 [例句]According to one official more than a hundred people have been arrested.
 一名官员称有一百多人被捕。
 [其他]	复数：hundreds
*** hundreds of
 成百上千
 hundred and hundreds of
 区别
 | 搭配不同                | 含义不同               |
 |-------------------------+------------------------|
 | 数字/a+hundred+名词复数 | 具体（一、二、三 \百） |
 | hundreds of +名词复数   | 笼统数百               |
 |-------------------------+------------------------|

 1.数字/a+hundred+可数名词复数
 表示具体数目
 five hundred cars
 五百辆汽车
 a hundred boys
 一百个男孩子
 I have three hundred books.
 我有三百本书。
 【注意：hundred 是单数，名词前没有 the 或其他修饰词】

 2.hundreds of+可数名词复数
 表示“数百、成百上千”的笼统数目
 hundreds of cars
 数百辆汽车
 I have hundreds of books.
 我有数百本书。
 【注意：hundreds 复数，后有 of，名词前没有 the 或其他修饰词】
 3.拓展 TIPS:
 1)表示...当中的...，须加 of
 数字+hundred+of+the+可数名词复数
 数字+hundred of us/them/these/those...

 three hundred of the people
 这些人当中的三百人

 three hundred of us 
 我们当中的三百人

 Five hundred of the students are there.
 这些学生当中的 500 人在这里。
 Five hundred students are here.
 500 位学生在这里。
 2）a few/several+hundred+可数名词复数
 a few/several hundred people
 几百人
 hundred 与具体数字或 a,a few, several, many 等连用时，不能加 s。
 以上为 hundred 和 hundreds of 区别。
 对于 thousand 和 million 的用法，与此类似。
*** crowd 
 crowd	英[kraʊd]
 美[kraʊd]
 n.	人群; 观众; 一伙人; 一帮人; 群众; 民众; 老百姓; 凡夫俗子;
 v.	挤满; 塞满; 使…拥挤; 涌上(心头); 涌入(脑海); 挤，靠近，挤在一旁(以致使人不舒服或紧张);
 [例句]A huge crowd gathered in a square outside the Kremlin walls
 一大群人聚集在克里姆林宫墙外的广场上。
 [其他]	第三人称单数：crowds 复数：crowds 现在分词：crowding 过去式：crowded 过去分词：crowded
*** exciting
exciting	英[ɪkˈsaɪtɪŋ]
美[ɪkˈsaɪtɪŋ]
adj.	令人激动的; 使人兴奋的;
v.	使激动; 使兴奋; 刺激; 使紧张不安; 激发; 引发; 引起;
[词典]	excite 的现在分词;
[例句]The race itself is very exciting
比赛本身非常刺激。
[其他]	原型： excite  比较级：more exciting 最高级：most exciting
*** winner
winner	英[ˈwɪnə(r)]
美[ˈwɪnər]
n.	获胜的人(或队、动物等); 优胜者; 成功者; 可能成功的人(或事物); 制胜的一记入球; 赢得比赛的一分;
[例句]She will present the trophies to the award winners
她将给获奖者颁奖。
[其他]	复数：winners
*** just
just	英[dʒʌst]
美[dʒʌst]
adv.	正好; 恰好; 正当…时; 不少于; 同样;
adj.	公正的; 正义的; 正当的; 合理的; 正直的人; 公正的人; 合适的; 恰当的;
[例句]I've just bought a new house
我刚买了栋新房子
just behind him 
紧跟在他后面
*** quickly
quickly	英[ˈkwɪkli]
美[ˈkwɪkli]
adv.	迅速地; 很快地; 不久; 立即;
[例句]The meeting quickly ended and Steve and I left the room
会议很快结束了，我和史蒂夫离开了房间。
[其他]	比较级：more quickly 最高级：most quickly

* He's awful 
** text

What's Ron Marston like, Pauline?
He's awful.
He telephoned me four times Yesterday.
and three times the day before yesterday.
He telephoned the office yesterday morning and yesterday afternoon.
My boss answered the telephone.
What did your boss say to him?
He said, "Pauline is typing letters. She can't speak to you now!"
Then I arrived home at six o'clock yesterday evening.
He telephoned again.
But I didn't answer the phone!
Did he telephone again last night?
Yes, he did.
He telephoned at nine o'clock.
What did you say to him?
I said, This is Pauline's mother.
Please don't telephone my daughter again!
Did he telephone again?
No, he didn't.

** Test
*** first

 What's Ron Marstan like, Pauline?
 He's awful.
 He telephoned me four times Yesterday,
 and three times the day before yesterday.
 He telephoned the office yesterday morning and yesterday afternoon.
 My boss answered the telephone.
 What did your boss say to him?
 He said, 'Pauline is typing letters. She can't speak to your now!'
 Then I arrived home at six o'clock yesterday evening.
 He telephoned again.
 But I didn't answer the phone!
 Did he telephone again (at \times)last night?
 Yes, he did.
 He telephoned (again \times )at nine o'clock.
 What did you say to him?
 I said. This is Pauline's mother.
 Please don't telephone my daughter again!
 Did he telephone again?
 No, he didn't.

*** Second

 What's Ron Marston like, Pauline?
 He's awful.
 He telephoned me four times yesterday,
 and three times the day before yesterday.
 He telephoned the office yesterday morning and yesterday afternoon.
 My boss answered the telephone.
 What did your boss say to him?
 He said, 'Pauline is typing letters. She can't speak to you now!'
 Then I arrived home at six o'clock yesterday evening.
 He telephoned again.
 But I didn't answer the phone!
 Did he telephone again (at)last night?
 Yes, he did.
 He telephoned again at nine o'clock.
 What did you say to him?
 I said. This is Pauline's mother.
 Please don't telephone my daughter again!
 Did he telephone again?
 No, he didn't.


*** third

 What's Ron Marston like, Pauline?
 He's awful.
 He telephoned me four times yesterday,
 and three times the day before yesterday.
 He telephoned the office yesterday morning and yesterday afternoon. 
 My boss answered the telephone.
 What did your boss say to him?
 He said. 'Pauline is typing letters. She can't speak to your now!'
 Then I arrived home at six o'clock yesterday evening.
 He telephoned again.
 But I didn't answer the phone! 
 Did he telephone again (at)last night?
 Yes, he did.
 He telephoned at nine o'clock.
 What did you say to him?
 I said. This is Pauline's mother.
 Please don't telephone my daughter again!
 Did he telephone again?
 No, he didn't.

*** Forth

 What's Ron Marston like, Pauline?
 He's awful!
 He telephoned me four times yesterday, and three times the day before yesterday.
 He telephoned the office yesterday morning and yesterday afternoon.
 My boss answered the telephone.
 What did your boss say to him?
 He said. 'Pauline is typing letters. She can't speak to you now!'
 Then I arrived home at six o'clock yesterday evening.
 He telephoned again.
 But I didn't answer the phone!
 Did he telephone again (at)last night?
 Yes, he did.
 He telephoned at nine o'clock.
 What did you say to him?
 I said, 'This is Pauline's mother.'
 Please don't telephone my daughter again!
 Did he telephone again? 
 No, he didn't.

*** Fifth 

 What's Ron Marston like, Pauline?
 He's awful.
 He telephoned me four times yesterday,
 and three times the day before yesterday.
 He telephoned the office yesterday morning and yesterday afternoon.
 My boss answered the telephone.
 What did your boss say to him?
 He said, 'Pauline is typing letters. She can't speak to you now!'
 Then I arrived home at six o'clock yesterday evening.
 He telephoned again.
 But I didn't answer the phone!
 Did he telephone again last night?
 Yes, he did.
 He telephoned at nine o'clock.
 What did you say to him?
 I said. This is Pauline's mother.
 Please don't telephone my daughter again!
 Did he telephone again?
 No, he didn't.

*** Sixth
What's Ron Marston like, Pauline?
He's awful!
He telephoned me four times yesterday, and three times the day before yesterday.
He telephoned the office yesterday morning and yesterday afternoon.
My boss answered the telephone.
What did your boss say to him?
He said, 'Puline is typing letters. She can't speak to you now!'
Then I arrived home at six o'clock yesterday evening.
He telephoned again!
But I didn't answer the phone.
Did he telephone again last night?
Yes, he did.
He telephoned again at nine o'clock.
What did you say to him?
I said. 'This is Pauline's mother.
Please don't telephone my daughter again!'
Did he telephone again?
No, he didn't.

** program 
*** 问一个人怎么样
what's somebody like?
What's this man like?
这人怎么样？
*** 一般过去时问句或否定加 did 
**** ?
What did you say to him?
What did your boss say to him?
Did he telephone again?
Did he telephone again last night?

*** 否定 did not didn't +原型
But I didn't answer the phone!
No, he didn't.

*** 一般现在时
Please don't telephone my daughter again!
What's Ron Marston like, Pauline?

*** 一般过去时
He telephoned me four times yesterday, and three times the day before yeaterday.
My boss answered the telephone.
He telephoned again.
He telephoned at nine o'clock.

* The way to King Street

Last week Mrs. Mills went to London.
She does not know London very well, and she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way.' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
The man smiled pleasantly.
He did not understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket,
and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase slowly.
'I am sorry,' he said. 'I do not speak English.'

** First
Last week Mrs. Mills went to London.
She does not know London very well, 
and she lost her way.
Suddenly(,) she saw a man near a bus stop.
'I can ask him the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
(The man smiled pleasantly.)
The man did not understand.(He did not understand English!)
He spoke German.
He was a tourist.
He smiled pleasantly.(\times)
Then he put his hand into his pocket,
and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase (very\times) slowly.
'I am sorry,' he said. 'I do not speak English.'

** second
Last week, Mrs. Mills went to London.
She does not know London very well,
and she lost her way.
Suddenly, she saw a man at a bus stop.
'I can ask his the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to the King Street, please?'
The man smiled pleasantly.
The man did not understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket.
and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase slowly.
'I am sorry,' he said. 'I don't speak English!'

** third

Last week, Mrs. Mills went to London.
She does not know London very well,
and she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to the King Street, please?'
The man smiled pleasantly.
He did not understand.
He spoke German.
He was a tourist.
Then he put his hand into his pocket, 
and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase slowly.
'I am sorry,' he said. 'I don't speak English!'

** Forth

Last week Mrs. Mills went to London.
She does not know London very well, 
and she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
The man smiled pleasantly.
He did not understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket,
and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase slowly.
'I am sorry,' he said. 'I do not speak English!'

** fifth
Last week Mrs. Mills went to London.
She does not know London very well,
so she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King street, please?'
The man smiled pleasantly.
He did not understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket, 
and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase slowly.
'I am sorry,' he said. 'I do not speak English!' 

** Sixth 
Last week Mrs. Mills went to London.
She does not know London very well, 
and she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way.' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
The man smiled pleasantly.
He did not understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket, and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase slowly.
'I am sorry,' he said. 'I do not speak English!'

** Seventh
Last week, Mrs. Mills went to London.
She does know London very well,
and she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
The man smiled pleantly.
He didn't understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket,
and took out a phrasebook.
He opened the book and found a phrase.
He read the phrase very slowly.
'I am sorry,' he said. 'I do not speak English!'

** Eighth
Last week, Mrs. Mills went to London.
She does not know London very well, and she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
The man smiled pleasantly.
He did not understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket,
and took out a phrasebook.
He opened the book and found a phrase.
He read the phrase very slowly.
'I am sorry.' he said. 'I do not speak English!'

* lesson 75 Uncomfortable shoes

Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those a month ago,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last.
But they're not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable.
But women always wear uncomfortable shoes!
像这样的鞋子你们有吗？
什么尺码的？
5 号的。
什么颜色？
黑的。
对不起，我们没有。
但是，我姐姐上个月买到了这样的一双。
好是在这儿买的吗？
不。她是在美国买的。
一个月前我们有这样的鞋。
但是现在没有了。
您能为我找一双吗？
恐怕不行。
这鞋在去年和前年时兴，而今年已不流行了。
现在流行的是这种鞋子。
这种鞋子看上去很不舒适。
的确很不舒适。
可是女人们总是穿不舒适的鞋子！

** write in

Do you have any shoes like these?
What size?
Number five.
What color?
Blank.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those a month ago,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last.
But they are not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable. 
But women always wear uncomfortable shoes!

wrong:
But my sister bought a pair last month.
Did she buy them here?
Do you get a pair for me, please?
I'm afraid I can't.
But they are not in fashion now.
But they look very uncomfortable.
But women always wear uncomfortable shoes.
correct:
But my sister bought this pair last month.
Did she buy them here?
Can you get a pair for me, please?
I'm afraid that I can't.
But they're not in fashion this year.
They look very uncomfortable.
But women always wear uncomfortable shoes!

** second test
Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those a month ago.
But we don't have any now.
Can you get a pair for me, please?
I'm afraired that I can't.
They were in fashion last year and the year before last.
But they're not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable.
But women always wear uncomfortable shoes!

** Third review

Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those a month ago,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last,
but they're not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable.
But women always 

** forth 
Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry. We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those last month,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion this year and the year before last.
But they're not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable.
But women always wear uncomfortable shoes!

** fifth
全部为对话，不加‘’了\\
Do you have any shoes like these?\\
What size?\\
Number five.\\
What color?\\
Black.\\
I'm sorry. We don't have any.\\
But my sister bought this pair last month.\\
Did she buy them here?\\
No, she bought them in the U.S.\\
We had some shoes like those a month ago,\\
but we don't have any now.\\
Can you get a pair for me, please?\\
I'm afraid that I can't.\\
They were in fashion last year and the year before last.\\
But they're not in fashion this year.\\
These shoes are in fashion now.\\
They look very uncomfortable.\\
They are very uncomfortable.\\
But women always wear uncomfortable shoes.\\

#+BEGIN_SRC LISP
(global-set-key (kbd "<f2>") 'open-init-file)
#+END_SRC 

** Sixth 

Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she bought them here?
No, she bought them in the U.S.
We had some shoes like those a month ago, 
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last.
But they're not in fashion this year.
These shoes are in fashion now. 
They look very uncomfortable. 
They are very uncomfortable.
But women always wear uncomfortable shoes!

** Seventh
Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
 We don't have any.
But my sister bought this pair last month.
Did she bought them here?
No, she bought them in the U.S.
We had some shoes like those a month ago,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last. 
But they're not in fashion this year.
These shoes are in fashion now. 
They like very uncomfortable.
They are very uncomfortable!
But women always wear uncomfortable shoes!
* lesson 77 tooth-ache

Good morning. Mr. Croft.
Good morning, nurse.
I want to see the dentist, please.
Do you have an appointment?
No, I don't.
Is it urgent?
Yes, it is.
It's very urgent.
I fell awful.
I have a terrible tooth-ache.
Can you come at 10 a.m on Monday, April 24th?
I must see the dentist now, nurse.
The dentist is very busy at the moment.
Can you come at 2 p.m?
That's very late
.
Can the dentist see me now?
I'm afraid that he can't. Mr. Croft.
Can't you wait till this afternoon?
I can wait, but my tooth-ache can't.
** test
*** First
 Good morning, Mr. Croft.
 Good morning, nurse.
 I want to see the dentist, please.
 Do you have an appointment?
 No, I don't.
 Is it urgent?
 Yes, it is.
 It's very urgent.
 I feel awful.
 I have a terrible toothache.
 Can you come at 10 a.m. on Monday, April 24th?
 Can the dentist see me now, nurse?
 I'm afraid that he can't, Mr. Croft.
 Can't you wait till this afternoon?
 I can wait, but my toothache can't!
*** Second
Good morning, Mr. Croft.
Good morning, nurse.
I want to see the dentist, please.
Do you have an appointment?
No, I don't.
Is it urgent?
Yes, it is.
It's very urgent.
I feel awful.
I have a terrible toothache.
Can you come at 10 a.m. on Monday, April, 24th?
I must see the dentist now, nurse.
The dentist is very busy at the moment.
Can you come at 2 p.m.?
That's too late.
Can the dentist see me now?
I'm afraid that he can't, Mr. Croft.
Can't you wait till this afteroon?
I can wait, but my toothache can't!

** words
*** feel
 feel	英[fiːl]
 美[fiːl]
 v.	觉得; 感到; 体会到; (通过触觉) 注意到，意识到，感觉到; 感觉到(抽象事物);
 n.	触觉; 手感; 触摸; 摸; (场所、情况等给人的) 印象，感受; 气氛;
 [例句]I am feeling very depressed
 我觉得非常沮丧。
 [其他]	第三人称单数：feels 现在分词：feeling 过去式：felt 过去分词：felt

*** write in 
 Good morning, Mr. Croft.
 Good morning, nurse.
 I want to see the dentist, please.
 Do you have an appointment?
 No, I don't.
 Is it urgent?
 Yes, it is.
 It is very urgent.
 I fell awful.
 I have a terrible tooth-ache.
 Can you come at 10 a.m. on Monday, April 24th?
 I must see the dentist now, nurse.
 The dentist is very busy at the moment.
 Can you come at 2 p.m.?
 That's very late.
 Can the dentist see me now?
 I'm afraid that he can't. Mr. Croft.
 Can't you wait till this afternoon?
 I can wait, but my tooth-ache can't.

*** Second write in.
 Good morning. Mr. Croft.
 Good morning, nurse.
 I want to see the dentist, please.
 Do you have an appointment?
 No. I don't.
 Is it urgent?
 Yes, it is.
 It's very urgent.
 I feel awful.
 I have a terrible tooth-ache.
 Can you come at 10 a.m. on Monday, April, 24th?
 I must see the dentist now, nurse.
 The dentist is very busy at the moment.
 Can you come at 2 p.m.?
 That's very late.
 Can the dentist see me now?
 I'm afraid that he can't. Mr. Croft.
 Can't you wait till this afternoon?
 I can wait, but my tooth-ache can't.
*** third write in
 Good morning, Mr. Croft.
 Good morning, nurse.
 I want to see the dentist, please.
 Do you have an appointment?
 No, I don't.
 Is it urgent?
 Yes, it is.
 It's very urgent.
 I feel awful.
 I have a terrible tooth-ache.
 Can you come at 10 a.m. on Monday, April, 24th?
 I must see the dentist now, nurse.
 The dentist is very busy now at the moment.
 Can you come at 2 p.m.?
 That's very late.
 Can the dentist see me now?
 I'm afraid that he can't, Mr. Croft.
 Can't you wait till this afternoon?
 I can wait, but my tooth-ache can't!
*** appointment
 英[əˈpɔɪntmənt]
 美[əˈpɔɪntmənt]
 n.	约会; 预约; 约定; 任命; 委任; 职务; 职位;
 [例句]His appointment to the Cabinet would please the right-wing.
 他被任命为内阁成员会让右翼党派很高兴。
 [其他]	复数：appointments
*** urgent	英[ˈɜːdʒənt]
 美[ˈɜːrdʒənt]
 adj.	紧急的; 紧迫的; 迫切的; 催促的; 急切的;
 [例句]There is an urgent need for food and water
 现在亟需食物和水。
*** awful	英[ˈɔːfl]
 美[ˈɔːfl]
 adj.	很坏的; 极讨厌的; 非常的; 很多的; 过多的; 骇人听闻的; 可怕的;
 adv.	非常; 极其;
 [例句]We met and I thought he was awful
 我们见了面，我觉得他很讨人厌。

* lesson 79 Carol's shopping list
What are you doing, Carol?
I'm making a shopping list, Tom.
What do we need?
We need a lot of thing this week.
I must go to the grocer's.
We haven't got much tea or coffee, 
and we haven't got any sugar or jam.
What about vegetables?
I must go to the green-grocer's.
We haven't got many tomatoes, 
but we've got a lot of potatoes.
I must go to the butcher's, too.
We need some meat.
We haven't got any meat at all.
Have you got any beer and wine?
No, we haven't. 
And I'm not going to get any!
I hope that you've got some money.
I haven't got much.
Well, I haven't got much either!

** test

What are you doing, Carol?
I'm making a shopping list, Tom.
What do we need?
We need a lot of thing this week.
I must go to the grocer's.
We haven't got much tea or coffee,
and we haven't got any sugar or jam.
What about vegetables?
I must go to the green-grocer's.
We haven't got many tomatoes,
but we've got a lot of potatoes.
I must go to the butcher's, too.
We need some meat.
We haven't got any meat at all.
Have we got any beer and wine?
No, we haven't.
And I'm not going to get any!
I hope that you've got some money.
I haven't got much.
Well, I haven't got much either!

** many 肯定或可数
We haven't got many tomatoes.
** much 否定或不可数
We haven't got much tea or coffee.
How much does this house cost?
I haven't got much.
Well, I haven't got much either.

** any 否定问句或不可数

and we haven't got any sugar or jam.
We haven't got any meat at all.
Have we got any beer and wine?
No, we haven't. And I'm not going to got any!

** a lot of 不可数的（钱、东西、马铃蓍） 
but we've got a lot of potatoes.
We need a lot of thing this week.
That's a lot of money.

** must 必须
I must go to the grocer's.
I must go to the green-grocer's.
I must go to the butcher's, too.
My wife must see it first.

** need
What do we need?
We need a lot of thing this week.
We need some meat.
You need a new car.
** Be going to 
Well, I'm not going to get any!
Well, you're going to have roast beef and potatoes again tonight.
We're going to leave tomorrow.
We're going to have a holiday.
Tom and I are going to have a holiday.
When are you going to have a holiday?

** get
get	英[ɡet]
美[ɡet]
v.	收到; 接到; 获得; 得到; (卖某物) 挣得;
[例句]The boys were getting bored
男孩子们开始感到厌烦。
[其他]	第三人称单数：gets 现在分词：getting 过去式：got 过去分词：got

have got 现在完成时
** 酒
*** whisky


 whisky	英[ˈwɪski]
 美[ˈwɪski]
 n.	威士忌; 一杯威士忌;
 [例句]He took a mouthful of neat whisky, and coughed.
 他喝了一口纯威士忌，咳嗽了起来。
 [其他]	复数：whiskies
 威士忌（Whisky、Whiskey），是一种由大麦等谷物酿制，在橡木桶中陈酿多年后，调配成 43 度左右的烈性蒸馏酒。英国人称之为“生命之水”。按照产地可以分为：苏格兰威士忌、爱尔兰威士忌、美国威士忌和加拿大威士忌四大类。威士忌的酿制工艺过程分为六个步骤：发芽、糖化、发酵、蒸馏、陈年、混配。
*** wine
 wine	英[waɪn]
 美[waɪn]
 n.	葡萄酒; (用植物或除葡萄以外的水果酿制的) 酒，果酒; 紫红色; 深红色;
 v.	喝酒; 请…喝酒;
 [例句]This is a nice wine.
 这种葡萄酒味道不错。
 [其他]	第三人称单数：wines 现在分词：wining 过去式：wined 过去分词：wined

*** beer 


 beer	英[bɪə(r)]
 美[bɪr]
 n.	啤酒; 一杯(或一瓶、一罐)啤酒;
 [例句]He sat in the kitchen drinking beer
 他坐在厨房里喝啤酒。
 [其他]	复数：beers
** 商店
*** grocer's
 杂货店; 食品杂货店;

*** greengrocer's 

 蔬菜水果店;

*** butcher's
 butcher's	英[ˈbʊtʃəz]
 美[ˈbʊtʃərz]
	 肉店; 屠夫

*** store
 store	英[stɔː(r)]
 美[stɔːr]
 n.	(大型) 百货商店; 商店; 店铺; 贮存物; 备用物;
 v.	贮存; 贮藏; 保存; (在计算机里) 存储; 记忆;
 [例句]Bombs were planted in stores in Manchester and Blackpool.
 炸弹被安放在曼彻斯特和布莱克浦的几家商店里。
 [其他]	第三人称单数：stores 复数：stores 现在分词：storing 过去式：stored 过去
 分词：stored

*** stove 火炉

*** market
 market	英[ˈmɑːkɪt]
 美[ˈmɑːrkɪt]
 n.	集市; 市场; 商场; 交易; 买卖; 交易量; 商品的销售地; 行销地区; 消费群体;
 v.	推销; 促销;
 [例句]He sold boots on a market stall.
 他在集市上摆摊卖靴子。
 [其他]	第三人称单数：markets 复数：markets 现在分词：marketing 过去式：marketed 过去分词：marketed

*** supermarket
 英[ˈsuːpəmɑːkɪt]
 美[ˈsuːpərmɑːrkɪt]
 n.	超级市场; 超市;
 [例句]Most of us do our food shopping in the supermarket
 我们大多数人去超市购买食品。
 [其他]	复数：supermarkets


* Lesson 81 Roast beef and potatoes
Hi, Carol! Where's Tom?
He's upstairs.
He's having a bath.
Tom! Yes?
Sam's here.
I'm nearly ready.
Hello, Sam.
Have a cigarette.
No, thanks, Tom.
Have a glass of whisky then.
OK. Thanks.
Is dinner ready, Carol?
It's nearly ready.
We can have dinner at seven o'clock.
Sam and I had lunch together today.
We went to a restaurant.
What did you have?
We had roast beef and potatoes.
Oh!
What's the matter, Carol?
Well, you're going to have roast beef and potatoes again tonight.
** test
*** first 
 err:
 Hi, Carol.
 No,thanks. Tom.
 OK, thanks.
 Correct:
 Hi, Carol!
 No, thanks, Tom.
 OK. Thanks.
*** Second
Hi, Carol! Where's Tom?
He's upstairs.
He's having a bath.
Tom! Yes?
Sam's here.
I'm nearly ready.
Hello, Sam.
Have a cigarette.
No, thanks, Tom.
Have a glass of whisky then.
Ok. Thanks.
Is dinner ready, Carol?
It's nearly ready.
We can have dinner at seven o'clock.
Sam and I had lunch together today.
We went to a restaurant.
What did you have?
We had roast beef and potatoes.
Oh!
What's the matter, Carol?
Well, you're going to have roast beef and potatoes again tonight!

** words
*** ask where
 Where's Tom?
*** ask what
 What did you have?
*** have eat meal ett.
 Have a cigarette.
 Have a glass whisky then.
 We can have dinner at seven o'clock.
 Sam and I had lunch together today.
 We had roast beef and potatoes.
 Well, you're going to have roast beef and potatoes again tonight.
*** ready
 I'm nearly ready.
 It's nearly ready.
*** 标点
 No,thanks, Tom.
 OK. Thanks.
 Oh!
* Lesson 83 Holiday
Hello, Sam. Come in.
Hi, Sam.
We're having lunch.
Do you want to have lunch with us?
No, thank you. Tom.
I've already had lunch.
I had a lunch at half past twelve.
Have a cup of coffee then.
I've just had a cup, thank you.
I had one after my lunch.
Let's go into the living room, Carol.
We can have our coffee there.
Excuse the mess, Sam.
This room's very untidy.
We're packing our suitcases.
We're going to leave tomorrow.
Tom and I are going to have a holiday.
Aren't you lucky!
When are you going to have a holiday, Sam?
I don't know.
I've already had my holiday this year.
Where did you go?
I stayed at home!
** 现在进行时
We're having lunch.
We're packing our suitcases.
** 打算（将来时）
We're going to leave tomorrow.
Tom and I are going to have a holiday.
When are you going to have a holiday, Sam?
** 正在完成时 have +过去分词
I've already had lunch.
I've just had a cup, thank you.
I've already had my holiday this year.
** 一般过去时
I had a lunch at half past twelve.
I had one after my lunch.
Where did you go?
I stayed at home.
** 一般现在时
Do you want to have lunch with us?
Have a cup of coffee then.
Let's go into the living room, Carol.
We can have our coffee there.
This broom's very untidy.
I don't know.

** test

Hello, Sam. Come in.
Hi, Sam. 
We're having lunch.
Do you want to have lunch with us?
No, thank you. Tom.
I've already had lunch.
I had a lunch at half past twelve.
Have a cup of coffee then.
I've just had a cup, thank you.
I had one after my lunch.
Let's go into the living room, Carol.
We can have our coffee there.
Excuse the mess, Sam.
This room's very untidy.
We're packing our suitcases.
We're going to leave tomorrow.
Tom and I are going to have a holiday.
Aren't you lucky!
When are you going to have a holiday, Sam?
I don't know.
I've already had my holiday this year.
Where did you go?
I stayed at home!

* Lesson 85 Pairs in the spring 

Hello, Ken.

Hi, George.

Have you just been to the cinema?

Yes, I have.

What's on?

'Pairs in the spring.'

Oh, I've already seen it.

I saw it on television last year.

It's an old film, but it's very good.

Pairs is a beautiful city.

I've never been there.

Have you ever been there, Ken? 

Yes, I have. I was there in spring. 

Pairs in the spring, eh?

It was spring,

but the weather was awful.

It rained all the time.

Just like London! 

** 现在完成时
Have you just been to the cinema?
Oh, I've already seen it.
I've never been there.
Have you ever been there, Ken?

** 一般过去时
I saw it on television last year.
I was there in April.
It was spring, but the weather was awful.
It rained all the time.

** 一般现在时
What's on?
It's an old film, but it's very good.
Pairs is a beautiful city.
Just like London.

** Test
Hello, Ken.
Hi, George.
Have you just been to the cinema?
Yes, I have.
What's on?
"Pairs in the spring."
Oh, I've already seen it.
I saw it on television last year.
It's an old film, but it's very good.
Pairs is a beautiful city.
I've never been there.
Have you ever been there, Ken?
Yes, I have. 
I was there in April.
Pairs in the spring, eh?
It was sprint, 
but the weather was awful.
It rained all the time.
Just like London!

err: George George

* lesson 87 crash
/Is/ my car ready yet?

I don't know, sir.

What's the number of your car?

It is LIZ 312G.
When did you bring it to us?
I brought here three days ago.
Oh,yes. I remember now.
Have your mechanics finished yet?
No, they're still working on it.
Let's go into the garage and have a look at it.
Isn't that your car?
Well, it was my car.
Didn't you have a crash? 
That's right.
I drove it into a lamp-post.
Can your mechanics repair it?
Well, they're trying to repair it, sir.
But to tell you the truth, 
you need a new car.

** 现在完成时（特殊）
Is my car ready yet?
Have your mechanics finished yet?
Didn't you have a crash?

** 一般过去时
I brought here three days ago.
It was my car.
I drove it into a lamp-post.
** 现在进行时
No, they're still working on it.
Well, they're trying to repair it, sir.
** Can
Can your mechanics repair it?
** test
Is my car ready yet?
I don't know, sir.
What's the number of your car?
It is LFZ 312G.
When did you bring it to us?
I bought here three days ago.
Oh, yes. I remember now.
Have your mechanics finished yet?
No, They're still working on it.
Let's go into the garage and have a look at it.
Isn't that your car?
Well, it was my car.
Didn't you have a crash?
That's right.
I drove it into a lamp-post.
Can your mechanics repair it?
Well, they're trying to repair it, sir.
But tell you the truth,
you need a new car.

err:
Is my car ready yet?
wrong:Is my car already yet.

I don't know, sir.
wrong: I don't know.

Well, they're trying to repair it, sir.
wrong: Well, they're trying to repair it, sir.
服务人员说话客气。加 sir.

Didn't you have a crash.
wrong:
Have you have a crash.

* Lesson 89 For Sale
Good afternoon.
I believe that this house is for sale.
That's right.
May I have a look at it, please?
Yes, of course.
Come in.
How long have you lived here?
I've live here for twenty years.
Twenty years!
That's a long time.
Yes, I've been here since 1976.
Then why do you want to sell it?
Because I've just retired.
I want to buy a small house in the country.
How much does this house cost?
\pounds68500.
That's a lot of money.
It's worth every penny of it.
Well, I like the house,
but I can't decide yet.
My wife must see it first.
Women always have the last word.
** Test
Good afternoon.
I believe that this house is for sale.
That's right.
May I have a look at it, please?
Yes, of course.
Come in.
How long have you lived here?
I've live here for twenty years.
That's a long time.
Yes, I've been here since 1976.
Then why do you want to sell it?
Because I've just retired.
I want to buy a small house in the country.
How much does this house cost?
\pounds68500.
That's a lot of money.
It's worth every penny of it.
Well, I like the house, 
but I can't decide yet.
My wife must see it first.
Women always have the last word.

err:
I think /that/ this house is for sale.
/Yes/, of course.
/but/ it's worth every penny of it.

** Test
Good afternoon.
I believe that this house is for sale.
That's right.
May I have a look at it, please?
Yes, of course.
Come in.
How long have you lived here?
I've lived here for twenty years.
Twenty years!
That's a long time.
Yes, I've been here since 1976.
Then why do you want to sell it?
Because I've just retired.
I want to buy a small house in the country.
How much does this house cost?
\pounds68500.
That's a lot of money.
It's worth every penny of it.
Well, I like the house, 
but I can't decide yet.
My wife must see it first.
Women always have the last word.

* Lesson 91 Poor Ian
Has Ian sold his house yet?
Yes, he has.
Has he moved to his new house yet? 
No,not yet.
He's still here.
He's going to move tomorrow.
When? Tomorrow morning.
No. Tomorrow afternoon.
I'll miss him.
He has always been a good neighbour.
He's a very nice person.
We'll all miss him.
When will the new people move into this house?
I think that they'll move in the day after tomorrow.
Will you see Ian today, Jenny?
Yes, I will.
Please give him my regards.
Poor Ian!
He didn't want to leave this house.
No, he didn't want to leave,
but his wife did.
** test

*** First
 Has Ian sold his house yet?
 Yes, he has.
 He sold it last week.
 Has he moved to his new house yet?
 No, not yet.
 He's still here.
 He's going to move tomorrow.
 When? Tomorrow morning.
 No. Tomorrow afternoon.
 I'll miss him. 
 He has always been a good neighbour.
 He's a very nice person.
 We'll miss him.
 When will the new people move into this house?
 I think that they'll move in the day after tomorrow.
 Will you see Ian, today?
 Yes, I will.
 Please give him my regards.
 Poor Ian!
 He didn't want to leave this house.
 No,he didn't want to leave, 
 but his wife did.

 err:
 Will you see Ian today, Jenny?
 wrong
 Will you see Ian, today?

 No, he didn't want to leave,
 wrong

 no, he didn't want to

*** Second 
Has Ian sold his house yet?
Yes, he has.
Has he moved to his new house yet?
No, not yet.
He's still here.
He's going to move tomorrow.
When? Tomorrow morning.
No. Tomorrow afternoon.
I'll miss him.
He has always been a good neighboour.
He's very nice person.
We'll miss him.
When will the people move into this house?
I think that they'll move in the day after tomorrow.
Will you see Ian today,Jenny?
Yes, I will.
Please give him my regards.
Poor Ian!
He didn't want to leave this house.
No, he didn't want to leave,
but his wife did!


* Lesson 93
Nigel is our new next-door neighbour.
He's a pilot.
He was in the R.A.F.
He will fly to New York next month.
The month after next he'll fly to Tokyo.
At the moment, he's in Madrid.
He flew to Spain a week ago.
He'll return to London the week after next.
He's only forty-one years old,
and he has already been to nearly every country in the world.
Nigel is a very lucky man.
But his wife isn't very lucky.
She usually stays at home!
** words
*** pilot
pilot	英[ˈpaɪlət]
美[ˈpaɪlət]
n.	飞行员; (飞行器) 驾驶员; 领航员; 引水员; 领港员; (电视的) 试播节目;
v.	驾驶(飞行器); 领航(船只); 引导; 使通过(尤指复杂的地方或系统); 试点; 试行;
adj.	试验性的; 试点的;
[例句]He spent seventeen years as an airline pilot.
他当了 17 年的航空公司飞行员。
[其他]	第三人称单数：pilots 复数：pilots 现在分词：piloting 过去式：piloted 过
去分词：piloted
*** Tokyo
Tokyo	英[ˈtəʊkiəʊ]
美['tokjo]
n.	东京;
[例句]On my way to New York, I stopped over in Tokyo for two days.
我在去纽约的途中在东京停了两天。
*** Madrid
Madrid	英[məˈdrɪd]
美[məˈdrɪd]
n.	马德里（西班牙首都）;
[例句]Tonight's clash between Real Madrid and Arsenal is being heralded as the match of the season.
今晚皇家马德里队和阿森纳队之间的对决被称为本赛季最重要的比赛。
*** Spain
Spain	英[speɪn]
美[speɪn]
n.	西班牙;
[例句]The game was transmitted live in Spain and Italy
这场比赛在西班牙和意大利进行了现场直播。
*** lucky
ucky	英[ˈlʌki]
美[ˈlʌki]
adj.	有好运的; 运气好的; 幸运的; 好运带来的; 带来好运的;
[例句]I am luckier than most. I have a job
我比大部分人幸运。我有份工作。
[其他]	比较级：luckier 最高级：luckiest
** Test
*** First
Nigel is our new next-door neighbour.
He's a pilot. 
He was in the R.A.F.
He will fly to New York next month.
The month after next he'll fly to Tokyo.
At the moment, he's in Madrid.
He flew to Spain a week ago.
He's return to London the week after the next.
He's only forty-one years old, 
and he has already been to nearly every country in the world.
Nigel is a very lucky man.
But his wife isn't very lucky.
She usually stays at home!

* Footnotes

[fn:10]conversation
英[ˌkɒnvəˈseɪʃn]
美[ˌkɑːnvərˈseɪʃn]
n.	(非正式) 交谈，谈话;
[例句]He's a talkative guy, and I struck up a conversation with him
他是一个健谈的人，于是我开始和他攀谈起来。
[其他]	复数：conversations 

[fn:9]subject
英[ˈsʌbdʒɪkt , səbˈdʒekt]
美[ˈsʌbdʒɪkt , səbˈdʒekt]
n.	主题; 题目; 话题; 题材; 问题; 学科; 科目; 课程; 表现对象; 绘画(或拍摄)题材;
adj.	可能受…影响的; 易遭受…的; 取决于; 视…而定; 受…支配; 服从于;
v.	使臣服; 使顺从; (尤指) 压服;
[例句]It was I who first raised the subject of plastic surgery.
是我第一个提到整形手术这个话题的。
[其他]	第三人称单数：subjects 复数：subjects 现在分词：subjecting 过去式：subjected 过去分词：subjected 

[fn:8]favorite	英[ˈfeɪvərɪt]
美[ˈfeɪvərɪt]
adj.	特别受喜爱的;
n.	特别喜爱的人（或物）；受宠的人；得到偏爱的人; (国王的) 宠臣；亲信，心腹; (尤指马) 最有希望获胜者;
[例句]I took the title of this chapter from one of my favorite books.
我这章的标题来自我最喜欢的一本书。
[其他]	比较级：more favorite 最高级：most favorite 复数：favorites
 

[fn:7][V] 落（下） 
to go down below the horizon
We sat and watched the sun setting.
我们坐着看太阳渐渐落下去。
see also sunset n. (1)
反义词： rise 

[fn:6]seasons	英[ˈsiːznz]
美[ˈsiːznz]
n.	季; 季节; (热带地区的) 旱 / 雨季; (一年中开展某项活动的) 季节，旺季;
v.	加调料调味; 加作料;
[词典]	season 的第三人称单数和复数;
[例句]The prospect of relegation is a comedown for a club that finished second two seasons ago.
对于两个赛季前排名第二的俱乐部来说，竟然有降级之虞真是太落魄了。
[其他]	原型： season
 

[fn:5]wet	英[wet]
美[wet]
adj.	潮的; 湿的; 潮湿的; 有雨的; 下雨的; 尚未干的;
v.	使潮湿; 把…弄湿;
n.	雨天; 雨; 液体; (尤指) 水; 保守党温和派成员;
[例句]He towelled his wet hair
他用毛巾擦干湿发。
[其他]	比较级：wetter 最高级：wettest 第三人称单数：wets 复数：wetter 现在分词：
wetting 过去式：wetted 过去分词：wetted
 

[fn:4]windy	英[ˈwɪndi]
美[ˈwɪndi]
adj.	多风的; 风大的; 当风的; 受大风吹的; 夸夸其谈的; 空话连篇的; 空洞无物的;
[例句]It was windy and Jake felt cold.
风很大，杰克觉得很冷。
[其他]	比较级：windier 最高级：windiest
 

[fn:3]mild	英[maɪld]
美[maɪld]
adj.	温和的; 和善的; 不严厉的; 和煦的; 不强烈的; 轻微的;
n.	淡味啤酒;
[例句]Teddy turned to Mona with a look of mild confusion
泰迪表情略带困惑地向莫娜求助。
[其他]	比较级：milder 最高级：mildest
 

[fn:2]climate	英[ˈklaɪmət]
美[ˈklaɪmət]
n.	气候; 气候区; 倾向; 思潮; 风气; 环境气氛;
[例句]The economic climate remains uncertain.
经济形势依然不确定。
[其他]	复数：climates
 

[fn:1]pleasant	英[ˈpleznt]
美[ˈpleznt]
adj.	令人愉快的; 可喜的; 宜人的; 吸引人的; 友好的; 和善的; 文雅的;
[例句]I've got a pleasant little apartment
我有一套舒适的小公寓。
[其他]	比较级：pleasanter 最高级：pleasantest
 
