
#+TITLE: 英语学习笔记
#+AUTHOR: 泰山职业技术学院   夏乐斋
#+OPTIONS: H:3
#+OPTIONS: toc:2 (目录中只显示二级标题)
* Mrs. Smith's kitchen
** Test
Mrs. Smith's kitchen is small.
There is a refrigerator in the kitchen.
The refrigerator is white. 
It is on the right.
There is an electric cooker in the kitchen.
The cooker is blue.
It is on the left.
There is a table in the middle of the room.
There is a bottle on the table.
The bottle is empty.
There is a cup on the table, too.
The cup is clean.
** Words
*** electric
electric | BrE ɪˈlɛktrɪk, AmE əˈlɛktrɪk |
 A. adjective
 ① (using electricity) 用电的 yòng diàn de
  ▸ an electric light 电灯
  ▸ an electric toothbrush 电动牙刷
 ② (relating to electricity) 电的 diàn de
 ③ figurative (emotionally charged) 紧张刺激的 jǐnzhāng cìjī de
  ▸ the atmosphere is electric 气氛很热烈
 B. electrics plural noun British informal 电路 diànlù
  ▸ to check the electrics 检查电路
*** middle
middle | BrE ˈmɪd(ə)l, AmE ˈmɪdl |
 A. noun
 ① (centre) 中间 zhōngjiān
  ▸ in the middle of the room/front page 在屋子的中间/在头版的正中
  ▸ the middle of a city/region; 城市/地区的中心
  ▸ the middle of May 5 月中旬
  ▸ in the middle of the night 在半夜时分
  ▸ in the middle of the nineteenth century 在 19 世纪中叶
  ▸ not cooked in the middle 没有熟透
  ▸ in the middle of the class 位居班级的中游
  ▸ to be caught in the middle of sth; 被卡在某物中间 figurative 被卷入某事中 bèi juǎnrù mǒu shì zhōng
  ▸ to be in the middle of sth/doing sth; 正忙于某事/做某事
  ▸ to be in the middle of a crisis 正处于危机中
  ▸ in the middle of nowhere informal 在偏远的地方
  ▸ to split sth down the middle 从中间切开 ‹object› 平分 píngfēn ‹bill, sum of money› 分担 fēndān ‹work›
  ▸ to split the party down the middle «issue, policy» 使政党分裂为两派
  ▸ to knock sb into the middle of next week informal 把某人打得不省人事
 ② informal (waist) 腰部 yāobù
  ▸ to grab sb round the middle 拦腰抱住某人
  ▸ we were up to our middles in water 我们站在齐腰深的水中
 B. adjective attributive
 ① (central) 中间的 zhōngjiān de ‹part, road›
  ▸ to stare into middle space 凝视半空
  ▸ middle and eastern Europe 中东欧
  ▸ to be in one's middle fifties 在 55 岁左右
  ▸ a middle child 排行居中的孩子
  ▸ a middle way between two extremes 折中的办法
  ▸ to steer or take a middle course 取中庸之道
 ② (average) 中等的 zhōngděng de ‹price, size, quality
*** empty
empty | BrE ˈɛm(p)ti, AmE ˈɛm(p)ti |
 A. adjective
 ① (lacking contents) 空的 kōng de ‹container, vehicle, shelf›; 空白的 kòngbái de ‹page›; 未放物品的 wèi fàng wùpǐn de ‹table›; 空着的 kōngzhe de ‹hand(s)›
  ▸ to be empty of sth 没有某物
 ② (lacking people) 无人的 wúrén de ‹room, building, street›; 未载人的 wèi zàirén de ‹vehicle, plane, boat›; 空缺的 kòngquē de ‹post›; 无人做的 wúrén zuò de ‹job›
  ▸ to stand empty «house, office» 空无一人
 ③ (lacking food) 饿的 è de
  ▸ on an empty stomach 空着肚子
 ④ (insincere, meaningless) 空洞的 kōngdòng de ‹words, argument, promises›; 虚张声势的 xū zhāng shēngshì de ‹threats›; 不现实的 bù xiànshí de ‹dreams›
  ▸ empty of meaning 没有意义
 ⑤ (purposeless) 空虚的 kōngxū de ‹life›; 空闲的 kòngxián de ‹hours, days, weeks›
 ⑥ predicative (exhausted) 疲乏的 pífá de
  ▸ to feel empty 感觉疲乏
 B. transitive verb
 ① (remove contents) 清空 qīngkōng ‹container, pool, cupboard›; 掏空 tāokōng ‹envelope, purse, pocket›; 腾空 téngkōng ‹vehicle, ship›
 ② (pour) 倒空 dàokōng
  ▸ to empty sth into/on to sth; 把…全部倒进某物里/倒在某物上 ‹contents, water, rubbish›
 ③ (clear) 将…清场 jiāng… qīngchǎng ‹building, cinema, shop, street, bus›
 C. intransitive verb
 ① (discharge contents) «container, tank, bin» 腾空 téngkōng
 ② (pour out) 倒空 dàokōng
  ▸ to empty into/on to sth; «contents, sand, rubbish» 全部倒入某物/倒在某物上
 ③ (flow) 流入 liúrù
  ▸ to empty into sth; «river, stream, water» 流入某处
 ④ (be vacated) «building, theatre, shop, street, bus» 被清场 bèi qīngchǎng
 D. empties plural noun British informal (bottles) 空瓶 kōngpíng ; (glasses) 空杯 kōngbēi PHRASAL VERB empty out:
 A. transitive verb [empty out sth, empty sth out] (pour out) 倒空 dàokōng ; (clear) 清空 qīngkōng
  ▸ to empty water out of one's boots; 把水从靴子里倒出来
  ▸ to empty one's pockets out on to the table; 把衣袋里的东西全掏到桌子上
 B. intransitive verb
 ① (leave a place) «people» 全部撤离 quánbù chèlí
 ② (pour out of a container) «contents» 倒出 dàochū
  ▸ the sand emptied out of the bag; 沙子从袋子里倒了出来
 ③ (be vacated) «building, bus» 被清场 bèi qīngchǎng
*** clean
clean | BrE kliːn, AmE klin |
 A. adjective
 ① (not dirty) 干净的 gānjìng de
  ▸ clean air 清洁的空气
  ▸ a clean wound 未感染的伤口
  ▸ to lick one's plate clean literal 把盘子舔干净 figurative 吃光盘中的食物 chīguāng pán zhòng de shíwù
  ▸ my hands are clean literal 我的手很干净 figurative 我是清白的 wǒ shì qīngbái de
 ② (attentive to hygiene) 爱干净的 ài gānjìng de
  ▸ it's not very clean to drink out of somebody else's glass 用别人的杯子喝不太卫生
 ③ Ecology 无污染的 wúwūrǎn de ‹energy›
  ▸ a clean fuel 清洁燃料
 ④ (not marked) 空白的 kòngbái de ‹sheet of paper, blackboard›
 ⑤ (not obscene) 不下流的 bù xiàliú de ‹joke, comedian, act›
  ▸ the evening was all good clean fun 这台晚会文明有趣
 ⑥ (unsullied) 清白的 qīngbái de
  ▸ a clean driving licence 无违章记录的驾照
  ▸ I've checked him out: he's clean informal 我已经查过他了，他没有前科
 ⑦ slang (without illicit property) 没有违禁品的 méiyǒu wéijìnpǐn de
  ▸ I've searched him, and he's clean 我搜了他的身，他没有携带违禁品
 ⑧ slang (no longer addicted) 不再吸毒的 bù zài xīdú de
 ⑨ Sport (following rules) 守规则的 shǒu guīzé de
  ▸ a clean tackle 正当的阻截
 ⑩ (done smoothly and skilfully) 干净利落的 gānjìng lìluo de ‹hit, blow, movement›
 ⑪ (with smooth edge) 边缘平整的 biānyuán píngzhěng de ‹cut, fracture›
  ▸ a clean break Medicine 整齐的骨折 figurative 彻底的决裂 chèdǐ de juéliè
 ⑫ (elegant, neat) 流畅匀称的 liúchàng yúnchèn de ‹curves, shape, profile›
  ▸ the car's clean lines 那辆车流畅的线条
 B. noun 清扫 qīngsǎo
  ▸ to give sth a clean; 清扫某物
  ▸ to give the room a clean 打扫房间
 C. adverb 完全地 wánquán de
  ▸ to come clean (with sb) (about sth) （向某人）和盘托出（某事）
  ▸ I've got to come clean with you: I was the one who told him 我得跟你说实话：是我告诉他的
  ▸ the thief got clean away informal 小偷跑得没影了
  ▸ I'd clean forgotten about her birthday informal 我把她的生日忘得一干二净
 D. transitive verb
 ① (remove dirt from) 把…弄干净 bǎ… nòng gānjìng
  ▸ to clean the room 打扫房间
  ▸ to clean the blackboard 擦黑板
  ▸ to clean oneself 把身体洗干净 bǎ shēntǐ xǐ gānjìng
  ▸ she cleaned the dirt from her fingernails 她除掉了指甲里的污垢
  ▸ to have a suit (dry-)cleaned 把西服拿去（干）洗
 ② Cooking «cook» 清除…的内脏 qīngchú… de nèizàng ‹chicken, fish›
 E. intransitive verb
 ① (do housework) 打扫 dǎsǎo
 ② (become clean) 变干净 biàn gānjìng
  ▸ these brass handles don't clean very easily 这些黄铜把手不容易弄干净 PHRASAL VERBS clean down: transitive verb [clean sth down, clean down sth] 把…清扫干净 bǎ… qīngsǎo gānjìng
  ▸ to clean down the walls 把墙壁擦洗干净 clean off
 A. transitive verb [clean sth off, clean off sth] 清除 qīngchú ‹writing, marks, graffiti›
  ▸ I've got to clean the mud off the car 我得把车上的泥擦掉
 B. intransitive verb «stain» 被除掉 bèi chúdiào
  ▸ this mark won't clean off 这块污渍擦不掉 clean out: transitive verb
 ① [clean sth out, clean out sth] (cleanse thoroughly) 把…的内部清扫干净 bǎ… de nèibù qīngsǎo gānjìng ‹oven, toilet›
  ▸ you need to clean out your ears! 你该掏一下耳朵了！
 ② [clean sb out, clean out sb] informal (leave penniless) 把…的钱花光 bǎ… de qián huā guāng ‹person›
  ▸ the new car's cleaned me out of all my savings 这辆新车花光了我的全部积蓄
 ③ [clean sb/sth out, clean out sb/sth] informal (rob) «thief, swindler» 把…洗劫一空 bǎ… xǐjié yī kōng ‹person, house›
  ▸ the burglars cleaned her out of all her jewellery 窃贼把她的珠宝洗劫一空 clean up
 A. [clean sth up, clean up sth] transitive verb
 ① (get rid of) 清除 qīngchú ‹mess, remains›
  ▸ to clean the rubbish up off or from the floor 把地板上的垃圾清走
 ② (remove crime, corruption from) 清理整顿 qīnglǐ zhěngdùn ‹city, streets, local government›
 ③ informal (make less obscene, violent) 使…变得纯洁 shǐ… biàn de chúnjié ‹TV, programme›
  ▸ to clean up one's act literal «comedian» 使表演文雅 figurative «person» 洁身自好 jié shēn zì hào
 B. [clean sb/sth up, clean up sb/sth] transitive verb (remove dirt from) 把…弄干净 bǎ… nòng gānjìng
  ▸ to clean up the kitchen 把厨房打扫干净
  ▸ to clean oneself up 把身体洗干净 bǎ shēntǐ xǐ gānjìng
 C. intransitive verb
 ① (remove dirt) 打扫干净 dǎsǎo gānjìng
 ② (tidy up) 整理 zhěnglǐ
  ▸ to clean up after sb; 跟在某人后面收拾
 ③ (wash oneself) 把身体洗干净 bǎ shēntǐ xǐ gānjìng
 ④ informal (make profit) «entrepreneur, gambler, film» 赚大钱 zhuàn dàqián
  ▸ to clean up on sth; 因…赚大钱 ‹deal, 
** Test
*** First
Mrs. Smith's kitchen is small.
There is a refrigerator in the kitchen.
The refrigerator is white.
It is on the right.
There is an electric cooker in the kitchen.
The cooker is blue.
It is on the left.
There is a table in the middle of the room.
There is a bottle on the table.
The bottle is empty.
There is a cup on the table, too.
The cup is clean.
* Mrs. Smith's living room
** Text
Mrs. Smith's living room is large.
There is a television in the room.
The television is near the window.
There are some magazines on the television.
There is a table in the room.
There are some newspapers on the table.
There are some armchairs in the room.
The armchairs are near the table.
There is a stereo in the room.
The stereo is near the door.
There are some books on the stereo.
There are some pictures in the room.
The pictures are on the wall.
** Words
*** television
television | BrE ˈtɛlɪvɪʒ(ə)n,tɛlɪˈvɪʒ(ə)n, AmE ˈtɛləˌvɪʒən | noun
 ① uncountable (medium) 电视 diànshì
  ▸ to watch television 看电视
  ▸ to be shown live on television 在电视上直播
  ▸ a television interview/personality 电视访谈节目/电视圈名人
 ② uncountable (programmes) 电视节目 diànshì jiémù
  ▸ how much television do you watch every day? 你每天看多长时间电视？
 ③ countable (set) 电视机 diànshìjī
  ▸ to turn the television on/off 打开/关上电视
 ④ uncountable (activity, profession) 电视行业 diànshì hángyè
  ▸ she works in television 她从事电视行业
*** magazine
magazine | BrE maɡəˈziːn, AmE ˈmæɡəˌzin,ˌmæɡəˈzin | noun
 ① (publication) 杂志 zázhì
  ▸ a literary magazine 文学期刊
 ② (on radio, TV) (also magazine programme) 专题节目 zhuāntí jiémù
 ③ (of gun) 弹仓 dàncāng
 ④ (store for arms, ammunition) 弹药库 dànyàokù
*** newspaper
newspaper | BrE ˈnjuːzpeɪpə,ˈnjuːspeɪpə, AmE ˈn(j)uzˌpeɪpər | noun
 ① countable Journalism 报纸 bàozhǐ
  ▸ to publish/edit a newspaper 出版/编辑报纸
  ▸ to work for a newspaper 为一家报社工作
  ▸ the Sunday newspapers 星期日周报
  ▸ a newspaper reporter 报社记者 bàoshè jìzhě
  ▸ a newspaper editor/article 报纸编辑/文章
 ② uncountable (paper) 旧报纸 jiù bàozhǐ
  ▸ to be wrapped in newspaper 包在报纸里
*** armchair
armchair | BrE ɑːmˈtʃɛː,ˈɑːmtʃɛː, AmE ˈɑrmˌtʃɛr | noun
 ① (chair) 扶手椅 fúshǒuyǐ
 ② before noun (lacking practical experience) 无实际经验的 wú shíjì jīngyàn de
  ▸ an armchair general 纸上谈兵的将军
  ▸ an armchair traveller 坐而神游的旅行者
*** stereo
stereo | BrE ˈstɛrɪəʊ,ˈstɪərɪəʊ, AmE ˈstɛrioʊ | noun
 ① uncountable (sound) 立体声 lìtǐshēng
  ▸ to broadcast in stereo 用立体声广播
 ② countable plural stereos (system) 立体声音响 lìtǐshēng yīnxiǎng
*** wall
wall | BrE wɔːl, AmE wɔl |
 A. noun
 ① (side of room, building) 墙壁 qiángbì
  ▸ an inside/outside wall 内墙/外墙
  ▸ the front/back wall 前墙/后墙
  ▸ these four walls 这四堵墙 [尤指私密的处所]
  ▸ what I'm telling you should remain within these four walls 我现在跟你说的话不得外传
  ▸ to drive sb up the wall informal 逼得某人受不了
  ▸ to go up the wall informal (become exasperated) 非常恼火 (become crazy) 发狂
  ▸ to be a fly on the wall figurative 暗中旁观
  ▸ to be off the wall informal «person, idea» 滑稽古怪
  ▸ walls have ears proverb 隔墙有耳
  ▸ to push or drive sb/sth to the wall informal (cause problems for) 使某人/某事物陷入困境 (bankrupt) 使某人/某机构破产
  ▸ to have sb up against the wall 使某人走投无路
  ▸ to go to the wall informal «company» 破产
  ▸ to have one's back to the wall informal 被逼得没有退路
  ▸ a wall clock 挂钟
  ▸ wall tiles/lighting 壁砖/墙照明
 ② (barrier) 围墙 wéiqiáng
  ▸ to build a wall 筑围墙
  ▸ the walls of the city 城墙
 ③ (side of hollow structure) 内壁 nèibì
 ④ (outer layer) [器官或细胞的] 外壁 wàibì
 ⑤ (of tyre) 轮胎壁 lúntāibì
 ⑥ (in football) 人墙 rénqiáng
 ⑦ (large number) (of people) 人墙 rénqiáng ; (of things) 墙状物 qiángzhuàngwù
  ▸ a wall of protesters 抗议者的人墙
  ▸ the cliffs form a steep wall 悬崖像墙一样陡峭
  ▸ a wall of water/flame 水幕/火墙
 ⑧ (non-physical barrier) 隔阂 géhé
  ▸ a wall of suspicion/hostility; 怀疑/敌意的隔阂
 B. transitive verb 用墙围住 yòng qiáng wéizhù ‹area›PHRASAL VERBS wall in transitive verb [wall sb/sth in, wall in sb/sth] 围住 wéizhù ‹person, area›
  ▸ the lagoon is walled in by tall cliffs 潟湖被高耸的悬崖环绕着 wall off transitive verb [wall sth off, wall off sth]
 ① (block off) 用墙把…封死 yòng qiáng bǎ… fēngsǐ ‹area, room›
 ② (separate) 用墙把…隔开 yòng qiáng bǎ… gékāi ‹area, land›wall up: transitive verb
 ① [wall sth up, wall up sth] (block up) 用墙把…堵住 yòng qiáng bǎ… dǔzhù ‹doorway, fireplace›
 ② [wall sb up, wall up sb] (imprison) 把…关在高墙后 bǎ… guān zài gāo qiáng hòu
 ‹prisoner›
** Test
*** First
Mrs. Smith's living room
Mrs. Smith's living is large.
There is a television in the room.
The television is near the window.
There are some magazines on the television.
There is a table in the room.
There are some newspapers on the table.
There are some armchairs in the room.
The armchairs are near the table.
There is a stereo in the room.
The stereo is near the door.
There are some books on the stereo.
There are some pictures in the room.
The pictures are on the wall.
*** Second
Mrs. Smith's living room is large.
There is a television in the room.
The television is near the window.
There are some magazines on the television.
There is a table in the room.
There are some newspapers on the table. 
There are some armchairs in the room.
There armchairs are near the table.
There is a stereo in the room.
The stereo is near the door.
There are some books on the stereo.
There are some pictures in the room.
The pictures are on the wall.
*** Third
Mrs. Smith's living room
Mrs. Smith's living room is large.
There is a television in the room.
The television is near the window.
There are some magazines on the television.
There is a table in the room.
There are some newspapers on the table.
There are some armchairs in the room.
The armchairs are near the table. There is a stereo in the room.
The stereo is near the door.
There are some books on the stereo.
There are some pictures in the room.
The pictures are on the wall.
*** Forth
Mrs. Smith's living room
Mrs. Smith's living room is large.
There is a television in the room.
The television is near the window.
There are some magazines on the television.
There is a table in the room.
There are some newspapers on the table.
There are some armchairs in the room.
The armchairs are near the table.
There is a stereo in the room.
The stereo is near the door.
There are some books on the stereo.
There are some pictures in the room.
The pictures are on the wall.
* Come in, Amy
** Text
Come in, Amy.
Shut the door, please.
This bedroom's very untidy.
What must I do, Mrs. Jones?
Open the window and air the room.
Then put these clothes in the wardrobe.
Then make the bed.
Dust the dressing table.
Then sweep the floor.
** Words
*** shut
shut | BrE ʃʌt, AmE ʃət |
 A. present participle shutting past tense, past participle shut transitive verb
 ① (close) 关上 guānshang ‹window, drawer›; 合上 héshang ‹book›; 闭上 bìshang ‹eyes›; 关闭 guānbì ‹road, rail line›
  ▸ come in and shut the door 进来把门关上
  ▸ I can't shut this suitcase! 我合不上这个手提箱！
  ▸ shut your mouth or gob or trap or face! informal 闭嘴！ bì zuǐ ！
 ② (trap) 夹住 jiāzhù ‹curtain, dress›
  ▸ to shut sth in a door/window/drawer etc.; 将某物夹在门/窗/抽屉等里
 ③ (stop activity of) 使停止营业 shǐ tíngzhǐ yíngyè
  ▸ we shut the shop at 5:30 我们店 5 点 30 分关门
 B. intransitive verb present participle shutting past tense, past participle shut
 ① 停止营业 tíngzhǐ yíngyè
  ▸ the pub shuts at 11:00 这家酒馆 11 点打烊
 ② 关闭 guānbì
  ▸ this window won't shut 这扇窗户关不上
  ▸ it shut with a bang or crash 砰的一声关上了
 C. adjective
 ① (closed) 关上的 guānshang de ‹box, lid›; 合上的 héshang de ‹book, purse›; 闭上的 bìshang de ‹eyes›
  ▸ you have to slam the door shut 你要用力才能把门关上
  ▸ she sat with her mouth tightly shut 她紧闭着嘴坐着
 ② predicative
  ▸ (not serving or working) to be shut; «shop, pub» 已打烊的 «business» 暂停营业的 zàntíng yíngyè de «factory» 已下班的 yǐ xiàbān de PHRASAL VERBS shut away transitive verb [shut sb/sth away] 把…放好 bǎ… fànghǎo ‹papers, jewellery›; 隔离 gélí ‹person›shut down
 A. transitive verb [shut sth down, shut down sth]
 ① (close temporarily) 使暂停营业 shǐ zàntíng yíngyè ; (permanently) 使停业 shǐ tíngyè
  ▸ the company has had to shut down many of its retail outlets 该公司不得不关闭很多零售点
 ② (cease operation of) 使…停止运转 shǐ… tíngzhǐ yùnzhuǎn ‹machinery, plant›
  ▸ how long does it take to shut down a nuclear reactor? 让核反应堆停止运行要用多长时间？
 B. intransitive verb «machinery, factory» 停止运转 tíngzhǐ yùnzhuǎn ; «business» 停止营业 tíngzhǐ yíngyè shut in: transitive verb [shut sb in] 把…关起来 bǎ… guān qilai
  ▸ to shut oneself in; 把自己关在屋里
  ▸ she's shut herself in and won't come out! 她把自己关在房间里不肯出来！ shut off: transitive verb
 ① [shut off sth, shut sth off] (cut supply of) 切断…的供应 qiēduàn… de gōngyìng ‹water, gas, electricity›; (to individual appliance) 关掉 guāndiào ‹water, gas, electricity›
 ②
  ▸ (isolate) to shut sth/sb off (from …); 将某物/某人（与…）隔离 jiāng mǒu wù/mǒu rén(yǔ… )gélí
  ▸ to shut oneself off (from …); 把自己封闭起来（不接触…） bǎ zìjǐ fēngbì qilai(bù jiēchù… ) shut out transitive verb [shut sth/sb out, shut out sth/sb]
 ① (keep out) «person» 把…关在外面 bǎ… guān zài wàimian ; «double glazing, barrier» 挡住 dǎngzhù ‹noise, water›
 ② figurative (exclude) 摆脱 bǎituō ‹memory›; 克制 kèzhì ‹sadness, misery›
  ▸ to shut sb out; 把某人排除在外
  ▸ she wants to shut him out of her life completely 她想彻底地把他赶出自己的生活
 ③ (block out) «trees, curtains, wall» 挡住 dǎngzhù ‹sun, light, view›shut up
 A. intransitive verb
  ▸ informal shut up! 闭嘴！ bì zuǐ ！
  ▸ when he was shown the evidence, he soon shut up 当证据摆在他面前时，他很快便不吭声了
 B. [shut sb up] transitive verb
 ① (silence) 使…住口 shǐ… zhùkǒu ‹person›; 使…停止发表意见 shǐ… tíngzhǐ fābiǎo yìjiàn ‹critics, journalists›
 ② (imprison) 把…关进监狱 bǎ… guānjìn jiānyù
 C. [shut up sth, shut sth up] transitive verb 关闭 guānbì ‹house, shop›
*** bedroom
bedroom | BrE ˈbɛdruːm,ˈbɛdrʊm, AmE ˈbɛdˌrum,ˈbɛdˌrʊm | noun
 ① 卧室 wòshì ; before noun (for a bedroom) 卧室的 wòshì de
  ▸ bedroom slippers 在家穿的拖鞋
 ② before noun (sexual) 性爱的 xìng'ài de
  ▸ a bedroom scene 床上戏
*** untidy
untidy | BrE ʌnˈtʌɪdi, AmE ˌənˈtaɪdi | adjective
 ① (messy) 凌乱的 língluàn de
  ▸ please excuse the untidy writing 笔迹潦草，万望见谅
 ② (unkempt) 不整洁的 bù zhěngjié de
  ▸ an untidy-looking person 看上去不修边幅的人
*** air
air | BrE ɛː, AmE ɛr |
 A. noun
 ① uncountable (substance) 空气 kōngqì
  ▸ warm air rises 暖气流上升
  ▸ the sound of children's voices filled the air 到处都是孩子们说话的声音
  ▸ I need some air 我要透透气
  ▸ in the open air 在户外
  ▸ to come up for air 浮出水面吸气
  ▸ the air temperature was 16° below zero 气温是零下 16 度
 ② uncountable (atmosphere, sky) 天空 tiānkōng
  ▸ the birds of the air 飞禽
  ▸ the heron took to the air 那只苍鹭飞上了天空
  ▸ he threw the ball up into the air 他把球抛到空中
  ▸ the battle was fought on the ground and in the air 战斗在地面和空中进行
  ▸ air attacks/transport 空袭/空运
  ▸ to travel by air 乘飞机旅行
  ▸ most of the mail goes by air 大多数邮件都是航空邮寄
  ▸ there's something in the air figurative 似乎要出事
  ▸ to be up in the air figurative 悬而未决
  ▸ to be walking or treading or floating on air figurative 得意扬扬
 ③ uncountable
  ▸ Radio, Television to be or come or go on the air; 播放 bōfàng
  ▸ the series will be back on the air in January 该系列节目将在 1 月份重新开播
  ▸ the minister went on (the) air to reassure the public 部长发表了广播讲话，以打消公众的疑虑
  ▸ to be or go off the air; 停止播放
  ▸ to take off the air; 停播…的节目 ‹broadcaster, interviewee› 停播 tíng bō ‹programme›
 ④ countable (impression) 样子 yàngzi
  ▸ with a knowing air 以心照不宣的神态
  ▸ phrases like these have a quaint, old-fashioned air 像这样的短语显得古朴有趣
  ▸ with an air of indifference/innocence 显示出漠不关心/天真的样子
  ▸ an air of mystery surrounds the project 这个项目充满了神秘感
  ▸ she has a certain air about her 她有某种魅力
 ⑤ countable Music dated 曲调 qǔdiào
  ▸ Bach's Air on a G String 巴赫的《G 弦上的咏叹调》
 B. airs plural noun 矫揉造作 jiǎo róu zào zuò
  ▸ to give oneself airs 摆架子
  ▸ airs and graces 装腔作势
 C. transitive verb
 ① (make dry) 晾干 liànggān ‹clothes, sheets›
 ② (make fresh) 使…通风 shǐ… tōngfēng ‹room, house›
  ▸ fold back the duvet to air the bed 叠起羽绒被让床透气
 ③ (express) 表达 biǎodá ‹opinions, feelings›; 诉说 sùshuō ‹grievances›; 卖弄 màinong ‹knowledge›
 ④ Radio, Television (broadcast) 播放 bōfàng
 D. intransitive verb
 ① (become dry) «clothes, sheets» 晾干 liànggān
  ▸ she put the sheets in front of the fire to air 她将被单放在火炉前烘干
 ② (become fresh) «room, building» 通风 tōngfēng
 ③ (be broadcast) 播出 bōchū
*** wardrobe
wardrobe | BrE ˈwɔːdrəʊb, AmE ˈwɔrˌdroʊb | noun
 ① countable (mainly British) (clothes cupboard) 衣柜 yīguì
 ② countable usually singular (clothes collection) 全部衣物 quánbù yīwù ; Cinema, Theatre 全部演出服 quánbù yǎnchūfú
 ③ uncountable Cinema, Theatre (department) 演出服装部 yǎnchū fúzhuāngbù
*** dust 
dust | BrE dʌst, AmE dəst |
 A. noun
 ① (grime) 灰尘 huīchén
  ▸ to gather dust 积灰 figurative 被忽视 bèi hūshì
  ▸ that idea has been gathering dust since it was put forward 那个计划从提出至今一直搁在一边
  ▸ to raise dust; 扬起灰尘
 ② (earth, soil) 尘土 chéntǔ
  ▸ a cloud of dust 一片尘雾
  ▸ to raise a lot of dust; 扬起大片尘土 figurative 引起骚乱 yǐnqǐ sāoluàn
  ▸ to allow the dust to settle 让尘埃落下 figurative 让事情平息 ràng shìqing píngxī
  ▸ to throw dust in sb's eyes figurative 蒙蔽某人
 ③ (fine powder) 粉尘 fěnchén
  ▸ coal dust 煤粉尘
 B. transitive verb
 ① (wipe dust from) 擦去…的灰尘 cāqù… de huīchén ‹furniture, surface›
 ② (clean) 打扫 dǎsǎo ‹room, house›
  ▸ to be (all) done and dusted informal (completely finished) 完全结束 (completely ready) 准备就绪
 ③
  ▸ (coat lightly) to dust sth with sth; 往…上撒某物 ‹pastry› 往…上擦某物 wǎng… shang cā mǒu wù ‹face›
  ▸ to dust the cake with sugar 把糖撒在蛋糕上
 ④
  ▸ to dust sth on to/over sth; 把…撒在某物上 ‹sugar› 把…擦在某物上 bǎ… cā zài mǒu wù shang ‹powder, make-up›PHRASAL VERBS dust down: transitive verb [dust sth down, dust down sth] 擦去…的灰尘 cāqù… de huīchén dust off transitive verb [dust sth off, dust off sth]
 ① (brush off) 把…掸掉 bǎ… dǎndiào ‹dirt, crumbs›
 ② (remove dust from) 擦去…的灰尘 cāqù… de huīchén ‹furniture, surfaces›dust out: transitive verb [dust sth out, dust out sth] 清扫…内部 qīngsǎo… nèibù
*** dressing table 
dressing table | BrE , AmE ˈdrɛsɪŋ ˌteɪbəl | noun 梳妆台 shūzhuāngtái
*** sweep
sweep | BrE swiːp, AmE swip |
 A. transitive verb past tense, past participle swept
 ① (clean with broom) 清扫 qīngsǎo
  ▸ to sweep sth clean 把某物清扫干净
 ② (clear away with broom, brush, hand) 扫去 sǎoqù
  ▸ to sweep sth into/on to sth; 将某物扫进某物/扫到某物上
  ▸ to sweep the crumbs on to the floor/into the wastebasket/into a heap 把面包屑扫到地板上/扫进垃圾桶/扫成一堆
  ▸ to sweep sth from or off sth; 将某物从某物上扫除
  ▸ to sweep the snow from or off the path 扫除路上的积雪
 ③ (move or push with force) 推送 tuīsòng
  ▸ the current swept the logs down the river 激流把圆木冲向河的下游
  ▸ to sweep sb/sth from or off/into/on to or over sth; 将某人/某物推离/推进/推上某处
  ▸ he swept me into his arms 他一下把我揽入怀中
  ▸ a huge wave swept us off our feet 一个巨浪将我们打翻
  ▸ to sweep sb/sth downstream/out to sea 将某人/某物冲向下游/大海
 ④ (clear of obstacles) «ship» 清除 qīngchú ‹area, channel, sea›
  ▸ to sweep sth clear or free (of sth) 清理干净某处（的某物）
 ⑤ (put in particular state) 一举送入 yījǔ sòngrù
  ▸ to be swept to or into power/office 以压倒优势获得选举胜利上台掌权
  ▸ to sweep sb off his/her feet 使某人对自己一见倾心
 ⑥ (in election) «party» 在…范围内大获全胜 zài… fànwéi nèi dà huò quánshèng ‹country›
 ⑦ (move through) «hurricane, wave, fire» 横扫 héngsǎo ‹area, coast, city›; (spread through) «disease, crime, rumour» 席卷 xíjuǎn ‹country, area, city›; (be directed over) «gaze, searchlight, periscope» 扫过 sǎoguo ‹sky, room, area›
 ⑧ (skim) «dress, coat» 掠过 lüèguo ‹ground, floor›
 ⑨ (search) «troops, police, vessel» 搜索 sōusuǒ ‹area, sea›
  ▸ to sweep sth for sb/sth; 在某处搜寻 ‹escapee, mines, bugs›
 ⑩ (arrange hair) 掠 lüè
  ▸ to sweep the hair from one's eyes 把眼睛上的头发掠开
  ▸ her hair was swept back from her face/into a chignon 她的头发是从前往后梳的/梳成了发髻
 ⑪ US Sport 获得…的全部胜利 huòdé… de quánbù shènglì ‹contest, event›; 完胜 wánshèng ‹team›
  ▸ to sweep the series 囊括系列比赛的全部冠军
 B. intransitive verb past tense, past participle swept
 ① (clean with broom) 打扫 dǎsǎo
 ② (move through area) 横扫 héngsǎo ; (spread in area) 席卷 xíjuǎn
  ▸ to sweep across sth; «hurricane» 横扫 héngsǎo ‹land, area› «disease, rumour, news» 席卷 xíjuǎn ‹area, city, country›
  ▸ the wind swept in from the east 风从东边吹来
  ▸ huge waves were sweeping over the deck 巨浪冲上了甲板
  ▸ fire swept through the building 大火蔓延到整个大楼
 ③ (move quickly) 快速移动 kuàisù yídòng
  ▸ to sweep down; «plane» 俯冲下来
  ▸ to sweep into sth; «enemy» 一举攻入 ‹region›
  ▸ to sweep past sth; «vehicle, car» 在某物旁一掠而过
 ④ (move majestically) 堂皇地移动 tánghuáng de yídòng
  ▸ a mighty eagle swept across the sky 一只雄鹰在空中巍然掠过
  ▸ she swept in dressed in a magnificent gown 她穿着华贵的礼服，仪态优雅地走了进来
  ▸ to sweep down/into/out of sth; 庄严地走下/走进/走出某处
 ⑤ (enter particular state) 一举进入 yījǔ jìnrù
  ▸ to sweep to or into power/office 以压倒优势在选举中获胜/一举上台
  ▸ to sweep into the lead 一举取得领先
  ▸ to sweep to victory 一举获胜
 ⑥ (extend) «road, coast, mountains, plain» 延伸 yánshēn
  ▸ to sweep around/down sth; 绕着/沿着某物延伸
  ▸ to sweep down/up to sth; 向下/向上延伸到某物
  ▸ to sweep north or northwards/south or southwards 向北/向南延伸
 C. noun
 ① countable (with broom) 扫 sǎo
  ▸ to give sth a sweep 扫一扫某物
  ▸ this room needs a good sweep 这个房间需要好好打扫一下
 ② countable (swing) 挥动 huīdòng
  ▸ the slow sweep of the pendulum 钟摆的缓慢摆动
  ▸ with or in one sweep of his hand he knocked all the plates off the shelf 他手一挥，把盘子全部从架子上扫了下来
 ③ countable (movement in curve) 掠 lüè
  ▸ to make a sweep 掠过 lüèguo
 ④ countable (curved stretch of road, river, country, etc.) 绵延弯曲的地带 miányán wānqū de dìdài
  ▸ the sweep of the cliffs/hills 蜿蜒的悬崖/山丘
 ⑤ uncountable (curved range) 范围 fànwéi
  ▸ outside the sweep of the guns/searchlights/telescope 在炮火的射程/探照灯的扫射范围/望远镜的视野之外
 ⑥ uncountable (scope of events) 广度 guǎngdù
  ▸ her book covers the long sweep of the country’s history 她这本书内容涵盖这个国家的漫长历史
 ⑦ countable (search on land, at sea, by air) 搜寻 sōuxún
  ▸ a sweep of or over or through sth; 对…的搜寻 ‹area, room, land, sea›
  ▸ a sweep for sb/sth; 对…的搜寻 ‹criminals, mines, bugs›
  ▸ a sweep with sth; 用…进行的搜索 ‹periscope, telescope, radar›
  ▸ to make a sweep 进行搜寻
 ⑧ countable (comprehensive survey) 扫荡 sǎodàng
  ▸ a sweep of or over or through; 对…的扫荡 ‹area, land, sea›
  ▸ the bombers made a series of sweeps over enemy territory 轰炸机在敌占区进行了一系列轰炸
 ⑨ countable (mainly British) = chimney sweep
 ⑩ countable US (series of wins) 连胜 liánshèng ; (comprehensive win) 全胜 quánshèng
  ▸ a World Series sweep 在世界棒球联赛中的全胜
 ⑪ countable informal = sweepstakeD. sweeps plural noun
  ▸ US the sweeps 收视率调查 shōushìlǜ diàochá PHRASAL VERBS sweep along transitive verb [sweep sb/sth along]
 ① (force to move) «current, water, crowd» 迫使…前移 pòshǐ… qián yí
  ▸ to be swept along by the crowd/the strong current 被人群/激流裹挟着向前
 ② (cause to become carried away with emotion) 使醉心 shǐ zuìxīn
  ▸ to be swept along by the force of one's emotions 受感情力量的驱使 sweep aside transitive verb [sweep sb/sth aside, sweep aside sb/sth]
 ① (move to one side) 把…推到一边 bǎ… tuīdào yībiān
 ② (ignore) 对…置之不理 duì… zhì zhī bù lǐ ‹person, protest, offer, inhibition›sweep away
 A. [sweep sth away, sweep away sth] transitive verb
 ① (clear away with broom, brush, hand) 扫除 sǎochú ‹dirt, snow, leaves›
 ② (get rid of) 彻底消除 chèdǐ xiāochú ‹restriction, obstacle, difficulty, doubt›
 B. [sweep sb/sth away, sweep away sb/sth] transitive verb «flood, hurricane, storm» 卷走 juǎnzǒu ‹object, bridge, person›
  ▸ a big wave came in and swept him away 一个大浪涌来把他冲走了
 C. [sweep sb away, sweep away sb] transitive verb «enthusiasm, passion, charm» 使醉心 shǐ zuìxīn
  ▸ to be swept away by sth; 对某事物着迷 sweep out transitive verb [sweep sth out, sweep out sth] 把…打扫干净 bǎ… dǎsǎo gānjìng ‹room›sweep over transitive verb [sweep over sb/sth]
 ① (be directed over) «eyes, gaze» 扫视 sǎoshì ‹person, room›; «searchlight, periscope» 扫过 sǎoguo ‹sky, area›
 ② (come over) «panic, guilt, elation» 强烈影响 qiángliè yǐngxiǎng
  ▸ fear swept over him 恐惧感笼罩着他
  ▸ the feeling swept over me that … 我猛然觉得… sweep up
 A. intransitive verb 打扫干净 dǎsǎo gānjìng
  ▸ after you've finished in the kitchen, please remember to sweep up 你在厨房里干完活后记得打扫干净
 B. transitive verb
 ① [sweep sth up, sweep up sth] (clear away with broom, brush, hand) 打扫 dǎsǎo
  ▸ he swept the leaves up into a pile 他把落叶扫成了一堆
 ② [sweep sb/sth up, sweep up sb/sth] (lift) 一把抱起 yī bǎ bào qǐ ‹person›; 一把拿起 yī bǎ náqǐ ‹object›
 ③ [sweep sb up, sweep up sb] (cause to become carried away) «passion, pleasure, enthusiasm, optimism» 使忘乎所以 shǐ wàng hū suǒ yǐ
  ▸ to be swept up in; 沉醉于 ‹revolution, wave of nationalism›

** Test

*** First
Come in, Amy
Come in, Amy.
Shut the door, please.
This bedroom's very untidy.
What must I do, Mrs. Jones?
Open the window and air the room.
Then put these clothes in the wardrobe.
Then make the bed.
Dust the dressing table.
Then sweep the floor.

*** Second
Come in, Amy
Come in, Amy.
Shut the door, please.
This bedroom's very untidy.
What must I do, Mrs. Jones?
Open the window and air the room.
Then put these clothes in the wardrobe.
Then make the bed.
Dust the dressing table.
Then sweep the floor.

*** Thrid
Come in, Amy.
Shut the door, please.
This bedroom's very untidy.
What must I do, Mrs. Jones?
Open the window and air the room.
Then put these clothes in the wardrobe.
Then make the bed.
Dust the dressing table.
Then sweep the floor.

*** Forth 
Come in, Amy.
Shut the door, please.
This bedroom's very untiday.
What must I do, Mrs. Jones?
Open the window and air the room.
Then put these clothes in the wardrobe.
Then make the bed.
Dust the dressing table.
Then sweep the floor.
* Where's Sally?
** Text
Where's Sally, Jack?
She's in the garden, Jean.
What's she doing?
She's sitting under the tree.
Is Tim in the garden, too?
Yes, he is.
He's climbing the tree.
I beg your pardon?
Who's climbing the tree?
Tim is.
What about the dog?
The dog's in the garden, too.
It's running across the grass.
It running after a cat.
** Words
*** garden
garden | BrE ˈɡɑːd(ə)n, AmE ˈɡɑrd(ə)n |
 A. noun uncountable and countable (mainly British) (area around house) 花园 huāyuán
  ▸ to lead sb up the garden path informal 引诱某人出洋相
  ▸ everything in the garden's rosy British informal 一切都称心如意
  ▸ garden flower/plant 园艺花卉/植物
 B. gardens plural noun 公园 gōngyuán
  ▸ botanical/zoological/municipal gardens 植物园/动物园/城市公园
*** climb
climb | BrE klʌɪm, AmE klaɪm |
 A. intransitive verb
 ① (move upwards) 攀登 pāndēng
  ▸ to climb up sth; 爬上 ‹ladder, tree, steps›
  ▸ to climb (up) to the summit 登上顶峰
 ② (scale a mountain) 登山 dēngshān
 ③ (clamber) 费力爬 fèilì pá
  ▸ to climb over the fence; 费力翻过篱笆
  ▸ to climb into bed; 费力爬上床
 ④ (go higher in sky) «plane, rocket» 爬升 páshēng ; «sun» 升起 shēngqǐ
  ▸ to climb to 10,000 metres 上升到１万米的高度
 ⑤ (slope upwards) «road» 向上斜升 xiàng shàng xié shēng ; (grow upwards) «plant» 向上攀缘 xiàng shàng pānyuán
  ▸ there were roses climbing up the walls 有几株玫瑰爬上了墙
 ⑥ (increase) «currency» 升值 shēngzhí ; «price» 上涨 shàngzhǎng ; «profits» 增加 zēngjiā ; «temperature, birth rate» 上升 shàngshēng
 ⑦ (improve position, status) 晋升 jìnshēng
  ▸ in a few years he had climbed to the top of his profession 他在几年内攀升到了职业生涯的顶峰
  ▸ the team has now climbed to fourth in the league 该队现已上升到联赛第四名
 B. transitive verb 攀登 pāndēng ‹mountain, stairs, ladder›
  ▸ the car slowly climbed the hill 汽车慢慢爬上了山
 C. noun
 ① (ascent) 攀登 pāndēng
  ▸ it's an hour's climb to the summit 登顶需一小时
 ② (mountain) 攀登的山 pāndēng de shān
  ▸ the most difficult climb in the Alps 阿尔卑斯山脉中最难攀登的山峰
 ③ (slope) 上坡 shàngpō
 ④ Aviation 爬升 páshēng
 ⑤ (increase) 上升 shàngshēng
  ▸ a climb in prices 价格的上涨
  ▸ the dollar's climb against the euro 美元对欧元汇率的上升
 ⑥ (improvement in position, status) 晋升 jìnshēng
  ▸ the book recounts her climb (from obscurity) to stardom 这本书讲述了她（从默默无闻到）成为明星的经历 PHRASAL VERB climb down intransitive verb (admit a mistake) 认错 rèncuò ; (withdraw) 退让 tuìràng
  ▸ to climb down from sth; 放弃 ‹accusation, threat, demand›
  ▸ to climb down over sth; 在…上让步 ‹issue, plan›
*** I beg your pardon?

I beg your pardon
英[aɪ beɡ jɔː(r) ˈpɑːdn]
美[aɪ beɡ jʊr ˈpɑːrdn]
[词典]	请你原谅；我请求你的原谅（宽恕）；请再说一遍;
[例句]I beg your pardon ( but would you repeat what you said)?
对不起，请你再讲一遍好吗？
*** grass 
grass | BrE ɡrɑːs, AmE ɡræs |
 A. noun
 ① uncountable (wild) 草 cǎo
  ▸ a blade of grass 一片草叶
  ▸ not let the grass grow under one's feet figurative (in getting sth done) 不拖拉 (in taking an opportunity) 不坐失良机
  ▸ to kick sth into the long grass figurative informal 把某事搁置一边
 ② countable (as botanical classification) 禾本科植物 héběnkē zhíwù
 ③ uncountable (lawn) 草地 cǎodì ; (pasture) 草场 cǎochǎng
  ▸ keep off the grass! 禁止踩踏草地！
  ▸ to mow or cut the grass 割草
  ▸ the grass is always greener on the other side (of the fence) proverb 这山望着那山高
  ▸ to put … out to grass 赶…去吃草 figurative humorous 迫使…退休 pòshǐ… tuìxiū
  ▸ to play on grass (in tennis) 在草地球场上打球
 ④ uncountable informal (marijuana) 大麻 dàmá
 ⑤ countable British informal (informer) 向警方告密的人 xiàng jǐngfāng gàomì de rén
 B. transitive verb 在…上种草 zài… shang zhòng cǎo ‹garden, field, land›
 C. intransitive verb British informal derogatory 告密 gàomì
  ▸ to grass on sb, to grass sb up; 告发某人
** Test
*** First
Where's Sally, Jack?
She's sitting in the garden, Jean.
What's she doing?
She's sitting under the tree.
Is Tim in the garden, too?
Yes, he is. 
He's climbing the tree.
I beg your pardon?
Who's climbing the tree?
Tim is.
What about the dog?
The dog's in the garden, too.
It's running across the grass.
It's running after a cat.
*** Second
Where's Sally
Where's Sally, Jack?
She's in the garden, Jean.
What's she doing?
She's sitting under the tree.
Is Tim in the garden, too?
Yes, he is.
He's climbing the tree.
I beg your pardon?
Who's climbing the tree?
Tim is.
What about the dog?
The dog's in the garden, too.
It's running across the grass.
It's running after a cat.
*** Third
Where's Sally, Jack?
She's in the garden, Jean.
What's she doing?
She's sitting under the tree.
Is Tim in the garden, too?
Yes, he is.
He's climbing the tree.
I beg your parden?
Who's climbing the tree?
Tim is.
What about the dog?
The dog's in the garden, too.
It's running across the grass.
It's running after a cat.
*** Forth
Where's Sally, Jack?
She's in the garden, Jean.
What's she doing?
She's sitting under the tree.
Is Tim in the garden, too?
Yes, he is.
He's climbing the tree.
I beg your pardon?
Who's climbing the tree?
Tim is.
What about the dog?
The dog's in the garden, too.
It's running across the grass.
It's running after a cat.
*** Fifth
Where's Sally?
Where's Sally, Jack?
She's in the garden, Jean.
What's she doing?
She's sitting under the tree.
Is Tim in the garden, too?
Yes, he is.
He's climbing the tree.
I beg your pardon?
Who's climbing the tree?
Tim is.
What about the dog?
The dog's in the garden, too.
It's running across the grass.
It's running after a 
*** Sixth
Where's Sally
Where's Sally, Jack?
She's in the garden, Jean.
What's she doing?
She's sitting under the tree.
Is Tim in the garden, too?
Yes, he is.
He's climbing the tree.
I beg your pardon?
Who's climbing the tree?
Tim is.
What about the dog?
The dog's in the garden, too.
It's running across the grass.
It's running after a cat.
* The sun is shinning
** Text
It is a fine day today.
There are some clouds in the sky,
but the sun is shining.
Mr. Jones is with his family.
They are walking over the bridge.
There are some boats on the river.
Mr. Jones and his wife are looking at them.
Sally is looking at a big ship.
This ship is going under the bridge.
Tim is looking at an aeroplane.
The aeroplane is flying over the river.
今天是个好天气。
天上有些白云，但阳光灿烂。
琼斯先生一家在一起。
他们正在桥上散步。
河上有些船。
琼斯先生及夫人目视它们。
萨利正看着一艘大船。
这船正在桥下通过。
蒂姆正看着一架飞机。
飞机正飞过河流。
** Test
*** First
It is a fine day today.
There are some clouds in the sky,
but the sun is shining.
Mr. Jones is with his family.
They are walking over the bridage.
There are some boats on the river.
Mr. Jones and his wife are looking at them.
Sally is looking at a big ship.
This ship is going under the bridge.
Tim is looking at an aeroplane.
The aeroplane is flying over the river.
*** Second
It is a fine day today.
There are some clouds in the sky,
but the sun is shining.
Mr. Jones is with his family.
They are walking over the bridge.
There are some boats on the river.
Mr. Jones and his wfie at looking at them.
Sally is looking at a big ship.
This ship is going under the bridge.
Tim is looking at an aeroplane.
The aeroplane is flying over the river.
*** Third
It is a fine day today.
There are some clouds in the sky, 
but the sun is shining.
Mr. Jones is with his family.
They are walking across the bridge.
There are some boats on the river.
Mr. Jones and his wife are looking at them.
Sally is looking at a big ship.
The ship is going under the bridge.
Tim is looking at an aeroplane.
The aeroplane is flying over the river.
** Words
*** fine 
fine	英[faɪn]
美[faɪn]
adj.	高质量的; 美好的; 健康的; 身体很好的; (指行为、建议、决定) 可接受;
adv.	可接受; 够好; 蛮不错;
n.	罚金; 罚款;
[例句]There is a fine view of the countryside
这里可以看到乡村的美景。
[其他]	比较级：finer 最高级：finest 第三人称单数：fines 复数：fines 现在分词：fining 过去式：fined 过去分词：fined
*** cloud 
cloud | BrE klaʊd, AmE klaʊd |
 A. noun
 ① uncountable and countable Meteorology 云 yún
  ▸ some patches of cloud 几片云
  ▸ to have one's head in the clouds 抱有幻想
  ▸ every cloud has a silver lining proverb 黑暗中总有一线光明
  ▸ (to be) on cloud nine informal 乐不可支
 ② countable (mass of particles) 云状物 yúnzhuàngwù ; (of insects, birds) 一群 yī qún
  ▸ a cloud of smoke/dust 一片烟雾/尘雾
  ▸ a cloud of starlings 一群椋鸟
 ③ countable (in liquid) 混浊团 hùnzhuótuán ; (in gem) 云纹 yúnwén ; (on glass) 雾气 wùqì
 ④ countable figurative (dark spot) 阴影 yīnyǐng
  ▸ a cloud of gloom/suspicion 一片忧虑/一团疑云
  ▸ to cast a cloud over sth 给某事物蒙上一层阴影
  ▸ to leave/be under a cloud (of suspicion) 留下疑团/受到怀疑
 B. transitive verb
 ① (blur) 使…模糊 shǐ… móhu ‹sky, vision›
  ▸ eyes clouded with tears 泪水模糊的眼睛
 ② figurative (confuse) 使…迷惑 shǐ… míhuò ‹mind›; 使…混乱 shǐ… hùnluàn ‹memory›
 ③ figurative (blight) 破坏 pòhuài ‹future, atmosphere›PHRASAL VERB cloud over intransitive verb
 ① literal «sky» 阴云密布 yīnyún mìbù
 ② figurative «expression, face» 阴沉下来 yīnchén xialai
*** shining  
shining | BrE ˈʃʌɪnɪŋ, AmE ˈʃaɪnɪŋ | adjective
 ① (shiny) 有光泽的 yǒu guāngzé de ‹hair›; 亮闪闪的 liàngshǎnshǎn de ‹room, vehicle, tools›
  ▸ there stood the car in all its shining splendour 那辆汽车停在那里，车身闪亮，尽显华丽
 ② (radiant) 发光的 fāguāng de ‹face›
  ▸ with shining eyes she tore the ribbon off the present 她两眼放光，解开了礼物上的绸带
 ③ figurative (excellent) 杰出的 jiéchū de
  ▸ to be a shining example of sth 是某方面的杰出榜样
*** bridge 
bridge | BrE brɪdʒ, AmE brɪdʒ |
 A. noun
 ① countable Building 桥梁 qiáoliáng
  ▸ a bridge over or across sth; 架在…上方的桥
  ▸ to be water under the bridge figurative 事情都过去了
  ▸ a lot of water has flowed under the bridge since then figurative 自那以后已然物是人非
  ▸ we'll cross that bridge when we come to it figurative 我们暂且把那个问题放一放
 ② countable figurative (link) 纽带 niǔdài
  ▸ to act as a/build a bridge between sth and sth 作为/建立一事与另一事之间的联系
 ③ countable (intermediate stage) 过渡 guòdù
  ▸ a bridge to a new career 通向新职业的踏板
 ④ countable Nautical 舰桥 jiànqiáo
 ⑤ countable (of nose) 鼻梁 bíliáng
 ⑥ countable (of glasses) 鼻梁架 bíliángjià
 ⑦ countable Music 琴马 qínmǎ
 ⑧ countable Dentistry 齿桥 chǐqiáo
 ⑨ uncountable Games 桥牌 qiáopái
 B. transitive verb
 ① Building 在…上架桥 zài… shang jià qiáo ‹river›
 ② figurative (reduce) 消除 xiāochú
  ▸ to bridge the gap between two countries/levels 消除两国之间的隔阂/两个层次之间的差距
 ③ figurative (fill in) 弥补 míbǔ
  ▸ to bridge a gap in the conversation 打破冷场局面
 ④ (span) 跨越 kuàyuè ‹period, centuries, eras›
*** boat 
boat | BrE bəʊt, AmE boʊt |
 A. noun
 ① (small vessel) 小船 xiǎo chuán
  ▸ to be in the same boat figurative 处于同样的困境
  ▸ to burn one's boats British figurative informal 破釜沉舟
  ▸ to miss the boat figurative informal 坐失良机
  ▸ to push the boat out British figurative informal 尽情欢庆
  ▸ to rock the boat figurative informal 捣乱 before noun 船的 chuán de ‹shape›; 乘船的 chéngchuán de ‹trip›
 ② (small passenger ship) 渡船 dùchuán
  ▸ by boat 乘船 chéngchuán
 B. intransitive verb 乘船 chéngchuán
*** ship
ship | BrE ʃɪp, AmE ʃɪp |
 A. noun 轮船 lúnchuán
  ▸ to board a ship 登船
  ▸ to disembark from a ship 下船
  ▸ to load/unload a ship 给船装货/
卸货
  ▸ to travel by ship 乘船旅行
  ▸ to take ship for somewhere dated 乘船去某处
  ▸ a ship of the line History 战列舰
  ▸ to keep or run a tight ship figurative informal 严格管理
  ▸ the ship of state figurative 政府
  ▸ at the helm of the ship of state figurative 执掌国家大权
  ▸ when someone's ship comes in or home figurative informal 发了大财时
  ▸ a ship of the desert literary 沙漠之舟 [指骆驼]
  ▸ to jump ship «crew member» 擅自弃职离船
  ▸ we are like ships that pass in the night 我们只是萍水相逢
  ▸ like a ship without a rudder 像无舵之船一样漫无目标
 B. transitive verb present participle shipping past tense, past participle shipped
 ① (transport by sea) 用船运 yòng chuán yùn ‹commodities›
 ② (transport by air or land) 运输 yùnshū
 ③ (take on board) «crew» 把…装船 bǎ… zhuāng chuán ‹cargo, supplies›
  ▸ to ship oars 收桨入船
  ▸ to ship water 从舷侧进水 PHRASAL VERBS ship off transitive verb [ship off sb/sth, ship sb/sth off]
 ① (send by ship or air) «firm» 运送 yùnsòng ‹goods, order›; «government» 派遣 pàiqiǎn ‹troops›
 ② humorous (dispatch) 送走 sòngzǒu ‹patients, children›
  ▸ we shipped the kids off to summer camp 我们送孩子们去了夏令营 ship out
 transitive verb [ship out sth, ship sth out] 运送 yùnsòng ‹goods, order›
*** aeroplane
aeroplane | BrE ˈɛːrəpleɪn, AmE ˈɛrəˌpleɪn | noun (mainly British) 飞机 fēijī
*** fly
fly
1 | BrE flʌɪ, AmE flaɪ |
 A. intransitive verb past tense flew past participle flown
 ① (move through air) «aircraft, insect, bird» 飞 fēi ; figurative literary «hope, worries, cares» 消失 xiāoshī
  ▸ I can't sleep with a mosquito flying around 有蚊子飞来飞去，我睡不着
  ▸ to fly into sth; 飞进某物
  ▸ hopes of an early settlement have flown out of the window 早日解决争端的希望破灭了
  ▸ rumours of her resignation were flying (around) 她辞职的谣言正四处流传
  ▸ to fly in the face of sth 违背某物
  ▸ to fly in the face of all the evidence 与所有证据相悖
  ▸ to fly in the face of danger 全然不顾危险
  ▸ to fly in the face of authority 违抗权威
  ▸ to fly high (ambitious) 雄心勃勃 (elated) 情绪高昂
 ② Aviation, Aerospace (as passenger) [乘坐飞机或航天器] 航行 hángxíng ; (as pilot of aeroplane) 驾驶飞机 jiàshǐ fēijī ; (as pilot of spaceship) 驾驶航天器 jiàshǐ hángtiānqì
  ▸ have you ever flown in a helicopter? 你乘坐过直升机吗？
  ▸ to fly to the moon 飞上月球
 ③ (be propelled) «person, animal» 飞奔 fēibēn ; «projectile» 飞行 fēixíng ; «spark» 飞溅 fēijiàn
  ▸ glass flew in all directions 玻璃四处乱飞
  ▸ to go flying 跌落
  ▸ the contents of the cupboard went flying 碗柜里的东西掉落下来
  ▸ to send sb/sth flying; 把某人打倒在地/四处乱抛某物
  ▸ the blow sent him flying 这重重的一击将他打飞在地
  ▸ to fly at sb; (physically) 扑向某人 (verbally) 针对某人
  ▸ she flew at me, kicking and punching 她扑向我，对我拳打脚踢
  ▸ there's no need to fly at me every time I ask you to do something 你没必要每次我要你做事时都对我恶言相向
  ▸ to let fly (at sb) (with sth); （用某物）击打（某人） figurative （用某物）攻击（某人） (yòng mǒu wù)gōngjī(mǒu rén)
  ▸ she let fly at him with a stream of abuse 她连声辱骂他
  ▸ they let fly (with) a hail of bullets 他们射出一阵弹雨
  ▸ to make the sparks or fur or feathers fly 引发激烈的争执
  ▸ to fly into a rage/panic 勃然大怒/突然惊慌失措
 ④ (rush, hurry) «person, animal» 飞奔 fēibēn ; «vehicle» 飞驰 fēichí
  ▸ I must fly! 我得快走了！
  ▸ the train flew by or past 列车飞驰而过
  ▸ she came flying through the door 她冲进门内
  ▸ to fly open «door, box» 猛地打开
 ⑤ (pass quickly) «period of time» 飞逝 fēishì
  ▸ time flies 时光飞逝
  ▸ to fly past or by 过得飞快
 ⑥ (flutter, wave) «flag, scarf» 飘扬 piāoyáng ; «cloak, hair, kite» 飘舞 piāowǔ
 ⑦ archaic (flee) 逃跑 táopǎo
  ▸ you must fly for your life 你必须逃命
  ▸ to fly from sth; 逃离某物
 B. transitive verb past tense flew past participle flown
 ① (operate) 驾驶 jiàshǐ ‹aircraft, rocket›
 ② (transport by air) «airline, carrier» 空运 kōngyùn ‹people, supplies›
 ③ (cross by air) 飞越 fēiyuè ‹the Atlantic, the Channel›
  ▸ we fly this route daily 我们每天飞这条航线
 ④ (use for flight) 乘坐…的飞机 chéngzuò… de fēijī ‹company, airline›; 乘坐 chéngzuò ‹aircraft, model›
 ⑤ (travel by air) «person, aircraft, bird, insect» 飞行 fēixíng ‹distance›
  ▸ we flew thousands of miles 我们飞了好几千英里
 ⑥ (cause to fly) 使飞行 shǐ fēixíng
  ▸ to fly a kite 放风筝
  ▸ a group of small boys flying their model aeroplanes 一群放飞飞机模型的小男孩
 ⑦ (display) «ship, building, organization» 悬挂 xuánguà ‹flag, ensign›
 ⑧ (raise) 升 shēng ‹flag›
 C. noun
 ① (in men's clothes) (zip) 裤子拉链 kùzi lāliàn ; (row of buttons) 裤子钮扣 kùzi niǔkòu ; (opening) 前裆开口 qiándāng kāikǒu
 ② (flap on tent) 帐篷的门帘 zhàngpeng de ménlián
 D. flies plural noun
 ① British = C1
 ②
  ▸ Theatre the flies 吊景区 diàojǐngqū PHRASAL VERBS fly away intransitive verb «bird, insect, bat» 飞走 fēizǒu
  ▸ all your cares will fly away figurative 你所有的烦恼都会烟消云散 fly in
 A. intransitive verb
 ① (enter or arrive using wings) «aircraft, bird, insect» 飞来 fēilai
 ② (arrive) «aircraft, pilot» 抵达 dǐdá ; «passenger» 乘飞机到达 chéng fēijī dàodá
 B. transitive verb [fly sb/sth in, fly in sb/sth] 用飞机运来 yòng fēijī yùnlai ‹person, supplies›fly off intransitive verb
 ① (leave using wings) «aircraft, bird, insect» 飞走 fēizǒu
 ② Aviation «passenger» 乘飞机离开 chéng fēijī líkāi
  ▸ we're flying off tomorrow 明天我们将乘飞机离开
 ③ (come off) «hat, roof, top» 脱落 tuōluò fly out
 A. intransitive verb
 ① Aviation 乘飞机去 chéng fēijī qù
 ② (extend) «flag» 飘扬 piāoyáng ; «cloak, hair, kite» 飘舞 piāowǔ
 B. transitive verb [fly sb/sth out, fly out sb/sth] 用飞机运走 yòng fēijī
yùnzǒu ‹person, supplies›
*** Third
It is a fine day today.
There are some clouds in the sky, 
but the sun is shining.
Mr. Jones is with his family.
They are walking over the bridge.
There are some boats on the river.
Mr. Jones and his wife are looking at them.
Sally is looking at a big ship.
This ship is going under the bridge.
Tim is looking at an aeroplane.
The aeroplane is flying over the river.
* Our village
** Text
This is a photograph of our village.
Our village is in a valley.
It is between two hills.
The village is on a river.
Here is another photograph of the village.
My wife and I are walking along the banks of the river.
We are on the left.
There is a boy in the water.
He is swimming across the river.
Here is another photograph.
This is the school building.
It is beside a park.
The park is on the right.
Some children are coming out of the building.
Some of them is going into the park.
** Words
*** photograph
photograph | BrE ˈfəʊtəɡrɑːf, AmE ˈfoʊdəˌɡræf |
 A. noun 照片 zhàopiàn
  ▸ to take a photograph of sb/sth; 给某人/
某物照相
  ▸ to be in a photograph; 在相片里
 B. transitive verb 给…拍照 gěi… pāizhào
  ▸ the children refused to be photographed 孩子们拒绝照相
 C. intransitive verb 在照片上显得 zài zhàopiàn shang xiǎn de
  ▸ to photograph well/badly 上相/不上相
*** village
village | BrE ˈvɪlɪdʒ, AmE ˈvɪlɪdʒ | noun
 ① (in country) 村庄 cūnzhuāng
  ▸ a mountain/farming/fishing village 山村/农村/渔村
  ▸ village school/life/fête 乡村学校/生活/义卖会
 ② (in town, city) 居民村 jūmíncūn
  ▸ the Olympic Village 奥运村
 ③
  ▸ (people) the village plus singular or plural verb 村民 cūnmín
*** valley
valley | BrE ˈvali, AmE ˈvæli | noun plural valleys 山谷 shāngǔ
  ▸ the Thames valley 泰晤士河谷
*** hill
hill | BrE hɪl, AmE hɪl | noun
 ① (raised land) 小山 xiǎoshān
  ▸ a range of hills 一片丘陵
  ▸ to take to the hills 逃跑后躲起来
  ▸ as old as the hills 古老的
  ▸ to be over the hill figurative 在走下坡路
  ▸ over hill and dale literary 漫山遍野
  ▸ up hill and down dale literary 到处
  ▸ over the hills and far away 遥远的
 ② (hillside) 山坡 shānpō ; (slope, incline) 斜坡 xiépō
*** bank
bank
1 | BrE baŋk, AmE bæŋk |
 A. noun
 ① countable (of river, lake) 岸 àn
 ② countable (mound, pile) 堆 duī
  ▸ a bank of snow 一堆雪
 ③ countable (slope) (of hill etc.) 斜坡 xiépō ; (of road or racetrack) 边坡 biānpō
 ④ countable (section of sea bed) 浅滩 qiǎntān
  ▸ a sand bank 沙洲
 ⑤ countable (mass) 大量 dàliàng
  ▸ a bank of thick cloud 厚厚的云层
 ⑥ countable (embankment) 路堤 lùdī
 ⑦ uncountable Aviation （拐弯时的）向内侧倾斜 (guǎiwān shí de)xiàng nèicè qīngxié
 ⑧ countable (of switches, electrical equipment etc.) 组 zǔ
 B. transitive verb
 ① (pile up) (also bank up) 堆积 duījī ‹snow, mud›
 ②
  ▸ (border) to be banked by sth; «road, river» 被某物像堤岸般围住 bèi mǒu wù xiàng dī'àn bān wéizhù
  ▸ the canal is banked on one side by high buildings 运河的一边高楼林立
 ③ Aviation 使…转弯时倾斜飞行 shǐ… zhuǎnwān shí qīngxié fēixíng ‹aeroplane›
 ④ (slope) (also bank up) 使…的转弯处向内侧倾斜 shǐ… de zhuǎnwānchù xiàng nèicè qīngxié ‹road, racetrack›
 ⑤ (dam) (also bank up) 在…上筑堤 zài… shang zhù dī ‹river›
 ⑥ (on a fire) 封 fēng
  ▸ to bank (up) the fire 压火
 C. intransitive verb
 ①
  ▸ (pile up) to bank (up) «snow, mud» 堆积 duījī
 ② Aviation 转弯时倾斜飞行 zhuǎnwānshí qīngxié fēixíng
*** swim
swim | BrE swɪm, AmE swɪm |
 A. intransitive verb present participle swimming past tense swam past participle swum
 ① (move through water) 游泳 yóuyǒng
  ▸ to swim underwater/on one's back/on one's front 潜泳/仰泳/俯游
  ▸ to swim downstream/upstream 游向下游/上游
  ▸ to swim across sth; 游过某物
  ▸ to swim for/to the shore; 游向岸边
  ▸ to swim around/away/past; 来回游动/游走/游过去
  ▸ to swim in/up and down sth; 在某物中游/游来游去
  ▸ to leave sb to sink or swim figurative 让某人自己去拼搏
 ② (be immersed) 浸泡 jìnpào
  ▸ to be swimming in sth; 浸泡在某物中
  ▸ to be swimming with sth; 充溢着某物
  ▸ the meat was swimming in fat 肉油汪汪的
  ▸ her eyes were swimming with tears 她眼睛里饱含泪水
 ③ (appear to whirl, reel) «scene, room, mirage» 仿佛在旋转 fǎngfú zài xuánzhuǎn ; «letters, figures, pages» 似乎在晃动 sìhū zài huàngdòng ; «head» 眩晕 xuànyùn
  ▸ to swim before sb's eyes 仿佛在某人的眼前晃动
 B. transitive verb present participle swimming past tense swam past participle swum
 ① (perform action, cover distance) 游过 yóuguo ‹length, mile›
  ▸ to swim the Channel 游过英吉利海峡
 ② (compete in) 参加…游泳 cānjiā… yóuyǒng
  ▸ to swim a race/event/heat 参加游泳比赛/项目/预赛
  ▸ the race is swum over 10 lengths 比赛要游 5 个来回
 C. noun 游泳 yóuyǒng
  ▸ to go for a swim 去游泳
  ▸ to have a swim 游泳 yóuyǒng
  ▸ in the swim (of things) informal 合潮流
*** across
across | BrE əˈkrɒs, AmE əˈkrɔs,əˈkrɑs |
 A. preposition
 ① (from one side to the other) 横穿过 héngchuānguo
  ▸ to build a bridge across the river 在河上建一座桥
  ▸ to walk across the room 走过房间
  ▸ we travelled across country 我们穿过田间旅行
 ② (on the other side of) 在…对面 zài… duìmiàn ‹street›; 在…对岸 zài… duì'àn ‹river›
  ▸ she shouted across the room to them 她在房间另一头向他们喊叫
 ③ (all over, throughout) 遍及 biànjí
  ▸ newspapers were scattered across the floor 报纸落了一地板
  ▸ the company has branches across the world 公司在世界各地都设有分支机构
 B. adverb
 ① (from one side to the other) 从一边到另一边 cóng yībiān dào lìng yībiān
  ▸ the lake is two miles across at the widest point 湖面最宽的地方有两英里
 ② (to the other side) 到对面 dào duìmiàn
  ▸ we could just swim across 我们游过去好了
*** building
building | BrE ˈbɪldɪŋ, AmE ˈbɪldɪŋ | noun
 ① countable (structure) 建筑物 jiànzhùwù
  ▸ apartment/office/residential buildings 公寓楼/写字楼/住宅楼
  ▸ farm/school buildings 农场/学校建筑
 ② uncountable (industry) 建筑业 jiànzhùyè
 ③ uncountable (action) 建造 jiànzào
  ▸ the building of new homes 新住房的建造
*** park
park | BrE pɑːk, AmE pɑrk |
 A. noun
 ① (public garden) 公园 gōngyuán
 ② Business 园区 yuánqū
  ▸ a business/industrial park 商业/工业园区
 ③ (estate) 庄园 zhuāngyuán
 ④ British informal (pitch) 运动场 yùndòngchǎng
 B. transitive verb
 ① (station) 停放 tíngfàng ‹vehicle›
 ② informal (deposit) 寄放 jìfàng ‹belongings, things›
  ▸ I parked the children at my mother's 我把孩子托放在母亲家里
 C. intransitive verb 停车 tíngchē
 D. to park oneself reflexive verb informal 坐下 zuòxia
** Test
*** First
This is a photograph of our village.
Our village is in a valley.
It is between two hills.
Here is another photograph of the village.
My wife and I are walking along the banks of the river.
We are on the left.
There is a boy in the water.
He is swimming across the river.
Here is another photograph.
This is the  school building.
It is beside a  park.
The park is on the right.
Some children are coming out of the building.
some of them are going into the park.
*** Second
This is a photograph of our village.
Our village is in a valley.
It is between two hills.
The village is on the river.
Here is another photograph of the village.
My wife and I are walking along the banks of the river.
We are on the left.
There is a boy in the water.
He is swimming across the river.
Here is another photograph.
This is the school building.
It is beside a park.
The park is on the right.
Some children are coming out of the school building.
Some of them are going into the park.
*** Third
This is a photograph of our village.
Our village is in a vally.
It is between two hills.
The village is on a river.
Here is another photograph of the village.
My wife and I are walking along the banks of the river.
We are on the left.
There is a boy in the water.
He is swimming across the river.
Here is another photograph.
This is a school building.
It is beside a park. 
The park is on the right.
Some children are coming out of the school building.
Some of them are going into the park.
*** Forth
This is a photograph of our village.
Our village is in a valley.
It is between two hills. 
The village is on a river.
Here is another photograph of the village.
My wife and I are walking along the banks of the river.
We are on the left.
There is a boy in the water.
He is swimming across the river.
Here is another photograph.
This is the school building.
It is beside a park. 
The park is on the right.
Some children are coming out of the school building.
Some of them are going into the park.
*** Fifth
This is a photograph of our village.
Our village is in a valley.
It is between two hills.
The village is on a river.
Here is another photograph of the village.
My wife and I are walking along the banks of the river.
We are on the left.
There is a boy on the water.
He is swimming across the river.
Here is another photograph.
This is the school building.
It is beside a park.
The park is on the right.
Some children are coming out of the builhding.
Some of them are going into the park.
*** Sixth
This is a photograph of our village.
Our village is in a valley.
It is between two hills.
The village is on a river.
Here is another photograph of the village.
My wife and I are walking along the banks.
We are on the left.
There is a boy in the water.
He is swimming across the river.
Here is another photograph.
This is the school building.
It is beside a park.
The park is on the right.
Some children are coming out of the building.
Some of them are going into the park.
* Making bookcase
** Text
You're working hard, George.
What are you doing?
I'm making a bookcase.
Give me that hammer please, Dan.
Which hammer?
This one?
No, not that one.
The big one.
Here you are.
Thanks, Dan.
What are you going to do now, George?
I'm going to paint it.
What colour are you going to paint it?
I'm going to paint it pink.
Pink!
This bookcase isn't for me.
It's for my daughter, Susan.
Pink's her favourite colour.
** Words
*** bookcase
bookcase	英[ˈbʊkkeɪs]
美[ˈbʊkkeɪs]
n.	书架; 书柜;
[例句]Mary left her most precious possession — a small bookcase — to her niece.
玛丽把她最珍视的财产——一个小书架，留给了她的侄女。
[其他]	复数：bookcases
*** hammer
hammer | BrE ˈhamə, AmE ˈhæmər |
 A. noun
 ① (tool) 锤子 chuízi
  ▸ to knock sth in with a hammer 用锤子把某物钉入
  ▸ to be or go at it or each other hammer and tongs figurative 激烈地争斗
 ② (of piano) 音锤 yīnchuí
 ③ (on firearm) 击铁 jītiě
 ④ (auctioneer's gavel) [拍卖时用的] 木槌 mùchuí
  ▸ to come or go under the hammer 被拍卖
 ⑤ Sport (ball attached to wire) 链球 liànqiú ; (event) 链球比赛 liànqiú bǐsài
  ▸ to throw the hammer 掷链球
 ⑥ (bone in ear) 锤骨 chuígǔ
 B. transitive verb
 ① (hit with tool) 锤击 chuíjī
  ▸ to hammer a nail into sth; 把钉子锤进某物
 ② (shape with tool) 锤打 chuídǎ ‹metal›
  ▸ to hammer sth straight or flat 把某物锤平
  ▸ to hammer sth into shape 把某物锤打成型
  ▸ to hammer sb into shape 培养某人成材
 ③ (beat with hand) 反复敲打 fǎnfù qiāodǎ
  ▸ to hammer sth against the wall/with one's fist; 在墙上反复摔打某物/用拳头反复击打某物
 ④ (kick hard) 猛击 měng jī
  ▸ to hammer the ball into the net 将球猛击入网
 ⑤ figurative (criticize) 严厉批评 yánlì pīpíng
  ▸ to hammer sb for sth/doing sth; 因为某事物/做某事严厉批评某人
 ⑥ (utterly defeat) 彻底击败 chèdǐ jībài
  ▸ Chelsea hammered Stoke 5-0 切尔西以５比 0 彻底击败斯托克
 ⑦ figurative (adversely affect) «recession, unemployment» 使…受负面影响 shǐ… shòu fùmiàn yǐngxiǎng ‹district, group›
  ▸ to be hammered by recession 因经济不景气而受挫
 ⑧
  ▸ to hammer sth into sb (instil) 把某事灌输给某人 bǎ mǒu shì guànshū gěi mǒu rén
  ▸ to hammer some sense into sb 让某人懂事一些 ràng mǒu rén dǒngshì yīxiē
 C. intransitive verb
 ① (use hammer) 锤击 chuíjī
 ② (pound) 敲打 qiāodǎ
  ▸ to hammer at or on sth (with one's hand/fist); （用手/拳头）敲打某物
  ▸ to hammer on or against sth; «rain, hail» 噼里啪啦地打在…上 ‹roof, window›
 ③ (thump) «heart» 剧烈跳动 jùliè tiàodòng PHRASAL VERBS hammer away intransitive verb
 ① (with tool or hand) 反复敲打 fǎnfù qiāodǎ
  ▸ to hammer away at sth/sb; 反复敲打某物/某人
  ▸ I could hear him hammering away at the door 我可以听到他一直在敲门
 ② figurative (insist) 作不懈努力 zuò bùxiè nǔlì
  ▸ to hammer away at the problem/point 致力于解决这个问题/反复强调这一点 hammer down intransitive verb informal «rain, hail» 噼里啪啦地落下 pīlipālā de luòxia hammer home transitive verb [hammer sth home, hammer home sth]
 ① (with tool) 将…完全钉入 jiāng… wánquán dìngrù ‹nail›
 ② figurative (emphasize) 着重把…讲清楚 zhuózhòng bǎ… jiǎng qīngchu ‹point, argument›
 ③ (score with) 用力踢…得分 yònglì tī… défēn ‹ball›
  ▸ to hammer the ball home 把球猛踢进球门得分 hammer in transitive verb [hammer sth in, hammer in sth]
 ① (with tool) 钉入 dìngrù ‹nail›
 ② figurative (cause to be learned) 反复灌输 fǎnfù guànshū ‹idea, message›hammer out transitive verb [hammer sth out, hammer out sth]
 ① (with tool) 敲平 qiāopíng ‹dent›
 ② (play) [尤指在钢琴上] 敲打出 qiāodǎ chū ‹tune›
 ③ figurative (achieve) 反复讨论出 fǎnfù tǎolùn chū
  ▸ to hammer out a compromise/decision 反复磋商后达成妥协/作出决定
*** paint
paint | BrE peɪnt, AmE peɪnt |
 A. noun
 ① uncountable (for decorating) 油漆 yóuqī
  ▸ a can or tin or pot of paint 一罐油漆
  ▸ be careful, the paint's still wet on that door 当心，门上的油漆未干
  ▸ it's like watching paint dry 这真无聊透顶
 ② uncountable (used by artist) 颜料 yánliào
 ③ countable
  ▸ paints Art 绘画颜料 huìhuà yánliào
  ▸ a box of paints 一盒水彩颜料 yī hé shuǐcǎi yánliào
  ▸ a set of oil paints 一套油画颜料 yī tào yóuhuà yánliào
 ④ uncountable humorous (make-up) 化妆品 huàzhuāngpǐn
  ▸ she always puts too much paint on 她总是浓妆艳抹
 B. transitive verb
 ① (apply paint to) 为…刷漆 wèi… shuā qī ‹room, house›
  ▸ I'm painting the walls (in) pink 我在把墙漆成粉红色
  ▸ to paint one's nails 涂指甲油
  ▸ to paint the town (red) 狂欢
 ② (draw) «painter, artist» 用颜料画 yòng yánliào huà ‹portrait, landscape›
  ▸ to paint a picture on canvas/board/paper 在画布/木板/纸上作画
 ③ (portray) 描绘 miáohuì
  ▸ their diaries paint a vivid picture of country life 他们的日记生动地描绘了乡村生活
  ▸ not as black as he/she/it is painted 他/她/它不像人们说得那么坏
 ④ (apply with a brush) 涂抹 túmǒ
  ▸ to paint varnish on sth; 在某处涂抹清漆
 ⑤ (apply make-up to) 在…上涂化妆品 zài… shang tú huàzhuāngpǐn ‹face›
  ▸ to paint one's nails 涂指甲
  ▸ she paints her lips bright red 她把嘴唇涂得鲜红
 C. intransitive verb
 ① Art «artist» 绘画 huìhuà
  ▸ to paint in oils/watercolours 用油画颜料/水彩作画
  ▸ I prefer to paint outdoors 我更喜欢在户外作画
  ▸ to paint on canvas/wood 在画布/木头上画画
 ② (decorate) 刷油漆 shuā yóuqī PHRASAL VERBS paint in transitive verb [paint
 sth in, paint in sth] 补画 bǔ huà ‹figure, detail›paint out transitive verb
 [paint sth out, paint out sth] 用颜料涂掉 yòng yánliào túdiào
*** pink
pink | BrE pɪŋk, AmE pɪŋk |
 A. adjective
 ① (in colour) 粉红色的 fěnhóngsè de
 ② (with embarrassment, anger, etc.) 绯红的 fēihóng de ‹face, cheeks›
  ▸ to go or turn pink 面红耳赤
  ▸ to look pink 面色发红
 ③ informal (left-wing) 略为左倾的 lüèwéi zuǒqīng de
 ④ informal (homosexual) 同性恋的 tóngxìngliàn de
  ▸ pink rights/issues 同性恋权利/问题
 B. noun
 ① countable and uncountable (colour) 粉红色 fěnhóngsè
  ▸ to be in the pink 满面红光 figurative 非常健康 fēicháng jiànkāng
 ② countable (plant) 石竹 shízhú ; (flower) 石竹花 shízhú huā
 ③ countable (snooker ball) 粉球 fěn qiú
 C. transitive verb (sew scallop edge) 把…剪成扇形 bǎ… jiǎnchéng shànxíng ; (sew zigzag edge) 把…剪成锯齿形 bǎ… jiǎnchéng jùchǐxíng
 D. intransitive verb British «engine, vehicle» 敲缸 qiāo gāng
*** favourite
favourite British, favorite US | BrE ˈfeɪv(ə)rɪt, AmE ˈfeɪv(ə)rət |
 A. adjective attributive 最喜欢的 zuì xǐhuan de
  ▸ who's your favourite writer? 你最喜欢的作家是谁？
 B. noun
 ① (favourite thing) 最喜爱的事物 zuì xǐ'ài de shìwù ; (favourite person) 最喜爱的人 zuì xǐ'ài de rén
  ▸ this film is a great favourite of his 这部电影是他特别喜爱的
  ▸ an old favourite 一直最喜欢的东西
  ▸ to be sb's favourite; 是某人的最爱
  ▸ he is always a favourite with children 他总是极受孩子们的喜爱
 ② Sport 最有希望获胜者 zuì yǒu xīwàng huòshèng zhě
  ▸ he is the favourite in the 100 metres 他是 100 米赛夺冠呼声最高的选手
*** colour
colour | BrE ˈkʌlə, AmE ˈkələr | British
 A. noun
 ① uncountable and countable (hue) 颜色 yánsè
  ▸ a bright/dark/pale/warm/cold colour 亮色/深色/浅色/暖色/冷色
  ▸ to take the colour out of sth 使某物褪色
  ▸ to change colour 变色 biànsè
  ▸ wait until you've seen the colour of his money 等先弄清他是不是真的有钱再说
 ② uncountable (not black-and-white) 彩色 cǎisè
  ▸ in colour 彩色的
  ▸ a colour TV/picture 彩色电视/照片
 ③ uncountable (vividness) 生动 shēngdòng
  ▸ the last movement is full of colour 最后一个乐章非常生动
  ▸ to give or lend colour to sth (authenticity) 使某事物显得可信 (vividness) 使某事物更加生动
 ④ uncountable and countable (paint, cosmetic) 颜料 yánliào ; (dye) 染料 rǎnliào ; (additive) 色素 sèsù
  ▸ I hope the colour won't run 我希望这种颜料不渗色
  ▸ hair colour 染发液
  ▸ cheek/eye/lip colour 腮红/眼影/口红
  ▸ to paint sth in glowing colours figurative 把某事物描绘得很美好
 ⑤ uncountable (complexion) 脸色 liǎnsè
  ▸ to change colour (go pale) 面色变苍白 (go red) 脸红 liǎnhóng
  ▸ to bring colour to sb's cheeks, to put colour into sb's cheeks 使某人脸色红润
  ▸ to get one's colour back 恢复气色
 ⑥ uncountable and countable (racial pigmentation) 肤色 fūsè
 B. colours plural noun
 ① (clothing) (of sports team) 队服 duìfú
  ▸ to show one's true colours 露出真面目
 ② School, University (badge, cap) 校体育运动队队标 xiào tǐyù yùndòngduì duìbiāo
  ▸ to get colours, to win one's colours 入选运动队
 ③ (mainly British) (flag) (of a country) 国旗 guóqí ; (of a regiment) 团旗 tuánqí ; (of a ship) 船旗 chuánqí
  ▸ they saluted the colours 他们向国旗敬礼 → nail B1
 C. transitive verb
 ① (put colour on) 给…着色 gěi… zhuósè ‹picture, food›
  ▸ to colour sth blue 把某物染成蓝色
  ▸ to colour one's hair 染发
 ② derogatory (prejudice) 影响 yǐngxiǎng ‹opinion, judgement, attitude›
 ③ derogatory (enhance) (by exaggeration) 渲染 xuànrǎn ‹account, excuse›; (by distortion) 歪曲 wāiqū ‹account›
  ▸ she coloured her story with an exaggerated description of the attack 她夸大其词地描述那次袭击，从而使她的故事更加生动
 D. intransitive verb
 ① (change colour) 变色 biànsè
 ②
  ▸ (go red) to colour (up); 脸红 liǎnhóng
  ▸ to colour (up) at sth; 听到…脸红 tīng dào… liǎnhóng ‹laughter, applause›
  ▸ to colour (up) with sth; 因…而脸红 yīn… ér liǎnhóng ‹anger,
 embarrassment›PHRASAL VERB colour in: transitive verb [colour sth in, colour in
 sth] 给…上色 gěi… shàngshǎi
** Test
*** First
You're working hard, George.
What are you doing?
I'm making a bookcase.
Give me that hammer please, Dan.
Which hammer?
This one?
No, not that one.
The big one.
Here you are.
Thanks, Dan.
What are you going to do now, George?
I'm going to paint it.
What colour are you going to paint it?
I'm going to paint it pink.
Pink?
This bookcase isn't for me.
It's for my daughter, Susan.
Pink's her favourite colour.
*** Second
You're working hard, George.
What are you doing?
I'm making a bookcase.
Give me that hammer please, Dan.
Which hammer?
This one?
No, not that one. 
The big one.
Here you are.
Thanks, Dan.
What are you doing now, George?
I'm going to paint it.
What colour are you going to paint it?
I'm going to paint it pink.
Pink!
This bookcase isn't for me.
It's for my daughter, Susan.
Pink's her favourite colour.
*** Third
You're working hard, George.
What are you doing?
I'm making a bookcase.
Give me that hammer please, Dan.
Which hammer?
This one?
No, not that one.
The big one. 
Here you are.
Thanks, Dan.
What are you going to do now, George?
I'm going to paint it.
What colour are you going to paint it?
I'm going to paint it pink.
Pink!
This bookcase isn't for me.
It's for my daughter, Susan.
Pink's her favourite colour!
*** Forth
You're working hard, George.
What are you doing?
I'm making a bookcase.
Give me that hammer please, Dan.
Which hammer?
This one?
No, not that one.
The big one.
Here you are.
What are you going to do now, George?
I'm going to paint it.
What colour are you going to paint it?
I'm going to paint it pink.
Pink!
This bookcase isn't for me.
It's for my daughter, Susan.
Pink's her favourite colour!
* Don't drop it!
** Text
What are you going to do with that vase, Penny?
I'm going to put it on this table, Sam.
Don't do that.
Give it to me.
What are you going to do with it?
I'm going to put it here.
in front of the window.
Be careful!
Don't drop it!
Don't put there, Sam.
Put it here.
on this shelf.
There we are!
It's a lovely vase.
Those flowers are lovely, too.
** Words
*** vase 
vase	英[vɑːz]
美[veɪs]
n.	花瓶; 装饰瓶;
[例句]You will catch it for breaking that vase.
你打破了那花瓶要挨骂了。
[其他]	复数：vases
*** drop
drop	英[drɒp]
美[drɑːp]
v.	(意外地) 落下，掉下，使落下; (故意) 降下，使降落; 累倒; 累垮;
n.	滴; 水珠; 少量; 微量; 一点点; 下降; 下跌; 减少;
[例句]Temperatures can drop to freezing at night
夜间温度可能会降到零度以下。
[其他]	第三人称单数：drops 现在分词：dropping 过去式：dropped 过去分词：dropped
*** Be careful!
小心
*** shelf 
shelf	英[ʃelf]
美[ʃelf]
n.	(固定在墙上的或橱柜、书架等的) 架子，搁板; (悬崖上或海底) 突出的岩石; 陆架; 陆棚;
[例句]He took a book from the shelf.
他从书架上拿了一本书。
[其他]	复数：shelves
*** lovely

lovely	英[ˈlʌvli]
美[ˈlʌvli]
adj.	美丽的; 优美的; 有吸引力的; 迷人的; 令人愉快的; 极好的; 亲切友好的; 慷慨大方的; 可爱的;
n.	美女; 美人; 佳人;
[例句]You look lovely, Marcia
你看上去真漂亮，马西娅。
[其他]	比较级：lovelier 最高级：loveliest
*** There we are!
好了。需上下文联系理解
** Test
*** First
What are you going to do with that vase, Penny?
I'm going to put it on this table, Sam.
Don't do that.
Give it to me.
What are you going to do with it?
I'm going to put it here.
In front of the window.
Be careful!
Don't drop it!
Don't put there, Sam.
Put it here.
On this shelf.
There we are!
It's a lovely vase.
Those flowers are lovely, too.
*** Second
What are you going to do with that vase, Penny?
I'm going to put it on this table, Sam.
Don't do that.
Give it to me.
What are you going to do with it?
I'm going to put it here.
In front of the window.
Be careful!
Don't drop it!
Don't put there, Sam.
Put it here,
On this shelf!
There we are!
It's a lovely vase.
Those flowers are lovely, too.
*** Third
What are you going to do with that vase, Penny?
I'm going to put it on this table, Sam.
Don't do that.
Give it to me.
What are you going to do with it?
I'm going to put it here,
in front of the window.
Be careful!
Don't drop it!
Don''t put there, Sam.
Put it here, 
on this shelf.
There we are!
It's a lovely vase.
Those flowers are lovely, too.
*** Forth
What are you going to do with that vase, Penny?
I'm going to put it on this table, Sam.
Don't do that.
Give it to me.
What are you going to do with it?
I'm going to put it here,
in front of the window.
Be careful!
Don't drop it.
Don't put it there, Sam.
Put it here,
on this shelf.
There we are!
It's a lovely vase.
Those flowers are lovely, too.
* Penny's bag
** text
Is that bag heavy, Penny?
Not very.
Here!
Put it on this chair.
What's in it?
A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of Chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
Is that tin of tobacco for me?
Well, it's certainly not for me!
** Words
*** cheese
cheese | BrE tʃiːz, AmE tʃiz | noun countable and uncountable 奶酪 nǎilào
  ▸ hard cheese! British informal 真不走运！
  ▸ say cheese 说“茄子”
  ▸ a big cheese informal 要人 PHRASAL VERB cheese off transitive verb [cheese sb off, cheese off sb] informal 使感到厌烦 shǐ gǎndào yànfán
  ▸ to be cheesed off with … 对…感到厌烦
*** bread 
bread | BrE brɛd, AmE brɛd | noun uncountable
 ① Cooking 面包 miànbāo
  ▸ to be on bread and water 吃粗茶淡饭
  ▸ to know which side one's bread is buttered informal 知道自己的利益所在
  ▸ to break bread (with sb) dated （与某人）共餐
  ▸ to cast one's bread upon the waters figurative 真心行善不图报
  ▸ bread and wine Religion 圣餐
 ② informal (money) 钱 qián
 ③ (livelihood) 生计 shēngjì
  ▸ to earn one's (daily) bread 谋生
  ▸ to take the bread out of sb's mouth 砸某人的饭碗
  ▸ to put bread on the table 挣钱糊
*** soap 
soap | BrE səʊp, AmE soʊp |
 A. noun
 ① countable and uncountable (for washing) 肥皂 féizào
 ② countable informal = soap operaB. transitive verb 用肥皂洗 yòng féizào xǐ
*** chocolate 
chocolate | BrE ˈtʃɒk(ə)lət, AmE ˈtʃɑk(ə)lət | noun
 ① uncountable (substance) 巧克力 qiǎokèlì
  ▸ a bar of chocolate 一块巧克力
  ▸ chocolate biscuits/cake/ice cream 巧克力饼干/蛋糕/冰激凌
 ② countable (sweet) 巧克力糖 qiǎokèlì táng
 ③ uncountable (drink) 巧克力饮料 qiǎokèlì yǐnliào
 ④ uncountable (colour) 巧克力色 qiǎokèlìsè
*** milk 
milk | BrE mɪlk, AmE mɪlk |
 A. noun
 ① uncountable (general) 奶 nǎi
  ▸ a glass of milk 一杯牛奶
  ▸ to produce milk 泌乳
  ▸ to be in milk «animal» 在授乳期
  ▸ a land flowing with milk and honey 富饶之地
  ▸ the milk of human kindness 人的善良天性
  ▸ to be like milk and water 平淡无味
  ▸ it's no use or good crying over spilt milk proverb 覆水难收，后悔也无济于事
 ② uncountable Botany 白色汁液 báisè zhīyè
  ▸ the milk of a coconut 椰汁
 ③ uncountable and countable (cosmetic) 乳剂 rǔjì
 B. transitive verb
 ① Farming 挤…的奶 jǐ… de nǎi ‹cow›
 ② (extract) 抽取 chōuqǔ ‹sap, venom›
 ③ figurative (draw on) 消耗 xiāohào ‹resources›
  ▸ to milk the fund 动用资金
 ④ figurative (exploit) 榨取 zhàqǔ ‹money›; 套取 tàoqǔ ‹ideas›
  ▸ to milk sth/sb of sth, to milk sth from or out of sth/sb; 从某事物/某人处榨取某物
  ▸ to milk sth/sb dry 榨干某物/某人
  ▸ to milk the situation 趁机牟利自肥
  ▸ to milk sb's strength/enthusiasm 利用某人的体力/热情
  ▸ to milk the audience for applause 卖力地想博得观众的掌声
*** sugar 
sugar | BrE ˈʃʊɡə, AmE ˈʃʊɡər |
 A. noun
 ① uncountable (unrefined) [植物所含的] 糖 táng
  ▸ to refine sugar 炼糖
 ② uncountable and countable (refined) 食糖 shítáng
  ▸ brown/white sugar 红糖/白糖
  ▸ how many sugars do you take? 你要加多少糖？
  ▸ a sugar spoon 糖勺
 ③ (mainly US) informal (term of endearment) 亲爱的 qīn'ài de
  ▸ bye, sugar! 再见，宝贝儿！
 B. exclamation euphemistic informal 完了 wánle [表示恼怒]
  ▸ sugar! I've forgotten my wallet! 糟了！我忘带钱包了！
 C. transitive verb 在…中加糖 zài… zhōng jiā táng
  ▸ sugared almonds 糖衣杏仁
*** tobacco
tobacco | BrE təˈbakəʊ, AmE təˈbækoʊ | noun uncountable
 ① (product) 烟草 yāncǎo
  ▸ a tin of tobacco 一听烟丝
  ▸ a tobacco tin 烟草罐
 ② (plant) 烟草植株 yāncǎo zhízhū
  ▸ a tobacco leaf/plant 烟叶/烟草植株 
** Test
*** First
Is that bag heavy, Penny?
Not very.
Here!
Put it on this chair.
What's in it?
A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
Is that tin of tobacco for me?
Well, it's certainly not for me!
*** Second
Is that bag heavy, Penny?
Not very.
Here!
Put it on this chair.
What's in it?
A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
Is that tin of tobacco for me?
Well, it's certainly not for me.
*** Third
Is that bag heavy, Penny?
Not very.
Here!
Put is on this chair.
What's in it?
A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
Is that tin of tobacco for me?
Well, it's certainly not for me!
*** Forth
Is that bag heary, Penny?
Not very.
Here!
Put it on this chair.
What's in it?
A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
Is that tin of tobacco for me?
Well, it's certainly not for me!
*** Fifth
Is that bag heavy, Penny?
Not very.
Here!
Put it on this chair.
What's in it?
A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
Is that tin of tobacco for me?
Well, it's certainly not for me!
* Hurry up!
** Text
 Can you make the tea, Sam?
 Yes, of course I can, Penny.
 Is there any water in this kettle?
 Yes, there is.
 Where's the tea?
 It's over there, behind the teapot.
 Can you see it?
 I can see the teapot,
 but I can't see the tea.
 There it is!
 It's in front of you!
 Ah, yes, I can see it now.
 Where are the cups?
 There are some in the cupboard.
 Can you find them?
 Yes. Here they are.
 Hurry up, Sam!
 The kettle's boiling!
** Words
*** tea

tea	英[tiː]
美[tiː]
n.	茶叶; 茶; 茶水; 一杯茶;
[例句]America imports about 190 million pounds of tea a year
美国每年进口大约 1.9 亿磅茶叶。
[其他]	复数：teas
*** kettle
kettle	英[ˈketl]
美[ˈketl]
n.	(烧水用的) 壶，水壶;
[例句]I'll put the kettle on and make us some tea.
我去烧壶水给大家沏茶。
[其他]	复数：kettles
*** teapot
teapot	英[ˈtiːpɒt]
美[ˈtiːpɑːt]
n.	茶壶;
[例句]On Capitol Hill, senators today appear to view the matter as something of a tempest in a teapot.
美国国会的参议员们今天似乎把这个问题小题大做了。
[其他]	复数：teapots
*** cupboard 
cupboard	英[ˈkʌbəd]
美[ˈkʌbərd]
n.	橱柜; 食物柜; 衣柜; 壁橱;
[例句]The kitchen cupboard was stocked with tins of soup and food.
厨房的橱柜里备有汤罐头和食品罐头。
[其他]	复数：cupboards
*** hurry up
hurry up	英[ˈhʌri ʌp]
美[ˈhɜːri ʌp]
[词典]	赶紧; 赶快; 使加快; 使提早;
[例句]Franklin told Howe to hurry up and take his bath; otherwise, they'd miss their train
富兰克林告诉豪赶快去洗澡；否则他们会赶不上火车。
*** boiling
boil	英[bɔɪl]
美[bɔɪl]
v.	(使) 沸腾; 煮沸; 烧开; (把壶、锅等) 里面的水烧开; 用沸水煮(或烫洗); 被煮(或烫洗);
n.	沸腾; 沸点; 疖; 皮下脓肿; 黄水疮;
[例句]I stood in the kitchen, waiting for the water to boil
我站在厨房，等着水烧开。
[其他]	第三人称单数：boils 现在分词：boiling 过去式：boiled 过去分词：boiled

** Test
*** First
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
I can see the teapot,
but I can't see the tea?
There it is!
It's in front of you!
Can you see it?
Ah, yes. I see it now.
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam！
The kettle's boiling!
*** Second
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
I can see the teapot,
but I can't see the pea.
There it is!
It's in front of you!
Can you see it?
Ah, yes, I can see it now.
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam!
The kettle's boiling!
*** Third
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
I can see the teapot,
but I can't see the tea.
There it is!
It's in front of you!
Can you see it?
Ah, yes. I can see it now.
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam!
The kettle's boiling!
*** Forth
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
Can you see it?
I can see the teapot,
but I can't see the tea.
There it is!
It's in front of you!
Ah, yes. I can see it now.
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam!
The kettle's boiling!
*** Fifth
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
Can you see it?
I can see the teapot,
but I can't see the tea.
There it is!
It's in front of you!
Ah, yes. I can see it now!
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam!
The kettle's boiling!
*** Sixth
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
Can you see it?
I can see the teapot,
but I can't see the tea.
There it is!
It's in front of you!
Ah, yes. I can see it now.
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam!
The kettle's boiling!
*** Seventh
Can you make the tea, Sam?
Yes, of course I can, Penny.
Is there any water in this kettle?
Yes, there is.
Where's the tea?
It's over there, behind the teapot.
Can you see it?
I can see the teapot,
but I can't see the tea.
There it is!
It's in front of you!
Ah, yes. I can see it now.
Where are the cups?
There are some in the cupboard.
Can you find them?
Yes. Here they are.
Hurry up, Sam!
The kettle's boiling!
* The boss's letter
** Text
Can you come here a minute please, Bob?
Yes, sir?
Where's Pamela?
She's next door.
She's in her office, sir.
Can she type this letter for me?
Ask her please.
Yes, sir.
Can you type this letter for the boss please, Pamela?
Yes, of course I can.
Here you are.
Thank you, Bob.
Bob!
Yes?
What's the matter?
I can't type this letter.
I can't read it!
The boss's handwriting is terrible!
** WORDS
*** handwriting | BrE ˈhandrʌɪtɪŋ, AmE ˈhæn(d)ˌraɪdɪŋ | noun uncountable
 ① (style) 笔迹 bǐjì
 ② (writing by hand) 书写 shūxiě
*** terrible 
terrible | BrE ˈtɛrɪb(ə)l, AmE ˈtɛrəb(ə)l | adjective
 ① (tragic) 可怕的 kěpà de ; (serious) 严重的 yánzhòng de ; (very unpleasant) 非常讨厌的 fēicháng tǎoyàn de
  ▸ a terrible blow 沉重的打击
  ▸ terrible poverty 赤贫
  ▸ a terrible fool/liar 大傻瓜/大骗子
  ▸ a terrible shame 奇耻大辱
 ② (unwell) 有病的 yǒubìng de
  ▸ to feel/look terrible 感觉不适/看上去有病
 ③ (guilty) 负疚的 fùjiù de
  ▸ to feel terrible about sth 对某事感到愧疚
 ④ (poor, awful) 糟糕的 zāogāo de ‹meal, performance, player›
  ▸ you look terrible in that hat 你戴那顶帽子难看死了
  ▸ to be terrible at sth/doing sth; 在某方面/做某事很差劲
 ⑤ (sinister) 骇人的 hàirén de ‹look, scream›
*** type 
type | BrE tʌɪp, AmE taɪp |
 A. noun
 ① countable (variety, kind) 类型 lèixíng
  ▸ a type of sth; 某物的一种
  ▸ all types of jobs, jobs of all types 各种各样的工作
  ▸ I'm not the or that type 我不是那种人
  ▸ this is definitely my type of place informal 这毫无疑问是我中意的那种地方
  ▸ he's not my type informal 他不是我喜欢的类型
 ② countable informal (person) 某种人 mǒu zhǒng rén
  ▸ an army type 军人一类的人
 ③ uncountable and countable Printing (for printing) 活字 huózì ; (on page) 字体 zìtǐ
  ▸ metal type 金属活字
  ▸ bold/italic type 黑体/斜体
  ▸ to be in type 付排
 ④ countable (archetype) 典型 diǎnxíng
  ▸ her characters are types rather than individuals 她塑造的人物是模式化的，缺乏个性
 B. -type combining form …类型的 … lèixíng de
  ▸ a documentary-type film 纪实类影片
 C. transitive verb
 ① (on typewriter, keyboard) 在…上打字 zài… shang dǎzì ‹page›; 键入 jiànrù ‹word›
  ▸ a typed letter 打印的信
  ▸ to type sth into a computer/on to a screen 把某内容输入电脑/打到屏幕上
  ▸ to type over a mistake 打错字
 ② (classify) 给…分型 gěi… fēnxíng ‹tissue›
  ▸ to type blood samples 给血样分类
  ▸ to be typed as sth; 被看作某类型
 D. intransitive verb 打字 dǎzì PHRASAL VERBS type in transitive verb [type sth in, type in sth]
 ① (on computer) 键入 jiànrù ‹word, command›
  ▸ to type in the file name 键入文件名
 ② (on typewriter) 打出 dǎchū ‹word, letter›type out transitive verb [type sth out, type out sth]
 ① (put in typed form) 打出 dǎchū ‹receipt, letter›
  ▸ I'd prefer it if you typed out the list 我希望你把单子打出来
 ② (erase) 打字覆盖 dǎ zì fùgài ‹error, name›
  ▸ if you make a mistake, you can just type it out 打错了就在上面再打字遮住
 type up transitive verb [type sth up, type up sth] 把…打出来 bǎ… dǎ chulai
 ‹note, draft, report, essay›

** Test
*** First
Can you come here a minute please, Bob?
Yes, sir.
Where's Pamela?
She's next door.
She's in the her office, sir.
Can she type this letter for me?
Ask her please.
Yes, sir.
Can you type this letter for the boss please, Pamela?
Yes, of course I can.
Here you are.
Bob?
Yes?
What's the matter?
I can't type this letter.
The boss's handwriting is terrible!
*** Second
Can you come here a minute please, Bob?
Yes, sir?
Where's Pamela?
She's next door.
She's in her office, sir.
Can she type this letter for me?
Ask her please.
Can you type this letter for the boss, Pamela?
Yes, of course I can.
Here you are.
Bob?
Yes?
What's the matter?
I can't type this letter.
I can't read it！
The boss's handwriting is terrible!
*** Third 
Can you come here a minute please, Bob?
Yes, sir?
Where's Pamela?
She's next door.
She's in her office, sir.
Can she type this letter for me?
Ask her please.
Yes, sir.
Can you type this letter for the boss please, Pamela?
Yes, of course I can.
Here you are.
Bob!
Yes?
What's the matter?
I can't type this letter.
I can't read it.
The boss's handwriting is terrible!
*** Forth
Can you come here a minute please, Bob?
Yes, sir.
Where's Pamela?
She's next door.
She's in her office, sir.
Can she type this letter for me.
Ask her please.
Yes, sir.
Can you type this letter for the boss please, Pamela?
Yes, of course I can.
Here you are.
Bob!
Yes?
What's the matter?
I can't type this letter.
I can's read it.
The boss's handwriting is terrible!
* A cup of coffee
** test
Do you like coffee, Ann?
Yes, I do.
Do you want a cup?
Yes, please. Christine.
Do you want any sugar?
Yes, please.
Do you want any milk?
No, thank you.
I don't like milk in my coffee.
I like black coffee.
Do you like biscuits?
Yes, I do.
Do you want one?
Yes, please.
** words
*** coffee
 A. noun
 ① uncountable (drink) 咖啡 kāfēi
 ② countable (cup) 一杯咖啡 yī bēi kāfēi
  ▸ three coffees, please 请来三杯咖啡
  ▸ black/white coffee 清咖/奶咖
 ③ uncountable (beans) 咖啡豆 kāfēidòu ; (ground) 研磨咖啡 yánmó kāfēi ; (powder) 咖啡粉 kāfēi fěn
 ④ uncountable (shrub) 咖啡树 kāfēi shù
 B. adjective (coffee-coloured) 咖啡色的 kāfēisè de ‹cloth, dress›
*** sugar
 A. noun
 ① uncountable (unrefined) [植物所含的] 糖 táng
  ▸ to refine sugar 炼糖
 ② uncountable and countable (refined) 食糖 shítáng
  ▸ brown/white sugar 红糖/白糖
  ▸ how many sugars do you take? 你要加多少糖？
  ▸ a sugar spoon 糖勺
 ③ (mainly US) informal (term of endearment) 亲爱的 qīn'ài de
  ▸ bye, sugar! 再见，宝贝儿！
 B. exclamation euphemistic informal 完了 wánle [表示恼怒]
  ▸ sugar! I've forgotten my wallet! 糟了！我忘带钱包了！
 C. transitive verb 在…中加糖 zài… zhōng jiā táng
  ▸ sugared almonds 糖衣杏仁
*** milk
 A. noun
 ① uncountable (general) 奶 nǎi
  ▸ a glass of milk 一杯牛奶
  ▸ to produce milk 泌乳
  ▸ to be in milk «animal» 在授乳期
  ▸ a land flowing with milk and honey 富饶之地
  ▸ the milk of human kindness 人的善良天性
  ▸ to be like milk and water 平淡无味
  ▸ it's no use or good crying over spilt milk proverb 覆水难收，后悔也无济于事
 ② uncountable Botany 白色汁液 báisè zhīyè
  ▸ the milk of a coconut 椰汁
 ③ uncountable and countable (cosmetic) 乳剂 rǔjì
 B. transitive verb
 ① Farming 挤…的奶 jǐ… de nǎi ‹cow›
 ② (extract) 抽取 chōuqǔ ‹sap, venom›
 ③ figurative (draw on) 消耗 xiāohào ‹resources›
  ▸ to milk the fund 动用资金
 ④ figurative (exploit) 榨取 zhàqǔ ‹money›; 套取 tàoqǔ ‹ideas›
  ▸ to milk sth/sb of sth, to milk sth from or out of sth/sb; 从某事物/某人处榨取某物
  ▸ to milk sth/sb dry 榨干某物/某人
  ▸ to milk the situation 趁机牟利自肥
  ▸ to milk sb's strength/enthusiasm 利用某人的体力/热情
  ▸ to milk the audience for applause 卖力地想博得观众的掌声
*** black coffee
black coffee	英[blæk ˈkɒfi]
美[blæk ˈkɔːfi]
网络	斋啡; 清咖啡; 清咖; 咖啡; 黑咖啡;
[例句]Newman poured more black coffee and lit a cigarette.
纽曼又倒了些黑咖啡，接着点了支烟
*** biscuits
biscuit | BrE ˈbɪskɪt, AmE ˈbɪskɪt |
 A. noun
 ① countable British (thin crisp cake) 饼干 bǐnggān
  ▸ plain/sweet biscuits 淡/甜饼干
  ▸ to take the biscuit British informal (be most surprising) 极为惊人 (be most annoying) 极其讨厌
 ② countable US (soft bread) 小松饼 xiǎo sōngbǐng
 ③ uncountable (colour) 淡褐色 dàn hèsè
 B. adjective 淡褐色的 dàn hèsè de

** test
*** First
Do you like coffee, Ann?
Yes, I do.
Do you want a cup?
Yes, please.
Do you want any sugar?
Yes, please. Christine.
Do you want any milk?
No, thank you.
I don't like milk in my coffee.
I like black coffee.
Do you like biscuits?
Yes, I do.
Do you want one?
Yes, please.
*** Second
Do you like coffee, Ann?
Yes, I do.
Do you want a cup?
Yes, please.
Do you want any sugar?
Yes, please. Christine.
Do you want any milk?
No, thank you.
I don't like milk in my coffee.
I like black coffee.
Do you like biscusts?
Yes, I do.
Do you want one?
Yes, please.
*** Third
Do you like coffee, Ann?
Yes, I do.
Do you want a cup?
Yes, please.
Do you like any sugar?
Yes, please. Christine.
Do you like any milk?
No, thank you.
I don't like milk in my coffee.
I like black coffee.
Do you like biscuits?
Yes, I do.
Do you want one?
Yes, please.

*** Forth
Do you like coffee, Ann?
Yes, I do.
Do you want a cup?
Yes, please.
Do you want any sugar?
Yes, please. Christine.
Do you want any milk?
No, thank you.
I don't like milk in my coffee?
I like black coffee.
Do you like biscuits?
Yes, I do.
Do you want one?
Yes, please.

*** Firth
Can you come here a minute please, Bob?
Yes, sir?
Where's Pamela?
She's next door.
She's in her office, sir.
Can she type this letter for me?
Ask her please.
Can you type this letter for the boss please, Pamela?
Yes, of course I can.
Here you are.
Thank you, Bob.
Bob!
Yes?
What's the matter?
I can't type this letter.
I can't read it!
The boss's handwriting is terrible!

*** Sixth
Can you come here a minute please, Bob?
Yes, sir?
Where's Pamela?
She's next door.
She's in her office, sir.
Can she type this letter for me?
Ask her please.
Yes, sir.
Can you type this letter for the boss please, Pamela?
Yes, of course I can.
Here you are.
Thank you, Bob.
Bob!
Yes?
What's the matter?
I can't type this letter.
I can't read it!
The boss's handwriting is terrible!
* At the Butchers
** Text
Do you want any meat today, Mrs. Bir?
Yes, please.
Do you want beef or lamb?
Beef, please.
This lamb's very good.
I like lamb,
but my husband doesn't.
What about some steak?
This is a nice piece.
Give me that piece, please.
And a pound of mince, too.
Do you want a chicken, Mrs. Bird?
They're are very nice.
No, thank you.
My husband likes steak, 
but he doesn't like chicken.
To tell you the truth, Mrs. Bird,
I don't like chicken either!
** Words
*** meat
meat	英[miːt]
美[miːt]
n.	肉类; (某种) 食用肉; 重要的部分; 有趣的部分;
[例句]Meat and fish are relatively expensive.
肉和鱼相对来说比较贵。
[其他]	复数：meats
*** beef
beef	英[biːf]
美[biːf]
n.	牛肉; 抱怨; 牢骚;
v.	老是抱怨; 大发牢骚;
[例句]Instead of beefing about what Mrs Martin has not done, her critics might take a look at what she is trying to do.
批评者不要老是抱怨马丁太太没有做什么事情，不妨看看她正要做什么事情。
[其他]	第三人称单数：beefs 现在分词：beefing 过去式：beefed
*** lamb

lamb	英[læm]
美[læm]
n.	羔羊; 小羊; 羊羔肉; (慈爱或怜悯地描述或称呼某人) 宝贝，乖乖;
v.	产羊羔;
[例句]She came and put her arms around me. 'You poor lamb. What's wrong?'
她走过来搂着我。“可怜的宝贝，出什么事儿啦？”
[其他]	复数：lambs
*** steak
steak	英[steɪk]
美[steɪk]
n.	牛排; 肉排; 肉块; 碎牛肉(不是最佳部位，常剁碎出售，可以炖或做馅等);
[例句]Waiter, I specifically asked for this steak rare.
服务员，我特别强调了这块牛排要做得嫩些。
[其他]	复数：steaks
*** mince
mince	英[mɪns]
美[mɪns]
v.	用绞肉机绞(食物，尤指肉); 装腔作势地小步快走;
n.	绞碎的肉，肉末(尤指牛肉);
[例句]Brown the mince in a frying pan.
在煎锅里把肉末煎至棕色。
[其他]	第三人称单数：minces 现在分词：mincing 过去式：minced 过去分词：minced
*** truth
truth	英[truːθ]
美[truːθ]
n.	真相; 实情; 事实; 真实情况; 真实; 真实性; 真理;
[例句]Is it possible to separate truth from fiction?
有可能把事实与虚构分开吗？
[其他]	复数：truths
** test
*** First
Do you want any meat today, Mrs. Bird?
Yes, please.
Do you want beef or lamb?
Beef, please.
This lamb's very good.
I like lamb,
but my husband doesn't.
What about some steak?
This is a nice piece.
Give me that piece, please.
And a pound of mince, too.
Do you want a chicken, Mrs. Bird?
They're very nice.
No, thank you.
My husband likes steak,
but he doesn't like chicken.
To tell you the truth, Mrs. Bird.
I don't like chicken either!
*** Second
Do you want any meat today, Mrs. Bird?
Yes, please.
Do you want beef or lamb?
Beef, please.
This lamp's very good.
I like lamb,
but my husband doesn't.
What about some steak?
This is a nice piece.
Give me that peice, please.
And a pound of mince, too.
Do you want a chicken, Mrs. Bird?
They're very nice.
No, thank you.
My husband likes steak,
but he doesn't like chicken.
To tell you the truth, Mrs. Bird.
I don't like chicken either!
*** Third
Do you want any meat today, Mrs. Bird?
Yes, please.
Do you want beef or lamb?
Beef, please.
This lamb's very good.
I like lamb,
but my husband doesn't.
What about some steak?
This is a very nice peice.
Gave me that peice, please.
And a pound of mince, too.
Do you want a chicken, Mrs. Bird?
They're very nice.
No, thank you. 
My husband likes steak,
but he doesn't like chicken.
To tell you the truth, Mrs. Bird.
I don't like chicken either!

* Interesting climate
** Text
Where do you come from?
I come from England.
What's the climate[fn:2] like in your country?
It's mild[fn:3],
but it's not always pleasant[fn:1].
The weather's often cold in the North and windy[fn:4] in the East.
It's often wet[fn:5] in the West and sometimes warm in the south.
Which seasons[fn:6] do you like best?
I like spring and summer.
The days are long and the nights are short.
I don't like autumn and winter.
The days are short and the nights are long.
The sun rises late and set[fn:7] early.
Our climate is not very good.
but it's certainly interesting.
It's our favorite[fn:8] subject[fn:9] of conversation[fn:10].
** Test
*** First
Where do you come from? 
I come from England.
What's the climate like in your country?
It's mild.
but it's not always pleasant.
The weather's often cold in the North and windy in the East.
It's often wet in the West and sometimes warm in the south.
Which seasons do you like best?
I like spring and summer.
The days are long and the nights are short.
I don't like autumn and winter.
The days are short and the nights are long.
The sun rises late and set early.
Our climate is not very good.
but it's certainly interesting.
It's our favorite subject of conversation.
*** Second
Where do you come from?
I come from England.
What's the climate like in your country?
It's mild.
The weather's often cold in the North,
and windy in the East.
It's often wet in the West and sometimes warm in the south.
Which seasons do you like best?
I like spring and summer.
The days are long and the nights are short.
I don't like autumn and winter.
The days are short and the nights are long.
The sun rises late and set early.
Our climate is not very good,
but it's certainly interesting.
It's our favorite subject of conversation.
*** Third
Where do you come from?
I come from England.
What's the cilmate like in your country?
It's mild.
but it's not always pleasant.
The weather's often cold in the North and windy in the East.
It's often wet in the West and sometimes warm in the South.
Which seasons do you like best?
I like spring and summer.
The days are long and the nights are short.
I don't like autumn and winter. 
The days are short and the nights are long.
The sun rises late and set early.
Our climate is not very good.
but it's certainly interesting.
It's our favorite subject of conversation.

* Sawyer's family
** Text
The Sawyer live at 87 King street.
In the morning, Mr. Sawyer goes to work and the children go to school..
Mrs. Sawyer stays at home every day.
She does the housework.
She always eats her lunch at noon.
In the afternoon, she usually sees her friends.
They often drink tea together.
In the evening, the children come home from school.
They arrive home early.
Mr. Sawyer comes home from work.
He arrives home late.
At night, the children always do their homework.
Then they go to bed.
Mr. Sawyer usually reads his newspaper,
but sometimes he and his wife watch television.
** Test
*** First
The Sawyer live at 87 King Street.
In the morning, Mr. Sawyer goes to work and the children go to school.
Mrs. Sawyer stays at home every day.
She does the housework.
She always eats her lunch at noon.
In the afternoon, she usually sees her friends.
They often drink tea together.
In the evening, the children come home from school.
They arrive home early.
Mr. Sawyer comes home from work. 
He arrives home late.
At night, the children always do their homework.
Then they go to bed.
Mr. Sawyer usually reads his newspaper, but sometimes he and his wife watch television.
*** Second
The Sawyer live at 87 King Street.
In the morning, Mr. Sawyer goes to work and the children go to school.
Mrs. Sawyer stays at home every day.
She does the housework.
She always eats her lunch at noon.
In the afternoon, Mrs. Sawyer usually sees her friends.
They often drink tea together.
In the evening, the children come home from school.
They arrive home early.
Mr. Sawyer comes home from work.
He arrives home late.
At night, the children always do their homework.
Then they go to bed.
Mr. Sawyer usually reads his newspaper at night.
But sometimes he and his wife watch television.
*** Third
The Sawyer live at 87 King Street.
In the morning, Mr. Sawyer goes to work and the children go to school.
Mrs. Sawyer stays at home every day.
She does the housework.
She always eats her lunch at noon.
In the afternoon, Mrs. Sawyer usually sees her friends.
They often drink tea together.
In the evening, the children come home from school.
They arrive home early.
Mr. Sawyer comes home from work.
He arrives home late.
At night, the children always do their homework.
Then they go to bed.
Mr. Sawyer usually reads his newspaper at night,
but sometimes he and his wife watch television.
*** Forth
The Sawyer live at 87 King Street.
In the morning, Mr. Sawyer goes to work and the children go to school.
Mrs. Sawyer stays at home every day.
She does the housework.
She always eats her lunch at noon.
In the afternoon, Mrs. Sawyer usually sees her friends.
They often drink tea together.
In the evening, the children come home from school.
They arrive home early.
Mr. Sawyer comes home from work.
He arrives home late.
At night, the children always do their homework.
Then they go to bed.
Mr. Sawyer usually reads his newspaper at night.
But sometimes he and his wife watch television.
* Unusuall days
** text 
#+BEGIN_VERSE 
  
It is eight o'clock.
The children go to school by car every day, but today, they are going to school on foot.
It is ten o'clock. Mrs. Sawyer usually stays at home in the morning, 
but this morning, she is going to the shops.
It is four o'clock.
In the afternoon, Mrs. Sawyer usually drinks tea in the living room.
But this afternoon, she is drinking tea in the garden.
It is six o'clock.
In the evening, the children usually do their homework,
but this evening, they are not doing their homework.
At the moment, they are playing in the garden.
It is nine o'clock.
Mr. Sawyer usually reads his newspaper at night.
But he's not reading his newspaper tonight.
At the moment, he's reading an interesting book.

#+END_VERSE
** words
*** on foot 
on foot	英[ɒn fʊt]
美[ɑːn fʊt]
[词典]	步行; 走路去;
[例句]I go to school usually on foot.
我上学通常是走路去。
*** living room
living room
英[ˈlɪvɪŋ ruːm]
美[ˈlɪvɪŋ ruːm]
n.	客厅; 起居室;
[例句]We were sitting on the couch in the living room watching TV.
我们就坐在客厅的沙发上看电视。
[其他]	复数：living rooms
*** at the moment
at the moment
英[æt ðə ˈməʊmənt]
美[æt ðə ˈmoʊmənt]
[词典]	此刻; 目前; 眼下;
[例句]I remember now. He arrived just at the moment it happened
现在我想起来了，他恰恰在事情发生的时候到了。
*** tonight 
tonight	英[təˈnaɪt]
美[təˈnaɪt]
adv.	在今夜; 在今晚;
n.	今夜; 今晚;
[例句]I'm at home tonight
我今晚在家。
** test 
*** First
 It is eight o'clock.
 The children usually go to school by car every day, 
 but today, they are going to school on foot.
 It is ten o'clock. Mrs. Sawyer usually stays at home in the morning,
 but this morning, she is going to the shops.
 It is four o'clock.
 In the afternoon, Mrs. Sawyer usually drinks tea in the living room, 
 But this afternoon, she is drinking tea in the garden.
 It is six o'clock.
 In the evening, the children usually do their homework,
 but this evening, they are not doing their homework.
 At the moment, they are playing in the garden.
 It is nine o'clock.
 Mr. Sawyer usually reads his newspaper at night.
 But he's not reading his newspaper tonight.
 At the moment, He's reading an interesting book.
*** Second
It is eight o'clock.
The children usually go to school by car every day, 
but today, they are going to school on foot.
It is ten o'clock. Mrs. Sawyer usually stays at home in the morning, 
but this morning, she is going to the shops.
It it four o'clock.
In the afternoon, Mrs. Sawyer usually drinks tea in the living room.
But this afternoon, she is drinking tea in the garden.
It is six o'clock.
In the evening, the children usually do their homework,
but this evening, they are not doing their homework.
At the moment, they are playing in the garden.
It is nine o'clock.
Mr. Sawyer usually reads his newspaper at night,
but he's not reading his newspaper tonight.
At the moment, he's reading an interesting book.
*** Third
It is eight o'clock.
The children go to school by car every day, 
but today, they are going to school on foot.
It is ten o'clock. Mrs. Swayer usually stays at home in the morning,
but this morning, she is going to the shops.
It is four o'clock.
In the afternoon, Mrs. Sawyer usually drinks tea in the living room.
But this afternoo, she is drinking tea in the garden.
It is six o'clock.
In the evening, the children usually do their homework,
but this evening, they are not doing their homework.
At the moment, they are playing in the garden.
It is nine o'clock.
Mr. Sawyer usually reads his newspaper at night.
But he's not reading his newspaper tonight.
At the moment, He's reading an interesting book.
*** Forth
It is eight o'clock.
The children go to school by car every day,
but today, they are going to school on foot.
It is ten o'clock. Mrs. Sawyer usually stays at home in the morning,
but this morning, she is going to the shops.
It is four o'clock.
In the afternoon, Mrs. Sawyer usually drinks tea in the living room.
But this afternoon, she is drinking tea in the garden.
It is six o'clock.
In the evening, the children usually do their homework,
but this evening, they are not doing their homework.
At the moment, they are playing in the darden.
It is nine o'clock.
Mr. Sawyer usually reads his newspaper at night.
But he's not reading his newspaper tonight.
At the moment, he's reading an interesting book.
*** Fifth
It is eight o'clock.
The children go to school by car every doy,
but today, they are going to school on foot.
It is ten o'clock. Mrs. Sawyer usually stays at home in the morning, 
but this morning, she is going to the shops.
It is four o'clock.
In the afternoon, Mrs. Sawyer usually drinks tea in the living room.
But this afternoon, she is drinking tea in the garden.
It is six o'clock.
In the evening, the children usually do their homework,
but this evening, they are not doing their homework.
At the moment, they are playing in the garden.
It is nine o'clock.
Mr. Sawyer usually reads his newspaper at night.
But he's not reading his newspaper tonight.
At the moment, he's reading an interesting book.
* Is that all?
I want some envelopes, please.
Do you want the large size or the small size?
The large size, please.
Do you have any writing paper?
Yes, we do.I don't have any small pads.
I only have large one.
Do you want a pad?
Yes, please.
And I want some glue.
A bottle of glue.
And I want a large box of chalk, too.
I only have small boxes.
Do you want one?
No, thank you.
Is that all?
That's all, thank you.
What else do you want?
I want my change.
** Words
*** envelope 
envelope	英[ˈenvələʊp]
美[ˈenvəloʊp]
n.	信封; 塑料封套; 塑料封皮;
[例句]There's a valuable place for fashion and design that pushes the envelope a bit
在原有尺度上有所突破的时尚和设计受到人们的重视。
[其他]	复数：envelopes
*** pad
pad	英[pæd]
美[pæd]
n.	(吸收液体、保洁或保护用的) 软垫，护垫，垫状物; 便笺本; 拍纸簿; 爪垫; 肉掌;
v.	(用软材料) 填充，覆盖，保护; 蹑手蹑脚地走; 虚报(账目); 做黑账;
[例句]He withdrew the needle and placed a pad of cotton-wool over the spot.
他把针头拔出，在扎针处按了一块药棉。
[其他]	第三人称单数：pads 复数：pads 现在分词：padding 过去式：padded 过去分词：
padded
*** glue
glue	英[ɡluː]
美[ɡluː]
n.	胶; 胶水;
v.	(用胶水) 粘合，粘牢，粘贴;
[例句]Glue the fabric around the window
用胶水把布料粘在窗户周围。
[其他]	第三人称单数：glues 复数：glues 现在分词：glueing 过去式：glued 过去分词：
glued
*** chalk
chalk	英[tʃɔːk]
美[tʃɑːk]
n.	白垩; (白色或彩色的) 粉笔;
v.	用粉笔写(或画);
[例句]Her skin was chalk white and dry-looking.
她的皮肤看上去苍白发干。
[其他]	第三人称单数：chalks 现在分词：chalking 过去式：chalked 过去分词：
chalked
*** change
change
英 [tʃeɪndʒ]   美 [tʃeɪndʒ]  
v.
改变;变化;使不同;(使)变换，改换，变成
n.
改变;变化;变更;变革;(会令人感兴趣或可喜的)变化;替代;更换;替代物;零钱。
第三人称单数： changes 复数： changes 现在分词： changing 过去式： changed 过去
分词： changed
** Test
*** First
I want some envelopes, please.
Do you want the large size or the small size?
The large size, please.
Do you have any writing paper?
Yes, we do.
I only have the large one.
Do you want a pad?
Yes, please.
And I want some glue.
A bottle of glue.
And I want a large box of chalk, too.
I only have small boxes.
Do you want one?
No, thank you.
Is that all?
That's all, thank you.
What else do you want?
I want my change.
*** Second
I want some envelopes, please.
Do you want the large size or the small size?
The large size, please.
Do you have any writing paper?
Yes, we do.
I don't have any small pads.
I only have large one. 
Do you want one?
Yes, please.
And I want some glue.
A bottle of glue.
And I want a large box of chalk, too.
I only have small boxes.
Do you want one?
No, thank you.
Is that all?
That's all, thank you.
What else do you want?
I want my change.
*** Third
I want some envelopes, please.
Do you want the large size or the small size?
The large size, please.
Do you have any writing paper?
Yes, we do.
I don't have any small pads.
I only have large one.
Do you want a pad?
Yes, please.
And I want some glue.
A bottle of glue.
And I want a large box of chalk, too.
I only have small boxes.
Do you want one?
No, thank you.
Is that all?
That's all, thank you.
What else do you want?
I want my change.
*** Forth
I want some envelopes, please.
Do you want the large size or the small size?
The large size, please.
Do you have any writing paper?
Yes, we do.
I don't have any small pads.
I only have large one.
Do you want a pad?
Yes, please.
And I want some glue.
A bottle of glue.
And I want a large box of chalk, too.
I only have small boxes.
Do you want one?
No, thank you.
It that all?
That's all, thank you.
What else do you want?
I want my change.

* Bad cold
** Text
Where's Jimmy?
He's in bed.
What's the matter with him?
He feels ill.
He looks ill.
We must call the doctor.
Yes, we must.
Can you remember the doctor's telephone number?
Yes. It's 09754.
Open your mouth, Jimmy.
Show me your tongue.
Say,"Ah."
What's the matter with him, doctor?
He has a bad cold. Mr. Williams, 
so he must stay in bed for a week.
That's good news for Jimmy.
Good news? Why?
Because he doesn't like school!
** test
*** First
Where's Jimmy?
He's in bed.
What's matter with him?
He feels ill.
He looks ill.
We must call the doctor.
Yes, we must.
Can you remember the doctor's telephone number?
Yes. It's 09754.
Open your mouth, Jimmy.
Show me your tongue.
Say, "Ah."
What's the matter with him, doctor?
He has a bad cold, Mr. Williams,
so he must stay in bed for a week.
That's good news for Jimmy.
Good news? Why?
Because he doesn't like the school!
*** Second
Where's Jimmy?
He's in bed.
What's the matter with him?
He feels ill.
He looks ill.
We must call the doctor.
Yes, we must.
Can you remember the doctor's telephone number?
Yes. It's 09754.
Open your mouth, Jimmy.
Show me your tongue.
Say, "Ah."
What's the matter with him, doctor?
He has a bad cold, Mr. Williams,
so he must stay in bed for a week.
That's good news for Jimmy.
Good news? Why?
Because he doesn't like school!
*** Third
Where's Jimmy?
He's in bed.
What's the matter with him?
He feels ill.
He looks ill.
We must call the doctor.
Yes, we must.
Can you remember the doctor's telephone number?
Yes, it's 09754.
Open your mouth, Jimmy.
Show me your tongue.
Say, "Ah."
What's the matter with him, doctor?
He has a bad cold, Mr. Williams,
so he must stay in bed for a week.
That's good news for Jimmy?
Good news? Why?
Because he doesn't like the school!
*** Forth
Where's Jimmy?
He's in bed.
What's the matter with him?
He feels ill.
He looks ill.
We must call the doctor.
Yes, we must.
Can you remember the doctor's telephone number?
Yes, it's 09754.
Open your mouth Jimmy.
Show me your tongue.
Say, 'Ah.'
What's the matter with him, doctor?
He has a bad cold, Mr. Williams, 
so he must stay in bed for a week.
That's good news for Jimmy.
Good news? Why?
Because he doesn't like school!
 
* Thank you. Doctor
How's Jimmy today?
Better. Thank you, Doctor.
Can I see him please, Mrs. Williams?
Certainly, doctor.
Come up stairs.
You look very well, Jimmy.
You are better now, 
but you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams.
And he mustn't eat rich food.
Does he have a temperature, doctor?
No, he doesn't.
Must he stay in bed?
Yes. He must remain in bed for another two days.
He can get up for about two hours each day, 
but you must keep the room warm.
Where's Mr. Williams this evening?
He's in bed, doctor.
Can you see him please?
He has a bad cold, too!
** words
*** remain

remain	英[rɪˈmeɪn]
美[rɪˈmeɪn]
v.	仍然是; 保持不变; 剩余; 遗留; 继续存在; 仍需去做(或说、处理);
[例句]The three men remained silent
这 3 个人保持着沉默。
[其他]	第三人称单数：remains 现在分词：remaining 过去式：remained 过去分词：
remained
*** stairs 
stairs	英[steəz]
美[stɛrz]
n.	楼梯; 梯级;
[词典]	stair 的复数;
[例句]We walked up a flight of stairs
我们上了一段楼梯。
[其他]	原型： stair
** test
*** First
How's Jimmy today?
Better. Thank you. Doctor.
Can I see him please, Mrs. Williams?
Certainly. Doctor.
Come up stairs.
You look very well, Jimmy.
You are better now, 
but you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams.
And he mustn't eat rich food.
Does he have a temperature, doctor?
No, he doesn't.
Must he stay in bed?
Yes, he must remain in bed for another two days.
He can get up for about two hours each day,
but you must keep the room warm.
Where's Mr. Williams this evening?
He's in bed, doctor.
Can you see him please?
He has a bad cold, too!
*** Second
How's Jimmy today?
Better. Thank you, Doctor.
Can I see him please, Mrs. Williams? 
Certainly, doctor.
Come up stairs.
You look very well, Jimmy.
You are better now, 
but you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams.
And he mustn't eat rich food.
Does he have a temperature，doctor? 
No, he doesn't.
Must he stays in bed?
Yes, he must remain in bed for another two days,
He can get up for about two hours each day,
but you must keep the room warm.

Where's Mr. Williams this evening? 
He's in bed, doctor.
Can you see him please?
He has a bad cold, too!
*** Third 
How's Jimmy today?
Better. Thank you, Doctor.
Can I see him please, Mrs. Williams? 
Certainly, doctor.
Come up stairs.
You look very well, Jimmy.
You are better now, 
but you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams,
and he mustn't eat rich food.
Does he have a temperature, doctor? 
No, he doesn't.
Must he stay in bed?
Yes, he must remain in bed for another two days.
He can get up for about two hours each day, 
but you must keep the room warm.
Where's Mr. Williams this evening?
He's in bed, doctor.
Can you see him please?
He has a bad cold, too!
*** Forth
How's Jimmy today?
Better. Thank you, Doctor.
Can I see him please, Mrs. Williams? 
Certainly, doctor.
Come up stairs.
You look very well, Jimmy.
You are better now.
But you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams.
And he mustn't eat rich food.
Does he have a temperature, doctor? 
No, he doesn't.
Must he stay in bed?
Yes. He must remain stay in bed for another two days.
He can get up for about two hours each day, 
but you must keep the room warm.
Where's Mr. Williams this evening? 
He's in bed, doctor.
Can you see him please?
He has a bad cold, too!
*** Fifth
How's Jimmy?
Better. Thank you, doctor.
Can I see him please, Mrs. Williams?
Certainly, doctor.
Come up stairs.
You look very well, Jimmy.
You are better now,
but you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams.
And he mustn't eat rich food.
Does he have a temperature, doctor?
No, he doesn't.
Must he stay in bed?
Yes. He must remain in bed for another two days.
He can get up for about two hours each day, 
but you must keep the room warm.
Where's Mr. Williams this evening?
He's bed, doctor.
Can you see him please?
He has a bad cold, too!
*** Seventh
How's Jimmy today?
Better. Thank you. Doctor.
Can I see him please, Mrs. Williams?
Certainly, doctor. 
Come up stairs.
You look very well, Jimmy.
You are better now,
but you mustn't get up yet.
You must stay in bed for another two days.
The boy mustn't go to school yet, Mrs. Williams.
And he mustn't eat rich food.
Does he have a temperature, doctor?
No, he doesn't.
Must he stay in bed?
Yes. He must remain stay in bed for another two days.
He can get up for about two hours each day, 
but you must keep the room warm.
Where's Mr. Williams this evening? 
He's in bed, doctor.
Can you see him please?
He has a bad cold, too!

* Not a same baby
What are you going to do this evening, Jill?
I'm going to meet some friends, Dad.
You mustn't come home late.
You must be home at half past ten.
I can't get home so early, Dad!
Can I have the key to the front door please?
No, you can't.
Jill's eighteen years old, Tom.
She's not a baby.
Give her the key.
She always comes home early.
Oh, all right!
Here you are.
But you mustn't come home after a quarter past eleven.
Do you hear?
Yes, Dad.
Thanks, Mum.
That's all right. Goodbye.
Enjoy youselef!
We always enjoy ourselves, Mum.
Bye-bye.
** Words
*** meet

meet	英[miːt]
美[miːt]
v.	相遇; 相逢; 遇见; 开会; 会晤; (与…) 会面; 集合;
n.	体育比赛; 运动会; 猎狐运动;
[例句]I have just met the man I want to spend the rest of my life with
我刚刚遇到了我想与之共度余生的男人。
[其他]	第三人称单数：meets 复数：meets 现在分词：meeting 过去式：met 过去分词：
met
*** home
home	英[həʊm]
美[hoʊm]
n.	家; 住所; (可买卖的) 房子，住宅，寓所; 家乡; 故乡; 定居地;
adj.	家的; 家庭的; 在家里做的; 家用的; 本国的; 国内的;
adv.	到家; 向家; 在家; 到正确的位置;
[例句]Last night they stayed at home and watched TV
昨晚他们呆在了家里看电视。
[其他]	第三人称单数：homes 复数：homes 现在分词：homing 过去式：homed 过去分词：
homed
*** get home
get home	英[ɡet həʊm]
美[ɡet hoʊm]
[词典]	抵家;
[例句]Come along, lad. Time for you to get home.
来吧，小伙子。你该回家了。
*** quarter
quarter	英[ˈkwɔːtə(r)]
美[ˈkwɔːrtər]
n.	四等份之一; (正点之前或之后的) 15 分钟，一刻钟; 三个月时间; 季度; 季;
v.	把…切成(或分成)四部分; 给…提供食宿;
[例句]The group said results for the third quarter are due on October 29.
该集团表示第三季度的结果将于 10 月 29 日公布。
[其他]	第三人称单数：quarters 复数：quarters 现在分词：quartering 过去式：quartered 过去分词：quartered
*** hear
hear	英[hɪə(r)]
美[hɪr]
v.	听见; 听到; 听; 注意听; 倾听; 听说; 得知;
[例句]She heard no further sounds
她再没有听到别的声音了。
[其他]	第三人称单数：hears 现在分词：hearing 过去式：heard 过去分词：heard
*** enjoy
enjoy	英[ɪnˈdʒɔɪ]
美[ɪnˈdʒɔɪ]
v.	享受…的乐趣; 欣赏; 喜爱; 过得快活; 玩得痛快; 得到乐趣; 享有; 享受;
[例句]Ross had always enjoyed the company of women
罗斯总是喜欢有女人陪伴。
[其他]	第三人称单数：enjoys 现在分词：enjoying 过去式：enjoyed 过去分词：
enjoyed
enjoy yourself
英[ɪnˈdʒɔɪ jɔːˈself]
美[ɪnˈdʒɔɪ jɔːrˈself]
[词典]	祝你玩得开心; 祝你玩得痛快; 尽情享受;
[例句]Get out and enjoy yourself, make new friends.
出去走走，好好玩玩，交些新朋友。
** Test
*** First
What are you going to do this evening, Jill?
I'm going to meet some friends, Dad.
You mustn't come home late.
You must be home at half past ten.
I can't get home so early, dad.
Can I have the key to the front door, please.
No, you can't!
Jill's eighteen years old, Tom.
She's not a baby.
Give her the key.
She always comes home early.
Oh, all right.
Here you are.
But you mustn't come home after a quarter past eleven.
Do you hear?
Yes, Dad.
Thanks, Mum.
That's all right. Goodbye.
Enjoy yourself.
We always enjoy ourselves, Mum.
Bye-bye.
*** Second
What are you going to do this evening, Jill?
I'm going to meet some friends, Dad.
You mustn't come home late.
You must be home at half past ten.
I can't get home so early, Dad!
Can I have the key to the front door please?
No, you can't.
Jill's eighteen years old, Tom.
She's not a baby.
Give her the key.
She always comes home early.
Oh! all right.
Here you are.
But you mustn't come home after a quarter past eleven.
Do you hear?
Yes, Dad.
Thinks, Mum.
That's all right. Goodbye.
Enjoy yourself!
We always enjoy ourselves, Mum.
Bye-bye.
语序错了一句。
*** Third
What do you going to do this evening, Jill?
I'm going to meet some friends, Dad.
You mustn't come home late.
You must be home at half past ten.
I can't get home so early, Dad!
Can I have the key to the front door please?
No, you can't.
Jill's eighteen years old, Tom.
She's not a baby.
Give her the key.
Oh! All right.
Here you are.
But you mustn't come home after a quarter past eleven.
Do you here?
Yes, dad.
Thanks, Mum.
That's all right. Boodbye.
Enjoy yourself!
We always enjoy ourselves, Mum. 
Bye-bye.

* Weekend
Hello. Were you at the butcher's?
Yes. I was.
Were you at butcher's, too?
No, I wasn't.
I was at the greengrocer's.
How's Jimmy today?
He's very well, thank you.
Was he absent from school last week?
Yes, he was.
He was absent on Monday, Tuesday, Wednesday and Thursday.
How are you all keeping?
Very well, thank you.
We're going to spend three days in the country.
We're going to stay at my mother's for the weekend.
Friday, Saturday and Sunday in the country!
Aren't you luck!
** Test
*** First
Hello. Were you at the butcher's?
Yes, I was.
Were you at the butcher's, too?
No, I wasn't.
I was at the greengrocer's.
How's Jimmy today?
Very well. Thank you.
Was he absent from school last wee?
Yes, he was.
He was absent on Monday, Tuesday, Wednesday and Thursday.
How are you all keeping?
Very well, thank you.
We're going to spend three days in the country.
We're going to stay at my mother's for the weekend.
Friday, Saturday and Sunday in the country!
Aren't you luck!
*** Second
Hello. Were you at the butcher's?
Yes, I was.
Were you at the butcher's, too?
No, I wasn't.
How's Jimmy today?
He's very well, thank you.
Was he absent from school last week?
Yes, he was.
He was absent on Monday, Tuesday, Wednesday and Thursday.
How are you all keeping?
Very well, thank you.
We're going to spend three days in the country.
We're going to stay at my mother's for the weekend,
Friday, Saturday and Sunday in the country!
Aren't you luck!
*** Third
Hello. Were you at the butcher's? 
Yes, I was.
Were you at butcher's, too?
No, I wasn't.
I was at the greengrocer's.
How's Jimmy today?
He's very well, thank you.
Was he absent from school last week?
Yes, he was.
He was absent on Monday, Tuesday, Wednesday and Thursday.
How are you all keeping? 
Very well, thank you.
We're going to spend three days in the country.
We're going to stay at my mother's for the weekend.
Friday, Saturday and Sunday in the country!
Aren't you luck!

Very good!
*** Forth
Hello. Were you at the butcher's?
Yes, I was.
Were you at butcher's, too?
No, I wasn't.
I was at the greengrocer's.
How's Jimmy today? He's very well, thank you.
Was he absent from school last week? 
Yes, he was.
He was absent on Monday, Tuesday, Wednesday and Thurday.
How are you all keeping?
Very well, thank you.
We're going to spend three days in the country.
We're going to stay at my mother's for the weekend.
Friday, Saturday and Sunday in the country.
Aren't you luck!
** words
*** week
this week next week last week
a week ago, the week before last
*** day of a week
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
What day is it today?
Sunday is a holiday.
Today is Saturday.
I'm so tired. I wish today was Saturday.
Today is Saturday. It's a day off.
Today is Saturday. I get up very early on.

* Car race

There is a car race near our town every year.
In 1995, there was a very big race.
There were hundreds of people there.
My wife and I were at the race.
Out friends Julie and Jack were there, too.
You can see us in the crowd.
We are standing on the left.
There are twenty cars in the race.
There were English cars, French cars, German cars. Italian cars. American cars
and Japanses cars.
It was an exciting finish.
The winner was Billy Stewart.
He was in car number fifteen.
Five other cars were just behind him.
On the way home, my wife said to me.
'Don't drive so quickly! You're not Billy Stewart!'
** Test
*** First
There is a car race near out town every year.
In 1995, there was a very big race.
There were hundreds of people there.
My wife and I were at the race.
Our friends Julie and Jack were there, too.
You can see us in the crowd.
We are standing on the left.
There were twenty cars in the race.
There were English cars, French cars, German cars. Italian cars, American cars
and Japanese cars.
It was an exciting finish.
The winner was Billy Stewart.
He was in car number fifteen.
Five other cars were just behind him.
On the way home, my wife said to me.
'Don't drive so quickly! You're not Billy Stewart!'
*** Second
There is a car race near our town every year.
In 1995, there was a very big race.
There were hundreds of people there.
My wife and I were at the race.
Our friends Julie and Jack were there, too.
You can see us in the crowd.
We are standing on the left.
There were twenty cars in the race.
There were English cars, French cars, German cars. Italian cars, American cars
and Japanese cars.
It was an exciting finish.
The winner was Billy Stewart. 
He was in car number fifteen.
Five other cars were just behind him.
On the way home, my wife said to me.
'Don't drive so quickly! You're not Billy Stewart!'
*** Third
There is a car race near our town every year.
In 1995, there was a very big race.
There were hundreds of people there.
My wife and I were at the race.
Our friends Julie and Jack were there, too.
You can see us in the crowd.
We are standing on the left.
There were twenty cars in the race.
They were English cars, French cars, German cars. Italian cars, American cars and
Japanese cars.
It was an exciting finish.
The winner was Billy Steward.
He was in car number fifteen.
Five other cars were just behind him.
On the way home, my wife said to me.
'Don't drive so quickly! You're not Billy Stewart!'
*** Forth
There is a car race near our town every year.
In 1995, there was a very big race.
There were hundreds of people there.
My wife and I were at the race.
Our friends Julie and Jack were there, too.
You can see us in the crowd.
We are standing on the left.
There were twenty cars in the race.
There were English cars, French cars, German cars. Italian cars, American cars
and Japanese cars.
It was an exciting finish.
The winner is Billy Stewart.
He was in car number fifteen.
Five other cars were just behind him.
On the way home, my wife said to me.
'Don't drive so quickly! You're not Billy Stewart!'
*** Fifth
There is a car race near our town every year.
In 1995, there was a very big race.
There were hundreds of people there.
My wife and I were at the race.
Our friends Julie and Jack were there, too.
You can see us in the crowd.
We are standing on the left.
There were twenty cars in the race.
There were English cars, French cars, German cars. Italian cars, American cars
and Japanese cars.
It was an exciting finish.
The winner was Billy Stewart!
He was in car number fifteen.
Five other cars were just behind him.
On the way home, my wife said to me.
'Don't drive so quickly! You're not Billy Stewart!'

** words
*** race
 race	英[reɪs]
 美[reɪs]
 n.	赛跑; 速度竞赛; 竞争; 角逐; 赛马会; 种族; 人种; 血统;
 v.	(和…) 比赛; 参加比赛; 使比赛; 让…参加速度比赛; (使) 快速移动，快速运转;
 [例句]The women's race was won by the American, Patti Sue Plumer.
 女子赛跑的冠军被美国人帕蒂·休·普卢默夺得。
 [其他]	第三人称单数：races 复数：races 现在分词：racing 过去式：raced 过去分词：
 raced
*** hundred
 hundred	英[ˈhʌndrəd]
 美[ˈhʌndrəd]
 num.	一百; 许多; 大量; 100 到 999 间的数目; 百位数;
 [例句]According to one official more than a hundred people have been arrested.
 一名官员称有一百多人被捕。
 [其他]	复数：hundreds
*** hundreds of
 成百上千
 hundred and hundreds of
 区别
 | 搭配不同                | 含义不同               |
 |-------------------------+------------------------|
 | 数字/a+hundred+名词复数 | 具体（一、二、三 \百） |
 | hundreds of +名词复数   | 笼统数百               |
 |-------------------------+------------------------|

 1.数字/a+hundred+可数名词复数
 表示具体数目
 five hundred cars
 五百辆汽车
 a hundred boys
 一百个男孩子
 I have three hundred books.
 我有三百本书。
 【注意：hundred 是单数，名词前没有 the 或其他修饰词】

 2.hundreds of+可数名词复数
 表示“数百、成百上千”的笼统数目
 hundreds of cars
 数百辆汽车
 I have hundreds of books.
 我有数百本书。
 【注意：hundreds 复数，后有 of，名词前没有 the 或其他修饰词】
 3.拓展 TIPS:
 1)表示...当中的...，须加 of
 数字+hundred+of+the+可数名词复数
 数字+hundred of us/them/these/those...

 three hundred of the people
 这些人当中的三百人

 three hundred of us 
 我们当中的三百人

 Five hundred of the students are there.
 这些学生当中的 500 人在这里。
 Five hundred students are here.
 500 位学生在这里。
 2）a few/several+hundred+可数名词复数
 a few/several hundred people
 几百人
 hundred 与具体数字或 a,a few, several, many 等连用时，不能加 s。
 以上为 hundred 和 hundreds of 区别。
 对于 thousand 和 million 的用法，与此类似。
*** crowd 
 crowd	英[kraʊd]
 美[kraʊd]
 n.	人群; 观众; 一伙人; 一帮人; 群众; 民众; 老百姓; 凡夫俗子;
 v.	挤满; 塞满; 使…拥挤; 涌上(心头); 涌入(脑海); 挤，靠近，挤在一旁(以致使人不舒服或紧张);
 [例句]A huge crowd gathered in a square outside the Kremlin walls
 一大群人聚集在克里姆林宫墙外的广场上。
 [其他]	第三人称单数：crowds 复数：crowds 现在分词：crowding 过去式：crowded 过去分词：crowded
*** exciting
exciting	英[ɪkˈsaɪtɪŋ]
美[ɪkˈsaɪtɪŋ]
adj.	令人激动的; 使人兴奋的;
v.	使激动; 使兴奋; 刺激; 使紧张不安; 激发; 引发; 引起;
[词典]	excite 的现在分词;
[例句]The race itself is very exciting
比赛本身非常刺激。
[其他]	原型： excite  比较级：more exciting 最高级：most exciting
*** winner
winner	英[ˈwɪnə(r)]
美[ˈwɪnər]
n.	获胜的人(或队、动物等); 优胜者; 成功者; 可能成功的人(或事物); 制胜的一记入球; 赢得比赛的一分;
[例句]She will present the trophies to the award winners
她将给获奖者颁奖。
[其他]	复数：winners
*** just
just	英[dʒʌst]
美[dʒʌst]
adv.	正好; 恰好; 正当…时; 不少于; 同样;
adj.	公正的; 正义的; 正当的; 合理的; 正直的人; 公正的人; 合适的; 恰当的;
[例句]I've just bought a new house
我刚买了栋新房子
just behind him 
紧跟在他后面
*** quickly
quickly	英[ˈkwɪkli]
美[ˈkwɪkli]
adv.	迅速地; 很快地; 不久; 立即;
[例句]The meeting quickly ended and Steve and I left the room
会议很快结束了，我和史蒂夫离开了房间。
[其他]	比较级：more quickly 最高级：most quickly

* He's awful 
** text

What's Ron Marston like, Pauline?
He's awful.
He telephoned me four times Yesterday.
and three times the day before yesterday.
He telephoned the office yesterday morning and yesterday afternoon.
My boss answered the telephone.
What did your boss say to him?
He said, "Pauline is typing letters. She can't speak to you now!"
Then I arrived home at six o'clock yesterday evening.
He telephoned again.
But I didn't answer the phone!
Did he telephone again last night?
Yes, he did.
He telephoned at nine o'clock.
What did you say to him?
I said, This is Pauline's mother.
Please don't telephone my daughter again!
Did he telephone again?
No, he didn't.

** Test
*** first

 What's Ron Marstan like, Pauline?
 He's awful.
 He telephoned me four times Yesterday,
 and three times the day before yesterday.
 He telephoned the office yesterday morning and yesterday afternoon.
 My boss answered the telephone.
 What did your boss say to him?
 He said, 'Pauline is typing letters. She can't speak to your now!'
 Then I arrived home at six o'clock yesterday evening.
 He telephoned again.
 But I didn't answer the phone!
 Did he telephone again (at \times)last night?
 Yes, he did.
 He telephoned (again \times )at nine o'clock.
 What did you say to him?
 I said. This is Pauline's mother.
 Please don't telephone my daughter again!
 Did he telephone again?
 No, he didn't.

*** Second

 What's Ron Marston like, Pauline?
 He's awful.
 He telephoned me four times yesterday,
 and three times the day before yesterday.
 He telephoned the office yesterday morning and yesterday afternoon.
 My boss answered the telephone.
 What did your boss say to him?
 He said, 'Pauline is typing letters. She can't speak to you now!'
 Then I arrived home at six o'clock yesterday evening.
 He telephoned again.
 But I didn't answer the phone!
 Did he telephone again (at)last night?
 Yes, he did.
 He telephoned again at nine o'clock.
 What did you say to him?
 I said. This is Pauline's mother.
 Please don't telephone my daughter again!
 Did he telephone again?
 No, he didn't.


*** third

 What's Ron Marston like, Pauline?
 He's awful.
 He telephoned me four times yesterday,
 and three times the day before yesterday.
 He telephoned the office yesterday morning and yesterday afternoon. 
 My boss answered the telephone.
 What did your boss say to him?
 He said. 'Pauline is typing letters. She can't speak to your now!'
 Then I arrived home at six o'clock yesterday evening.
 He telephoned again.
 But I didn't answer the phone! 
 Did he telephone again (at)last night?
 Yes, he did.
 He telephoned at nine o'clock.
 What did you say to him?
 I said. This is Pauline's mother.
 Please don't telephone my daughter again!
 Did he telephone again?
 No, he didn't.

*** Forth

 What's Ron Marston like, Pauline?
 He's awful!
 He telephoned me four times yesterday, and three times the day before yesterday.
 He telephoned the office yesterday morning and yesterday afternoon.
 My boss answered the telephone.
 What did your boss say to him?
 He said. 'Pauline is typing letters. She can't speak to you now!'
 Then I arrived home at six o'clock yesterday evening.
 He telephoned again.
 But I didn't answer the phone!
 Did he telephone again (at)last night?
 Yes, he did.
 He telephoned at nine o'clock.
 What did you say to him?
 I said, 'This is Pauline's mother.'
 Please don't telephone my daughter again!
 Did he telephone again? 
 No, he didn't.

*** Fifth 

 What's Ron Marston like, Pauline?
 He's awful.
 He telephoned me four times yesterday,
 and three times the day before yesterday.
 He telephoned the office yesterday morning and yesterday afternoon.
 My boss answered the telephone.
 What did your boss say to him?
 He said, 'Pauline is typing letters. She can't speak to you now!'
 Then I arrived home at six o'clock yesterday evening.
 He telephoned again.
 But I didn't answer the phone!
 Did he telephone again last night?
 Yes, he did.
 He telephoned at nine o'clock.
 What did you say to him?
 I said. This is Pauline's mother.
 Please don't telephone my daughter again!
 Did he telephone again?
 No, he didn't.

*** Sixth
What's Ron Marston like, Pauline?
He's awful!
He telephoned me four times yesterday, and three times the day before yesterday.
He telephoned the office yesterday morning and yesterday afternoon.
My boss answered the telephone.
What did your boss say to him?
He said, 'Puline is typing letters. She can't speak to you now!'
Then I arrived home at six o'clock yesterday evening.
He telephoned again!
But I didn't answer the phone.
Did he telephone again last night?
Yes, he did.
He telephoned again at nine o'clock.
What did you say to him?
I said. 'This is Pauline's mother.
Please don't telephone my daughter again!'
Did he telephone again?
No, he didn't.

** program 
*** 问一个人怎么样
what's somebody like?
What's this man like?
这人怎么样？
*** 一般过去时问句或否定加 did 
**** ?
What did you say to him?
What did your boss say to him?
Did he telephone again?
Did he telephone again last night?

*** 否定 did not didn't +原型
But I didn't answer the phone!
No, he didn't.

*** 一般现在时
Please don't telephone my daughter again!
What's Ron Marston like, Pauline?

*** 一般过去时
He telephoned me four times yesterday, and three times the day before yeaterday.
My boss answered the telephone.
He telephoned again.
He telephoned at nine o'clock.

* The way to King Street

Last week Mrs. Mills went to London.
She does not know London very well, and she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way.' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
The man smiled pleasantly.
He did not understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket,
and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase slowly.
'I am sorry,' he said. 'I do not speak English.'

** First
Last week Mrs. Mills went to London.
She does not know London very well, 
and she lost her way.
Suddenly(,) she saw a man near a bus stop.
'I can ask him the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
(The man smiled pleasantly.)
The man did not understand.(He did not understand English!)
He spoke German.
He was a tourist.
He smiled pleasantly.(\times)
Then he put his hand into his pocket,
and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase (very\times) slowly.
'I am sorry,' he said. 'I do not speak English.'

** second
Last week, Mrs. Mills went to London.
She does not know London very well,
and she lost her way.
Suddenly, she saw a man at a bus stop.
'I can ask his the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to the King Street, please?'
The man smiled pleasantly.
The man did not understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket.
and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase slowly.
'I am sorry,' he said. 'I don't speak English!'

** third

Last week, Mrs. Mills went to London.
She does not know London very well,
and she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to the King Street, please?'
The man smiled pleasantly.
He did not understand.
He spoke German.
He was a tourist.
Then he put his hand into his pocket, 
and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase slowly.
'I am sorry,' he said. 'I don't speak English!'

** Forth

Last week Mrs. Mills went to London.
She does not know London very well, 
and she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
The man smiled pleasantly.
He did not understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket,
and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase slowly.
'I am sorry,' he said. 'I do not speak English!'

** fifth
Last week Mrs. Mills went to London.
She does not know London very well,
so she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King street, please?'
The man smiled pleasantly.
He did not understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket, 
and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase slowly.
'I am sorry,' he said. 'I do not speak English!' 

** Sixth 
Last week Mrs. Mills went to London.
She does not know London very well, 
and she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way.' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
The man smiled pleasantly.
He did not understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket, and took out a phrase-book.
He opened the book and found a phrase.
He read the phrase slowly.
'I am sorry,' he said. 'I do not speak English!'

** Seventh
Last week, Mrs. Mills went to London.
She does know London very well,
and she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
The man smiled pleantly.
He didn't understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket,
and took out a phrasebook.
He opened the book and found a phrase.
He read the phrase very slowly.
'I am sorry,' he said. 'I do not speak English!'

** Eighth
Last week, Mrs. Mills went to London.
She does not know London very well, and she lost her way.
Suddenly, she saw a man near a bus stop.
'I can ask him the way,' she said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
The man smiled pleasantly.
He did not understand English!
He spoke German.
He was a tourist.
Then he put his hand into his pocket,
and took out a phrasebook.
He opened the book and found a phrase.
He read the phrase very slowly.
'I am sorry.' he said. 'I do not speak English!'

* lesson 75 Uncomfortable shoes

Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those a month ago,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last.
But they're not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable.
But women always wear uncomfortable shoes!
像这样的鞋子你们有吗？
什么尺码的？
5 号的。
什么颜色？
黑的。
对不起，我们没有。
但是，我姐姐上个月买到了这样的一双。
好是在这儿买的吗？
不。她是在美国买的。
一个月前我们有这样的鞋。
但是现在没有了。
您能为我找一双吗？
恐怕不行。
这鞋在去年和前年时兴，而今年已不流行了。
现在流行的是这种鞋子。
这种鞋子看上去很不舒适。
的确很不舒适。
可是女人们总是穿不舒适的鞋子！

** write in

Do you have any shoes like these?
What size?
Number five.
What color?
Blank.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those a month ago,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last.
But they are not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable. 
But women always wear uncomfortable shoes!

wrong:
But my sister bought a pair last month.
Did she buy them here?
Do you get a pair for me, please?
I'm afraid I can't.
But they are not in fashion now.
But they look very uncomfortable.
But women always wear uncomfortable shoes.
correct:
But my sister bought this pair last month.
Did she buy them here?
Can you get a pair for me, please?
I'm afraid that I can't.
But they're not in fashion this year.
They look very uncomfortable.
But women always wear uncomfortable shoes!

** second test
Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those a month ago.
But we don't have any now.
Can you get a pair for me, please?
I'm afraired that I can't.
They were in fashion last year and the year before last.
But they're not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable.
But women always wear uncomfortable shoes!

** Third review

Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those a month ago,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last,
but they're not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable.
But women always 

** forth 
Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry. We don't have any.
But my sister bought this pair last month.
Did she buy them here?
No, she bought them in the U.S.
We had some shoes like those last month,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion this year and the year before last.
But they're not in fashion this year.
These shoes are in fashion now.
They look very uncomfortable.
They are very uncomfortable.
But women always wear uncomfortable shoes!

** fifth
全部为对话，不加‘’了\\
Do you have any shoes like these?\\
What size?\\
Number five.\\
What color?\\
Black.\\
I'm sorry. We don't have any.\\
But my sister bought this pair last month.\\
Did she buy them here?\\
No, she bought them in the U.S.\\
We had some shoes like those a month ago,\\
but we don't have any now.\\
Can you get a pair for me, please?\\
I'm afraid that I can't.\\
They were in fashion last year and the year before last.\\
But they're not in fashion this year.\\
These shoes are in fashion now.\\
They look very uncomfortable.\\
They are very uncomfortable.\\
But women always wear uncomfortable shoes.\\

#+BEGIN_SRC LISP
(global-set-key (kbd "<f2>") 'open-init-file)
#+END_SRC 

** Sixth 

Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
We don't have any.
But my sister bought this pair last month.
Did she bought them here?
No, she bought them in the U.S.
We had some shoes like those a month ago, 
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last.
But they're not in fashion this year.
These shoes are in fashion now. 
They look very uncomfortable. 
They are very uncomfortable.
But women always wear uncomfortable shoes!

** Seventh
Do you have any shoes like these?
What size?
Number five.
What color?
Black.
I'm sorry.
 We don't have any.
But my sister bought this pair last month.
Did she bought them here?
No, she bought them in the U.S.
We had some shoes like those a month ago,
but we don't have any now.
Can you get a pair for me, please?
I'm afraid that I can't.
They were in fashion last year and the year before last. 
But they're not in fashion this year.
These shoes are in fashion now. 
They like very uncomfortable.
They are very uncomfortable!
But women always wear uncomfortable shoes!
* lesson 77 tooth-ache

Good morning. Mr. Croft.
Good morning, nurse.
I want to see the dentist, please.
Do you have an appointment?
No, I don't.
Is it urgent?
Yes, it is.
It's very urgent.
I fell awful.
I have a terrible tooth-ache.
Can you come at 10 a.m on Monday, April 24th?
I must see the dentist now, nurse.
The dentist is very busy at the moment.
Can you come at 2 p.m?
That's very late
.
Can the dentist see me now?
I'm afraid that he can't. Mr. Croft.
Can't you wait till this afternoon?
I can wait, but my tooth-ache can't.
** test
*** First
 Good morning, Mr. Croft.
 Good morning, nurse.
 I want to see the dentist, please.
 Do you have an appointment?
 No, I don't.
 Is it urgent?
 Yes, it is.
 It's very urgent.
 I feel awful.
 I have a terrible toothache.
 Can you come at 10 a.m. on Monday, April 24th?
 Can the dentist see me now, nurse?
 I'm afraid that he can't, Mr. Croft.
 Can't you wait till this afternoon?
 I can wait, but my toothache can't!
*** Second
Good morning, Mr. Croft.
Good morning, nurse.
I want to see the dentist, please.
Do you have an appointment?
No, I don't.
Is it urgent?
Yes, it is.
It's very urgent.
I feel awful.
I have a terrible toothache.
Can you come at 10 a.m. on Monday, April, 24th?
I must see the dentist now, nurse.
The dentist is very busy at the moment.
Can you come at 2 p.m.?
That's too late.
Can the dentist see me now?
I'm afraid that he can't, Mr. Croft.
Can't you wait till this afteroon?
I can wait, but my toothache can't!

** words
*** feel
 feel	英[fiːl]
 美[fiːl]
 v.	觉得; 感到; 体会到; (通过触觉) 注意到，意识到，感觉到; 感觉到(抽象事物);
 n.	触觉; 手感; 触摸; 摸; (场所、情况等给人的) 印象，感受; 气氛;
 [例句]I am feeling very depressed
 我觉得非常沮丧。
 [其他]	第三人称单数：feels 现在分词：feeling 过去式：felt 过去分词：felt

*** write in 
 Good morning, Mr. Croft.
 Good morning, nurse.
 I want to see the dentist, please.
 Do you have an appointment?
 No, I don't.
 Is it urgent?
 Yes, it is.
 It is very urgent.
 I fell awful.
 I have a terrible tooth-ache.
 Can you come at 10 a.m. on Monday, April 24th?
 I must see the dentist now, nurse.
 The dentist is very busy at the moment.
 Can you come at 2 p.m.?
 That's very late.
 Can the dentist see me now?
 I'm afraid that he can't. Mr. Croft.
 Can't you wait till this afternoon?
 I can wait, but my tooth-ache can't.

*** Second write in.
 Good morning. Mr. Croft.
 Good morning, nurse.
 I want to see the dentist, please.
 Do you have an appointment?
 No. I don't.
 Is it urgent?
 Yes, it is.
 It's very urgent.
 I feel awful.
 I have a terrible tooth-ache.
 Can you come at 10 a.m. on Monday, April, 24th?
 I must see the dentist now, nurse.
 The dentist is very busy at the moment.
 Can you come at 2 p.m.?
 That's very late.
 Can the dentist see me now?
 I'm afraid that he can't. Mr. Croft.
 Can't you wait till this afternoon?
 I can wait, but my tooth-ache can't.
*** third write in
 Good morning, Mr. Croft.
 Good morning, nurse.
 I want to see the dentist, please.
 Do you have an appointment?
 No, I don't.
 Is it urgent?
 Yes, it is.
 It's very urgent.
 I feel awful.
 I have a terrible tooth-ache.
 Can you come at 10 a.m. on Monday, April, 24th?
 I must see the dentist now, nurse.
 The dentist is very busy now at the moment.
 Can you come at 2 p.m.?
 That's very late.
 Can the dentist see me now?
 I'm afraid that he can't, Mr. Croft.
 Can't you wait till this afternoon?
 I can wait, but my tooth-ache can't!
*** appointment
 英[əˈpɔɪntmənt]
 美[əˈpɔɪntmənt]
 n.	约会; 预约; 约定; 任命; 委任; 职务; 职位;
 [例句]His appointment to the Cabinet would please the right-wing.
 他被任命为内阁成员会让右翼党派很高兴。
 [其他]	复数：appointments
*** urgent	英[ˈɜːdʒənt]
 美[ˈɜːrdʒənt]
 adj.	紧急的; 紧迫的; 迫切的; 催促的; 急切的;
 [例句]There is an urgent need for food and water
 现在亟需食物和水。
*** awful	英[ˈɔːfl]
 美[ˈɔːfl]
 adj.	很坏的; 极讨厌的; 非常的; 很多的; 过多的; 骇人听闻的; 可怕的;
 adv.	非常; 极其;
 [例句]We met and I thought he was awful
 我们见了面，我觉得他很讨人厌。

* lesson 79 Carol's shopping list
What are you doing, Carol?
I'm making a shopping list, Tom.
What do we need?
We need a lot of thing this week.
I must go to the grocer's.
We haven't got much tea or coffee, 
and we haven't got any sugar or jam.
What about vegetables?
I must go to the green-grocer's.
We haven't got many tomatoes, 
but we've got a lot of potatoes.
I must go to the butcher's, too.
We need some meat.
We haven't got any meat at all.
Have you got any beer and wine?
No, we haven't. 
And I'm not going to get any!
I hope that you've got some money.
I haven't got much.
Well, I haven't got much either!

** test

What are you doing, Carol?
I'm making a shopping list, Tom.
What do we need?
We need a lot of thing this week.
I must go to the grocer's.
We haven't got much tea or coffee,
and we haven't got any sugar or jam.
What about vegetables?
I must go to the green-grocer's.
We haven't got many tomatoes,
but we've got a lot of potatoes.
I must go to the butcher's, too.
We need some meat.
We haven't got any meat at all.
Have we got any beer and wine?
No, we haven't.
And I'm not going to get any!
I hope that you've got some money.
I haven't got much.
Well, I haven't got much either!

** many 肯定或可数
We haven't got many tomatoes.
** much 否定或不可数
We haven't got much tea or coffee.
How much does this house cost?
I haven't got much.
Well, I haven't got much either.

** any 否定问句或不可数

and we haven't got any sugar or jam.
We haven't got any meat at all.
Have we got any beer and wine?
No, we haven't. And I'm not going to got any!

** a lot of 不可数的（钱、东西、马铃蓍） 
but we've got a lot of potatoes.
We need a lot of thing this week.
That's a lot of money.

** must 必须
I must go to the grocer's.
I must go to the green-grocer's.
I must go to the butcher's, too.
My wife must see it first.

** need
What do we need?
We need a lot of thing this week.
We need some meat.
You need a new car.
** Be going to 
Well, I'm not going to get any!
Well, you're going to have roast beef and potatoes again tonight.
We're going to leave tomorrow.
We're going to have a holiday.
Tom and I are going to have a holiday.
When are you going to have a holiday?

** get
get	英[ɡet]
美[ɡet]
v.	收到; 接到; 获得; 得到; (卖某物) 挣得;
[例句]The boys were getting bored
男孩子们开始感到厌烦。
[其他]	第三人称单数：gets 现在分词：getting 过去式：got 过去分词：got

have got 现在完成时
** 酒
*** whisky


 whisky	英[ˈwɪski]
 美[ˈwɪski]
 n.	威士忌; 一杯威士忌;
 [例句]He took a mouthful of neat whisky, and coughed.
 他喝了一口纯威士忌，咳嗽了起来。
 [其他]	复数：whiskies
 威士忌（Whisky、Whiskey），是一种由大麦等谷物酿制，在橡木桶中陈酿多年后，调配成 43 度左右的烈性蒸馏酒。英国人称之为“生命之水”。按照产地可以分为：苏格兰威士忌、爱尔兰威士忌、美国威士忌和加拿大威士忌四大类。威士忌的酿制工艺过程分为六个步骤：发芽、糖化、发酵、蒸馏、陈年、混配。
*** wine
 wine	英[waɪn]
 美[waɪn]
 n.	葡萄酒; (用植物或除葡萄以外的水果酿制的) 酒，果酒; 紫红色; 深红色;
 v.	喝酒; 请…喝酒;
 [例句]This is a nice wine.
 这种葡萄酒味道不错。
 [其他]	第三人称单数：wines 现在分词：wining 过去式：wined 过去分词：wined

*** beer 


 beer	英[bɪə(r)]
 美[bɪr]
 n.	啤酒; 一杯(或一瓶、一罐)啤酒;
 [例句]He sat in the kitchen drinking beer
 他坐在厨房里喝啤酒。
 [其他]	复数：beers
** 商店
*** grocer's
 杂货店; 食品杂货店;

*** greengrocer's 

 蔬菜水果店;

*** butcher's
 butcher's	英[ˈbʊtʃəz]
 美[ˈbʊtʃərz]
	 肉店; 屠夫

*** store
 store	英[stɔː(r)]
 美[stɔːr]
 n.	(大型) 百货商店; 商店; 店铺; 贮存物; 备用物;
 v.	贮存; 贮藏; 保存; (在计算机里) 存储; 记忆;
 [例句]Bombs were planted in stores in Manchester and Blackpool.
 炸弹被安放在曼彻斯特和布莱克浦的几家商店里。
 [其他]	第三人称单数：stores 复数：stores 现在分词：storing 过去式：stored 过去
 分词：stored

*** stove 火炉

*** market
 market	英[ˈmɑːkɪt]
 美[ˈmɑːrkɪt]
 n.	集市; 市场; 商场; 交易; 买卖; 交易量; 商品的销售地; 行销地区; 消费群体;
 v.	推销; 促销;
 [例句]He sold boots on a market stall.
 他在集市上摆摊卖靴子。
 [其他]	第三人称单数：markets 复数：markets 现在分词：marketing 过去式：marketed 过去分词：marketed

*** supermarket
 英[ˈsuːpəmɑːkɪt]
 美[ˈsuːpərmɑːrkɪt]
 n.	超级市场; 超市;
 [例句]Most of us do our food shopping in the supermarket
 我们大多数人去超市购买食品。
 [其他]	复数：supermarkets


* Lesson 81 Roast beef and potatoes
Hi, Carol! Where's Tom?
He's upstairs.
He's having a bath.
Tom! Yes?
Sam's here.
I'm nearly ready.
Hello, Sam.
Have a cigarette.
No, thanks, Tom.
Have a glass of whisky then.
OK. Thanks.
Is dinner ready, Carol?
It's nearly ready.
We can have dinner at seven o'clock.
Sam and I had lunch together today.
We went to a restaurant.
What did you have?
We had roast beef and potatoes.
Oh!
What's the matter, Carol?
Well, you're going to have roast beef and potatoes again tonight.
** test
*** first 
 err:
 Hi, Carol.
 No,thanks. Tom.
 OK, thanks.
 Correct:
 Hi, Carol!
 No, thanks, Tom.
 OK. Thanks.
*** Second
Hi, Carol! Where's Tom?
He's upstairs.
He's having a bath.
Tom! Yes?
Sam's here.
I'm nearly ready.
Hello, Sam.
Have a cigarette.
No, thanks, Tom.
Have a glass of whisky then.
Ok. Thanks.
Is dinner ready, Carol?
It's nearly ready.
We can have dinner at seven o'clock.
Sam and I had lunch together today.
We went to a restaurant.
What did you have?
We had roast beef and potatoes.
Oh!
What's the matter, Carol?
Well, you're going to have roast beef and potatoes again tonight!

** words
*** ask where
 Where's Tom?
*** ask what
 What did you have?
*** have eat meal ett.
 Have a cigarette.
 Have a glass whisky then.
 We can have dinner at seven o'clock.
 Sam and I had lunch together today.
 We had roast beef and potatoes.
 Well, you're going to have roast beef and potatoes again tonight.
*** ready
 I'm nearly ready.
 It's nearly ready.
*** 标点
 No,thanks, Tom.
 OK. Thanks.
 Oh!
* Lesson 83 Holiday
Hello, Sam. Come in.
Hi, Sam.
We're having lunch.
Do you want to have lunch with us?
No, thank you. Tom.
I've already had lunch.
I had a lunch at half past twelve.
Have a cup of coffee then.
I've just had a cup, thank you.
I had one after my lunch.
Let's go into the living room, Carol.
We can have our coffee there.
Excuse the mess, Sam.
This room's very untidy.
We're packing our suitcases.
We're going to leave tomorrow.
Tom and I are going to have a holiday.
Aren't you lucky!
When are you going to have a holiday, Sam?
I don't know.
I've already had my holiday this year.
Where did you go?
I stayed at home!
** 现在进行时
We're having lunch.
We're packing our suitcases.
** 打算（将来时）
We're going to leave tomorrow.
Tom and I are going to have a holiday.
When are you going to have a holiday, Sam?
** 正在完成时 have +过去分词
I've already had lunch.
I've just had a cup, thank you.
I've already had my holiday this year.
** 一般过去时
I had a lunch at half past twelve.
I had one after my lunch.
Where did you go?
I stayed at home.
** 一般现在时
Do you want to have lunch with us?
Have a cup of coffee then.
Let's go into the living room, Carol.
We can have our coffee there.
This broom's very untidy.
I don't know.

** test

Hello, Sam. Come in.
Hi, Sam. 
We're having lunch.
Do you want to have lunch with us?
No, thank you. Tom.
I've already had lunch.
I had a lunch at half past twelve.
Have a cup of coffee then.
I've just had a cup, thank you.
I had one after my lunch.
Let's go into the living room, Carol.
We can have our coffee there.
Excuse the mess, Sam.
This room's very untidy.
We're packing our suitcases.
We're going to leave tomorrow.
Tom and I are going to have a holiday.
Aren't you lucky!
When are you going to have a holiday, Sam?
I don't know.
I've already had my holiday this year.
Where did you go?
I stayed at home!

* Lesson 85 Pairs in the spring 

Hello, Ken.

Hi, George.

Have you just been to the cinema?

Yes, I have.

What's on?

'Pairs in the spring.'

Oh, I've already seen it.

I saw it on television last year.

It's an old film, but it's very good.

Pairs is a beautiful city.

I've never been there.

Have you ever been there, Ken? 

Yes, I have. I was there in spring. 

Pairs in the spring, eh?

It was spring,

but the weather was awful.

It rained all the time.

Just like London! 

** 现在完成时
Have you just been to the cinema?
Oh, I've already seen it.
I've never been there.
Have you ever been there, Ken?

** 一般过去时
I saw it on television last year.
I was there in April.
It was spring, but the weather was awful.
It rained all the time.

** 一般现在时
What's on?
It's an old film, but it's very good.
Pairs is a beautiful city.
Just like London.

** Test
Hello, Ken.
Hi, George.
Have you just been to the cinema?
Yes, I have.
What's on?
"Pairs in the spring."
Oh, I've already seen it.
I saw it on television last year.
It's an old film, but it's very good.
Pairs is a beautiful city.
I've never been there.
Have you ever been there, Ken?
Yes, I have. 
I was there in April.
Pairs in the spring, eh?
It was sprint, 
but the weather was awful.
It rained all the time.
Just like London!

err: George George

* lesson 87 crash
/Is/ my car ready yet?

I don't know, sir.

What's the number of your car?

It is LIZ 312G.
When did you bring it to us?
I brought here three days ago.
Oh,yes. I remember now.
Have your mechanics finished yet?
No, they're still working on it.
Let's go into the garage and have a look at it.
Isn't that your car?
Well, it was my car.
Didn't you have a crash? 
That's right.
I drove it into a lamp-post.
Can your mechanics repair it?
Well, they're trying to repair it, sir.
But to tell you the truth, 
you need a new car.

** 现在完成时（特殊）
Is my car ready yet?
Have your mechanics finished yet?
Didn't you have a crash?

** 一般过去时
I brought here three days ago.
It was my car.
I drove it into a lamp-post.
** 现在进行时
No, they're still working on it.
Well, they're trying to repair it, sir.
** Can
Can your mechanics repair it?
** test
Is my car ready yet?
I don't know, sir.
What's the number of your car?
It is LFZ 312G.
When did you bring it to us?
I bought here three days ago.
Oh, yes. I remember now.
Have your mechanics finished yet?
No, They're still working on it.
Let's go into the garage and have a look at it.
Isn't that your car?
Well, it was my car.
Didn't you have a crash?
That's right.
I drove it into a lamp-post.
Can your mechanics repair it?
Well, they're trying to repair it, sir.
But tell you the truth,
you need a new car.

err:
Is my car ready yet?
wrong:Is my car already yet.

I don't know, sir.
wrong: I don't know.

Well, they're trying to repair it, sir.
wrong: Well, they're trying to repair it, sir.
服务人员说话客气。加 sir.

Didn't you have a crash.
wrong:
Have you have a crash.

* Lesson 89 For Sale
Good afternoon.
I believe that this house is for sale.
That's right.
May I have a look at it, please?
Yes, of course.
Come in.
How long have you lived here?
I've live here for twenty years.
Twenty years!
That's a long time.
Yes, I've been here since 1976.
Then why do you want to sell it?
Because I've just retired.
I want to buy a small house in the country.
How much does this house cost?
\pounds68500.
That's a lot of money.
It's worth every penny of it.
Well, I like the house,
but I can't decide yet.
My wife must see it first.
Women always have the last word.
** Test
Good afternoon.
I believe that this house is for sale.
That's right.
May I have a look at it, please?
Yes, of course.
Come in.
How long have you lived here?
I've live here for twenty years.
That's a long time.
Yes, I've been here since 1976.
Then why do you want to sell it?
Because I've just retired.
I want to buy a small house in the country.
How much does this house cost?
\pounds68500.
That's a lot of money.
It's worth every penny of it.
Well, I like the house, 
but I can't decide yet.
My wife must see it first.
Women always have the last word.

err:
I think /that/ this house is for sale.
/Yes/, of course.
/but/ it's worth every penny of it.

** Test
Good afternoon.
I believe that this house is for sale.
That's right.
May I have a look at it, please?
Yes, of course.
Come in.
How long have you lived here?
I've lived here for twenty years.
Twenty years!
That's a long time.
Yes, I've been here since 1976.
Then why do you want to sell it?
Because I've just retired.
I want to buy a small house in the country.
How much does this house cost?
\pounds68500.
That's a lot of money.
It's worth every penny of it.
Well, I like the house, 
but I can't decide yet.
My wife must see it first.
Women always have the last word.

* Lesson 91 Poor Ian
Has Ian sold his house yet?
Yes, he has.
Has he moved to his new house yet? 
No,not yet.
He's still here.
He's going to move tomorrow.
When? Tomorrow morning.
No. Tomorrow afternoon.
I'll miss him.
He has always been a good neighbour.
He's a very nice person.
We'll all miss him.
When will the new people move into this house?
I think that they'll move in the day after tomorrow.
Will you see Ian today, Jenny?
Yes, I will.
Please give him my regards.
Poor Ian!
He didn't want to leave this house.
No, he didn't want to leave,
but his wife did.
** test

*** First
 Has Ian sold his house yet?
 Yes, he has.
 He sold it last week.
 Has he moved to his new house yet?
 No, not yet.
 He's still here.
 He's going to move tomorrow.
 When? Tomorrow morning.
 No. Tomorrow afternoon.
 I'll miss him. 
 He has always been a good neighbour.
 He's a very nice person.
 We'll miss him.
 When will the new people move into this house?
 I think that they'll move in the day after tomorrow.
 Will you see Ian, today?
 Yes, I will.
 Please give him my regards.
 Poor Ian!
 He didn't want to leave this house.
 No,he didn't want to leave, 
 but his wife did.

 err:
 Will you see Ian today, Jenny?
 wrong
 Will you see Ian, today?

 No, he didn't want to leave,
 wrong

 no, he didn't want to

*** Second 
Has Ian sold his house yet?
Yes, he has.
Has he moved to his new house yet?
No, not yet.
He's still here.
He's going to move tomorrow.
When? Tomorrow morning.
No. Tomorrow afternoon.
I'll miss him.
He has always been a good neighboour.
He's very nice person.
We'll miss him.
When will the people move into this house?
I think that they'll move in the day after tomorrow.
Will you see Ian today,Jenny?
Yes, I will.
Please give him my regards.
Poor Ian!
He didn't want to leave this house.
No, he didn't want to leave,
but his wife did!


* Lesson 93
Nigel is our new next-door neighbour.
He's a pilot.
He was in the R.A.F.
He will fly to New York next month.
The month after next he'll fly to Tokyo.
At the moment, he's in Madrid.
He flew to Spain a week ago.
He'll return to London the week after next.
He's only forty-one years old,
and he has already been to nearly every country in the world.
Nigel is a very lucky man.
But his wife isn't very lucky.
She usually stays at home!
** words
*** pilot
pilot	英[ˈpaɪlət]
美[ˈpaɪlət]
n.	飞行员; (飞行器) 驾驶员; 领航员; 引水员; 领港员; (电视的) 试播节目;
v.	驾驶(飞行器); 领航(船只); 引导; 使通过(尤指复杂的地方或系统); 试点; 试行;
adj.	试验性的; 试点的;
[例句]He spent seventeen years as an airline pilot.
他当了 17 年的航空公司飞行员。
[其他]	第三人称单数：pilots 复数：pilots 现在分词：piloting 过去式：piloted 过
去分词：piloted
*** Tokyo
Tokyo	英[ˈtəʊkiəʊ]
美['tokjo]
n.	东京;
[例句]On my way to New York, I stopped over in Tokyo for two days.
我在去纽约的途中在东京停了两天。
*** Madrid
Madrid	英[məˈdrɪd]
美[məˈdrɪd]
n.	马德里（西班牙首都）;
[例句]Tonight's clash between Real Madrid and Arsenal is being heralded as the match of the season.
今晚皇家马德里队和阿森纳队之间的对决被称为本赛季最重要的比赛。
*** Spain
Spain	英[speɪn]
美[speɪn]
n.	西班牙;
[例句]The game was transmitted live in Spain and Italy
这场比赛在西班牙和意大利进行了现场直播。
*** lucky
ucky	英[ˈlʌki]
美[ˈlʌki]
adj.	有好运的; 运气好的; 幸运的; 好运带来的; 带来好运的;
[例句]I am luckier than most. I have a job
我比大部分人幸运。我有份工作。
[其他]	比较级：luckier 最高级：luckiest
** Test
*** First
Nigel is our new next-door neighbour.
He's a pilot. 
He was in the R.A.F.
He will fly to New York next month.
The month after next he'll fly to Tokyo.
At the moment, he's in Madrid.
He flew to Spain a week ago.
He's return to London the week after the next.
He's only forty-one years old, 
and he has already been to nearly every country in the world.
Nigel is a very lucky man.
But his wife isn't very lucky.
She usually stays at home!

* Footnotes

[fn:10]conversation
英[ˌkɒnvəˈseɪʃn]
美[ˌkɑːnvərˈseɪʃn]
n.	(非正式) 交谈，谈话;
[例句]He's a talkative guy, and I struck up a conversation with him
他是一个健谈的人，于是我开始和他攀谈起来。
[其他]	复数：conversations 

[fn:9]subject
英[ˈsʌbdʒɪkt , səbˈdʒekt]
美[ˈsʌbdʒɪkt , səbˈdʒekt]
n.	主题; 题目; 话题; 题材; 问题; 学科; 科目; 课程; 表现对象; 绘画(或拍摄)题材;
adj.	可能受…影响的; 易遭受…的; 取决于; 视…而定; 受…支配; 服从于;
v.	使臣服; 使顺从; (尤指) 压服;
[例句]It was I who first raised the subject of plastic surgery.
是我第一个提到整形手术这个话题的。
[其他]	第三人称单数：subjects 复数：subjects 现在分词：subjecting 过去式：subjected 过去分词：subjected 

[fn:8]favorite	英[ˈfeɪvərɪt]
美[ˈfeɪvərɪt]
adj.	特别受喜爱的;
n.	特别喜爱的人（或物）；受宠的人；得到偏爱的人; (国王的) 宠臣；亲信，心腹; (尤指马) 最有希望获胜者;
[例句]I took the title of this chapter from one of my favorite books.
我这章的标题来自我最喜欢的一本书。
[其他]	比较级：more favorite 最高级：most favorite 复数：favorites
 

[fn:7][V] 落（下） 
to go down below the horizon
We sat and watched the sun setting.
我们坐着看太阳渐渐落下去。
see also sunset n. (1)
反义词： rise 

[fn:6]seasons	英[ˈsiːznz]
美[ˈsiːznz]
n.	季; 季节; (热带地区的) 旱 / 雨季; (一年中开展某项活动的) 季节，旺季;
v.	加调料调味; 加作料;
[词典]	season 的第三人称单数和复数;
[例句]The prospect of relegation is a comedown for a club that finished second two seasons ago.
对于两个赛季前排名第二的俱乐部来说，竟然有降级之虞真是太落魄了。
[其他]	原型： season
 

[fn:5]wet	英[wet]
美[wet]
adj.	潮的; 湿的; 潮湿的; 有雨的; 下雨的; 尚未干的;
v.	使潮湿; 把…弄湿;
n.	雨天; 雨; 液体; (尤指) 水; 保守党温和派成员;
[例句]He towelled his wet hair
他用毛巾擦干湿发。
[其他]	比较级：wetter 最高级：wettest 第三人称单数：wets 复数：wetter 现在分词：
wetting 过去式：wetted 过去分词：wetted
 

[fn:4]windy	英[ˈwɪndi]
美[ˈwɪndi]
adj.	多风的; 风大的; 当风的; 受大风吹的; 夸夸其谈的; 空话连篇的; 空洞无物的;
[例句]It was windy and Jake felt cold.
风很大，杰克觉得很冷。
[其他]	比较级：windier 最高级：windiest
 

[fn:3]mild	英[maɪld]
美[maɪld]
adj.	温和的; 和善的; 不严厉的; 和煦的; 不强烈的; 轻微的;
n.	淡味啤酒;
[例句]Teddy turned to Mona with a look of mild confusion
泰迪表情略带困惑地向莫娜求助。
[其他]	比较级：milder 最高级：mildest
 

[fn:2]climate	英[ˈklaɪmət]
美[ˈklaɪmət]
n.	气候; 气候区; 倾向; 思潮; 风气; 环境气氛;
[例句]The economic climate remains uncertain.
经济形势依然不确定。
[其他]	复数：climates
 

[fn:1]pleasant	英[ˈpleznt]
美[ˈpleznt]
adj.	令人愉快的; 可喜的; 宜人的; 吸引人的; 友好的; 和善的; 文雅的;
[例句]I've got a pleasant little apartment
我有一套舒适的小公寓。
[其他]	比较级：pleasanter 最高级：pleasantest
 
