* english learn
** 语法
How many dogs do you have?
wrong:
How many dogs are you have?
I was there in April.
Error: I was there in the spring.
It was spring.(It was in spring.)
[2020-04-14 Tue]
I've just had a cup. Think you.
err:
I've already had a cup, think you.

I had a lunch at half past twelve.
err:
I had lunch at half past twelve.

Have a cup of coffee then.

err: Have you a cup of coffee then.

* emacs 
** clls wrong
install llvm 解决部分
** ycmd
apt-get 如何安装
** 因 emacs background 困绕
set-background-color black
set-foreground-color grey80
** dictionary
不能使用
** 解决了文件不 tracked 的问题
文件状态：Untraceked
变为 tracked 
用 github desktop
command ?
** <2020-04-16 Thu> 今天安装了 mac emacs-plus
但 tern company-tern 问题未解决，子龙山人排除了
用 brew install npm
但用 npm install -g tern 报错

* handwriting
** 
* C programming
** 今天安装了 gdp
brew install gdp
是什么东西，待探索。
** 学会的命令
*** gcc 编译
Gcc -o 输出的文件名 被编译的文件
simple: gcc -o hello.exe hello.c
- 因不同文件，修改其一，而编译另一；结果同，浪费时间。
** 易犯的错
*** 名尾漏";"
printf("hello, world!\n");
return 0;
*** 取变量格式 &dogs
两次错误
少了“&”
*** include 
*** 变量名错
declared
** 每次修改皆提交
保存，提交，知道哪里改了，错在哪里。<2020-04-15 Wed> 
** main 格式错误
漏了 int
err int main(argc,const char*argv[])
correct:
int main(int argc,const char*argv[])
** 几个新 word
*** butler 男俑 仆人
*** summon 呼叫，调用
*** rang 如唤
*** writeable 可写的
*** function 函数
