* country
** London 伦敦 英国首都
He'll return to London the week after next.
It rained all the time. Just like London.
** Madrid 马德里 西班牙
At the moment, he's in Madrid. 
** Tokyo 东京 日本
The month after the next he's fly to Tokyo.
** New York 纽约 美国
He will fly to New York next month.
** Spain 西班牙
He flow to Spain a week ago.
* move into
** When will the new people move into this house?
* move in 
** I think that they'll move in the day after tomorrow.
* teacher
** Who dictates, and who writes? A teacher dictates, and pupils write.
** The teacher is explaining a complex assignment on the board.
** The teacher is counting how many pupils are sitting in the classroom.
** The teacher is dictating, and the students are writing on the board with chalk.
** The teacher asks, and the pupil answers the question from his seat.
** The teacher checks the assignment and gives a grade.
* professor
** The professor is giving the students an interesting lecture.
* classroom
** The teacher is counting how many pupils are sitting in the classroom. 
* learn
** The pupil learns at school.
** The student learns at a university.
** The pupils go to school in order to learn.
** The students go to the university in order to learn.
** The pupils learn in a class.
** The students learn in an auditorium.
** To learn at school is simple.
** To learn at a university is complex.

* study
** Who studies in school, and who studies at a university? Pupils study in school, and students study at a university.
** 
* class
** The pupils learn in a class.
** After every class there's a recess.
* lecture
** After every lecture there's a break.
** The professor is giving the students an interesting lecture.
** In lecture students listen and write in notebooks with pens.
* recess
** After every class there's a recess.
** During recess pupils relax, play and eat.
* break
** After every lecture there's a break.
* simple
** To read a book is simple.
** To learn at school is simple.
** To play with toys is simple.
** The pupils are drawing a house. This is a simple assignment.
* complex
** To play on stage is complex.
** To learn at a university is complex.
** To drive a car is complex.
** The teacher is explaining a complex assignment in class.
** The pupils can't draw a horse. This is a complex assignment.
* time
** week
*** a week ago 一周前
He flew to Spain a week ago.
*** The week after next 再下周
He'll return to London the week after next
** Month
*** next month 下个月
He will fly to New York next month.
*** the month after next 再一个月
The month after next he'll fly to Tokyo.
** 当下 At the moment
At the moment, he's in Madrid.
** day
*** today
**** Will you see Ian today, Jenny?
**** 

*** yesterday
**** 
*** tomorrow 
**** When? Tomorrow morning.
**** No. Tomorrow afternoon.
**** He's going to move tomorrow.

*** the day after tomorrow
**** I think that they'll move in the day after tomorrow.
 
*** the day before yesterday
* see
** Will you see Ian today, Jenny?
** My wife must see it first.
* Can
** Can I help you?
** The pupils can't draw a horse. This is a complex assignment.
** Can your mechanics repair it?
Well, they're trying repair it, sir.
* may
** You may cross the street when the light is green.
** You may not speak on the phone in the theater.
** You may not cross the street when the light is red.
** During working hours you may not talk on the phone.
** During work time you may not drink coffee and lie on the couch, but in your free time you may.
** May I have a look at it, please?

* must
** My wife must see it first.
** You must give up fishing. My friends say.
** 
* search words
** primer	英[ˈpraɪmə(r)]
美[ˈpraɪmər]
n.	底漆; 底层涂料; 初级读本; 入门书; 识字课本; 启蒙读本;
[例句]The bare metal was sprayed with several coats of primer.
裸露的金属上被喷上了几层底漆。
[其他]	复数：primers
** premier	英[ˈpremiə(r)]
美[prɪˈmɪr]
adj.	首要的; 最著名的; 最成功的; 第一的;
n.	(尤用于报章等) 首相，总理; (加拿大的) 省总理，地区总理;
[例句]He has acquired a reputation as this country's premier solo violinist.
他已经赢得了该国首席小提琴独奏家的名誉。
[其他]	复数：premiers
** vector 矢量向量
** argument
argc argv 
** const

* animal
** carnivorous
*** wolf wolves
The wolf is hunting a deer.
A wolf is a carnivorous animal. It eats meat.
The hungry wolf is looking around. He's looking for a rabbit.

In the country graze cows and cheep, but there are no leopards or wolves.
What hunts rabbits? Hungry wolves hunt rabbits.
*** tiger
a striped tiger.
The hungry tiger is hunting a deer.
What is striped and carnivorous? A tiger is striped and carnivorous.
*** lion lions
The lion is lying under a tree and eating meat.
The small, full lion is jumping on the tree. He's playing.
The full lion is sleeping under a tree.
If lions sleep, they're not hungry.
*** leopard leopards 
The spotted leopard chases a yellow deer. It's hunting.
A leopard also is a carnivorous animal.
a spotted leopard
A leopard is spotted. It's invisible among the trees.
If a leopard is hungry, it hunts.
In the country graze cows and sheep, but there are no leopards or wolves.
** herbivorous
*** cow cows bull
Cows give milk.
The cows and bull are crossing the street. They're looking for grass.
In the country graze cows and sheep, but there are no leopards or wolves.
a spotted cow
*** deer
a spotted deer
The deer is grazing in the forest.
If a deer is thirsty, it goes to the river.
What is spotted and herbivorous? A deer is spotted and herbivorous.
*** rabbit
a grey rabbit on yellow sand
The rabbit is hiding behind a tree.
In the winter a rabbit is white. It's invisible in the snow. It doesn't hide.
What hunts rabbits? Hungry wolves hunt rabbits.
*** sheep ram(公羊)
The sheep is standing by the house and eating grass.
Sheep and rams give fur.
What gives fur? A sheep and a ram give fur.
*** chicken rooster
Chickens lay eggs.
The chicken is walking by the house. It's looking for food.
What lays eggs? Chickens lay eggs.
What sings at dawn? A rooster sings at dawn.

