《高效能人士的七个习惯》查看《高效能人士的七个习惯》书评和最新更新以及相关书籍推荐请到《高效能人士的七个习惯》专题网址http://www.xiaoshuotxt.com/lizhi/2609/



* 第一部分 重新探索自我第一章 由内而外全面造就自己（一）

　

** 品德成功论强调，圆满的生活与基本品德是不可分的。惟有修养自己具备品德，才能享受真正的成功与恒久的快乐。
 没有正常的生活，就没有真正卓越的人生。
 ——乔登(david starr jordan)，美国生物学家及教育家

 25余年来，我在商界、大学与担任家庭婚姻顾问的工作经验中，接触过形形色色表面上事
 业有成、内心却感到匮乏的人，他们极渴望过和谐、圆满的生活，并享有不断开展的良好
 人际关系。我相信他们所面临的问题，也是你所关注的：

 ● 我曾为自己定下许多目标，也都一一达成。我的事业十分成功，但却牺牲了个人与家庭。
 不但与妻儿形同陌路，甚至不知道还认不认识自己，不了解什么对自己是真正重要的。我
 不得不扪心自问——这样做值得吗?

 ● 我今年已开始第5次控制饮食。我知道自己身体过重，也的确想改变。我阅读了所有的
 新资料，确定目标，用积极的态度激励自己，说我是可以做到的。但我并没有做到。几周
 后，我失败了。我似乎根本不能实现自己的诺言。

 ● 我上过无数教导主管如何有效管理的课程，我对员工的期望很高，也想尽办法善待他们，
 希望维持彼此良好的关系。可是总觉得员工不忠心，我若是有一天生病在家，他们一定会
 终日无所事事闲扯。为什么不能把他们训练成独立又有责任心的员工呢?为什么我始终找不
 到这种员工?

 ● 我那十几岁的儿子不听话，还吸毒。不管我怎么说，他就是不听我的话。我该怎么办呢?

 ● 我要做的事太多了，可是总感到时间不够用。每天都觉得神经紧张、匆匆忙忙。一周7
 天，天天如此。我参加时间管理研讨会，也尝试过不下6种规划时间的办法，虽然不能说没
 有帮助，但是仍觉得无法过上理想中的既充实又自在的生活。

 ● 我想教我的孩子懂得工作的价值，但是每次要他们做点事，都得时时刻刻在旁边监督，
 还得忍受他们不时发出的怨言，结果还不如自己动手来得简单。为什么孩子们就不能快快
 乐乐地料理自己的事而用不着别人来提醒呢?

 ● 我很忙，的确很忙。但有时候我并不清楚，从长远看，我做的工作是否有意义。我的确
 希望在我的生活中，那是有意义的，希望由于我的存在，事情会出现某种不同。
 ● 看到别人有所成功，或获得某种肯定，表面上我会堆出一张笑脸，热忱忱地恭贺他们。
 可是，心底却难过得不得了。为什么会有这种感觉?

 ● 我的个性很强。我知道，几乎在任何交往中，我都能控制结果。多数情况下，我甚至可
 以影响其他人通过我想要的决议。我仔细考虑每种情况，并且觉得我提出的建议通常对大
 家都是最好的。但是我感到不安。我往往不知道他人对我的建议到底取何态度。
 ● 我的婚姻已变得平淡无趣。我们并没有恶言相向，甚至大打出手，只是不再有爱的感觉。
 我们请教过婚姻顾问，也试过许多办法，可是仿佛就是无法重新燃起往日的爱情火花。
 这些都是深层、痛苦的问题，不是一天两天就能解决得了的。

 几年前我和妻子桑德拉就为类似的问题大伤脑筋。我们的一个儿子当时在学校陷入困境，
 他的成绩惨不忍睹，连考卷上的答题说明都看不懂，更甭想拿高分了。在交往上，他是不
 成熟的，往往使那些十分亲近他的人都感到很窘迫。在运动场上，他身材瘦小，又不灵活。
 打棒球时，往往球还没投出就已挥棒，每每招来同学的嘲笑。

 桑德拉和我想尽办法帮助他。我们总以为，若要做个“十全十美”的人，当然也得做个完
 美的父母。于是我们改变自己的态度与行为，也试着想改变儿子的，我们企图用积极的态
 度来激发他的自信心。例如鼓励他：“加油，孩子，你可以办得到!我们知道你可以。把棒
 子握高一点，眼睛看着球，等球快到面前再挥棒。”只要稍有进步，我们一定忙不停地称
 赞，来增强他的信心。

 如果有人嘲笑他，我们一定斥责对方：“不要笑，让他自己来，他还在学习。”而这时我
 们的儿子会哭起来，坚持说自己永远也学不好，还有他根本就不喜欢棒球。

 所有的努力似乎都徒劳无功，那时我们真是心急如焚，看得出来这一切努力反而对他的自
 尊心是个打击。一开始我们尽量鼓励、帮助、肯定他，可是一再失败之后，终于放弃了。
 只有试着从另一个角度来看待这件事。

 当时我的主要工作是，为全美各地的客户设计领导力训练课程。由于这个机缘，我每两个
 月要为国际商用机器公司(ibm)的主管，讲授有关沟通与认知的课程。

 在准备教材的过程中，有关思维的形成、思维如何影响观点、观点又如何左右行为，这些
 都令我深感兴趣，因而进一步研究相关的理论。从中我意识到，每个人的思维是多么根深
 蒂固。并且了解到，认知不仅是认识外在世界，更与我们向外看时所透过的“镜片”有关，
 因为这镜片(即思维)往往左右着我们对外界的诠释。

 我跟桑德拉谈到这些观念，并借此检讨自身所遭遇的困境。终于体认到，我们对儿子往往
 言不由衷。反躬自省后，我们承认在内心深处，的确觉得儿子“不如人”。所以不论态度
 与行为表现得多么愿意帮助他，效果都有限。因为表面的言行终究掩饰不住真正传达的信
 息，那就是：“你不行，你需要父母的保护。”

 此时我们才觉悟，要改变现状，就得改变自己；要改变自己，先得改变我们看待外界的观
 点。


* 第一部分 重新探索自我第一章 由内而外全面造就自己（二）

　品德与个人魅力孰重?

正巧在当时，我潜心研究自1776年以来，美国所有讨论成功因素的文献。我阅读或浏览过的
论著不下数百，主题遍及自我完善、大众心理学以及自我帮助等等。对于爱好自由民主的美
国人民所公认的种种成功之论，已算得上了如指掌。

从这200年来的作品中，我注意到一个令人诧异的趋势。那就是过去50年来讨论成功的著作
都很肤浅，谈的都是如何运用社会形象的技巧与如何成功的捷径。但往往是头痛医头、脚痛
医脚的特效药，治标而不治本。

比较而言，前150年的作品则有很大不同。这些早期论著强调“品德”(character ethic)为
成功之本，诸如像正直、谦虚、诚信、勤勉、朴实、耐心、勇气、公正和一些称得上是金科
玉律的品德。富兰克林(benjamin franklin)的自传就是这个时期的代表作，内容主要描述
一个人如何努力进行品德修养。

品德成功论强调，圆满的生活与基本品德是不可分的。惟有修养自己具备品德，才能享受真
正的成功与恒久的快乐。

然而第一次世界大战后不久，人们对成功的基本观念改变了。由重视“品德”转而强调“个
人魅力”(personality ethic)，即成功与否取决于个性、社会形象，以及维持良好人际关
系的圆熟技巧。这种思潮朝两大方向发展：一是着重人际关系与公关技巧；一是鼓吹积极进
取心态。由此衍生出的行为习惯，有些的确是金科玉律，例如：“态度决定成败”、“微笑
比皱眉更能赢得朋友”及“有志者事竟成”等等，但却也毫不避讳地鼓励玩弄手段、欺骗他
人。例如运用技巧以赢得好感，伪装自己以套取情报，或虚张声势，甚至以威胁手段达到目
标。

这类论著中，有些固然承认品德是成功的要素之一，但多半不十分重视，只是草草带过。对
作者而言，品德只不过是用来妆点门面，要紧的还是速成的技巧与捷径。

两相比较下，我终于了解，过去我与桑德拉潜意识里都受到这种速成观念的影响，才会对儿
子采取上述作法。其实，我们那么做是为了自己的社会形象。在我们心目中，这个孩子有失
颜面，我们重视如何扮演模范父母及维持形象，更甚于对孩子的关切。这种心态或许也影响
到孩子对自己的看法。的确，在面对与处理这个问题时，我们被许多因素所蒙蔽，反而忽略
了儿子自身的幸福。

桑德拉和我愈深入地探讨，愈惭愧地发现，我们自身的动机与观点是如何强烈影响着孩子。
因为好面子，使我们对孩子的爱有了条件，造成他的自我评价低落。所以我们决定从自身下
功夫，不讲究技巧，而着重调整内心真正的动机与对孩子的看法。我们不设法改变他，转从
客观的角度去了解，找出他独特的个性与特质。

经过一番努力，我们终于> 发现这孩子也有不同凡响之处与无尽的潜能，只要顺其自然，必可
发挥无疑。于是我们决定不再插手，让他自由发展，只是从旁肯定、重视，并且分享他的一
切经验。另一方面，我们也做了一番心理建设——不凭借孩子良好的表现来肯定自我。

一旦摆脱了过去的心态，顿时感受到一股新气象。不必再拿儿子与旁人比较，把固定的社会
模式强加在他身上，反而能够平心静气地与孩子相处。我们相信他有能力应付人生的种种挑
战，也就不急于保护，以使他不受嘲笑。

可是孩子已习惯于接受保护，因此一开始表现得相当退缩。他向我们求援，我们虽然倾听，
但不一定如他预期的反应。这无形中传达了一个信息：“父母不必保护你，你不会有问题
的。”

几个月过去，他渐渐有了信心，也肯定自己的价值，终于以自己的速度与步调发挥潜能。不
论在学业、运动场与社交场合上，他的表现以一般社会标准来衡量，都是相当杰出的。这一
切都在一念之间，一旦思维改变，便豁然开朗。后来他还当选学生社团代表、州代表队选手，
拿回家的成绩单则科科甲等。另外，还培养出诚恳热心的个性，走到哪儿都能与人相处融洽。

桑德拉与我相信，这个孩子“足以傲人”的成就，出于自动自发的因素要多于外在的影响。
这是前所未有的经验，对我们教养子女以及扮演其他角色很有启发作用。也使我们体验到，
凭借品德和依靠个人魅力而成功，两者之间的差距有多么大。

光有技巧还不够
教养儿子的经验，以及研究人们的认知能力、阅读讨论成功因素的著作，三者心得相互激励
之下，我突然间认清了个人魅力论无与伦比的影响力。也体会到从小所学并且深植于心灵深
处的价值观，其实与现在四处弥漫的速成哲学相去不远，而这种细微的差异经常被人忽略。
多年来我传授他人的若干习惯，自信十分有效，却与流行的思潮不尽相同，现在我终于对个
中原因有了深一层的领会。

我并非暗示，个人魅力论所强调的重点，如追求个人成长、训练沟通技巧、培养积极思考及
发挥影响力，不具效用。它们有时确实是成功的要素，但是这些只是次要却非最根本的优点。
或许我们沿着前人的轨迹开创前程时，太过重视造就自己，忽略了前人所打下的基础；也或
许我们习惯于坐享其成，已经遗忘了自己必须耕耘。

即使我可以运用手段使他人投我所好，为我赴汤蹈火，或对我产生好感，彼此同仇敌忾；然
而只要品德有缺陷，尤其是言不由衷、虚情假意，终究成不了大器，因为言不由衷会招致怀
疑，到时一切的所作所为都会被视为别有用心。任凭再冠冕堂皇，甚至于出发点再良善，如
果不能获得信任，就算成功了也经不起考验。因此，惟有基本的品德能够为人际关系技巧赋
予生命。





* 第一部分 重新探索自我第一章 由内而外全面造就自己（三）

只重技巧就仿佛考前临时抱佛脚。纵使有时顺利过关，甚至成绩还不错，但不经过日积月累
的苦读，绝对无法学得精通，也不能增进心智成长。

试想如果耕种也临时抱佛脚，这不是很荒谬吗?春天忘了播种，夏天忙着享乐，秋天能够收
成吗?播种什么收获什么，没有捷径可抄，这是自然界的定律。

世事也是这样。在人为的社会体制中，例如学校里，你或许能靠着一点小聪明，成功于一时。
短暂的人际关系中，你也可凭借个人魅力畅行无阻，不但给人留下良好的印象，甚至会被视
为知己。但对于持久的人际关系，这些次要的长处便英雄无用武之地了。倘若没有真诚的品
德作后盾，日久见人心，真正的动机总会浮现，一时的成功便难以为继。

许多具备这些次要优点，也就是社会公认有才华的人，往往欠缺基本的品德。不论是同事、
朋友、配偶或处于尴尬年龄的青少年，你的四周一定存在这种有缺陷的人。事实上品德才是
沟通的利器。美国作家、哲学家爱默生(ralph waldo emerson)曾说：“大声喧哗反而难以
入耳。”

当然，也有人品德修养不错，却不善言辞，自然影响到人际关系的品质，但毕竟瑕不掩瑜。
由此可见，内在本质比外在言行更具有说服力，这个道理人人都知道。有人能获得完全的信
赖，因为我们了解他的本性。所以不论他是否能说会道，或是否擅长于人际关系，我们依然
信任有加，而且与他们合作无间。

文学家乔登(william george jordan)曾说：
人性可善可恶，冥冥中影响着我们的一生，而且总是如实反映出真正的自我，那是伪装不来的。

认识个人的心灵地图
本书汇集了追求圆满人生所不可或缺的七个基本习惯，它们是长保快乐成功的不变真理，放
诸四海皆准。不过，我们必须先了解人类的“思维”以及如何转换思维，才能真正认识这七
个习惯。

先前提到的品德成功论与个人魅力论就是两个典型的社会思维。“思维”(paradigm)这个字
来自希腊文，最初是一个科学名词，目前多半用来指某种理论、典范或假说。不过广义而言，
是指我们看待外在世界的观点。我们的所见所闻并非直接来自感官，而是透过主观的了解、
感受与诠释。

简言之，我们可以把思维比作地图。地图并不代表一个实际的地点，只是告诉我们有关地点
的一些信息。思维也是这样，它不是实际的事物，而是对事物的诠释或理论。

乍到一处陌生地方，却发现带错了地图，难免感到冤枉无助。同样地，若想改进缺点，但着
力点不对，徒然白费工夫，与初衷背道而驰。或许你并不在乎，因为你奉行“只问耕耘不问
收获”的人生哲学。但问题在于方向错误，“地图”不对，努力便等于浪费。惟有方向(地
图)正确，努力才有意义。在这种情况下，只问耕耘不问收获也才有可取之处。因此，关键
仍在于手上的地图是否正确。

我们每个人脑海中都有许多地图，大致上可分为两大类：一是关于现实世界的，是有关个人
价值判断的。我们以这些心灵的地图诠释所有的经验，但从不怀疑地图是否正确，甚至于不
知道它们的存在。我们理所当然地以为，个人的所见所闻就是感官传来的信息，也就是外界
的真实情况。我们的态度与行为又从这些假设中衍生而来，所以说，思维决定一个人的思想
与行为。

现在来做一个小小的测验，请先看图1-1与图1-2。你认为图中是两位女士吗?她们大约几岁?
长相如何?衣着如何?身分又如何?

或许你认为图1-2的女士是位妙龄女子，时髦、端庄、讨人喜欢，是约会的好对象，也有当
模特儿的本钱。如果我说你看走眼了，这位女士已六七十的高龄，而且面带忧戚，绝非模特
儿，或许过马路时还有劳你扶她一把，你会有什么反应?究竟谁才是对的?假使不论你怎么观
察，也看不出那是一位老妇人，不妨再试试看。你能否辨认出她的硕大的鹰钩鼻子，她的披
肩?

若我们是面对面地讨论，你就可以把你看到的描述给我，我也可以把我看到的讲述给你。这
样不断交流看法，直到我们都清楚地把所看到的指点给对方。

因为做不到这一点，所以现在请再看图1-3，并且将它与图1-2对照。你看出这位老妇人了吗?在
继续往下读之前请先看看她，这很重要。

多年以前我就读哈佛商学院时，首次接触这个实验。当年那位教授借此说明，不同的人对同
样一件事会有不同的看法，并且都能成立。这无关乎逻辑，而是心理因素使然。

起先，教授把两叠卡片分发给教室两边的同学，其中一叠是图1-1的少妇像，另一叠是图1-3
的老妇像。他给我们10秒钟观看这些卡片，然后收回。接着在银幕上打出两者重叠后的画面，
也就是图1-2，并要全班描述这位女子。结果，事先看过少妇像的，几乎一致认定这就是那
位少妇；而先前看到老妇像的同学，也都认为图1-2是位老妇人。

接着教授请同学说明理由，双方各执一词：
“别开玩笑，我看她绝对不超过二十几岁，怎么可能是个老太婆?”
“你才开玩笑，她少说也有70。”
“你怎么啦?瞎了吗?她很年轻，漂亮又可爱。我倒想带她出去遛遛。”
“可爱?她是个丑老太婆。”
当时我们都心知肚明自己观点不一定正确，对方的看法也可能成立，只是口头上谁也不肯认
输，只有少数同学试着从另一种角度来看这幅画像。

经过一番争辩，双方僵持不下。终于有位同学走上前去，指着一条线条说：“这少妇戴了一
串项链。”另一位马上反驳：“不，这是老妇的嘴角。”于是大家你来我往开始一一讨论画
中每个细节，并逐渐接受对方的观点。但当转过脸去，然后再回头看时，大多数人又会立即
认出当时被限定在10秒钟之内看到的形象。





* 第一部分 重新探索自我第一章 由内而外全面造就自己（四）

后来我为个人或公司担任顾问时，经常借用这个实验，因为它能够使我们对人以及人际关系的本质，有更透彻的认识。最要紧的是，它充分体现出制约作用对我们的思维有多大的影响力。仅仅10秒钟就能产生如此这般的影响，持续终身的制约作用可想而知。人的一生中，来自家庭、学校、工作环境、亲友同事、宗教以及流行思潮(如个人魅力论)的影响力，均在不知不觉中制约着我们，左右着我们的思维——心灵地图。
这个实验也说明，思维是行为与态度的根本，我们的一言一行均脱离不了思维的影响。就以图1-2为例，你若认为那是一位少妇，就自然不会想到搀扶她过街。你对她的态度和行为必须同你对她的看法相一致。
由此可凸显个人魅力说的基本缺陷之一，也就是仅仅强调行为与态度的皮毛，却忽略了根源。
从这个实验中，我们还可体会到观点对人际关系的作用。一般人总认为自己的观点正确且立场客观，但实验却证明，虽然别人的结论不同，并不代表他们是主观的、错误的。
事实上，我们高估了自己，因为我们是透过有色眼镜去看外在的世界，也就是用自身的观点去看。因此当有人跟我们意见不一致时，我们便直觉认为别人有问题。其实观点不同以致看法有异，是完全正常的现象。
不过这并不表示没有客观的事实存在。譬如在图1-2中，双方都看到了白底黑线条，也都承认它的存在，只是每个人根据以往的经验而有不同的诠释。若不经过诠释，这些事实便不具有任何意义。
一旦我们对自身的基本思维(地图)以及经验加诸我们的影响力，有愈多的认识，就愈能够为自己的思维负责，并加以检视。同时对别人的看法与思维也愈能够接纳，如此才能获得较客观的看法。
思维转换，建立全新的观点
由这个实验所得到的种种启发当中，最重要的莫过于“顿悟”的经验，也就是忽然领悟对方原来是这样观看这幅画的。这种现象我们称为“思维转换”。第一印象对你的影响愈大，顿悟的刺激也愈大。
“思维转换”(paradigm shift)一词是美国哲学家库恩(thomas kuhn)首先提出的，见于他极具影响力的经典之作《科学革命的结构》(the structure of scientific revolutions)一书。库恩在书中阐释，每一项科学研究的重大突破，几乎都是先打破传统，打破旧思维，而后才成功的。
●古埃及天文家托勒密(ptolemy)认为地球是宇宙的中心，但哥白尼(copernicus)主张太阳才是宇宙的中心，因而激起思维的转换。尽管后者曾招致强烈反抗与迫害，但转眼间，人类对宇宙万物的诠释完全改观。
●牛顿(sir isaac newton)的物理学原理虽至今仍是现代工程学的基础，但并未穷尽科学的边界。直到爱因斯坦(albert einstein)的相对论一出，又为科学界带来一次革命。
●有关细菌的学说未出现之前，许多妇女死于分娩，许多战士死于伤病而非敌人的攻击；直到细菌论带来了全新的观念，现代医学才有进步的可能。
●今日的美国也是思维转换的成果。传统君权神授、君主专制思维，由民主、民享的观念所取代，才促成民主宪政与自由富足的社会。
但并非所有的思维转换都是正面的。例如我们曾提到，由强调品德转为强调个人魅力，反而使我们偏离了享受真正成功与快乐的正轨。
姑且不论思维转换的利弊得失，也不必追究它是逐渐发生抑或突如其来的。总之它会改变我们的态度与行为，而且威力惊人，这是勿庸置疑的。
我个人曾有一次小小的思维转换经验。记得那是周日早晨，在纽约的地铁内，乘客都静静地坐着，或看报或沉思或小憩，眼前一幅平静安祥的景象。这时候突然上来一名男子与几个小孩，孩子的喧哗吵闹声，破坏了整个气氛。那名男子坐在我旁边，任凭他的孩子如何撒野作怪，依旧无动于衷。这种情形谁看了都会生气，全车的人似乎都十分不满，最后我终于忍无可忍对他说：“先生，你的孩子打扰了不少乘客，可否请你管管他们?”
那人抬起呆滞的目光，仿佛如梦初醒，他轻声说：“是，我想我该设法管管他们。我们刚从医院回来，他们的母亲1小时前才过去的。我已经六神无主，孩子们大概也不知该如何是好。”
你能想象我当时的感觉吗?瞬间，我看此事的角度改变了，想法、感觉与行为也随之一变。我的怒气全消，情不自禁为他感到难过，同情与怜悯之情油然而生。“噢，您的夫人刚过世?很抱歉!您能向我谈谈吗?有需要帮忙的地方吗?”所有的一切就此改观。
许多人在面临生死攸关的危机时，也会大彻大悟，以新的角度去评定生命的意义。有时突然进入一个新角色，如丈夫、妻子、父母、主管或领导，也会发生这种现象。
看法与本质
当然并非所有的思维转换，都如同我在纽约地铁的经历那般迅速，我和桑德拉教育儿子的经验，就是一段漫长、艰辛且费神的过程。一开始我们因袭传统与流俗，深信子女的成败代表父母的荣辱。直到后来，思维改变，看事情的角度不同，才彻底调整了自己以及四周的环境。
为了以全新的观点看待儿子，我们必须先重新做人。我们投入时间精力修养品德，建立不同于以往的思维。
思维与品德是息息相关的，所以说“什么样的人有什么样的思维”。如果本性不改，思维也难以转换。




* 第一部分 重新探索自我第一章 由内而外全面造就自己（五）

比方说，那天在纽约地铁的转变，也是我的本性使然。我相信，有些人即使得知真实情况，只会略感遗憾或稍有内疚感，顶多默默而尴尬地坐在那名不知所措的男子身旁。同样地，我也相信有人天生比较敏感，一开始就察觉出这名男子深受困扰，而主动去了解与帮助他，不会像我这么后知后觉。
由此可知，思维的威力无穷，因为它是我们观察外在世界所透过的“镜片”。而思维
转换无论是瞬间完成或长期酝酿而成，都是改变行为与态度的原动力。
以原则为中心的思维
品德成功论植根于一个基本信念之上，那就是人生有些原则(principle)是指向成功圆满的明灯，相当于人世间的自然法则，又仿佛自然科学的定理，放诸四海而皆准，任何人都无法否定其存在或正确性。
这些原则究竟多么真切、多么不容忽视，由柯克(frank koch)在海军学院的杂志《过程》(proceedings)中讲到的以下这段海上经历，可以获得证明：
两艘正在演习的战舰在阴沉的天气中航行了数日，我在其中的旗舰上服役。有一天傍晚，我正在船桥上负责望，但在浓重的雾气下，能见度极差。此时船长也守在船桥上指挥一切。
入夜后不久，船桥一侧的望员忽然报告：“右舷有灯光。”
船长询问光线是正逼近还是远离。望员答：“逼近。”这表示对方会撞上我们，后果不堪设想。
船长命令信号手通知对方：“我们正迎面驶来，建议你转向20度。”
对方说：“我是二等水手，贵船最好转向。”
这时船长已勃然大怒，他大叫：“告诉他，这里是战舰，转向20度。”
对方的信号传来：“这里是灯塔。”
结果，我们改了航道。
我们随着这位船长经历了一次思维转换，思维一旦移转，整个情况就完全改观。这位船长因为视线不良而看不清实情，但是认清事实在日常生活中，对我们就如同对置身浓雾中的船长，同样是很重要的。
人生的原则仿佛灯塔，是千锤百炼的真理。一般人从经验与社会制约中建立起思维——也就是地图，然后透过这些观点去看待自己的生活与人际关系。但地图并不代表地点本身，只是“主观的事实”，陈述我们对某一地点的认识。而如“灯塔”一般的原则才是“客观的事实”，不论我们的心灵地图如何解释，都无法改变它的存在。
任何人只要对人类历史的盛衰循环深切了解，都会承认这些原则是颠扑不破、历久而弥新的。国家社会的存亡与兴衰，往往就取决于是否能遵奉这些原则。
我所强调的这些原则，并非一些深奥玄妙的宗教哲理，也不属于任何特定的宗教或信仰。可以说世上各主要宗教、民族的伦理道德思想中，几乎都涵盖了它们。这些不辩自明的真理，任何人都可以心领神会，就好像人类与生俱来的良知，不分种族肤色，人人具备。即使被社会流俗或个人否定而隐晦不彰，但它们依然存在。
比方说“公平”的原则，平等与正义的思维便由此衍生而来。固然每个社会对何谓公平以及如何维持公平，看法可能分歧很大，但基本上都承认公平原则的本身。
其次是“诚实”与“正直”，这是人类互信的基础。有了这个基础，人类才能互助合作，追求个人与群体的持续成长。
“人性尊严”的原则，就如同美国独立宣言所揭示的：“人类生而平等，享有天赋不可侵犯的权利，包括生命、自由及追求幸福之权。”
此外，还包括“服务”的原则——对社会有所贡献，以及“讲求品质”或“追求卓越”的原则。“潜力”原则是指人人均可成长进步，不断发挥潜能，展现才华。与此密切相关的是“成长”原则，也就是潜能得以发挥，特长得以展现；这个过程需要“耐心”、“教育”与“鼓励”的配合。
原则不同于实践。实践是特定的行为或活动，往往适用于某一种情况，一旦情况改变便失效了。就好比父母不能完全以教养第一个孩子的方式，去养育另一个孩子。
实践是个别的、局部的，原则却是普遍的、整体的。原则适用于个人、婚姻、家庭以及公私团体，假使我们能把原则化为习惯，那么要解决个别问题就易如反掌。
原则不是价值观(value)。一群盗匪可能有相同的价值观，但他们违反了我们所说的良善原则。价值观是地图，原则才是地点本身。惟有借重正确的原则，才能认清事情的真相。
原则是人类行为的准则，也是不容置疑的基本道理，历经考验而永垂不朽。试问人们可以凭借欺骗、不公、卑鄙、庸碌、一无所长或堕落，而获得持久的幸福与成功吗?尽管对于行为规范的涵义与实践，各人有各人的说法，不过这类原则确实存在于我们的良知中。一个人的思维愈能符合上述原则，便愈正确有益。
遵循成长和变化的原则
目前盛行的个人魅力论最吸引人的地方，就是号称圆满的人生——包括个人成就、财富与良好的人际关系——有捷径可循，不必脚踏实地去追求。
这种华而不实、“暴发户式”的论调，无异于鼓励不劳而获。纵使得以成功，也是胜之不武。
强调个人魅力既不切实际，又会误导人心。一步登天就如同身在芝加哥，手上拿的却是底特律的地图，欲速则不达。
对这种主张颇有研究的美国哲学家弗罗姆(erich fromm)曾说：
现在我们常见到一类浑浑噩噩的人，没有自知之明，却也毫不在乎。惟一认识的人，是别人眼中的自己。他们已失去沟通的能力，终日言不及义；一脸伪善，见不到真情流露；除了无聊至极的感觉，早已无法感受真正的痛楚。我们可以用两句话来形容这种人：一是他们丧失了天性与个人特质，而且无可救药；再就是基本上他们并不比芸芸众生更高明。




* 第一部分 重新探索自我第一章 由内而外全面造就自己（六）

人生有许多成长发展的阶段，必须循序渐进。小孩子先学会翻身、坐立、爬行，然后才学会走路、跑步。每一步骤都十分重要，而且需要时间，没有一步可以省略。同样地，人生的各个层面，小到学钢琴，或是与同事相处；大至个人、家庭、婚姻与社会上的种种，莫不如此。
然而，在有形的事物上，我们较能接受“循序渐进”的原则。但在精神领域、人际关
系，甚至个人品性上，一般人却不见得能了解这一原则。即使了解，也不一定能够认同或加以实践。于是有人难免想抄近路，企图投机取巧。
但是缩短自然成长与发展的过程，结果如何呢?假设你的网球技术普通，却想与高手较量，只为了给人深刻的印象，结局不问可知。难道只靠高昂的意志就能帮助你击败职业高手?又假设你琴艺平平，却向亲朋吹嘘有开演奏会的实力，牛皮终有吹破的一天。
想要不劳而获、一蹴而就，不但违反自然，而且寸步难行，只会使你失望，加深挫折感而已。假若拿一个10分的标尺来衡量，若我在任何方面的水平都只有2分，而我想达到5分，那我首先必须向3分迈进。所谓“千里之行，始于脚下”，便是这个道理。
如果学生不肯发问，不肯暴露自己的无知，不肯让老师知道他真正的程度，那么绝对学不到东西，也就不能有长进。而且伪装实非长久之计，总有被拆穿的一天。承认自己的无知往往是求知的第一步。美国文学家及哲学家梭罗(henry david thoreau)曾说：
如果我们时时忙着展现自己的知识，将何从忆起成长所需的无知?
记得有一次，一位朋友的两个女儿向我哭诉，抱怨她们的父亲太严厉、不知体谅。她们不敢向父母吐露，却迫切需要父母的爱、关怀与教导。
我跟朋友详谈，他承认脾气不好，却不肯为自己的行为负责，更不愿承认修养不够。他的自尊心使他无法迈出改变的第一步。
与配偶、子女、朋友或同事相处，最要紧的就是学习倾听，这需要相当成熟的修养。倾听代表耐心、开放与想要了解对方的诚意，这些都属于成熟的人格。反之，自说自话、不尊重别人却轻而易举得多。
打网球或弹钢琴时，个人的实力往往高下立判，可是品格与情绪的成熟与否就不易分辨。因此，在陌生人甚至同事面前，我们可以伪装得万无一失，一时间不致被拆穿，甚至骗得了自己。但我相信，一般人对自己的人格多半心里有数，旁人也不是傻子。
我看过太多投机取巧却徒劳无功的例子，企业界尤其这样。不少企业主管试图通过强有力的演说、微笑训练、施加压力，或是善意、敌意的购并，来达到提升生产力、士气与改善品质、服务水准等目标。他们虽“购买”了新的企业文化，却忽略了如此玩弄权术，难以建立互信的气氛。而一旦这些手段效果不明显，他们又求助于其他技巧。其实，惟有在自然而循序渐进的基础上，才能发展出高度信赖的企业文化。
多年以前我也犯过同样的过错。在女儿3岁生日的那一天，我一进门就发现气氛不太对劲。她站在客厅角落，手上紧紧抓着礼物，不让其他小朋友玩。面对在场的家长，我觉得分外尴尬，因为当时我正在大学教授人际关系。心想，应该趁此机会教导女儿礼让的观念，这是最基本的价值观之一。
于是我先用命令的方式：“宝贝，请把小朋友送的礼物分给大家一起玩，好不好?”
“不!”她毫不犹豫地拒绝了。
接着，我试图跟她讲道理：“你现在肯跟小朋友玩玩具，下一次你到他们家，他们也会把玩具让给你玩。”
结果她依然不肯。我觉得很窘，连3岁小孩都管教不好。迫不得已只好贿赂，我轻声对她说：“如果你肯让别的小朋友玩玩具，爸爸就给你一个特殊的奖品——一片口香糖。”
她大叫：“我不要口香糖。”
这时我也发火了，威胁道：“如果不让出玩具，你看我怎么处罚你!”
女儿哭道：“我不管，这些是我的玩具，我不要跟别人一起玩!”
最后我只好采取强迫手段，硬从她手上抢过一些玩具分给其他小朋友。
或许我的女儿需要先经历拥有的感觉，然后才会心甘情愿地付出。(事实上，如果不曾拥有，又如何付出?)身为父亲的我，情绪应该相当沉稳，知道她需要经历这个阶段。
可是我当时担心其他家长的反应，其程度超过对孩子成长及亲子关系的重视。我只是直觉认定自己是对的，她不肯礼让就是错的。
或许因为我不够成熟，才对女儿做了过高的要求。我缺乏耐心，又未能体谅幼小的心灵，一味期待她懂得礼让。最后只有借重父亲的权威，强迫她照吩咐做。
如此一来反而凸显弱点，因为你必须倚重外力来达到目的。不但阻碍被迫顺从一方的成长，也妨碍其独立判断与自律能力的发展，对彼此的关系弊多于利。结果是畏惧心理取代合作态度，最后双方都流于专断而急于自保。更何况，你所借重的优势——不论是体型、力气、职位、权威、学历、社会地位、外表或是过去的成就——若发生变化甚至消失，又该怎么办呢?
当年如果我更为成熟，就不会诉诸父亲的权威，而会以对礼让观念与儿童成长的了解，并基于爱护与教养子女的立场，让女儿自行决定要不要让出玩具。或许在讲理不成后，我可以带孩子们做个有趣的游戏，转移他们的注意力，也解除女儿心理上的压力。现在我已明白，一旦儿童体会了真正拥有的感觉，自然会乐于与他人分享。
经验告诉我，教导孩子也要因时制宜。在关系紧张、气氛僵硬的时候，教导会被视为是价值判断与否定。但私下相处融洽时，循循善诱，效果极佳。可惜当年我还无法体会这一点。

www。xiaoshuotxt.net



* 第一部分 重新探索自我第一章 由内而外全面造就自己（七）

。小%说^t*xt-天.堂
或许在真正懂得分享之前，需要经历拥有的感觉。许多人对家庭或婚姻只知机械式地付出，不然就是完全不懂得付出；这可能正由于他们从不了解拥有自我的意义，缺乏对自我的认同，而且自我评价低。所以真正有益于孩子的教养方式，应该是以充分的耐心，培养他们拥有的感觉，同时以足够的智慧，教导他们“乐善好施”的价值，并且经常以身作则。
问题的症结在于治标不治本
一般人对于成功的个人、家庭与团体，总是钦羡不已。他们羡慕别人的能干、成熟，家人的团结合作，以及组织的团队精神。但他们真正想知道的却是成功背后的秘诀，向成功者请教的，不外乎如何能够立竿见影、立收解决自身难题的方法。
有这种想法的人，就有能提供这类答案的人。有时候速成的办法还颇管用，可暂时消除一些表象的问题。只是真正的症结依旧存在，久而久之问题又会浮现。而且愈是求助于“特效药”，病症拖得愈久，病情愈加恶化。
现在让我们回顾一下本章刚开始所提到的几个例子。
●我上过无数教导主管如何有效管理的课程，我对员工的期望很高，也想尽办法善待他们，希望维持彼此良好的关系。可是总觉得员工不忠心，我若是有一天生病在家，他们一定会终日无所事事闲扯。为什么不能把他们训练成独立又有责任心的员工呢?为什么我始终找不到这种员工?
对急于想约束员工却束手无策的那位经理，个人魅力论建议他采取激烈的手段，大事整顿一番，逼得员工兢兢业业。或者让员工接受相关的训练，以提高工作热忱，甚至另聘更称职的外来和尚。
但阳奉阴违的员工，私底下可能正质疑着老板究竟有没有为他们着想，有没有把他们当作机器看待。员工的想法也许并非空穴来风，老板心中的确如此看待他们，而主管态度偏差或许就是管理不善的原因之一。
●我要做的事太多了，可是总感到时间不够用。每天都觉得神经紧张、匆匆忙忙。一周7天，天天如此。我参加时间管理研讨会，也尝试过不下6种规划时间的办法，虽然不能说没有帮助，但是仍觉得无法过上理想中的既充实又自在的生活。
对于时间总是不够用的人，个人魅力论保证一定有解决之道，例如各种时间管理的计划与讲座，便是针对需要而设计的。
但你是否想过，提高效率也许并不能解决问题。以更短的时间完成更多的工作，难道真的如此重要，抑或反而会使你对周遭的人与事更为轻忽草率?是否有些事情才是真正值得你深入认识与体会，包括某些思维足以影响你对时间、生命与自我本质的看法?
●我的婚姻已变得平淡无趣。我们并没有恶言相向，甚至大打出手，只是不再有爱的感觉。我们请教过婚姻顾问，也试过许多办法，可是仿佛就是无法重新燃起往日的爱情火花。
对于婚姻已进入平淡期的人，个人魅力论会指点你，某本书或某种课程有助于表达能力，可以增进夫妻感情。或者，就干脆认为这桩婚姻既然已经这样，还不如另起炉灶，以重新享受爱的感觉。
然而也许问题并不出在另一半，是你助长了对方的缺点，间接导致所遭受的待遇。你对配偶、婚姻、爱情的基本观念，可能正是问题的根源所在。
由以上的例子，你是否已察觉个人魅力论如何深入人心，彻底左右着我们对问题的看法以及寻求解答的途径?
不论一般人觉悟与否，总之现在已有愈来愈多的人，对这些空洞的承诺不再存有幻想。我曾与全美各类组织合作，发现目光远大的主管，对只会以动人的故事或空唱高调，来振奋人心、激励成就的作风，都敬而远之。他们要的是实际而循序渐进的办法，不是阿斯匹灵与急救箱式的建议。他们希望解决长久的根本问题，并且把重心放在有长远未来的原则上。
反求诸己，由内而外
著名科学家爱因斯坦曾说：
重大问题发生时，依我们当时的思想水准往往无法解决。
当我们环顾四周、审视内心，发现因追求速成特效反而制造了许多问题之后，才会了解，有些根本的问题不能以肤浅的方式解决。因此我们需要更深入的新思想标准，也就是一套正确的行为准绳，引导我们解决根本的问题、追求圆满的人生。这种新的思想标准，也就是高效能人士的七个习惯，它强调以原则为中心，以品德为基础，以及能达到个人效能和人际效能(interpersonal effectiveness)的“由内而外”的修炼。
“由内而外”(inside-out)即反求诸己，由个人最基本的部分——思维、品德与动机——做起。
如果你想拥有美满的婚姻，那么就做一个能产生助力而非阻力的人，不要一味强求对方。如果你希望青春期的子女更听话，更讨人喜欢，那么先做个言行一致、充满爱心且懂得体谅的父母。如果你希望在工作上享有更多自由与自主，那么先做个更负责尽职的员工。如果你希望获得信任，那么先做个值得信任的人。如果你希望才华不被埋没，那么先修养自己的基本品德。
由内而外的修炼强调，先追求个人的成功，才能有人际关系的成就；先信守对自己的承诺，才能信守对他人的诺言。凡是以个人魅力重于品德，或者不能由个人修养做起，而期望改善人际关系，都将徒劳无功。
由内而外是一个过程，是遵循主宰个人成长进步的自然法则，不断精益求精的过程。它会形成良性循环，把我们提升到自立自强与相互依存的更高境界。我曾与许多才华横溢且渴望幸福成功的人共事，其中包括企业主管、大学生、宗教与民间团体人士、夫妇。从我与他们接触的经验证实，求助于外力所得到的幸福、成功或解决问题之道，往往经不起考验。
这种由外而内的观念，往往使人产生怨怼的心理，眼中只看到别人的缺点或致使彼此关系不和的客观环境。我见过一些婚姻亮起红灯的夫妇，夫妻俩都只希望对方改变，都忙着揭发对方的“罪状”，都希望控制对方。我也经历过一些劳资纠纷，双方宁可耗费大量时间精力，订下种种规章彼此约束，但事实上谁也不信任谁。
我的家人曾住过世上三个最“热闹”的地方——南非、以色列与爱尔兰。这些地区的冲突始终悬而未决，我相信必然是因为社会大众不能反求诸己。每一方都认为问题是别人造成的，如果“别人”能够“讲理”或突然“消失”，问题自然就解决了。
至于我们所提倡的反求诸己、由内而外的思维，因为个人魅力论的流风所及，再加上传统观念影响，因此当事人往往需要大幅度的自我调适才能转换思维。
其实从我自身以及与人共事的经验，再加上仔细观察历史的心得，我确信本书的七个习惯早已深入人心，它们所涵盖的原则符合一般人的良知与常识。但是为了要确认这些原则，并加以发挥来解除内心深处的困惑，我们必须改变想法，转换思维，提升自我到一个“由内而外”的新境界。
当我们认真了解这些原则，并将之融入生活，我相信美国诗人艾略特(tseliot)这句名言就会不断涌现真义：
我们必不可停止探索，而一切探索的尽头，就是重回起点，并对起点有首次般的了解。

www、xiaoshuotxt.net



* 第一部分 重新探索自我第二章 七个习惯——概论（上）

习惯对我们的生活有绝大的影响，因为它是一贯的。在不知不觉中，经年累月影响着我们的品德，暴露出我们的本性，左右着我们的成败。
人的行为总是一再重复。因此卓越不是单一的举动，而是习惯。
——亚里斯多德(aristotle),古希腊哲学家、文艺理论家
人的品德基本上是由习惯组成的。俗语说：
思想决定行动，行动决定习惯，习惯决定品德，品德决定命运。
习惯对我们的生活有绝大的影响，因为它是一贯的。在不知不觉中，经年累月影响着我们的品德，暴露出我们的本性，左右着我们的成败。
美国著名教育家曼恩(horace mann)曾说：“习惯就仿佛一条缆绳，我们每天为它缠上一股新索，不要多久就会变得牢不可破。”这句话的后半段我不敢苟同，我相信习惯可以养成，也可以打破，但决不是一蹴而就，而是需要长期的努力和无比的毅力。
太空人搭乘阿波罗11号太空船(apollo 11)，首次登陆月球的刹那，的确令人叹为观止。但太空人得先摆脱地球强大的引力，才能飞往月球。因此在刚发射的几分钟，也就是整个任务一开始的几英里之内，是最艰难的时刻，所耗的力量往往超越往后的几十万英里。
习惯也是一样，它具有极大的引力，只是许多人不加注意或不肯承认罢了。想要革除因循苟且、缺乏耐心、吹毛求疵或自私自利等不良习性，若是缺乏意志力，不能大刀阔斧地改革，便难以实现目标。“起飞”需要极大的努力，然而一旦脱离重力的牵绊，我们便可享受前所未有的自由。
习惯的引力就如同自然界所有的力量一般，可以为我们所用，也可能危害我们，关键看我们如何运用。不过，习惯或许一时有碍于达成目标，但也有积极的一面。宇宙万物各循轨道运行，彼此保持一定的秩序，毕竟也都有赖于引力的作用。所以只要我们善于运用习惯的庞大引力，就能使生活有重心、有秩序、有效率。
“习惯”的定义
本书将习惯(habit)定义为“知识”、“技巧”与“意愿”三者的混合体。
知识是理论性的观念，指点我们“做什么”及“为何做”。技巧是指“如何做”。意愿则是“想做”，表示我们有付诸行动的愿望。要培养一种习惯，这三项要素缺一不可。
假设我与同事、配偶或女儿相处得并不融洽，因为我总是只愿表达自己的意见，从不肯倾听。除非我有心改善人际关系，设法了解正确的待人接物之道，否则我可能根本不“知道”我必须聆听。即使知道了，也不见得明了该“如何”去倾听。但知道应该聆听，也懂得倾听的技巧，还远远不够。除非我真想听、有这个意愿，否则依然无法养成习惯。因此习惯的培养需要这三方面的配合。
前面曾提到，要提升自我必须先从思维着手。思维一旦改变，对外界的看法自然不同，而且又会回过头来影响自我，形成一个良性循环。所以我们应该从知识、技巧与意愿三方面努力，突破旧有思维的束缚，使个人与人际关系都能更上一层楼。
改变习惯的过程可能很不好受，毕竟习以为常的事物比较能给人安全感。但为追求一生的幸福与成功，暂时牺牲眼前的安适与近利，也是值得的。经过一番努力与牺牲所换来的果实，将更为甜美。
成熟模式图：成长三阶段
本书所提出的七个习惯是相辅相成、一气呵成的。借着培养这些习惯，我们可以循序渐进，由依赖而独立，再由独立进而互赖。
人类在幼年时期必须完全仰赖他人，经由长辈的引导与养育而成长。但随着光阴的流逝，我们日渐独立。生理、心理、情感与经济能力等方面，都不断成长，直到有一天终于能够完全自立。
但这并不表示成长就到此为止。在不断提升自我的同时，我们可以体会宇宙万物唇齿相依的关系。包括人类社会在内，整个大自然共享着一个生态体系，个人无法离群索居。大凡人类较高层次的心智活动都与人际关系有关，就是明证。
由婴儿以致于成人，是人生必经的历程。只不过成长涵盖许多层面，例如生理上发育完全并不意味着心理或情感同样成熟。相同地，生理上有缺陷，也不代表心理不成熟。
所谓“成熟模式图”(maturity continuum)，即人类成长的三个阶段，分别为依赖期、独立期、互赖期。
●依赖(dependence)期：围绕着“你”这个观念——你照顾我；你为我的成败得失负责；事情若有差错，我便怪罪于你。
●独立(independence)期：着眼于“我”的观念——我可以自立；我为自己负责；我可以自由选择。
●互赖(interdependence)期：从“我们”的观念出发——我们可以自主、合作、统合综效，共创伟大前程。
依赖心重的人，靠别人来完成愿望；独立自主的人，自己打天下；互赖的人，群策群力以达成功。
如果生理上无法自立，例如身体有残缺，便需要别人的帮助。假使情感不能独立，价值观与安全感建立在别人的评价上，一旦无法取悦别人，个人便失去价值。若是知识上无法独立，就得依赖旁人代为思考，解决生活中的大小问题。
相反地，生理上独立的人可以畅所欲为；心智上独立的人可以有自己的思想，兼具抽象思考、创造、分析、组织与表达的能力；情感上独立的人能够肯定自我，不在乎外界的毁誉。
由此可见，独立比依赖成熟得多，不过独立并非个人成长的极致。只可惜当前的社会价值观将独立奉为圭臬，大多数励志修身的书籍与文章都过分强调独立，仿佛沟通、团队精神并不重要。其实这多半是对依赖观念的矫枉过正，为避免受制于人而反抗。




* 第一部分 重新探索自我第二章 七个习惯——概论（中）

至于互赖的观念则经常受到误解，很多人把它跟依赖混为一谈，无怪乎我们往往见到有人为了自私的理由，抛弃妻子，不负责任，却都假借独立的名义。
有些人虽宣称要“摆脱桎梏”、“追求解放”、“坚持自己的权利”、“做自己的事”，其实这种行径正暴露出若干摆脱不掉的依赖心理，他们情愿让他人的缺失左右自己的情绪，或是总把自己的遭遇怪罪于外界的不公平。
当然，我们所处的环境的确有值得改进的地方，但依赖心态是个人成熟与否的问题，与环境无关。即使客观条件再好，有人永远是扶不起的阿斗。
拥有真正独立人格的人，能够事事主动积极，而非受制于人。这种境界的确值得追求，但并非圆满生活的终极目标。
只重独立并不适于人我息息相关的现代生活。一个人若缺乏互赖观念，难以与人相处共事，充其量只能独善其身；永远无法成为出色的领袖或团队的一分子，也不会有美满的家庭、婚姻与团体生活。由此可知，个人无法离群索居，想要独自追求圆满人生，无异于缘木求鱼。
互赖是一个相当成熟进步的观念。生理上互赖的人，可以自给自足，但也了解互助能发挥更大的作用。情感上互赖的人，完全肯定自己的价值，但也承认需要爱、关怀以及付出。知识上互赖的人，取人之长，补己之短。总言之，一个互赖的人，能够与人分享内心真正的感受，做有意义的交流，也能共享别人的心得。
但在此必须强调，只有独立的人才能达到互赖的境界，依赖的人还不具备足够的条件。因此，以下数章讲述的习惯，是七个习惯中的前三个，着重在如何修养自己，由依赖进而独立。这些习惯属于“个人的成功”(private victory)的范畴，是培养品德的基础。而个人的成功一定先于公众的成功，就如同播种、耕耘与收成，次序无法颠倒。就个人而言，则是先内省而后外显。
真正的独立是培养良好互赖关系的基础，凭借此基础，我们可以致力于第四、五、六个习惯所涵盖的团队精神、合作与沟通，追求“公众的成功”(public victory)。
不过，本书如此安排并不表示前三个习惯与后三个各自独立，互不关联。
其实它们可以兼容并蓄，我们如此排列是为了帮助读者了解与实践。
至于第七个习惯，则涵盖了其他六个习惯，赋予其新生命，督促我们日新又新，永无止境。
图2-2标示了这七个习惯与三个成长阶段的关系，以下各章我们仍将谈到这个图表，以及七个习惯如何相互激荡，发挥出更大的效果。
“有效性”的定义
本书介绍的七个习惯最合乎效能原则，且效果最为持久。它们能帮助你更有效地解决问题、把握机会以及吸收最多的正确观念。
我对“效能”(effectiveness)所下的定义是——“产出与产能必须平衡”(p/pc balance)。伊索寓言中有则鹅生金蛋的故事，正足以说明这个常遭人忽视的原则。
这则故事是说，一个农夫无意间发现一只会生金蛋的鹅，不久便成了富翁。可是财富却使他变得更贪婪更急躁，每天一个金蛋已无法满足他，于是农夫异想天开地把鹅宰杀，企图将鹅肚子里的金蛋全部取出来。谁知打开一看，鹅肚子里并没有金蛋，鹅却死了，再也生不出金蛋。
这则寓言是效能观念一个很好的例证。一般人往往从金蛋的角度来衡量效率，也就是产品愈多，效能愈高。可是上面的故事却告诉我们，效能包括两个要素，一是“产出”(production)即金蛋，也就是你希望获得的结果；一是“产能”(production capability)即鹅，也就是你借以达到目标的资产或本领。
仅重视金蛋，无视于鹅的人，结果会连产金蛋的资产本身都保不住。反之，“重鹅轻蛋”的人，最后可能养不活自己，更不用说鹅了。因此，产出与产能必须平衡才能达到真正的高效能。
个人的效能观
人类所拥有的资产，基本上可分为人力、物力及财力三大类。
数年前我曾经买过一项物质资产——电动割草机。我经常使用，却从不保养。前两季还没有问题，到第三季就出故障了。这时我才着手维修，可是已经太迟，引擎只剩下不到一半的马力，可以说成了一堆废铁。
如果我及早开始保养这项资产，那么现在还能享受它的产出——修剪平整的草皮。如今我必须花费更多时间与金钱来更换一部新机器，显然不符合效能原则。
由此可见，急功近利反而会破坏珍贵的资产——或许是一辆汽车、一部电脑，也可能是自己的身体或自然环境。
同样的情形也适用于金融资产。举例来说，本金与利息相当于产能与产出。如果为了改善生活而重用本金，利息收入就会减少，财产总值自然随之缩水，最后连起码的生活都无法维持。
我们最宝贵的金融资产就是赚钱的本领。如果不能持续投资，增进自己的生产能力，发展的机会便会受到限制，只能停滞于现有的职位上，终日忙着揣摩上司的心意。不仅经济上受制于人，又担心职位不保，最后落得一事无成。
对人力资产而言，产出与产能之间的平衡尤为重要。因为物质与金融资产可为人所控制，人力资产则不能。
比方说，夫妻双方都汲汲营营于获得金蛋，亦即享受婚姻的好处，却忽略了维护彼此的感情，最后便会变得冷淡而疏远。因为夫妻如果只急于耍手段、操纵对方以满足自己的需要；或是忙着为自己辨护与挑剔对方的缺点，相爱的感觉及亲密的关系自然会衰退，就好比鹅的病情一天比一天恶化。亲子关系是否也会演变到这种地步呢?子女年幼时，必须完全依赖父母，缺乏自主能力。这时候父母很容易忘却教养、沟通、倾听与感情交流——即亲子关系的产能——的重要性，而以优势的地位来操纵子女，实现自身的愿望。父母往往因过于重视产出而纵容与讨好子女。在此环境下长大的儿童多半不懂规矩，缺乏责任感。

www-xiaoshuotxt-net



* 第一部分 重新探索自我第二章 七个习惯——概论（下）

?小说/tＸt|天堂
不论权威式还是纵容式的管教，基本心态都是偏重金蛋。父母只在乎孩子是否照着他们自己的意思行事，或能不能讨好子女。至于鹅，也就是孩子未来的责任感、纪律感以及自信心，似乎就无关紧要了。等到子女进入关键性的青春期，产生认同危机之后，过去与父母相处的经验——父母是否不带批判地倾听，是否真心地关怀等等——将决定父母能否与子女亲近、沟通，甚或影响子女的行为。
举例来说，你要求女儿保持房间整洁，这是你希望得到的产出——金蛋。而你的女儿就是产能——那只鹅。如果她觉得你的要求并不过分，便会心甘情愿地整理自己的房间，无须旁人催促，因为她知道许下承诺就不应食言。这时她是一项可贵的资产，一只会生金蛋的鹅。
但是如果你只问房间是否整洁，毫不顾虑她的感受。那么即使频频唠叨，甚至以威胁、吼叫迫她就范，也是徒劳无功。因为你忽略了鹅的需要与福祉，它自然不会生金蛋了。
关于产能，我和我的一个女儿有一些有趣的经验。有一回，我们计划单独呆上一天，我对她说，“宝贝，今晚是属于你的，你想做什么?”
“噢，不用了。”她回答说，“我想做的，你不见得就想。”
“我希望做你想做的，不管你想做什么。”我诚恳地说。
“我想看《星球大战》，可我知道你并不喜欢这类科幻片。过去你看时，从头睡到尾。算了吧。”
“不，宝贝，如果你想看，我会愿意看的。”
我们去了。她坐我身边，给我讲解。我成了她的学生，她的听众。
这不是有计划的产出经验；这是产能投资的偶然成果。但是我们也得到了金蛋，因为鹅——父女关系的质量——养得很好。
团体的效能观
任何正确的原则最可贵的地方，就在于可以适用于各种不同的状况。本书所提到的每个原则，不仅适用于个人，也适用于团体(包括家庭)。
产出与产能平衡的原则，在团体生活中如何运用呢?假使组织成员运用物质资产时，不尊重平衡的原则，便会降低效能，而且往往遗祸继任者。
譬如某人负责管理一部机器。为了讨好上司，便把产能发挥到极致，从不维修，任由机器日夜运转。结果产量提高，成本大幅降低，利润因而激增。由于公司此时正在迅速扩张，升迁机会多，所以不久他就获得晋升，得到了金蛋。
但如果你接替他的职位，接收到手的却是一只病鹅，你必须加倍维修，给予机器喘息的机会。结果成本飞涨，利润剧降，这些损失会算到谁的账上呢?当然是你。你的前任者破坏了这项资产，但会计账簿上却只列出产量、成本与利润。
再谈到人力资源。产量与产能平衡的原则，对一个团体的人力资产——即顾客与员工——的运用更为重要。
我认识一家以蛤蜊浓汤叫座的餐厅，每天中午都高朋满座。可是后来餐厅转手，新老板认为利润重于一切，于是在浓汤中掺水。第一个月的确大发横财，因为成本降低，顾客却依然捧场，但是渐渐地顾客不再上当。失去了顾客的信任，这家餐厅最后终于门可罗雀。即使此时老板想重新回头，可惜已失去宝贵的资产——顾客的信任，会生金蛋的鹅不再存在了。
有些公司虽强调顾客至上，却完全忽略为顾客服务的员工。我的建议是：“你希望员工如何对待顾客，就如何对待员工。”
因为你可以收买一个人的双手，却买不到他的心，而心才是忠诚与热忱的根源。你也可以收买一个人的形体，却买不到他的头脑，而头脑才是创造力与才华智慧的大本营。重视人力资产的主管，应该把员工和顾客当作自愿工作者一般好好对待，因为他们确实是心甘情愿地奉献可贵的心智与忠诚。
在一场讨论会上，有人问：“对懒散与表现欠佳的职员，该如何整顿?”一位仁兄回答：“投几颗手榴弹!”有些人颇附和这种强势管理的主张——“不争气就淘汰”。
可是接着又出现下面的回答：
“谁来收拾残局呢?”
“不会有残局。”
“那你何不用同样的方式对待顾客：‘如果不想买就滚蛋吧!’”
“那怎么可以这样对待顾客?”
“那为什么可以这样对待员工?”
“因为他们是我雇来的。”
“原来如此。请问你的员工是否忠心耿耿、勤奋工作?流动率大不大?”
“别开玩笑了，现在根本找不到好帮手。人人都想请假、兼职、跳槽，对公司毫不在乎。”
像这种只重金蛋的态度，实在难以激发员工的潜能。眼前的盈余固然重要，但却不应凌驾一切之上。
过分重视产出，会破坏健康、耗损机器、降低银行存款及危害人际关系。但太过维护产能，就如同一个人每天长跑三四个小时，满以为可以因此多活10年，但不知其实正在透支生命。又好像有些人，不断念书却从不事生产，只知坐享别人的金蛋，永远不敢面对现实世界。
惟有产出与产能取得平衡，才能达到真正的效能。虽然你常会因此面临困难的抉择，但这的确是效能原则的精髓所在。日常生活中，足以印证这个道理的例子俯拾即是。譬如你是否曾因想多做点事情，熬夜不眠，结果却弄得精疲力竭，甚至身体不适?反之，若是好好睡一觉，则第二天精力充沛，可以做更多的事，并准备迎接一天的挑战?
或者，有时别人虽屈服在你的压力下，你的内心却仍感到空虚。这时候倒不如开诚布公，努力经营人际关系，反而能赢得信任与合作。
产出与产能平衡是有效性的精髓，放之四海而皆准。它是灯塔，也是本书阐述的七个习惯的基础。




* 第二部分 个人的成功：从依赖倒独立第三章 习惯一：积极主动（一）

　——个人愿景的原则
人性本质是主动而非被动的，不仅能消极选择反应，更能主动创造有利环境。
采取主动并不表示要强求、惹人厌或具侵略性，只是不逃避为自己开创前途的责任。
最令人鼓舞的事实，莫过于人类确实能主动努力以提升生命价值。
——梭罗(henry david thoreau)，美国文学家及哲学家
现在请尝试跳出自我，把意识转移到室内屋顶的某个角落。然后以客观的角度，观察你阅读本书的情况。你能够把自己当作一个不相干的人来观察吗?
再换个方式，想一想现在的心情如何，你能够用语言形容吗?
接下来，请检讨心智是否反应灵敏，是否正在为这个实验的目的而纳闷。
以上这些都是人类特有的精神活动，而动物则缺乏这种自觉(self-awareness)，也就是自我觉察的能力。这是人之所以为万物之灵，以及能够不断进步的关键；同时也是我们能从经验中汲取教训，并且改善习性的根本缘由。
凭借自觉意识，我们可以客观检讨我们是如何“看待”自己——也就是我们的“自我思维”(self-paradigm)。所有正确有益的观念都必须以这种“自我思维”为基础，它影响我们的行为态度以及如何看待别人，可说是一张属于个人的人性本质地图。有了这种认识之后，将心比心，我们也就不难体会他人的想法。否则难免会以己之心度人之意，以致于表错情会错意。幸好人类独有的自我意识，使我们能够检讨自己的自我思维究竟确实发自内在，还是来自社会的制约与环境的影响。
社会眼中的我
如果我们对自己的惟一想象来自“社会眼中的我”(social mirror)——依照时下流行的价值观以及四周人群的看法来衡量自己，那么所看到的景象就仿佛是从哈哈镜里反射出来的自己。
“你从不守时。”
“你为什么不能保持整洁?”
“你准是一名艺术家!”
“你真能吃!”
“我不相信你会赢!”
“这么简单的事，你都弄不懂。”
然而，这些支离破碎的评语不见得代表真正的你，充其量不过反映说话者自身的想法与缺点而已。
目前一般人都认为，人性是环境与制约作用的产物。的确，制约作用对人的影响极大，前面我们也提到这一点。但若认为人的意志无法克服社会制约，未免错得离谱。
不过这类“决定论”相当盛行，可分为三大类：
一、基因决定论(genetic determinism)：认为人的本性是祖先遗传而来。你的脾气不好，那是因为祖父母就是这样，借着基因承袭到你身上。
二、心理决定论(psychic determinism)：强调你的个性是父母种下的因。父母的教养方式与童年的经验，造就了今日的你。你从不敢强出头，因为从小爸妈告诫不可以这样。你每次犯错都内疚不已，因为你忘不了小时候表现欠佳所受到的排斥与心理伤害，以及被拿来与别人比较的感受。
三、环境决定论(environmental determinism)：主张环境决定人的本性。周遭的人与事，例如老板、配偶、子女，或者经济状况、国家政策，都可能是影响因素。这种理论是根据俄国心理学家巴甫洛夫(ivan petrovich pavlov)以狗为实验，所得出的“刺激—回应”理论。也就是我们对某一刺激的回应，受制约作用所左右。这些理论是否正确，是否能自圆其说，有待商榷。
选择的自由
要回答上述疑问，请先看弗兰克尔(victor frankl)的感人事迹。
他是一位受过弗洛伊德(sigmund freud)心理学派洗礼的决定论者。这个学派认为一个人的本性在幼年时期即已定型，而且会左右一生，日后改变的可能性微乎其微。弗兰克尔由于身为犹太裔心理学家，二次大战期间被关进纳粹(nazi)死亡营，遭遇极其悲惨。父母、妻子与兄弟都死于纳粹魔掌，惟一的亲人只剩下一个妹妹。他本人则受到严刑拷打，朝不保夕。
有一天，他赤身独处于囚室，忽然之间意识到一种全新的感受。日后他将此感受命名为“人类终极的自由”(the last of the human freedoms),当时他只知晓这种自由是纳粹军人永远无法剥夺的。在客观环境上，他完全受制于人，但自我意识却是独立的，超脱于肉体束缚之外。他可以自行决定外界的刺激对自身的影响程度。换句话说，在刺激与回应之间，他发现自己还有选择如何回应的自由与能力。他在脑海中设想各式各样的状况。譬如说，获释后将如何站在讲台上，把这一段痛苦折磨学得的宝贵教训，传授给学生。
凭着想象与记忆，他不断锻练自己的意志，直到心灵的自由终于超越了纳粹的禁锢。这种超越也感召了其他的囚犯，甚至狱卒。他协助狱友在苦难中找到意义，寻回自尊。
处在最恶劣的环境中，弗兰克尔运用难得的自我意识天赋，发掘人性最可贵的一面，那就是人有“选择的自由”(freedom to choose)。这种自由来自人类特有的四种天赋。除自我意识外，我们还拥有“想象力”(imagination)，能超出现实之外；有“良知”(conscience)，能明辨是非善恶；更有“独立意志”(independent will)，能够不受外力影响，自行其是。
其他动物智慧再高，也不具有上述的禀赋。以计算机来作比喻，动物的程序是由本能与训练设定，而且已经定型，无法更改。人类却可自创程序，完全不受本能与训练所约束。
因此，动物的能力有限，人类却永无止境。但是生而为人，如果也像动物一样，只听命于本能及后天环境的影响，发展自然极其有限。
决定论所依据的观念主要来自对动物的研究，虽然在学理上有其价值，但人类历史以及自我意识都证实，这类的人性地图根本不确实。
“积极主动”的定义
弗兰克尔在狱中发现的人性典则，正是追求圆满人生的首要准则——“积极主动”(be proactivity)。
这个英文字如今经常出现在管理方面的著作里，但大部分字典都查不到。它的涵义不仅止于采取主动，还代表人必须为自己负责。个人行为取决于自身，而非外在环境；理智可以战胜感情；人有能力也有责任创造有利的外在环境。
责任感是一个很重要的观念，能够积极主动的人深谙其理，因此不会把自己的行为归咎于环境或他人。他们待人接物是根据自身原则或价值观做有意识的抉择，而非全凭对外界环境的感觉来行事。
积极主动是人类的天性，如若不然，那就表示一个人在有意无意间选择消极被动(reactive)。消极被动的人易被自然环境所左右，在秋高气爽的时节里，兴高采烈；在阴霾晦暗的日子，就无精打采。积极主动的人，心中自有一片天地，天气的变化不会发生太大的作用，自身的原则、价值观才是关键。如果认定工作品质第一，即使天气再坏，依然不改敬业精神。
消极被动的人，同样也受制于社会“天气”的阴晴圆缺。如果受到礼遇，就愉快积极，反之则退缩逃避。心情好坏建立在他人的行为上，别人不成熟的人格反而是控制他们的利器。
理智重于情感的人，则经过审慎思考，选定自己的原则、价值观，作为行为的原动力。他们与感情用事、陷溺于环境而无法自拔的人截然不同。
不过，这并不表示积极主动的人对外来的刺激无动于衷。他们对外界的物质、精神与社会刺激仍会有所回应，只是如何回应完全掌握在自己手中。
美国小罗斯福总统的夫人(eleanor roosevelt)曾说：“除非你同意，任何人都不能伤害你。”以印度民族主义者和精神领袖圣雄甘地(gandhi)的话来说就是：“若非拱手让人，任何人无法剥夺我们的自尊。”因此，令人受害最深的不是悲惨的遭遇，而是“默许”那些遭遇发生在自己的身上。
这个观念一时的确令人难以接受，对习于怨天尤人者尤其如此。但只有真心接纳“昨日之我选择了今日之我”的观念，否则“选择的自由”便成空谈。
有一回我在萨克拉门托(sacramento)演讲，主题正是“积极主动”。讲到一半时，听众里一位女士突然站起来大声喧哗，引起不少人侧目。她自觉不好意思，才勉强坐回座位。可是依旧按捺不住，又向周围的人大发议论，神情看来相当愉快。
我不禁想听听她的高见。等不及讲到一个段落，就暂时打住，改请她上台来，与大家分享心得。她终于有了一吐为快的机会：
你们绝对想象不到我的心路历程!我是一个护士，我负责看护过一个可能是世上最挑剔、最难侍候的病人。他从来没有一句感激的话，反而处处找碴，处处作对，使我每天都过得很痛苦，然后又不由自主地把痛苦发泄在家人身上。其他护士也有同感，我们简直就希望他早点死。
而你居然站在台上大谈积极主动，说什么未得我同意，谁也不能把我怎么样。难道我的痛苦都是自找的?!这观念委实令人难以接受。
可是我仍然不断地玩味这番话，一直探索到内心最深处。我自问：我真有能力选择自己的回应吗?
终于我发现自己的确有这个能耐，在硬生生吞下这苦涩的良药，并承认痛苦是自己选择的之后，我体认到人可以选择不要痛苦。
那一刻我站了起来，只觉得自己像个重生的犯人，想向全世界宣言：“我自由了!我摆脱了牢笼!不再受制于别人给我的待遇。”




* 第二部分 个人的成功：从依赖倒独立第三章 习惯一：积极主动（二）(1)

由此可见，不幸的遭遇固然会使人身心受伤，但是基本人格可以不受影响。愈是艰难痛苦的经验，反而愈能砥砺志节，坚强意志，提升面对未来考验的勇气，甚至于感召他人。
前面提到的弗兰克尔就是一个好例子。这类在逆境中坚忍不拔的事例不胜枚举；或许是罹患重病，或许是严重残障，却因精神力量而受人钦佩，给人启示。这种超越痛苦、超越环境、发挥人性光辉的经历，的确发人深省。
我与桑德拉就拥有过这么一位朋友卡罗，她是我们结婚时的伴娘，与桑德拉相交25年以上，交情匪浅。可惜卡罗得了癌症，不久于人世。即使如此，她依然异常坚强，尽量不吃止痛药，以便能完全控制自己的心智与情绪。为了替子女未来的每个成长阶段留下一些感言，尽管十分虚弱，她还是设法对着录音机，或直接向桑德拉口述她的一生。桑德拉每每为这份勇气与苦心感动不已。
卡罗的不畏艰难、勇往直前及爱心，使许多人都受到感召与启发。我永远忘不了，她过世前一天，我在她眼中所发现的人性光辉。
多年来，我常在许多场合做小规模的调查，看看有多少人曾自临终者身上体会到类似的经验，通常有这类经验的约占1/4。若再追问，这段历程是否令人永难忘怀，以致会暂时产生“有所作为的人都应该这样”的感慨，这1/4的人在这个时候都有同感。
弗兰克尔曾指出人生共有三种重要的价值，一是经验价值(the experiential value),来自遭遇；二是创造价值(the creative value),出自个人独创；三是态度价值(the attitudinal value),也就是面临困境，如罹患绝症时的反应；这三种价值中，境界最高的是态度价值。依我多年的经验证明，这种说法的确有道理。
逆境往往能激发思维的改变，使人以全新的观点去看人与事，进而审视自己与生命的意义；并由此获得难能可贵的见地，令人感动不已。
采取主动
人性本质是主动而非被动的，不仅能消极选择反应，更能主动创造有利环境。
采取主动并不表示要强求、惹人厌或具侵略性，只是不逃避为自己开创前途的责任。
我经常劝导有意更上一层楼的人，加倍积极进取，不妨做爱好和能力的测验，研究适合从事的行业。甚至设法打听试图加入的机构正面临何种难题，然后以有效的表达方式，向对方证明自己能够协助他们解决问题。这叫做“顾问式销售”(solution selling),是事业成功的主要诀窍之一。
通常前来咨询的人都不否认，这么做的确大有助于求职、晋升，只是一般人都找出各种借口，不肯采取必要的步骤，主动开创机会。
“怎么打听某行业或某家公司的困境呢?谁肯帮我?”
“我不知该到哪儿去做爱好和能力的测验。”
“我想不出来该如何表现自己。”
太多人只是坐等命运的安排或贵人相助，事实上，好工作都是靠自己争取而来的。在我家，任何人都别想推卸责任，让别人替他设法收拾残局。即使孩子年纪还小，我照样要求他们：“自己想办法。”而家人也已习惯这种作风。
要求责任感并非贬抑，反而是一种肯定。主动是人的天性，尊重这种天性，至少可提供对方一面镜子，以便清晰且未扭曲地反映自我。
由于个人的成熟度不同，对尚处于情绪依赖阶段的人，不必期望太高。但至少可创造有利的气氛，逐渐培养他的责任感。
化消极为积极
积极主动与消极被动有天壤之别，尤其再配合聪明才智，差距就更远了。
想要生命的产能与产出平衡，进而追求圆满人生，主动精神实在不可缺少。因此本书其余六个习惯，都是以积极主动的精神为后盾。每个习惯都仰赖你积极主动，如果你消极等待，你就会受制于人，一旦受制于人，发展与机会便不会降临。
我曾经参加过某个行业的每季业绩检讨会，记得当时正值景气落入谷底，那一行所受的打击尤其大。因此会议一开始，各厂商的士气都很低落。
第一天的会议主题是该行业的现况。许多业者表示，不得不裁掉熟识的员工，以维持企业的生存。结果会后，每个人都比会前还要灰心。
第二天讨论该行业的未来，主题围绕着日后左右其发展的因素。议程结束时，沮丧的气氛又深一层，人人都认为景气还会更加恶化。
到了第三天，大家决定换个角度，着重于积极主动的做法：“我们将如何应对?有何策略与计划?如何主动出击?”于是早上商讨加强管理与降低成本，下午则筹划如何开拓市场。以脑力激荡方式，找出若干实际可行的途径，再认真讨论。结果为期3天的会议结束时，人人都士气高昂，信心十足。




* 第二部分 个人的成功：从依赖倒独立第三章 习惯一：积极主动（二）(2)

　第一天的会议主题是该行业的现况。许多业者表示，不得不裁掉熟识的员工，以维持企业的生存。结果会后，每个人都比会前还要灰心。
第二天讨论该行业的未来，主题围绕着日后左右其发展的因素。议程结束时，沮丧的气氛又深一层，人人都认为景气还会更加恶化。
到了第三天，大家决定换个角度，着重于积极主动的做法：“我们将如何应对?有何策略与计划?如何主动出击?”于是早上商讨加强管理与降低成本，下午则筹划如何开拓市场。以脑力激荡方式，找出若干实际可行的途径，再认真讨论。结果为期3天的会议结束时，人人都士气高昂，信心十足。
这次会议的结论是：
一、本行业目前的情况并不好，未来的趋势显示短期内还会更恶化。
二、但我们采取正确的对策，改进管理，降低成本，并提高市场占有率。
三、因此，这个行业的景气会比过去都好。
积极主动又与积极思考有所不同。积极主动不仅承认现实，也肯定人有权选择对现实环境做出积极回应。
任何团体，包括企业、社会团体及家庭，都可以汇集各个成员的聪明才智，对环境主动出击，以达成群体的共同目标，建立积极主动的企业文化。
不要说“我办不到”
我们可以利用自我意识检讨自身的观念，以言语为例，它颇能真切反映一个人对环境的态度。
习惯于消极被动的人，言语中就会流露出推卸责任的个性。例如：
“我就是这样。”仿佛是说：这辈子注定改不了。
“他使我怒不可遏!”意味着：责任不在我，是外力控制了我的情绪。
“办不到，我根本没时间。”又是外力控制了我。
“要是某人的脾气好一点”，意思是：别人的行为会影响我的效率。
“我不得不如此。”意味着：迫于环境或他人。
言语态度对照表：
消极被动
●我已无能为力
●我就是这样一个人
●他使我怒不可遏
●他们不会接受的
●我被迫……
●我不能
●我必须
●如果
积极主动
●试试看有没有其他可能性
●我可以选择不同的作风
●我可以控制自己的情绪
●我可以想出有效的表达方式
●我能选择恰当的回应
●我选择
●我情愿
●我打算……
有一次有位学生向我请假，因为他想随网球队到外地比赛。
我问他：“你是自愿，还是不得不去?”
“我真的没办法不去。”
“不去会有什么后果?”
“他们会把我从校队中剔除。”
“你希望有这种结果吗?”
“不希望。”
“换句话说，你为了想待在校队所以要请假，可是缺了我的课，后果又如何呢?”
“我不知道。”
“仔细想一想，缺课的自然后果是什么?”
“你不会开除我吧?”
“那是社会后果，是人为的。反之，不能加入网球队，就不能打球，那是自然后果。缺课会有什么自然后果?”
“我想大概是失去学习的机会。”
“不错，所以你必须两相权衡，做个决定。我知道，换了我，也会选择网球队，但请决不要说你是被迫这么做。”
最后这个学生当然还是参加比赛，但却是出于自己的选择。
行动胜过“感觉”
推诿责任的话语往往会强化宿命论。说者一遍遍被自己洗脑，变得更加自怨自艾，怪罪别人的不是、环境恶劣，甚至与星座也有关系。
我曾碰过这么一位男士，他说：
“你说得很有道理，可是每个人的状况不同。你看我的婚姻，我和太太已经失去了往日那种感觉，我真的很担心，或许我们已不再相爱，这该怎么办?”
“已经不再有爱的感觉了?”
“是的，可是我们有3个孩子，真叫人放心不下，你可有什么好建议?”
“去爱她。”我说。
“可是我告诉过你，我已经没有那种感觉了。”
“去爱她。”
“可是你不了解，没有了感觉如何爱?”
“正因为如此，你才要去爱她。”
“可是我办不到。”
“老兄，爱是一个动词，爱的感觉是行动所带来的成果。所以请你爱她、关心她、照顾她……你愿意这么做吗?”
在所有进步的社会中，爱都是代表动作，但消极被动的人却把爱当做一种感觉。好莱坞式的电影就常灌输这种不必为爱负责的观念——因为爱只是感觉，没有感觉，便没有爱。事实上，任由感觉左右行为是不负责任的做法。
积极主动的人则以实际行动来表现爱。就像母亲忍受痛苦，把新生命带至人世，爱是牺牲奉献，不求回报。又好像父母爱护子女，无微不至，爱必须通过行动来实现，爱的感觉由此而生。
关注圈与影响圈
从一个人对周遭事务关注范围的大小，以及发挥影响力的意志强弱，也能判断态度是否积极。每个人都有一些关注的问题，包括健康、子女、事业、经济状况或世界局势，这些可归入“关注圈”(circle of concern)。其中，有些是个人可以掌握的，有些则无能为力。把个人可以控制的事圈起来，就形成“影响圈”(circle of influence)。




* 第二部分 个人的成功：从依赖倒独立第三章 习惯一：积极主动（三）

　着重于“影响圈”的人，脚踏实地，不好高鹜远；把心力投注于自己能有所作为的事情，所获成就将使影响圈逐步扩大。
反之，消极被动的人全神贯注在“关注圈”，时刻不忘环境的种种限制、他人的种种缺失，徒为无法改变的状况担忧。结果是怨天尤人、畏畏缩缩，受迫害的感觉日益强烈。由于着力方向错误及由此而生的副作用，影响圈便会缩小。
前面曾提到我的一个儿子在学校适应不良，我与桑德拉都很担心他不如人，受人轻视，这些都属关注圈之内。起先我们把全部心力投注其上，完全处于被动，反而增添忧虑无助以及孩子的依赖心。
后来我们转移目标到影响圈，产生了积极效果，不但改变了我们，最后也影响到孩子。因此我们不必担忧外在条件，只要反求诸己，就足以化阻力为助力。
由于每个人的地位、财富、角色与人际关系不同，在某些情况下，影响圈可能大于关注圈。这反映出此人自私浅薄，也是另一种形式的受制于人。
影响力的发挥固然有其轻重缓急，无法完全脱离关注的目标。不过积极主动的人，关注圈应与影响圈不相上下，如此影响力才能做最有效的发挥。
别让问题制服了你
根据自主程度的高低，人生的问题可分为三类：个人可直接控制(与自身行为有关)；个人可间接控制(与他人行为有关)；无法控制(已成过去或客观环境使然)。积极主动的人对影响圈中的这三类问题，都有应对之道。
●可直接控制的问题：解决之道在于改变习惯，这是我们绝对做得到的。本书第二部分“个人的成功”中讨论到的习惯一、二、三即属这一类。
●可间接控制的问题：有赖改进发挥影响力的方法来加以解决，这在第三部分“人际关系的成功”中的习惯四、五、六中有所讨论。我个人即曾发掘过30余种截然不同的方法，足以影响他人。通常一般人顶多知晓个三四招：不外乎动之以情，说之以理；不成功便三十六计走为上策或唇枪舌战、拳脚相向。若能扬弃传统压制对方的观念，学习有效的新方式，你可以施展得更为游刃有余。
●无能为力的问题：我们的责任就是改变嘴角的线条——以微笑、真诚平和的态度，接纳这些问题。纵使有再多不满，也要学习处之泰然，如此才不至于让问题制服了我们。不管一个问题是能直接控制还是无法控制，或是能间接控制，解决问题的第一步都在于改变我们的习惯，改变我们的影响途径，改变我们看问题的方式。而所有这些，都在我们所能控制的影响圈之内。
用心扩大影响圈
一旦化学方程式有某一部分改变，整个化学变化就会改观。同样地，只要我们开始对环境做选择性的回应，影响力也会大增。
我曾经与一家公司合作过，该公司总裁精力旺盛，而且对流行趋势反应极其敏锐。他才华横溢，精明干练，但是管理风格却十分独裁。对部属总是颐指气使，从不给他们独当一面的机会，人人都只是奉命行事的小角色，连主管也不例外。
这种作风几乎使所有主管离心离德，大多一有机会便聚集在走廊上大发牢骚。乍听之下，不但言之成理而且用心良苦，仿佛全心全意为公司着想。只可惜他们光说不练，以上司的缺失作为坐而言却不起而行的借口。
例如一位主管说：“你绝对不会相信。那天我把所有事情都安排好了，他却突然跑来指示一番。就凭一句话，把我这几个月来的努力一笔勾销，我真不知道该如何再做下去。他还有多久才退休?”
有人答道：“他才59岁，你想你还能熬6年吗?”
“不知道，反正公司大概也不会让他这种人退休。”
然而，有一位主管却不愿意向环境低头。他并非不了解顶头上司的缺点，但他的回应不是批评，而是设法弥补这些缺失。上司颐指气使，他就加以缓冲，减轻属下的压力。又设法配合上司的长处，把努力的重点放在能够着力的范围内。
受差遣时，他总尽量多做一步，设身处地体会上司的需要与心意。假定奉命提供资料，他就附上资料分析，并根据分析结果提出建议。
有一天，我以顾问的身分与该公司总裁交谈，他大为夸赞这位主管。以后再开会时，其他主管依然接到各种指示，惟有那位积极主动的主管，受到总裁征询意见，他的影响圈因此而扩大。
这在办公室造成不小的震撼，那些只知抱怨的人又找到了新的攻击目标。对他们而言，惟有推卸责任才能立于不败之地，因为肯负责，就得不怕失败，为了免于为自己的错误负责，有人干脆把责任推得一干二净。这种人以尽量挑剔别人的错误为能事，借此证明“错不在我”。
幸好这位主管对同事的批评不以为意，仍以平常心待之。久而久之，他对同事的影响力也增加了。后来，公司里任何重大决策必经他的参与及认可，总裁也对他极为倚重，并未因他的表现受到威胁。因为他们两人正可取长补短，相辅相成，产生互补的效果。
这位主管并非依靠客观的条件而成功，是正确的抉择造就了他。有许多人与他处境相同，但未必人人都会注重扩大个人的影响圈。
有人误以为“积极主动”就是强出头、富侵略性或无视他人的反应，其实不然。积极主动的人只是反应更为敏锐，更为理智，能够切乎实际并掌握问题的症结所在。
印度圣雄甘地就曾受到印度议员的抨击，因为他不肯跟他们唱高调，谴责大英帝国奴役印度人民。相反地，他亲自下乡，在田间与农民同甘共苦。一点一滴努力经营，脚踏实地建立影响力，最后终于赢得全国人民的支持。他没有任何高官厚禄，以一介平民，凭着热忱、勇气、绝食以及道德说服的力量，终于使英国人投降。3亿人民因而脱离殖民地统治。
想了解一个人的关注圈与影响圈，从言谈中就可看出端倪。描述关注圈的语句多半带有假设性质。
“要是我的房屋贷款付清了，我就了无牵挂。”
“如果我的老板不这么独裁……”
“如果我的丈夫脾气好一点……孩子肯听话……”
“如果我能有更多属于自己的时间……”
“如果我学历更高……”
至于反映影响圈的语句则多半强调自身的修养，例如：
“我可以更有耐心，更明智，更体贴……”




* 第二部分 个人的成功：从依赖倒独立第三章 习惯一：积极主动（四）

　先从自己做起
“外在环境是造成问题的症结所在”，这种想法不但错误，而且正是问题的根源。假使不能反求诸己，一味希望外在环境改变来达成个人的愿望，无异于任凭别人摆布。
正确的做法应该是，先改变个人的行为，做个更充实、更勤奋、更具创意、更能合作
的人，然后再去影响环境。
我最欣赏《旧约》里约瑟夫的故事，约瑟夫便是一个尽其在我的人。他年方17就被亲生手足卖至埃及，任何人处在同样的境遇下，都难免自怨自艾，并对出卖及奴役他的人愤愤不平。但约瑟夫不这么想，他专注于修养自己，不久便成了主人家的总管，掌理所有的产业，备受倚重。
后来他遭到诬陷，冤枉坐牢13年，可是依然不改其志，化怨愤为上进的动力。没有多久，整座监狱便在他的管理之下。到最后，更掌理了整个埃及，成为法老以下、万人之上的大人物。
这种行为的确不是一般人所能企及，可是人人都可以为自己的生命负责，为自己开创有利的环境，而不是坐等好运或恶运的降临。
举例来说，如果某人婚姻出了问题，却只顾揭发对方的过错。这种做法于事无补，只不过强调错不在我，且充其量证明你是个无能的受害者，并不能挽回婚姻。不断的指责不但无法使人改过迁善，反而会令人恼羞成怒。
真正有效的策略应从自身能控制的方面着手，也就是先改进自己的缺失，努力成为模范妻子或丈夫，给予对方无条件的爱与支持。我们当然也盼望能感受这份苦心，进而改善自己的行为。不过对方的反应如何，并非重点所在。
除了好丈夫、好妻子，我们何妨试着做个好学生或好职员。如果遇上实在无能为力的状况，保持乐观进取的心情仍是上上策，不管快乐或不快乐，同样积极主动。有些事物不是人力所能控制，比方说天气，但我们仍可保持内心或外在环境的愉悦气氛。对力不能及之事处之泰然，对能够掌握之事则全力以赴。
不怕犯错只怕不改过
在我们把生命重心由关注圈转移至影响圈前，有两件事值得考虑，那就是自由选择的后果与错误。
每个人固然可以选择自己的行为与反应，但后果仍由自然法则来决定，非人力所能左右。比方一步跨到一列高速行驶的火车的正前方，可以出自个人的选择，但后果却在影响圈之外，非人所能控制。
又比方，有人喜欢玩弄欺诈手段，如果不被揭发，虽不会受到社会的惩罚，但是人格上的污点却无论如何难以抹杀。
因此我们固然享有选择的自由，可是也须承担随之而来的后果。人的一生中，选择错误的机率颇大，无怪乎常会有悔不当初的遗憾，但木已成舟，这些都须列入个人无法控制的关注圈。
对于已难挽回的错误，积极主动的做法不是悔恨不已，而是承认、改正并从中汲取教训，这样才能真正反败为胜。国际商用机器公司(ibm)创始人沃森(t.j.watson)曾说：
失败是成功之母
犯了错却不肯承认，等于错上加错，自欺欺人。为自己造成的错误编织各种理由加以辩解，则形同掩耳盗铃，反而愈描愈黑，受害的还是自己。
因为对我们伤害最深的，不是别人的所作所为，也不是我们自身的缺失，而在于不能正视这些缺失。那就仿佛被毒蛇咬了，却追上前想去抓蛇，反使毒性散得更快，还不如尽快设法吸出毒汁。因此，切勿文过饰非，以免一错再错。
作出承诺，信守诺言
让我们再回到影响圈上，这个范围所环绕的核心就是许诺与实践诺言。对自己对别人有所承诺，并且从不食言，是积极主动精神最崇高的表现，同时也是个人成长的真义。凭借人类天赋的自我意识与良知，我们可以检讨自己，找出犹待改进之处及尚可发挥的潜能。然后运用想象力及独立意志，立定志向，许下承诺、矢志达成。这就是人类成长的过程。
许诺与立志可以使我们掌握人生。有勇气许下诺言，即使是小事一桩，也能激发自尊。因为这表示我们有自制力，并有足够的勇气与实力来承担更多责任。经由不断许诺与实践诺言，终有一天荣誉感会凌驾情绪性反应之上。所以，对自己信守诺言的力量，正是圆满人生不可缺少的基本条件之一。
积极主动：为期三十天的试验
我们虽没有弗兰克尔在死亡集中营的经历，但是日常生活中的种种琐事，已足以使我们培养积极主动的精神，来应付人生无比庞大的压力。不论是面对交通阻塞，或是顾客的无理要求，都需要这种修养。它表现在我们如何集中心力，如何看待问题以及如何遣词用句上。
我建议各位利用30天的时间，身体力行积极主动的精神。在这30天内，全力专注于影响圈的事物，许下承诺并予以兑现。做照亮他人的蜡烛，而非评判对错的法官；以身作则，不要只顾批评；解决问题，不要制造问题。
在婚姻、家庭、工作中，都可以试行这个原则。不必怪罪别人或文过饰非，不怨天，不尤人，但求尽其在我。
对他人的缺失要心存怜悯，别人如何待我，并不重要，要紧的是何以待人。别活在父母、同事或社会的驱使之下，请善用天赋的独立意志，为自己的行为与幸福负责，如此才能享受最大的自由与幸福。
英国辞典编纂家兼作家约翰逊(samuel johnson)曾说：
满意之泉必须源自内心。若不了解人性，而企求不改变自我就可以找到幸福的人，终其一生必定虚掷于无意义的追求之中，且日益增长其企图摆脱的痛苦。
立即行动
一、以一整天时间，倾听自己以及四周人们的用语，注意是否常有“但愿”、“我办不到”或“我不得不”等字眼出现。
二、依据过去经验，设想近期内是否会遭遇一些令人退缩逃避的情况?这种情况在影响范围之内吗?你应该如何本着积极主动的原则加以应对?请在脑海中一一模拟。提醒自己，刺激与回应之间还有余地，并把握自由选择的精神。
三、从工作或日常生活中，找出一个令你备感挫折的问题。判断它属于直接、间接或无法控制的问题，然后在影响圈内寻觅解决的第一步骤，并付诸行动。
四、试行积极主动原则30天，观察影响圈是否有任何变化?




* 第二部分 个人的成功：从依赖倒独立第四章 习惯二：以终为始（一）

　——自我领导的原则
太多人成功之后，反而感到空虚；得到名利之后，却发现牺牲了更可贵的事物。因此，我们务必掌握真正重要的愿景，然后勇往直前坚持到底，使生活充满意义。
身外之物和内在力量相比，便显得微不足道。
——霍姆斯(oliver wendell holmes)，前美国最高法院大法官
阅读本章时，请找个僻静不受干扰的角落，抛开一切杂念，敞开心扉，跟着我作一段心灵之旅。
假设你正在前往殡仪馆的路上，要去参加一位至亲的丧礼。抵达之后，居然发现亲朋友好齐集一堂，是为了向你告别。也许这是三五年，甚至许久之后的事，但姑且假定这时亲族代表、友人、同事或社团伙伴，即将上台追述你的生平。
请认真想一想，你希望听到什么样的评语?你这一生有任何成就、贡献或值得怀念的事吗?你是个称职的丈夫、妻子、父母、子女或亲友吗?你是个令人怀念的同事或伙伴吗?失去了你，对关心你的人会有什么影响?请大致记下你的感受，这有助于了解本章的重点——以终为始(begin with the end in mind)。
“以终为始”的意思
以终为始的习惯可适用于各个不同的生活层面，而最基本的目的还是人生的最终期许。从上述的实验中，可以发掘人们心底最根深蒂固的价值观，间接触及影响圈的核心部分。从此时此刻起，一举一动，一切价值标准，都必须以人生的最终愿景为依归；也就是由个人最重视的期许或价值来决定一切。我们应该时时刻刻把人生使命谨记在心，每一天都要朝此迈进，不敢有丝毫违背。
确认使命也意味着，着手做任何一件事前，先认清方向。这样不但可对目前所处的状况了解得更透彻，在追求目标的过程中，也不致误入岐途，白费工夫。
人生旅途，岔路很多，一不小心就会走冤枉路。许多人拼命埋头苦干，却不知所为何来，到头来仍然发现追求成功的阶梯搭错了墙，为时已晚。因此，人们也许很忙碌，却不见得有意义。
太多人成功之后，反而感到空虚；得到名利之后，却发现牺牲了更可贵的事物。上自达官显贵、富豪巨贾，下至平头小民、凡夫俗子，无人不在追求更多的财富或更高的事业地位与声誉，可是名利往往蒙蔽良知，成功每每须付出昂贵的代价。因此，我们务必掌握真正重要的愿景，然后勇往直前坚持到底，使生活充满意义。
盖棺论定时，你希望获得的评价，才是你心目中真正渴望的目标。从这个角度看，名利、成就等等不免显得微不足道。
有这么一则小故事：丧礼上有人问死者的朋友：“他留下多少遗产?”对方答：“他什么也没带走。”
所有事物都经过两次创造
“以终为始”是以所有事物都经过两次创造的原则为基础的。所有事物都有心智的即第一次的创造(mental /first creation)和实际的即第二次的创造(physical/second creation)。我们做任何事都是先在心中构思，然后付诸实现。正因如此，认定使命才显得如此重要。
以建筑为例，在拿起工具建造之前，必须先有详尽的设计图；而绘出设计图之前，须先在脑海中构思每一细节。有了设计图，然后有施工计划，这样按部就班，才能完成建筑。假使设计稍有缺失，弥补起来，可能就事倍功半。设计蓝图代表愿景，整个建筑过程均以它为准绳，因此宁可事先追求尽善尽美，以免亡羊补牢。
创办企业也是同样道理。要想经营成功，必须先确定产品或服务可达到的营运目标，然后综合资金、研究发展、生产作业、行销、人事、厂房设备等方面资源，朝愿景努力前进。许多企业都败在事先规划不周，以致资金不足，或对市场认识不清。
教养子女也要有使命。想调教出既懂事又有责任感的子女，日常与子女相处时，就得谨守这个使命，不可做出相违背的举动。
先构思而后行动的原则适用范围极广。比方出门旅行，要先决定目的地与路线；上台演讲，应先预备讲稿；做衣服，要先设计款式。明白这个道理，把订定使命看得与行为本身同样重要，影响圈就会日渐扩大。
不过，“使命”不见得都是有意识的产物。有些人自我意识薄弱，只知遵循家庭、社会或环境所赋予的使命前进。这类使命多半出于个人主观好恶，不符合客观原则。它之所以被接受，乃由于有些人依赖心过重，深怕不顺从别人的要求便会失去爱，因而必须靠别人来肯定自我价值。
领导与管理：两次创造的体现
“以终为始”是以自我领导的原则为基础的，但领导(leadership)不同于管理(management)。管理的层次低于领导，我们将在第三个习惯那一章讨论。
领导与管理的差异就好比思想与行为。管理是有效地把事情做好，领导则是确定所做的事是否正确;管理是在成功的阶梯上努力往上爬,领导则指出所爬阶梯是否靠在正确的墙上。
要理解两者间的这一区别不难。想象一下，一群工人在丛林里清除矮灌木。他们是生产者，解决的是实际问题。管理者在他们后面拟定政策，引进技术，确定工作进程和补贴计划。领导者则爬上最高那棵树，巡视全貌，然后大声嚷道：“不是这块丛林!”
而忙碌的生产者和管理者常常怎么回答呢?“别说了，我们正干得有声有色呢。”
作为个人和企业，常常是埋头砍矮灌木，甚至没有意识到要砍的并非那块丛林。
尤其在这日新月异的世界中，有效的领导比以往更显得重要。我们需要方针，需要指引。面对纷扰不已的世事，谁也难以预料未来的发展，这时惟有依靠自己的判断行事。而使命——也就是心中的罗盘——能使你判断正确。
成功——甚至可说求生存的关键——并不完全取决于流了多少血汗，而在于努力是否得法。因此对各行各业而言，领导都重于管理。
企业方面，市场瞬息万变，领导者必须不断密切注视环境的变化，特别是消费者的购买习惯和购买心理，以使企业保持正确的发展方向。
工业方面也是这样。领导者若不注意外部环境的变化，管理技能再好也不能使他们免于破产。缺乏有效领导的高效率管理，有人称之为“就像在泰坦尼克号轮船上拉开躺椅”。无论管理多么成功，都不能弥补领导的失败。不过领导的确是很难的，因为我们常常陷于管理的圈子难以自拔。
记得在西雅图，我曾为一家石油公司主持为期1年的主管进修课程。在最后一堂课上，该公司总裁跟我谈到他个人的上课心得：
史蒂芬，你在第二个月指出领导与管理的不同之后，我立即检讨了自己的角色，结果发现我根本不曾领导。每天忙着应付管理问题，已令人焦头烂额。于是我决定退出管理工作，留给别人去负责，我希望好好为公司确定大方向。
这实在不容易啊!要放手不管眼前急迫的公务，牺牲唾手可得的成就，令我十分痛苦。苦思如何领导公司，如何建立企业文化，如何掌握先机，以及深入分析一些问题，更让我头痛不已。手下的管理人员也适应不良，他们无法再把难题推给我解决，日子比以前难过。
不过我决心坚持到底，因为我认定自己必须做个领导者。现在我已确实做到，整个公司也彷佛脱胎换骨。如今，我们更能因应环境的变化，公司营业额加倍，利润也增长了3倍。我真正发挥了领导力。
在家庭中，为人父母者难免也会落入类似的管理陷阱，只重规矩、效率与控制，忽略了管教的目的、方向与亲情。至于个人的生活，可能就更缺乏主导了。终日汲汲营营，却像无头苍蝇般漫无目标。




* 第二部分 个人的成功：从依赖倒独立第四章 习惯二：以终为始（二）

改写人生剧本
每个人在成长过程中都承袭了许多来自他人的“人生剧本”，也就是价值观与其他方面的制约。要掌握自己的人生，就得改写这些剧本，或者改变既有的成见。
已故埃及总统萨达特(anwar sadt)的自传，讲述了一个最令人振奋的改写人生剧本的
故事。萨达特是在仇恨以色列的环境中长大成人的，一度以仇恨以色列来调动民众的意志。这个剧本有很强的独立性和浓厚的民族主义，但它也是愚蠢的，忽视了当今世界相互依存的事实。萨达特也知道这一点。
于是，萨达特决心改写自己的人生剧本。因为参与推翻法鲁克国王，他被关进了监牢。在那里，他学会了从旁观者的角度来观照自己，反躬自省，改造自我。
当终于成为埃及总统时，他改变了自己对以色列的态度。他访问了耶路撒冷的以色列国会，开启世界历史上最勇于突破先例的和平运动，而这一大胆的行为最终产生了戴维营协议。
萨达特利用他的独立意识、想象力和良知进行自我领导，改写了自己的“人生剧本”，影响了数百万人的生活。
当我们因袭的“人生剧本”有违我们的生活目标时，我们能够利用想象力和创造力书写新的剧本，它将更为符合我们内在的价值观。
假设我是一位严厉的父亲，每当子女做出令我反感的行为，立刻会火冒三丈，把教训子女的真正目的抛诸脑后；拿出做父亲的权威，迫使子女屈服。在眼前的冲突中我固然得胜，亲子关系却出现裂痕。孩子表面顺从，但口服心不服，受到压抑的情绪，日后会以更糟的形式表现出来。
让我们再回到本章一开始提到的实验。在我的丧礼上，子女齐集一堂，表达孝思。我期望他们个个都很有教养，满怀对父亲的爱，而不是与父亲起冲突的创痛。但愿他们心中所充满的是往日美好的回忆，记得老爸曾与他们同甘共苦过。我所以有这些期望，因为我重视子女、爱护子女，以做他们的父亲为傲。
但在实际生活中，却不一定时时牢记这些，表面对孩子的态度并不能真正反映我心底的情感，因为繁复的事务扰乱了我的方向。
好在这个缺点并非无法克服。我可以排除外来不合宜的价值观与其他制约，由此建立自己的价值观与方向，和对生命的负责，来改写人生剧本，让自己的人生真正符合自己的意愿。
于是乎，日常生活一旦出现困难或挑战，我就可以根据个人价值观决定因应之道。
个人使命宣言
确立人生愿景最有效的方法，就是认定自己的人生哲学或基本信念，然后写一份个人使命宣言(mission statement)。宣言中应包括自我期许与基本价值观，内容往往因人而异。举例来说，我有一位朋友的个人信条如下：
●家庭第一。
●借重宗教的力量。
●决不放弃诚信原则。
●未听取正反双方意见，不妄下断语。
●征求他人意见。
●保护不在场的人。
●诚恳但立场坚定。
●每年掌握一种新技能。
●今天计划明天的工作。
●抓紧等待的时间。
●态度积极，保持幽默。
●生活与工作有条不紊。
●别怕犯错——怕的是不能记取教训。
●协助属下成功。
●多请教别人。
●珍惜现在。
对于一位希望兼顾家庭与事业的妇女，她的使命感便不尽相同：
●我兼顾事业与家庭，因为两者对我都很重要。
●家庭是平安、祥和与幸福之地，我要以智慧来创造整洁温馨的环境，并教导子女有爱心、进取与充满欢愉，培养他们发挥长才。
●珍惜民主社会的权利与自由，善尽社会一分子的责任。
●积极主动追求人生目标。
●避免养成恶习，不断改进自己。
●金钱是人的奴隶而非主人。我要追求经济独立，量入为出，并定期储蓄或投资一部分收入。
●我愿贡献金钱与才智，改善他人的生活。
个人使命宣言是行为处事的根本大法，好比一国的宪法。不管世事如何多变，环境多么艰困，它依然不为所动。
凡是心中秉持恒久不变真理的人，才能屹立于动荡的环境中。因为一个人的应变能力取决于他对自我、目标以及价值观的不变信念。确立个人使命之后，我们就不必借助成见或偏见来面对变局，如此一来，便能保持安全感。
世界变动太快，许多人难以适应，因而选择了退缩与放弃，其实人生不必如此消极。弗兰克尔在纳粹死亡集中营中，不仅觉悟到积极主动的真谛，还体会到生命意义的重要。后来他提倡一种“标记疗法”(logotherapy)，基本理论便是：许多心理与情绪疾病事实上只是失落感、空虚感在作祟。标记疗法可以协助病人找回生命的意义与使命，以祛除内心的空虚。
直指核心
想要确立个人使命，必须从影响圈的核心开始，因为这是一切思想观念的根本，也是安全感、人生方向、智慧与力量的泉源。
“安全感”代表价值观、认同、自尊自重与归属感。“人生方向”是生命的追求方向以及决断所依据的原则。“智慧”是对事物的认知、理解与判断能力。“力量”则指采取行动、达成目标的能耐。
这四者相辅相成，安全感与明确的方向可以带来智慧，智慧则能激发行动。若四者十分健全且均衡发展，便能产生高尚的人格、平和的个性与完美正直的个体。
这四方面的成熟度，同样可以用依赖——独立——互赖三阶段来衡量。处于最底层依赖阶段的人，则极度缺乏安全感，他们凭借社会价值订定方向，对外界认识不清，缺乏行动勇气或受人摆布。若是位在最高的互赖层次，则能肯定自我，处世泰然；他们确知自己的努力方向，深谙待人接物的艺术，积极主动，不假外求。




* 第二部分 个人的成功：从依赖倒独立第四章 习惯二：以终为始（三）

小,说t,xt,天,堂
你的生活重心是什么?
人人都有生活重心，即使不一定意识得到，但它依旧存在。一般而言，生活重心可以分为以下数种：
一、以配偶为重心：婚姻可说是最亲密持久、最美好可贵的人际关系，因此以丈夫或
妻子为生活重心，再自然不过了。
但根据我多年来担任婚姻顾问的经验，以配偶为重心的婚姻关系，多半发生情感过度依赖的问题。太过于重视婚姻，会使人的情感异常脆弱，经不起些许打击，甚至无法面对如新生儿降临或经济窘迫等变化。
婚姻会带来更多的责任与压力，一般人通常根据以往所受的教养来应付。然而两个背景不同的人，思想必定有差异，于是乎理财、教养子女、婆家或岳家的问题，都会引起争执。若再加上其中一方情感难以独立，这桩婚姻便岌岌可危。
如果我们一方面在情感上依赖对方，一方面又与对方有所突击，就极易陷入爱恨交织、进退失据的矛盾中。为了保护自己，便更加退缩及排斥对方。于是，冷嘲热讽代替了真实的感受，感情用事的结果是失去了方向、智慧与力量。纵使表面似乎保住了安全感，实则不然。
二、以家庭为重心：以家庭为重的现象也十分普遍，而且似乎理所当然。家的确带来爱与被爱、同甘共苦以及归属的感觉，但过分重视家庭，反而有害家庭生活。
太仰赖家庭提供安全感及价值感，太重视家族传统与名誉，通常无法接受任何可能影响这些传统与声誉的改变。以家庭为重的父母，不能为子女的真正幸福着想，他们的爱往往是有条件的。结果若非导致子女更为依赖，就是变得叛逆。
三、以金钱为重心：谁也无法否认钱的重要，经济上的安全感也是人类最基本的需求之一，因此追求财富无可厚非。但若惟利是图，往往得不偿失。
如果一个人的安全感与价值观完全建立在金钱的多寡上，势必寝食难安，因为影响财富的变数太多，任何一个闪失都令人承受不起。但是钱却不能带来智慧或指引生命的方向，只能提供有限的力量与安全感。
有人为了逐利，不惜将家庭及其他重要事物摆在一边，而且以为别人都认同这种做法。我认识一位可敬的父亲，准备带子女出游时，忽然接到公司要求加班的电话，但是他回绝了，因为“工作还会再来，童年却只有一次”。这一幕深深印在子女脑海里，永志不忘。
四、以工作为重心：只知埋头苦干的“工作狂”，即使牺牲健康、家庭与人际关系也在所不惜。他的生命价值只在于他是个医生、作家或演员……一旦无法工作，便失去所有的生活意义。
五、以名利为重心：占有欲极强的人，想据为己有的不仅是有形的物质，如汽车、洋房、华服等等；无形的名誉、荣耀与社会地位也决不放过。
我们都知道名利不可依靠，因为它们随时可以毁于一旦，一个人若必须靠名利与物质来肯定自我，必定时时处于惶惶不安的状态中，深恐身外之物转眼成空。当他们面对条件比自己更好的人，便相形见拙；见到略逊一筹的人，又趾高气扬。如此一来，自我价值起伏不定，永无宁日。难怪有人在股票大跌或政坛失意后，会选择自戕一途。
六、以享乐为重心：在当前崇尚速成的世界里，享乐之风盛行，不足为奇。电视与电影喂大了观众的胃口，然而银幕上的浮华生活，骨子里并不如表面上看起来那般美好光鲜。
真正的快乐可使人身心舒畅，短暂的刺激却丝毫不能给人持久的快乐与满足。贪图享乐的人很快便会对既有的刺激感到乏味，然后就得追求更刺激的“快感”。
休太长的假，看太多的电影、电视，打太多的电子游戏，长久无所事事，都只是浪费生命。无益于增长智慧，激发潜能，增进安全感或指引人生，只不过制造更多的空虚而已。
马格里奇(malcolm muggeridge)在《二十世纪的圣经》(a twentieth-century testimony)中写到：
回忆旧日生活，对我触动最大的是，当时看上去十分重要、十分吸引人的事，现在看来微不足道，荒唐可笑。比方，各种各样的成功、名气和赞誉；得到金钱或吸引女人后的欢愉；旅行，像撒旦那样上下沉浮，经历着浮华世界里的一切。
回想起来，所有这些满足都已虚无缥缈。
七、以敌人或朋友为重心：青少年尤其容易陷于以朋友为重的情结中。为了被同行团体接纳，他们愿付出一切代价；对团体的所有价值观，也都照单全收，因而极为依赖团体。
以朋友为重心，可能只针对一个人而言，情况类似以配偶为重心。也就是完全为对方而活，导致的不良后果则大同小异。
以敌人为重心，似乎少有所闻，其实这种现象相当普遍，只是不易被察觉罢了。当某人觉得遭到重要人物(如主管)的不公平待遇后，很容易耿耿于怀，所作所为都为了要反抗待他不公的人。这就是以敌人为生活重心。
我有一位朋友在大学教书，由于与行政主管交恶，便终日以对方为假想敌，几乎到了走火入魔的地步。家庭生活与工作都大受影响，最后逼得他不得不选择离开。
于是我问他：“如果不是那位仁兄，你宁愿继续留下来，对不对?”
他回答：“是的，可是只要他在一天，我便永远不得安宁，只好另谋高就。”
“你为什么让他成了你生活的重心?”
朋友被这个问题震住了，一口否认。但我分析道理，说明他咎由自取。朋友起先只承认行政主管的确对他影响很大，但认为错在对方。最后经过我不断开导，才承认自己也应负一部分责任。
有些离婚的人，仍念念不忘对前夫前妻的深仇大恨；有些已成年的子女，仍为父母当年的忽视、偏心或责骂而愤愤不平，这也都是以敌人为重心。
以朋友或敌人为重心的人没有安全感。他们的价值观变化无常，受制于他人的情绪和行为，时时揣摩如何反击。这样的个人是没有力量的，时时被别人牵着鼻子走。
八、以宗教为重心：有人对宗教活动极为热衷，甚或没有宗教信仰，言行却更合乎宗教劝人向善的宗旨。
九、以自我为重心：时下最常见的恐怕就是以自我为中心的人，他们最明显的特征就是自私自利。然而，市面上盛行的个人成功术，无一不以个人为中心，标榜只索取不付出。殊不知狭隘的自我中心观，会使人缺乏安全感和人生方向，而且也不会有智慧及行动力量。惟有为造福人群、无私奉献，而追求自我成长，才能在这四方面有所长进。
一般而言，我们都是以上某几种形态的混合体，随外在情势的不同而有所调整。此一时可能以朋友为重心，彼一时或许又变为以配偶为重心。
生活重心如此摇摆不定，情绪上难免起起落落，一会儿意兴风发，一会儿颓唐沮丧；一会儿斗志昂扬，一会儿又落魄消沉。
所以，最理想的状况还是建立明确固定的生活重心，使人生更平顺、更和谐。




* 第二部分 个人的成功：从依赖倒独立第四章 习惯二：以终为始（四）(1)

以原则为重心
所谓正确的生活重心，也就是以原则为依归。
原则是恒久不变、历久弥新的，不像其他重心依靠的是善变的人或物。所以原则值得信赖，更可以增加安全感。同时它是理智而非感情用事的，能带给你“虽千万人，吾往矣”
的信心。
配偶也许会与你离婚，再亲密的朋友也可能离你而去。但原则助人披荆斩棘，克服人生，也教人处顺境而不迷失方向。原则使人冷静发挥智慧，正确判断；它使我们不为外力所动，勇往直前。
以原则为生活重心，可说是统合了其他重心而自成一格。
我们且举实例来说，生活重心不同，产生的观念便互异。(参看附录一)
现在假定你已买好票，准备晚上与妻子(或丈夫)一同去欣赏音乐会，对方兴奋不已，充满期待。可是突然老板要你晚上加班，因为第二天有一个重要会议。
●对以家庭或配偶为重的人而言，当然是优先考虑配偶的感受。那么你很可能委婉拒绝老板，以免令配偶大失所望。即使为了保住工作而勉强留下来加班，心里也一定十分不情愿，一方面还得设法平息配偶的失望与不满。
●至于金钱至上的人，则重视加班费，或考虑到加班能使老板在调薪时另眼相看。你会理直气壮地告诉配偶你要加班，也会理所当然认为对方应该谅解，因为经济的需求超过一切。
●对工作狂来说，加班正中下怀。因为既可增加经验，又有更多表现的机会，有利于晋升。所以不论是否需要，仍然自动延长加班时间，且自以为配偶一定以此为荣，对爽约不会小题大作。
●贪嗜名利的人，则为加班费所增加的购买力而兴奋，或认为加班对个人形象很有帮助，可借此赢得为工作而牺牲奉献的美誉。
●重视享受的人，即使配偶并不介意他加班，仍会撇下工作去赴音乐会，因为他觉得该慰劳自己一下。
●看重朋友的人，则根据是否有朋友同行，或其他工作伙伴是否也留下来加班而做决定。
●以敌人为念的人，会乐于留下来，因为这可能是一个打击对手的良机。在对方悠哉游哉的时候拼命工作，正足以证明你对公司的贡献更胜一筹。
●热衷宗教的人则会衡量，共同加班的人是否信仰同一宗教，或音乐会演奏的是否为宗教音乐等等，来决定取舍。
●自我中心的人只关心，加班或赴音乐会，哪一样对个人的好处较大。
●但注重原则的人会保持冷静客观的态度，不受情绪或其他因素干扰。然后从整体的角度——包括工作需要、家庭需要、其他相关因素，以及不同的决定可能造成的结果——加以考虑，经过深思熟虑，才做出正确的抉择。
不论最后选择赴音乐会或是加班，都不足为奇，因为拥有其他生活重心的人也是两者择一，只不过基本上拥有原则的人所做的抉择会有以下几个特征：
第一，这是主动而非被动的决定。
第二，这是经过通盘考虑所得的结论，不是一时冲动。
第三，根据原则所做的决定，能提高自我的价值。为了报复他人而决定加班，与真心为企业福祉着想而加班，结果虽相同，意义却大相径庭。
此外，若平时已与老板及妻子建立良好的互赖关系，此时不难向他们解释如此决定的缘由，而且也会获得体谅。使你可以心安理得，无所牵挂。
总而言之，以原则为生活重心的人，见解不同凡响，思想行为也自成一格。由于拥有坚实的内在，其所获得的高度安全感、人生方向、智慧与力量，使其能享有积极主动而充实的一生。




* 第二部分 个人的成功：从依赖倒独立第四章 习惯二：以终为始（四）(2)

　制订和使用个人使用宣言
弗兰克尔说：“我们是发现而不是发明自己的人生使命。”这么说的确再恰当不过了。凡是人都具备良知与理智，足以发现个人的特长与使命。弗兰克尔说得好：
每个人都有特殊的职责或使命，他人无法越俎代庖。生命只有一次，所以实现人生目标的机会也仅止于一次……追根究底，其实不是你询问生命的意义何在，而是生命正提出质疑，要求你回答存在的意义为何。换言之，人必须对自己的生命负责。
再以计算机作比喻。前一章曾提到，你是自己的人生程序设计员。本章则要求你写出属于个人的程序，也就是个人使命宣言。
这件工作并非一蹴而就，而是必须经过深思熟虑，几经删改，才可以定案。其间可能耗费数周，甚至数月的时间，而且即使定案，仍须不时修正。因为随着物换星移，人的想法也会改变。
无论如何，使命宣言是个人的根本大法、基本人生观，也是衡量一切利弊得失的基准。撰写使命宣言的过程，重要性不亚于最后的结论。为了形诸文字，你势必要彻底检讨自己真正的理想——最珍贵的人生目标。随着思想日益清明、貌随心转，你会有面目一新的感觉。
善用你的全部头脑
根据研究结果显示，人的大脑可分为左右两部分，左脑主司逻辑思考与语言能力，右脑职掌创造力与直觉。左脑处理文字，右脑擅长图像；左脑重局部与分析，右脑重整体与整合。
最理想的状况是左右脑的均衡发展，但实际上，每个人或多或少都是某半边大脑较发达。面对外界刺激时，也倾向于用较发达的一边做反应。用美国心理学家马斯洛(abraham maslow)的话说：“善用头的人往往认为所有东西都是钉子。”这也是影响前面实验中的少妇/老妇不同看法的另一因素。用右脑的和用左脑的人看事物往往是不同的。
基本上，目前是个崇尚左脑的世界，语言文字、逻辑推理等被奉为重要的才能，而感官直觉、艺术创造总是居于从属地位，无怪乎一般人多不习惯于发挥右脑的功能。
依据这个理论，前文所提到的构思与实行两阶段，前者须借重右脑的创造力，以跨越时空障碍，做全盘考虑与规划。
有时，人会因突发事件，在一瞬间由左脑为主的思想型态，变成以右脑为主。比方说，突然失去亲人、罹患重病、经济陷入窘境时，就会扪心自问：“到底什么才真正重要?我究竟在追求什么?”但积极主动的人，不待外界刺激就能设法主动转变思考模式。
本章一开始，想象参加自己的丧礼，就是一种扭转思维模式的方法。现在请试着写下理想的一生，愈详细愈好。你不妨和配偶在脑海里描绘结婚20周年以及50周年的情景，两人共同计划未来，讨论理想的婚姻关系什么样。你也可设想退休后的情形，希望有怎样的成就与贡献，退休后又有什么计划。
尽量敞开心灵去想，掌握每个细节，并且投入所有的情感与感觉。
我曾经在大学课堂上做过类似实验，要求学生假设自己只剩一学期的生命，该如何好好把握这最后的学习机会。经过一番省思，学生有不少新发现。于是我要求他们以1周的时间，从这个角度来检讨自己，并逐日记下心得。
结果，有人开始给父母写信，表达对父母的爱；有人则与感情不睦的手足和好，所有这一切都发人深省。
运用想象力来挖掘内心深处真正的感觉，是人人都会技巧，只是每个人的体会不同。凡是肯用心去追根究底的人，必然对生命充满虔敬，对人生诸事都能从大处、远处着眼。
心灵演练：想象与确认
在驾驭想象力的同时，我们应进行心灵演练(visualization)以获得确认(affirmation)，使实际生活更符合理想的人生目标。
心灵演练包括：针对个人、积极、立即行动、富有感情等要素，还必须是可预见的。例如：“发现子女行为不当时，我能以智慧、爱心、坚定的立场与自制力(积极的表现)加以应对(即立即行动)，我(个人)内心深感欣慰(富有感情)。”
你不妨每天抽出几分钟，在身心完全放松的情况下，模拟各种可能出现的状况以及适当的反应，脑海中的影像愈清晰愈好。你的行为在潜移默化中会逐渐转变，最后终于能完全控制情绪，冷静应变。
这个方法我曾应用在我儿子西恩身上。他在高中时是美式足球队的四分卫，当时我开始教他如何放松自己，运用想象力来加强临场应战能力。
有一次，他抱怨常常会莫名其妙地紧张。细谈之下，我发现他脑海中浮现的总是千钧一发的时刻，无怪乎精神紧张。于是我教他利用心灵演练，在压力最大时，保持心平气和。
加菲尔德(charls garfield)博士曾对竞技运动和企业方面的佼佼者有过广泛研究，他的一个重要发现是，世上有许多顶尖人物——包括一流运动员，都长于这种心理准备功夫。所以，在参与重要谈判、上台表演或面对困难冲突以前，不妨参照以上范例多加演练。直到胸有成竹，产生兵来将挡、水来土掩的勇气。
许多古老的宗教也采用同样的方式，只是名称略有出入，如静坐、祈祷、各种祭典、献礼等等，都诉诸良知与想象力。
心灵演练的威力无穷，但必须以品德及原则为基础，否则就会误用滥用。若是用于追逐功利，心灵演练虽然可以助人达到目的，却无法带来内心的安宁。




* 第二部分 个人的成功：从依赖倒独立第四章 习惯二：以终为始（五）(1)

确定角色和目标
人生在世，扮演着各式各样的角色：为人父母、妻子、丈夫、主管、职员、亲友，同时也担负不同的责任。因此，在追求圆满人生的过程中，如何兼顾全局，就成了最大的考验。顾此失彼，在所难免；因小失大，更是司空见惯。
考虑到这一点，在撰写使命宣言时，不妨分开不同的角色领域，一一订立目标。在事业上，你可能扮演业务员、管理人员、产品开发人员的角色。在生活中，你或许是妻子、母亲、丈夫、邻居、朋友。其余政治、信仰方面的种种角色，也都各有不同的期待与价值标准。
以下是一位企业主管的人生目标：
我的使命是正正当当地生活，并且对社会有所贡献。
为达成这一使命：
我有慈悲心——拥抱人群，不分贵贱，热爱每一个人。
我愿牺牲——为人生使命奉献时间、精力、金钱及才华。
我以身作则——以身教教导人为万物之灵长，可以克服一切困难。
我有影响力——所作所为会使他人的生活改善。
以下是达成人生使命过程中的各种角色的扮演状况：
丈夫——老伴是我这一生中最重要的人，我们同甘共苦，携手前行。
父亲——我要帮助子女体验乐趣无穷的人生。
儿子/兄弟——我不忘父母、手足的亲情，随时对他们出手相援。
基督徒——我信守对上帝的誓言，并为他的子民服务。
邻居——我要发挥基督之爱来对待他人。
鼓舞人心者——我是激发群体优异表现的媒介。
学者——我每日求取新知。
一旦确定主要的人生角色，你就能清楚地掌握全局。接着，还要订定每个角色的长期目标，这些目标必须反映你真正的价值观、独特的才干与使命感。
角色与目标能赋予人生完整的架构与方向，假定你还缺少这么一份个人使命宣言，现在正是开始撰写的最佳时机。至于近期的目标，将于下一章再讨论。
家庭使命宣言
除了个人以外，家庭也可凭借共同的目标来促进和谐。有不少家庭处理人际关系没有原则，全凭一时兴起及个人好恶，缺乏长久之计。因此，每当压力升高，家人便乱了方寸，出现冷言相向、冷嘲热讽或沉默抗议等不良反应。在这种环境下长大的孩子，必然以为解决问题的方法只有冲突或逃避。
其实，每个家庭都有共同的价值观及理念，作为生活的重心，撰写家庭使命宣言正可加以凸显这个生活重心。家庭使命宣言有如宪法，可当作衡量一切利弊得失的标准，以及重大决定的依据，并使全家人团结在共同的目标下。
撰写家庭使命宣言，同样也是过程与成果并重。由全家共同讨论、拟订及定时修正，更能促进沟通，强化向心力与坚定付诸实现的决心。面临危机或困难时，家庭使命宣言可帮助一家人认清方向，共渡难关。
我家墙上便贴有这么一份使命宣言，记载着全家共同定下的原则，包括互助合作、维持整洁、用言语表达感情、培养专长与欣赏家人的才华等等。每年6月与9月，即学年结束与开始之际，我们都会修订，使之更符合实际状况。




* 第二部分 个人的成功：从依赖倒独立第四章 习惯二：以终为始（五）(2)

小.说。t。xt-天/堂
　组织使命宣言
身为企业顾问，主要任务之一，就是协助企业订立可行的长期目标。这类目标必须由所有成员共同拟定，不可取决于少数高高在上的决策者。
每次到国际商用机器公司(ibm)参观员工训练，我都感触良多。ibm主管总不忘向员工耳提面命该公司的三大原则：个人尊严、卓越与服务。
不论世事如何变化，ibm始终信守这三大原则。而且从上到下，人人奉行不渝，就彷佛水的渗透，无所不在。
记得有一次在纽约训练一批ibm员工，班上人数不多，约20人左右。不幸有位来自加州的学员生病，需要特殊治疗。主办训练的ibm人员，原想安排他们就近住院治疗，但为体谅他妻子的心情，便决定送他回家由家庭医生诊治。为了争取时间，无法等待普通班机，公司居然租直升机送他到机场。还包专机，千里迢迢送回加州。
虽然确实的金额不详，但我相信这笔开销不下数千美元。为了秉持个人尊严的原则，ibm宁愿付出这些代价。这对在场的每个人都是最好的教育机会，我也留下了深刻的印象。
另一家连锁旅馆的服务态度，同样令我难以忘怀。那决不是表面功夫，而是全体员工自动自发的表现。
当时我因为主持一项研讨会而住进这家旅馆，由于到得太迟，已无餐点可用。前台人员却主动表示，可以到厨房跑一趟，还殷勤询问：“您要不要先看看会议厅?有没有需要我效劳的地方?您还需要其他东西吗?”当时并没有主管在旁边监督。
第二天研讨会开始，我发现所带的色笔不够，便趁空抓住一名服务员，说明困难。
他瞥了我的名片一眼，然后说：“科威先生，我会解决这个问题的。”
他并没有推脱：“叫我到哪儿去找。”或者：“请你问前台。”他一口承担下来，而且表现出为服务深感荣幸的样子。
事后我又观察到不少员工热心服务的实例，这引起了我的好奇心。为什么这个机构能够彻底奉行顾客至上的原则?我访问了各阶层的员工，发现个个士气高昂，态度积极。于是我请教经理秘诀何在。
他取出整个连锁网的共同使命宣言给我看。
我看过以后说：“这的确不同凡响，但很多公司都订有崇高的目标，却不见得能够实践。”这位经理接着又取出专属于这家旅馆的经营目标，是另一份组织宣言：“这是根据总公司的大原则，并针对我们的特殊需要而拟定的。”
“是谁订立的呢?”
“全体员工。”
“清洁工、女侍、文书职员都包括在内?”
“是的。”
这两份宣言代表整个旅馆的中心思想，无怪乎营运成绩斐然。它既有助于员工与顾客、员工与员工之间的关系，也左右了主管的领导方式，甚至影响到人员的招募、训练与薪资福利。
后来，我住过同一连锁网的另一家旅馆，那里的服务水准也毫不逊色。当我问服务员饮水机在哪里时，他亲自领我到饮水机前。
更令人印象深刻的是，那里的职员居然向主管主动承认错误。当我住进旅馆的第二天，客房部经理打电话来为服务不周表示道歉，并招待我们用早餐。只为了一位服务员送饮料到我们的房间时，迟了15分钟，虽然我并不在乎。这名服务员若不主动报告，没有人会知道。但是他承认错误，使顾客获得更好的服务。
惟有参与，才有认同
许多组织——包括家庭，都有一个最根本的问题，就是成员并不认同集体的大目标，反而常有个人目标与企业目标背道而驰的情形。另一方面，不少企业的薪津制度与其标榜的理想不相符合。
所以在检讨企业的使命宣言时，我一定调查有多少人参与制定，又有多少人知道它的存在，并且真正认同与奉行。惟有参与，才有认同，这个原则值得强调再强调。
小孩子或新进人员很容易接受父母与企业加诸其上的观念，但长大成人或熟悉环境后，就会产生独立意志，要求参与。假使没有全体成员参与，实在难以激发向心力与热忱。这便是为什么我要一再强调，组织应开诚布公，不厌其烦地广征意见，订立全体共有的使命宣言。
立即行动
一、记下你做本章开头那个心灵实验时的想法，将心得列表整理。
二、确立重要的人生角色，并检讨你对目前所扮演的角色是否满意。
三、每天抽空撰写个人使命宣言，并搜集可用的资料。
四、阅读附录一，你的行为符合其中哪种类型?你是否满意?
五、设想近期内会面临的某种状况，并写下你希望获得的结果与应该采取的步骤。
六、与家人或同事分享本章的精华，并建议大家一同拟定家庭或企业的共同目标。




* 第二部分 个人的成功：从依赖倒独立第五章 习惯三：要事第一（上）(1)

——自我管理的原则
有效管理是掌握重点式的管理，它把最重要的事放在第一位。由领导决定什么是重点后，再靠自制力来掌握重点，时刻把它们放在第一位，以免被感觉、情绪或冲动所左右。
重要之事决不可受芝麻绿豆小事牵绊。
——歌德(goethe)，德国诗人
请先用几分钟的时间简短回答以下两个问题，这对你培养习惯三将是非常重要的。
●有哪件事，你经常做的话会对你个人的生活产生重大的正面影响，可是却迟迟没有去做?
●在事业上有哪件事会产生类似的效果?
我们过一会儿再讨论这两个问题的答案。现在先步入正题——习惯三：要事第一(put first things first)。这个习惯落实了前两个习惯，在日常生活中，随时随地展现出积极主动与确立目标的功夫。
要事第一是通过独立意志的发挥，建立以原则为重心的处事态度，进而达到有效的自我管理。
前面已强调，管理不同于领导。领导是力道十足的右脑活动，有某种哲学为基础而更近乎艺术，讲究的是关于人生目标、使命等大道理。
不过大方向确定之后，应落实于日常生活，此时管理就显得异常重要。管理是分析、推理、规划、应用等左脑所擅长的活动。我个人对此的格言是：左脑管理，右脑领导。
独立意志：有效管理的先决条件
除了自我意识、良知与想象力之外，真正使有效管理成为可能的是人类的第四个天赋——独立意志。有了它，人类得以做各种抉择，并依据这些抉择行事。因此独立意志是有效自我管理的先决条件。
独立意志具有不可思议的力量，屡屡创造奇迹。不过对一般人而言，如何在日常每个决定中发挥独立意志，才是最重要的课题。
独立意志的强弱，可由自制力——是否言出必行、言行一致——见出端倪，因此自制力是一项极为重要的品格。
有效管理是掌握重点式的管理，它把最重要的事放在第一位。由领导决定什么是重点后，再靠自制力来掌握重点，时刻把它们放在第一位，以免被感觉、情绪或冲动所左右。
自制力一词来源于信徒，他们信奉一种哲学，一套原则或价值观，信奉一个压倒一切的目标或代表这个目标的人。
换句话说，自制力来自内部，那是独立意志的作用。你是你自己内在价值观的信徒，具有让感情、冲动和情绪服从于价值观的意志和品德。
葛雷(e.m.gray)所著《成功的共通性》(the common denominator of success)一文，深获我心。终其一生，葛雷都在寻找所有成功者共通的秘诀。最后他发现，勤奋、运气或灵活的手腕虽很重要，却非关键，惟有掌握重点才是成功的不二法门。他说：
成功者能为失败者所不能为，纵使并非心甘情愿，但为了理想与目标，仍可以凭毅力克服心理障碍。
强烈的进取心可使人勉为其难，排除不急之务的牵绊。
四代时间管理理论的演进
习惯三触及许多人生管理与时间管理的问题，我研究多年的心得是：如何分辨轻重缓急与培养组织能力，是时间管理的精髓所在。
有关时间管理的研究已有相当历史。犹如人类社会从农业革命演进到工业革命，再到资讯革命，时间管理理论也可分为四代。
●第一代理论着重利用便条与备忘录，在忙碌中调配时间与精力。
●第二代理论强调行事历与日程表，反映出时间管理已注意到规划未来的重要。
●第三代是目前正流行、讲求优先顺序的观念。也就是依据轻重缓急设定短、中、长期目标，再逐日订定实现目标的计划，将有限的时间、精力加以分配，争取最高的效率。
这种做法有它可取的地方。但也有人发现，过分强调效率，把时间崩得死死的，反而会产生反效果，使人失去增进感情、满足个人需要以及享受意外之喜的机会。于是许多人放弃这种过于死板拘束的时间管理法，回复到前两代的做法，以维护生活的品质。
现在，又有第四代理论出现。与以往截然不同之处在于，它根本否定“时间管理”这个名词，主张关键不在于时间管理，而在于个人管理。与其着重于时间与事务的安排，不如把重心放在维持产出与产能的平衡上。




* 第二部分 个人的成功：从依赖倒独立第五章 习惯三：要事第一（上）(2)

——自我管理的原则
有效管理是掌握重点式的管理，它把最重要的事放在第一位。由领导决定什么是重点后，再靠自制力来掌握重点，时刻把它们放在第一位，以免被感觉、情绪或冲动所左右。
重要之事决不可受芝麻绿豆小事牵绊。
——歌德(goethe)，德国诗人
请先用几分钟的时间简短回答以下两个问题，这对你培养习惯三将是非常重要的。
●有哪件事，你经常做的话会对你个人的生活产生重大的正面影响，可是却迟迟没有去做?
●在事业上有哪件事会产生类似的效果?
我们过一会儿再讨论这两个问题的答案。现在先步入正题——习惯三：要事第一(put first things first)。这个习惯落实了前两个习惯，在日常生活中，随时随地展现出积极主动与确立目标的功夫。
要事第一是通过独立意志的发挥，建立以原则为重心的处事态度，进而达到有效的自我管理。
前面已强调，管理不同于领导。领导是力道十足的右脑活动，有某种哲学为基础而更近乎艺术，讲究的是关于人生目标、使命等大道理。
不过大方向确定之后，应落实于日常生活，此时管理就显得异常重要。管理是分析、推理、规划、应用等左脑所擅长的活动。我个人对此的格言是：左脑管理，右脑领导。
独立意志：有效管理的先决条件
除了自我意识、良知与想象力之外，真正使有效管理成为可能的是人类的第四个天赋——独立意志。有了它，人类得以做各种抉择，并依据这些抉择行事。因此独立意志是有效自我管理的先决条件。
独立意志具有不可思议的力量，屡屡创造奇迹。不过对一般人而言，如何在日常每个决定中发挥独立意志，才是最重要的课题。
独立意志的强弱，可由自制力——是否言出必行、言行一致——见出端倪，因此自制力是一项极为重要的品格。
有效管理是掌握重点式的管理，它把最重要的事放在第一位。由领导决定什么是重点后，再靠自制力来掌握重点，时刻把它们放在第一位，以免被感觉、情绪或冲动所左右。
自制力一词来源于信徒，他们信奉一种哲学，一套原则或价值观，信奉一个压倒一切的目标或代表这个目标的人。
换句话说，自制力来自内部，那是独立意志的作用。你是你自己内在价值观的信徒，具有让感情、冲动和情绪服从于价值观的意志和品德。
葛雷(e.m.gray)所著《成功的共通性》(the common denominator of success)一文，深获我心。终其一生，葛雷都在寻找所有成功者共通的秘诀。最后他发现，勤奋、运气或灵活的手腕虽很重要，却非关键，惟有掌握重点才是成功的不二法门。他说：
成功者能为失败者所不能为，纵使并非心甘情愿，但为了理想与目标，仍可以凭毅力克服心理障碍。
强烈的进取心可使人勉为其难，排除不急之务的牵绊。
四代时间管理理论的演进
习惯三触及许多人生管理与时间管理的问题，我研究多年的心得是：如何分辨轻重缓急与培养组织能力，是时间管理的精髓所在。
有关时间管理的研究已有相当历史。犹如人类社会从农业革命演进到工业革命，再到资讯革命，时间管理理论也可分为四代。
●第一代理论着重利用便条与备忘录，在忙碌中调配时间与精力。
●第二代理论强调行事历与日程表，反映出时间管理已注意到规划未来的重要。
●第三代是目前正流行、讲求优先顺序的观念。也就是依据轻重缓急设定短、中、长期目标，再逐日订定实现目标的计划，将有限的时间、精力加以分配，争取最高的效率。
这种做法有它可取的地方。但也有人发现，过分强调效率，把时间崩得死死的，反而会产生反效果，使人失去增进感情、满足个人需要以及享受意外之喜的机会。于是许多人放弃这种过于死板拘束的时间管理法，回复到前两代的做法，以维护生活的品质。
现在，又有第四代理论出现。与以往截然不同之处在于，它根本否定“时间管理”这个名词，主张关键不在于时间管理，而在于个人管理。与其着重于时间与事务的安排，不如把重心放在维持产出与产能的平衡上。




* 第二部分 个人的成功：从依赖倒独立第五章 习惯三：要事第一（中）

集大成的时间管理理论
第一代的时间管理理论丝毫没有“优先”的观念。固然每做完备忘录上的一件事，会带给人成就感，可是这种成就不一定符合人生的大目标。因此，所完成的只是必要而非重要的事。
然而好此道者不在少数，因为阻力最少，痛苦与压力也最少。更何况，根据外在要求与规律行事，容易推卸责任。这类经理人缺乏效率，缺乏自制力与自尊。
第二代经理人自制力增强了，能够未雨绸缪，不只是随波逐流，但是对事情仍没有轻重缓急之分。
第三代经理人则大有进步，讲究理清价值观与认定目标。可惜，拘泥于逐日规划行事，视野不够开阔，难免因小失大。第一、三类事务往往占去所有的时间，这是第三代理论最严重的缺失。
不过以上三代理论的演进，仍有可资借鉴的地方。第四代理论便在旧有基础上，开创新局面。以原则为重心，配合个人对使命的认知，兼顾重要性与急迫性；强调产出与产能齐头并进，着重第二类事务的完成。
管理方法六标准
有效的个人管理方法须符合以下标准：
一、一致：个人的理想与使命、角色与目标、工作重点与计划、欲望与自制之间，应和谐一致。
二、平衡：管理方法应有助于生活平衡发展，提醒我们扮演不同的角色，以免忽略了健康、家庭、个人发展等重要的人生层面。有人以为某方面的成功可补偿他方面的遗憾，但那终非长久之计。难道成功的事业可以弥补破碎的婚姻、孱弱的身体或性格上的缺失?
三、有重心：理想的管理方法会鼓励并协助你，着重虽不紧迫却极重要的事。我认为，最有效的方法是以一星期为单位订定计划。一周7天中，每天各有不同的优先标的，但基本上7日一体，相互呼应。如此安排人生，秘诀在于不要就日程表订定优先顺序，应就事件本身的重要性来安排行事历。
四、重人性：个人管理的重点在人，不在事。行事固然要讲求效率，但以原则为重心的人更重视人际关系的得失。因此有效的个人管理偶尔须牺牲效率，迁就人的因素。毕竟日程表的目的在于协助工作推行，并不是要让我们为进度落后而产生内疚感。
五、能变通：管理方法应为人所用，不可一成不变，视个人作风与需要而调整。
六、携带方便：管理工具必须便于携带，随时可供参考修正。
根据实际经验，我设计出一种符合以上诸条件的表格。其实，许多优秀的第三代管理工具，也值得采用，只是实际做法或具体运用因人而异罢了。以下举实例说明如何以原则为重心，建立起充分掌握重点的一周行事历。
个人管理四步骤
有效的个人管理可分为四个步骤：
●确定角色——首先，写下个人认为重要的角色。假若以往不曾认真考虑这个问题，就把这时闪过脑际的角色逐一写下。除了“个人”以外，父母、儿女、职员、老师……凡是你愿意定期投入时间精力的，都可以纳入其中。
不必想得太严肃，仿佛立下终身职志，只须考虑未来一周中应该扮演的角色即可。
请看以下两例，是一般人如何看待他们所扮演的各种角色：
一、个人
二、丈夫/父亲
三、新产品经理
四、研究经理
五、人事经理
六、行政经理
七、公司董事长
一、个人发展
二、妻子
三、母亲
四、房地产推销员
五、主日学老师
六、交响乐团董事
●选择目标——其次，为每个角色订定未来1周欲达成的2至3个重要成果，列入目标栏中(请看表五-2)。
这些短期目标应与使命宣言中的终极目标有所关联，至少有一部分如此。即使不曾写过使命宣言，也可以自己设想每一角色及重要目标。在未来1周的目标中，务必有一些真正重要但不急迫之事。
●安排进度——现在，根据上面所列目标，安排未来7天的行程。比方说，目标之一是完成个人使命宣言初稿，那么不妨在周日抽出连续2个小时完成此事。通常星期日(或一周中对你最有意义或最特殊的一天)，正是思考如何提升自我及规划一周行事的最佳时刻。
再比方，锻炼身体是你的目标，那么不妨安排3至4天，每天运动1小时。
有些目标可能必须在办公时间完成，有些得在全家共聚一堂时实现。
每个目标都可当做某一天的第一要务，更理想的是当做特殊的约会，全力以赴。对本年度或1个月内已定的约会则一一检讨，凡是符合个人目标的加以保留，否则便取消或更改时间。
在表五-2中，一共有19个目标，大致都很重要，分别安排在7天内。左下角的方格是“精益求精”栏，提醒你定期就身体、心智、精神、社会情感四个层面，来检讨追求人生目标后的情况。详情请参阅第十章。
经过一番规划，这张“一周行事历”中，居然还留有不少空白。足以应付突发事件，调整工作日程，建立人际关系，或偷得浮生半日闲。由于一切都在个人掌握之中，便无须瞻前顾后。
●逐日调整——每天早晨依据行事历，安排一天的大小事务。第三代理论强调的逐日计划行事，在此可以派上用场，使事情井然有序，不致因小失大。
从以上的实例，你是否已心领神会这种做法的可贵之处?依据我个人的心得，以及许多人受益的情形，我深信这种做法确实不同凡响。
执行程序
第三个习惯重在身体力行。就仿佛程序设计员设计出程序后，计算机必须加以执行。
顺从别人的意愿，完成他人眼中的要务，或无牵无挂地享受既不紧张又不重要的活动，岂不轻松愉快?至于执行自己依理性原则设计出的程序，则或多或少考验着自制力，此时就得靠诚心正意的修养功夫，坚定意志。
俗语说：“天有不测风云，人有旦夕祸福。”事先安排妥当的行事历，必要时仍须有所更动。只要把握原则，任何调整都心安理得。
我有个儿子，一度对追求效率十分着迷，每天的行程都安排得相当紧凑。到后来，日程表居然已细分到以分钟为单位。记得有那么一天诸事顺利，他依计划洗车、借书……但到了“与女友分手”这一项，事先的计划完全打破。
原本他只安排了10至15分钟打电话，向女友解释一切。没想到，解释了1个半小时，还难以收场，因为女友实在无法接受这突如其来的打击。这再一次证明，对人不可讲效率，对事才可如此。对人应讲效用——即某一行为是否有效。
为人父母者，尤其是母亲，常耗费所有的时间照顾小孩，以致一事无成，备感挫折。但挫折多来自有所期望，而这期望反映的却是社会价值观，不是个人的价值观。若想要克服因社会价值观而产生的内疚感，可以依靠习惯二——以终为始。
第四代个人管理理论的特点，在于承认人比事更重要。而芸芸众生中，首要顾及的便是自己。它比第三代理论高明之处是：强调以原则为重心，以良知为导向，针对个人独有的使命，帮助个人平衡发展生活中的不同角色，并且全盘规划日常生活。




* 第二部分 个人的成功：从依赖倒独立第五章 习惯三：要事第一（下）

　高效能的秘诀——授权
授权是提高效能或效能的秘诀之一，可惜一般人多吝于授权，总觉得不如靠自己更省时省事。
其实把责任分配给其他成熟老练的员工，才有余力从事更高层次的活动。因此，授权
代表成长，不但是个人，也是团体的成长。已故名企业家潘尼(j.c.penney)曾表示，他这一生中最明智的决定就是“放手”。在发现独立难撑大局之后，他毅然决然放手让别人去做，结果造就了无数商店、个人的成长与发展。
由此可见，授权也与公众的成功有关，这一点留待第六章加以讨论。此处专论授权与个人管理技巧的关系。
授权是事必躬亲与管理之间的最大分野。事必躬亲者凡事不假外求。不放心子女、宁可自己洗碗的父母，自绘蓝图的建筑师或自己打字的秘书，都属于这一类。
反之，管理者注重建立制度，然后汇集群力共同完成工作。比如分派子女洗碗的父母，领导一群设计人员的建筑师，或监督其他秘书与行政人员的执行秘书。
假定事必躬亲者花1小时可产生1单位的成果(如图5-7)，那么管理者经由有效的授权，每投入1小时便可产生10倍、50倍，甚至100倍的成果，其中诀窍不过是将杠杆支点向右移而已(如图5-8)。
两种类型的授权
授权依型态可分为两种，一是“下达指令”型，一是“充分信任”型。
下达指令
放不开手的管理者坚持一人独挑大梁，属下惟命是从，意即不做任何决策、不负任何责任。
有一次，我们全家去滑水。擅长滑水的儿子由我驾船拖着滑行，我的妻子负责拍下他的精采动作。起先我叮咛她慎选镜头，因底片所剩不多。后来发现她对相机性能不熟，就频频面授机宜：要等太阳落在船的前方，且儿子表现美妙动作时再按快门。
可是愈担心底片不够或妻子技术欠佳，我愈无法放手让她拍。到最后，演变成我下口令，妻子才按快门。
这就是下达指令型的授权，必须亦步亦趋地监督。这种方式常被采用，但成效如何呢?有多少人能够如此事无巨细地管理属下呢?
充分信任
充分信任型的授权，才是有效的管理之道。这种方式注重的是结果，不是过程。获授权者可自行决定如何完成任务，并对结果负责。起初，也许会比较费时，但绝对值得。
充分信任型授权必须双方对以下事项，有足够的默契与共识：
●预期的成果：管理与被管理的一方须对预期的结果与时限进行沟通，宁可多花时间讨论，确定彼此认知无误。讨论重点在成果，不在手段。
●应遵守的规范：授权有一定的限度，所以必须加以规范，但切忌太多，约束太多。
然而也不可过度放任，以致违背了原则。对可能出现的难题与障碍，应事先告知对方，避免无谓的摸索。
●可用的资源：双方确定可用的人力、物力、财务、技术或其他资源。
●责任的归属：约定考评的标准及次数。
●明确的奖惩：依据考评结果订定赏罚，包括金钱报酬、精神奖励与职务调整等等。
仍以我家为例来说明。有一年，我们开家庭会议，讨论共同的生活目标以及工作分配。会议结果不问可知，因为孩子还小，我与妻子分担了大部分工作。当时年仅7岁的史蒂芬已相当懂事，自愿负责照顾庭院，于是我认真指导他如何做个好园丁。
我指着邻居的院子对他说：“这就是我们希望的院子——绿油油而又整洁。除了上油漆以外，你可以自己想办法使院中充满绿意，用水桶、水管或喷壶浇水都行。”
又为了把我所期望的整洁程度具体化，我俩当场清理了半边的院子，好给他留下深刻的印象。
经过两星期的训练，史蒂芬终于完全接下了这个任务。我们协议一切由他作主，我只在有空时从旁协助。此外，每周两次，他必须带我巡视整个院子，说明工作成果，并自行判断表现成绩。
当时并未谈到零用钱的问题，不过我很乐意付这笔钱。我想，7岁大的孩子应该已有责任感，足以负担这个任务。
那一天是星期六，一连过了3天，史蒂芬毫无动静。星期六才做的决定，我不奢望他立即行动，星期天也不是工作日，可是星期一他依然故我。到星期二，我已经有些按捺不住。不幸的是，下班之后，院内脏乱依旧，史蒂芬却在对街的公园里嬉戏。
我感到极度失望，忍不住想要唤他过来整理院子。这么做可收立竿见影之效，却会给孩子推卸责任的借口。于是我勉为其难忍耐到晚餐用毕，才对他说：“照前几天的约定，你现在带我到院子里，看看工作成绩，好不好?”
才出门他就低下头，过不多久更抽噎地哭起来。
“爸，这好难哟!”
很难?我心里想：你根本什么都没做。不过我也明白，难的是自动自发，于是我说：“需不需要我帮忙呢?”
“你肯吗?爸!”
“我答应过什么?”
“你说有空的时候会帮我。”
“现在我就有空。”
他跑进屋去拿来两个大袋子，一人一个，然后指着一堆垃圾说：“请把那些捡起来好不好?”
我乐于从命，因为他已开始负起照顾这片园地的责任。
那年暑假我总共又帮了两、三次忙，之后他就完全独立作业，悉心照顾一切。甚至哥哥姐姐乱丢纸屑，立刻就会受到指责。他做得比我还好。
信任可以激发最强烈的动机，使人全力以赴，但需要时间与耐心。惟有经过相当的训练与陶冶，才能培养足够的能力，不致有辱使命。
我相信，善于授权可以收事半功倍之效，且对双方都有益处。不过授权者必须真心诚意以管理为出发点，而不是只求效果。比方整理房间，做父母的自然是得心应手。但为了训练子女，就得耐住性子，给他们时间，放手让他们去做，父母只能从旁指导。纵使一时浪费时间，将来却能省掉不少麻烦，这种投资绝对值。至于获授权的人，既拥有自主权，也就无从推委，惟有竭力达成目标，不负所托。
授权的大原则不变，权限却因人而异。对不够成熟的人，目标不必订得太高，指示要详尽，并且充分提供资源；监督考核则较频繁，奖惩也更直接。对成熟的人，可分配挑战性高的任务，精简指示，减少监督考核的次数，考评标准则较为抽象。
成功的授权是有效管理的表征，重要性可想而知。在附录二中有一则实例，说明办公时把握要点可发挥庞大的力量。
?立即行动
一、找出一件一直为你所忽略，但是会对个人或事业产生重大影响的事，写下来作为近期目标。
二、根据表五-1估计自己花在这四类事务上的时间，然后连续3天记录行事历，每15分钟为1单位，验证估计正确与否。你是否满意自己运用时间的方式?有没有应当改弦更张之处?
三、列举可授权的事项及合适的授权对象，并付诸行动。
四、规划下一周的活动，依据不同的角色设定目标，再把目标转换成行动，列入行事历。一周过后，检讨自己是否成功地把人生目标和价值观溶入日常生活，意志是否坚定?
五、下定决心，以后每周固定规划行事历，并选择一定时间来进行。
六、设计合用的表格，可参考本书范例。
七、阅读附录二的实例。
