2020 年信息技术工程系工作要点

2020 年信息技术工程系工作计划要点的总体思路：以习近平新时代中国特色社会主义思想为
指导，深入学习贯彻党的十九大和十九届历次全会、2020 年全国两会、泰安市委十一届十次
全会、市“两会”精神，全面落实习近平总书记关于教育的重要论述、全国全省教育大会及有
关文件精神，以党的建设为引领，以立德树人为根本，以综合改革为动力，以优质校建设为
抓手，以提质培优为主线，以办学治校能力建设为重点，统筹推进管党治党、改革发展和疫
情防控工作，实现学院“十三五”规划圆满收官，充分发挥党支部的战斗堡垒作用和党员先锋
模范作用，确保党中央和上级重大决策部署和部门各项工作要求贯彻落实到位，不断实践改
革创新发展。 

* 一、加强新时代党的建设，纵深推动全面从严治党工作

** 1.落实管党治党责任。
贯彻党的十九大和十九届四中全会精神，增强“四个意识”，坚定“四
个自信”，坚决做到“两个维护”。严格落实《党章》《准则》《条例》《党委（党组）落实
全面从严治党主体责任规定》，落实全省教育系统全面从严治党工作视频会议精神，加强对
全面从严治党工作的组织领导、层层压实责任。定期开会研究推进落实主体责任，把全面从
严治党的要求融入工作日常，做到党建和业务两手抓，两手都要硬，发挥党支部领导核心作
用。制定并落实我系领导班子、第一责任人、班子其他成员责任清单，班子成员经常检查指
导分管领域全面从严治党工作，定期听取情况汇报。

** 2.强化宣传思想政治工作。
把“不忘初心，牢记使命”作为党的建设的永恒课题和党员干部终
身课题，继续推进“两学一做”学习教育常态化制度化。加强习近平新时代中国特色社会主义
思想与形势政策理论宣传教育。深入开展中国梦、社会主义核心价值观、志愿服务等宣教活
动。大力宣扬中国特色社会主义的道路自信、理论自信、制度自信和文化自信，营造健康积
极向上的系部思想文化氛围。贯彻落实全国和省市思想政治工作会议精神，深化理想信念和
形势政策教育，提升师生思想理论水平与教育、学习理念。坚持党支部书记讲思政课制度，
确保习近平新时代中国特色社会主义思想占领高校阵地。

** 3.抓实党组织建设。
抓好党建工作重点任务落实；严格发展党员标准和程序，严格执行发展
党员全程纪实制度，对入党积极分子高标准严要求，做到成熟一个发展一个；创新教育培训
方式，开展党员、入党积极分子经常性教育活动；严格落实主题党日、“三会一课”、组织生
活会、谈心谈话、民主评议党员制度，加强党员日常管理监督；加强党建信息化建设，用好
“灯塔-党建”在线平台；强化党支部考核评价，用好评价结果。

** 4.夯实意识形态主体责任。
落实意识形态工作责任制，扎实推进意识形态工作，认真学习学
院意识形态工作手册，组织系部教职工签订意识形态责任书，定期汇报意识形态领域情况。
坚决抵制和防范校园宗教渗透，做好少数民族学生思想政治工作。严格网站、宣传栏、微信
公众号等宣传阵地管理，加强对新媒体平台的监管与建设，完善网络舆情引导的体制机制，
做好舆情管理与引导，加强思想文化引领，培育健康向上的舆论生态。

** 5.驰而不息抓党风廉政建设。
严格落实党风廉政建设“两个责任”和“一岗双责”责任，支部组
织签订党风廉政建设工作责任书、责任清单和廉政承诺书，切实压紧压实党风廉政建设责任
制。运用好“四种形态”，强化监督执纪问责。严明“六个纪律”，强化警示教育和纪律执行。
对违纪行为、违反师德行为，严肃追究责任。系部开展党支部主要负责人讲廉政党课活动。
严格执行中央八项规定及其实施细则精神、省委实施办法、市委实施细则，坚决纠正工作生
活中不正之风，定期不定期开展自查或监督检查。进一步规范支部党员行为，贯彻落实党员
违反党风廉政建设责任追究的有关规定。

** 7.大力开展文明创建活动。
巩固深化精神文明创建成果。认真执行《2020 年文明城市创建活
动方案》《2020-2021 年度文明校园创建工作方案》等，按照方案统筹协调，全方位开展创
建活动。

* 二、深化教育教学改革，全面提升人才培养质量

** 8.完善专业标准。
 以国家及省颁发的专业教学标准为指导，以依据职业岗位需求及职业资格
 标准，完善系部各类各级专业标准。

**  9.培育优势特色专业。
打造特色专业；优化创新人才培养模式，构建创新型、发展型、复合
 型技术技能人才培养体系。配合学院工作，继续做好 1+X 证书制度试点工作。认真学习《学
 生综合素质评价办法》，做好专升本有关工作。

**  10.提升实训基地内涵。
加强教学做一体化多功能室改造和管理，提高实训室利用率。继续
 实施“分阶段、项目化、协同化”实践教学模式。

**  11.深化教学模式改革。
落实《全面深化教学改革实施方案》，全面推进“动态交互、多元评
 价混合教学模式”改革，以“三位一体”教学平台为基础，以项目化课程改革与有效教学改革
 为载体，以课堂教学应用为重点，应用校内外信息化教学资源，深化“三教”改革。利用现代
 信息技术，对线上课程、线下课程、线上线下混合式课程进行深入的实践探索。继续开展中
 青年教师“五个一”信息化教学达标活动。鼓励教师参加线上线下信息化教学培训，总结形成
 典型案例。

**  12.促进教研活动开展。
做好教学成果奖的申报和成果推广工作；做好常规教学管理工作，
 发挥教研室职能作用，开展教研活动，引导教师研究职业教育和专业教学，切实提高教育教
 学质量。

**  13.持续加强技能大赛工作。
坚持以赛促学、以赛促教、以赛促改，实现专业全覆盖、学生
 全参与，创造性开展“核心技能竞赛月”等竞赛活动。

*  三、切实提升教师专业素质能力，打造专业化师资队伍

14.组织广大教师通过学习，认清形势明确任务，组织党员学习教育方针、教育先进经验、
师德教育有关内容，不断提高广大干部教师思想政治素质和业务素质。要以贯彻《公民道德
建设实施纲要》、《教师职业道德规范》、《学生守则》和礼仪规范为主要内容，增强学校
德育工作方针和实效性；加强对广大教师的法制教育和诚信教育，增强他们的民主法制观念
和社会公德，职业道德和家庭美德意识。

15.突出“师德”教育，教师不仅要教好书，还要育好人，为人师表。采取集中教育与经常性
思想教育相结合，思想教育与行政管理相结合。党支部要关注教职工的思想动态，发现问题，
要及时做工作，解除思想隔阂，充分调动大家的积极性和创造性，使各方面的工作争创一流。
进行塑师德风范，做满意教师活动，全面提高教师师德水平。

16.调动积极因素，做好稳定工作。统一思想、提高认识、团结进取、鼓舞士气工作。围绕
教师专业技术工作的实施，把工作做实、做细，尊重群众民主权益，调动积极因素，做好稳
定人心、稳定教学秩序工作。

2020 年信息技术工程系工作要点
2020 年信息技术工程系工作计划要点的总体思路：以习近平新时代中国特色社会主义思想为指导，深入学习贯彻党的十九大和十九届历次全会、2020 年全国两会、泰安市委十一届十次全会、市“两会”精神，全面落实习近平总书记关于教育的重要论述、全国全省教育大会及有关文件精神，以党的建设为引领，以立德树人为根本，以综合改革为动力，以优质校建设为抓手，以提质培优为主线，以办学治校能力建设为重点，统筹推进管党治党、改革发展和疫情防控工作，实现学院“十三五”规划圆满收官，充分发挥党支部的战斗堡垒作用和党员先锋模范作用，确保党中央和上级重大决策部署和部门各项工作要求贯彻落实到位，不断实践改革创新发展。 
一、加强新时代党的建设，纵深推动全面从严治党工作
1.落实管党治党责任。贯彻党的十九大和十九届四中全会精神，增强“四个意识”，坚定“四个自信”，坚决做到“两个维护”。严格落实《党章》《准则》《条例》《党委（党组）落实全面从严治党主体责任规定》，落实全省教育系统全面从严治党工作视频会议精神，加强对全面从严治党工作的组织领导、层层压实责任。定期开会研究推进落实主体责任，把全面从严治党的要求融入工作日常，做到党建和业务两手抓，两手都要硬，发挥党支部领导核心作用。制定并落实我系领导班子、第一责任人、班子其他成员责任清单，班子成员经常检查指导分管领域全面从严治党工作，定期听取情况汇报。
2.强化宣传思想政治工作。把“不忘初心，牢记使命”作为党的建设的永恒课题和党员干部终身课题，继续推进“两学一做”学习教育常态化制度化。加强习近平新时代中国特色社会主义思想与形势政策理论宣传教育。深入开展中国梦、社会主义核心价值观、志愿服务等宣教活动。大力宣扬中国特色社会主义的道路自信、理论自信、制度自信和文化自信，营造健康积极向上的系部思想文化氛围。贯彻落实全国和省市思想政治工作会议精神，深化理想信念和形势政策教育，提升师生思想理论水平与教育、学习理念。坚持党支部书记讲思政课制度，确保习近平新时代中国特色社会主义思想占领高校阵地。
3.抓实党组织建设。抓好党建工作重点任务落实；严格发展党员标准和程序，严格执行发展党员全程纪实制度，对入党积极分子高标准严要求，做到成熟一个发展一个；创新教育培训方式，开展党员、入党积极分子经常性教育活动；严格落实主题党日、“三会一课”、组织生活会、谈心谈话、民主评议党员制度，加强党员日常管理监督；加强党建信息化建设，用好“灯塔-党建”在线平台；强化党支部考核评价，用好评价结果。
4.夯实意识形态主体责任。落实意识形态工作责任制，扎实推进意识形态工作，认真学习学院意识形态工作手册，组织系部教职工签订意识形态责任书，定期汇报意识形态领域情况。坚决抵制和防范校园宗教渗透，做好少数民族学生思想政治工作。严格网站、宣传栏、微信公众号等宣传阵地管理，加强对新媒体平台的监管与建设，完善网络舆情引导的体制机制，做好舆情管理与引导，加强思想文化引领，培育健康向上的舆论生态。
5.驰而不息抓党风廉政建设。严格落实党风廉政建设“两个责任”和“一岗双责”责任，支部组织签订党风廉政建设工作责任书、责任清单和廉政承诺书，切实压紧压实党风廉政建设责任制。运用好“四种形态”，强化监督执纪问责。严明“六个纪律”，强化警示教育和纪律执行。对违纪行为、违反师德行为，严肃追究责任。系部开展党支部主要负责人讲廉政党课活动。严格执行中央八项规定及其实施细则精神、省委实施办法、市委实施细则，坚决纠正工作生活中不正之风，定期不定期开展自查或监督检查。进一步规范支部党员行为，贯彻落实党员违反党风廉政建设责任追究的有关规定。
6.大力开展文明创建活动。巩固深化精神文明创建成果。认真执行《2020 年文明城市创建活动方案》《2020-2021 年度文明校园创建工作方案》等，按照方案统筹协调，全方位开展创建活动。
二、深化教育教学改革，全面提升人才培养质量
7.完善专业标准。以国家及省颁发的专业教学标准为指导，以依据职业岗位需求及职业资格标准，完善系部各类各级专业标准。
8.培育优势特色专业。打造特色专业；优化创新人才培养模式，构建创新型、发展型、复合型技术技能人才培养体系。配合学院工作，继续做好 1+X 证书制度试点工作。认真学习《学生综合素质评价办法》，做好专升本有关工作。
9.提升实训基地内涵。加强教学做一体化多功能室改造和管理，提高实训室利用率。继续实施“分阶段、项目化、协同化”实践教学模式。
10.深化教学模式改革。落实《全面深化教学改革实施方案》，全面推进“动态交互、多元评价混合教学模式”改革，以“三位一体”教学平台为基础，以项目化课程改革与有效教学改革为载体，以课堂教学应用为重点，应用校内外信息化教学资源，深化“三教”改革。利用现代信息技术，对线上课程、线下课程、线上线下混合式课程进行深入的实践探索。继续开展中青年教师“五个一”信息化教学达标活动。鼓励教师参加线上线下信息化教学培训，总结形成典型案例。
11.促进教研活动开展。做好教学成果奖的申报和成果推广工作；做好常规教学管理工作，发挥教研室职能作用，开展教研活动，引导教师研究职业教育和专业教学，切实提高教育教学质量。
12.持续加强技能大赛工作。坚持以赛促学、以赛促教、以赛促改，实现专业全覆盖、学生全参与，创造性开展“核心技能竞赛月”等竞赛活动。
三、切实提升教师专业素质能力，打造专业化师资队伍
　  13.组织广大教师通过学习，认清形势明确任务，学习教育方针、教育先进经验、师德教育有关内容，不断提高广大干部教师思想政治素质和业务素质。要以贯彻《公民道德建设实施纲要》、《教师职业道德规范》、《学生守则》和礼仪规范为主要内容，增强学校德育工作方针和实效性；加强对广大教师的法制教育和诚信教育，增强他们的民主法制观念和社会公德，职业道德和家庭美德意识。
　　14.突出“师德”教育，教师不仅要教好书，还要育好人，为人师表。采取集中教育与经常性思想教育相结合，思想教育与行政管理相结合。党支部要关注教职工的思想动态，发现问题，要及时做工作，解除思想隔阂，充分调动大家的积极性和创造性，使各方面的工作争创一流。开展师德师风建设月活动，全面提高教师师德水平。
15.调动积极因素，做好稳定工作。形成思想统一、团结协作工作氛围。围绕师生关注热点难点，把工作做实、做细，为师生工作学习排忧解难，保障事业又快又好发展。
