#+TITLE:探讨大数据时代计算机信息处理技术
#+AUTHOR: 泰山职业技术学院 夏乐斋
#+OPTIONS: toc:nil
　摘 要： 随着时代的发展和科学技术的飞速发展，21 世纪呈现出一种新的科学技术形态，
计算机软件技术的应用给人们的生活带来了舒适和质量。数据的存储和应用为社会的发展提
供了效率，在大数据时代，计算机软件技术应该得到进一步的传播和技术的突破，本文将介
绍如何在大数据时代更好地利用计算机软件来实现促进人民生活水平的提高和社会的快速发
展。

关键词：大数据时代；计算机软件技术；应用分析

计算机科学的进步需要时间，而这不是一夜之间就能实现的可以。到为了促进信息技术的技
术加工，我们必须不断地讨论和研究一般来说，大数据以数字方式存储社会发展和日常生活
中的所有信息，这是大多数信息处理的明显特点。与以前的信息处理相比，信息处理速度快
效率高大数据时代的发展极大地促进了我国经济社会的发展，也凸显了计算机科学的发展方
向。同时，我们需要大数据的特征去分析。大数据时代的出现，加速了信息的获取，使生产
生活更加舒适。首先，大数据的收集是广泛的，这为计算机信息的基础设定了新的目标设置，
通过信息存储能力和水平的不断提高，大数据时代的数据处理。

一、大数据时代计算机软件技术的发展概况

科学技术的发展加快了计算机技术的发展进程。在大数据时代，中国大多数企业对自身的发
展都有着清晰的认识。在发展过程中，他们在一定程度上逐步加大了对计算机软件中数据库
和信息数据的研究，为了促进企业的快速发展，同时也为了提高企业的发展水平，以满足软
件技术的发展需要。同时，在大数据时代，我们可以通过人们接收到的海量数据和信息来更
加关注数据，然后通过软件技术对不同的数据进行分析，找到有价值的数据和信息，同时通
过不同的软件技术对重要的信息进行监控，提高企业处理数据和信息的能力，根据数据和信
息的特点，改进数据和信息此外，计算机技术的广泛应用和软件技术的快速发展，将逐步提
高数据处理能力，增加数据处理操作次数。相关调查显示，目前借助软件技术进行数据处理
的数量已超过 10 亿吨，因此，与计算机相关的软件技术研发应在大数据时代背景下改进或
优化自身的技术，以根据目前的发展状况，适应时间的演进，未来计算机软件技术将有更大
的发展空间。因此，我们应该充分利用这项技术，促进社会发展，创造更多的经济效益。

二、计算机软件技术发展现状

计算机软件技术是时代发展的新产物。它一经问世，就迅速占领了世界市场，在互联网上，
大数据的发展也日新月异，互联网用户逐年增加，用户数量也将不断增加。这有利于人们的
生活和商业发展。计算机应用也正在兴起。人们开始学习计算机软件技术，希望成为互联网
时代的一股浪潮，在大数据时代，人们的生活发生了很大的变化。通信、家庭生活、旅游等
有不同的方式和乐趣。社会发展，由大数据技术驱动，计算机软件技术已经广泛应用于社会
的各个方面，发挥着重要的作用和价值，但是，计算机软件技术在安全、应用链反应等方面
的发展还存在一些问题迫使不断突破和改变现状，以求更好地应用计算机软件技术。

三、常用的计算机软件技术分析

　3.1 虚拟化技术

虚拟化技术在大数据时代是必不可少的，虚拟化技术评估海量数据，优化配置，在人们需要
使用数据时提供准确有效的数据，在业务发展方面，通过虚拟化技术对公司各类金融、业务
和投资资产进行分类统计，虚拟化技术在未来需要进一步发展，以更好地促进社会发展。

3.2 云存储技术

云存储技术是大数据时代的一项了不起的工作，而且世界如此之大，信息数万，海量的资源
和数据都受到云存储技术的保护，人们可以通过云存储技术存储大量的信息和资源。如果需
要，可以通过互联网电脑软件进行浏览和应用，非常实用，云存储技术的应用是企业发展和
人民生活的福祉，云存储技术使大量数据有了栖身之地，为人们省去很多麻烦。

3.3 信息安全技术

在大数据时代，人们的数据存储在互联网上，其他人可以通过互联网访问个人数据这个必须
保证信息安全，互联网需要清洁国家信息技术阻碍了人们的信息。通过互联网，人们不能随
意地看到别人的信息。有很多数据。个人有自己的世界。信息技术是大数据时代必不可少的
计算机软件技术，为了保障人们的信息安全，必须长期发展。

四、大数据时代计算机信息处理技术研究

4.1 信息安全技术

在大数据时代，信息是最有价值的资源，谁拥有足够的信息，谁拥有更多的话语权，谁能够
获得更多的资源和市场，各公司必须不断维护信息资源，必须尊重自身信息的安全性和保密
性，在大数据时代，所有类型的资源都被计算机化和数字化，不同信息和数据的信息和通信
它方便了各类通信和传输，也方便了各类信息的非法获取，每个公司都必须注意信息安全的
保护。做好信息安全保护工作是每个企业的重要管理任务，信息系统保护技术的开发和应用，
促进社会信息系统的建立，已成为大数据时代的一项重要任务。

4.2 信息采集和处理技术

在大数据时代，各种各样的数据不断产生，海量的数据每天充斥着互联网，越来越多的企业
需要各种各样的数据和信息，也需要对各种信息进行提炼，才能真正发挥信息价值的作用信
息是信息处理的重要前提，也是大数据时代最重要的任务，做好各种信息采集工作，做好围
绕信息采集的各种技术研发和支持工作是其本质特征信息处理过程是实现大数据信息的重要
保证。有效处理海量信息，满足个性化需求，从中获取更可靠的数据，是大数据时代经济发
展的重要特征，信息技术的研究和发展越来越迫切，竞争也越来越激烈。

4.3 信息存储技术

在大数据时代，数据信息是一种重要的资源。它必须收集所有类型的信息并存储所有类型的
数据，以便随时检索和使用它。这个信息存储占用了很大的空间，必须对信息存储设备进行
不断的检测。一方面，应不断增加信息量，以便存储更好的分类信息。另一方面，为了更好
的可读性和分析，各种存储的数据应该分类。不仅要节约资源，而且要保证各种类型的数据
都能高效、快速地提取出来，这已经成为研究的热点是的，所以例如，分布式存储技术是应
用最广泛的技术。

总结

随着“大数据”时代的到来，各种计算机信息处理技术的应用价值和普及程度得到有效提高，
但也存在着一些应用上的误区和挑战，同时也为技术发展提供了机遇，大数据对社会经济发
展的重要性日益增强，导致了各行业的颠覆性变化。经济一体化、市场竞争日趋激烈，技术
和信息竞争日趋激烈。掌握先进信息处理技术，充分利用大数据技术为管理和决策服务的人
才，将在竞争中立于不败之地。

参考文献：

[1] 王会娥.大数据时代计算机信息处理技术及应用研究[J].现代工业经济和信息化，2018，
8（16）：81-82，108.　

[2]王明宇，戴蔚伯，张世琪.大数据时代的计算机信息处理技术分析[J].电子元器件与信息
技术，2018，2（02）：1-3.

[3] 胡声艳.试谈大数据时代背景下计算机软件技术的应用[J].电脑编程技巧与维护，2018
（11）：104-

