



#+TITLE:  泰山职业技术学院

#+AUTHOR: 信息技术工程系春季开学工作方案（修订)

#+OPTIONS: H:2


* 指导思想

为统筹做好疫情防控和春季学期开学工作，全面打赢疫情防控阻击战，根据《山东省 2020 年
春季学期疫情防控工作指导意见》《山东省高等学校 2020 年春季学期疫情防控工作指导手册》
《山东省高等学校 2020 年春季学期开学工作指南》《山东省高等学校 2020 年春季学期开
学条件核验细则》《山东省高等学校开学工作方案》 及市委指挥部、省教育厅、市教育局
有关文件精神，结合本系实际，制定本方案。

全面贯彻落实习近平总书记关于新冠肺炎疫情防控工作的重要讲话和指示批示精神，按照中
央、省委、市委和上级教育部门关于新冠肺炎疫情防控工作的决策部署，把疫情防控作为压
倒一切的政治任务，进一步完善应急和常态化防控结合的措施与机制，把守护师生安全健康
始终放在首位，把师生为本的理念落实到疫情防控的全过程。强化“疫情就是命令，防控就
是责任”意识，树牢疫情防控“一盘棋”思想，主动谋划、周密部署、科学防控、精准施策，
以对师生极端负责的态度，以决战决胜的坚定决心，严格落实疫情防控和春季学期开学工作
责任，坚决打赢校园疫情防控阻击战，保障师生身体健康和生命安全，维护学院安全稳定，
为夺取疫情防控全面胜利，彰显泰职担当，贡献泰职力量。

* 工作安排

** 日常防控工作

具体职责：

1.建立健全体温检测制度。开学后建立早中晚个人体温检测台账；二是因病缺勤登记及追踪
制度。详细记录和追踪学生缺课原因和去向，确保掌握全体学生动向。

2.保持健康行为习惯。开学后集中进行宿舍、教室、实习实训场地的卫生清洁，勤开窗、常
通风，每次通风 20—30 分钟；宿舍成员不共用毛巾等，保持宿舍、桌椅、卫生间及个人物品
清洁，勤晒衣被；注意营养，适度运动；不要接触、购买、饲养和食用野生动物，尽量避免
到售卖活体动物市场；严禁校园内吸烟。

3.强化防疫宣传。普及防疫基本知识介绍、进出校园管理方法、个人卫生防护方法、学生活
动管理方法、学院防疫宣传材料等方面进行培训和学习。

4.强化个人防护。开学时学生自行准备必需的防疫物品，如餐具、口罩、体温计、消毒液等
个人使用物品，日常做到勤量体温、戴口罩、勤洗手、不随地吐痰。同时学习、谈话、就餐
时不面对面，口罩在吃饭时再摘下，最好使用个人餐具打餐后回宿舍吃饭。快递尽量选择无
接触配送，如必须与快递员接触，应佩戴好口罩，取件途中避免人员聚集及面对面。

5.尽量缩小活动范围。尽量少与人正面交谈，少去人员聚集场所，禁止离开房间和相互探访，
有限度的接触同学或公共物品，做好个人行踪记录。

6.严控外出。因特殊情况（如生病）确实需要外出时，家长与老师联系，学生填写《泰山职
业技术学院学生外出审批表》，经批准后，在做好防疫措施前提下严格按出行路线、方式外
出，同时在规定时间内返回。

7.严格执行疫情期间的“日报告”、“零报告”制度，及时、准确、全面上报疫情情况，杜绝漏
报、瞒报事件发生。

8.完成领导交办的其他工作。
** 应急处置工作
1.强化应急处置工作组织领导。成立新型冠状病毒感染的肺炎防控工作领导小组。

2.学生管理组负责各系组织辅导员（班主任）提前联系每名学生，再次确认学
生健康状况，通知具体返校时间，告知入校体温监测位置和应急处置程序，提醒返程和报到
注意事项，指导做好个人防护，要求自备口罩并每天随身携带。
学生管理组组织当天返校学生的辅导员（班主任）在返校入口
迎接学生，提醒学生佩戴口罩、有序排队，相互间隔 2 米；
健康监测组依次检测体温；健康监测组
发现体温高于 37.3℃的学生，辅导员（班主任）配合留观转诊组和安全保卫组立即将体温异
常人员引领至返校入口临时留观点，并陪护安抚学生。

3.开学后健康监测异常。如体温异常人员为学生，学生应及时联系辅导员（班主任）。场
地组织工作人员登记在场人员个人信息后，继续开展体温检测工作，引导师生员工有序进出。
留观转诊组穿戴防护套装到达现场，对体温异常人员重测体温，确认体温异常后，启动应急
处置，并报告校区负责人。辅导员（班主任）接到学生电话后，第一时间穿戴防护套装赶赴
现场，配合做好相关工作。 

4.开学后自测（自感）异常 。一是宿舍内自测（自感）异常。学生每天早晚各自测体温 1 次，
及时上报辅导员（班主任），信息计入健康台账。学生自测体温高于 37.3℃或出现咳嗽、乏
力以及腹泻、结膜充血等可疑症状，立即佩戴口罩，并报告辅导员（班主任）。辅导员报告
所在系部负责人，并穿戴防护套装赶到宿舍，陪护安抚学生，告知宿舍内其他学生暂时在宿
舍等待并尽量相互远离，同时通知同一楼层其他宿舍学生闭门休息或登记个人信息后正常外
出上课。系部负责人通知留观转诊组穿戴防护套装到达现场，对体温异常人员重测体温，确
认体温异常后，启动应急处置，并报告学院负责人。教职员工自测或自感不适的，参考执行
上述流程。二是人员聚集性场所自感异常。学生在教室、实验室、图书馆、食堂等人员聚集
性场所内自感不适，立即报告辅导员（班主任）。辅导员（班主任）报告所在系部负责人和
学生所在场所工作人员，并穿戴防护套装赶赴现场,引导学生至临时留观点等候。系部负责
人通知留观转诊组穿戴防护套装到达现场，对自感异常人员检测体温，确认体温异常后，启
动应急处置，并报告学院负责人。场所负责人员赶赴现场，组织登记同一场所人员个人信息。
如在食堂，应登记周边 5 米内餐桌就餐人员和各窗口工作人员信息。教职员工在公共场所自
感不适的，参考执行上述流程。 

5.应急处置流程。按学校规定程序处理
** 教育教学工作
1.做好线上线下课程衔接工作。按照《泰山职业技术学院关于 2019-2020 学年寒假延期后的
教学安排方案》《泰山职业技术学院“网络课堂”线上教学服务工作方案》《关于进一步做好
2019-2020 学年第 2 学期教学工作的通知》《关于做好“网络课堂”助教工作的通知》《关于做
好“网络课堂”督导管理和毕业生顶岗实习工作的通知》等工作要求，摸清各专业课程开课情
况和教学进度，有条不紊的推进线上线下课程衔接工作。（1）科学调整教学计划和教学安
排。各教学系部要在坚持执行专业人才培养方案和课程标准的基础上，有针对性地调整授课
计划及教学时间，优化教学方式。合理把握教学进度，做到教学内容适量、教学时长适当，
提高课堂教学效率。针对 2021 届毕业生即将进入顶岗实习阶段的特殊情况，要及时调整相关
课程的教学安排，加强授课计划和教学进度的针对性和实效性，有序安排好相关课程的教学
活动，保证实践教学学时，确保教学质量不打折。（2）精准做好线上线下课程衔接。根据
《泰山职业技术学院 2020 年春季学期返校后学业检测及教学衔接计划》的工作安排，各教学
系部要对延期开学期间学生的线上、居家学习情况进行摸底和诊断，做好教学评估，精准分
析学情。没有开展新课程线上教学的，应实施“零起点”教学；已开展新课程线上教学的，要
认真进行串讲复习，在确保每名学生都能较好地掌握所学知识的基础上，再进行新课程教学。
各教学系部应帮助学生做好由线上学习到返校学习的心理调节，消除因疫情带来的焦虑、急
躁情绪，帮助师生尽快调整好状态，以健康乐观的心态和积极向上的精神面貌投入教学工作
和学习生活。（3）关爱特殊学生群体，加强保学工作。开课前，学院组织各教学系部对学
生的学习条件情况进行了提前摸底，主要针对是否有存在网络不通或手机、电脑设备不够的
情况进行排查。经过摸排，学院共有 12 名同学因为家庭经济条件、区域网络条件的影响，而
无法使用网络或电脑进行网络学习。相关教学系部开学后要精准对接此类学生进行补课，确
保有困难、学习效果不佳的学生正常完成学习任务。

2.做好学业检测工作。按照《泰山职业技术学院 2020 年春季学期返校后学业检测及教学衔接
计划》的要求，各教学系部制定切实可行的《学业检测工作计划》，科学、公正的做好学业
检测工作，摸清学生线上的真实学习情况。

3.开展“开学第一课”活动。各教学系部要精心组织，上好开学第一课。做好思想政治宣传教
育，全面开展师生心理疏导工作和疫情防控专题教育。（1）利用开学第一课，普遍开展战
“疫”专题教育。充分用好疫情防控形成的宝贵教育资源，认真组织开展以“敬畏生命，爱国
励志”为主题的战“疫”专题教育，增强学生社会责任感和奉献精神；加强爱国主义和民族精
神教育，增强学生家国情怀和民族自豪感。（2）加强防疫知识和生命、健康教育，将公共
卫生安全教育贯穿于日常教育之中，结合季节性、突发性传染病及食物中毒的预防，安排必
要的课时，进行相应的健康教育，提高学生的健康意识和自我保护能力。

4.做好实习学生的管理工作。要按照《关于做好疫情防控期间实习实训管理工作的通
知》，认真进行实习学生的疫情排查，每天对实习人数、实习地点、实习疫情进行“日报告”。

5.做好开学后课堂教学工作。统筹安排返校后课堂教学，根据教室数量、容量大小等因素，
多班次、多批次安排线下教学，上课是教师与学生、学生与学生之间距离须保持 1 米以上。
尽可能实施小班教学、同楼层隔房间安排教学班、错时上下课，避免师生进出教学楼、实训
楼等场所出现人流高峰。

6.完成领导交办的其他工作。
** 学生管理工作

具体职责：

1.做好开学前的排查统计。通过各种渠道向学生和家长宣传普及疫情防治知识和防控要求，
制发“致学生及家长一封信”、开设“开学第一课”；通过《寒假学生动态统计表》收集有无从
疫区返回、与疫区人员接触和有无发烧、干咳、乏力等症状的相关信息，建立信息动态管理
制度，实时掌握学生健康信息。做好六类人员和境外人员排查、摸底工作。细化开学工作要
求和流程，组织师生认真学习学院应急处置预案。

2.建立自检自查自记录制度。按照工作要求，指导学生严格做好健康自检，对每日健康状况
进行详实记录，时间自返校当日算起前推不低于 15 天，并由监护人落实监督义务，返校时，
有家长提供学生近 15 天的身体健康状况证明并签字，学生须持有效期内健康通行卡(码)返校。
任何学生不得擅自提前返回学校。

3.制定《错峰返校安排表》，严格按照《山东省高等学校 2020 年春季学期开学工作指南》
关于开学返校要求，安全有序、错时错峰组织好开学返校工作。学生返校后，严格实行学生
公寓封闭管理措施，凭学生证实名验证、测温和查看健康通行卡（码）进出。坚持每天健康
自检和特情上报，本着“早发现、早报告、早隔离、早治疗”的原则，一旦发现有任何疑似新
冠肺炎症状的学生，立即上报并进行隔离观察。

4.心理咨询专业人员通过电话网络进行谈心谈话和心理疏导，全力做好学生健康辅导。
5.落实国家资助政策，帮扶疫情期间困难学生，关注学生学业、生活。
6.完成领导交办的其他工作。
* 工作要求

** 提高站位，全面深化疫情防控认识

 切实提高政治站位，把思想和行动统一到习近平总书记关于新冠肺炎疫情防控工作的重要指
 示精神，中央、省委、市委和上级教育部门的决策部署上来，充分认识当前疫情防控工作及
 学校开学条件核验工作的极端重要性、严峻性、紧迫性、复杂性，以高度自觉的大局意识，
 坚决落实各项防控措施，履好职、担起责，全力以赴，科学有效、稳妥有序做好疫情防控及
 开学工作。
**  加强领导，实而又实抓好责任落实

 疫情处置工作领导小组全面负责疫情防控工作，切实发挥牵头抓总、统筹协调作用，靠前指
 挥、加强指导监督，及时掌握疫情，及时发现问题、解决问题。引导基层党组织和党员发挥
 战斗堡垒作用和先锋模范作用，让党旗在疫情防控一线高高飘扬。各系部处室要强化防控主
 体责任，做深做细疫情防控各项工作，把各项防控措施做实、做细、做到位，做到条件检验
 合格后开学。 

 根据我省统一发布的最早开学时间，经泰安市疫情处置工作领导小组批准，确定具体开学返
 校时间，提前通知师生员工，安排师生错时错峰返校。
**  群防群控，形成抗“疫”工作合力

 统筹做好疫情防控和 2020 年春季学期开学工作，要全院动员、全员参与、全力抗“疫”，各
 部门要密切配合，通力合作，统筹做好师生情况全面摸排、教育教学安排、全员培训演练、
 疫情防控物资准备、场所设施消毒、校园安全稳定、舆情管控等工作，教育引导师生员工及
 家长全面掌握防控要求、配合做好开学工作。通过适当形式向社会公布开学工作流程和防控
 要求。从人、财、物等各方面为疫情防控和 2020 年春季学期开学工作做好充分保障，形成
 疫情防控生动局面，确保广大师生生命安全和身体健康。

    信息技术工程系     
 
   2020 年 5 月 9 日 
*   突发新冠肺炎疫情应急处置预案（修订）
**  组织机构设立及职责

  为进一步加强新型冠状病毒肺炎疫情防控工作的领导，更好地保障全体师生的生命安全和身
  体健康，根据上级要求，结合学院开学前后工作实际，决定对学院新型冠状病毒肺炎疫情防
  控工作领导小组调整为新型冠状病毒肺炎疫情处置工作领导小组，统一指挥协调全院新型冠
  状病毒肺炎防控工作。

  组      长：夏乐斋
  副组长：陈振超 李倩 王树兵
  成员：辅导员、班主任及任课教师
** 领导小组下设三个专项工作组
   CLOSED: [2020-05-18 Mon 15:19]
  1.消毒组：乔孟平：安排落实检查每天教室、实训室及宿舍等场所消毒工作。
  2.健康监测组：陈振超、王树兵及辅导员、班主任。做好职工及学生健康监测上报。
  3.教学工作组：李倩及课教师：做好教学及场所防控及应急处置工作

  辅导员（班主任）建立学生健康台账，负责统计、报告每名学生返校时间、每日健康状况等
  信息，保持 24 小时联络畅通。发动学生党员、干部和志愿者在做好个人防护基础上协助开
  展应急处置有关工作。
  领导小组成员，保障 24 小时联络畅通。
**    应急处置启动
***   开学返校体温监测异常 
   1.学生管理组组织当天返校学生的辅导员（班主任）在返校入口迎接学生，提醒学生佩戴口
   罩、有序排队，相互间隔 2 米；健康监测组依次检测体温；安全保卫组负责维持秩序，适
   时引流、控制好人流量，同时加强周边交通安全管理。 

   2.健康监测组发现体温高于 37.3℃的学生，辅导员（班主任）配合留观转诊组和安全保卫组
   立即将体温异常人员引领至返校入口临时留观点，并陪护安抚学生。健康监测组继续进行体
   温检测，确保学生有序返校。 

   3.在临时留观点，留观转诊组对体温异常人员重测体温，确认体温异常后，启动突发疫情应
   急处置。同时，报告学院疫情处置负责人。 

   4.报到期间，发现有未按时报到的学生，辅导员（班主任）要及时电话联系。如了解到有自
   测（自感）体温异常或不适，立即询问学生目前所在位置，安抚学生并告知应对措施，同时
   第一时间报告系部负责人、学院负责人，根据不同情况，采取相应措施。 
*** 开学后健康监测异常 

   1.工作人员检测到体温高于 37.3℃的师生员工，立即引导他们前往临时留观点等候，并在旁
   陪护安抚，同时报告所在场所联络员通知留观转诊组。如体温异常人员为学生，学生应及时
   联系辅导员（班主任）。场地组织工作人员登记在场人员个人信息后，继续开展体温检测工
   作，引导师生员工有序进出。 

   2.留观转诊组穿戴防护套装到达现场，对体温异常人员重测体温，确认体温异常后，启动应
   急处置，并报告校区负责人。辅导员（班主任）接到学生电话后，第一时间穿戴防护套装赶
   赴现场，配合做好相关工作。 
*** 开学后自测（自感）异常 
   1.宿舍内自测（自感）异常 
   （1）学生每天早晚各自测体温 1 次，及时上报辅导员（班主任），信息计入健康台账。 
   （2）学生自测体温高于 37.3℃或出现咳嗽、乏力以及腹泻、结膜充血等可疑症状，立即佩
   戴口罩，并报告辅导员（班主任）。 

   （3）辅导员报告所在系部负责人，并穿戴防护套装赶到宿舍，陪护安抚学生，告知宿舍内
   其他学生暂时在宿舍等待并尽量相互远离，同时通知同一楼层其他宿舍学生闭门休息或登记
   个人信息后正常外出上课。 

   （4）系部负责人通知留观转诊组穿戴防护套装到达现场，对体温异常人员重测体温，确认
   体温异常后，启动应急处置，并报告学院负责人。 

   （5）教职员工自测或自感不适的，参考执行上述流程。
   2.人员聚集性场所自感异常 
   （1）学生在教室、实验室、图书馆、食堂等人员聚集性场所内自感不适，立即报告辅导员（班主任）。 
   （2）辅导员（班主任）报告所在系部负责人和学生所在场所工作人员，并穿戴防护套装赶
   赴现场,引导学生至临时留观点等候。
 
   （3）系部负责人通知留观转诊组穿戴防护套装到达现场，对自感异常人员检测体温，确认
   体温异常后，启动应急处置，并报告学院负责人。 

   （4）场所负责人员赶赴现场，组织登记同一场所人员个人信息。如在食堂，应登记周边 5
   米内餐桌就餐人员和各窗口工作人员信息。 

   （5）教职员工在公共场所自感不适的，参考执行上述流程。 
** 应急处置流程 参照学校手册执行 
***   定点医院：    泰安市中心医院四院
   联系人：      赵正华     
   联系电话：    0538-5395315
   核酸检验医院：泰安市中心医院四院
   联系人：      王永刚
   联系电话：    13561786908
***   泰山职业技术学院疫情防控顾问
   王方明；联系电话 15153876386
** 泰山职业技术学院临时留观室工作制度
*** 临时留观对象工作要求
   1.各系部在校内一旦发现疫情对象时，应立即通知学校分管领导;
   2.对可疑病例以及早期症状者，应立即带入留观室;
   3.凡与可疑病例有过密切接触者，应进行医学观察，对其行动轨迹、场所按要求进行消毒。
***  个人防护要求
   1.进入留观场所及房间的工作人员采取防护措施，穿戴防护服，护目镜，医用外科手套。戴
   医用外科口罩，每 4 小时更换 1 次或感潮湿时更换。

   2.每次接触留观对象后及时更换手套并进行手部卫生清洗消毒。
*** 值守人员要求
   1.值守人员在疫情期间 24 小时在岗并做好值守记录，备好各系部相关学生、家长、老师等
   联络信息存档工作，以备急需。

   2.从接到系部老师、行政疫情报告及处置信息开始，直至疫情疑似对象进入隔离留观室，等
   待医院疫情“120”专车未到时段，学校在各环节，值守人员应该尽职尽责、密切配合，对值
   守不在岗，造成疫情事件人员将严肃追究其职责

   3.要求处置合理，按“早发现、早隔离、早治疗、早处置”的有效防控机制，为快速切断传染
   源、快速扼杀病毒的传播途径而快速对接医院接送，以达立诊立医。

   4.严格执行疫情报告制度，做到不误报、不延报、不瞒报。
** 常见消毒剂及配制使用
  1.含氯消毒液(有效氯 5%):常规按消毒液:水为 1:100 稀释后即为有效氯 500mg/L (以此类
  推)。

  2.其他消毒剂按产品标签标识以杀灭肠道致病菌的浓度进行配制和使用。
** 严格对隔离的场所和设施消毒要求
*** 日常消毒方法
   1.水银体温计需一人一用，用后需用 75%的酒精浸泡 30 分钟（水银体温计、体温计套一同
   浸泡）用干净纱布或消毒纸巾擦干后装入体温计套备用。

   2.对留观室每天湿式清扫，对桌椅、门把手、台面等物体表面进行消毒时，可选用清洗、擦
   拭、喷雾的方法。一般选择含氯消毒剂，浓度为 500mg/L~ 1000mg/L，作用时间 30 分钟。

   3.留观人员产生的生活垃圾均放入垃圾桶，每天清理，清理前用含有效氯 2000mg/L 的含氯
   消毒液喷洒或浇洒垃圾至完全湿润，然后扎紧塑料袋口，统一收集处理。

   4.呕吐物、分泌物可采用加盖容器收集，用 5%的含氯消毒剂按 1:3 直接覆盖或者浸泡 ，
   可用普通矿泉水瓶（500ml)取 1.5L 水（3瓶）倒入水盆中再加一瓶 84 消毒液混合后使用。
   如呕吐物、分泌物等污染物直接污染地面，可用 5%的含氯消毒剂浸泡的抹布直接覆盖包裹
   污染物，作用 30 分钟后清除，同时用有效氯 5000mg/L 的含氯消毒剂的擦(拖)布擦(拖)拭
   可能接触到呕吐物的物体表面及其周围 (消毒范围为呕吐物周围 2 米，建议擦拭 2 遍)。

   5.日常的织物(如毛巾、衣物、被罩等) 250mg/L~ 500mg/L 的含氯消毒剂浸泡 1h 后常规清
   洗。
*** 终末消毒

   隔离留观者转移至医院隔离后,组织对留观室进行全面彻底的终末消毒可用有效氯为
   1000mg/L 的含氯消毒剂溶液喷洒，并用紫外线灯光照 1 小时。

** 联系电话：
 座机：8628131（内线 88131）,8628055（内线 88055）
  手机：夏老师：15698128816（内线 88816）
** 学院疫情防控专题网站
  http://www.mtotc.com.cn/yiqingfangkong/
** 市教育局新型冠状病毒肺炎疫情工作领导小组办公室电话
  李化友：13583856382
  高校工委电话
  座机：6297856
  张士龙：13515389688



信息技术工程系

2020 年 5 月
